Repository googleapis/google-cloud-dotnet, pull requests merged in 2019-06, with the labels that each got.

#3100 Release Spanner libraries version 2.0
  apis/Google.Cloud.EntityFrameworkCore.Spanner/Google.Cloud.EntityFrameworkCore.Spanner/Google.Cloud.EntityFrameworkCore.Spanner.csproj
  apis/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1.csproj
  apis/Google.Cloud.Spanner.Admin.Instance.V1/Google.Cloud.Spanner.Admin.Instance.V1/Google.Cloud.Spanner.Admin.Instance.V1.csproj
  apis/Google.Cloud.Spanner.Common.V1/Google.Cloud.Spanner.Common.V1/Google.Cloud.Spanner.Common.V1.csproj
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.csproj
  apis/Google.Cloud.Spanner.Data/docs/history.md
  apis/Google.Cloud.Spanner.Data/docs/migration-to-2.md
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1.csproj
  apis/apis.json
Labels: cla: yes

#3104 Add curly braces to conform to our normal practice
  apis/Google.Cloud.Logging.NLog/Google.Cloud.Logging.NLog/GoogleStackdriverTarget.cs
Labels: cla: yes

#3105 Release Video Intelligence V1 version 1.0.0-beta04
  apis/Google.Cloud.VideoIntelligence.V1/Google.Cloud.VideoIntelligence.V1/Google.Cloud.VideoIntelligence.V1.csproj
  apis/apis.json
Labels: cla: yes

#3103 Pattern Conversions in Log4Net custom labels
  apis/Google.Cloud.Logging.Log4Net/Google.Cloud.Logging.Log4Net.Tests/Log4NetTest.cs
  apis/Google.Cloud.Logging.Log4Net/Google.Cloud.Logging.Log4Net/GoogleStackdriverAppender.cs
  apis/Google.Cloud.Logging.Log4Net/Google.Cloud.Logging.Log4Net/GoogleStackdriverAppender_Configuration.cs
Labels: cla: yes

#3109 Release new beta of Grafeas.V1 and ContainerAnalysis.V1
  apis/Google.Cloud.DevTools.ContainerAnalysis.V1/Google.Cloud.DevTools.ContainerAnalysis.V1/Google.Cloud.DevTools.ContainerAnalysis.V1.csproj
  apis/Grafeas.V1/Grafeas.V1/Grafeas.V1.csproj
  apis/apis.json
Labels: cla: yes

#3088 GoogleStackdriverTarget - Avoid InvalidCastException for custom IConvertible
  apis/Google.Cloud.Logging.NLog/Google.Cloud.Logging.NLog.Tests/GoogleStackdriverTargetTest.cs
  apis/Google.Cloud.Logging.NLog/Google.Cloud.Logging.NLog/GoogleStackdriverTarget.cs
Labels: cla: yes, needs work

#3115 GoogleStackdriverTarget - Include ServiceContext by default
  apis/Google.Cloud.Logging.NLog/Google.Cloud.Logging.NLog/GoogleStackdriverTarget.cs
  apis/Google.Cloud.Logging.NLog/Google.Cloud.Logging.NLog/GoogleStackdriverTarget_Configuration.cs
Labels: cla: yes

#3118 Beta release of nlog and log4net stackdriver providers
  apis/Google.Cloud.Logging.Log4Net/Google.Cloud.Logging.Log4Net.IntegrationTests/Google.Cloud.Logging.Log4Net.IntegrationTests.csproj
  apis/Google.Cloud.Logging.Log4Net/Google.Cloud.Logging.Log4Net.Snippets/Google.Cloud.Logging.Log4Net.Snippets.csproj
  apis/Google.Cloud.Logging.Log4Net/Google.Cloud.Logging.Log4Net.Tests/Google.Cloud.Logging.Log4Net.Tests.csproj
  apis/Google.Cloud.Logging.Log4Net/Google.Cloud.Logging.Log4Net/Google.Cloud.Logging.Log4Net.csproj
  apis/Google.Cloud.Logging.NLog/Google.Cloud.Logging.NLog.IntegrationTests/Google.Cloud.Logging.NLog.IntegrationTests.csproj
  apis/Google.Cloud.Logging.NLog/Google.Cloud.Logging.NLog.Snippets/Google.Cloud.Logging.NLog.Snippets.csproj
  apis/Google.Cloud.Logging.NLog/Google.Cloud.Logging.NLog.Tests/Google.Cloud.Logging.NLog.Tests.csproj
  apis/Google.Cloud.Logging.NLog/Google.Cloud.Logging.NLog/Google.Cloud.Logging.NLog.csproj
  apis/apis.json
Labels: cla: yes

#3119 Beta releases for Speech and Firestore
  apis/Google.Cloud.Firestore.V1/Google.Cloud.Firestore.V1/Google.Cloud.Firestore.V1.csproj
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore.IntegrationTests/Google.Cloud.Firestore.IntegrationTests.csproj
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore.Snippets/Google.Cloud.Firestore.Snippets.csproj
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore.Tests/Google.Cloud.Firestore.Tests.csproj
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore/Google.Cloud.Firestore.csproj
  apis/Google.Cloud.Speech.V1/Google.Cloud.Speech.V1/Google.Cloud.Speech.V1.csproj
  apis/Google.Cloud.Speech.V1P1Beta1/Google.Cloud.Speech.V1P1Beta1/Google.Cloud.Speech.V1P1Beta1.csproj
  apis/apis.json
Labels: cla: yes

#3099 Pubsub client ordering-keys
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1.OrderingKeyTester/Google.Cloud.PubSub.V1.OrderingKeyTester.csproj
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1.OrderingKeyTester/Program.cs
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1.Tests/PublisherClientTest.cs
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1.Tests/SubscriberClientTest.cs
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1.sln
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/OrderingKeyInErrorStateException.cs
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/PublisherClient.cs
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/SubscriberClient.cs
Labels: :rotating_light:, cla: yes

#3120 Minor fix in pubsub
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/PublisherClient.cs
Labels: cla: yes

#3122 Disable the ordering-keys feature in publisher
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1.OrderingKeyTester/Google.Cloud.PubSub.V1.OrderingKeyTester.csproj
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/AssemblyInfo.cs
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/PublisherClient.cs
Labels: cla: yes

#3123 Release pubsub v1.1.0-beta03
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1.csproj
  apis/apis.json
Labels: cla: yes

#3125 GoogleStackdriverTarget - Docs for ServiceContextName
  apis/Google.Cloud.Logging.NLog/Google.Cloud.Logging.NLog/readme.md
Labels: cla: yes

#3129 Provide a Dialogflow webhook example for ASP.NET classic
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2.Snippets/AgentsClientSnippets.cs
  apis/Google.Cloud.Dialogflow.V2/docs/index.md
Labels: cla: yes

#3133 Fix error in handling non-ordered batch errors
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/PublisherClient.cs
Labels: cla: yes

#3132 Prepare for uploading documentation to googleapis.dev
  .kokoro/release.sh
  uploaddocs.sh
Labels: cla: yes

#3134 Pubsub release v1.1.0-beta04
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1.csproj
  apis/apis.json
Labels: cla: yes

#3137 Fix release process
  .kokoro/release.sh
Labels: cla: yes

#3138 Update Storage dependency
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.IntegrationTests/Google.Cloud.Storage.V1.IntegrationTests.csproj
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.Snippets/Google.Cloud.Storage.V1.Snippets.csproj
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.Tests/Google.Cloud.Storage.V1.Tests.csproj
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.csproj
  apis/apis.json
Labels: cla: yes

#3139 Update the FAQ with guidance for credentials in gRPC APIs
  docs/root/faq.md
Labels: cla: yes

#3141 Regenerate KMS for new features including import jobs
  apis/Google.Cloud.Kms.V1/Google.Cloud.Kms.V1.Snippets/KeyManagementServiceClientSnippets.g.cs
  apis/Google.Cloud.Kms.V1/Google.Cloud.Kms.V1.Tests/KeyManagementServiceClientTest.g.cs
  apis/Google.Cloud.Kms.V1/Google.Cloud.Kms.V1/KeyManagementServiceClient.cs
  apis/Google.Cloud.Kms.V1/Google.Cloud.Kms.V1/ResourceNames.cs
  apis/Google.Cloud.Kms.V1/Google.Cloud.Kms.V1/Resources.cs
  apis/Google.Cloud.Kms.V1/Google.Cloud.Kms.V1/Service.cs
  apis/Google.Cloud.Kms.V1/Google.Cloud.Kms.V1/ServiceGrpc.cs
Labels: cla: yes

#3142 New releases (all betas, with client builder support):
  apis/Google.Cloud.BigQuery.DataTransfer.V1/Google.Cloud.BigQuery.DataTransfer.V1/Google.Cloud.BigQuery.DataTransfer.V1.csproj
  apis/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2.csproj
  apis/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2.csproj
  apis/Google.Cloud.Bigtable.Common.V2/Google.Cloud.Bigtable.Common.V2/Google.Cloud.Bigtable.Common.V2.csproj
  apis/Google.Cloud.DevTools.ContainerAnalysis.V1/Google.Cloud.DevTools.ContainerAnalysis.V1/Google.Cloud.DevTools.ContainerAnalysis.V1.csproj
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2.csproj
  apis/Google.Cloud.Kms.V1/Google.Cloud.Kms.V1/Google.Cloud.Kms.V1.csproj
  apis/Google.Cloud.Language.V1/Google.Cloud.Language.V1/Google.Cloud.Language.V1.csproj
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.csproj
  apis/Google.Cloud.Tasks.V2/Google.Cloud.Tasks.V2/Google.Cloud.Tasks.V2.csproj
  apis/Google.Cloud.Translation.V2/Google.Cloud.Translation.V2/Google.Cloud.Translation.V2.csproj
  apis/Google.Cloud.VideoIntelligence.V1/Google.Cloud.VideoIntelligence.V1/Google.Cloud.VideoIntelligence.V1.csproj
  apis/Google.Cloud.Vision.V1/Google.Cloud.Vision.V1/Google.Cloud.Vision.V1.csproj
  apis/Grafeas.V1/Grafeas.V1/Grafeas.V1.csproj
  apis/apis.json
Labels: cla: yes

#3143 Fix release build script
  .kokoro/release.sh
  buildrelease.sh
Labels: cla: yes

#3144 Create a new release of Google.Cloud.Tasks.V2Beta3
  apis/Google.Cloud.Tasks.V2Beta3/Google.Cloud.Tasks.V2Beta3/Google.Cloud.Tasks.V2Beta3.csproj
  apis/apis.json
Labels: cla: yes

#3147 Remove attempted fix for docuploader
  uploaddocs.sh
Labels: cla: yes

#3151 Introduce new attribute to populate the Firestore document ID on deserialization
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore.Tests/Converters/AttributedIdAssignerTest.cs
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore.Tests/DocumentSnapshotTest.cs
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore/Converters/AttributedIdAssigner.cs
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore/Converters/AttributedTypeConverter.cs
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore/DocumentSnapshot.cs
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore/FirestoreDocumentIdAttribute.cs
Labels: cla: yes

#3159 Refactoring to introduce a DeserializationContext type.
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore.Benchmarks/ValueDeserializerBenchmark.cs
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore.Tests/Converters/AttributedTypeConverterTest.cs
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore.Tests/Converters/CustomConverterTest.cs
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore.Tests/SerializationTestData.cs
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore.Tests/ValueDeserializerTest.cs
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore/Converters/ArrayConverter.cs
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore/Converters/AttributedTypeConverter.cs
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore/Converters/ConverterBase.cs
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore/Converters/CustomConverter.cs
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore/Converters/DictionaryConverter.cs
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore/Converters/EnumConverter.cs
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore/Converters/IFirestoreInternalConverter.cs
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore/Converters/ListConverter.cs
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore/Converters/SimpleConverters.cs
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore/DeserializationContext.cs
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore/DocumentSnapshot.cs
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore/ValueDeserializer.cs
Labels: cla: yes

#3062 Integration test for #3061
  apis/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2.IntegrationTests/QueryTest.cs
Labels: cla: yes

#3162 Use the cross-language test bucket for unauthenticated access listing
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.IntegrationTests/UnauthenticatedAccessTest.cs
Labels: cla: yes

#3163 Add documentation for FirestoreDocumentId
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore.Snippets/DataModelSnippets.cs
  apis/Google.Cloud.Firestore/docs/datamodel.md
Labels: cla: yes

#3171 Clarify PollUntilCompleted documentation
  apis/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2/BigQueryJob.cs
Labels: cla: yes

#3173 Add a base URL for xrefmap.yml
  uploaddocs.sh
Labels: cla: yes

#3172 Add a FAQ entry for repeated fields and maps
  docs/root/faq.md
  tools/Google.Cloud.Docs.Snippets/FaqSnippets.cs
  tools/Google.Cloud.Docs.Snippets/Google.Cloud.Docs.Snippets.csproj
  tools/Google.Cloud.Tools.sln
Labels: cla: yes

#3175 Skip flaky test
  apis/Google.Cloud.Vision.V1/Google.Cloud.Vision.V1.Snippets/ImageAnnotatorClientSnippets.cs
Labels: cla: yes
