Repository googleapis/google-cloud-dotnet, pull requests merged in 2020-10, with the labels that each got.

#5386 [apis/Google.Cloud.Talent.V4] feat: Remove commute methods from Job Search v4 API
  apis/Google.Cloud.Talent.V4/Google.Cloud.Talent.V4/Common.cs
  apis/Google.Cloud.Talent.V4/Google.Cloud.Talent.V4/Company.cs
  apis/Google.Cloud.Talent.V4/Google.Cloud.Talent.V4/CompanyService.cs
  apis/Google.Cloud.Talent.V4/Google.Cloud.Talent.V4/CompanyServiceClient.g.cs
  apis/Google.Cloud.Talent.V4/Google.Cloud.Talent.V4/CompletionService.cs
  apis/Google.Cloud.Talent.V4/Google.Cloud.Talent.V4/Event.cs
  apis/Google.Cloud.Talent.V4/Google.Cloud.Talent.V4/EventService.cs
  apis/Google.Cloud.Talent.V4/Google.Cloud.Talent.V4/EventServiceClient.g.cs
  apis/Google.Cloud.Talent.V4/Google.Cloud.Talent.V4/Filters.cs
  apis/Google.Cloud.Talent.V4/Google.Cloud.Talent.V4/Histogram.cs
  apis/Google.Cloud.Talent.V4/Google.Cloud.Talent.V4/Job.cs
  apis/Google.Cloud.Talent.V4/Google.Cloud.Talent.V4/Tenant.cs
  apis/Google.Cloud.Talent.V4/Google.Cloud.Talent.V4/TenantService.cs
  apis/Google.Cloud.Talent.V4/Google.Cloud.Talent.V4/TenantServiceClient.g.cs
  apis/Google.Cloud.Talent.V4/synth.metadata
Labels: cla: yes, context: full

#5387 [apis/ServiceDirectory] feat: add GetVulnerabilityOccurrencesSummary rpc.
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5388 Release Google.Cloud.Talent.V4 version 1.0.0-beta02
  README.md
  apis/Google.Cloud.Talent.V4/Google.Cloud.Talent.V4/Google.Cloud.Talent.V4.csproj
  apis/Google.Cloud.Talent.V4/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5389 Release Spanner libraries version 3.3.0
  README.md
  apis/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1.csproj
  apis/Google.Cloud.Spanner.Admin.Instance.V1/Google.Cloud.Spanner.Admin.Instance.V1/Google.Cloud.Spanner.Admin.Instance.V1.csproj
  apis/Google.Cloud.Spanner.Common.V1/Google.Cloud.Spanner.Common.V1/Google.Cloud.Spanner.Common.V1.csproj
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.csproj
  apis/Google.Cloud.Spanner.Data/docs/history.md
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1.csproj
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5390 Fix generation by removing a previous tweak
  apis/Google.Cloud.DevTools.ContainerAnalysis.V1/postgeneration.sh
Labels: cla: yes

#5391 [CHANGE ME] Re-generated apis/Google.Cloud.DevTools.ContainerAnalysis.V1 to pick up changes in the API or client library generator.
  apis/Google.Cloud.DevTools.ContainerAnalysis.V1/Google.Cloud.DevTools.ContainerAnalysis.V1.Snippets/ContainerAnalysisClientSnippets.g.cs
  apis/Google.Cloud.DevTools.ContainerAnalysis.V1/Google.Cloud.DevTools.ContainerAnalysis.V1.Tests/ContainerAnalysisClientTest.g.cs
  apis/Google.Cloud.DevTools.ContainerAnalysis.V1/Google.Cloud.DevTools.ContainerAnalysis.V1/ContainerAnalysisClient.g.cs
  apis/Google.Cloud.DevTools.ContainerAnalysis.V1/Google.Cloud.DevTools.ContainerAnalysis.V1/Containeranalysis.cs
  apis/Google.Cloud.DevTools.ContainerAnalysis.V1/Google.Cloud.DevTools.ContainerAnalysis.V1/ContaineranalysisGrpc.cs
  apis/Google.Cloud.DevTools.ContainerAnalysis.V1/Google.Cloud.DevTools.ContainerAnalysis.V1/ContaineranalysisResourceNames.g.cs
  apis/Google.Cloud.DevTools.ContainerAnalysis.V1/synth.metadata
Labels: cla: yes, context: partial

#5392 [Diagnostics]: Adds #5384 to backlog.
  BACKLOG.md
Labels: automerge, cla: yes

#5395 Fix small typos in BACKLOG.md
  BACKLOG.md
Labels: automerge, cla: yes

#5397 [apis/Google.Cloud.Security.PrivateCA.V1Beta1] feat!: BREAKING_CHANGE: Updates to Certificate Authority Service for Beta release
  apis/Google.Cloud.Security.PrivateCA.V1Beta1/Google.Cloud.Security.PrivateCA.V1Beta1.Snippets/CertificateAuthorityServiceClientSnippets.g.cs
  apis/Google.Cloud.Security.PrivateCA.V1Beta1/Google.Cloud.Security.PrivateCA.V1Beta1/CertificateAuthorityServiceClient.g.cs
  apis/Google.Cloud.Security.PrivateCA.V1Beta1/Google.Cloud.Security.PrivateCA.V1Beta1/Resources.cs
  apis/Google.Cloud.Security.PrivateCA.V1Beta1/Google.Cloud.Security.PrivateCA.V1Beta1/Service.cs
  apis/Google.Cloud.Security.PrivateCA.V1Beta1/Google.Cloud.Security.PrivateCA.V1Beta1/ServiceGrpc.cs
  apis/Google.Cloud.Security.PrivateCA.V1Beta1/Google.Cloud.Security.PrivateCA.V1Beta1/ServiceResourceNames.g.cs
  apis/Google.Cloud.Security.PrivateCA.V1Beta1/synth.metadata
Labels: cla: yes, context: full

#5396 [apis/Google.Cloud.BigQuery.Connection.V1] feat: add aws connection support
  apis/Google.Cloud.BigQuery.Connection.V1/Google.Cloud.BigQuery.Connection.V1.Tests/ConnectionServiceClientTest.g.cs
  apis/Google.Cloud.BigQuery.Connection.V1/Google.Cloud.BigQuery.Connection.V1/Connection.cs
  apis/Google.Cloud.BigQuery.Connection.V1/synth.metadata
Labels: cla: yes, context: full

#5398 [Storage]: Adds missing x-goog* headers in some V4 signing tests.
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.IntegrationTests/UrlSignerTest.V4SignerTest.cs
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.IntegrationTests/UrlSignerTest.cs
Labels: cla: yes

#5400 Release Google.Cloud.VideoIntelligence.V1 version 2.1.0
  README.md
  apis/Google.Cloud.VideoIntelligence.V1/Google.Cloud.VideoIntelligence.V1/Google.Cloud.VideoIntelligence.V1.csproj
  apis/Google.Cloud.VideoIntelligence.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5402 Delete previously-generated source code before generating
  generateapis.sh
Labels: cla: yes

#5404 Release Google.Cloud.Firestore version 2.2.0
  README.md
  apis/Google.Cloud.Firestore.V1/Google.Cloud.Firestore.V1/Google.Cloud.Firestore.V1.csproj
  apis/Google.Cloud.Firestore.V1/docs/history.md
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore/Google.Cloud.Firestore.csproj
  apis/Google.Cloud.Firestore/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5407 [apis/ServiceDirectory] feat: add v1 Cloud Billing Budgets API
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5408 Delete files in apis, not api
  generateapis.sh
Labels: cla: yes

#5411 [apis/Google.Cloud.Firestore.V1] fix(firestore/v1): give PartitionQuery retry/timeout config
  apis/Google.Cloud.Firestore.V1/Google.Cloud.Firestore.V1/FirestoreClient.g.cs
  apis/Google.Cloud.Firestore.V1/synth.metadata
Labels: cla: yes, context: full

#5412 Release Google.Cloud.AutoML.V1 version 2.1.0
  README.md
  apis/Google.Cloud.AutoML.V1/Google.Cloud.AutoML.V1/Google.Cloud.AutoML.V1.csproj
  apis/Google.Cloud.AutoML.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5410 [apis/Google.Analytics.Data.V1Alpha] feat!: GetMetadata method renamed to GetUniversalMetdata docs: documentation updates
  apis/Google.Analytics.Data.V1Alpha/Google.Analytics.Data.V1Alpha.Snippets/AlphaAnalyticsDataClientSnippets.g.cs
  apis/Google.Analytics.Data.V1Alpha/Google.Analytics.Data.V1Alpha.Tests/AlphaAnalyticsDataClientTest.g.cs
  apis/Google.Analytics.Data.V1Alpha/Google.Analytics.Data.V1Alpha/AlphaAnalyticsDataClient.g.cs
  apis/Google.Analytics.Data.V1Alpha/Google.Analytics.Data.V1Alpha/AnalyticsDataApi.cs
  apis/Google.Analytics.Data.V1Alpha/Google.Analytics.Data.V1Alpha/AnalyticsDataApiGrpc.cs
  apis/Google.Analytics.Data.V1Alpha/Google.Analytics.Data.V1Alpha/AnalyticsDataApiResourceNames.g.cs
  apis/Google.Analytics.Data.V1Alpha/Google.Analytics.Data.V1Alpha/Data.cs
  apis/Google.Analytics.Data.V1Alpha/synth.metadata
Labels: cla: yes, context: full

#5413 Release Google.Cloud.BigQuery.Connection.V1 version 1.1.0
  README.md
  apis/Google.Cloud.BigQuery.Connection.V1/Google.Cloud.BigQuery.Connection.V1/Google.Cloud.BigQuery.Connection.V1.csproj
  apis/Google.Cloud.BigQuery.Connection.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5414 Release Google.Cloud.BigQuery.Reservation.V1 version 1.1.0
  README.md
  apis/Google.Cloud.BigQuery.Reservation.V1/Google.Cloud.BigQuery.Reservation.V1/Google.Cloud.BigQuery.Reservation.V1.csproj
  apis/Google.Cloud.BigQuery.Reservation.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5415 [apis/Google.Cloud.Language.V1] feat: Fix proto comments for language API inorder for docs parsing to work correctly.
  apis/Google.Cloud.Language.V1/Google.Cloud.Language.V1/LanguageService.cs
  apis/Google.Cloud.Language.V1/synth.metadata
Labels: cla: yes, context: full

#5416 [apis/Google.Cloud.Retail.V2] Sync the public proto up-to-date with the recent changes
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2.Snippets/ProductServiceClientSnippets.g.cs
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2.Snippets/UserEventServiceClientSnippets.g.cs
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/Catalog.cs
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/Common.cs
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/ImportConfig.cs
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/ImportConfigResourceNames.g.cs
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/PredictionService.cs
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/Product.cs
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/ProductService.cs
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/ProductServiceClient.g.cs
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/ProductServiceGrpc.cs
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/PurgeConfig.cs
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/UserEvent.cs
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/UserEventService.cs
  apis/Google.Cloud.Retail.V2/synth.metadata
Labels: cla: yes, context: full

#5417 Release Google.Cloud.BigQuery.Storage.V1 version 2.1.0
  README.md
  apis/Google.Cloud.BigQuery.Storage.V1/Google.Cloud.BigQuery.Storage.V1/Google.Cloud.BigQuery.Storage.V1.csproj
  apis/Google.Cloud.BigQuery.Storage.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5418 Release Google.Cloud.Bigtable.Admin.V2 version 2.2.0
  README.md
  apis/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2.csproj
  apis/Google.Cloud.Bigtable.Admin.V2/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5420 [apis/Google.Cloud.Dialogflow.V2] docs: fixed link from SentimentAnalysisResult
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/Session.cs
  apis/Google.Cloud.Dialogflow.V2/synth.metadata
Labels: cla: yes, context: full

#5423 Release Google.Cloud.Bigtable.V2 version 2.1.0
  README.md
  apis/Google.Cloud.Bigtable.V2/Google.Cloud.Bigtable.V2/Google.Cloud.Bigtable.V2.csproj
  apis/Google.Cloud.Bigtable.V2/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5424 Release Google.Cloud.Billing.V1 version 2.1.0
  README.md
  apis/Google.Cloud.Billing.V1/Google.Cloud.Billing.V1/Google.Cloud.Billing.V1.csproj
  apis/Google.Cloud.Billing.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5428 Makes change detector work with netcoreapp3.1.
  detect-pr-changes.sh
Labels: cla: yes

#5427 Release Google.Cloud.Diagnostics packages.
  README.md
  apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore.csproj
  apis/Google.Cloud.Diagnostics.AspNetCore/docs/history.md
  apis/Google.Cloud.Diagnostics.AspNetCore3/Google.Cloud.Diagnostics.AspNetCore3/Google.Cloud.Diagnostics.AspNetCore3.csproj
  apis/Google.Cloud.Diagnostics.AspNetCore3/docs/history.md
  apis/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common.csproj
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5430 [apis/Google.Cloud.Dlp.V2] Fix: retrieve job config for risk analysis jobs. Docs: clarify timespan config for BigQuery and Datastore.
  apis/Google.Cloud.Dlp.V2/Google.Cloud.Dlp.V2/Dlp.cs
  apis/Google.Cloud.Dlp.V2/Google.Cloud.Dlp.V2/Storage.cs
  apis/Google.Cloud.Dlp.V2/synth.metadata
Labels: cla: yes, context: full

#5436 Add option for a smoke test to be skipped
  apis/Google.Cloud.Retail.V2Beta/smoketests.json
  tools/Google.Cloud.Tools.ReleaseManager/SmokeTest.cs
Labels: cla: yes

#5439 Make pre/post-generation scripts executable
  apis/Google.Cloud.Retail.V2Beta/postgeneration.sh
  apis/Google.Cloud.Retail.V2Beta/pregeneration.sh
Labels: cla: yes

#5440 [apis/Google.Cloud.Security.PrivateCA.V1Beta1] chore(privateca): Fix Ruby and PHP namespaces
  apis/Google.Cloud.Security.PrivateCA.V1Beta1/Google.Cloud.Security.PrivateCA.V1Beta1/Resources.cs
  apis/Google.Cloud.Security.PrivateCA.V1Beta1/Google.Cloud.Security.PrivateCA.V1Beta1/Service.cs
  apis/Google.Cloud.Security.PrivateCA.V1Beta1/synth.metadata
Labels: cla: yes, context: full

#5441 [apis/Google.Analytics.Admin.V1Alpha] feat!: added ListAccountSummaries method
  apis/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha.Snippets/AnalyticsAdminServiceClientSnippets.g.cs
  apis/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha/AnalyticsAdmin.cs
  apis/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha/AnalyticsAdminGrpc.cs
  apis/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha/AnalyticsAdminServiceClient.g.cs
  apis/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha/Resources.cs
  apis/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha/ResourcesResourceNames.g.cs
  apis/Google.Analytics.Admin.V1Alpha/synth.metadata
Labels: cla: yes, context: full

#5442 [apis/ServiceDirectory] feat!: added ListAccountSummaries method
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5443 Remove Google.Cloud.Retail.V2Beta
  apis/Google.Cloud.Retail.V2Beta/Google.Cloud.Retail.V2Beta.Snippets/CatalogServiceClientSnippets.g.cs
  apis/Google.Cloud.Retail.V2Beta/Google.Cloud.Retail.V2Beta.Snippets/Google.Cloud.Retail.V2Beta.Snippets.csproj
  apis/Google.Cloud.Retail.V2Beta/Google.Cloud.Retail.V2Beta.Snippets/PredictionServiceClientSnippets.g.cs
  apis/Google.Cloud.Retail.V2Beta/Google.Cloud.Retail.V2Beta.Snippets/ProductServiceClientSnippets.g.cs
  apis/Google.Cloud.Retail.V2Beta/Google.Cloud.Retail.V2Beta.Snippets/UserEventServiceClientSnippets.g.cs
  apis/Google.Cloud.Retail.V2Beta/Google.Cloud.Retail.V2Beta.Snippets/coverage.xml
  apis/Google.Cloud.Retail.V2Beta/Google.Cloud.Retail.V2Beta.Tests/CatalogServiceClientTest.g.cs
  apis/Google.Cloud.Retail.V2Beta/Google.Cloud.Retail.V2Beta.Tests/Google.Cloud.Retail.V2Beta.Tests.csproj
  apis/Google.Cloud.Retail.V2Beta/Google.Cloud.Retail.V2Beta.Tests/PredictionServiceClientTest.g.cs
  apis/Google.Cloud.Retail.V2Beta/Google.Cloud.Retail.V2Beta.Tests/ProductServiceClientTest.g.cs
  apis/Google.Cloud.Retail.V2Beta/Google.Cloud.Retail.V2Beta.Tests/UserEventServiceClientTest.g.cs
  apis/Google.Cloud.Retail.V2Beta/Google.Cloud.Retail.V2Beta.Tests/coverage.xml
  apis/Google.Cloud.Retail.V2Beta/Google.Cloud.Retail.V2Beta.sln
  apis/Google.Cloud.Retail.V2Beta/Google.Cloud.Retail.V2Beta/Catalog.cs
  apis/Google.Cloud.Retail.V2Beta/Google.Cloud.Retail.V2Beta/CatalogResourceNames.g.cs
  apis/Google.Cloud.Retail.V2Beta/Google.Cloud.Retail.V2Beta/CatalogService.cs
  apis/Google.Cloud.Retail.V2Beta/Google.Cloud.Retail.V2Beta/CatalogServiceClient.g.cs
  apis/Google.Cloud.Retail.V2Beta/Google.Cloud.Retail.V2Beta/CatalogServiceGrpc.cs
  apis/Google.Cloud.Retail.V2Beta/Google.Cloud.Retail.V2Beta/CatalogServiceResourceNames.g.cs
  apis/Google.Cloud.Retail.V2Beta/Google.Cloud.Retail.V2Beta/Common.cs
  apis/Google.Cloud.Retail.V2Beta/Google.Cloud.Retail.V2Beta/ExportConfig.cs
  apis/Google.Cloud.Retail.V2Beta/Google.Cloud.Retail.V2Beta/Google.Cloud.Retail.V2Beta.csproj
  apis/Google.Cloud.Retail.V2Beta/Google.Cloud.Retail.V2Beta/ImportConfig.cs
  apis/Google.Cloud.Retail.V2Beta/Google.Cloud.Retail.V2Beta/ImportConfigResourceNames.g.cs
  apis/Google.Cloud.Retail.V2Beta/Google.Cloud.Retail.V2Beta/PredictionService.cs
  apis/Google.Cloud.Retail.V2Beta/Google.Cloud.Retail.V2Beta/PredictionServiceClient.g.cs
  apis/Google.Cloud.Retail.V2Beta/Google.Cloud.Retail.V2Beta/PredictionServiceGrpc.cs
  apis/Google.Cloud.Retail.V2Beta/Google.Cloud.Retail.V2Beta/Product.cs
  apis/Google.Cloud.Retail.V2Beta/Google.Cloud.Retail.V2Beta/ProductResourceNames.g.cs
  apis/Google.Cloud.Retail.V2Beta/Google.Cloud.Retail.V2Beta/ProductService.cs
  apis/Google.Cloud.Retail.V2Beta/Google.Cloud.Retail.V2Beta/ProductServiceClient.g.cs
  apis/Google.Cloud.Retail.V2Beta/Google.Cloud.Retail.V2Beta/ProductServiceGrpc.cs
  apis/Google.Cloud.Retail.V2Beta/Google.Cloud.Retail.V2Beta/ProductServiceResourceNames.g.cs
  apis/Google.Cloud.Retail.V2Beta/Google.Cloud.Retail.V2Beta/PurgeConfig.cs
  apis/Google.Cloud.Retail.V2Beta/Google.Cloud.Retail.V2Beta/UserEvent.cs
  apis/Google.Cloud.Retail.V2Beta/Google.Cloud.Retail.V2Beta/UserEventService.cs
  apis/Google.Cloud.Retail.V2Beta/Google.Cloud.Retail.V2Beta/UserEventServiceClient.g.cs
  apis/Google.Cloud.Retail.V2Beta/Google.Cloud.Retail.V2Beta/UserEventServiceGrpc.cs
  apis/Google.Cloud.Retail.V2Beta/docs/index.md
  apis/Google.Cloud.Retail.V2Beta/postgeneration.sh
  apis/Google.Cloud.Retail.V2Beta/pregeneration.sh
  apis/Google.Cloud.Retail.V2Beta/smoketests.json
  apis/Google.Cloud.Retail.V2Beta/synth.metadata
  apis/Google.Cloud.Retail.V2Beta/synth.py
  apis/apis.json
Labels: cla: yes

#5444 Document the commit-multiple command
  PROCESSES.md
Labels: cla: yes

#5445 Release Workflows V1Beta01 packages version 1.0.0-beta01
  README.md
  apis/Google.Cloud.Workflows.Common.V1Beta/.repo-metadata.json
  apis/Google.Cloud.Workflows.Common.V1Beta/Google.Cloud.Workflows.Common.V1Beta/Google.Cloud.Workflows.Common.V1Beta.csproj
  apis/Google.Cloud.Workflows.Executions.V1Beta/.repo-metadata.json
  apis/Google.Cloud.Workflows.Executions.V1Beta/Google.Cloud.Workflows.Executions.V1Beta/Google.Cloud.Workflows.Executions.V1Beta.csproj
  apis/Google.Cloud.Workflows.Executions.V1Beta/docs/history.md
  apis/Google.Cloud.Workflows.V1Beta/.repo-metadata.json
  apis/Google.Cloud.Workflows.V1Beta/Google.Cloud.Workflows.V1Beta/Google.Cloud.Workflows.V1Beta.csproj
  apis/Google.Cloud.Workflows.V1Beta/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5446 Improve formatting in commit-multiple command
  tools/Google.Cloud.Tools.ReleaseManager/CommitMultipleCommand.cs
Labels: cla: yes

#5447 Release Google.Cloud.Container.V1 version 2.1.0
  README.md
  apis/Google.Cloud.Container.V1/Google.Cloud.Container.V1/Google.Cloud.Container.V1.csproj
  apis/Google.Cloud.Container.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5448 Allow for more flexible commit handling
  tools/Google.Cloud.Tools.ReleaseManager/Google.Cloud.Tools.ReleaseManager.csproj
  tools/Google.Cloud.Tools.ReleaseManager/History/GitCommit.cs
  tools/Google.Cloud.Tools.ReleaseManager/History/overrides.json
Labels: cla: yes

#5449 Release Google.Cloud.DataCatalog.V1 version 1.1.0
  README.md
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1.csproj
  apis/Google.Cloud.DataCatalog.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5451 Release Google.Cloud.Debugger.V2 version 2.1.0
  README.md
  apis/Google.Cloud.Debugger.V2/Google.Cloud.Debugger.V2/Google.Cloud.Debugger.V2.csproj
  apis/Google.Cloud.Debugger.V2/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5454 Order the service directory entries by proto path
  tools/Google.Cloud.Tools.Common/ServiceDirectory.cs
Labels: cla: yes

#5455 Re-generated apis/ServiceDirectory to pick up changes in the API or client library generator.
  apis/ServiceDirectory/directory.json
Labels: cla: yes, context: none

#5458 Release Google.Cloud.Dialogflow.V2 version 3.1.0
  README.md
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2.csproj
  apis/Google.Cloud.Dialogflow.V2/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5459 [apis/ServiceDirectory] Update Retail namespaces
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5460 [apis/Google.Cloud.Firestore.V1] fix: retry PartitionQuery for INTERNAL and DEADLINE_EXCEEDED
  apis/Google.Cloud.Firestore.V1/Google.Cloud.Firestore.V1/FirestoreClient.g.cs
  apis/Google.Cloud.Firestore.V1/synth.metadata
Labels: cla: yes, context: full

#5461 [apis/ServiceDirectory] chore: debrand 'Stackdriver' in favor of 'Cloud' in Error Reporting GAPIC libraries
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5463 Release Google.Cloud.Dlp.V2 version 3.1.0
  README.md
  apis/Google.Cloud.Dlp.V2/Google.Cloud.Dlp.V2/Google.Cloud.Dlp.V2.csproj
  apis/Google.Cloud.Dlp.V2/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5464 Release Google.Cloud.Functions.V1 version 1.0.0
  README.md
  apis/Google.Cloud.Functions.V1/.repo-metadata.json
  apis/Google.Cloud.Functions.V1/Google.Cloud.Functions.V1/Google.Cloud.Functions.V1.csproj
  apis/Google.Cloud.Functions.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5465 Release Google.LongRunning version 2.1.0
  README.md
  apis/Google.LongRunning/Google.LongRunning/Google.LongRunning.csproj
  apis/Google.LongRunning/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5466 Release Google.Cloud.Iam.V1 version 2.1.0
  README.md
  apis/Google.Cloud.Iam.V1/Google.Cloud.Iam.V1/Google.Cloud.Iam.V1.csproj
  apis/Google.Cloud.Iam.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5468 Update "internal" package dependencies as well as "external" ones
  tools/Google.Cloud.Tools.ReleaseManager/GenerateProjectsCommand.cs
  tools/Google.Cloud.Tools.ReleaseManager/SetVersionCommand.cs
Labels: cla: yes

#5469 Release Google.Cloud.Gaming.V1 version 1.0.0
  README.md
  apis/Google.Cloud.Gaming.V1/.repo-metadata.json
  apis/Google.Cloud.Gaming.V1/Google.Cloud.Gaming.V1/Google.Cloud.Gaming.V1.csproj
  apis/Google.Cloud.Gaming.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5471 Release Google.Cloud.Kms.V1 version 2.1.0
  README.md
  apis/Google.Cloud.Kms.V1/Google.Cloud.Kms.V1/Google.Cloud.Kms.V1.csproj
  apis/Google.Cloud.Kms.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5472 Show the updated history section when doing the updating
  tools/Google.Cloud.Tools.ReleaseManager/History/HistoryFile.cs
  tools/Google.Cloud.Tools.ReleaseManager/UpdateHistoryCommand.cs
Labels: cla: yes

#5473 Release Google.Cloud.Language.V1 version 2.1.0
  README.md
  apis/Google.Cloud.Language.V1/Google.Cloud.Language.V1/Google.Cloud.Language.V1.csproj
  apis/Google.Cloud.Language.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5475 Release Google.Cloud.Logging.Type version 3.1.0
  README.md
  apis/Google.Cloud.Logging.Type/Google.Cloud.Logging.Type/Google.Cloud.Logging.Type.csproj
  apis/Google.Cloud.Logging.Type/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5476 [apis/Google.Analytics.Data.V1Alpha] feat: added GetMetadata method for metadata including custom dimensions and metrics.
  apis/Google.Analytics.Data.V1Alpha/Google.Analytics.Data.V1Alpha.Snippets/AlphaAnalyticsDataClientSnippets.g.cs
  apis/Google.Analytics.Data.V1Alpha/Google.Analytics.Data.V1Alpha.Tests/AlphaAnalyticsDataClientTest.g.cs
  apis/Google.Analytics.Data.V1Alpha/Google.Analytics.Data.V1Alpha/AlphaAnalyticsDataClient.g.cs
  apis/Google.Analytics.Data.V1Alpha/Google.Analytics.Data.V1Alpha/AnalyticsDataApi.cs
  apis/Google.Analytics.Data.V1Alpha/Google.Analytics.Data.V1Alpha/AnalyticsDataApiGrpc.cs
  apis/Google.Analytics.Data.V1Alpha/Google.Analytics.Data.V1Alpha/AnalyticsDataApiResourceNames.g.cs
  apis/Google.Analytics.Data.V1Alpha/Google.Analytics.Data.V1Alpha/Data.cs
  apis/Google.Analytics.Data.V1Alpha/synth.metadata
Labels: cla: yes, context: full

#5477 Re-generated apis/ServiceDirectory with Visual Inspection API
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: partial

#5478 Release Google.Cloud.Logging.V2 version 3.1.0
  README.md
  apis/Google.Cloud.Logging.V2/Google.Cloud.Logging.V2/Google.Cloud.Logging.V2.csproj
  apis/Google.Cloud.Logging.V2/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5479 Release Google.Cloud.ManagedIdentities.V1 version 2.1.0
  README.md
  apis/Google.Cloud.ManagedIdentities.V1/Google.Cloud.ManagedIdentities.V1/Google.Cloud.ManagedIdentities.V1.csproj
  apis/Google.Cloud.ManagedIdentities.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5481 [apis/ServiceDirectory] feat: create the client for artifactregistry API.
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5482 Release Google.Cloud.Monitoring.V3 version 2.2.0
  README.md
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3.csproj
  apis/Google.Cloud.Monitoring.V3/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5483 [apis/Google.Analytics.Admin.V1Alpha] docs: renamed App + Web to Google Analytics 4 (GA4) in public documentation
  apis/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha/AnalyticsAdminGrpc.cs
  apis/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha/AnalyticsAdminServiceClient.g.cs
  apis/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha/Resources.cs
  apis/Google.Analytics.Admin.V1Alpha/synth.metadata
Labels: cla: yes, context: full

#5487 Release Google.Cloud.RecaptchaEnterprise.V1 version 1.1.0
  README.md
  apis/Google.Cloud.RecaptchaEnterprise.V1/Google.Cloud.RecaptchaEnterprise.V1/Google.Cloud.RecaptchaEnterprise.V1.csproj
  apis/Google.Cloud.RecaptchaEnterprise.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5488 Release Google.Cloud.Recommender.V1 version 2.2.0
  README.md
  apis/Google.Cloud.Recommender.V1/Google.Cloud.Recommender.V1/Google.Cloud.Recommender.V1.csproj
  apis/Google.Cloud.Recommender.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5486 Release Google.Cloud.OsConfig.V1 version 1.1.0
  README.md
  apis/Google.Cloud.OsConfig.V1/Google.Cloud.OsConfig.V1/Google.Cloud.OsConfig.V1.csproj
  apis/Google.Cloud.OsConfig.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5491 [apis/ServiceDirectory] feat: BigQuery Write API V1Beta2 public interface.
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5494 [apis/Google.Cloud.Billing.Budgets.V1] feat: Add support for credit type filter field.
  apis/Google.Cloud.Billing.Budgets.V1/Google.Cloud.Billing.Budgets.V1/BudgetModel.cs
  apis/Google.Cloud.Billing.Budgets.V1/synth.metadata
Labels: cla: yes, context: full

#5495 [apis/Google.Cloud.Recommender.V1] fix: updating the v1 retry params name for ListInsights, GetInsight, and MarkInsightAccepted.
  apis/Google.Cloud.Recommender.V1/Google.Cloud.Recommender.V1/RecommenderClient.g.cs
  apis/Google.Cloud.Recommender.V1/synth.metadata
Labels: cla: yes, context: full

#5496 [CHANGE ME] Re-generated apis/ServiceDirectory to pick up changes in the API or client library generator.
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5498 Clean output directories for desktop frameworks when running on Linux
  build.sh
Labels: cla: yes

#5499 Remove unnecessary netcoreapp1.0 dependency
  tools/Google.Cloud.Tools.Analyzers.Tests/Google.Cloud.Tools.Analyzers.Tests.csproj
Labels: cla: yes

#5500 Use GitHub actions badge instead of Travis
  README.md
Labels: cla: yes

#5501 [apis/Google.Cloud.Bigtable.Admin.V2] feat:Update BigtableTableAdmin GetIamPolicy to include the additional binding for Backup. feat:Change DeleteAppProfileRequest.ignore_warnings to REQUIRED.
  apis/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2.Snippets/BigtableTableAdminClientSnippets.g.cs
  apis/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2/BigtableInstanceAdmin.cs
  apis/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2/BigtableInstanceAdminGrpc.cs
  apis/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2/BigtableTableAdmin.cs
  apis/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2/BigtableTableAdminClient.g.cs
  apis/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2/BigtableTableAdminGrpc.cs
  apis/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2/BigtableTableAdminResourceNames.g.cs
  apis/Google.Cloud.Bigtable.Admin.V2/synth.metadata
Labels: cla: yes, context: full

#5502 [apis/Google.Cloud.Billing.Budgets.V1Beta1] feat: Add support for credit type filter field.
  apis/Google.Cloud.Billing.Budgets.V1Beta1/Google.Cloud.Billing.Budgets.V1Beta1/BudgetModel.cs
  apis/Google.Cloud.Billing.Budgets.V1Beta1/synth.metadata
Labels: cla: yes, context: full

#5503 Remove Travis configuration
  .travis.yml
Labels: cla: yes

#5474 Prototype of passing server-provided fields to custom type converters
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore.Tests/ConverterRegistryTest.cs
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore.Tests/Converters/CustomConverterTest.cs
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore/ConverterRegistry.cs
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore/Converters/CustomConverter.cs
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore/FirestoreDeserializationConfigurationAttribute.cs
  apis/Google.Cloud.Firestore/docs/datamodel.md
Labels: cla: yes

#5504 Release Google.Cloud.Firestore version 2.3.0-beta01
  README.md
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore.IntegrationTests/coverage.xml
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore.Snippets/coverage.xml
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore.Tests/coverage.xml
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore/Google.Cloud.Firestore.csproj
  apis/Google.Cloud.Firestore/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5505 [apis/Google.Cloud.Asset.V1] feat: add AnalyzeIamPolicy and AnalyzeIamPolicyLongrunning RPCs
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1.Snippets/AssetServiceClientSnippets.g.cs
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1.Tests/AssetServiceClientTest.g.cs
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1/AssetService.cs
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1/AssetServiceClient.g.cs
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1/AssetServiceGrpc.cs
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1/Assets.cs
  apis/Google.Cloud.Asset.V1/synth.metadata
Labels: cla: yes, context: full
