Repository googleapis/google-cloud-dotnet, pull requests merged in 2020-07, with the labels that each got.

#5125 [apis/Google.Cloud.Gaming.V1Beta] fix!: correct return type of delete operations BREAKING CHANGE: response type of Delete LRO is changed fix: increase timeout for CreateGameServerCluster
  apis/Google.Cloud.Gaming.V1Beta/Google.Cloud.Gaming.V1Beta.Snippets/GameServerClustersServiceClientSnippets.g.cs
  apis/Google.Cloud.Gaming.V1Beta/Google.Cloud.Gaming.V1Beta.Snippets/GameServerConfigsServiceClientSnippets.g.cs
  apis/Google.Cloud.Gaming.V1Beta/Google.Cloud.Gaming.V1Beta.Snippets/GameServerDeploymentsServiceClientSnippets.g.cs
  apis/Google.Cloud.Gaming.V1Beta/Google.Cloud.Gaming.V1Beta.Snippets/RealmsServiceClientSnippets.g.cs
  apis/Google.Cloud.Gaming.V1Beta/Google.Cloud.Gaming.V1Beta/GameServerClustersService.cs
  apis/Google.Cloud.Gaming.V1Beta/Google.Cloud.Gaming.V1Beta/GameServerClustersServiceClient.g.cs
  apis/Google.Cloud.Gaming.V1Beta/Google.Cloud.Gaming.V1Beta/GameServerConfigsService.cs
  apis/Google.Cloud.Gaming.V1Beta/Google.Cloud.Gaming.V1Beta/GameServerConfigsServiceClient.g.cs
  apis/Google.Cloud.Gaming.V1Beta/Google.Cloud.Gaming.V1Beta/GameServerDeploymentsService.cs
  apis/Google.Cloud.Gaming.V1Beta/Google.Cloud.Gaming.V1Beta/GameServerDeploymentsServiceClient.g.cs
  apis/Google.Cloud.Gaming.V1Beta/Google.Cloud.Gaming.V1Beta/RealmsService.cs
  apis/Google.Cloud.Gaming.V1Beta/Google.Cloud.Gaming.V1Beta/RealmsServiceClient.g.cs
  apis/Google.Cloud.Gaming.V1Beta/synth.metadata
Labels: cla: yes, context: full

#5124 Adds test for using client side signed JWT with a gRPC client.
  apis/Google.Cloud.Vision.V1/Google.Cloud.Vision.V1.IntegrationTests/Google.Cloud.Vision.V1.IntegrationTests.csproj
  apis/Google.Cloud.Vision.V1/Google.Cloud.Vision.V1.IntegrationTests/JwtAccessTests.cs
  apis/Google.Cloud.Vision.V1/Google.Cloud.Vision.V1.IntegrationTests/SydneyOperaHouse.jpg
Labels: cla: yes

#5126 Update Google.Apis.Storage.v1 dependency
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.IntegrationTests/Google.Cloud.Storage.V1.IntegrationTests.csproj
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.Snippets/Google.Cloud.Storage.V1.Snippets.csproj
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.Tests/Google.Cloud.Storage.V1.Tests.csproj
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.csproj
  apis/apis.json
Labels: cla: yes

#5127 [apis/ServiceDirectory] This is first release of the API protos and Bazel BUILD files for the Analytics Admin API V1alpha.
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5130 Release Google.Cloud.Storage.V1 version 3.2.0
  README.md
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.csproj
  apis/Google.Cloud.Storage.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5132 [apis/Google.Cloud.Recommender.V1] feat: adds methods for interacting with insights
  apis/Google.Cloud.Recommender.V1/Google.Cloud.Recommender.V1.Snippets/RecommenderClientSnippets.g.cs
  apis/Google.Cloud.Recommender.V1/Google.Cloud.Recommender.V1.Tests/RecommenderClientTest.g.cs
  apis/Google.Cloud.Recommender.V1/Google.Cloud.Recommender.V1/Insight.cs
  apis/Google.Cloud.Recommender.V1/Google.Cloud.Recommender.V1/InsightResourceNames.g.cs
  apis/Google.Cloud.Recommender.V1/Google.Cloud.Recommender.V1/Recommendation.cs
  apis/Google.Cloud.Recommender.V1/Google.Cloud.Recommender.V1/RecommenderClient.g.cs
  apis/Google.Cloud.Recommender.V1/Google.Cloud.Recommender.V1/RecommenderService.cs
  apis/Google.Cloud.Recommender.V1/Google.Cloud.Recommender.V1/RecommenderServiceGrpc.cs
  apis/Google.Cloud.Recommender.V1/Google.Cloud.Recommender.V1/RecommenderServiceResourceNames.g.cs
  apis/Google.Cloud.Recommender.V1/synth.metadata
Labels: cla: yes, context: full

#5133 [apis/Google.Cloud.Redis.V1] redis: v1 add UpgradeInstance request
  apis/Google.Cloud.Redis.V1/Google.Cloud.Redis.V1.Snippets/CloudRedisClientSnippets.g.cs
  apis/Google.Cloud.Redis.V1/Google.Cloud.Redis.V1/CloudRedis.cs
  apis/Google.Cloud.Redis.V1/Google.Cloud.Redis.V1/CloudRedisClient.g.cs
  apis/Google.Cloud.Redis.V1/Google.Cloud.Redis.V1/CloudRedisGrpc.cs
  apis/Google.Cloud.Redis.V1/Google.Cloud.Redis.V1/CloudRedisResourceNames.g.cs
  apis/Google.Cloud.Redis.V1/synth.metadata
Labels: cla: yes, context: full

#5136 Fix console output in Travis logs
  .travis.yml
  detect-pr-changes.sh
  toolversions.sh
Labels: cla: yes

#5123 docs: update path to /dotnet/docs/reference
  third_party/docfx/templates/devsite/README.md
  tools/Google.Cloud.Tools.GenerateDocfxSources/Program.cs
Labels: cla: yes

#5118 test: run spanner ITs against the emulator
  .travis.yml
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.Snippets/SpannerConnectionSnippets.cs
  spanner-ITs-against-emulator.sh
Labels: api: spanner, cla: yes

#5140 Release Google.Cloud.BigQuery.Connection.V1 version 1.0.0
  README.md
  apis/Google.Cloud.BigQuery.Connection.V1/.repo-metadata.json
  apis/Google.Cloud.BigQuery.Connection.V1/Google.Cloud.BigQuery.Connection.V1/Google.Cloud.BigQuery.Connection.V1.csproj
  apis/Google.Cloud.BigQuery.Connection.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5139 Changes to Spanner integration tests for CI
  .travis.yml
  apis/Google.Cloud.Spanner.Data/run-emulator-tests.sh
Labels: cla: yes

#5141 Release Google.Cloud.BigQuery.Reservation.V1 version 1.0.0
  README.md
  apis/Google.Cloud.BigQuery.Reservation.V1/.repo-metadata.json
  apis/Google.Cloud.BigQuery.Reservation.V1/Google.Cloud.BigQuery.Reservation.V1/Google.Cloud.BigQuery.Reservation.V1.csproj
  apis/Google.Cloud.BigQuery.Reservation.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5143 [apis/Google.Cloud.Trace.V2] feat: added support for span kind
  apis/Google.Cloud.Trace.V2/Google.Cloud.Trace.V2.Snippets/TraceServiceClientSnippets.g.cs
  apis/Google.Cloud.Trace.V2/Google.Cloud.Trace.V2.Tests/TraceServiceClientTest.g.cs
  apis/Google.Cloud.Trace.V2/Google.Cloud.Trace.V2/Trace.cs
  apis/Google.Cloud.Trace.V2/Google.Cloud.Trace.V2/TracingGrpc.cs
  apis/Google.Cloud.Trace.V2/synth.metadata
Labels: cla: yes, context: full

#5142 [apis/Google.Cloud.Trace.V1] feat: added support for span kind
  apis/Google.Cloud.Trace.V1/Google.Cloud.Trace.V1/Trace.cs
  apis/Google.Cloud.Trace.V1/Google.Cloud.Trace.V1/TraceGrpc.cs
  apis/Google.Cloud.Trace.V1/synth.metadata
Labels: cla: yes, context: full

#5144 [apis/Google.Cloud.DocumentAI.V1Beta2] feat: publish documentai/v1beta2 protos
  apis/Google.Cloud.DocumentAI.V1Beta2/Google.Cloud.DocumentAI.V1Beta2/DocumentUnderstandingServiceClient.g.cs
  apis/Google.Cloud.DocumentAI.V1Beta2/synth.metadata
Labels: cla: yes, context: full

#5146 [apis/Google.Cloud.Spanner.Admin.Database.V1] Fully qualify response type in longrunning_operation.info for CreateBackup in the same fashion as all other longrunning operations.
  apis/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1/SpannerDatabaseAdmin.cs
  apis/Google.Cloud.Spanner.Admin.Database.V1/synth.metadata
Labels: cla: yes, context: full

#5145 [apis/Google.Cloud.Logging.V2] feat: Update Logging API protos.
  apis/Google.Cloud.Logging.V2/Google.Cloud.Logging.V2/ConfigServiceV2Client.g.cs
  apis/Google.Cloud.Logging.V2/Google.Cloud.Logging.V2/LogEntry.cs
  apis/Google.Cloud.Logging.V2/Google.Cloud.Logging.V2/Logging.cs
  apis/Google.Cloud.Logging.V2/Google.Cloud.Logging.V2/LoggingConfig.cs
  apis/Google.Cloud.Logging.V2/Google.Cloud.Logging.V2/LoggingConfigGrpc.cs
  apis/Google.Cloud.Logging.V2/Google.Cloud.Logging.V2/LoggingGrpc.cs
  apis/Google.Cloud.Logging.V2/Google.Cloud.Logging.V2/LoggingMetrics.cs
  apis/Google.Cloud.Logging.V2/Google.Cloud.Logging.V2/LoggingServiceV2Client.g.cs
  apis/Google.Cloud.Logging.V2/Google.Cloud.Logging.V2/MetricsServiceV2Client.g.cs
  apis/Google.Cloud.Logging.V2/synth.metadata
Labels: cla: yes, context: full

#5147 [CHANGE ME] Re-generated apis/ServiceDirectory to pick up changes in the API or client library generator.
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5150 Remove cruft from output when generating documentation
  tools/Google.Cloud.Tools.GenerateDocfxSources/Program.cs
Labels: cla: yes

#5153 [apis/Google.Cloud.Dlp.V2] Feature: Add CSV and TSV to file types. Fixes: Cleaned up resource_reference annotations for correct semantics and improved client library generation Fixes: BucketingConfig.replacement_value marked as required
  apis/Google.Cloud.Dlp.V2/Google.Cloud.Dlp.V2.Snippets/DlpServiceClientSnippets.g.cs
  apis/Google.Cloud.Dlp.V2/Google.Cloud.Dlp.V2.Tests/DlpServiceClientTest.g.cs
  apis/Google.Cloud.Dlp.V2/Google.Cloud.Dlp.V2/Dlp.cs
  apis/Google.Cloud.Dlp.V2/Google.Cloud.Dlp.V2/DlpResourceNames.g.cs
  apis/Google.Cloud.Dlp.V2/Google.Cloud.Dlp.V2/DlpServiceClient.g.cs
  apis/Google.Cloud.Dlp.V2/Google.Cloud.Dlp.V2/Storage.cs
  apis/Google.Cloud.Dlp.V2/synth.metadata
Labels: cla: yes, context: full

#5154 Release Google.Cloud.Recommender.V1 version 2.1.0
  README.md
  apis/Google.Cloud.Recommender.V1/Google.Cloud.Recommender.V1/Google.Cloud.Recommender.V1.csproj
  apis/Google.Cloud.Recommender.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5159 [CHANGE ME] Re-generated apis/ServiceDirectory to pick up changes in the API or client library generator.
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5161 Fix the "clean test data" script
  .kokoro/cleantestdata.sh
Labels: cla: yes

#5164 [apis/ServiceDirectory] feat: generating GAPIC libraries for Google Cloud Functions v1.
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5171 [apis/ServiceDirectory] feat!: remove Google Cloud Functions v1beta2 API
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5168 [apis/Google.Cloud.SecurityCenter.V1] fix: correct securitycenter grpc_service_configs
  apis/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1/SecurityCenterClient.g.cs
  apis/Google.Cloud.SecurityCenter.V1/synth.metadata
Labels: cla: yes, context: full

#5169 [apis/Google.Cloud.SecurityCenter.V1P1Beta1] fix: correct securitycenter grpc_service_configs
  apis/Google.Cloud.SecurityCenter.V1P1Beta1/Google.Cloud.SecurityCenter.V1P1Beta1/SecurityCenterClient.g.cs
  apis/Google.Cloud.SecurityCenter.V1P1Beta1/synth.metadata
Labels: cla: yes, context: full

#5170 [apis/Google.Cloud.Spanner.V1] feat: Spanner NUMERIC type
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/Type.cs
  apis/Google.Cloud.Spanner.V1/synth.metadata
Labels: cla: yes, context: full

#5166 Revert "Skip URL signer test that needs to metadata access"
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.Snippets/UrlSignerSnippets.cs
Labels: cla: yes

#5173 Release Google.Analytics.Admin.V1Alpha version 1.0.0-alpha01
  README.md
  apis/Google.Analytics.Admin.V1Alpha/.repo-metadata.json
  apis/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha.csproj
  apis/Google.Analytics.Admin.V1Alpha/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5174 Fix release script
  .kokoro/release.sh
Labels: cla: yes

#5175 Fix release script again
  .kokoro/release.sh
Labels: cla: yes

#5176 Fix release script one more time
  .kokoro/release.sh
Labels: cla: yes

#5178 Release Spanner libraries version 3.1.0
  README.md
  apis/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1.csproj
  apis/Google.Cloud.Spanner.Admin.Instance.V1/Google.Cloud.Spanner.Admin.Instance.V1/Google.Cloud.Spanner.Admin.Instance.V1.csproj
  apis/Google.Cloud.Spanner.Common.V1/Google.Cloud.Spanner.Common.V1/Google.Cloud.Spanner.Common.V1.csproj
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.csproj
  apis/Google.Cloud.Spanner.Data/docs/history.md
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1.csproj
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5182 [apis/Google.Cloud.Dataproc.V1] fix!: fix LRO annotations for method `DiagnoseCluster`.
  apis/Google.Cloud.Dataproc.V1/Google.Cloud.Dataproc.V1.Snippets/ClusterControllerClientSnippets.g.cs
  apis/Google.Cloud.Dataproc.V1/Google.Cloud.Dataproc.V1/ClusterControllerClient.g.cs
  apis/Google.Cloud.Dataproc.V1/Google.Cloud.Dataproc.V1/Clusters.cs
  apis/Google.Cloud.Dataproc.V1/synth.metadata
Labels: cla: yes, context: full

#5183 [apis/ServiceDirectory] Beta version of the Certificate Authority Service.
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5184 Bump Dataproc library version due to breaking change
  README.md
  apis/Google.Cloud.Dataproc.V1/Google.Cloud.Dataproc.V1/Google.Cloud.Dataproc.V1.csproj
  apis/apis.json
  docs/root/index.md
Labels: cla: yes

#5186 Clarify the scopes used by BigQueryClient.Create and CreateAsync
  apis/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2/BigQueryClient.cs
Labels: cla: yes

#5188 [apis/ServiceDirectory] feat: Update App Engine Admin API protos for v1 and v1beta APIs. Also update the AuditData proto used in audit logs generated by App Engine.
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5192 Prints available disk space during build.
  build.sh
Labels: cla: yes

#5193 Adds step by step disk space info in build logs.
  .kokoro/build.sh
  .kokoro/runintegrationtests.sh
  build.sh
  toolversions.sh
Labels: cla: yes

#5197 Avoid unnecessarily problematic language
  .travis.yml
Labels: cla: yes

#5198 [apis/Google.Cloud.Spanner.Admin.Database.V1] fix(spanner): update UpdateBackup to be retryable
  apis/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1/DatabaseAdminClient.g.cs
  apis/Google.Cloud.Spanner.Admin.Database.V1/synth.metadata
Labels: cla: yes, context: full

#5199 [Diagnostics]: Associates logs to the correct trace/span if there is one.
  apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore.IntegrationTests/Logging/LoggingTest.cs
  apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore/Logging/GoogleLogger.cs
  apis/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common.IntegrationTests/EntryData.cs
  apis/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common.IntegrationTests/Trace/TraceEntryPolling.cs
Labels: cla: yes

#5201 [Diagnostics] Fixes some flakiness introduced in #5199.
  apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore.IntegrationTests/Logging/LoggingTest.cs
  apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore.IntegrationTests/Trace/TraceTest.cs
Labels: cla: yes

#5202 [apis/ServiceDirectory] fix: add resource config to scc/v1beta1/Asset
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5205 [apis/Google.Cloud.Dialogflow.V2] docs: more detailed docs on APIs such as Environment, Intents, Sessions.
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/Agent.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/Context.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/ContextGrpc.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/ContextsClient.g.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/EntityType.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/EntityTypeGrpc.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/EntityTypesClient.g.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/Environment.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/EnvironmentGrpc.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/EnvironmentsClient.g.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/Intent.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/IntentGrpc.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/IntentsClient.g.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/Session.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/SessionEntityType.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/SessionEntityTypeGrpc.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/SessionEntityTypesClient.g.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/SessionGrpc.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/SessionsClient.g.cs
  apis/Google.Cloud.Dialogflow.V2/synth.metadata
Labels: cla: yes, context: full

#5208 [apis/Google.Cloud.Dialogflow.V2] feat: added support for custom content types docs: clarified wording around quota usage
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/AudioConfig.cs
  apis/Google.Cloud.Dialogflow.V2/synth.metadata
Labels: cla: yes, context: full

#5212 [apis/ServiceDirectory] feat: Add Dataproc Metastore v1alpha API.
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5210 [apis/Google.Cloud.BigQuery.Connection.V1] Add/correct PHP namespace for BigQuery connection/reservation
  apis/Google.Cloud.BigQuery.Connection.V1/Google.Cloud.BigQuery.Connection.V1/Connection.cs
  apis/Google.Cloud.BigQuery.Connection.V1/synth.metadata
Labels: cla: yes, context: full

#5211 [apis/Google.Cloud.BigQuery.Reservation.V1] Add/correct PHP namespace for BigQuery connection/reservation
  apis/Google.Cloud.BigQuery.Reservation.V1/Google.Cloud.BigQuery.Reservation.V1/Reservation.cs
  apis/Google.Cloud.BigQuery.Reservation.V1/synth.metadata
Labels: cla: yes, context: full

#5215 [apis/ServiceDirectory] feat: Add Video Transcoder V1Beta1 API.
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5217 [apis/Google.Cloud.BigQuery.Connection.V1] Correct PHP namespace for BigQuery connection
  apis/Google.Cloud.BigQuery.Connection.V1/Google.Cloud.BigQuery.Connection.V1/Connection.cs
  apis/Google.Cloud.BigQuery.Connection.V1/synth.metadata
Labels: cla: yes, context: full

#5218 [apis/Google.Cloud.Dataproc.V1] feat: Additional fields for the `ClusterConfig` and `InstanceGroupConfig` messages.
  apis/Google.Cloud.Dataproc.V1/Google.Cloud.Dataproc.V1/AutoscalingPolicies.cs
  apis/Google.Cloud.Dataproc.V1/Google.Cloud.Dataproc.V1/Clusters.cs
  apis/Google.Cloud.Dataproc.V1/Google.Cloud.Dataproc.V1/Jobs.cs
  apis/Google.Cloud.Dataproc.V1/Google.Cloud.Dataproc.V1/Shared.cs
  apis/Google.Cloud.Dataproc.V1/Google.Cloud.Dataproc.V1/WorkflowTemplates.cs
  apis/Google.Cloud.Dataproc.V1/synth.metadata
Labels: cla: yes, context: full

#5219 [apis/Google.Cloud.PubSub.V1] Remove experimental warning for ordering keys properties.
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/PublisherServiceApiClient.g.cs
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/Pubsub.cs
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/PubsubGrpc.cs
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/SubscriberServiceApiClient.g.cs
  apis/Google.Cloud.PubSub.V1/synth.metadata
Labels: cla: yes, context: full

#5220 [apis/Google.Cloud.Translate.V3] fix: corrects spelling of build dependency adds backticks in docstring to smooth doc generation
  apis/Google.Cloud.Translate.V3/Google.Cloud.Translate.V3/TranslationService.cs
  apis/Google.Cloud.Translate.V3/synth.metadata
Labels: cla: yes, context: full

#5214 [Diagnostics]: Adds support for including external tracing information in log entries.
  apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore.IntegrationTests/Logging/LoggingTest.cs
  apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore.Tests/Logging/GoogleLoggerTest.cs
  apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore/Logging/GoogleLogger.cs
  apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore/Logging/IExternalTraceProvider.cs
  apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore/Logging/TraceContextForLogEntry.cs
Labels: cla: yes

#5222 [apis/ServiceDirectory] feat: Add cloud gaming v1
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5221 [Diagnostics]: Trace rate limiter always/never trace.
  apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore.IntegrationTests/Logging/LoggingTest.cs
  apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore.IntegrationTests/Trace/TraceTest.cs
  apis/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common.Tests/Trace/RateLimiterTest.cs
  apis/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common/Trace/RateLimiter.cs
  apis/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common/Trace/TraceOptions.cs
Labels: cla: yes

#5224 Remove disk space output from common logging method
  toolversions.sh
Labels: cla: yes
