Repository googleapis/google-cloud-dotnet, pull requests merged in 2020-08, with the labels that each got.

#5228 Release Google.Cloud.PubSub.V1 version 2.1.0
  README.md
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1.csproj
  apis/Google.Cloud.PubSub.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5229 Diagnostics release v4.1.0-beta01
  README.md
  apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore.csproj
  apis/Google.Cloud.Diagnostics.AspNetCore/docs/history.md
  apis/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common.csproj
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5230 NLog GoogleStackDriverTarget skip reflection on Stream-objects
  apis/Google.Cloud.Logging.NLog/Google.Cloud.Logging.NLog/GoogleStackdriverTarget.cs
Labels: cla: yes

#5232 [apis/Google.Cloud.Dataproc.V1] docs: change relative URLs to absolute URLs to fix broken links.
  apis/Google.Cloud.Dataproc.V1/Google.Cloud.Dataproc.V1/AutoscalingPolicies.cs
  apis/Google.Cloud.Dataproc.V1/synth.metadata
Labels: cla: yes, context: full

#5233 [apis/ServiceDirectory] feat: Initial client generation for Dialogflow CX v3beta1.
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5237 tests: unskip some skipped tests against emulator
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.IntegrationTests/ChunkingTests.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.IntegrationTests/SpannerStressTests.cs
Labels: api: spanner, cla: yes

#5239 [Speech]: Fixes Speech smoke tests.
  apis/Google.Cloud.Speech.V1/smoketests.json
  apis/Google.Cloud.Speech.V1P1Beta1/smoketests.json
Labels: cla: yes

#5240 [apis/Google.Cloud.TextToSpeech.V1] chore: escape `*` characters in comments
  apis/Google.Cloud.TextToSpeech.V1/Google.Cloud.TextToSpeech.V1/CloudTts.cs
  apis/Google.Cloud.TextToSpeech.V1/Google.Cloud.TextToSpeech.V1/TextToSpeechClient.g.cs
  apis/Google.Cloud.TextToSpeech.V1/synth.metadata
Labels: cla: yes, context: full

#5242 [apis/ServiceDirectory] chore: set C#, PHP, and Ruby namespaces in proto options
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5241 [apis/Google.Cloud.Kms.V1] Add client integrity verification fields to the KMS protos
  apis/Google.Cloud.Kms.V1/Google.Cloud.Kms.V1.Snippets/KeyManagementServiceClientSnippets.g.cs
  apis/Google.Cloud.Kms.V1/Google.Cloud.Kms.V1.Tests/KeyManagementServiceClientTest.g.cs
  apis/Google.Cloud.Kms.V1/Google.Cloud.Kms.V1/Resources.cs
  apis/Google.Cloud.Kms.V1/Google.Cloud.Kms.V1/ResourcesResourceNames.g.cs
  apis/Google.Cloud.Kms.V1/Google.Cloud.Kms.V1/Service.cs
  apis/Google.Cloud.Kms.V1/synth.metadata
Labels: cla: yes, context: full

#5203 feat(spanner): set resource header in data client
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1.Tests/ResourcePrefixHeaderTest.cs
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/SpannerClientPartial.cs
Labels: api: spanner, cla: yes

#5243 [apis/Google.Cloud.Notebooks.V1Beta1] chore: Fix Ruby namespace for Cloud Notebooks V1beta1
  apis/Google.Cloud.Notebooks.V1Beta1/Google.Cloud.Notebooks.V1Beta1/Environment.cs
  apis/Google.Cloud.Notebooks.V1Beta1/Google.Cloud.Notebooks.V1Beta1/Instance.cs
  apis/Google.Cloud.Notebooks.V1Beta1/Google.Cloud.Notebooks.V1Beta1/Service.cs
  apis/Google.Cloud.Notebooks.V1Beta1/synth.metadata
Labels: cla: yes, context: full

#5246 [apis/Google.Cloud.SecurityCenter.V1P1Beta1] feat: added field severity to findings
  apis/Google.Cloud.SecurityCenter.V1P1Beta1/Google.Cloud.SecurityCenter.V1P1Beta1.Tests/SecurityCenterClientTest.g.cs
  apis/Google.Cloud.SecurityCenter.V1P1Beta1/Google.Cloud.SecurityCenter.V1P1Beta1/Finding.cs
  apis/Google.Cloud.SecurityCenter.V1P1Beta1/Google.Cloud.SecurityCenter.V1P1Beta1/SecurityCenterClient.g.cs
  apis/Google.Cloud.SecurityCenter.V1P1Beta1/Google.Cloud.SecurityCenter.V1P1Beta1/SecuritycenterService.cs
  apis/Google.Cloud.SecurityCenter.V1P1Beta1/Google.Cloud.SecurityCenter.V1P1Beta1/SecuritycenterServiceGrpc.cs
  apis/Google.Cloud.SecurityCenter.V1P1Beta1/synth.metadata
Labels: cla: yes, context: full

#5245 [apis/Google.Cloud.Asset.V1] feat: added support OutputResult in ExportAssetsResponse. docs: updated existing docs.
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1/AssetService.cs
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1/AssetServiceClient.g.cs
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1/AssetServiceGrpc.cs
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1/Assets.cs
  apis/Google.Cloud.Asset.V1/synth.metadata
Labels: cla: yes, context: full

#5251 [apis/ServiceDirectory] Removing protos for v1 of Google Ads API, which has sunset and is no longer in use.
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5253 Release Google.Cloud.SecurityCenter.V1P1Beta1 version 2.0.0-beta03
  README.md
  apis/Google.Cloud.SecurityCenter.V1P1Beta1/Google.Cloud.SecurityCenter.V1P1Beta1/Google.Cloud.SecurityCenter.V1P1Beta1.csproj
  apis/Google.Cloud.SecurityCenter.V1P1Beta1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5254 Release Google.Cloud.Diagnostics packages version 4.1.0
  README.md
  apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore.csproj
  apis/Google.Cloud.Diagnostics.AspNetCore/docs/history.md
  apis/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common.csproj
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5257 [apis/Google.Cloud.SecurityCenter.V1P1Beta1] docs: Clarified that event_time can also be considered as the "update time" for a Finding. It also captures when a Finding was updated. The previous wording could've been interpreted as only the creation time.
  apis/Google.Cloud.SecurityCenter.V1P1Beta1/Google.Cloud.SecurityCenter.V1P1Beta1/Finding.cs
  apis/Google.Cloud.SecurityCenter.V1P1Beta1/synth.metadata
Labels: cla: yes, context: full

#5256 [apis/Google.Cloud.SecurityCenter.V1] docs: Clarified that event_time can also be considered as the "update time" for a Finding. It also captures when a Finding was updated. The previous wording could've been interpreted as only the creation time.
  apis/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1/Finding.cs
  apis/Google.Cloud.SecurityCenter.V1/synth.metadata
Labels: cla: yes, context: full

#5255 [Spanner] feat: set resource header in streaming method
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.Tests/SpannerCommandTests.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.Tests/V1/SpannerClientHelpers.cs
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/PooledSession.cs
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/SpannerClientPartial.cs
Labels: api: spanner, cla: yes

#5259 [CHANGE ME] Re-generated apis/ServiceDirectory to pick up changes in the API or client library generator.
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5258 [apis/Google.Cloud.Firestore.V1] firestore: add `!=` support
  apis/Google.Cloud.Firestore.V1/Google.Cloud.Firestore.V1/Firestore.cs
  apis/Google.Cloud.Firestore.V1/Google.Cloud.Firestore.V1/Query.cs
  apis/Google.Cloud.Firestore.V1/synth.metadata
Labels: cla: yes, context: full

#5264 [apis/Google.Cloud.Asset.V1] feat: add AnalyzeIamPolicy and ExportIamPolicyAnalysis RPCs
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1.Snippets/AssetServiceClientSnippets.g.cs
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1.Tests/AssetServiceClientTest.g.cs
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1/AssetService.cs
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1/AssetServiceClient.g.cs
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1/AssetServiceGrpc.cs
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1/Assets.cs
  apis/Google.Cloud.Asset.V1/synth.metadata
Labels: cla: yes, context: full

#5265 Release Google.Cloud.Asset.V1 version 2.3.0
  README.md
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1.csproj
  apis/Google.Cloud.Asset.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5268 [apis/ServiceDirectory] feat: add media translation v1alpha1 API
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5269 Change the bucket we upload the raw docfx YAML to for DevSite
  .kokoro/release.sh
Labels: cla: yes

#5267 Ignore "EffectivePackageOwner" when writing out API metadata
  apis/apis.json
  tools/Google.Cloud.Tools.Common/ApiMetadata.cs
Labels: cla: yes

#5270 [apis/ServiceDirectory] Google Ads API v5 protos and config files.
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5271 [apis/ServiceDirectory] Adding Cloud Domains v1alpha2 API.
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5272 [apis/ServiceDirectory] feat: added google.cloud.assuredworkloads.v1beta1.AssuredWorkloadsService service
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5273 [CHANGE ME] Re-generated apis/ServiceDirectory to pick up changes in the API or client library generator.
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5277 [apis/ServiceDirectory] feat: Initial client libraries for Area 120 Tables API.
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full
