Repository googleapis/google-cloud-dotnet, pull requests merged in 2020-06, with the labels that each got.

#5003 [BigQuery] Adds testing for filtering jobs by parent.
  apis/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2.IntegrationTests/JobsTest.cs
Labels: cla: yes

#5006 Release Google.Cloud.Dlp.V2 version 3.0.0
  README.md
  apis/Google.Cloud.Dlp.V2/Google.Cloud.Dlp.V2/Google.Cloud.Dlp.V2.csproj
  apis/Google.Cloud.Dlp.V2/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5011 Release Google.Cloud.Asset.V1 version 2.1.0
  README.md
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1.csproj
  apis/Google.Cloud.Asset.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5010 Release Google.Cloud.Firestore version 2.1.0
  README.md
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore.IntegrationTests/coverage.xml
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore.Snippets/coverage.xml
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore.Tests/coverage.xml
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore/Google.Cloud.Firestore.csproj
  apis/Google.Cloud.Firestore/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5013 [apis/Google.Cloud.Firestore.V1] firestore: add BatchWrite
  apis/Google.Cloud.Firestore.V1/Google.Cloud.Firestore.V1.Snippets/FirestoreClientSnippets.g.cs
  apis/Google.Cloud.Firestore.V1/Google.Cloud.Firestore.V1.Tests/FirestoreClientTest.g.cs
  apis/Google.Cloud.Firestore.V1/Google.Cloud.Firestore.V1/Firestore.cs
  apis/Google.Cloud.Firestore.V1/Google.Cloud.Firestore.V1/FirestoreClient.g.cs
  apis/Google.Cloud.Firestore.V1/Google.Cloud.Firestore.V1/FirestoreGrpc.cs
  apis/Google.Cloud.Firestore.V1/Google.Cloud.Firestore.V1/Query.cs
  apis/Google.Cloud.Firestore.V1/synth.metadata
Labels: cla: yes, context: full

#5014 [apis/Google.Cloud.Redis.V1] docs: change relative URLs to absolute URLs to fix broken links.
  apis/Google.Cloud.Redis.V1/Google.Cloud.Redis.V1/CloudRedis.cs
  apis/Google.Cloud.Redis.V1/Google.Cloud.Redis.V1/CloudRedisClient.g.cs
  apis/Google.Cloud.Redis.V1/Google.Cloud.Redis.V1/CloudRedisGrpc.cs
  apis/Google.Cloud.Redis.V1/synth.metadata
Labels: cla: yes, context: full

#5016 [apis/Google.Cloud.TextToSpeech.V1] docs: change relative URLs to absolute URLs to fix broken links.
  apis/Google.Cloud.TextToSpeech.V1/Google.Cloud.TextToSpeech.V1/CloudTts.cs
  apis/Google.Cloud.TextToSpeech.V1/synth.metadata
Labels: cla: yes, context: full

#5015 [apis/Google.Cloud.Redis.V1Beta1] docs: change relative URLs to absolute URLs to fix broken links.
  apis/Google.Cloud.Redis.V1Beta1/Google.Cloud.Redis.V1Beta1/CloudRedis.cs
  apis/Google.Cloud.Redis.V1Beta1/Google.Cloud.Redis.V1Beta1/CloudRedisClient.g.cs
  apis/Google.Cloud.Redis.V1Beta1/Google.Cloud.Redis.V1Beta1/CloudRedisGrpc.cs
  apis/Google.Cloud.Redis.V1Beta1/synth.metadata
Labels: cla: yes, context: full

#5017 Release Google.Cloud.Dialogflow.V2 version 3.0.0
  README.md
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2.csproj
  apis/Google.Cloud.Dialogflow.V2/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5019 Disable deterministic source roots "harder" for docs builds
  docs/builddocs.sh
Labels: cla: yes

#5020 Note client thread safety in documentation
  apis/Google.Cloud.Firestore/docs/index.md
  apis/Google.Cloud.Storage.V1/docs/index.md
  docs/root/guides/cleanup.md
  tools/Google.Cloud.Tools.GenerateDocfxSources/Program.cs
Labels: cla: yes

#5022 Allow general iterable object to be serialized (but not deserialized) in Firestore
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore.Tests/ValueDeserializerTest.cs
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore.Tests/ValueSerializerTest.cs
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore/Converters/ConverterCache.cs
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore/Converters/SequenceConverter.cs
Labels: cla: yes

#5026 Remove a now-unused Google.Cloud.AnalyzersTesting project from the Diagnostics solution
  apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore.sln
Labels: cla: yes

#5030 [apis/Google.Cloud.Dlp.V2] docs: fix several broken links in the docs.
  apis/Google.Cloud.Dlp.V2/Google.Cloud.Dlp.V2/Dlp.cs
  apis/Google.Cloud.Dlp.V2/Google.Cloud.Dlp.V2/Storage.cs
  apis/Google.Cloud.Dlp.V2/synth.metadata
Labels: cla: yes, context: full

#5029 [apis/Google.Cloud.Dataproc.V1] docs: change relative URLs to absolute URLs to fix broken links.
  apis/Google.Cloud.Dataproc.V1/Google.Cloud.Dataproc.V1/Jobs.cs
  apis/Google.Cloud.Dataproc.V1/synth.metadata
Labels: cla: yes, context: full

#5031 Release Google.Cloud.BigQuery.V2 version 2.0.0
  README.md
  apis/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2.csproj
  apis/Google.Cloud.BigQuery.V2/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5032 Cleaning up some Google.Cloud.Diagnostics.AspNet leftover references.
  apis/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common.IntegrationTests/AssemblyInfo.cs
  apis/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common.Tests/AssemblyInfo.cs
  apis/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common/AssemblyInfo.cs
Labels: cla: yes

#5034 [apis/Google.Cloud.Container.V1] docs: fix a broken link in the docs.
  apis/Google.Cloud.Container.V1/Google.Cloud.Container.V1/ClusterService.cs
  apis/Google.Cloud.Container.V1/synth.metadata
Labels: cla: yes, context: full

#5035 [apis/Google.Cloud.ErrorReporting.V1Beta1] docs: fix several broken links in the docs.
  apis/Google.Cloud.ErrorReporting.V1Beta1/Google.Cloud.ErrorReporting.V1Beta1/Common.cs
  apis/Google.Cloud.ErrorReporting.V1Beta1/Google.Cloud.ErrorReporting.V1Beta1/ErrorGroupService.cs
  apis/Google.Cloud.ErrorReporting.V1Beta1/Google.Cloud.ErrorReporting.V1Beta1/ErrorGroupServiceClient.g.cs
  apis/Google.Cloud.ErrorReporting.V1Beta1/synth.metadata
Labels: cla: yes, context: full

#5036 [apis/Google.Cloud.Kms.V1] docs: change relative URLs to absolute URLs to fix broken links.
  apis/Google.Cloud.Kms.V1/Google.Cloud.Kms.V1/Resources.cs
  apis/Google.Cloud.Kms.V1/synth.metadata
Labels: cla: yes, context: full

#5037 [apis/Google.Cloud.Monitoring.V3] docs: change relative URLs to absolute URLs to fix broken links.
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3/Common.cs
  apis/Google.Cloud.Monitoring.V3/synth.metadata
Labels: cla: yes, context: full

#5038 [apis/Google.Cloud.PubSub.V1] Add "detached" bool to Subscription
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1.Snippets/SubscriberServiceApiClientSnippets.g.cs
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1.Tests/SubscriberServiceApiClientTest.g.cs
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/Pubsub.cs
  apis/Google.Cloud.PubSub.V1/synth.metadata
Labels: cla: yes, context: full

#5039 [apis/Google.Cloud.Talent.V4Beta1] docs: Remove a broken link from the documentation.
  apis/Google.Cloud.Talent.V4Beta1/Google.Cloud.Talent.V4Beta1/Filters.cs
  apis/Google.Cloud.Talent.V4Beta1/synth.metadata
Labels: cla: yes, context: full

#5041 [apis/Google.Cloud.Container.V1] docs: Fixed broken links in the reference documentation
  apis/Google.Cloud.Container.V1/Google.Cloud.Container.V1/ClusterService.cs
  apis/Google.Cloud.Container.V1/synth.metadata
Labels: cla: yes, context: full

#5046 Release Google.Cloud.BigQuery.Connection.V1 version 1.0.0-beta01
  README.md
  apis/Google.Cloud.BigQuery.Connection.V1/.repo-metadata.json
  apis/Google.Cloud.BigQuery.Connection.V1/Google.Cloud.BigQuery.Connection.V1/Google.Cloud.BigQuery.Connection.V1.csproj
  apis/Google.Cloud.BigQuery.Connection.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5050 [CHANGE ME] Re-generated apis/ServiceDirectory to pick up changes in the API or client library generator.
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5049 Remove now-unnecessary patch shell scripts for DocumentAI
  apis/Google.Cloud.DocumentAI.V1Beta2/postgeneration.sh
  apis/Google.Cloud.DocumentAI.V1Beta2/pregeneration.sh
Labels: cla: yes

#5051 Update Google.Api.CommonProtos to 2.1.0 for Monitoring
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3.csproj
  apis/apis.json
Labels: cla: yes

#5053 [apis/Google.Cloud.Monitoring.V3] Regular update of Google API service config with clarification of documentations.
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3.Tests/MetricServiceClientTest.g.cs
  apis/Google.Cloud.Monitoring.V3/synth.metadata
Labels: cla: yes, context: full

#5058 [apis/Google.Cloud.BigQuery.Connection.V1] fix: update method_signature annotation for list RPC
  apis/Google.Cloud.BigQuery.Connection.V1/Google.Cloud.BigQuery.Connection.V1.Snippets/ConnectionServiceClientSnippets.g.cs
  apis/Google.Cloud.BigQuery.Connection.V1/Google.Cloud.BigQuery.Connection.V1/Connection.cs
  apis/Google.Cloud.BigQuery.Connection.V1/Google.Cloud.BigQuery.Connection.V1/ConnectionGrpc.cs
  apis/Google.Cloud.BigQuery.Connection.V1/Google.Cloud.BigQuery.Connection.V1/ConnectionServiceClient.g.cs
  apis/Google.Cloud.BigQuery.Connection.V1/synth.metadata
Labels: cla: yes, context: full

#5059 [apis/Google.Cloud.Memcache.V1Beta2] docs: Change relative URLs to absolute URLs to fix broken links.
  apis/Google.Cloud.Memcache.V1Beta2/Google.Cloud.Memcache.V1Beta2/CloudMemcache.cs
  apis/Google.Cloud.Memcache.V1Beta2/synth.metadata
Labels: cla: yes, context: full

#5062 Service directory regeneration
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5060 [apis/Google.Cloud.SecurityCenter.V1] feat: Add Resource to the v1 NotificationMessage, which contains resource-related fields associated to the Finding notification. docs: Adjusted wording from Cloud SCC to Security Command Center, and updated filtering docs for List APIs.
  apis/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1/Asset.cs
  apis/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1/Finding.cs
  apis/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1/NotificationMessage.cs
  apis/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1/OrganizationSettings.cs
  apis/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1/Resource.cs
  apis/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1/SecurityMarks.cs
  apis/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1/SecuritycenterService.cs
  apis/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1/Source.cs
  apis/Google.Cloud.SecurityCenter.V1/synth.metadata
Labels: cla: yes, context: full

#5064 Release Google.Cloud.BigQuery.Connection.V1 version 1.0.0-beta02
  README.md
  apis/Google.Cloud.BigQuery.Connection.V1/Google.Cloud.BigQuery.Connection.V1/Google.Cloud.BigQuery.Connection.V1.csproj
  apis/Google.Cloud.BigQuery.Connection.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5065 Roll back uncommitted (and not-rolled-back) read/write transactions on session release
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.IntegrationTests/BatchDmlTests.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.Tests/SpannerBatchCommandTests.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.Tests/V1/PooledSessionTests.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.Tests/V1/SessionPoolTests.SessionTestingSpannerClient.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.Tests/V1/SessionPoolTests.TargetedSessionPoolTests.cs
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/PooledSession.cs
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/SessionPool.DetachedSessionPool.cs
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/SessionPool.ISessionPool.cs
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/SessionPool.SessionPoolBase.cs
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/SessionPool.TargetedSessionPool.cs
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/SessionPool.cs
Labels: cla: yes

#5067 [apis/Google.Cloud.SecurityCenter.V1P1Beta1] fix!: Fix the version casing in the C# namespace option BREAKING CHANGE: This would break any C# code already generated, but this file is very new, so is unlikely to break anyone.
  apis/Google.Cloud.SecurityCenter.V1P1Beta1/Google.Cloud.SecurityCenter.V1P1Beta1.Snippets/SecurityCenterClientSnippets.g.cs
  apis/Google.Cloud.SecurityCenter.V1P1Beta1/Google.Cloud.SecurityCenter.V1P1Beta1/Asset.cs
  apis/Google.Cloud.SecurityCenter.V1P1Beta1/Google.Cloud.SecurityCenter.V1P1Beta1/Finding.cs
  apis/Google.Cloud.SecurityCenter.V1P1Beta1/Google.Cloud.SecurityCenter.V1P1Beta1/NotificationConfig.cs
  apis/Google.Cloud.SecurityCenter.V1P1Beta1/Google.Cloud.SecurityCenter.V1P1Beta1/NotificationMessage.cs
  apis/Google.Cloud.SecurityCenter.V1P1Beta1/Google.Cloud.SecurityCenter.V1P1Beta1/OrganizationSettings.cs
  apis/Google.Cloud.SecurityCenter.V1P1Beta1/Google.Cloud.SecurityCenter.V1P1Beta1/Resource.cs
  apis/Google.Cloud.SecurityCenter.V1P1Beta1/Google.Cloud.SecurityCenter.V1P1Beta1/SecurityCenterClient.g.cs
  apis/Google.Cloud.SecurityCenter.V1P1Beta1/Google.Cloud.SecurityCenter.V1P1Beta1/SecurityMarks.cs
  apis/Google.Cloud.SecurityCenter.V1P1Beta1/Google.Cloud.SecurityCenter.V1P1Beta1/SecuritycenterService.cs
  apis/Google.Cloud.SecurityCenter.V1P1Beta1/Google.Cloud.SecurityCenter.V1P1Beta1/SecuritycenterServiceGrpc.cs
  apis/Google.Cloud.SecurityCenter.V1P1Beta1/Google.Cloud.SecurityCenter.V1P1Beta1/Source.cs
  apis/Google.Cloud.SecurityCenter.V1P1Beta1/synth.metadata
Labels: cla: yes, context: full

#5068 [apis/ServiceDirectory] fix!: Fix the version casing in the C# namespace option BREAKING CHANGE: This would break any C# code already generated, but this file is very new, so is unlikely to break anyone.
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5066 [apis/Google.Cloud.PubSub.V1] docs: Add a link to Pub/Sub filtering language public documentation to pubsub.proto
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/Pubsub.cs
  apis/Google.Cloud.PubSub.V1/synth.metadata
Labels: cla: yes, context: full

#5069 [apis/Google.Cloud.Bigtable.Admin.V2] chore: set Ruby namespace in proto options
  apis/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2/BigtableInstanceAdmin.cs
  apis/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2/BigtableTableAdmin.cs
  apis/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2/Common.cs
  apis/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2/Instance.cs
  apis/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2/Table.cs
  apis/Google.Cloud.Bigtable.Admin.V2/synth.metadata
Labels: cla: yes, context: full

#5070 [apis/Google.Cloud.Bigtable.V2] chore: set Ruby namespace in proto options
  apis/Google.Cloud.Bigtable.V2/Google.Cloud.Bigtable.V2/Bigtable.cs
  apis/Google.Cloud.Bigtable.V2/Google.Cloud.Bigtable.V2/Data.cs
  apis/Google.Cloud.Bigtable.V2/synth.metadata
Labels: cla: yes, context: full

#5071 [apis/Google.Cloud.Debugger.V2] chore: set Ruby namespace in proto options
  apis/Google.Cloud.Debugger.V2/Google.Cloud.Debugger.V2/Controller.cs
  apis/Google.Cloud.Debugger.V2/Google.Cloud.Debugger.V2/Data.cs
  apis/Google.Cloud.Debugger.V2/Google.Cloud.Debugger.V2/Debugger.cs
  apis/Google.Cloud.Debugger.V2/synth.metadata
Labels: cla: yes, context: full

#5072 [apis/Google.Cloud.Logging.Type] chore: set Ruby namespace in proto options
  apis/Google.Cloud.Logging.Type/Google.Cloud.Logging.Type/HttpRequest.cs
  apis/Google.Cloud.Logging.Type/Google.Cloud.Logging.Type/LogSeverity.cs
  apis/Google.Cloud.Logging.Type/synth.metadata
Labels: cla: yes, context: full

#5073 [apis/Google.Cloud.Logging.V2] chore: set Ruby namespace in proto options
  apis/Google.Cloud.Logging.V2/Google.Cloud.Logging.V2/LogEntry.cs
  apis/Google.Cloud.Logging.V2/Google.Cloud.Logging.V2/Logging.cs
  apis/Google.Cloud.Logging.V2/Google.Cloud.Logging.V2/LoggingConfig.cs
  apis/Google.Cloud.Logging.V2/Google.Cloud.Logging.V2/LoggingMetrics.cs
  apis/Google.Cloud.Logging.V2/synth.metadata
Labels: cla: yes, context: full

#5075 [apis/Google.Cloud.ErrorReporting.V1Beta1] chore: set Ruby namespace in proto options
  apis/Google.Cloud.ErrorReporting.V1Beta1/Google.Cloud.ErrorReporting.V1Beta1/Common.cs
  apis/Google.Cloud.ErrorReporting.V1Beta1/Google.Cloud.ErrorReporting.V1Beta1/ErrorGroupService.cs
  apis/Google.Cloud.ErrorReporting.V1Beta1/Google.Cloud.ErrorReporting.V1Beta1/ErrorStatsService.cs
  apis/Google.Cloud.ErrorReporting.V1Beta1/Google.Cloud.ErrorReporting.V1Beta1/ReportErrorsService.cs
  apis/Google.Cloud.ErrorReporting.V1Beta1/synth.metadata
Labels: cla: yes, context: full

#5074 [apis/Google.Cloud.Datastore.V1] chore: set Ruby namespace in proto options
  apis/Google.Cloud.Datastore.V1/Google.Cloud.Datastore.V1/Datastore.cs
  apis/Google.Cloud.Datastore.V1/Google.Cloud.Datastore.V1/Entity.cs
  apis/Google.Cloud.Datastore.V1/Google.Cloud.Datastore.V1/Query.cs
  apis/Google.Cloud.Datastore.V1/synth.metadata
Labels: cla: yes, context: full

#5077 [apis/Google.Cloud.Firestore.V1] chore: set Ruby namespace in proto options
  apis/Google.Cloud.Firestore.V1/Google.Cloud.Firestore.V1/Common.cs
  apis/Google.Cloud.Firestore.V1/Google.Cloud.Firestore.V1/Document.cs
  apis/Google.Cloud.Firestore.V1/Google.Cloud.Firestore.V1/Firestore.cs
  apis/Google.Cloud.Firestore.V1/Google.Cloud.Firestore.V1/Query.cs
  apis/Google.Cloud.Firestore.V1/Google.Cloud.Firestore.V1/Write.cs
  apis/Google.Cloud.Firestore.V1/synth.metadata
Labels: cla: yes, context: full

#5076 [apis/Google.Cloud.Firestore.Admin.V1] chore: set Ruby namespace in proto options
  apis/Google.Cloud.Firestore.Admin.V1/Google.Cloud.Firestore.Admin.V1/Field.cs
  apis/Google.Cloud.Firestore.Admin.V1/Google.Cloud.Firestore.Admin.V1/FirestoreAdmin.cs
  apis/Google.Cloud.Firestore.Admin.V1/Google.Cloud.Firestore.Admin.V1/Index.cs
  apis/Google.Cloud.Firestore.Admin.V1/Google.Cloud.Firestore.Admin.V1/Location.cs
  apis/Google.Cloud.Firestore.Admin.V1/Google.Cloud.Firestore.Admin.V1/Operation.cs
  apis/Google.Cloud.Firestore.Admin.V1/synth.metadata
Labels: cla: yes, context: full

#5079 [apis/Google.Cloud.Trace.V2] chore: set Ruby namespace in proto options
  apis/Google.Cloud.Trace.V2/Google.Cloud.Trace.V2/Trace.cs
  apis/Google.Cloud.Trace.V2/Google.Cloud.Trace.V2/Tracing.cs
  apis/Google.Cloud.Trace.V2/synth.metadata
Labels: cla: yes, context: full

#5078 [apis/Google.Cloud.Trace.V1] chore: set Ruby namespace in proto options
  apis/Google.Cloud.Trace.V1/Google.Cloud.Trace.V1/Trace.cs
  apis/Google.Cloud.Trace.V1/synth.metadata
Labels: cla: yes, context: full

#5080 [apis/ServiceDirectory] fix!:Provide C# namespace option for consistent capitalization.
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5083 [apis/Google.Cloud.Spanner.V1] chore: set Ruby namespace in proto options
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/Keys.cs
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/Mutation.cs
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/QueryPlan.cs
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/ResultSet.cs
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/Spanner.cs
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/Transaction.cs
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/Type.cs
  apis/Google.Cloud.Spanner.V1/synth.metadata
Labels: cla: yes, context: full

#5082 [apis/Google.Cloud.Spanner.Admin.Instance.V1] chore: set Ruby namespace in proto options
  apis/Google.Cloud.Spanner.Admin.Instance.V1/Google.Cloud.Spanner.Admin.Instance.V1/SpannerInstanceAdmin.cs
  apis/Google.Cloud.Spanner.Admin.Instance.V1/synth.metadata
Labels: cla: yes, context: full

#5081 [apis/Google.Cloud.Spanner.Admin.Database.V1] chore: set Ruby namespace in proto options
  apis/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1/Backup.cs
  apis/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1/Common.cs
  apis/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1/SpannerDatabaseAdmin.cs
  apis/Google.Cloud.Spanner.Admin.Database.V1/synth.metadata
Labels: cla: yes, context: full

#5085 Release Google.Cloud.BigQuery.Reservation.V1 version 1.0.0-beta01
  README.md
  apis/Google.Cloud.BigQuery.Reservation.V1/.repo-metadata.json
  apis/Google.Cloud.BigQuery.Reservation.V1/Google.Cloud.BigQuery.Reservation.V1/Google.Cloud.BigQuery.Reservation.V1.csproj
  apis/Google.Cloud.BigQuery.Reservation.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5086 Release Google.Cloud.Monitoring.V3 version 2.1.0
  README.md
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3.csproj
  apis/Google.Cloud.Monitoring.V3/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5087 Fix WhereIn filters being used in implicit orderings
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore.Tests/QueryTest.cs
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore/Query.cs
Labels: cla: yes

#5089 [apis/Google.Cloud.Firestore.V1] feat: retry CommitRequests that fail with UNAVAILABLE
  apis/Google.Cloud.Firestore.V1/Google.Cloud.Firestore.V1/FirestoreClient.g.cs
  apis/Google.Cloud.Firestore.V1/Google.Cloud.Firestore.V1/Query.cs
  apis/Google.Cloud.Firestore.V1/synth.metadata
Labels: cla: yes, context: full

#5088 Fixes #5028: Adds options to specify service context values for GoogleLogger.
  apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore.IntegrationTests/Logging/LoggingTest.cs
  apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore.Tests/Logging/GoogleLoggerTest.cs
  apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore/GoogleDiagnosticsWebHostBuilderExtensions.cs
  apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore/Logging/GoogleLogger.cs
  apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore/Logging/LoggerOptions.cs
  apis/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common/CommonUtils.cs
  apis/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common/ErrorReporting/ErrorReportingContextExceptionLogger.cs
  apis/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common/ServiceContextUtils.cs
Labels: cla: yes

#5091 [BigQuery] Unskips Routine's and Model's Etag tests.
  apis/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2.IntegrationTests/ModelTests.cs
  apis/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2.IntegrationTests/RoutineTests.cs
Labels: cla: yes

#5094 [apis/Google.Cloud.Asset.V1] feat: added support for condition in Feed docs: updated existing docs.
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1.Tests/AssetServiceClientTest.g.cs
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1/AssetService.cs
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1/AssetServiceClient.g.cs
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1/AssetServiceGrpc.cs
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1/Assets.cs
  apis/Google.Cloud.Asset.V1/synth.metadata
Labels: cla: yes, context: full

#5098 [apis/ServiceDirectory] feat: added support for condition in Feed docs: updated existing docs.
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5096 [apis/Google.Cloud.SecurityCenter.V1] Specify allowed fields for UpdateNotificationConfig
  apis/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1/SecurityCenterClient.g.cs
  apis/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1/SecuritycenterServiceGrpc.cs
  apis/Google.Cloud.SecurityCenter.V1/synth.metadata
Labels: cla: yes, context: full

#5097 [apis/Google.Cloud.SecurityCenter.V1P1Beta1] Specify allowed fields for UpdateNotificationConfig
  apis/Google.Cloud.SecurityCenter.V1P1Beta1/Google.Cloud.SecurityCenter.V1P1Beta1/SecurityCenterClient.g.cs
  apis/Google.Cloud.SecurityCenter.V1P1Beta1/Google.Cloud.SecurityCenter.V1P1Beta1/SecuritycenterServiceGrpc.cs
  apis/Google.Cloud.SecurityCenter.V1P1Beta1/synth.metadata
Labels: cla: yes, context: full

#5095 Release Google.Cloud.Asset.V1 version 2.2.0
  README.md
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1.csproj
  apis/Google.Cloud.Asset.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5099 [apis/ServiceDirectory] Add protos and configs for the Google Analytics Data API v1 alpha.
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5102 Document why we're ignoring a few more APIs
  apis/apis.json
Labels: cla: yes

#5103 [apis/Google.Cloud.Gaming.V1Beta] docs: Fixed casing in proto documentation to match other documentation. feat: Added retry configuration.
  apis/Google.Cloud.Gaming.V1Beta/Google.Cloud.Gaming.V1Beta/Common.cs
  apis/Google.Cloud.Gaming.V1Beta/Google.Cloud.Gaming.V1Beta/GameServerClusters.cs
  apis/Google.Cloud.Gaming.V1Beta/Google.Cloud.Gaming.V1Beta/GameServerClustersServiceClient.g.cs
  apis/Google.Cloud.Gaming.V1Beta/Google.Cloud.Gaming.V1Beta/GameServerClustersServiceGrpc.cs
  apis/Google.Cloud.Gaming.V1Beta/Google.Cloud.Gaming.V1Beta/GameServerConfigs.cs
  apis/Google.Cloud.Gaming.V1Beta/Google.Cloud.Gaming.V1Beta/GameServerConfigsServiceClient.g.cs
  apis/Google.Cloud.Gaming.V1Beta/Google.Cloud.Gaming.V1Beta/GameServerConfigsServiceGrpc.cs
  apis/Google.Cloud.Gaming.V1Beta/Google.Cloud.Gaming.V1Beta/GameServerDeployments.cs
  apis/Google.Cloud.Gaming.V1Beta/Google.Cloud.Gaming.V1Beta/GameServerDeploymentsServiceClient.g.cs
  apis/Google.Cloud.Gaming.V1Beta/Google.Cloud.Gaming.V1Beta/GameServerDeploymentsServiceGrpc.cs
  apis/Google.Cloud.Gaming.V1Beta/Google.Cloud.Gaming.V1Beta/Realms.cs
  apis/Google.Cloud.Gaming.V1Beta/Google.Cloud.Gaming.V1Beta/RealmsServiceClient.g.cs
  apis/Google.Cloud.Gaming.V1Beta/Google.Cloud.Gaming.V1Beta/RealmsServiceGrpc.cs
  apis/Google.Cloud.Gaming.V1Beta/synth.metadata
Labels: cla: yes, context: full

#5104 [apis/Google.Cloud.Tasks.V2Beta3] feat: introducing field Queue.type docs: fixing typos and minor updates
  apis/Google.Cloud.Tasks.V2Beta3/Google.Cloud.Tasks.V2Beta3.Tests/CloudTasksClientTest.g.cs
  apis/Google.Cloud.Tasks.V2Beta3/Google.Cloud.Tasks.V2Beta3/CloudtasksGrpc.cs
  apis/Google.Cloud.Tasks.V2Beta3/Google.Cloud.Tasks.V2Beta3/Queue.cs
  apis/Google.Cloud.Tasks.V2Beta3/Google.Cloud.Tasks.V2Beta3/Target.cs
  apis/Google.Cloud.Tasks.V2Beta3/Google.Cloud.Tasks.V2Beta3/Task.cs
  apis/Google.Cloud.Tasks.V2Beta3/synth.metadata
Labels: cla: yes, context: full

#5105 [apis/ServiceDirectory] docs: Fixed casing in proto documentation to match other documentation. feat: Added retry configuration.
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5106 [apis/Google.Cloud.BigQuery.Connection.V1] fix: update annotations for java proto generation
  apis/Google.Cloud.BigQuery.Connection.V1/Google.Cloud.BigQuery.Connection.V1/Connection.cs
  apis/Google.Cloud.BigQuery.Connection.V1/synth.metadata
Labels: cla: yes, context: full

#5107 [apis/Google.Cloud.WebRisk.V1] fix: add CreateSubmission to webrisk/v1 config
  apis/Google.Cloud.WebRisk.V1/Google.Cloud.WebRisk.V1/WebRiskServiceClient.g.cs
  apis/Google.Cloud.WebRisk.V1/synth.metadata
Labels: cla: yes, context: full

#5110 [apis/Google.Cloud.OsConfig.V1] docs: Fix several broken links in reference documentation
  apis/Google.Cloud.OsConfig.V1/Google.Cloud.OsConfig.V1/PatchDeployments.cs
  apis/Google.Cloud.OsConfig.V1/Google.Cloud.OsConfig.V1/PatchJobs.cs
  apis/Google.Cloud.OsConfig.V1/synth.metadata
Labels: cla: yes, context: full

#5112 [apis/Google.Cloud.Dialogflow.V2] - Update grpc config for retry mechanism. - Update ImportAgent/ExportAgent external documentation.
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/AgentGrpc.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/AgentsClient.g.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/ContextsClient.g.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/EntityTypesClient.g.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/EnvironmentsClient.g.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/IntentsClient.g.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/SessionEntityTypesClient.g.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/SessionsClient.g.cs
  apis/Google.Cloud.Dialogflow.V2/synth.metadata
Labels: cla: yes, context: full

#5111 [apis/Google.Cloud.Asset.V1] fix: asset/v1 add missing RPCs to grpc_service_config
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1/AssetServiceClient.g.cs
  apis/Google.Cloud.Asset.V1/synth.metadata
Labels: cla: yes, context: full

#5113 [apis/Google.Cloud.PubSub.V1] feature: Add flow control settings for StreamingPullRequest to pubsub.proto
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1.Snippets/SubscriberServiceApiClientSnippets.g.cs
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/Pubsub.cs
  apis/Google.Cloud.PubSub.V1/synth.metadata
Labels: cla: yes, context: full

#5117 [apis/Google.Cloud.Firestore.V1] firestore: add BatchWrite to service config
  apis/Google.Cloud.Firestore.V1/Google.Cloud.Firestore.V1/FirestoreClient.g.cs
  apis/Google.Cloud.Firestore.V1/Google.Cloud.Firestore.V1/Query.cs
  apis/Google.Cloud.Firestore.V1/synth.metadata
Labels: cla: yes, context: full

#5116 [apis/Google.Cloud.Billing.V1] fix: combine billing/v1 grpc_service_config files
  apis/Google.Cloud.Billing.V1/Google.Cloud.Billing.V1/CloudBillingClient.g.cs
  apis/Google.Cloud.Billing.V1/Google.Cloud.Billing.V1/CloudCatalogClient.g.cs
  apis/Google.Cloud.Billing.V1/synth.metadata
Labels: cla: yes, context: full

#5119 [apis/Google.Cloud.PubSub.V1] feat: Add support for server-side streaming pull flow control
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/SubscriberClient.cs
Labels: cla: yes

#5121 Improvements to GetOrdinal behavior
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.IntegrationTests/ReadTests.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/SpannerDataReader.cs
Labels: cla: yes

#5122 Attempt to fix broken logging on Travis
  detect-pr-changes.sh
Labels: cla: yes
