Repository googleapis/google-cloud-dotnet, pull requests merged in 2020-12, with the labels that each got.

#5640 [apis/Google.Cloud.Spanner.Admin.Database.V1] chore: adds throttled to UpdateDatabaseDdlMetadata
  apis/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1/SpannerDatabaseAdmin.cs
  apis/Google.Cloud.Spanner.Admin.Database.V1/synth.metadata
Labels: cla: yes, context: full

#5641 [apis/Google.Cloud.Vision.V1] feat: Add TextDetectionParams.enable_text_detection_confidence_score
  apis/Google.Cloud.Vision.V1/Google.Cloud.Vision.V1/ImageAnnotator.cs
  apis/Google.Cloud.Vision.V1/synth.metadata
Labels: cla: yes, context: full

#5642 Add Cloud Retail API
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5643 Release Google.Cloud.Vision.V1 version 2.2.0
  README.md
  apis/Google.Cloud.Vision.V1/Google.Cloud.Vision.V1/Google.Cloud.Vision.V1.csproj
  apis/Google.Cloud.Vision.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5635 Google.Cloud.Logging.Nlog Adds possibility to use custom jsonLayout
  apis/Google.Cloud.Logging.NLog/Google.Cloud.Logging.NLog.Snippets/Google.Cloud.Logging.NLog.Snippets.csproj
  apis/Google.Cloud.Logging.NLog/Google.Cloud.Logging.NLog.Snippets/nlog-jsonTemplate.xml
  apis/Google.Cloud.Logging.NLog/Google.Cloud.Logging.NLog.Tests/GoogleStackdriverTargetTest.cs
  apis/Google.Cloud.Logging.NLog/Google.Cloud.Logging.NLog/GoogleStackdriverTarget.cs
  apis/Google.Cloud.Logging.NLog/Google.Cloud.Logging.NLog/GoogleStackdriverTarget_Configuration.cs
Labels: cla: yes

#5647 [apis/Google.Cloud.Asset.V1] chore: fix typo 'partion_key' in comments
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1/AssetService.cs
  apis/Google.Cloud.Asset.V1/synth.metadata
Labels: cla: yes, context: full

#5649 Release Google.Cloud.PubSub.V1 version 2.2.0
  README.md
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1.csproj
  apis/Google.Cloud.PubSub.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5650 Update Log4Net dependency to fix issue on Linux
  apis/Google.Cloud.Logging.Log4Net/Google.Cloud.Logging.Log4Net/Google.Cloud.Logging.Log4Net.csproj
  apis/apis.json
Labels: cla: yes

#5651 docs: Recommend using CreateAsync also for creating generated clients.
  tools/Google.Cloud.Tools.GenerateDocfxSources/Program.cs
Labels: cla: yes

#5654 [apis/ServiceDirectory] feat: Add API definitions for Cloud Channel API.
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5655 [Vision]: test: Checks for a different label in a Vision.DetectLabels test.
  apis/Google.Cloud.Vision.V1/Google.Cloud.Vision.V1.Snippets/ImageAnnotatorClientSnippets.cs
Labels: cla: yes

#5658 [apis/Google.Analytics.Data.V1Alpha] feat: custom_definition field added to DimensionMetadata object, indicating whether a dimension is a custom dimension for a property feat: custom_definition field added to MetricMetadata object, indicating whether
  apis/Google.Analytics.Data.V1Alpha/Google.Analytics.Data.V1Alpha/AlphaAnalyticsDataClient.g.cs
  apis/Google.Analytics.Data.V1Alpha/Google.Analytics.Data.V1Alpha/AnalyticsDataApi.cs
  apis/Google.Analytics.Data.V1Alpha/Google.Analytics.Data.V1Alpha/Data.cs
  apis/Google.Analytics.Data.V1Alpha/synth.metadata
Labels: cla: yes, context: full

#5659 Changes in service metadata
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5660 [apis/Google.Cloud.Dialogflow.V2] feat: allowed custom to specify webhook headers through query parameters docs: suggested to always use version for production traffic when calling DetectIntent, mark match_mode in Agent message as deprecated
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2.Tests/AgentsClientTest.g.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/Agent.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/Session.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/SessionGrpc.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/SessionsClient.g.cs
  apis/Google.Cloud.Dialogflow.V2/synth.metadata
Labels: cla: yes, context: full

#5661 ci: Pass "APIs to check" into the NuGet compatibility check
  detect-pr-changes.sh
Labels: cla: yes

#5662 chore: Remove generation tweaking scripts for Google.Cloud.Container.V1
  apis/Google.Cloud.Container.V1/postgeneration.sh
  apis/Google.Cloud.Container.V1/pregeneration.sh
Labels: cla: yes

#5656 docs: Fix a link in the Firestore docs
  apis/Google.Cloud.Firestore/docs/index.md
Labels: cla: yes

#5663 docs: Hack to make sure we generate ASP.NET Core 3 diagnostics snippets
  tools/Google.Cloud.Tools.GenerateSnippetMarkdown/Program.cs
Labels: cla: yes

#5665 Release version 4.2.0 of all diagnostics packages
  README.md
  apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore.csproj
  apis/Google.Cloud.Diagnostics.AspNetCore/docs/history.md
  apis/Google.Cloud.Diagnostics.AspNetCore3/Google.Cloud.Diagnostics.AspNetCore3/Google.Cloud.Diagnostics.AspNetCore3.csproj
  apis/Google.Cloud.Diagnostics.AspNetCore3/docs/history.md
  apis/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common.IntegrationTests/Google.Cloud.Diagnostics.Common.IntegrationTests.csproj
  apis/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common.Tests/Google.Cloud.Diagnostics.Common.Tests.csproj
  apis/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common.csproj
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5668 [apis/Google.Analytics.Admin.V1Alpha] chore: migrate analytics to the Java microgenerator
  apis/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha.Tests/AnalyticsAdminServiceClientTest.g.cs
  apis/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha/Resources.cs
  apis/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha/ResourcesResourceNames.g.cs
  apis/Google.Analytics.Admin.V1Alpha/synth.metadata
Labels: cla: yes, context: full

#5670 Don't build dependencies for the DevSite docs upload
  tools/Google.Cloud.Tools.GenerateDocfxSources/Program.cs
  uploaddocs.sh
Labels: cla: yes

#5669 [apis/Google.Cloud.VideoIntelligence.V1] fix:Introduce tracks and thumbnails fields for FaceDetectionAnnotations proto.
  apis/Google.Cloud.VideoIntelligence.V1/Google.Cloud.VideoIntelligence.V1/VideoIntelligence.cs
  apis/Google.Cloud.VideoIntelligence.V1/synth.metadata
Labels: cla: yes, context: full

#5676 Require a client to be specified in all smoke tests
  apis/Google.Cloud.Asset.V1/smoketests.json
  apis/Google.Cloud.BigQuery.DataTransfer.V1/smoketests.json
  apis/Google.Cloud.Container.V1/smoketests.json
  apis/Google.Cloud.Language.V1/smoketests.json
  apis/Google.Cloud.Redis.V1/smoketests.json
  apis/Google.Cloud.Redis.V1Beta1/smoketests.json
  apis/Google.Cloud.SecretManager.V1Beta1/smoketests.json
  apis/Google.Cloud.Speech.V1/smoketests.json
  apis/Google.Cloud.Speech.V1P1Beta1/smoketests.json
  apis/Google.Cloud.VideoIntelligence.V1/smoketests.json
  tools/Google.Cloud.Tools.ReleaseManager/SmokeTest.cs
Labels: cla: yes

#5678 Give some hints about how to fix smoke tests
  NEWAPI.md
Labels: cla: yes

#5680 Make the AccessApproval "mid-generation" script executable
  apis/Google.Cloud.AccessApproval.V1/midmicrogeneration.sh
Labels: cla: yes

#5685 [apis/Google.Cloud.Bigtable.V2] feat: migrate bigtable retry/timeout settings to gRPC's service configs
  apis/Google.Cloud.Bigtable.V2/Google.Cloud.Bigtable.V2/BigtableServiceApiClient.g.cs
  apis/Google.Cloud.Bigtable.V2/synth.metadata
Labels: cla: yes, context: full

#5684 [apis/Google.Cloud.Bigtable.Admin.V2] feat: migrate bigtable retry/timeout settings to gRPC's service configs
  apis/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2/BigtableInstanceAdminClient.g.cs
  apis/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2/BigtableTableAdminClient.g.cs
  apis/Google.Cloud.Bigtable.Admin.V2/synth.metadata
Labels: cla: yes, context: full

#5686 [apis/ServiceDirectory] feat: added API files, GAPIC configuration and BUILD.bazel for Network Connectivity API
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5690 [apis/ServiceDirectory] feat!: Remove Cloud Asset v1beta1 support.
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5691 Exclude ServiceDirectory from the list of APIs when diffing
  detect-pr-changes.sh
Labels: cla: yes

#5692 Add smoke test for AccessApproval
  apis/Google.Cloud.AccessApproval.V1/smoketests.json
Labels: cla: yes

#5693 Release Spanner libraries version 3.4.0
  README.md
  apis/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1.csproj
  apis/Google.Cloud.Spanner.Admin.Instance.V1/Google.Cloud.Spanner.Admin.Instance.V1/Google.Cloud.Spanner.Admin.Instance.V1.csproj
  apis/Google.Cloud.Spanner.Common.V1/Google.Cloud.Spanner.Common.V1/Google.Cloud.Spanner.Common.V1.csproj
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.csproj
  apis/Google.Cloud.Spanner.Data/docs/history.md
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1.csproj
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5699 Re-generated apis/ServiceDirectory to pick up changes in APIs
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5698 [apis/Google.Cloud.SecurityCenter.V1] feat: added field severity to findings in v1 API
  apis/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1.Tests/SecurityCenterClientTest.g.cs
  apis/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1/Finding.cs
  apis/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1/NotificationConfig.cs
  apis/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1/SecurityCenterClient.g.cs
  apis/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1/SecuritycenterService.cs
  apis/Google.Cloud.SecurityCenter.V1/synth.metadata
Labels: cla: yes, context: full

#5701 Release Google.Cloud.Retail.V2 version 1.0.0-beta01
  apis/Google.Cloud.Retail.V2/smoketests.json
Labels: autorelease: pending, cla: yes

#5702 docs: Improve the playbook for adding a new API
  ENVIRONMENT.md
  NEWAPI.md
  docker/Dockerfile
Labels: cla: yes

#5703 Release Google.Cloud.Domains.V1Beta1 version 1.0.0-beta01
  README.md
  apis/Google.Cloud.Domains.V1Beta1/.repo-metadata.json
  apis/Google.Cloud.Domains.V1Beta1/Google.Cloud.Domains.V1Beta1/Google.Cloud.Domains.V1Beta1.csproj
  apis/Google.Cloud.Domains.V1Beta1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5706 [apis/ServiceDirectory] feat: public protos for API Gateway API
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5707 Provide notes around using git inside/outside Docker
  ENVIRONMENT.md
  NEWAPI.md
  PROCESSES.md
Labels: cla: yes

#5708 [apis/Google.Cloud.Recommender.V1] feat: Add support for "billingAccounts" as another parent resource name for recommendations and insights APIs.
  apis/Google.Cloud.Recommender.V1/Google.Cloud.Recommender.V1/Insight.cs
  apis/Google.Cloud.Recommender.V1/Google.Cloud.Recommender.V1/InsightResourceNames.g.cs
  apis/Google.Cloud.Recommender.V1/Google.Cloud.Recommender.V1/Recommendation.cs
  apis/Google.Cloud.Recommender.V1/Google.Cloud.Recommender.V1/RecommendationResourceNames.g.cs
  apis/Google.Cloud.Recommender.V1/Google.Cloud.Recommender.V1/RecommenderClient.g.cs
  apis/Google.Cloud.Recommender.V1/Google.Cloud.Recommender.V1/RecommenderService.cs
  apis/Google.Cloud.Recommender.V1/synth.metadata
Labels: cla: yes, context: full

#5710 [apis/ServiceDirectory] feat: add schema service
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5711 Fully-qualify System.Text.Encoding to avoid naming collisions
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/PublisherClient.cs
Labels: cla: yes

#5712 [apis/Google.Cloud.PubSub.V1] feat: add schema service
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1.Snippets/PublisherServiceApiClientSnippets.g.cs
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1.Snippets/SchemaServiceClientSnippets.g.cs
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1.Tests/PublisherServiceApiClientTest.g.cs
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1.Tests/SchemaServiceClientTest.g.cs
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/PublisherServiceApiClient.g.cs
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/Pubsub.cs
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/PubsubGrpc.cs
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/PubsubResourceNames.g.cs
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/Schema.cs
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/SchemaGrpc.cs
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/SchemaResourceNames.g.cs
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/SchemaServiceClient.g.cs
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/SubscriberServiceApiClient.g.cs
  apis/Google.Cloud.PubSub.V1/synth.metadata
Labels: cla: yes, context: full

#5714 fix: Fix the build by disambiguating Encoding
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.IntegrationTests/NotificationsTest.cs
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.Snippets/StorageClientSnippets.cs
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.Snippets/StorageSnippetFixture.cs
Labels: cla: yes

#5717 [apis/Google.Cloud.Dialogflow.Cx.V3] feat: add experiment and API docs: update comments on parameters and agent
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3.Snippets/ExperimentsClientSnippets.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3.Tests/ExperimentsClientTest.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Experiment.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/ExperimentGrpc.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/ExperimentResourceNames.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/ExperimentsClient.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Session.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/SessionGrpc.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/SessionsClient.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/synth.metadata
Labels: cla: yes, context: full

#5718 [apis/Google.Cloud.Dialogflow.V2] docs: update comments on parameters and validation result.
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/Context.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/Session.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/ValidationResult.cs
  apis/Google.Cloud.Dialogflow.V2/synth.metadata
Labels: cla: yes, context: full

#5720 [apis/ServiceDirectory] chore: Fix C# and PHP namespaces and Ruby package
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full
