Repository googleapis/google-cloud-dotnet, pull requests merged in 2020-05, with the labels that each got.

#4925 Release Google.Cloud.Dataproc.V1 version 2.1.0
  README.md
  apis/Google.Cloud.Dataproc.V1/Google.Cloud.Dataproc.V1/Google.Cloud.Dataproc.V1.csproj
  apis/Google.Cloud.Dataproc.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#4926 fix: move third party code to third_party directory
  third_party/docfx/LICENSE
  third_party/docfx/README.md
  third_party/docfx/templates/custom/partials/class.tmpl.partial
  third_party/docfx/templates/devsite/README.md
  third_party/docfx/templates/devsite/layout/_master.tmpl
  third_party/docfx/templates/devsite/partials/class.header.tmpl.partial
  third_party/docfx/templates/devsite/partials/class.tmpl.partial
  third_party/docfx/templates/devsite/partials/head.tmpl.partial
  third_party/docfx/templates/devsite/partials/li.tmpl.partial
  third_party/docfx/templates/devsite/partials/namespace.tmpl.partial
  third_party/docfx/templates/devsite/partials/scripts.tmpl.partial
  third_party/docfx/templates/devsite/toc.html.tmpl
  tools/Google.Cloud.Tools.GenerateDocfxSources/Program.cs
Labels: cla: yes

#4928 feat: add support for spanner emulator detection in clients
  apis/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1/DatabaseAdminClientBuilder.cs
  apis/Google.Cloud.Spanner.Admin.Instance.V1/Google.Cloud.Spanner.Admin.Instance.V1/InstanceAdminClientBuilder.cs
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/SpannerClientBuilder.cs
Labels: api: spanner, cla: yes

#4929 Fix the autorelease reporter script
  .kokoro/autorelease.sh
Labels: cla: yes

#4930 Release Google.Cloud.Bigtable.Admin.V2 version 2.1.0
  README.md
  apis/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2.Snippets/coverage.xml
  apis/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2.Tests/coverage.xml
  apis/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2.csproj
  apis/Google.Cloud.Bigtable.Admin.V2/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#4931 Change Bigtable dependency on Bigtable.Common to be a NuGet dependency
  apis/Google.Cloud.Bigtable.V2/Google.Cloud.Bigtable.V2.IntegrationTests/coverage.xml
  apis/Google.Cloud.Bigtable.V2/Google.Cloud.Bigtable.V2.Snippets/coverage.xml
  apis/Google.Cloud.Bigtable.V2/Google.Cloud.Bigtable.V2.Tests/coverage.xml
  apis/Google.Cloud.Bigtable.V2/Google.Cloud.Bigtable.V2/Google.Cloud.Bigtable.V2.csproj
  apis/apis.json
Labels: cla: yes

#4934 Generate devsite docs at the same time as the regular ones
  docs/builddocs.sh
  tools/Google.Cloud.Tools.GenerateDocfxSources/Program.cs
Labels: cla: yes

#4936 Release Google.Cloud.Dialogflow.V2 version 3.0.0-beta02
  README.md
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2.csproj
  apis/Google.Cloud.Dialogflow.V2/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#4938 [apis/Google.Cloud.Dialogflow.V2] docs: minor comments change.
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/AudioConfig.cs
  apis/Google.Cloud.Dialogflow.V2/synth.metadata
Labels: cla: yes, context: full

#4937 [apis/Google.Cloud.Datastore.V1] Fix documentation for string_value. The value does not have to be at least 1MB, but rather, at most 1MB.
  apis/Google.Cloud.Datastore.V1/Google.Cloud.Datastore.V1/Entity.cs
  apis/Google.Cloud.Datastore.V1/synth.metadata
Labels: cla: yes, context: full

#4940 Fix issue where root doesn't have a devsite equivalent
  docs/builddocs.sh
Labels: cla: yes

#4944 [apis/Google.Cloud.Monitoring.V3] BREAKING_CHANGE: Removing TimeSeriesQueryLanguageCondition as an alert condition type. The condition type is unsupported and unused. It was originally added for the Monitoring Query Language Alpha feature.
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3/Alert.cs
  apis/Google.Cloud.Monitoring.V3/synth.metadata
Labels: cla: yes, context: full

#4945 Release Google.Cloud.Monitoring.V3 version 2.1.0-beta01
  README.md
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3.csproj
  apis/Google.Cloud.Monitoring.V3/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#4947 Create CODEOWNERS
  .github/CODEOWNERS
Labels: cla: yes

#4950 [apis/Google.Cloud.SecretManager.V1Beta1] Update documentation
  apis/Google.Cloud.SecretManager.V1Beta1/Google.Cloud.SecretManager.V1Beta1/SecretManagerServiceClient.g.cs
  apis/Google.Cloud.SecretManager.V1Beta1/Google.Cloud.SecretManager.V1Beta1/Service.cs
  apis/Google.Cloud.SecretManager.V1Beta1/Google.Cloud.SecretManager.V1Beta1/ServiceGrpc.cs
  apis/Google.Cloud.SecretManager.V1Beta1/synth.metadata
Labels: cla: yes, context: full

#4951 Fix a warning spotted during docfx builds
  docs/builddocs.sh
Labels: cla: yes

#4952 Make sure we have docs for Google.Api.Gax.Grpc
  tools/Google.Cloud.Tools.GenerateDocfxSources/Project.cs
Labels: cla: yes

#4953 [apis/Google.Cloud.DataCatalog.V1] chore: enable gapicv2 for datacatalog/v1beta1 API
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1.Snippets/DataCatalogClientSnippets.g.cs
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1.Tests/DataCatalogClientTest.g.cs
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/DataCatalogClient.g.cs
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/Datacatalog.cs
  apis/Google.Cloud.DataCatalog.V1/synth.metadata
Labels: cla: yes, context: full

#4955 [apis/Google.Cloud.PubSub.V1] Removing the experimental tag from dead letter policy related fields.
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/Pubsub.cs
  apis/Google.Cloud.PubSub.V1/synth.metadata
Labels: cla: yes, context: full

#4954 [apis/Google.Cloud.Dlp.V2] Release new file type enums and new MetadataLocation proto.
  apis/Google.Cloud.Dlp.V2/Google.Cloud.Dlp.V2/Dlp.cs
  apis/Google.Cloud.Dlp.V2/Google.Cloud.Dlp.V2/DlpResourceNames.g.cs
  apis/Google.Cloud.Dlp.V2/Google.Cloud.Dlp.V2/DlpServiceClient.g.cs
  apis/Google.Cloud.Dlp.V2/Google.Cloud.Dlp.V2/Storage.cs
  apis/Google.Cloud.Dlp.V2/synth.metadata
Labels: cla: yes, context: full

#4957 Release Firestore libraries version 2.0.0
  README.md
  apis/Google.Cloud.Firestore.V1/Google.Cloud.Firestore.V1/Google.Cloud.Firestore.V1.csproj
  apis/Google.Cloud.Firestore.V1/docs/history.md
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore/Google.Cloud.Firestore.csproj
  apis/Google.Cloud.Firestore/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#4958 Release Google.Cloud.Storage.V1 version 3.0.0
  README.md
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.csproj
  apis/Google.Cloud.Storage.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#4961 [apis/Google.Cloud.Dlp.V2] Cloud DLP - fix routing for gRPC clients by embedding location into parent instead of having it's own parameter. API still remain global only, but prepares for the addition of regional support.
  apis/Google.Cloud.Dlp.V2/Google.Cloud.Dlp.V2.Snippets/DlpServiceClientSnippets.g.cs
  apis/Google.Cloud.Dlp.V2/Google.Cloud.Dlp.V2.Tests/DlpServiceClientTest.g.cs
  apis/Google.Cloud.Dlp.V2/Google.Cloud.Dlp.V2/Dlp.cs
  apis/Google.Cloud.Dlp.V2/Google.Cloud.Dlp.V2/DlpServiceClient.g.cs
  apis/Google.Cloud.Dlp.V2/synth.metadata
Labels: cla: yes, context: full

#4962 [apis/Google.Cloud.SecretManager.V1] Update documentation
  apis/Google.Cloud.SecretManager.V1/Google.Cloud.SecretManager.V1/Resources.cs
  apis/Google.Cloud.SecretManager.V1/Google.Cloud.SecretManager.V1/ServiceGrpc.cs
  apis/Google.Cloud.SecretManager.V1/synth.metadata
Labels: cla: yes, context: full

#4964 Temporary command to write service directory data
  apis/ServiceDirectory/README.md
  apis/ServiceDirectory/synth.py
  build.sh
  tools/Google.Cloud.Tools.ReleaseManager/WriteServiceDirectoryCommand.cs
Labels: cla: yes

#4968 Provide a synth.metadata as a starting point
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes

#4969 [CHANGE ME] Re-generated apis/ServiceDirectory to pick up changes in the API or client library generator.
  apis/ServiceDirectory/directory.json
Labels: cla: yes, context: none

#4972 Fix dependency calculations for docfx generation
  tools/Google.Cloud.Tools.GenerateDocfxSources/Program.cs
  tools/Google.Cloud.Tools.GenerateDocfxSources/Project.cs
Labels: cla: yes

#4974 [apis/Google.Cloud.Asset.V1] cloudasset: add SearchAllResources and SearchAllIamPolicies RPCs
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1.Snippets/AssetServiceClientSnippets.g.cs
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1/AssetService.cs
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1/AssetServiceClient.g.cs
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1/AssetServiceGrpc.cs
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1/Assets.cs
  apis/Google.Cloud.Asset.V1/synth.metadata
Labels: cla: yes, context: full

#4976 Convert BigQuery field validation from a regex to hand-written code
  apis/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2.Benchmarks/Google.Cloud.BigQuery.V2.Benchmarks.csproj
  apis/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2.Benchmarks/TableSchemaBuilderBenchmark.cs
  apis/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2/AssemblyInfo.cs
  apis/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2/BigQueryNumeric.cs
  apis/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2/TableSchemaBuilder.cs
Labels: cla: yes

#4977 [apis/Google.Cloud.Dialogflow.V2] Dialogflow weekly v2 library update:
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/Environment.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/Intent.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/Session.cs
  apis/Google.Cloud.Dialogflow.V2/synth.metadata
Labels: cla: yes, context: full

#4978 [apis/ServiceDirectory] feat(v1p3beta1): added support for streaming automl action recognition.
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#4979 [Storage] Simple Post Policy snippet now adds a custom Google metadata field.
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.Snippets/UrlSignerSnippets.cs
Labels: cla: yes

#4980 [apis/ServiceDirectory] Export protos for pubsublite.googleapis.com.
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#4982 [apis/Google.Cloud.Bigtable.V2] Update bigtable grpc service config
  apis/Google.Cloud.Bigtable.V2/Google.Cloud.Bigtable.V2/BigtableServiceApiClient.g.cs
  apis/Google.Cloud.Bigtable.V2/synth.metadata
Labels: cla: yes, context: full

#4985 [apis/Google.Cloud.Spanner.Admin.Database.V1] Update grpc config files to be consistent.
  apis/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1/DatabaseAdminClient.g.cs
  apis/Google.Cloud.Spanner.Admin.Database.V1/synth.metadata
Labels: cla: yes, context: full

#4986 [apis/Google.Cloud.Spanner.Admin.Instance.V1] Update grpc config files to be consistent.
  apis/Google.Cloud.Spanner.Admin.Instance.V1/Google.Cloud.Spanner.Admin.Instance.V1/InstanceAdminClient.g.cs
  apis/Google.Cloud.Spanner.Admin.Instance.V1/synth.metadata
Labels: cla: yes, context: full

#4987 [apis/Google.Cloud.Spanner.V1] Update grpc config files to be consistent.
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/SpannerClient.g.cs
  apis/Google.Cloud.Spanner.V1/synth.metadata
Labels: cla: yes, context: full

#4991 [apis/Google.Cloud.PubSub.V1] Add DetachSubscription RPC
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1.Snippets/PublisherServiceApiClientSnippets.g.cs
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1.Tests/PublisherServiceApiClientTest.g.cs
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/PublisherServiceApiClient.g.cs
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/Pubsub.cs
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/PubsubGrpc.cs
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/PubsubResourceNames.g.cs
  apis/Google.Cloud.PubSub.V1/synth.metadata
Labels: cla: yes, context: full

#4990 [apis/Google.Cloud.Asset.V1] docs: Properly format literal strings.
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1/Assets.cs
  apis/Google.Cloud.Asset.V1/synth.metadata
Labels: cla: yes, context: full

#4994 [apis/Google.Cloud.PubSub.V1] Use correct resource type for DetachSubscriptionRequest
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1.Snippets/PublisherServiceApiClientSnippets.g.cs
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1.Tests/PublisherServiceApiClientTest.g.cs
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/Pubsub.cs
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/PubsubResourceNames.g.cs
  apis/Google.Cloud.PubSub.V1/synth.metadata
Labels: cla: yes, context: full

#4915 feat: spanner emulator support
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.CommonTesting/SpannerTestDatabase.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.Tests/SpannerCommandTests.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.Tests/SpannerConnectionStringBuilderTests.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/SessionPoolManager.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/SpannerClientCreationOptions.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/SpannerCommand.ExecutableCommand.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/SpannerConnectionStringBuilder.cs
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/SpannerClientBuilder.cs
Labels: api: spanner, cla: yes

#4998 Release Google.Cloud.Storage.V1 version 3.1.0
  README.md
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.csproj
  apis/Google.Cloud.Storage.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#4995 Use custom SessionPoolOptions for emulator clients
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.Tests/SpannerCommandTests.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/SessionPoolManager.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/SpannerClientCreationOptions.cs
Labels: cla: yes

#4996 Testable emulator detection
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.Tests/SessionPoolManagerTests.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.Tests/SpannerCommandTests.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/SpannerClientCreationOptions.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/SpannerConnectionStringBuilder.cs
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/SpannerClientBuilder.cs
Labels: cla: yes

#5004 [CHANGE ME] Re-generated apis/Google.Cloud.PubSub.V1 to pick up changes in the API or client library generator.
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/Pubsub.cs
  apis/Google.Cloud.PubSub.V1/synth.metadata
Labels: cla: yes, context: full
