Repository googleapis/google-cloud-dotnet, pull requests merged in 2020-11, with the labels that each got.

#5508 Update our PROCESSES documentation to clarify releasing.
  PROCESSES.md
Labels: cla: yes

#5510 [apis/ServiceDirectory] feat: Initial API proto for Dialogflow CX client library (GA).
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5509 [apis/Google.Analytics.Data.V1Alpha] docs: App+Web properties renamed to GA4
  apis/Google.Analytics.Data.V1Alpha/Google.Analytics.Data.V1Alpha/AlphaAnalyticsDataClient.g.cs
  apis/Google.Analytics.Data.V1Alpha/Google.Analytics.Data.V1Alpha/AnalyticsDataApi.cs
  apis/Google.Analytics.Data.V1Alpha/Google.Analytics.Data.V1Alpha/AnalyticsDataApiGrpc.cs
  apis/Google.Analytics.Data.V1Alpha/Google.Analytics.Data.V1Alpha/Data.cs
  apis/Google.Analytics.Data.V1Alpha/synth.metadata
Labels: cla: yes, context: full

#5511 Add tool to detect misconfigured proto namespaces
  tools/Google.Cloud.Tools.ReleaseManager/DetectNamingAnomaliesCommand.cs
Labels: cla: yes

#5512 [apis/ServiceDirectory] chore: Remove protos for Google Ads API v2, which has sunset and is no longer available.
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5513 [apis/Google.Analytics.Data.V1Alpha] feat: added RunRealtimeReport method that returns a customized report of realtime event data for a GA4 property docs: minor documentation updates
  apis/Google.Analytics.Data.V1Alpha/Google.Analytics.Data.V1Alpha.Snippets/AlphaAnalyticsDataClientSnippets.g.cs
  apis/Google.Analytics.Data.V1Alpha/Google.Analytics.Data.V1Alpha.Tests/AlphaAnalyticsDataClientTest.g.cs
  apis/Google.Analytics.Data.V1Alpha/Google.Analytics.Data.V1Alpha/AlphaAnalyticsDataClient.g.cs
  apis/Google.Analytics.Data.V1Alpha/Google.Analytics.Data.V1Alpha/AnalyticsDataApi.cs
  apis/Google.Analytics.Data.V1Alpha/Google.Analytics.Data.V1Alpha/AnalyticsDataApiGrpc.cs
  apis/Google.Analytics.Data.V1Alpha/Google.Analytics.Data.V1Alpha/Data.cs
  apis/Google.Analytics.Data.V1Alpha/synth.metadata
Labels: cla: yes, context: full

#5514 [apis/Google.Cloud.Billing.Budgets.V1] docs: Reworded comments for the new credit types filter
  apis/Google.Cloud.Billing.Budgets.V1/Google.Cloud.Billing.Budgets.V1/BudgetModel.cs
  apis/Google.Cloud.Billing.Budgets.V1/synth.metadata
Labels: cla: yes, context: full

#5515 [apis/Google.Cloud.DocumentAI.V1Beta2] chore: Fix namespaces for Ruby, PHP, and C# clients
  apis/Google.Cloud.DocumentAI.V1Beta2/Google.Cloud.DocumentAI.V1Beta2/Document.cs
  apis/Google.Cloud.DocumentAI.V1Beta2/Google.Cloud.DocumentAI.V1Beta2/DocumentUnderstanding.cs
  apis/Google.Cloud.DocumentAI.V1Beta2/Google.Cloud.DocumentAI.V1Beta2/Geometry.cs
  apis/Google.Cloud.DocumentAI.V1Beta2/synth.metadata
Labels: cla: yes, context: full

#5516 [apis/Google.Cloud.ManagedIdentities.V1] chore: Set namespaces for PHP and Ruby clients
  apis/Google.Cloud.ManagedIdentities.V1/Google.Cloud.ManagedIdentities.V1/ManagedIdentitiesService.cs
  apis/Google.Cloud.ManagedIdentities.V1/Google.Cloud.ManagedIdentities.V1/Resource.cs
  apis/Google.Cloud.ManagedIdentities.V1/synth.metadata
Labels: cla: yes, context: full

#5517 Re-generated apis/ServiceDirectory with namespace changes
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5520 Release Google.Analytics.Admin.V1Alpha version 1.0.0-alpha02
  README.md
  apis/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha.csproj
  apis/Google.Analytics.Admin.V1Alpha/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5522 Release Google.Analytics.Data.V1Alpha version 1.0.0-alpha02
  README.md
  apis/Google.Analytics.Data.V1Alpha/Google.Analytics.Data.V1Alpha/Google.Analytics.Data.V1Alpha.csproj
  apis/Google.Analytics.Data.V1Alpha/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5525 Fix description for binary authorization API
  apis/Google.Cloud.BinaryAuthorization.V1Beta1/Google.Cloud.BinaryAuthorization.V1Beta1/Google.Cloud.BinaryAuthorization.V1Beta1.csproj
  apis/apis.json
Labels: cla: yes

#5526 Release Google.Cloud.Recommender.V1 version 2.3.0
  README.md
  apis/Google.Cloud.Recommender.V1/Google.Cloud.Recommender.V1/Google.Cloud.Recommender.V1.csproj
  apis/Google.Cloud.Recommender.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5527 chore: add blunderbuss
  .github/blunderbuss.yml
Labels: api: logging, cla: yes, priority: p2, type: process

#5529 [apis/Google.Analytics.Admin.V1Alpha] fix: 'requests' field of CreateUserLink, UpdateUserLink, DeleteUserLink methods is now required docs: minor documentation updates
  apis/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha.Snippets/AnalyticsAdminServiceClientSnippets.g.cs
  apis/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha.Tests/AnalyticsAdminServiceClientTest.g.cs
  apis/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha/AnalyticsAdmin.cs
  apis/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha/AnalyticsAdminResourceNames.g.cs
  apis/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha/AnalyticsAdminServiceClient.g.cs
  apis/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha/Resources.cs
  apis/Google.Analytics.Admin.V1Alpha/synth.metadata
Labels: cla: yes, context: full

#5531 [apis/ServiceDirectory] chore: Set namespaces for Ruby, PHP, and C# clients
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5532 [apis/Google.Cloud.ServiceManagement.V1] chore: Set namespaces for Ruby clients
  apis/Google.Cloud.ServiceManagement.V1/Google.Cloud.ServiceManagement.V1/Resources.cs
  apis/Google.Cloud.ServiceManagement.V1/Google.Cloud.ServiceManagement.V1/Servicemanager.cs
  apis/Google.Cloud.ServiceManagement.V1/synth.metadata
Labels: cla: yes, context: full

#5533 Release Google.Cloud.PolicyTroubleshooter.V1 version 1.0.0
  README.md
  apis/Google.Cloud.PolicyTroubleshooter.V1/.repo-metadata.json
  apis/Google.Cloud.PolicyTroubleshooter.V1/Google.Cloud.PolicyTroubleshooter.V1/Google.Cloud.PolicyTroubleshooter.V1.csproj
  apis/Google.Cloud.PolicyTroubleshooter.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5535 Release Google.Cloud.Redis.V1 version 2.1.0
  README.md
  apis/Google.Cloud.Redis.V1/Google.Cloud.Redis.V1/Google.Cloud.Redis.V1.csproj
  apis/Google.Cloud.Redis.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5537 Release Google.Cloud.Scheduler.V1 version 2.1.0
  README.md
  apis/Google.Cloud.Scheduler.V1/Google.Cloud.Scheduler.V1/Google.Cloud.Scheduler.V1.csproj
  apis/Google.Cloud.Scheduler.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5538 Release Google.Cloud.SecretManager.V1 version 1.2.0
  README.md
  apis/Google.Cloud.SecretManager.V1/Google.Cloud.SecretManager.V1/Google.Cloud.SecretManager.V1.csproj
  apis/Google.Cloud.SecretManager.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5539 [apis/ServiceDirectory] feat: Add Service Directory v1 protos and configs
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5540 [apis/Google.Cloud.Billing.Budgets.V1Beta1] docs: Reworded comments for the new credit types filter
  apis/Google.Cloud.Billing.Budgets.V1Beta1/Google.Cloud.Billing.Budgets.V1Beta1/BudgetModel.cs
  apis/Google.Cloud.Billing.Budgets.V1Beta1/synth.metadata
Labels: cla: yes, context: full

#5541 [apis/ServiceDirectory] feat: Publish Google Ads API v6 protos and config files.
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5528 feat: Enable server side flow control by default with the option to turn it off
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/SubscriberClient.cs
Labels: cla: yes

#5543 Release Google.Cloud.SecurityCenter.V1 version 2.1.0
  README.md
  apis/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1.csproj
  apis/Google.Cloud.SecurityCenter.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5544 Release Google.Cloud.Speech.V1 version 2.1.0
  README.md
  apis/Google.Cloud.Speech.V1/Google.Cloud.Speech.V1/Google.Cloud.Speech.V1.csproj
  apis/Google.Cloud.Speech.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5546 Release Google.Cloud.Tasks.V2 version 2.1.0
  README.md
  apis/Google.Cloud.Tasks.V2/Google.Cloud.Tasks.V2/Google.Cloud.Tasks.V2.csproj
  apis/Google.Cloud.Tasks.V2/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5547 Release Google.Cloud.TextToSpeech.V1 version 2.1.0
  README.md
  apis/Google.Cloud.TextToSpeech.V1/Google.Cloud.TextToSpeech.V1/Google.Cloud.TextToSpeech.V1.csproj
  apis/Google.Cloud.TextToSpeech.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5549 Release Google.Cloud.Trace.V1 version 2.1.0
  README.md
  apis/Google.Cloud.Trace.V1/Google.Cloud.Trace.V1/Google.Cloud.Trace.V1.csproj
  apis/Google.Cloud.Trace.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5550 [Storage]: Skips tests that depend on a missing bucket.
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.IntegrationTests/DownloadObjectTest.cs
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.IntegrationTests/NormalizationTest.cs
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.IntegrationTests/UnauthenticatedAccessTest.cs
Labels: cla: yes

#5551 [apis/ServiceDirectory] fix: Remove redundant service config files.
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5552 Release Google.Cloud.Trace.V2 version 2.1.0
  README.md
  apis/Google.Cloud.Trace.V2/Google.Cloud.Trace.V2/Google.Cloud.Trace.V2.csproj
  apis/Google.Cloud.Trace.V2/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5553 Release Google.Cloud.Translate.V3 version 2.1.0
  README.md
  apis/Google.Cloud.Translate.V3/Google.Cloud.Translate.V3/Google.Cloud.Translate.V3.csproj
  apis/Google.Cloud.Translate.V3/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5554 Release Google.Cloud.Vision.V1 version 2.1.0
  README.md
  apis/Google.Cloud.Vision.V1/Google.Cloud.Vision.V1/Google.Cloud.Vision.V1.csproj
  apis/Google.Cloud.Vision.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5555 Release Google.Cloud.WebRisk.V1 version 1.1.0
  README.md
  apis/Google.Cloud.WebRisk.V1/Google.Cloud.WebRisk.V1/Google.Cloud.WebRisk.V1.csproj
  apis/Google.Cloud.WebRisk.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5556 [apis/Google.Analytics.Data.V1Alpha] fix!: GetUniversalMetadata method removed from the API, GetMetadata method should be used instead feat: reporting requests now support date ranges longer than one year docs: minor documentation updates
  apis/Google.Analytics.Data.V1Alpha/Google.Analytics.Data.V1Alpha.Snippets/AlphaAnalyticsDataClientSnippets.g.cs
  apis/Google.Analytics.Data.V1Alpha/Google.Analytics.Data.V1Alpha.Tests/AlphaAnalyticsDataClientTest.g.cs
  apis/Google.Analytics.Data.V1Alpha/Google.Analytics.Data.V1Alpha/AlphaAnalyticsDataClient.g.cs
  apis/Google.Analytics.Data.V1Alpha/Google.Analytics.Data.V1Alpha/AnalyticsDataApi.cs
  apis/Google.Analytics.Data.V1Alpha/Google.Analytics.Data.V1Alpha/AnalyticsDataApiGrpc.cs
  apis/Google.Analytics.Data.V1Alpha/Google.Analytics.Data.V1Alpha/Data.cs
  apis/Google.Analytics.Data.V1Alpha/synth.metadata
Labels: cla: yes, context: full

#5557 [apis/Google.Cloud.OsConfig.V1] feat: Added PatchRollout feature to PatchDeployments feat: Added Inventory proto definitions for VM Manager Inventory.
  apis/Google.Cloud.OsConfig.V1/Google.Cloud.OsConfig.V1.Snippets/OsConfigServiceClientSnippets.g.cs
  apis/Google.Cloud.OsConfig.V1/Google.Cloud.OsConfig.V1.Tests/OsConfigServiceClientTest.g.cs
  apis/Google.Cloud.OsConfig.V1/Google.Cloud.OsConfig.V1/Inventory.cs
  apis/Google.Cloud.OsConfig.V1/Google.Cloud.OsConfig.V1/OsConfigServiceClient.g.cs
  apis/Google.Cloud.OsConfig.V1/Google.Cloud.OsConfig.V1/OsconfigCommon.cs
  apis/Google.Cloud.OsConfig.V1/Google.Cloud.OsConfig.V1/PatchDeployments.cs
  apis/Google.Cloud.OsConfig.V1/Google.Cloud.OsConfig.V1/PatchJobs.cs
  apis/Google.Cloud.OsConfig.V1/synth.metadata
Labels: cla: yes, context: full

#5558 Re-generated apis/ServiceDirectory to pick up API changes
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5559 Remove now-unnecessary patch scripts for RecommendationEngine
  apis/Google.Cloud.RecommendationEngine.V1Beta1/postgeneration.sh
  apis/Google.Cloud.RecommendationEngine.V1Beta1/pregeneration.sh
Labels: cla: yes

#5560 Release new version of all OsLogin packages
  README.md
  apis/Google.Cloud.OsLogin.Common/Google.Cloud.OsLogin.Common/Google.Cloud.OsLogin.Common.csproj
  apis/Google.Cloud.OsLogin.V1/Google.Cloud.OsLogin.V1/Google.Cloud.OsLogin.V1.csproj
  apis/Google.Cloud.OsLogin.V1/docs/history.md
  apis/Google.Cloud.OsLogin.V1Beta/Google.Cloud.OsLogin.V1Beta/Google.Cloud.OsLogin.V1Beta.csproj
  apis/Google.Cloud.OsLogin.V1Beta/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5561 Release Google.Cloud.ErrorReporting.V1Beta1 version 2.0.0-beta03
  README.md
  apis/Google.Cloud.ErrorReporting.V1Beta1/Google.Cloud.ErrorReporting.V1Beta1/Google.Cloud.ErrorReporting.V1Beta1.csproj
  apis/Google.Cloud.ErrorReporting.V1Beta1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5563 Release new version of all OsLogin packages
  apis/Google.Cloud.OsLogin.Common/docs/history.md
  apis/Google.Cloud.OsLogin.V1/docs/history.md
  apis/Google.Cloud.OsLogin.V1Beta/docs/history.md
Labels: autorelease: pending, cla: yes

#5564 Release all OsLogin packages
  apis/Google.Cloud.OsLogin.Common/docs/history.md
  apis/Google.Cloud.OsLogin.V1/docs/history.md
  apis/Google.Cloud.OsLogin.V1Beta/docs/history.md
Labels: autorelease: pending, cla: yes

#5565 [CHANGE ME] Re-generated apis/Google.Cloud.RecommendationEngine.V1Beta1 to pick up changes in the API or client library generator.
  apis/Google.Cloud.RecommendationEngine.V1Beta1/Google.Cloud.RecommendationEngine.V1Beta1/RecommendationengineResources.cs
  apis/Google.Cloud.RecommendationEngine.V1Beta1/synth.metadata
Labels: cla: yes, context: partial

#5566 [apis/ServiceDirectory] fix!: Apply namespace/package options to RecommendationEngine resources proto.
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5567 Release Grafeas and ContainerAnalysis update
  README.md
  apis/Google.Cloud.DevTools.ContainerAnalysis.V1/Google.Cloud.DevTools.ContainerAnalysis.V1/Google.Cloud.DevTools.ContainerAnalysis.V1.csproj
  apis/Google.Cloud.DevTools.ContainerAnalysis.V1/docs/history.md
  apis/Grafeas.V1/Grafeas.V1/Grafeas.V1.csproj
  apis/Grafeas.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5571 Update Google.Cloud.Container.V1
  apis/Google.Cloud.Container.V1/Google.Cloud.Container.V1.Snippets/ClusterManagerClientSnippets.g.cs
  apis/Google.Cloud.Container.V1/Google.Cloud.Container.V1.Tests/ClusterManagerClientTest.g.cs
  apis/Google.Cloud.Container.V1/Google.Cloud.Container.V1/ClusterManagerClient.g.cs
  apis/Google.Cloud.Container.V1/Google.Cloud.Container.V1/ClusterService.cs
  apis/Google.Cloud.Container.V1/Google.Cloud.Container.V1/ClusterServiceGrpc.cs
  apis/Google.Cloud.Container.V1/synth.metadata
  apis/Grafeas.V1/synth.metadata
Labels: cla: yes

#5572 [apis/Google.Cloud.Logging.Type] feat: Makes remaining LogBucket and LogViews methods public
  apis/Google.Cloud.Logging.Type/Google.Cloud.Logging.Type/HttpRequest.cs
  apis/Google.Cloud.Logging.Type/synth.metadata
Labels: cla: yes, context: full

#5573 [apis/Google.Cloud.Logging.V2] feat: Makes remaining LogBucket and LogViews methods public
  apis/Google.Cloud.Logging.V2/Google.Cloud.Logging.V2.Snippets/ConfigServiceV2ClientSnippets.g.cs
  apis/Google.Cloud.Logging.V2/Google.Cloud.Logging.V2.Tests/ConfigServiceV2ClientTest.g.cs
  apis/Google.Cloud.Logging.V2/Google.Cloud.Logging.V2/ConfigServiceV2Client.g.cs
  apis/Google.Cloud.Logging.V2/Google.Cloud.Logging.V2/LoggingConfig.cs
  apis/Google.Cloud.Logging.V2/Google.Cloud.Logging.V2/LoggingConfigGrpc.cs
  apis/Google.Cloud.Logging.V2/Google.Cloud.Logging.V2/LoggingConfigResourceNames.g.cs
  apis/Google.Cloud.Logging.V2/Google.Cloud.Logging.V2/LoggingMetrics.cs
  apis/Google.Cloud.Logging.V2/synth.metadata
Labels: cla: yes, context: full

#5577 test: optimizer version tests did not actually verify the input
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.Tests/SpannerCommandTests.cs
Labels: cla: yes

#5574 [apis/ServiceDirectory] feat: Adding Data QnA v1alpha API.
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5582 Release Google.Cloud.Redis.V1Beta1 version 2.0.0-beta03
  README.md
  apis/Google.Cloud.Redis.V1Beta1/Google.Cloud.Redis.V1Beta1/Google.Cloud.Redis.V1Beta1.csproj
  apis/Google.Cloud.Redis.V1Beta1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5583 test: [Spanner] Fixes retriable transaction test that had become flaky.
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.IntegrationTests/RetriableTransactionTests.cs
Labels: cla: yes

#5584 [apis/Google.Cloud.AssuredWorkloads.V1Beta1] feat: updated google.cloud.assuredworkloads.v1beta1.AssuredWorkloadsService service
  apis/Google.Cloud.AssuredWorkloads.V1Beta1/Google.Cloud.AssuredWorkloads.V1Beta1.Tests/AssuredWorkloadsServiceClientTest.g.cs
  apis/Google.Cloud.AssuredWorkloads.V1Beta1/Google.Cloud.AssuredWorkloads.V1Beta1/AssuredworkloadsV1Beta1.cs
  apis/Google.Cloud.AssuredWorkloads.V1Beta1/synth.metadata
Labels: cla: yes, context: full

#5586 [apis/ServiceDirectory] feat: added support OSInventory in Assets. docs: updated existing docs.
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5587 Release Google.Cloud.OsConfig.V1 version 1.2.0
  README.md
  apis/Google.Cloud.OsConfig.V1/Google.Cloud.OsConfig.V1/Google.Cloud.OsConfig.V1.csproj
  apis/Google.Cloud.OsConfig.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5588 Simplify the "add new API" experience
  tools/Google.Cloud.Tools.ReleaseManager/History/HistoryFile.cs
Labels: cla: yes

#5589 Add OsConfig.V1 dependency to Asset.V1
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1.csproj
  apis/apis.json
Labels: cla: yes

#5590 [apis/Google.Cloud.Asset.V1] feat: added support OSInventory in Assets. docs: updated existing docs.
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1/AssetService.cs
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1/Assets.cs
  apis/Google.Cloud.Asset.V1/synth.metadata
Labels: cla: yes, context: full

#5591 Release Google.Cloud.Asset.V1 version 2.6.0
  README.md
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1.csproj
  apis/Google.Cloud.Asset.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5592 Release Google.Cloud.Billing.Budgets.V1Beta1 version 1.0.0-beta02
  README.md
  apis/Google.Cloud.Billing.Budgets.V1Beta1/Google.Cloud.Billing.Budgets.V1Beta1/Google.Cloud.Billing.Budgets.V1Beta1.csproj
  apis/Google.Cloud.Billing.Budgets.V1Beta1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5593 Release Google.Cloud.Dataproc.V1 version 3.0.0
  README.md
  apis/Google.Cloud.Dataproc.V1/Google.Cloud.Dataproc.V1/Google.Cloud.Dataproc.V1.csproj
  apis/Google.Cloud.Dataproc.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5594 Release Google.Cloud.Firestore.Admin.V1 version 2.1.0
  README.md
  apis/Google.Cloud.Firestore.Admin.V1/Google.Cloud.Firestore.Admin.V1/Google.Cloud.Firestore.Admin.V1.csproj
  apis/Google.Cloud.Firestore.Admin.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5595 Release Google.Cloud.SecretManager.V1Beta1 version 2.0.0-beta03
  README.md
  apis/Google.Cloud.SecretManager.V1Beta1/Google.Cloud.SecretManager.V1Beta1/Google.Cloud.SecretManager.V1Beta1.csproj
  apis/Google.Cloud.SecretManager.V1Beta1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5596 Release Google.Cloud.RecaptchaEnterprise.V1Beta1 version 1.0.0-beta03
  README.md
  apis/Google.Cloud.RecaptchaEnterprise.V1Beta1/Google.Cloud.RecaptchaEnterprise.V1Beta1/Google.Cloud.RecaptchaEnterprise.V1Beta1.csproj
  apis/Google.Cloud.RecaptchaEnterprise.V1Beta1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5597 Release Google.Cloud.Speech.V1P1Beta1 version 2.0.0-beta03
  README.md
  apis/Google.Cloud.Speech.V1P1Beta1/Google.Cloud.Speech.V1P1Beta1/Google.Cloud.Speech.V1P1Beta1.csproj
  apis/Google.Cloud.Speech.V1P1Beta1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5598 Release Google.Cloud.ServiceDirectory.V1Beta1 version 1.0.0-beta03
  README.md
  apis/Google.Cloud.ServiceDirectory.V1Beta1/Google.Cloud.ServiceDirectory.V1Beta1/Google.Cloud.ServiceDirectory.V1Beta1.csproj
  apis/Google.Cloud.ServiceDirectory.V1Beta1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5599 Release Google.Cloud.PhishingProtection.V1Beta1 version 1.0.0-beta03
  README.md
  apis/Google.Cloud.PhishingProtection.V1Beta1/Google.Cloud.PhishingProtection.V1Beta1/Google.Cloud.PhishingProtection.V1Beta1.csproj
  apis/Google.Cloud.PhishingProtection.V1Beta1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5600 Release Google.Cloud.Tasks.V2Beta3 version 2.0.0-beta03
  README.md
  apis/Google.Cloud.Tasks.V2Beta3/Google.Cloud.Tasks.V2Beta3/Google.Cloud.Tasks.V2Beta3.csproj
  apis/Google.Cloud.Tasks.V2Beta3/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5601 Release Google.Cloud.WebRisk.V1Beta1 version 2.0.0-beta03
  README.md
  apis/Google.Cloud.WebRisk.V1Beta1/Google.Cloud.WebRisk.V1Beta1/Google.Cloud.WebRisk.V1Beta1.csproj
  apis/Google.Cloud.WebRisk.V1Beta1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5602 Release Google.Cloud.Memcache.V1Beta2 version 1.0.0-beta03
  README.md
  apis/Google.Cloud.Memcache.V1Beta2/Google.Cloud.Memcache.V1Beta2/Google.Cloud.Memcache.V1Beta2.csproj
  apis/Google.Cloud.Memcache.V1Beta2/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5603 Release Google.Cloud.SecurityCenter.Settings.V1Beta1 version 1.0.0-beta02
  README.md
  apis/Google.Cloud.SecurityCenter.Settings.V1Beta1/Google.Cloud.SecurityCenter.Settings.V1Beta1/Google.Cloud.SecurityCenter.Settings.V1Beta1.csproj
  apis/Google.Cloud.SecurityCenter.Settings.V1Beta1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5604 Release Google.Cloud.Talent.V4Beta1 version 2.0.0-beta04
  README.md
  apis/Google.Cloud.Talent.V4Beta1/Google.Cloud.Talent.V4Beta1/Google.Cloud.Talent.V4Beta1.csproj
  apis/Google.Cloud.Talent.V4Beta1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5605 Release Google.Identity.AccessContextManager.V1 version 1.1.0
  README.md
  apis/Google.Identity.AccessContextManager.V1/Google.Identity.AccessContextManager.V1/Google.Identity.AccessContextManager.V1.csproj
  apis/Google.Identity.AccessContextManager.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5606 Release Google.Cloud.OrgPolicy.V1 version 2.1.0
  README.md
  apis/Google.Cloud.OrgPolicy.V1/Google.Cloud.OrgPolicy.V1/Google.Cloud.OrgPolicy.V1.csproj
  apis/Google.Cloud.OrgPolicy.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5607 Release Google.Cloud.Notebooks.V1Beta1 version 1.0.0-beta02
  README.md
  apis/Google.Cloud.Notebooks.V1Beta1/Google.Cloud.Notebooks.V1Beta1/Google.Cloud.Notebooks.V1Beta1.csproj
  apis/Google.Cloud.Notebooks.V1Beta1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5608 Release Google.Cloud.DocumentAI.V1Beta2 version 1.0.0-beta02
  README.md
  apis/Google.Cloud.DocumentAI.V1Beta2/Google.Cloud.DocumentAI.V1Beta2/Google.Cloud.DocumentAI.V1Beta2.csproj
  apis/Google.Cloud.DocumentAI.V1Beta2/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5609 Release Google.Cloud.Logging.Type version 3.2.0
  README.md
  apis/Google.Cloud.Logging.Type/Google.Cloud.Logging.Type/Google.Cloud.Logging.Type.csproj
  apis/Google.Cloud.Logging.Type/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5610 Release Google.Cloud.Logging.V2 version 3.2.0
  README.md
  apis/Google.Cloud.Logging.V2/Google.Cloud.Logging.V2/Google.Cloud.Logging.V2.csproj
  apis/Google.Cloud.Logging.V2/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5611 Release Google.Cloud.Firestore.V1 version 2.2.0
  README.md
  apis/Google.Cloud.Firestore.V1/Google.Cloud.Firestore.V1/Google.Cloud.Firestore.V1.csproj
  apis/Google.Cloud.Firestore.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5612 Release Google.Cloud.SecurityCenter.V1P1Beta1 version 2.0.0-beta04
  README.md
  apis/Google.Cloud.SecurityCenter.V1P1Beta1/Google.Cloud.SecurityCenter.V1P1Beta1/Google.Cloud.SecurityCenter.V1P1Beta1.csproj
  apis/Google.Cloud.SecurityCenter.V1P1Beta1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5613 Release Google.Cloud.Gaming.V1Beta version 1.0.0-beta06
  README.md
  apis/Google.Cloud.Gaming.V1Beta/Google.Cloud.Gaming.V1Beta/Google.Cloud.Gaming.V1Beta.csproj
  apis/Google.Cloud.Gaming.V1Beta/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5614 Release Google.Cloud.Firestore version 2.3.0
  README.md
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore/Google.Cloud.Firestore.csproj
  apis/Google.Cloud.Firestore/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5615 Release Google.Cloud.Datastore.Admin.V1 version 1.0.0
  README.md
  apis/Google.Cloud.Datastore.Admin.V1/.repo-metadata.json
  apis/Google.Cloud.Datastore.Admin.V1/Google.Cloud.Datastore.Admin.V1/Google.Cloud.Datastore.Admin.V1.csproj
  apis/Google.Cloud.Datastore.Admin.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5616 Release Google.Cloud.ServiceManagement.V1 version 1.0.0
  README.md
  apis/Google.Cloud.ServiceManagement.V1/.repo-metadata.json
  apis/Google.Cloud.ServiceManagement.V1/Google.Cloud.ServiceManagement.V1/Google.Cloud.ServiceManagement.V1.csproj
  apis/Google.Cloud.ServiceManagement.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5617 Release Google.Cloud.Billing.Budgets.V1 version 1.0.0
  README.md
  apis/Google.Cloud.Billing.Budgets.V1/.repo-metadata.json
  apis/Google.Cloud.Billing.Budgets.V1/Google.Cloud.Billing.Budgets.V1/Google.Cloud.Billing.Budgets.V1.csproj
  apis/Google.Cloud.Billing.Budgets.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5619 Release Google.Cloud.AssuredWorkloads.V1Beta1 version 1.0.0-beta02
  README.md
  apis/Google.Cloud.AssuredWorkloads.V1Beta1/Google.Cloud.AssuredWorkloads.V1Beta1/Google.Cloud.AssuredWorkloads.V1Beta1.csproj
  apis/Google.Cloud.AssuredWorkloads.V1Beta1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5620 Release Google.Area120.Tables.V1Alpha1 version 1.0.0-alpha02
  README.md
  apis/Google.Area120.Tables.V1Alpha1/Google.Area120.Tables.V1Alpha1/Google.Area120.Tables.V1Alpha1.csproj
  apis/Google.Area120.Tables.V1Alpha1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5621 Release Google.Cloud.Container.V1 version 2.2.0
  README.md
  apis/Google.Cloud.Container.V1/Google.Cloud.Container.V1/Google.Cloud.Container.V1.csproj
  apis/Google.Cloud.Container.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5622 Use "skip" overrides in show-stale tool
  tools/Google.Cloud.Tools.ReleaseManager/GitHelpers.cs
  tools/Google.Cloud.Tools.ReleaseManager/History/CommitOverrides.cs
  tools/Google.Cloud.Tools.ReleaseManager/History/GitCommit.cs
  tools/Google.Cloud.Tools.ReleaseManager/History/HistoryFile.cs
  tools/Google.Cloud.Tools.ReleaseManager/History/overrides.json
  tools/Google.Cloud.Tools.ReleaseManager/ShowStaleCommand.cs
Labels: cla: yes

#5623 Release Google.Cloud.Bigtable.Admin.V2 version 2.3.0
  README.md
  apis/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2.csproj
  apis/Google.Cloud.Bigtable.Admin.V2/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5624 Release Google.Analytics.Admin.V1Alpha version 1.0.0-alpha03
  README.md
  apis/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha.csproj
  apis/Google.Analytics.Admin.V1Alpha/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5625 Release Google.Analytics.Data.V1Alpha version 1.0.0-alpha03
  README.md
  apis/Google.Analytics.Data.V1Alpha/Google.Analytics.Data.V1Alpha/Google.Analytics.Data.V1Alpha.csproj
  apis/Google.Analytics.Data.V1Alpha/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5618 [Log4Net]: Adds snippet showing how to set Log4Net properties as Google Cloud log entry labels.
  apis/Google.Cloud.Logging.Log4Net/Google.Cloud.Logging.Log4Net.Snippets/AssemblyInfo.cs
  apis/Google.Cloud.Logging.Log4Net/Google.Cloud.Logging.Log4Net.Snippets/Google.Cloud.Logging.Log4Net.Snippets.csproj
  apis/Google.Cloud.Logging.Log4Net/Google.Cloud.Logging.Log4Net.Snippets/GoogleStackdriverAppenderSnippets.cs
  apis/Google.Cloud.Logging.Log4Net/Google.Cloud.Logging.Log4Net.Snippets/log4net-custom-labels-template.xml
  apis/Google.Cloud.Logging.Log4Net/docs/configuration.md
  apis/Google.Cloud.Logging.Log4Net/docs/index.md
Labels: cla: yes

#5626 Release Google.Cloud.Logging.NLog version 3.1.0
  README.md
  apis/Google.Cloud.Logging.NLog/Google.Cloud.Logging.NLog/Google.Cloud.Logging.NLog.csproj
  apis/Google.Cloud.Logging.NLog/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5627 Release Google.Cloud.Logging.Log4Net version 3.2.0
  README.md
  apis/Google.Cloud.Logging.Log4Net/Google.Cloud.Logging.Log4Net/Google.Cloud.Logging.Log4Net.csproj
  apis/Google.Cloud.Logging.Log4Net/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5628 chore: Backlog update.
  BACKLOG.md
Labels: cla: yes

#5631 [apis/ServiceDirectory] feat: Removing VI proto.
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5630 Update Google.Cloud.Logging.Console with GA Microsoft.Extensions.Logg…
  apis/Google.Cloud.Logging.Console/Google.Cloud.Logging.Console.Tests/GoogleCloudConsoleFormatterTest.cs
  apis/Google.Cloud.Logging.Console/Google.Cloud.Logging.Console.Tests/TestFormatterOptionsMonitor.cs
  apis/Google.Cloud.Logging.Console/Google.Cloud.Logging.Console/Google.Cloud.Logging.Console.csproj
  apis/apis.json
Labels: cla: yes

#5637 [apis/Google.Cloud.Logging.V2] feat: add the Tailing API to get a live stream of the tail end of filtered logs
  apis/Google.Cloud.Logging.V2/Google.Cloud.Logging.V2.Snippets/LoggingServiceV2ClientSnippets.g.cs
  apis/Google.Cloud.Logging.V2/Google.Cloud.Logging.V2/Logging.cs
  apis/Google.Cloud.Logging.V2/Google.Cloud.Logging.V2/LoggingGrpc.cs
  apis/Google.Cloud.Logging.V2/Google.Cloud.Logging.V2/LoggingServiceV2Client.g.cs
  apis/Google.Cloud.Logging.V2/synth.metadata
Labels: cla: yes, context: full

#5638 [apis/ServiceDirectory] feat: sync v1beta1 GKE API fix: deprecate SetLocations; use UpdateCluster feat: support for sysctls config in Linux nodes feat: support for node kubelet config controlling CPU manager policy, CFS quota feat: support for Custom
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full
