Repository googleapis/google-cloud-dotnet, pull requests merged in 2020-09, with the labels that each got.

#5281 Release Google.Cloud.Storage.V1 version 3.3.0
  README.md
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.IntegrationTests/Google.Cloud.Storage.V1.IntegrationTests.csproj
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.Snippets/Google.Cloud.Storage.V1.Snippets.csproj
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.Tests/Google.Cloud.Storage.V1.Tests.csproj
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.csproj
  apis/Google.Cloud.Storage.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5282 [apis/Google.Analytics.Data.V1Alpha] feat: added GetMetadata method feat: DimensionHeader type renamed to PivotDimensionHeader feat: added TYPE_SECONDS,TYPE_CURRENCY to MetricType enum docs: documentation updates
  apis/Google.Analytics.Data.V1Alpha/Google.Analytics.Data.V1Alpha.Snippets/AlphaAnalyticsDataClientSnippets.g.cs
  apis/Google.Analytics.Data.V1Alpha/Google.Analytics.Data.V1Alpha.Tests/AlphaAnalyticsDataClientTest.g.cs
  apis/Google.Analytics.Data.V1Alpha/Google.Analytics.Data.V1Alpha/AlphaAnalyticsDataClient.g.cs
  apis/Google.Analytics.Data.V1Alpha/Google.Analytics.Data.V1Alpha/AnalyticsDataApi.cs
  apis/Google.Analytics.Data.V1Alpha/Google.Analytics.Data.V1Alpha/AnalyticsDataApiGrpc.cs
  apis/Google.Analytics.Data.V1Alpha/Google.Analytics.Data.V1Alpha/AnalyticsDataApiResourceNames.g.cs
  apis/Google.Analytics.Data.V1Alpha/Google.Analytics.Data.V1Alpha/Data.cs
  apis/Google.Analytics.Data.V1Alpha/synth.metadata
Labels: cla: yes, context: full

#5287 [CHANGE ME] Re-generated apis/ServiceDirectory to pick up changes in the API or client library generator.
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5286 [apis/Google.Cloud.Dlp.V2] docs: expand parent field format, and BigQuery sampling options. Also describing which transformations are allowed for ReidentifyContent API calls, and the custom alphabet allowed for format-preserving encryption (FPE).
  apis/Google.Cloud.Dlp.V2/Google.Cloud.Dlp.V2/Dlp.cs
  apis/Google.Cloud.Dlp.V2/Google.Cloud.Dlp.V2/DlpServiceClient.g.cs
  apis/Google.Cloud.Dlp.V2/Google.Cloud.Dlp.V2/Storage.cs
  apis/Google.Cloud.Dlp.V2/synth.metadata
Labels: cla: yes, context: full

#5289 [apis/ServiceDirectory] feat!: Updating CAS beta libraries for release.
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5285 feat(spanner): set resource header in database admin client
  apis/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1.Tests/ResourcePrefixHeaderTest.cs
  apis/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1/DatabaseAdminClientPartial.cs
Labels: api: spanner, cla: yes

#5288 feat(spanner): set resource header in instance admin client
  apis/Google.Cloud.Spanner.Admin.Instance.V1/Google.Cloud.Spanner.Admin.Instance.V1.Tests/ResourcePrefixHeaderTest.cs
  apis/Google.Cloud.Spanner.Admin.Instance.V1/Google.Cloud.Spanner.Admin.Instance.V1/InstanceAdminClientPartial.cs
Labels: api: spanner, cla: yes

#5057 feat(spanner): add NUMERIC support
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.IntegrationTests/AllTypesTableFixture.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.IntegrationTests/BindingTests.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.IntegrationTests/WriteTests.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.Tests/SpannerDbTypeTests.ValueConversions.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.Tests/SpannerDbTypeTests.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/SpannerDataReader.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/SpannerDbType.StringParsing.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/SpannerDbType.ValueConversion.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/SpannerDbType.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/SpannerParameter.cs
Labels: api: spanner, cla: yes

#5238 fix: retry PDML on EOS on DATA error
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.Tests/SpannerCommandTests.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.Tests/V1/SpannerClientHelpers.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/EphemeralTransaction.cs
Labels: api: spanner, cla: yes

#5294 Release Google.Cloud.Datastore.Admin.V1 version 1.0.0-beta01
  README.md
  apis/Google.Cloud.Datastore.Admin.V1/.repo-metadata.json
  apis/Google.Cloud.Datastore.Admin.V1/Google.Cloud.Datastore.Admin.V1/Google.Cloud.Datastore.Admin.V1.csproj
  apis/Google.Cloud.Datastore.Admin.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5292 test(spanner): ensure mock is verified in emulator test
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.Tests/SpannerCommandTests.cs
Labels: api: spanner, cla: yes

#5295 Adds links to Access Control documentation for Logging and Tracing.
  apis/Google.Cloud.Diagnostics.AspNetCore/docs/index.md
Labels: cla: yes

#5296 Release Google.Cloud.Gaming.V1Beta version 1.0.0-beta05
  README.md
  apis/Google.Cloud.Gaming.V1Beta/Google.Cloud.Gaming.V1Beta/Google.Cloud.Gaming.V1Beta.csproj
  apis/Google.Cloud.Gaming.V1Beta/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5298 [apis/ServiceDirectory] Adding Cloud Domains v1beta1 API.
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5301 [apis/Google.Cloud.SecretManager.V1] Update secretmanager.googleapis.com v1 protos
  apis/Google.Cloud.SecretManager.V1/Google.Cloud.SecretManager.V1.Tests/SecretManagerServiceClientTest.g.cs
  apis/Google.Cloud.SecretManager.V1/Google.Cloud.SecretManager.V1/Resources.cs
  apis/Google.Cloud.SecretManager.V1/synth.metadata
Labels: cla: yes, context: full

#5304 Release Google.Cloud.SecretManager.V1 version 1.1.0
  README.md
  apis/Google.Cloud.SecretManager.V1/Google.Cloud.SecretManager.V1/Google.Cloud.SecretManager.V1.csproj
  apis/Google.Cloud.SecretManager.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5303 Release Spanner libraries version 3.2.0
  README.md
  apis/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1.csproj
  apis/Google.Cloud.Spanner.Admin.Instance.V1/Google.Cloud.Spanner.Admin.Instance.V1/Google.Cloud.Spanner.Admin.Instance.V1.csproj
  apis/Google.Cloud.Spanner.Common.V1/Google.Cloud.Spanner.Common.V1/Google.Cloud.Spanner.Common.V1.csproj
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.IntegrationTests/Google.Cloud.Spanner.Data.IntegrationTests.csproj
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.Snippets/Google.Cloud.Spanner.Data.Snippets.csproj
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.Tests/Google.Cloud.Spanner.Data.Tests.csproj
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.csproj
  apis/Google.Cloud.Spanner.Data/docs/history.md
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1.csproj
  apis/Google.Cloud.Speech.V1/Google.Cloud.Speech.V1/Google.Cloud.Speech.V1.csproj
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5305 Renormalize line endings
  apis/Google.Cloud.Logging.Log4Net/Google.Cloud.Logging.Log4Net/GoogleStackdriverAppender.cs
  apis/Google.Cloud.Logging.NLog/Google.Cloud.Logging.NLog.Tests/GoogleStackdriverTargetTest.cs
  apis/Google.Cloud.Logging.NLog/Google.Cloud.Logging.NLog.sln
  apis/Google.Cloud.Logging.NLog/Google.Cloud.Logging.NLog/GoogleStackdriverTarget.cs
  apis/Google.Cloud.Logging.NLog/Google.Cloud.Logging.NLog/GoogleStackdriverTarget_Configuration.cs
  apis/Google.Cloud.Logging.NLog/Google.Cloud.Logging.NLog/ToStringJsonConverter.cs
  apis/Google.Cloud.Logging.NLog/Google.Cloud.Logging.NLog/readme.md
Labels: cla: yes

#5308 Massively speed up the version history update
  tools/Google.Cloud.Tools.ReleaseManager/UpdateHistoryCommand.cs
Labels: cla: yes

#5310 [apis/Google.Cloud.Dialogflow.V2] docs: wording updates for tiers.
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/Webhook.cs
  apis/Google.Cloud.Dialogflow.V2/synth.metadata
Labels: cla: yes, context: full

#5311 [apis/ServiceDirectory] feat: Add Job Search v4 API
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5314 [Diagnostics] Sets LogEntry.TraceSampled to true if the entry is traced.
  apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore/Logging/GoogleLogger.cs
Labels: cla: yes

#5300 [apis/Google.Cloud.Asset.V1] fix!: remove AnalyzeIamPolicy and ExportIamPolicyAnalysis RPCs
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1.Snippets/AssetServiceClientSnippets.g.cs
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1.Tests/AssetServiceClientTest.g.cs
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1/AssetService.cs
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1/AssetServiceClient.g.cs
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1/AssetServiceGrpc.cs
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1/Assets.cs
  apis/Google.Cloud.Asset.V1/synth.metadata
Labels: cla: yes, context: full

#5316 [apis/Google.Cloud.Billing.Budgets.V1Beta1] feat: Added support for field to disable default budget alerts to IAM recipients. fix: Pub/Sub fields in AllUpdatesRule are now optional. fix: Added cloud-billing OAuth scope.
  apis/Google.Cloud.Billing.Budgets.V1Beta1/Google.Cloud.Billing.Budgets.V1Beta1/BudgetModel.cs
  apis/Google.Cloud.Billing.Budgets.V1Beta1/Google.Cloud.Billing.Budgets.V1Beta1/BudgetService.cs
  apis/Google.Cloud.Billing.Budgets.V1Beta1/Google.Cloud.Billing.Budgets.V1Beta1/BudgetServiceClient.g.cs
  apis/Google.Cloud.Billing.Budgets.V1Beta1/synth.metadata
Labels: cla: yes, context: full

#5309 Create tool to show "stale" APIs
  tools/Google.Cloud.Tools.ReleaseManager/GitHelpers.cs
  tools/Google.Cloud.Tools.ReleaseManager/History/Release.cs
  tools/Google.Cloud.Tools.ReleaseManager/ShowStaleCommand.cs
  tools/Google.Cloud.Tools.ReleaseManager/UpdateHistoryCommand.cs
Labels: cla: yes

#5315 chore: update CODEOWNERS file
  .github/CODEOWNERS
Labels: cla: yes

#5318 Release Google.Cloud.Asset.V1 version 2.4.0
  README.md
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1.csproj
  apis/Google.Cloud.Asset.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5323 docs: fix datastore samples link
  apis/Google.Cloud.Datastore.V1/docs/index.md
Labels: cla: yes

#5326 [apis/Google.Cloud.Asset.V1] feat: added support for per type and partition export for Cloud Asset API
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1/AssetService.cs
  apis/Google.Cloud.Asset.V1/synth.metadata
Labels: cla: yes, context: full

#5327 Release Google.Cloud.AssuredWorkloads.V1Beta1 version 1.0.0-beta01
  README.md
  apis/Google.Cloud.AssuredWorkloads.V1Beta1/.repo-metadata.json
  apis/Google.Cloud.AssuredWorkloads.V1Beta1/Google.Cloud.AssuredWorkloads.V1Beta1/Google.Cloud.AssuredWorkloads.V1Beta1.csproj
  apis/Google.Cloud.AssuredWorkloads.V1Beta1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5329 Re-generated apis/ServiceDirectory to pick up changes in the API or client library generator.
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5331 [apis/Google.Cloud.SecurityCenter.V1P1Beta1] docs: updated description of finding severity field
  apis/Google.Cloud.SecurityCenter.V1P1Beta1/Google.Cloud.SecurityCenter.V1P1Beta1/Finding.cs
  apis/Google.Cloud.SecurityCenter.V1P1Beta1/Google.Cloud.SecurityCenter.V1P1Beta1/SecurityCenterClient.g.cs
  apis/Google.Cloud.SecurityCenter.V1P1Beta1/Google.Cloud.SecurityCenter.V1P1Beta1/SecuritycenterService.cs
  apis/Google.Cloud.SecurityCenter.V1P1Beta1/synth.metadata
Labels: cla: yes, context: full

#5332 [apis/ServiceDirectory] google.cloud.aiplatform API v1beta1
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5336 Updates release date in history.md for Google.Cloud.Gaming.V1Beta
  apis/Google.Cloud.Gaming.V1Beta/docs/history.md
Labels: cla: yes

#5339 Release Google.Area120.Tables.V1Alpha1 version 1.0.0-alpha01
  README.md
  apis/Google.Area120.Tables.V1Alpha1/.repo-metadata.json
  apis/Google.Area120.Tables.V1Alpha1/Google.Area120.Tables.V1Alpha1/Google.Area120.Tables.V1Alpha1.csproj
  apis/Google.Area120.Tables.V1Alpha1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5337 Disable pretty printing in BigQuery unless explicitly requested
  apis/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2.Tests/BigQueryClientImplTest.cs
  apis/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2.Tests/FakeBigqueryService.cs
  apis/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2/BigQueryClient.cs
  apis/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2/BigQueryClientBuilder.cs
  apis/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2/BigQueryClientImpl.DatasetCrud.cs
  apis/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2/BigQueryClientImpl.InsertData.cs
  apis/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2/BigQueryClientImpl.JobCrud.cs
  apis/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2/BigQueryClientImpl.ModelCrud.cs
  apis/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2/BigQueryClientImpl.ProjectCrud.cs
  apis/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2/BigQueryClientImpl.Queries.cs
  apis/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2/BigQueryClientImpl.RoutineCrud.cs
  apis/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2/BigQueryClientImpl.ServiceAccount.cs
  apis/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2/BigQueryClientImpl.TableCrud.cs
  apis/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2/BigQueryClientImpl.cs
Labels: cla: yes

#5328 [apis/Google.Cloud.Dlp.V2] docs: correct the links for parent fields
  apis/Google.Cloud.Dlp.V2/Google.Cloud.Dlp.V2/Dlp.cs
  apis/Google.Cloud.Dlp.V2/Google.Cloud.Dlp.V2/DlpServiceClient.g.cs
  apis/Google.Cloud.Dlp.V2/synth.metadata
Labels: cla: yes, context: full

#5324 chore: update CODEOWNERS for bigtable
  .github/CODEOWNERS
Labels: cla: yes

#5341 Release Google.Cloud.BigQuery.V2 version 2.1.0
  README.md
  apis/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2.csproj
  apis/Google.Cloud.BigQuery.V2/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5342 [Firestore]: Skips some conformance tests pending guidance on including update mask.
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore.Tests/Proto/ProtoTest.cs
Labels: cla: yes

#5347 [apis/Google.Cloud.Notebooks.V1Beta1] feat: update third party protos with URLs and latest fields
  apis/Google.Cloud.Notebooks.V1Beta1/Google.Cloud.Notebooks.V1Beta1.Tests/NotebookServiceClientTest.g.cs
  apis/Google.Cloud.Notebooks.V1Beta1/Google.Cloud.Notebooks.V1Beta1/Instance.cs
  apis/Google.Cloud.Notebooks.V1Beta1/Google.Cloud.Notebooks.V1Beta1/NotebookServiceClient.g.cs
  apis/Google.Cloud.Notebooks.V1Beta1/Google.Cloud.Notebooks.V1Beta1/Service.cs
  apis/Google.Cloud.Notebooks.V1Beta1/Google.Cloud.Notebooks.V1Beta1/ServiceGrpc.cs
  apis/Google.Cloud.Notebooks.V1Beta1/synth.metadata
Labels: cla: yes, context: full

#5348 [apis/ServiceDirectory] feat: update third party protos with URLs and latest fields
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5351 Ignore aistreams API when reporting on missing APIs
  apis/apis.json
Labels: cla: yes

#5352 [Translate]: Loosens HTML translation tests to avoid flakiness.
  apis/Google.Cloud.Translation.V2/Google.Cloud.Translation.V2.Snippets/TranslationClientSnippets.cs
Labels: cla: yes

#5354 [apis/ServiceDirectory] Add Service Direcotry v1 protos and configs
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5356 [CHANGE ME] Re-generated apis/ServiceDirectory to pick up changes in the API or client library generator.
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5357 Add note in Pub/Sub documentation around use in occasional-CPU environments
  apis/Google.Cloud.PubSub.V1/docs/index.md
Labels: cla: yes

#5367 [Translate] Loosens translate HTML snippets to avoid flakiness.
  apis/Google.Cloud.Translation.V2/Google.Cloud.Translation.V2.Snippets/AdvancedTranslationClientSnippets.cs
  apis/Google.Cloud.Translation.V2/Google.Cloud.Translation.V2.Snippets/TranslationClientSnippets.cs
Labels: cla: yes

#5369 Specify insecure credentials when connecting to the emulator
  apis/Google.Cloud.Datastore.V1/Google.Cloud.Datastore.V1/DatastoreDbBuilder.cs
Labels: cla: yes

#5374 Release Google.Cloud.Datastore.V1 version 3.1.0
  README.md
  apis/Google.Cloud.Datastore.V1/Google.Cloud.Datastore.V1/Google.Cloud.Datastore.V1.csproj
  apis/Google.Cloud.Datastore.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5375 Release Google.Cloud.Asset.V1 version 2.5.0
  README.md
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1.csproj
  apis/Google.Cloud.Asset.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5368 [Storage]: Makes V4 signature include x-goog-resumable header.
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1/UrlSigner.V4Signer.cs
Labels: cla: yes

#5379 Release Google.Cloud.Diagnostics packages version 4.2.0-beta01
  README.md
  apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore.csproj
  apis/Google.Cloud.Diagnostics.AspNetCore/docs/history.md
  apis/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common.csproj
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5364 Trust SpannerClientCreationOptions to connect to the emulator
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/SpannerCommand.ExecutableCommand.cs
Labels: cla: yes

#5381 Add Smart Device Management API to apis/ServiceDirectory
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: partial

#5382 For all but patch releases, update known dependencies
  tools/Google.Cloud.Tools.ReleaseManager/GenerateProjectsCommand.cs
  tools/Google.Cloud.Tools.ReleaseManager/SetVersionCommand.cs
Labels: cla: yes

#5383 Modifies namespace health checking to exempt external tooling.
  tools/Google.Cloud.ClientTesting/CodeHealthTester.cs
Labels: cla: yes
