Repository googleapis/google-cloud-dotnet, pull requests merged in 2021-06, with the labels that each got.

#6585 docs: Change Stackdriver to Google Cloud
  apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore.Snippets/LoggingSnippets.cs
  apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore/ErrorReporting/ErrorReportingExceptionLoggerExtension.cs
  apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore/ErrorReporting/ErrorReportingExceptionLoggerMiddleware.cs
  apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore/ErrorReporting/GoogleExceptionLogger.cs
  apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore/Logging/GoogleLogger.cs
  apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore/Logging/GoogleLoggerFactoryExtensions.cs
  apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore/Logging/GoogleLoggerProvider.cs
  apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore/Trace/CloudTraceExtension.cs
  apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore/Trace/CloudTraceMiddleware.cs
  apis/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common.IntegrationTests/AssemblyInfo.cs
  apis/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common.Tests/ErrorReporting/ErrorReportingOptionsTest.cs
  apis/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common/ErrorReporting/ErrorReportingOptions.cs
  apis/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common/ErrorReporting/EventTarget.cs
  apis/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common/Logging/GrpcLogConsumer.cs
  apis/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common/Trace/GrpcTraceConsumer.cs
Labels: cla: yes

#6586 [apis/Google.Cloud.DocumentAI.V1] feat: Move CommonOperationMetadata into a separate proto file for potential reuse.
  apis/Google.Cloud.DocumentAI.V1/Google.Cloud.DocumentAI.V1/DocumentProcessorService.g.cs
  apis/Google.Cloud.DocumentAI.V1/Google.Cloud.DocumentAI.V1/Geometry.g.cs
  apis/Google.Cloud.DocumentAI.V1/Google.Cloud.DocumentAI.V1/OperationMetadata.g.cs
  apis/Google.Cloud.DocumentAI.V1/synth.metadata
Labels: cla: yes, context: full

#6588 [apis/Google.Cloud.Dialogflow.Cx.V3] feat: support sentiment analysis in bot testing
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/TestCase.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/synth.metadata
Labels: cla: yes, context: full

#6584 feat(spanner): add query_optimizer_statistics_package support
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.IntegrationTests/QueryOptionsTests.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.Tests/QueryOptionsTests.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.Tests/SpannerCommandTests.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/QueryOptions.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/SpannerCommand.ExecutableCommand.cs
Labels: api: spanner, cla: yes

#6581 [apis/ServiceDirectory] feat: connectgateway public protos
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#6592 Release Google.Cloud.DocumentAI.V1 version 1.0.0
  README.md
  apis/Google.Cloud.DocumentAI.V1/.repo-metadata.json
  apis/Google.Cloud.DocumentAI.V1/Google.Cloud.DocumentAI.V1/Google.Cloud.DocumentAI.V1.csproj
  apis/Google.Cloud.DocumentAI.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6594 Promote GSuiteAddOns APIs to 1.0.0
  README.md
  apis/Google.Apps.Script.Type/.repo-metadata.json
  apis/Google.Apps.Script.Type/Google.Apps.Script.Type/Google.Apps.Script.Type.csproj
  apis/Google.Apps.Script.Type/docs/history.md
  apis/Google.Cloud.GSuiteAddOns.V1/.repo-metadata.json
  apis/Google.Cloud.GSuiteAddOns.V1/Google.Cloud.GSuiteAddOns.V1/Google.Cloud.GSuiteAddOns.V1.csproj
  apis/Google.Cloud.GSuiteAddOns.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6595 Release Google.Cloud.Metastore.V1 version 1.0.0
  README.md
  apis/Google.Cloud.Metastore.V1/.repo-metadata.json
  apis/Google.Cloud.Metastore.V1/Google.Cloud.Metastore.V1/Google.Cloud.Metastore.V1.csproj
  apis/Google.Cloud.Metastore.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6596 Release Google.Cloud.EssentialContacts.V1 version 1.0.0
  README.md
  apis/Google.Cloud.EssentialContacts.V1/.repo-metadata.json
  apis/Google.Cloud.EssentialContacts.V1/Google.Cloud.EssentialContacts.V1/Google.Cloud.EssentialContacts.V1.csproj
  apis/Google.Cloud.EssentialContacts.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6597 [CHANGE ME] Re-generated apis/ServiceDirectory to pick up changes in the API or client library generator.
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#6599 Release Google.Cloud.Shell.V1 version 1.0.0
  README.md
  apis/Google.Cloud.Shell.V1/.repo-metadata.json
  apis/Google.Cloud.Shell.V1/Google.Cloud.Shell.V1/Google.Cloud.Shell.V1.csproj
  apis/Google.Cloud.Shell.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6600 [apis/Google.Cloud.Channel.V1] feat: Add/Update API definitions for Cloud Channel API, including
  apis/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1.Snippets/CloudChannelServiceClientSnippets.g.cs
  apis/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1.Tests/CloudChannelServiceClientTest.g.cs
  apis/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1/CloudChannelServiceClient.g.cs
  apis/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1/Customers.g.cs
  apis/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1/Service.g.cs
  apis/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1/ServiceGrpc.g.cs
  apis/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1/ServiceResourceNames.g.cs
  apis/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1/SubscriberEvent.g.cs
  apis/Google.Cloud.Channel.V1/gapic_metadata.json
  apis/Google.Cloud.Channel.V1/synth.metadata
Labels: cla: yes, context: full

#6601 [apis/Google.Cloud.Container.V1] feat: support for NodeAutoprovisioning ImageType
  apis/Google.Cloud.Container.V1/Google.Cloud.Container.V1/ClusterService.g.cs
  apis/Google.Cloud.Container.V1/Google.Cloud.Container.V1/ClusterServiceGrpc.g.cs
  apis/Google.Cloud.Container.V1/synth.metadata
Labels: cla: yes, context: full

#6602 [apis/Google.Cloud.SecurityCenter.V1] docs: update currently supported Finding filter fields.
  apis/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1/SecurityCenterClient.g.cs
  apis/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1/SecuritycenterService.g.cs
  apis/Google.Cloud.SecurityCenter.V1/synth.metadata
Labels: cla: yes, context: full

#6604 Release Spanner libraries version 3.9.0
  README.md
  apis/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1.csproj
  apis/Google.Cloud.Spanner.Admin.Instance.V1/Google.Cloud.Spanner.Admin.Instance.V1/Google.Cloud.Spanner.Admin.Instance.V1.csproj
  apis/Google.Cloud.Spanner.Common.V1/Google.Cloud.Spanner.Common.V1/Google.Cloud.Spanner.Common.V1.csproj
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.csproj
  apis/Google.Cloud.Spanner.Data/docs/history.md
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1.csproj
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6605 [apis/ServiceDirectory] feat: add protos and build files for Google Ads API v8
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#6607 [apis/ServiceDirectory] fix!: Correct capitalization for C#, Ruby and PHP namespaces/packages.
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#6608 [apis/Google.Cloud.CloudDms.V1] docs: update link in comments
  apis/Google.Cloud.CloudDms.V1/Google.Cloud.CloudDms.V1/Clouddms.g.cs
  apis/Google.Cloud.CloudDms.V1/Google.Cloud.CloudDms.V1/DataMigrationServiceClient.g.cs
  apis/Google.Cloud.CloudDms.V1/synth.metadata
Labels: cla: yes, context: full

#6609 [apis/Google.Cloud.Spanner.Admin.Instance.V1] feat(spanner): add processing_units to Instance resource
  apis/Google.Cloud.Spanner.Admin.Instance.V1/Google.Cloud.Spanner.Admin.Instance.V1.Tests/InstanceAdminClientTest.g.cs
  apis/Google.Cloud.Spanner.Admin.Instance.V1/Google.Cloud.Spanner.Admin.Instance.V1/SpannerInstanceAdmin.g.cs
  apis/Google.Cloud.Spanner.Admin.Instance.V1/synth.metadata
Labels: api: spanner, cla: yes, context: full

#6613 [apis/Google.Cloud.Dialogflow.V2] feat: added Automated agent reply type and allow cancellation flag for partial response feature.
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/Participant.g.cs
  apis/Google.Cloud.Dialogflow.V2/synth.metadata
Labels: cla: yes, context: full

#6614 [apis/Google.Cloud.Kms.V1] feat: add ECDSA secp256k1 to the list of supported algorithms.
  apis/Google.Cloud.Kms.V1/Google.Cloud.Kms.V1.Tests/KeyManagementServiceClientTest.g.cs
  apis/Google.Cloud.Kms.V1/Google.Cloud.Kms.V1/KeyManagementServiceClient.g.cs
  apis/Google.Cloud.Kms.V1/Google.Cloud.Kms.V1/Resources.g.cs
  apis/Google.Cloud.Kms.V1/Google.Cloud.Kms.V1/ServiceGrpc.g.cs
  apis/Google.Cloud.Kms.V1/synth.metadata
Labels: cla: yes, context: full

#6615 [apis/ServiceDirectory] feat: eventarc public protos
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#6612 tests: tests required for alpha
  apis/Google.Cloud.Compute.V1/Google.Cloud.Compute.V1.IntegrationTests/InstancesTest.cs
Labels: cla: yes

#6617 [apis/ServiceDirectory] feat: publishing Testing API protos
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#6622 Release Google.Cloud.CloudDms.V1 version 1.0.0
  README.md
  apis/Google.Cloud.CloudDms.V1/.repo-metadata.json
  apis/Google.Cloud.CloudDms.V1/Google.Cloud.CloudDms.V1/Google.Cloud.CloudDms.V1.csproj
  apis/Google.Cloud.CloudDms.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6624 Make the DocumentAI.V1Beta3 scripts executable
  apis/Google.Cloud.DocumentAI.V1Beta3/postgeneration.sh
  apis/Google.Cloud.DocumentAI.V1Beta3/pregeneration.sh
Labels: cla: yes

#6626 [apis/ServiceDirectory] feat: Publish public APIs for FleetEngine
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#6625 [apis/Google.Cloud.Security.PrivateCA.V1] fix: Fixed casing of the Ruby namespace
  apis/Google.Cloud.Security.PrivateCA.V1/Google.Cloud.Security.PrivateCA.V1/Service.g.cs
  apis/Google.Cloud.Security.PrivateCA.V1/synth.metadata
Labels: cla: yes, context: full

#6628 Remove Google.Cloud.DocumentAI.V1Beta2
  apis/Google.Cloud.DocumentAI.V1Beta2/.repo-metadata.json
  apis/Google.Cloud.DocumentAI.V1Beta2/Google.Cloud.DocumentAI.V1Beta2.Snippets/DocumentUnderstandingServiceClientSnippets.g.cs
  apis/Google.Cloud.DocumentAI.V1Beta2/Google.Cloud.DocumentAI.V1Beta2.Snippets/Google.Cloud.DocumentAI.V1Beta2.Snippets.csproj
  apis/Google.Cloud.DocumentAI.V1Beta2/Google.Cloud.DocumentAI.V1Beta2.Snippets/coverage.xml
  apis/Google.Cloud.DocumentAI.V1Beta2/Google.Cloud.DocumentAI.V1Beta2.Tests/DocumentUnderstandingServiceClientTest.g.cs
  apis/Google.Cloud.DocumentAI.V1Beta2/Google.Cloud.DocumentAI.V1Beta2.Tests/Google.Cloud.DocumentAI.V1Beta2.Tests.csproj
  apis/Google.Cloud.DocumentAI.V1Beta2/Google.Cloud.DocumentAI.V1Beta2.Tests/coverage.xml
  apis/Google.Cloud.DocumentAI.V1Beta2/Google.Cloud.DocumentAI.V1Beta2.sln
  apis/Google.Cloud.DocumentAI.V1Beta2/Google.Cloud.DocumentAI.V1Beta2/Document.g.cs
  apis/Google.Cloud.DocumentAI.V1Beta2/Google.Cloud.DocumentAI.V1Beta2/DocumentUnderstanding.g.cs
  apis/Google.Cloud.DocumentAI.V1Beta2/Google.Cloud.DocumentAI.V1Beta2/DocumentUnderstandingGrpc.g.cs
  apis/Google.Cloud.DocumentAI.V1Beta2/Google.Cloud.DocumentAI.V1Beta2/DocumentUnderstandingServiceClient.g.cs
  apis/Google.Cloud.DocumentAI.V1Beta2/Google.Cloud.DocumentAI.V1Beta2/Geometry.g.cs
  apis/Google.Cloud.DocumentAI.V1Beta2/Google.Cloud.DocumentAI.V1Beta2/Google.Cloud.DocumentAI.V1Beta2.csproj
  apis/Google.Cloud.DocumentAI.V1Beta2/docs/history.md
  apis/Google.Cloud.DocumentAI.V1Beta2/docs/index.md
  apis/Google.Cloud.DocumentAI.V1Beta2/gapic_metadata.json
  apis/Google.Cloud.DocumentAI.V1Beta2/synth.metadata
  apis/Google.Cloud.DocumentAI.V1Beta2/synth.py
  apis/apis.json
Labels: cla: yes

#6629 Use autosynth for Google.Cloud.Compute.V1
  apis/Google.Cloud.Compute.V1/synth.metadata
  apis/Google.Cloud.Compute.V1/synth.py
  generateapis.sh
  tools/Google.Cloud.Tools.ReleaseManager/GenerateProjectsCommand.cs
Labels: cla: yes

#6631 Temporarily disable Compute autosynth generation
  apis/Google.Cloud.Compute.V1/synth.py
  tools/Google.Cloud.Tools.ReleaseManager/GenerateProjectsCommand.cs
Labels: cla: yes

#6632 [apis/Google.Cloud.Dialogflow.Cx.V3] feat!: mark agent.default_language_code as required feat: add return_partial response to Fulfillment docs: add notes to train agent before sending queries
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3.Snippets/SessionsClientSnippets.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3.Tests/SessionsClientTest.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Agent.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/AgentGrpc.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/AgentsClient.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/EntityTypeGrpc.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/EntityTypesClient.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/FlowGrpc.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/FlowsClient.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Fulfillment.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Intent.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/IntentGrpc.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/IntentsClient.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/PageGrpc.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/PagesClient.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/SecuritySettings.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Session.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/TransitionRouteGroupGrpc.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/TransitionRouteGroupsClient.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/synth.metadata
Labels: cla: yes, context: full

#6633 [apis/Google.Cloud.Dialogflow.V2] docs: added notes to train agent prior to sending queries fix: added resource reference to agent_version
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2.Tests/EnvironmentsClientTest.g.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/AgentGrpc.g.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/AgentsClient.g.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/EntityTypeGrpc.g.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/EntityTypesClient.g.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/Environment.g.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/EnvironmentResourceNames.g.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/IntentGrpc.g.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/IntentsClient.g.cs
  apis/Google.Cloud.Dialogflow.V2/synth.metadata
Labels: cla: yes, context: full

#6634 [apis/Google.Cloud.DocumentAI.V1] feat: update ReviewDocumentRequest to allow set priority and enable validation.
  apis/Google.Cloud.DocumentAI.V1/Google.Cloud.DocumentAI.V1.Snippets/DocumentProcessorServiceClientSnippets.g.cs
  apis/Google.Cloud.DocumentAI.V1/Google.Cloud.DocumentAI.V1/Document.g.cs
  apis/Google.Cloud.DocumentAI.V1/Google.Cloud.DocumentAI.V1/DocumentProcessorService.g.cs
  apis/Google.Cloud.DocumentAI.V1/synth.metadata
Labels: cla: yes, context: full

#6635 [apis/ServiceDirectory] feat: Add SeekSubscription and Operations to API
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#6636 Release Google.Analytics.Admin.V1Alpha version 1.0.0-alpha07
  README.md
  apis/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha.csproj
  apis/Google.Analytics.Admin.V1Alpha/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6637 Release Google.Cloud.BigQuery.Storage.V1 version 2.3.0
  README.md
  apis/Google.Cloud.BigQuery.Storage.V1/Google.Cloud.BigQuery.Storage.V1/Google.Cloud.BigQuery.Storage.V1.csproj
  apis/Google.Cloud.BigQuery.Storage.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6638 Release Google.Cloud.BinaryAuthorization.V1Beta1 version 1.0.0-beta03
  README.md
  apis/Google.Cloud.BinaryAuthorization.V1Beta1/Google.Cloud.BinaryAuthorization.V1Beta1/Google.Cloud.BinaryAuthorization.V1Beta1.csproj
  apis/Google.Cloud.BinaryAuthorization.V1Beta1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6639 Release Google.Cloud.Channel.V1 version 1.2.0
  README.md
  apis/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1.csproj
  apis/Google.Cloud.Channel.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6640 Release Google.Cloud.Tpu.V1 version 1.0.0
  README.md
  apis/Google.Cloud.Tpu.V1/.repo-metadata.json
  apis/Google.Cloud.Tpu.V1/Google.Cloud.Tpu.V1/Google.Cloud.Tpu.V1.csproj
  apis/Google.Cloud.Tpu.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6641 Release Google.Cloud.VpcAccess.V1 version 1.0.0
  README.md
  apis/Google.Cloud.VpcAccess.V1/.repo-metadata.json
  apis/Google.Cloud.VpcAccess.V1/Google.Cloud.VpcAccess.V1/Google.Cloud.VpcAccess.V1.csproj
  apis/Google.Cloud.VpcAccess.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6642 Release Google.Cloud.ServiceUsage.V1 version 1.0.0
  README.md
  apis/Google.Cloud.ServiceUsage.V1/.repo-metadata.json
  apis/Google.Cloud.ServiceUsage.V1/Google.Cloud.ServiceUsage.V1/Google.Cloud.ServiceUsage.V1.csproj
  apis/Google.Cloud.ServiceUsage.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6643 Release Google.Cloud.CloudBuild.V1 version 1.2.0
  README.md
  apis/Google.Cloud.CloudBuild.V1/Google.Cloud.CloudBuild.V1/Google.Cloud.CloudBuild.V1.csproj
  apis/Google.Cloud.CloudBuild.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6644 Release Google.Cloud.Container.V1 version 2.4.0
  README.md
  apis/Google.Cloud.Container.V1/Google.Cloud.Container.V1/Google.Cloud.Container.V1.csproj
  apis/Google.Cloud.Container.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6645 Release Google.Cloud.Dialogflow.Cx.V3 version 1.2.0
  README.md
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3.csproj
  apis/Google.Cloud.Dialogflow.Cx.V3/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6646 Release Google.Cloud.Dialogflow.V2 version 3.3.0
  README.md
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2.csproj
  apis/Google.Cloud.Dialogflow.V2/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6647 Release Google.Cloud.DocumentAI.V1 version 1.1.0
  README.md
  apis/Google.Cloud.DocumentAI.V1/Google.Cloud.DocumentAI.V1/Google.Cloud.DocumentAI.V1.csproj
  apis/Google.Cloud.DocumentAI.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6648 Release Google.Cloud.Kms.V1 version 2.3.0
  README.md
  apis/Google.Cloud.Kms.V1/Google.Cloud.Kms.V1/Google.Cloud.Kms.V1.csproj
  apis/Google.Cloud.Kms.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6649 Release Google.Cloud.OsConfig.V1Alpha version 1.0.0-alpha02
  README.md
  apis/Google.Cloud.OsConfig.V1Alpha/Google.Cloud.OsConfig.V1Alpha/Google.Cloud.OsConfig.V1Alpha.csproj
  apis/Google.Cloud.OsConfig.V1Alpha/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6650 Release Google.Cloud.SecretManager.V1 version 1.5.0
  README.md
  apis/Google.Cloud.SecretManager.V1/Google.Cloud.SecretManager.V1/Google.Cloud.SecretManager.V1.csproj
  apis/Google.Cloud.SecretManager.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6651 Release Google.Cloud.SecurityCenter.V1 version 2.4.0
  README.md
  apis/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1.csproj
  apis/Google.Cloud.SecurityCenter.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6652 Release Google.Cloud.ServiceManagement.V1 version 1.2.0
  README.md
  apis/Google.Cloud.ServiceManagement.V1/Google.Cloud.ServiceManagement.V1/Google.Cloud.ServiceManagement.V1.csproj
  apis/Google.Cloud.ServiceManagement.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6653 Release Google.Cloud.Tasks.V2Beta3 version 2.0.0-beta06
  README.md
  apis/Google.Cloud.Tasks.V2Beta3/Google.Cloud.Tasks.V2Beta3/Google.Cloud.Tasks.V2Beta3.csproj
  apis/Google.Cloud.Tasks.V2Beta3/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6655 [CHANGE ME] Re-generated apis/ServiceDirectory to pick up changes in the API or client library generator.
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#6658 [apis/Google.Cloud.Asset.V1] feat: add new searchable fields (memberTypes, roles, project, folders and organization), new request fields (assetTypes and orderBy) and new response fields (assetType, folders and organization) in SearchAllIamPolicies
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1.Snippets/AssetServiceClientSnippets.g.cs
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1/AssetService.g.cs
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1/AssetServiceClient.g.cs
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1/Assets.g.cs
  apis/Google.Cloud.Asset.V1/synth.metadata
Labels: cla: yes, context: full

#6659 [apis/Google.Cloud.Spanner.V1] feat(spanner): add JSON type
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/Type.g.cs
  apis/Google.Cloud.Spanner.V1/synth.metadata
Labels: api: spanner, cla: yes, context: full

#6660 [apis/ServiceDirectory] feat: filestore public protos
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#6662 Release version 4.3.0-beta01 of all diagnostics packages
  README.md
  apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore.IntegrationTests/Google.Cloud.Diagnostics.AspNetCore.IntegrationTests.csproj
  apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore.Snippets/Google.Cloud.Diagnostics.AspNetCore.Snippets.csproj
  apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore.Tests/Google.Cloud.Diagnostics.AspNetCore.Tests.csproj
  apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore.csproj
  apis/Google.Cloud.Diagnostics.AspNetCore/docs/history.md
  apis/Google.Cloud.Diagnostics.AspNetCore3/Google.Cloud.Diagnostics.AspNetCore3.IntegrationTests/Google.Cloud.Diagnostics.AspNetCore3.IntegrationTests.csproj
  apis/Google.Cloud.Diagnostics.AspNetCore3/Google.Cloud.Diagnostics.AspNetCore3.Snippets/Google.Cloud.Diagnostics.AspNetCore3.Snippets.csproj
  apis/Google.Cloud.Diagnostics.AspNetCore3/Google.Cloud.Diagnostics.AspNetCore3.Tests/Google.Cloud.Diagnostics.AspNetCore3.Tests.csproj
  apis/Google.Cloud.Diagnostics.AspNetCore3/Google.Cloud.Diagnostics.AspNetCore3/Google.Cloud.Diagnostics.AspNetCore3.csproj
  apis/Google.Cloud.Diagnostics.AspNetCore3/docs/history.md
  apis/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common.IntegrationTests/Google.Cloud.Diagnostics.Common.IntegrationTests.csproj
  apis/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common.Tests/Google.Cloud.Diagnostics.Common.Tests.csproj
  apis/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common.csproj
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6666 [apis/Google.Cloud.ServiceControl.V1] feat: Added the gRPC service config for the Service Controller v1 API docs: Updated some comments.
  apis/Google.Cloud.ServiceControl.V1/Google.Cloud.ServiceControl.V1/Distribution.g.cs
  apis/Google.Cloud.ServiceControl.V1/Google.Cloud.ServiceControl.V1/MetricValue.g.cs
  apis/Google.Cloud.ServiceControl.V1/Google.Cloud.ServiceControl.V1/Operation.g.cs
  apis/Google.Cloud.ServiceControl.V1/Google.Cloud.ServiceControl.V1/QuotaController.g.cs
  apis/Google.Cloud.ServiceControl.V1/Google.Cloud.ServiceControl.V1/QuotaControllerClient.g.cs
  apis/Google.Cloud.ServiceControl.V1/Google.Cloud.ServiceControl.V1/QuotaControllerGrpc.g.cs
  apis/Google.Cloud.ServiceControl.V1/Google.Cloud.ServiceControl.V1/ServiceController.g.cs
  apis/Google.Cloud.ServiceControl.V1/Google.Cloud.ServiceControl.V1/ServiceControllerClient.g.cs
  apis/Google.Cloud.ServiceControl.V1/Google.Cloud.ServiceControl.V1/ServiceControllerGrpc.g.cs
  apis/Google.Cloud.ServiceControl.V1/synth.metadata
Labels: cla: yes, context: full

#6664 [apis/ServiceDirectory] feat: Update Service Directory v1beta1 protos to include VPC Network field, and create/modify timestamp fields.
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#6663 [apis/Google.Cloud.ServiceDirectory.V1Beta1] feat: Update Service Directory v1beta1 protos to include VPC Network field, and create/modify timestamp fields.
  apis/Google.Cloud.ServiceDirectory.V1Beta1/Google.Cloud.ServiceDirectory.V1Beta1.Tests/RegistrationServiceClientTest.g.cs
  apis/Google.Cloud.ServiceDirectory.V1Beta1/Google.Cloud.ServiceDirectory.V1Beta1/Endpoint.g.cs
  apis/Google.Cloud.ServiceDirectory.V1Beta1/Google.Cloud.ServiceDirectory.V1Beta1/EndpointResourceNames.g.cs
  apis/Google.Cloud.ServiceDirectory.V1Beta1/Google.Cloud.ServiceDirectory.V1Beta1/LookupService.g.cs
  apis/Google.Cloud.ServiceDirectory.V1Beta1/Google.Cloud.ServiceDirectory.V1Beta1/LookupServiceGrpc.g.cs
  apis/Google.Cloud.ServiceDirectory.V1Beta1/Google.Cloud.ServiceDirectory.V1Beta1/Namespace.g.cs
  apis/Google.Cloud.ServiceDirectory.V1Beta1/Google.Cloud.ServiceDirectory.V1Beta1/RegistrationService.g.cs
  apis/Google.Cloud.ServiceDirectory.V1Beta1/Google.Cloud.ServiceDirectory.V1Beta1/RegistrationServiceClient.g.cs
  apis/Google.Cloud.ServiceDirectory.V1Beta1/Google.Cloud.ServiceDirectory.V1Beta1/RegistrationServiceGrpc.g.cs
  apis/Google.Cloud.ServiceDirectory.V1Beta1/Google.Cloud.ServiceDirectory.V1Beta1/Service.g.cs
  apis/Google.Cloud.ServiceDirectory.V1Beta1/synth.metadata
Labels: cla: yes, context: full

#6667 [CHANGE ME] Re-generated apis/ServiceDirectory to pick up changes in the API or client library generator.
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#6673 [apis/ServiceDirectory] feat: added v1beta, v1 messages and client for gkehub
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#6674 Release Google.Cloud.AIPlatform.V1 version 1.0.0-beta01
  README.md
  apis/Google.Cloud.AIPlatform.V1/.repo-metadata.json
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1.csproj
  apis/Google.Cloud.AIPlatform.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6675 Release Spanner libraries version 3.10.0
  README.md
  apis/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1.csproj
  apis/Google.Cloud.Spanner.Admin.Instance.V1/Google.Cloud.Spanner.Admin.Instance.V1/Google.Cloud.Spanner.Admin.Instance.V1.csproj
  apis/Google.Cloud.Spanner.Common.V1/Google.Cloud.Spanner.Common.V1/Google.Cloud.Spanner.Common.V1.csproj
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.IntegrationTests/Google.Cloud.Spanner.Data.IntegrationTests.csproj
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.Snippets/Google.Cloud.Spanner.Data.Snippets.csproj
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.Tests/Google.Cloud.Spanner.Data.Tests.csproj
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.csproj
  apis/Google.Cloud.Spanner.Data/docs/history.md
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1.csproj
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6677 Release Google.Cloud.Iam.Admin.V1 version 1.0.0
  README.md
  apis/Google.Cloud.Iam.Admin.V1/.repo-metadata.json
  apis/Google.Cloud.Iam.Admin.V1/Google.Cloud.Iam.Admin.V1/Google.Cloud.Iam.Admin.V1.csproj
  apis/Google.Cloud.Iam.Admin.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6678 Release Google.Cloud.ResourceSettings.V1 version 1.0.0
  README.md
  apis/Google.Cloud.ResourceSettings.V1/.repo-metadata.json
  apis/Google.Cloud.ResourceSettings.V1/Google.Cloud.ResourceSettings.V1/Google.Cloud.ResourceSettings.V1.csproj
  apis/Google.Cloud.ResourceSettings.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6679 Release Google.Cloud.ApigeeConnect.V1 version 1.0.0
  README.md
  apis/Google.Cloud.ApigeeConnect.V1/.repo-metadata.json
  apis/Google.Cloud.ApigeeConnect.V1/Google.Cloud.ApigeeConnect.V1/Google.Cloud.ApigeeConnect.V1.csproj
  apis/Google.Cloud.ApigeeConnect.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6680 Release Google.Cloud.Security.PrivateCA.V1 version 1.0.0
  README.md
  apis/Google.Cloud.Security.PrivateCA.V1/.repo-metadata.json
  apis/Google.Cloud.Security.PrivateCA.V1/Google.Cloud.Security.PrivateCA.V1/Google.Cloud.Security.PrivateCA.V1.csproj
  apis/Google.Cloud.Security.PrivateCA.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6682 [apis/Google.Cloud.CloudBuild.V1] Synchronize new proto/yaml changes.
  apis/Google.Cloud.CloudBuild.V1/Google.Cloud.CloudBuild.V1.Snippets/CloudBuildClientSnippets.g.cs
  apis/Google.Cloud.CloudBuild.V1/Google.Cloud.CloudBuild.V1.Tests/CloudBuildClientTest.g.cs
  apis/Google.Cloud.CloudBuild.V1/Google.Cloud.CloudBuild.V1/Cloudbuild.g.cs
  apis/Google.Cloud.CloudBuild.V1/Google.Cloud.CloudBuild.V1/CloudbuildResourceNames.g.cs
  apis/Google.Cloud.CloudBuild.V1/synth.metadata
Labels: cla: yes, context: full

#6683 [apis/ServiceDirectory] Synchronize new proto/yaml changes.
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#6689 [apis/Google.Cloud.ResourceManager.V3] chore(ruby): Configure Ruby microgenerator arguments for Resource Manager V3
  apis/Google.Cloud.ResourceManager.V3/Google.Cloud.ResourceManager.V3/Folders.g.cs
  apis/Google.Cloud.ResourceManager.V3/Google.Cloud.ResourceManager.V3/Organizations.g.cs
  apis/Google.Cloud.ResourceManager.V3/Google.Cloud.ResourceManager.V3/Projects.g.cs
  apis/Google.Cloud.ResourceManager.V3/Google.Cloud.ResourceManager.V3/TagBindings.g.cs
  apis/Google.Cloud.ResourceManager.V3/Google.Cloud.ResourceManager.V3/TagKeys.g.cs
  apis/Google.Cloud.ResourceManager.V3/Google.Cloud.ResourceManager.V3/TagValues.g.cs
  apis/Google.Cloud.ResourceManager.V3/synth.metadata
Labels: cla: yes, context: full

#6690 [CHANGE ME] Re-generated apis/ServiceDirectory to pick up changes in the API or client library generator.
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#6693 Fix DataFusion smoke tests
  apis/Google.Cloud.DataFusion.V1/smoketests.json
Labels: cla: yes

#6694 Return no canonical link for API-specific packages beginning with Google.Apis
  tools/Google.Cloud.Tools.GenerateCanonicalLinks.Tests/CanonicalizerTest.cs
  tools/Google.Cloud.Tools.GenerateCanonicalLinks/Canonicalizer.cs
Labels: cla: yes

#6696 [CHANGE ME] Re-generated apis/Google.Cloud.Datastream.V1Alpha1 to pick up changes in the API or client library generator.
  apis/Google.Cloud.Datastream.V1Alpha1/Google.Cloud.Datastream.V1Alpha1.Snippets/DatastreamClientSnippets.g.cs
  apis/Google.Cloud.Datastream.V1Alpha1/Google.Cloud.Datastream.V1Alpha1.Tests/DatastreamClientTest.g.cs
  apis/Google.Cloud.Datastream.V1Alpha1/Google.Cloud.Datastream.V1Alpha1/Datastream.g.cs
  apis/Google.Cloud.Datastream.V1Alpha1/Google.Cloud.Datastream.V1Alpha1/DatastreamClient.g.cs
  apis/Google.Cloud.Datastream.V1Alpha1/Google.Cloud.Datastream.V1Alpha1/DatastreamGrpc.g.cs
  apis/Google.Cloud.Datastream.V1Alpha1/Google.Cloud.Datastream.V1Alpha1/DatastreamResources.g.cs
  apis/Google.Cloud.Datastream.V1Alpha1/synth.metadata
Labels: cla: yes, context: partial

#6698 [apis/ServiceDirectory] fix!: Remove DiscoverConnectionProfile method signature which didn't populate the request sufficiently fix!: Overhaul resource annotations, some of which were incorrect and some of which were just non-ideal
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#6699 Release Google.Cloud.Datastream.V1Alpha1 version 1.0.0-beta01
  README.md
  apis/Google.Cloud.Datastream.V1Alpha1/.repo-metadata.json
  apis/Google.Cloud.Datastream.V1Alpha1/Google.Cloud.Datastream.V1Alpha1/Google.Cloud.Datastream.V1Alpha1.csproj
  apis/Google.Cloud.Datastream.V1Alpha1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes
