Repository googleapis/google-cloud-dotnet, pull requests merged in 2021-04, with the labels that each got.

#6306 Release Spanner libraries version 3.7.0
  README.md
  apis/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1.csproj
  apis/Google.Cloud.Spanner.Admin.Instance.V1/Google.Cloud.Spanner.Admin.Instance.V1/Google.Cloud.Spanner.Admin.Instance.V1.csproj
  apis/Google.Cloud.Spanner.Common.V1/Google.Cloud.Spanner.Common.V1/Google.Cloud.Spanner.Common.V1.csproj
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.csproj
  apis/Google.Cloud.Spanner.Data/docs/history.md
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1.csproj
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6308 Skip DevSite push for non-Cloud APIs
  tools/Google.Cloud.Tools.PostProcessDevSite/Program.cs
  uploaddocs.sh
Labels: cla: yes

#6311 [apis/ServiceDirectory] feat: Publish Certificate Authority Service V1 API
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#6312 [apis/Google.Cloud.ServiceManagement.V1] build: update links for service-management, update package name for appengine-admin
  apis/Google.Cloud.ServiceManagement.V1/Google.Cloud.ServiceManagement.V1/ServiceManagerClient.g.cs
  apis/Google.Cloud.ServiceManagement.V1/Google.Cloud.ServiceManagement.V1/Servicemanager.cs
  apis/Google.Cloud.ServiceManagement.V1/Google.Cloud.ServiceManagement.V1/ServicemanagerGrpc.cs
  apis/Google.Cloud.ServiceManagement.V1/synth.metadata
Labels: cla: yes, context: full

#6316 [apis/Google.Cloud.Channel.V1] docs: Update documentation comments to match tone and style with the rest of Cloud documentation. Adding customer level pubsub events for primary domain verification and primary domain change. Enabled support for boole
  apis/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1/CloudChannelServiceClient.g.cs
  apis/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1/Common.cs
  apis/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1/Entitlements.cs
  apis/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1/Service.cs
  apis/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1/ServiceGrpc.cs
  apis/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1/SubscriberEvent.cs
  apis/Google.Cloud.Channel.V1/synth.metadata
Labels: cla: yes, context: full

#6317 [apis/Google.Cloud.Dialogflow.Cx.V3] feat: support setting current_page to resume sessions; expose transition_route_groups in flows and language_code in webhook
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3.Tests/FlowsClientTest.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Flow.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/FlowResourceNames.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Intent.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Session.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/SessionResourceNames.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Webhook.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/synth.metadata
Labels: cla: yes, context: full

#6318 [apis/Google.Cloud.Firestore.V1] fix: retry RESOURCE_EXHAUSTED errors docs: various documentation improvements
  apis/Google.Cloud.Firestore.V1/Google.Cloud.Firestore.V1/FirestoreClient.g.cs
  apis/Google.Cloud.Firestore.V1/Google.Cloud.Firestore.V1/FirestoreGrpc.cs
  apis/Google.Cloud.Firestore.V1/Google.Cloud.Firestore.V1/Write.cs
  apis/Google.Cloud.Firestore.V1/synth.metadata
Labels: cla: yes, context: full

#6319 [apis/ServiceDirectory] feat: publish serviceusage/v1 API
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#6321 [apis/Google.Cloud.BinaryAuthorization.V1Beta1] fix: add Java options to Binaryauthorization protos
  apis/Google.Cloud.BinaryAuthorization.V1Beta1/Google.Cloud.BinaryAuthorization.V1Beta1/BinauthzManagementServiceV1Beta1Client.g.cs
  apis/Google.Cloud.BinaryAuthorization.V1Beta1/Google.Cloud.BinaryAuthorization.V1Beta1/Resources.cs
  apis/Google.Cloud.BinaryAuthorization.V1Beta1/Google.Cloud.BinaryAuthorization.V1Beta1/Service.cs
  apis/Google.Cloud.BinaryAuthorization.V1Beta1/Google.Cloud.BinaryAuthorization.V1Beta1/ServiceGrpc.cs
  apis/Google.Cloud.BinaryAuthorization.V1Beta1/synth.metadata
Labels: cla: yes, context: full

#6324 Integration test helpers
  runintegrationtests.sh
Labels: cla: yes

#6322 [apis/Google.Cloud.Speech.V1P1Beta1] feat: Support for spoken punctuation and spoken emojis.
  apis/Google.Cloud.Speech.V1P1Beta1/Google.Cloud.Speech.V1P1Beta1/CloudSpeech.cs
  apis/Google.Cloud.Speech.V1P1Beta1/synth.metadata
Labels: cla: yes, context: full

#6327 [apis/Google.Cloud.Dataproc.V1] feat: update the Dataproc V1 API client library
  apis/Google.Cloud.Dataproc.V1/Google.Cloud.Dataproc.V1.Snippets/ClusterControllerClientSnippets.g.cs
  apis/Google.Cloud.Dataproc.V1/Google.Cloud.Dataproc.V1.Tests/WorkflowTemplateServiceClientTest.g.cs
  apis/Google.Cloud.Dataproc.V1/Google.Cloud.Dataproc.V1/ClusterControllerClient.g.cs
  apis/Google.Cloud.Dataproc.V1/Google.Cloud.Dataproc.V1/Clusters.cs
  apis/Google.Cloud.Dataproc.V1/Google.Cloud.Dataproc.V1/ClustersGrpc.cs
  apis/Google.Cloud.Dataproc.V1/Google.Cloud.Dataproc.V1/ClustersResourceNames.g.cs
  apis/Google.Cloud.Dataproc.V1/Google.Cloud.Dataproc.V1/Jobs.cs
  apis/Google.Cloud.Dataproc.V1/Google.Cloud.Dataproc.V1/Shared.cs
  apis/Google.Cloud.Dataproc.V1/Google.Cloud.Dataproc.V1/WorkflowTemplateServiceClient.g.cs
  apis/Google.Cloud.Dataproc.V1/Google.Cloud.Dataproc.V1/WorkflowTemplates.cs
  apis/Google.Cloud.Dataproc.V1/Google.Cloud.Dataproc.V1/WorkflowTemplatesGrpc.cs
  apis/Google.Cloud.Dataproc.V1/gapic_metadata.json
  apis/Google.Cloud.Dataproc.V1/synth.metadata
Labels: cla: yes, context: full

#6330 Remove legacy empty resource name files
  apis/Google.Cloud.Debugger.V2/Google.Cloud.Debugger.V2/ResourceNames.cs
  apis/Google.Cloud.Speech.V1P1Beta1/Google.Cloud.Speech.V1P1Beta1/ResourceNames.cs
  apis/Google.Cloud.TextToSpeech.V1/Google.Cloud.TextToSpeech.V1/ResourceNames.cs
  apis/Google.Cloud.VideoIntelligence.V1/Google.Cloud.VideoIntelligence.V1/ResourceNames.cs
  apis/Google.Cloud.WebRisk.V1Beta1/Google.Cloud.WebRisk.V1Beta1/ResourceNames.cs
  apis/Google.LongRunning/Google.LongRunning/ResourceNames.cs
Labels: cla: yes

#6335 [apis/ServiceDirectory] feat: Adding BigQuery Migration v2alpha API.
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#6336 Regenerate server-streaming calls with Google request params
  apis/Google.Cloud.BigQuery.Storage.V1/Google.Cloud.BigQuery.Storage.V1/BigQueryReadClient.g.cs
  apis/Google.Cloud.Bigtable.V2/Google.Cloud.Bigtable.V2/BigtableServiceApiClient.g.cs
  apis/Google.Cloud.Firestore.V1/Google.Cloud.Firestore.V1/FirestoreClient.g.cs
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/SpannerClient.g.cs
Labels: cla: yes

#6338 Release Google.Analytics.Admin.V1Alpha version 1.0.0-alpha05
  README.md
  apis/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha.csproj
  apis/Google.Analytics.Admin.V1Alpha/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6339 [apis/Google.Cloud.Spanner.Admin.Database.V1] feat(spanner): add `progress` field to `UpdateDatabaseDdlMetadata`
  apis/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1/Backup.g.cs
  apis/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1/Common.g.cs
  apis/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1/DatabaseAdminClient.g.cs
  apis/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1/SpannerDatabaseAdmin.g.cs
  apis/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1/SpannerDatabaseAdminGrpc.g.cs
  apis/Google.Cloud.Spanner.Admin.Database.V1/synth.metadata
Labels: api: spanner, cla: yes, context: full

#6340 [apis/Google.Cloud.Spanner.V1] feat(spanner): add `progress` field to `UpdateDatabaseDdlMetadata`
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/CommitResponse.g.cs
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/Spanner.g.cs
  apis/Google.Cloud.Spanner.V1/synth.metadata
Labels: api: spanner, cla: yes, context: full

#6342 Fix service directory generation around "import public"
  tools/Google.Cloud.Tools.Common/ServiceDirectory.cs
Labels: cla: yes

#6345 [apis/Google.Cloud.CloudBuild.V1] feat: Add fields for Pub/Sub triggers
  apis/Google.Cloud.CloudBuild.V1/Google.Cloud.CloudBuild.V1.Tests/CloudBuildClientTest.g.cs
  apis/Google.Cloud.CloudBuild.V1/Google.Cloud.CloudBuild.V1/Cloudbuild.g.cs
  apis/Google.Cloud.CloudBuild.V1/Google.Cloud.CloudBuild.V1/CloudbuildResourceNames.g.cs
  apis/Google.Cloud.CloudBuild.V1/synth.metadata
Labels: cla: yes, context: full

#6344 chore(Spanner): Add skuruppu as default assignee for spanner issues
  .github/blunderbuss.yml
Labels: api: spanner, cla: yes

#6347 Move Google.Cloud.Tools.DocfxMetadata into the tools directory
  docs/Google.Cloud.DocTools.sln
  tools/Google.Cloud.Tools.DocfxMetadata/Google.Cloud.Tools.DocfxMetadata.csproj
  tools/Google.Cloud.Tools.DocfxMetadata/ItemType.cs
  tools/Google.Cloud.Tools.DocfxMetadata/MetadataFile.cs
  tools/Google.Cloud.Tools.DocfxMetadata/MetadataItem.cs
  tools/Google.Cloud.Tools.DocfxMetadata/TocEntry.cs
  tools/Google.Cloud.Tools.DocfxMetadata/YamlHelpers.cs
  tools/Google.Cloud.Tools.RegenerateToc/Google.Cloud.Tools.RegenerateToc.csproj
Labels: cla: yes

#6348 Re-generated apis/ServiceDirectory with "public import" fixes
  apis/ServiceDirectory/directory.json
Labels: cla: yes, context: none

#6349 [apis/Google.Cloud.DataCatalog.V1] docs: reformat comments in PolicyTagManager definition
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/PolicyTagManagerClient.g.cs
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/Policytagmanager.g.cs
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/PolicytagmanagerGrpc.g.cs
  apis/Google.Cloud.DataCatalog.V1/synth.metadata
Labels: cla: yes, context: full

#6350 [apis/Google.Cloud.Gaming.V1Beta] chore: migrate gaming/{v1, v1beta} to the PHP microgenerator
  apis/Google.Cloud.Gaming.V1Beta/Google.Cloud.Gaming.V1Beta/GameServerClusters.g.cs
  apis/Google.Cloud.Gaming.V1Beta/Google.Cloud.Gaming.V1Beta/GameServerClustersService.g.cs
  apis/Google.Cloud.Gaming.V1Beta/Google.Cloud.Gaming.V1Beta/GameServerConfigs.g.cs
  apis/Google.Cloud.Gaming.V1Beta/Google.Cloud.Gaming.V1Beta/GameServerConfigsService.g.cs
  apis/Google.Cloud.Gaming.V1Beta/Google.Cloud.Gaming.V1Beta/GameServerDeployments.g.cs
  apis/Google.Cloud.Gaming.V1Beta/Google.Cloud.Gaming.V1Beta/GameServerDeploymentsService.g.cs
  apis/Google.Cloud.Gaming.V1Beta/Google.Cloud.Gaming.V1Beta/GameServerDeploymentsServiceClient.g.cs
  apis/Google.Cloud.Gaming.V1Beta/Google.Cloud.Gaming.V1Beta/Realms.g.cs
  apis/Google.Cloud.Gaming.V1Beta/Google.Cloud.Gaming.V1Beta/RealmsService.g.cs
  apis/Google.Cloud.Gaming.V1Beta/synth.metadata
Labels: cla: yes, context: full

#6351 [apis/Google.Cloud.Security.PrivateCA.V1] feat!: Refactored Elliptic Key curves to provide additional options, the NamedCurve enum is replaced by the EcKeyType message.
  apis/Google.Cloud.Security.PrivateCA.V1/Google.Cloud.Security.PrivateCA.V1/CertificateAuthorityServiceClient.g.cs
  apis/Google.Cloud.Security.PrivateCA.V1/Google.Cloud.Security.PrivateCA.V1/Resources.g.cs
  apis/Google.Cloud.Security.PrivateCA.V1/Google.Cloud.Security.PrivateCA.V1/Service.g.cs
  apis/Google.Cloud.Security.PrivateCA.V1/Google.Cloud.Security.PrivateCA.V1/ServiceGrpc.g.cs
  apis/Google.Cloud.Security.PrivateCA.V1/synth.metadata
Labels: cla: yes, context: full

#6352 [apis/Google.Cloud.Billing.Budgets.V1] feat: Added support for configurable budget time period. fix: Updated some documentation links.
  apis/Google.Cloud.Billing.Budgets.V1/Google.Cloud.Billing.Budgets.V1/BudgetModel.g.cs
  apis/Google.Cloud.Billing.Budgets.V1/synth.metadata
Labels: cla: yes, context: full

#6353 [apis/Google.Cloud.Billing.Budgets.V1Beta1] feat: Added support for configurable budget time period. fix: Updated some documentation links.
  apis/Google.Cloud.Billing.Budgets.V1Beta1/Google.Cloud.Billing.Budgets.V1Beta1/BudgetModel.g.cs
  apis/Google.Cloud.Billing.Budgets.V1Beta1/synth.metadata
Labels: cla: yes, context: full

#6354 [apis/ServiceDirectory] feat: publish serviceusage/v1beta1 API
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#6356 Clean up resources at the end of Compute tests
  apis/Google.Cloud.Compute.V1/Google.Cloud.Compute.V1.IntegrationTests/AcceptanceTest.cs
  apis/Google.Cloud.Compute.V1/Google.Cloud.Compute.V1.IntegrationTests/ComputeFixture.cs
Labels: cla: yes

#6357 Simplify deleting generated files
  generateapis.sh
Labels: cla: yes

#6359 [apis/ServiceDirectory] feat: Cloud Privatecatalog service protos
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#6362 Simplify how we run smoke tests
  NEWAPI.md
  runintegrationtests.sh
  tools/Google.Cloud.Tools.ReleaseManager/SmokeTestCommand.cs
Labels: cla: yes

#6364 Fix Compute documentation generation
  tools/Google.Cloud.Tools.Common/ApiMetadata.cs
  tools/Google.Cloud.Tools.GenerateDocfxSources/Program.cs
Labels: cla: yes

#6365 [apis/ServiceDirectory] feat!:Publish Cloud ResourceSettings v1 API
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#6366 tests: Fixes flakiness by diferenciating some error messages.
  apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore.IntegrationTests/ErrorReporting/ErrorReportingTest.cs
Labels: cla: yes

#6369 [apis/Google.Cloud.DocumentAI.V1] feat: add confidence field to the PageAnchor.PageRef in document.proto.
  apis/Google.Cloud.DocumentAI.V1/Google.Cloud.DocumentAI.V1/Document.g.cs
  apis/Google.Cloud.DocumentAI.V1/synth.metadata
Labels: cla: yes, context: full

#6370 [apis/Google.Cloud.Speech.V1P1Beta1] feat: add webm opus support.
  apis/Google.Cloud.Speech.V1P1Beta1/Google.Cloud.Speech.V1P1Beta1/CloudSpeech.g.cs
  apis/Google.Cloud.Speech.V1P1Beta1/synth.metadata
Labels: cla: yes, context: full

#6372 [apis/ServiceDirectory] feat: adding new Cloud Client Libraries for essentialcontacts.googleapis.com
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#6371 [apis/Google.Identity.AccessContextManager.Type] fix: specify valid go_package option
  apis/Google.Identity.AccessContextManager.Type/Google.Identity.AccessContextManager.Type/DeviceResources.cs
  apis/Google.Identity.AccessContextManager.Type/synth.metadata
Labels: cla: yes, context: full

#6375 [apis/Google.Analytics.Admin.V1Alpha] fix!: remove `CreateIosAppDataStream`, `CreateAndroidAppDataStream` methods from the API feat: add `SearchChangeHistoryEvents` method to the API fix!: update `DeleteProperty` method to return the deleted property
  apis/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha.Snippets/AnalyticsAdminServiceClientSnippets.g.cs
  apis/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha.Tests/AnalyticsAdminServiceClientTest.g.cs
  apis/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha/AnalyticsAdmin.g.cs
  apis/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha/AnalyticsAdminGrpc.g.cs
  apis/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha/AnalyticsAdminResourceNames.g.cs
  apis/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha/AnalyticsAdminServiceClient.g.cs
  apis/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha/Resources.g.cs
  apis/Google.Analytics.Admin.V1Alpha/gapic_metadata.json
  apis/Google.Analytics.Admin.V1Alpha/synth.metadata
Labels: cla: yes, context: full

#6376 [apis/Google.Cloud.MediaTranslation.V1Beta1] fix!: Remove unsupported fields: recognition_result and alternative_source_language_codes. docs: Add more comments for supported audio type.
  apis/Google.Cloud.MediaTranslation.V1Beta1/Google.Cloud.MediaTranslation.V1Beta1/MediaTranslation.g.cs
  apis/Google.Cloud.MediaTranslation.V1Beta1/Google.Cloud.MediaTranslation.V1Beta1/MediaTranslationGrpc.g.cs
  apis/Google.Cloud.MediaTranslation.V1Beta1/synth.metadata
Labels: cla: yes, context: full

#6377 [apis/Google.Cloud.Security.PrivateCA.V1] chore: migrate security/privateca to the PHP microgenerator
  apis/Google.Cloud.Security.PrivateCA.V1/Google.Cloud.Security.PrivateCA.V1/Service.g.cs
  apis/Google.Cloud.Security.PrivateCA.V1/synth.metadata
Labels: cla: yes, context: full

#6378 [apis/Google.Cloud.ServiceManagement.V1] feat: Publish visibility.proto; refresh other google/api/ files.
  apis/Google.Cloud.ServiceManagement.V1/Google.Cloud.ServiceManagement.V1.Tests/ServiceManagerClientTest.g.cs
  apis/Google.Cloud.ServiceManagement.V1/synth.metadata
Labels: cla: yes, context: full

#6380 Release Google.Cloud.MediaTranslation.V1Beta1 version 1.0.0-beta02
  README.md
  apis/Google.Cloud.MediaTranslation.V1Beta1/Google.Cloud.MediaTranslation.V1Beta1/Google.Cloud.MediaTranslation.V1Beta1.csproj
  apis/Google.Cloud.MediaTranslation.V1Beta1/docs/history.md
  apis/apis.json
  docs/root/index.md
  tools/Google.Cloud.Tools.ReleaseManager/History/overrides.json
Labels: autorelease: pending, cla: yes

#6381 tools: More skipped commits, and remove unnecessary code in GitCommit
  tools/Google.Cloud.Tools.ReleaseManager/History/GitCommit.cs
  tools/Google.Cloud.Tools.ReleaseManager/History/overrides.json
Labels: automerge, cla: yes

#6379 Release GSuite AddOns libraries version 1.0.0-beta01
  README.md
  apis/Google.Apps.Script.Type/.repo-metadata.json
  apis/Google.Apps.Script.Type/Google.Apps.Script.Type/Google.Apps.Script.Type.csproj
  apis/Google.Apps.Script.Type/docs/history.md
  apis/Google.Cloud.GSuiteAddOns.V1/.repo-metadata.json
  apis/Google.Cloud.GSuiteAddOns.V1/Google.Cloud.GSuiteAddOns.V1/Google.Cloud.GSuiteAddOns.V1.csproj
  apis/Google.Cloud.GSuiteAddOns.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6384 Release Google.Analytics.Admin.V1Alpha version 1.0.0-alpha06
  README.md
  apis/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha.csproj
  apis/Google.Analytics.Admin.V1Alpha/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6385 Release Google.Analytics.Data.V1Beta version 1.0.0-beta03
  README.md
  apis/Google.Analytics.Data.V1Beta/Google.Analytics.Data.V1Beta/Google.Analytics.Data.V1Beta.csproj
  apis/Google.Analytics.Data.V1Beta/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6386 Release Google.Area120.Tables.V1Alpha1 version 1.0.0-alpha03
  README.md
  apis/Google.Area120.Tables.V1Alpha1/Google.Area120.Tables.V1Alpha1/Google.Area120.Tables.V1Alpha1.csproj
  apis/Google.Area120.Tables.V1Alpha1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6389 [apis/Google.Cloud.Dialogflow.Cx.V3] feat: Expose supported languages of the agent; feat: add export / import flow API docs: Update docs on Pages, Session, Version, etc.
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3.Snippets/AgentsClientSnippets.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3.Snippets/FlowsClientSnippets.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3.Tests/AgentsClientTest.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Agent.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/AgentResourceNames.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Experiment.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Flow.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/FlowGrpc.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/FlowResourceNames.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/FlowsClient.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Page.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Session.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/SessionGrpc.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/SessionsClient.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/TransitionRouteGroup.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Version.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/VersionGrpc.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/VersionsClient.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/gapic_metadata.json
  apis/Google.Cloud.Dialogflow.Cx.V3/synth.metadata
Labels: cla: yes, context: full

#6387 Release Google.Cloud.AssuredWorkloads.V1Beta1 version 1.0.0-beta04
  README.md
  apis/Google.Cloud.AssuredWorkloads.V1Beta1/Google.Cloud.AssuredWorkloads.V1Beta1/Google.Cloud.AssuredWorkloads.V1Beta1.csproj
  apis/Google.Cloud.AssuredWorkloads.V1Beta1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6388 Release Google.Cloud.Billing.Budgets.V1 version 1.1.0
  README.md
  apis/Google.Cloud.Billing.Budgets.V1/Google.Cloud.Billing.Budgets.V1/Google.Cloud.Billing.Budgets.V1.csproj
  apis/Google.Cloud.Billing.Budgets.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6391 [apis/ServiceDirectory] feat: publish protos for Google Ads API v7
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#6396 Release Google.Cloud.Speech.V1P1Beta1 version 2.0.0-beta04
  README.md
  apis/Google.Cloud.Speech.V1P1Beta1/Google.Cloud.Speech.V1P1Beta1/Google.Cloud.Speech.V1P1Beta1.csproj
  apis/Google.Cloud.Speech.V1P1Beta1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6392 Release Google.Cloud.Billing.Budgets.V1Beta1 version 1.0.0-beta03
  README.md
  apis/Google.Cloud.Billing.Budgets.V1Beta1/Google.Cloud.Billing.Budgets.V1Beta1/Google.Cloud.Billing.Budgets.V1Beta1.csproj
  apis/Google.Cloud.Billing.Budgets.V1Beta1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6394 Release Google.Cloud.Dataproc.V1 version 3.1.0
  README.md
  apis/Google.Cloud.Dataproc.V1/Google.Cloud.Dataproc.V1/Google.Cloud.Dataproc.V1.csproj
  apis/Google.Cloud.Dataproc.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6395 Release Google.Cloud.Vision.V1 version 2.3.0
  README.md
  apis/Google.Cloud.Vision.V1/Google.Cloud.Vision.V1/Google.Cloud.Vision.V1.csproj
  apis/Google.Cloud.Vision.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6393 Release Google.Cloud.Iot.V1 version 1.1.0
  README.md
  apis/Google.Cloud.Iot.V1/Google.Cloud.Iot.V1/Google.Cloud.Iot.V1.csproj
  apis/Google.Cloud.Iot.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6398 Release Google.Cloud.Recommender.V1 version 2.5.0
  README.md
  apis/Google.Cloud.Recommender.V1/Google.Cloud.Recommender.V1/Google.Cloud.Recommender.V1.csproj
  apis/Google.Cloud.Recommender.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6400 Release Google.Cloud.Datastore.Admin.V1 version 1.1.0
  README.md
  apis/Google.Cloud.Datastore.Admin.V1/Google.Cloud.Datastore.Admin.V1/Google.Cloud.Datastore.Admin.V1.csproj
  apis/Google.Cloud.Datastore.Admin.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6399 Release Google.Cloud.BinaryAuthorization.V1Beta1 version 1.0.0-beta02
  README.md
  apis/Google.Cloud.BinaryAuthorization.V1Beta1/Google.Cloud.BinaryAuthorization.V1Beta1/Google.Cloud.BinaryAuthorization.V1Beta1.csproj
  apis/Google.Cloud.BinaryAuthorization.V1Beta1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6401 Release Google.Cloud.Dialogflow.V2 version 3.2.0
  README.md
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2.csproj
  apis/Google.Cloud.Dialogflow.V2/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6402 Release Google.Cloud.ManagedIdentities.V1 version 2.2.0
  README.md
  apis/Google.Cloud.ManagedIdentities.V1/Google.Cloud.ManagedIdentities.V1/Google.Cloud.ManagedIdentities.V1.csproj
  apis/Google.Cloud.ManagedIdentities.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6403 Release Google.Cloud.ErrorReporting.V1Beta1 version 2.0.0-beta04
  README.md
  apis/Google.Cloud.ErrorReporting.V1Beta1/Google.Cloud.ErrorReporting.V1Beta1/Google.Cloud.ErrorReporting.V1Beta1.csproj
  apis/Google.Cloud.ErrorReporting.V1Beta1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6404 Release Google.Cloud.Dialogflow.Cx.V3 version 1.1.0
  README.md
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3.csproj
  apis/Google.Cloud.Dialogflow.Cx.V3/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6405 Release Google.Cloud.ServiceManagement.V1 version 1.1.0
  README.md
  apis/Google.Cloud.ServiceManagement.V1/Google.Cloud.ServiceManagement.V1/Google.Cloud.ServiceManagement.V1.csproj
  apis/Google.Cloud.ServiceManagement.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6407 Release Google.Cloud.Asset.V1 version 2.7.0
  README.md
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1.csproj
  apis/Google.Cloud.Asset.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6406 Release Google.Cloud.VideoIntelligence.V1 version 2.2.0
  README.md
  apis/Google.Cloud.VideoIntelligence.V1/Google.Cloud.VideoIntelligence.V1/Google.Cloud.VideoIntelligence.V1.csproj
  apis/Google.Cloud.VideoIntelligence.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6408 Release Google.Cloud.GkeHub.V1Beta1 version 1.0.0-beta02
  README.md
  apis/Google.Cloud.GkeHub.V1Beta1/Google.Cloud.GkeHub.V1Beta1/Google.Cloud.GkeHub.V1Beta1.csproj
  apis/Google.Cloud.GkeHub.V1Beta1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6409 Release Google.Cloud.Channel.V1 version 1.1.0
  README.md
  apis/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1.csproj
  apis/Google.Cloud.Channel.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6410 Release Google.Cloud.DocumentAI.V1 version 1.0.0-beta02
  README.md
  apis/Google.Cloud.DocumentAI.V1/Google.Cloud.DocumentAI.V1/Google.Cloud.DocumentAI.V1.csproj
  apis/Google.Cloud.DocumentAI.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6411 Release Google.Cloud.Kms.V1 version 2.2.0
  README.md
  apis/Google.Cloud.Kms.V1/Google.Cloud.Kms.V1/Google.Cloud.Kms.V1.csproj
  apis/Google.Cloud.Kms.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6417 test: enable integration tests for NUMERIC on emulator
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.IntegrationTests/AllTypesTableFixture.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.IntegrationTests/WriteTests.cs
Labels: cla: yes

#6412 Release Google.Cloud.Monitoring.V3 version 2.3.0
  README.md
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3.csproj
  apis/Google.Cloud.Monitoring.V3/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6413 Release Google.Cloud.Retail.V2 version 1.1.0
  README.md
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2.csproj
  apis/Google.Cloud.Retail.V2/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6414 Release Google.Cloud.ServiceControl.V1 version 1.1.0
  README.md
  apis/Google.Cloud.ServiceControl.V1/Google.Cloud.ServiceControl.V1/Google.Cloud.ServiceControl.V1.csproj
  apis/Google.Cloud.ServiceControl.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6415 Release Google.Cloud.CloudBuild.V1 version 1.1.0
  README.md
  apis/Google.Cloud.CloudBuild.V1/Google.Cloud.CloudBuild.V1/Google.Cloud.CloudBuild.V1.csproj
  apis/Google.Cloud.CloudBuild.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6416 Release Google.Cloud.AppEngine.V1 version 1.1.0
  README.md
  apis/Google.Cloud.AppEngine.V1/Google.Cloud.AppEngine.V1/Google.Cloud.AppEngine.V1.csproj
  apis/Google.Cloud.AppEngine.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6418 [apis/ServiceDirectory] fix: adding namespace rules for C#, php, and ruby
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full
