Repository googleapis/google-cloud-dotnet, pull requests merged in 2021-08, with the labels that each got.

#6850 [apis/Google.Cloud.Dialogflow.V2] docs: fix typos
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/ValidationResult.g.cs
  apis/Google.Cloud.Dialogflow.V2/synth.metadata
Labels: cla: yes, context: full

#6877 feat(compat): Support custom attributes in generic parameters.
  tools/Google.Cloud.Tools.VersionCompat.Tests/ClassMethodTest.cs
  tools/Google.Cloud.Tools.VersionCompat/CecilUtils/SameGenericParameterConstraintComparer.cs
  tools/Google.Cloud.Tools.VersionCompat/Detectors/ClassStructInterface.cs
  tools/Google.Cloud.Tools.VersionCompat/Google.Cloud.Tools.VersionCompat.csproj
Labels: cla: yes

#6880 chore: Update Bigtable client generator dependencies
  apis/Google.Cloud.Bigtable.V2/Google.Cloud.Bigtable.V2.GenerateClient/Google.Cloud.Bigtable.V2.GenerateClient.csproj
  apis/Google.Cloud.Bigtable.V2/Google.Cloud.Bigtable.V2.GenerateClient/Program.cs
Labels: cla: yes

#6881 chore: Fix the analyzer
  tools/Google.Cloud.AnalyzersTesting/Google.Cloud.AnalyzersTesting.csproj
  tools/Google.Cloud.Tools.Analyzers/Google.Cloud.Tools.Analyzers.csproj
  tools/Google.Cloud.Tools.Analyzers/InternalOptionalParametersRequiredAnalyzer.cs
  tools/Google.Cloud.Tools.Analyzers/PublicDependencyForbiddenAnalyzer.cs
Labels: cla: yes

#6886 [apis/Google.Cloud.Dialogflow.V2] fix: fix validation result docs feat: add language code to streaming recognition result docs: update environment docs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/Environment.g.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/EnvironmentGrpc.g.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/EnvironmentsClient.g.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/Session.g.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/Version.g.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/VersionsClient.g.cs
  apis/Google.Cloud.Dialogflow.V2/synth.metadata
Labels: cla: yes, context: full

#6887 [apis/Google.Cloud.Retail.V2] docs(retail): Quote several literal expressions for better rendering
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/SearchService.g.cs
  apis/Google.Cloud.Retail.V2/synth.metadata
Labels: api: retail, cla: yes, context: full

#6890 build: Fixes Diagnostics renovate config.
  .github/renovate.json
  tools/Google.Cloud.Tools.ReleaseManager/GenerateProjectsCommand.cs
Labels: cla: yes

#6891 Release Google.Cloud.NetworkManagement.V1 version 1.0.0
  README.md
  apis/Google.Cloud.NetworkManagement.V1/.repo-metadata.json
  apis/Google.Cloud.NetworkManagement.V1/Google.Cloud.NetworkManagement.V1/Google.Cloud.NetworkManagement.V1.csproj
  apis/Google.Cloud.NetworkManagement.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, cla: yes

#6892 Remove unused fields in PublisherClient
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/PublisherClient.cs
Labels: cla: yes

#6896 [apis/Google.Cloud.Functions.V1] fix: Updating behavior of source_upload_url during Get/List function calls
  apis/Google.Cloud.Functions.V1/Google.Cloud.Functions.V1/Functions.g.cs
  apis/Google.Cloud.Functions.V1/Google.Cloud.Functions.V1/FunctionsGrpc.g.cs
  apis/Google.Cloud.Functions.V1/synth.metadata
Labels: cla: yes, context: full

#6897 [apis/Google.Cloud.Kms.V1] feat: add support for HMAC, Variable Key Destruction, and GenerateRandom
  apis/Google.Cloud.Kms.V1/Google.Cloud.Kms.V1.Snippets/KeyManagementServiceClientSnippets.g.cs
  apis/Google.Cloud.Kms.V1/Google.Cloud.Kms.V1.Tests/KeyManagementServiceClientTest.g.cs
  apis/Google.Cloud.Kms.V1/Google.Cloud.Kms.V1/KeyManagementServiceClient.g.cs
  apis/Google.Cloud.Kms.V1/Google.Cloud.Kms.V1/Resources.g.cs
  apis/Google.Cloud.Kms.V1/Google.Cloud.Kms.V1/Service.g.cs
  apis/Google.Cloud.Kms.V1/Google.Cloud.Kms.V1/ServiceGrpc.g.cs
  apis/Google.Cloud.Kms.V1/Google.Cloud.Kms.V1/ServiceResourceNames.g.cs
  apis/Google.Cloud.Kms.V1/gapic_metadata.json
  apis/Google.Cloud.Kms.V1/synth.metadata
Labels: cla: yes, context: full

#6901 [apis/Google.Cloud.Video.Transcoder.V1Beta1] feat: Add video cropping feature feat: Add video padding feature feat: Add ttl_after_completion_days field to Job docs: Update proto documentation docs: Indicate v1beta1 deprecation
  apis/Google.Cloud.Video.Transcoder.V1Beta1/Google.Cloud.Video.Transcoder.V1Beta1.Tests/TranscoderServiceClientTest.g.cs
  apis/Google.Cloud.Video.Transcoder.V1Beta1/Google.Cloud.Video.Transcoder.V1Beta1/Resources.g.cs
  apis/Google.Cloud.Video.Transcoder.V1Beta1/Google.Cloud.Video.Transcoder.V1Beta1/Services.g.cs
  apis/Google.Cloud.Video.Transcoder.V1Beta1/Google.Cloud.Video.Transcoder.V1Beta1/ServicesGrpc.g.cs
  apis/Google.Cloud.Video.Transcoder.V1Beta1/synth.metadata
Labels: cla: yes, context: full

#6904 Release Google.Cloud.AIPlatform.V1 version 1.0.0-beta02
  README.md
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1.csproj
  apis/Google.Cloud.AIPlatform.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending

#6905 Update Compute GAX dependency to 3.5.0-beta01
  apis/Google.Cloud.Compute.V1/Google.Cloud.Compute.V1/Google.Cloud.Compute.V1.csproj
  apis/apis.json
Labels: cla: yes

#6898 tests(compute): Test surfacing meaningful error messages.
  apis/Google.Cloud.Compute.V1/Google.Cloud.Compute.V1.IntegrationTests/AcceptanceTest.cs
Labels: cla: yes, api: compute, automerge

#6906 Release Google.Cloud.Compute.V1 version 1.0.0-beta01
  README.md
  apis/Google.Cloud.Compute.V1/.repo-metadata.json
  apis/Google.Cloud.Compute.V1/Google.Cloud.Compute.V1/Google.Cloud.Compute.V1.csproj
  apis/Google.Cloud.Compute.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending

#6908 [apis/Google.Cloud.Speech.V1] feat: add total_billed_time response field
  apis/Google.Cloud.Speech.V1/Google.Cloud.Speech.V1.Tests/SpeechClientTest.g.cs
  apis/Google.Cloud.Speech.V1/Google.Cloud.Speech.V1/CloudSpeech.g.cs
  apis/Google.Cloud.Speech.V1/Google.Cloud.Speech.V1/CloudSpeechGrpc.g.cs
  apis/Google.Cloud.Speech.V1/synth.metadata
Labels: cla: yes, context: full

#6911 Generate projects automatically at end of generateapis.sh
  NEWAPI.md
  generateapis.sh
Labels: cla: yes

#6909 In GetOrCreate, retry "get" operation if "create" fails due to conflict
  apis/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2.IntegrationTests/DatasetsTest.cs
  apis/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2.IntegrationTests/RoutineTests.cs
  apis/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2.IntegrationTests/TablesTest.cs
  apis/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2/BigQueryClientImpl.DatasetCrud.cs
  apis/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2/BigQueryClientImpl.RoutineCrud.cs
  apis/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2/BigQueryClientImpl.TableCrud.cs
Labels: cla: yes

#6912 Release Google.Cloud.BigQuery.V2 version 2.3.0
  README.md
  apis/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2.csproj
  apis/Google.Cloud.BigQuery.V2/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending

#6913 Release Google.Cloud.AssuredWorkloads.V1Beta1 version 1.0.0-beta05
  README.md
  apis/Google.Cloud.AssuredWorkloads.V1Beta1/Google.Cloud.AssuredWorkloads.V1Beta1/Google.Cloud.AssuredWorkloads.V1Beta1.csproj
  apis/Google.Cloud.AssuredWorkloads.V1Beta1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending

#6915 Release Google.Cloud.BigQuery.Connection.V1 version 1.3.0
  README.md
  apis/Google.Cloud.BigQuery.Connection.V1/Google.Cloud.BigQuery.Connection.V1/Google.Cloud.BigQuery.Connection.V1.csproj
  apis/Google.Cloud.BigQuery.Connection.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending

#6919 Release Google.Cloud.Dialogflow.Cx.V3 version 1.3.0
  README.md
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3.csproj
  apis/Google.Cloud.Dialogflow.Cx.V3/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending

#6917 Release Google.Cloud.DataCatalog.V1 version 1.3.0
  README.md
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1.csproj
  apis/Google.Cloud.DataCatalog.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending

#6918 Release Google.Cloud.Datastore.Admin.V1 version 1.2.0
  README.md
  apis/Google.Cloud.Datastore.Admin.V1/Google.Cloud.Datastore.Admin.V1/Google.Cloud.Datastore.Admin.V1.csproj
  apis/Google.Cloud.Datastore.Admin.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending

#6916 Release Google.Cloud.Container.V1 version 2.5.0
  README.md
  apis/Google.Cloud.Container.V1/Google.Cloud.Container.V1/Google.Cloud.Container.V1.csproj
  apis/Google.Cloud.Container.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending

#6920 Workaround for autosynth squashing lines in commit messages
  tools/Google.Cloud.Tools.ReleaseManager/History/GitCommit.cs
Labels: cla: yes

#6921 Release Google.Cloud.PubSub.V1 version 2.6.0
  README.md
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1.csproj
  apis/Google.Cloud.PubSub.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending

#6923 Remove accidental diagnostic line
  tools/Google.Cloud.Tools.ReleaseManager/History/GitCommit.cs
Labels: cla: yes

#6925 Release Google.Cloud.ResourceSettings.V1 version 1.1.0
  README.md
  apis/Google.Cloud.ResourceSettings.V1/Google.Cloud.ResourceSettings.V1/Google.Cloud.ResourceSettings.V1.csproj
  apis/Google.Cloud.ResourceSettings.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending

#6930 Stop using labeled/unlabeled as a trigger for diff-pr
  .github/workflows/diff-pr.yml
Labels: cla: yes

#6929 Release Google.Cloud.Speech.V1 version 2.3.0
  README.md
  apis/Google.Cloud.Speech.V1/Google.Cloud.Speech.V1/Google.Cloud.Speech.V1.csproj
  apis/Google.Cloud.Speech.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending

#6924 Release Google.Cloud.Kms.V1 version 2.4.0
  README.md
  apis/Google.Cloud.Kms.V1/Google.Cloud.Kms.V1/Google.Cloud.Kms.V1.csproj
  apis/Google.Cloud.Kms.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending

#6922 Release Google.Cloud.Dialogflow.V2 version 3.4.0
  README.md
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2.csproj
  apis/Google.Cloud.Dialogflow.V2/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending

#6928 Release Google.Cloud.SecurityCenter.V1 version 2.5.0
  README.md
  apis/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1.csproj
  apis/Google.Cloud.SecurityCenter.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending

#6931 Release Google.Cloud.Video.Transcoder.V1Beta1 version 1.0.0-beta03
  README.md
  apis/Google.Cloud.Video.Transcoder.V1Beta1/Google.Cloud.Video.Transcoder.V1Beta1/Google.Cloud.Video.Transcoder.V1Beta1.csproj
  apis/Google.Cloud.Video.Transcoder.V1Beta1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending

#6927 Release Google.Cloud.SecretManager.V1 version 1.6.0
  README.md
  apis/Google.Cloud.SecretManager.V1/Google.Cloud.SecretManager.V1/Google.Cloud.SecretManager.V1.csproj
  apis/Google.Cloud.SecretManager.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending

#6926 Release Google.Cloud.Retail.V2 version 1.2.0
  README.md
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2.csproj
  apis/Google.Cloud.Retail.V2/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending

#6932 Release Google.Identity.AccessContextManager.V1 version 1.3.0
  README.md
  apis/Google.Identity.AccessContextManager.V1/Google.Identity.AccessContextManager.V1/Google.Identity.AccessContextManager.V1.csproj
  apis/Google.Identity.AccessContextManager.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending

#6933 Release Google.Cloud.ServiceControl.V1 version 1.2.0
  README.md
  apis/Google.Cloud.ServiceControl.V1/Google.Cloud.ServiceControl.V1/Google.Cloud.ServiceControl.V1.csproj
  apis/Google.Cloud.ServiceControl.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending

#6934 Back to running diff on label changes...
  .github/workflows/diff-pr.yml
Labels: cla: yes

#6935 Release Google.Cloud.Asset.V1 version 2.9.0
  README.md
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1.csproj
  apis/Google.Cloud.Asset.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, allow breaking changes

#6936 Really don't run diff-pr on label changes
  .github/workflows/diff-pr.yml
Labels: cla: yes

#6939 [apis/Google.Cloud.PubSub.V1] feat: Add topic retention options
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1.Snippets/PublisherServiceApiClientSnippets.g.cs
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1.Snippets/SubscriberServiceApiClientSnippets.g.cs
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1.Tests/PublisherServiceApiClientTest.g.cs
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1.Tests/SubscriberServiceApiClientTest.g.cs
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/Pubsub.g.cs
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/Schema.g.cs
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/SchemaGrpc.g.cs
  apis/Google.Cloud.PubSub.V1/synth.metadata
Labels: cla: yes, context: full

#6938 [apis/Google.Cloud.Dialogflow.V2] feat: expose `Locations` service to get/list avaliable locations of Dialogflow products; fixed some API annotations
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/Intent.g.cs
  apis/Google.Cloud.Dialogflow.V2/synth.metadata
Labels: cla: yes, context: full

#6940 Remove unnecessary diagnostic
  tools/Google.Cloud.Tools.PostProcessDevSite/Program.cs
Labels: cla: yes

#6945 [apis/Google.Cloud.ContactCenterInsights.V1] feat: add new issue model API methods feat: support Dialogflow and user-specified participant IDs docs: update pubsub_notification_settings docs
  apis/Google.Cloud.ContactCenterInsights.V1/Google.Cloud.ContactCenterInsights.V1.Snippets/ContactCenterInsightsClientSnippets.g.cs
  apis/Google.Cloud.ContactCenterInsights.V1/Google.Cloud.ContactCenterInsights.V1.Tests/ContactCenterInsightsClientTest.g.cs
  apis/Google.Cloud.ContactCenterInsights.V1/Google.Cloud.ContactCenterInsights.V1/ContactCenterInsights.g.cs
  apis/Google.Cloud.ContactCenterInsights.V1/Google.Cloud.ContactCenterInsights.V1/ContactCenterInsightsClient.g.cs
  apis/Google.Cloud.ContactCenterInsights.V1/Google.Cloud.ContactCenterInsights.V1/ContactCenterInsightsGrpc.g.cs
  apis/Google.Cloud.ContactCenterInsights.V1/Google.Cloud.ContactCenterInsights.V1/ContactCenterInsightsResourceNames.g.cs
  apis/Google.Cloud.ContactCenterInsights.V1/Google.Cloud.ContactCenterInsights.V1/Resources.g.cs
  apis/Google.Cloud.ContactCenterInsights.V1/Google.Cloud.ContactCenterInsights.V1/ResourcesResourceNames.g.cs
  apis/Google.Cloud.ContactCenterInsights.V1/gapic_metadata.json
  apis/Google.Cloud.ContactCenterInsights.V1/synth.metadata
Labels: cla: yes, context: full

#6946 [apis/Google.Cloud.Dialogflow.Cx.V3] feat: added support for DLP templates; expose `Locations` service to get/list avaliable locations of Dialogflow products
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3.Tests/SecuritySettingsServiceClientTest.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/SecuritySettings.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/SecuritySettingsResourceNames.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/synth.metadata
Labels: cla: yes, context: full

#6947 feat(Spanner): Support comments and statement hints in untyped commands.
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.Tests/SpannerCommandTextBuilderTests.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/SpannerCommandTextBuilder.cs
Labels: api: spanner, cla: yes

#6957 Release Google.Cloud.Audit version 1.0.0
  README.md
  apis/Google.Cloud.Audit/.repo-metadata.json
  apis/Google.Cloud.Audit/Google.Cloud.Audit/Google.Cloud.Audit.csproj
  apis/Google.Cloud.Audit/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending

#6958 Release Google.Cloud.GkeHub.V1 version 1.0.0
  README.md
  apis/Google.Cloud.GkeHub.V1/.repo-metadata.json
  apis/Google.Cloud.GkeHub.V1/Google.Cloud.GkeHub.V1/Google.Cloud.GkeHub.V1.csproj
  apis/Google.Cloud.GkeHub.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending

#6959 Release Google.Cloud.StorageTransfer.V1 version 1.0.0
  README.md
  apis/Google.Cloud.StorageTransfer.V1/.repo-metadata.json
  apis/Google.Cloud.StorageTransfer.V1/Google.Cloud.StorageTransfer.V1/Google.Cloud.StorageTransfer.V1.csproj
  apis/Google.Cloud.StorageTransfer.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending

#6961 [apis/Google.Cloud.Asset.V1] feat: Release of relationships in v1, Add content type Relationship to support relationship export Committer: lvv@
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1.Snippets/AssetServiceClientSnippets.g.cs
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1.Tests/AssetServiceClientTest.g.cs
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1/AssetService.g.cs
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1/Assets.g.cs
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1/AssetsResourceNames.g.cs
  apis/Google.Cloud.Asset.V1/synth.metadata
Labels: cla: yes, context: full, allow breaking changes

#6962 [apis/Google.Cloud.CloudBuild.V1] feat: Add ability to configure BuildTriggers to create Builds that require approval before executing and ApproveBuild API to approve or reject pending Builds
  apis/Google.Cloud.CloudBuild.V1/Google.Cloud.CloudBuild.V1.Snippets/CloudBuildClientSnippets.g.cs
  apis/Google.Cloud.CloudBuild.V1/Google.Cloud.CloudBuild.V1.Tests/CloudBuildClientTest.g.cs
  apis/Google.Cloud.CloudBuild.V1/Google.Cloud.CloudBuild.V1/CloudBuildClient.g.cs
  apis/Google.Cloud.CloudBuild.V1/Google.Cloud.CloudBuild.V1/Cloudbuild.g.cs
  apis/Google.Cloud.CloudBuild.V1/Google.Cloud.CloudBuild.V1/CloudbuildGrpc.g.cs
  apis/Google.Cloud.CloudBuild.V1/gapic_metadata.json
  apis/Google.Cloud.CloudBuild.V1/synth.metadata
Labels: cla: yes, context: full, allow breaking changes

#6963 [apis/Google.Cloud.Metastore.V1] feat: Added the Backup resource and Backup resource GetIamPolicy/SetIamPolicy to V1 feat: Added the RestoreService method to V1
  apis/Google.Cloud.Metastore.V1/Google.Cloud.Metastore.V1.Snippets/DataprocMetastoreClientSnippets.g.cs
  apis/Google.Cloud.Metastore.V1/Google.Cloud.Metastore.V1.Tests/DataprocMetastoreClientTest.g.cs
  apis/Google.Cloud.Metastore.V1/Google.Cloud.Metastore.V1/DataprocMetastoreClient.g.cs
  apis/Google.Cloud.Metastore.V1/Google.Cloud.Metastore.V1/Metastore.g.cs
  apis/Google.Cloud.Metastore.V1/Google.Cloud.Metastore.V1/MetastoreGrpc.g.cs
  apis/Google.Cloud.Metastore.V1/Google.Cloud.Metastore.V1/MetastoreResourceNames.g.cs
  apis/Google.Cloud.Metastore.V1/gapic_metadata.json
  apis/Google.Cloud.Metastore.V1/synth.metadata
Labels: cla: yes, context: full

#6964 [apis/Google.Cloud.Talent.V4] feat: Add new commute methods in Search APIs feat: Add new histogram type 'publish_time_in_day' feat: Support filtering by requisitionId is ListJobs API
  apis/Google.Cloud.Talent.V4/Google.Cloud.Talent.V4/Common.g.cs
  apis/Google.Cloud.Talent.V4/Google.Cloud.Talent.V4/Filters.g.cs
  apis/Google.Cloud.Talent.V4/Google.Cloud.Talent.V4/Job.g.cs
  apis/Google.Cloud.Talent.V4/Google.Cloud.Talent.V4/JobService.g.cs
  apis/Google.Cloud.Talent.V4/Google.Cloud.Talent.V4/JobServiceClient.g.cs
  apis/Google.Cloud.Talent.V4/synth.metadata
Labels: cla: yes, context: full

#6967 Fix NRE for APIs with no changes
  tools/Google.Cloud.Tools.ReleaseManager/CheckVersionCompatibilityCommand.cs
Labels: cla: yes

#6969 [apis/Google.Cloud.Functions.V1] docs: minor formatting fixes to Cloud Functions reference docs
  apis/Google.Cloud.Functions.V1/Google.Cloud.Functions.V1/Functions.g.cs
  apis/Google.Cloud.Functions.V1/Google.Cloud.Functions.V1/Operations.g.cs
  apis/Google.Cloud.Functions.V1/synth.metadata
Labels: cla: yes, context: full

#6971 Release Google.Cloud.Bigtable.V2 version 2.3.0
  README.md
  apis/Google.Cloud.Bigtable.V2/Google.Cloud.Bigtable.V2/Google.Cloud.Bigtable.V2.csproj
  apis/Google.Cloud.Bigtable.V2/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending

#6976 Release Google.Cloud.Datastore.V1 version 3.3.0
  README.md
  apis/Google.Cloud.Datastore.V1/Google.Cloud.Datastore.V1/Google.Cloud.Datastore.V1.csproj
  apis/Google.Cloud.Datastore.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#6977 Release Google.Cloud.Firestore.V1 version 2.4.0
  README.md
  apis/Google.Cloud.Firestore.V1/Google.Cloud.Firestore.V1/Google.Cloud.Firestore.V1.csproj
  apis/Google.Cloud.Firestore.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#6978 Release Google.Analytics.Admin.V1Alpha version 1.0.0-alpha08
  README.md
  apis/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha.csproj
  apis/Google.Analytics.Admin.V1Alpha/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#6981 Release Google.Area120.Tables.V1Alpha1 version 1.0.0-alpha04
  README.md
  apis/Google.Area120.Tables.V1Alpha1/Google.Area120.Tables.V1Alpha1/Google.Area120.Tables.V1Alpha1.csproj
  apis/Google.Area120.Tables.V1Alpha1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#6980 Release Google.Analytics.Data.V1Beta version 1.0.0-beta05
  README.md
  apis/Google.Analytics.Data.V1Beta/Google.Analytics.Data.V1Beta/Google.Analytics.Data.V1Beta.csproj
  apis/Google.Analytics.Data.V1Beta/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#6983 Release Google.Analytics.Data.V1Alpha version 1.0.0-alpha06
  README.md
  apis/Google.Analytics.Data.V1Alpha/Google.Analytics.Data.V1Alpha/Google.Analytics.Data.V1Alpha.csproj
  apis/Google.Analytics.Data.V1Alpha/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#6986 [apis/Google.Cloud.BigQuery.DataTransfer.V1] docs: Improvements to various message and field descriptions
  apis/Google.Cloud.BigQuery.DataTransfer.V1/Google.Cloud.BigQuery.DataTransfer.V1/DataTransferServiceClient.g.cs
  apis/Google.Cloud.BigQuery.DataTransfer.V1/Google.Cloud.BigQuery.DataTransfer.V1/Datatransfer.g.cs
  apis/Google.Cloud.BigQuery.DataTransfer.V1/Google.Cloud.BigQuery.DataTransfer.V1/DatatransferGrpc.g.cs
  apis/Google.Cloud.BigQuery.DataTransfer.V1/Google.Cloud.BigQuery.DataTransfer.V1/Transfer.g.cs
  apis/Google.Cloud.BigQuery.DataTransfer.V1/synth.metadata
Labels: cla: yes, context: full

#6989 [apis/Google.Cloud.Speech.V1P1Beta1] feat: Add transcript normalization
  apis/Google.Cloud.Speech.V1P1Beta1/Google.Cloud.Speech.V1P1Beta1/CloudSpeech.g.cs
  apis/Google.Cloud.Speech.V1P1Beta1/Google.Cloud.Speech.V1P1Beta1/Resource.g.cs
  apis/Google.Cloud.Speech.V1P1Beta1/synth.metadata
Labels: cla: yes, context: full

#6987 [apis/Google.Cloud.Bigtable.Admin.V2] feat: Publish new fields to support cluster group routing for Cloud Bigtable
  apis/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2/Instance.g.cs
  apis/Google.Cloud.Bigtable.Admin.V2/synth.metadata
Labels: cla: yes, context: full

#6988 [apis/Google.Cloud.Retail.V2] docs: Keep the API doc up-to-date
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/CatalogServiceClient.g.cs
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/CatalogServiceGrpc.g.cs
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/CompletionService.g.cs
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/CompletionServiceClient.g.cs
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/CompletionServiceGrpc.g.cs
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/ImportConfig.g.cs
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/PredictionServiceGrpc.g.cs
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/Product.g.cs
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/ProductServiceClient.g.cs
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/ProductServiceGrpc.g.cs
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/SearchService.g.cs
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/SearchServiceClient.g.cs
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/SearchServiceGrpc.g.cs
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/UserEvent.g.cs
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/UserEventServiceGrpc.g.cs
  apis/Google.Cloud.Retail.V2/synth.metadata
Labels: cla: yes, context: full

#6992 Release Google.Cloud.ApiGateway.V1 version 1.1.0
  apis/Google.Cloud.ApiGateway.V1/Google.Cloud.ApiGateway.V1/Google.Cloud.ApiGateway.V1.csproj
  apis/Google.Cloud.ApiGateway.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#6994 Release Google.Cloud.ApigeeConnect.V1 version 1.1.0
  apis/Google.Cloud.ApigeeConnect.V1/Google.Cloud.ApigeeConnect.V1/Google.Cloud.ApigeeConnect.V1.csproj
  apis/Google.Cloud.ApigeeConnect.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#6991 Release Google.Cloud.AccessApproval.V1 version 1.2.0
  apis/Google.Cloud.AccessApproval.V1/Google.Cloud.AccessApproval.V1/Google.Cloud.AccessApproval.V1.csproj
  apis/Google.Cloud.AccessApproval.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#6996 Release Google.Cloud.ArtifactRegistry.V1Beta2 version 1.0.0-beta03
  apis/Google.Cloud.ArtifactRegistry.V1Beta2/Google.Cloud.ArtifactRegistry.V1Beta2/Google.Cloud.ArtifactRegistry.V1Beta2.csproj
  apis/Google.Cloud.ArtifactRegistry.V1Beta2/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#6997 Release Google.Cloud.AssuredWorkloads.V1Beta1 version 1.0.0-beta06
  apis/Google.Cloud.AssuredWorkloads.V1Beta1/Google.Cloud.AssuredWorkloads.V1Beta1/Google.Cloud.AssuredWorkloads.V1Beta1.csproj
  apis/Google.Cloud.AssuredWorkloads.V1Beta1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#6999 Release Google.Cloud.BigQuery.Connection.V1 version 1.4.0
  apis/Google.Cloud.BigQuery.Connection.V1/Google.Cloud.BigQuery.Connection.V1/Google.Cloud.BigQuery.Connection.V1.csproj
  apis/Google.Cloud.BigQuery.Connection.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#6998 Release Google.Cloud.AutoML.V1 version 2.3.0
  apis/Google.Cloud.AutoML.V1/Google.Cloud.AutoML.V1/Google.Cloud.AutoML.V1.csproj
  apis/Google.Cloud.AutoML.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7001 Release Google.Cloud.BigQuery.Storage.V1 version 2.4.0
  apis/Google.Cloud.BigQuery.Storage.V1/Google.Cloud.BigQuery.Storage.V1/Google.Cloud.BigQuery.Storage.V1.csproj
  apis/Google.Cloud.BigQuery.Storage.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7016 Release Google.Cloud.Debugger.V2 version 2.4.0
  apis/Google.Cloud.Debugger.V2/Google.Cloud.Debugger.V2/Google.Cloud.Debugger.V2.csproj
  apis/Google.Cloud.Debugger.V2/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#6995 Release Google.Cloud.AppEngine.V1 version 1.2.0
  apis/Google.Cloud.AppEngine.V1/Google.Cloud.AppEngine.V1/Google.Cloud.AppEngine.V1.csproj
  apis/Google.Cloud.AppEngine.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7014 Release Google.Cloud.Dataproc.V1 version 3.2.0
  apis/Google.Cloud.Dataproc.V1/Google.Cloud.Dataproc.V1/Google.Cloud.Dataproc.V1.csproj
  apis/Google.Cloud.Dataproc.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7000 Release Google.Cloud.BigQuery.Reservation.V1 version 1.3.0
  apis/Google.Cloud.BigQuery.Reservation.V1/Google.Cloud.BigQuery.Reservation.V1/Google.Cloud.BigQuery.Reservation.V1.csproj
  apis/Google.Cloud.BigQuery.Reservation.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7010 Release Google.Cloud.DataFusion.V1 version 1.0.0-beta02
  apis/Google.Cloud.DataFusion.V1/Google.Cloud.DataFusion.V1/Google.Cloud.DataFusion.V1.csproj
  apis/Google.Cloud.DataFusion.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7015 Release Google.Cloud.Datastore.Admin.V1 version 1.3.0
  apis/Google.Cloud.Datastore.Admin.V1/Google.Cloud.Datastore.Admin.V1/Google.Cloud.Datastore.Admin.V1.csproj
  apis/Google.Cloud.Datastore.Admin.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#6993 Release Google.Cloud.AIPlatform.V1 version 1.0.0-beta03
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1.csproj
  apis/Google.Cloud.AIPlatform.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7007 Release Google.Cloud.Compute.V1 version 1.0.0-beta02
  apis/Google.Cloud.Compute.V1/Google.Cloud.Compute.V1/Google.Cloud.Compute.V1.csproj
  apis/Google.Cloud.Compute.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7011 Release Google.Cloud.DataLabeling.V1Beta1 version 1.0.0-beta03
  apis/Google.Cloud.DataLabeling.V1Beta1/Google.Cloud.DataLabeling.V1Beta1/Google.Cloud.DataLabeling.V1Beta1.csproj
  apis/Google.Cloud.DataLabeling.V1Beta1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7012 Release Google.Cloud.DataQnA.V1Alpha version 1.0.0-alpha03
  apis/Google.Cloud.DataQnA.V1Alpha/Google.Cloud.DataQnA.V1Alpha/Google.Cloud.DataQnA.V1Alpha.csproj
  apis/Google.Cloud.DataQnA.V1Alpha/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7004 Release Google.Cloud.Billing.V1 version 2.3.0
  apis/Google.Cloud.Billing.V1/Google.Cloud.Billing.V1/Google.Cloud.Billing.V1.csproj
  apis/Google.Cloud.Billing.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7006 Release Google.Cloud.CloudDms.V1 version 1.1.0
  apis/Google.Cloud.CloudDms.V1/Google.Cloud.CloudDms.V1/Google.Cloud.CloudDms.V1.csproj
  apis/Google.Cloud.CloudDms.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7013 Release Google.Cloud.Dataflow.V1Beta3 version 1.0.0-beta02
  apis/Google.Cloud.Dataflow.V1Beta3/Google.Cloud.Dataflow.V1Beta3/Google.Cloud.Dataflow.V1Beta3.csproj
  apis/Google.Cloud.Dataflow.V1Beta3/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7003 Release Google.Cloud.Billing.Budgets.V1Beta1 version 1.0.0-beta04
  apis/Google.Cloud.Billing.Budgets.V1Beta1/Google.Cloud.Billing.Budgets.V1Beta1/Google.Cloud.Billing.Budgets.V1Beta1.csproj
  apis/Google.Cloud.Billing.Budgets.V1Beta1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7008 Release Google.Cloud.Container.V1 version 2.6.0
  apis/Google.Cloud.Container.V1/Google.Cloud.Container.V1/Google.Cloud.Container.V1.csproj
  apis/Google.Cloud.Container.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7002 Release Google.Cloud.Billing.Budgets.V1 version 1.2.0
  apis/Google.Cloud.Billing.Budgets.V1/Google.Cloud.Billing.Budgets.V1/Google.Cloud.Billing.Budgets.V1.csproj
  apis/Google.Cloud.Billing.Budgets.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7005 Release Google.Cloud.Channel.V1 version 1.3.0
  apis/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1.csproj
  apis/Google.Cloud.Channel.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7009 Release Google.Cloud.DataCatalog.V1 version 1.4.0
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1.csproj
  apis/Google.Cloud.DataCatalog.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7018 Release Google.Cloud.Dlp.V2 version 3.3.0
  apis/Google.Cloud.Dlp.V2/Google.Cloud.Dlp.V2/Google.Cloud.Dlp.V2.csproj
  apis/Google.Cloud.Dlp.V2/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7019 Release Google.Cloud.DocumentAI.V1 version 1.2.0
  apis/Google.Cloud.DocumentAI.V1/Google.Cloud.DocumentAI.V1/Google.Cloud.DocumentAI.V1.csproj
  apis/Google.Cloud.DocumentAI.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7020 Tidy up output for batch releasing
  tools/Google.Cloud.Tools.ReleaseManager/BatchRelease/ReleaseProposal.cs
  tools/Google.Cloud.Tools.ReleaseManager/PushCommand.cs
  tools/Google.Cloud.Tools.ReleaseManager/SetVersionCommand.cs
Labels: cla: yes

#7026 [apis/Google.Cloud.DataCatalog.V1] build: change links to make them absolute
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/DataCatalogClient.g.cs
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/Datacatalog.g.cs
  apis/Google.Cloud.DataCatalog.V1/synth.metadata
Labels: cla: yes, context: full

#7027 tests(BigQuery): Stop using routine.description in tests.
  apis/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2.IntegrationTests/BigQueryFixture.cs
  apis/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2.IntegrationTests/RoutineTests.cs
Labels: api: bigquery, cla: yes

#7028 [apis/Google.Cloud.Dialogflow.Cx.V3] chore: Configure Dialogflow CX for Ruby clients
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/AdvancedSettings.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Agent.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/AudioConfig.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/EntityType.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Environment.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Experiment.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Flow.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Fulfillment.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Intent.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Page.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/ResponseMessage.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/SecuritySettings.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Session.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/SessionEntityType.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/TestCase.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/TransitionRouteGroup.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/ValidationMessage.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Version.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Webhook.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/synth.metadata
Labels: cla: yes, context: full

#6390 feat: add support for JSON data type in Spanner
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.IntegrationTests/AllTypesTableFixture.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.IntegrationTests/BindingTests.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.IntegrationTests/GetSchemaTableTests.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.IntegrationTests/WriteTests.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.Tests/SpannerDbTypeTests.ValueConversions.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.Tests/SpannerDbTypeTests.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.Tests/SpannerParameterTests.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/SpannerDbType.StringParsing.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/SpannerDbType.ValueConversion.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/SpannerDbType.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/SpannerParameter.cs
Labels: cla: yes

#7031 [apis/Google.Cloud.NetworkConnectivity.V1] fix!: Remove ActivateSpoke and DeactivateSpoke methods BREAKING_CHANGE: ActivateSpoke and DeactivateSpoke were included in a previous change by mistake feat: Add hub.routing_vpcs field docs: Specify that sit
  apis/Google.Cloud.NetworkConnectivity.V1/Google.Cloud.NetworkConnectivity.V1.Snippets/HubServiceClientSnippets.g.cs
  apis/Google.Cloud.NetworkConnectivity.V1/Google.Cloud.NetworkConnectivity.V1.Tests/HubServiceClientTest.g.cs
  apis/Google.Cloud.NetworkConnectivity.V1/Google.Cloud.NetworkConnectivity.V1/Common.g.cs
  apis/Google.Cloud.NetworkConnectivity.V1/Google.Cloud.NetworkConnectivity.V1/Hub.g.cs
  apis/Google.Cloud.NetworkConnectivity.V1/Google.Cloud.NetworkConnectivity.V1/HubGrpc.g.cs
  apis/Google.Cloud.NetworkConnectivity.V1/Google.Cloud.NetworkConnectivity.V1/HubResourceNames.g.cs
  apis/Google.Cloud.NetworkConnectivity.V1/Google.Cloud.NetworkConnectivity.V1/HubServiceClient.g.cs
  apis/Google.Cloud.NetworkConnectivity.V1/gapic_metadata.json
  apis/Google.Cloud.NetworkConnectivity.V1/synth.metadata
Labels: cla: yes, context: full, allow breaking changes

#7030 [apis/Google.Analytics.Admin.V1Alpha] feat: add `GetDataRetentionSettings`, `UpdateDataRetentionSettings` methods to the API
  apis/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha.Snippets/AnalyticsAdminServiceClientSnippets.g.cs
  apis/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha.Tests/AnalyticsAdminServiceClientTest.g.cs
  apis/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha/AnalyticsAdmin.g.cs
  apis/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha/AnalyticsAdminGrpc.g.cs
  apis/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha/AnalyticsAdminResourceNames.g.cs
  apis/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha/AnalyticsAdminServiceClient.g.cs
  apis/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha/Resources.g.cs
  apis/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha/ResourcesResourceNames.g.cs
  apis/Google.Analytics.Admin.V1Alpha/gapic_metadata.json
  apis/Google.Analytics.Admin.V1Alpha/synth.metadata
Labels: cla: yes, context: full, allow breaking changes

#7032 Release Spanner libraries version 3.12.0
  apis/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1.csproj
  apis/Google.Cloud.Spanner.Admin.Instance.V1/Google.Cloud.Spanner.Admin.Instance.V1/Google.Cloud.Spanner.Admin.Instance.V1.csproj
  apis/Google.Cloud.Spanner.Common.V1/Google.Cloud.Spanner.Common.V1/Google.Cloud.Spanner.Common.V1.csproj
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.csproj
  apis/Google.Cloud.Spanner.Data/docs/history.md
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1.csproj
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7036 [apis/Google.Cloud.GkeHub.V1Beta1] feat: Add request_id under `DeleteMembershipRequest` and `UpdateMembershipRequest`
  apis/Google.Cloud.GkeHub.V1Beta1/Google.Cloud.GkeHub.V1Beta1.Snippets/GkeHubMembershipServiceClientSnippets.g.cs
  apis/Google.Cloud.GkeHub.V1Beta1/Google.Cloud.GkeHub.V1Beta1/GkeHubMembershipServiceClient.g.cs
  apis/Google.Cloud.GkeHub.V1Beta1/Google.Cloud.GkeHub.V1Beta1/Membership.g.cs
  apis/Google.Cloud.GkeHub.V1Beta1/Google.Cloud.GkeHub.V1Beta1/MembershipGrpc.g.cs
  apis/Google.Cloud.GkeHub.V1Beta1/synth.metadata
Labels: cla: yes, context: full

#7037 [apis/Google.Cloud.Retail.V2] docs: Keep the API doc up-to-date feat: update grpc service config settings to reflect correct API deadlines chore: remove relative private links from search service comments to prevent crashing client lib generation too
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/CatalogServiceClient.g.cs
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/CompletionServiceClient.g.cs
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/PredictionServiceClient.g.cs
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/Product.g.cs
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/ProductServiceClient.g.cs
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/SearchService.g.cs
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/SearchServiceClient.g.cs
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/UserEventServiceClient.g.cs
  apis/Google.Cloud.Retail.V2/synth.metadata
Labels: cla: yes, context: full

#7044 [apis/Google.Cloud.ContactCenterInsights.V1] feat: display_name is the display name for the assigned issue
  apis/Google.Cloud.ContactCenterInsights.V1/Google.Cloud.ContactCenterInsights.V1/ContactCenterInsights.g.cs
  apis/Google.Cloud.ContactCenterInsights.V1/Google.Cloud.ContactCenterInsights.V1/ContactCenterInsightsClient.g.cs
  apis/Google.Cloud.ContactCenterInsights.V1/Google.Cloud.ContactCenterInsights.V1/Resources.g.cs
  apis/Google.Cloud.ContactCenterInsights.V1/synth.metadata
Labels: cla: yes, context: full

#7046 [apis/Google.Cloud.Gaming.V1] feat: support version reporting API
  apis/Google.Cloud.Gaming.V1/Google.Cloud.Gaming.V1.Snippets/GameServerClustersServiceClientSnippets.g.cs
  apis/Google.Cloud.Gaming.V1/Google.Cloud.Gaming.V1.Tests/GameServerClustersServiceClientTest.g.cs
  apis/Google.Cloud.Gaming.V1/Google.Cloud.Gaming.V1/Common.g.cs
  apis/Google.Cloud.Gaming.V1/Google.Cloud.Gaming.V1/GameServerClusters.g.cs
  apis/Google.Cloud.Gaming.V1/Google.Cloud.Gaming.V1/GameServerClustersServiceClient.g.cs
  apis/Google.Cloud.Gaming.V1/Google.Cloud.Gaming.V1/GameServerClustersServiceGrpc.g.cs
  apis/Google.Cloud.Gaming.V1/Google.Cloud.Gaming.V1/GameServerConfigs.g.cs
  apis/Google.Cloud.Gaming.V1/Google.Cloud.Gaming.V1/GameServerConfigsServiceClient.g.cs
  apis/Google.Cloud.Gaming.V1/Google.Cloud.Gaming.V1/GameServerConfigsServiceGrpc.g.cs
  apis/Google.Cloud.Gaming.V1/Google.Cloud.Gaming.V1/GameServerDeployments.g.cs
  apis/Google.Cloud.Gaming.V1/Google.Cloud.Gaming.V1/GameServerDeploymentsServiceClient.g.cs
  apis/Google.Cloud.Gaming.V1/Google.Cloud.Gaming.V1/GameServerDeploymentsServiceGrpc.g.cs
  apis/Google.Cloud.Gaming.V1/Google.Cloud.Gaming.V1/Realms.g.cs
  apis/Google.Cloud.Gaming.V1/Google.Cloud.Gaming.V1/RealmsServiceClient.g.cs
  apis/Google.Cloud.Gaming.V1/Google.Cloud.Gaming.V1/RealmsServiceGrpc.g.cs
  apis/Google.Cloud.Gaming.V1/synth.metadata
Labels: cla: yes, context: full

#7045 [apis/Google.Cloud.Dialogflow.Cx.V3] docs: clarified some LRO types docs: fixed some wrong update mask descriptions
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/AgentGrpc.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/AgentsClient.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/AudioConfig.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Flow.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/FlowsClient.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/TestCase.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/TestCaseGrpc.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/TestCasesClient.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/synth.metadata
Labels: cla: yes, context: full

#7047 [apis/Google.Cloud.Translate.V3] feat: added v3 proto for online/batch document translation and updated v3beta1 proto for format conversion
  apis/Google.Cloud.Translate.V3/Google.Cloud.Translate.V3.Snippets/TranslationServiceClientSnippets.g.cs
  apis/Google.Cloud.Translate.V3/Google.Cloud.Translate.V3.Tests/TranslationServiceClientTest.g.cs
  apis/Google.Cloud.Translate.V3/Google.Cloud.Translate.V3/TranslationService.g.cs
  apis/Google.Cloud.Translate.V3/Google.Cloud.Translate.V3/TranslationServiceClient.g.cs
  apis/Google.Cloud.Translate.V3/Google.Cloud.Translate.V3/TranslationServiceGrpc.g.cs
  apis/Google.Cloud.Translate.V3/Google.Cloud.Translate.V3/TranslationServiceResourceNames.g.cs
  apis/Google.Cloud.Translate.V3/gapic_metadata.json
  apis/Google.Cloud.Translate.V3/synth.metadata
Labels: cla: yes, context: full

#7048 [apis/Google.Cloud.Datastream.V1Alpha1] fix(datastream)!: Change a few resource pattern variables from camelCase to snake_case
  apis/Google.Cloud.Datastream.V1Alpha1/Google.Cloud.Datastream.V1Alpha1.Snippets/DatastreamClientSnippets.g.cs
  apis/Google.Cloud.Datastream.V1Alpha1/Google.Cloud.Datastream.V1Alpha1.Tests/DatastreamClientTest.g.cs
  apis/Google.Cloud.Datastream.V1Alpha1/Google.Cloud.Datastream.V1Alpha1/DatastreamResources.g.cs
  apis/Google.Cloud.Datastream.V1Alpha1/Google.Cloud.Datastream.V1Alpha1/DatastreamResourcesResourceNames.g.cs
  apis/Google.Cloud.Datastream.V1Alpha1/synth.metadata
Labels: cla: yes, context: full

#7049 [apis/Google.Cloud.Kms.V1] feat: add support for Key Reimport
  apis/Google.Cloud.Kms.V1/Google.Cloud.Kms.V1.Snippets/KeyManagementServiceClientSnippets.g.cs
  apis/Google.Cloud.Kms.V1/Google.Cloud.Kms.V1.Tests/KeyManagementServiceClientTest.g.cs
  apis/Google.Cloud.Kms.V1/Google.Cloud.Kms.V1/KeyManagementServiceClient.g.cs
  apis/Google.Cloud.Kms.V1/Google.Cloud.Kms.V1/Resources.g.cs
  apis/Google.Cloud.Kms.V1/Google.Cloud.Kms.V1/Service.g.cs
  apis/Google.Cloud.Kms.V1/Google.Cloud.Kms.V1/ServiceGrpc.g.cs
  apis/Google.Cloud.Kms.V1/Google.Cloud.Kms.V1/ServiceResourceNames.g.cs
  apis/Google.Cloud.Kms.V1/synth.metadata
Labels: cla: yes, context: full

#7050 [apis/Google.Cloud.OsConfig.V1] feat: Update osconfig v1 and v1alpha with WindowsApplication
  apis/Google.Cloud.OsConfig.V1/Google.Cloud.OsConfig.V1/Inventory.g.cs
  apis/Google.Cloud.OsConfig.V1/synth.metadata
Labels: cla: yes, context: full

#7054 chore: Add Google.LongRunning dependency to Google.Cloud.Monitoring.V3
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3.csproj
  apis/apis.json
Labels: cla: yes

#7080 Release Google.Cloud.PhishingProtection.V1Beta1 version 1.0.0-beta05
  apis/Google.Cloud.PhishingProtection.V1Beta1/Google.Cloud.PhishingProtection.V1Beta1/Google.Cloud.PhishingProtection.V1Beta1.csproj
  apis/Google.Cloud.PhishingProtection.V1Beta1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7076 Release Google.Cloud.Metastore.V1Beta version 1.0.0-beta02
  apis/Google.Cloud.Metastore.V1Beta/Google.Cloud.Metastore.V1Beta/Google.Cloud.Metastore.V1Beta.csproj
  apis/Google.Cloud.Metastore.V1Beta/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7078 Release Google.Cloud.Notebooks.V1Beta1 version 1.0.0-beta04
  apis/Google.Cloud.Notebooks.V1Beta1/Google.Cloud.Notebooks.V1Beta1/Google.Cloud.Notebooks.V1Beta1.csproj
  apis/Google.Cloud.Notebooks.V1Beta1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7072 Release Google.Cloud.MediaTranslation.V1Beta1 version 1.0.0-beta03
  apis/Google.Cloud.MediaTranslation.V1Beta1/Google.Cloud.MediaTranslation.V1Beta1/Google.Cloud.MediaTranslation.V1Beta1.csproj
  apis/Google.Cloud.MediaTranslation.V1Beta1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7075 Release Google.Cloud.Metastore.V1Alpha version 1.0.0-alpha03
  apis/Google.Cloud.Metastore.V1Alpha/Google.Cloud.Metastore.V1Alpha/Google.Cloud.Metastore.V1Alpha.csproj
  apis/Google.Cloud.Metastore.V1Alpha/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7062 Release Google.Cloud.GkeConnect.Gateway.V1Beta1 version 1.0.0-beta02
  apis/Google.Cloud.GkeConnect.Gateway.V1Beta1/Google.Cloud.GkeConnect.Gateway.V1Beta1/Google.Cloud.GkeConnect.Gateway.V1Beta1.csproj
  apis/Google.Cloud.GkeConnect.Gateway.V1Beta1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7069 Release Google.Cloud.Language.V1 version 2.3.0
  apis/Google.Cloud.Language.V1/Google.Cloud.Language.V1/Google.Cloud.Language.V1.csproj
  apis/Google.Cloud.Language.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7074 Release Google.Cloud.Memcache.V1Beta2 version 1.0.0-beta05
  apis/Google.Cloud.Memcache.V1Beta2/Google.Cloud.Memcache.V1Beta2/Google.Cloud.Memcache.V1Beta2.csproj
  apis/Google.Cloud.Memcache.V1Beta2/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7077 Release Google.Cloud.NetworkManagement.V1 version 1.1.0
  apis/Google.Cloud.NetworkManagement.V1/Google.Cloud.NetworkManagement.V1/Google.Cloud.NetworkManagement.V1.csproj
  apis/Google.Cloud.NetworkManagement.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7056 Release Google.Cloud.DocumentAI.V1Beta3 version 1.0.0-beta02
  apis/Google.Cloud.DocumentAI.V1Beta3/Google.Cloud.DocumentAI.V1Beta3/Google.Cloud.DocumentAI.V1Beta3.csproj
  apis/Google.Cloud.DocumentAI.V1Beta3/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7058 Release Google.Cloud.ErrorReporting.V1Beta1 version 2.0.0-beta05
  apis/Google.Cloud.ErrorReporting.V1Beta1/Google.Cloud.ErrorReporting.V1Beta1/Google.Cloud.ErrorReporting.V1Beta1.csproj
  apis/Google.Cloud.ErrorReporting.V1Beta1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7066 Release Google.Cloud.Iam.Credentials.V1 version 1.2.0
  apis/Google.Cloud.Iam.Credentials.V1/Google.Cloud.Iam.Credentials.V1/Google.Cloud.Iam.Credentials.V1.csproj
  apis/Google.Cloud.Iam.Credentials.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7071 Release Google.Cloud.ManagedIdentities.V1 version 2.3.0
  apis/Google.Cloud.ManagedIdentities.V1/Google.Cloud.ManagedIdentities.V1/Google.Cloud.ManagedIdentities.V1.csproj
  apis/Google.Cloud.ManagedIdentities.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7079 Release Google.Cloud.OrgPolicy.V2 version 1.1.0
  apis/Google.Cloud.OrgPolicy.V2/Google.Cloud.OrgPolicy.V2/Google.Cloud.OrgPolicy.V2.csproj
  apis/Google.Cloud.OrgPolicy.V2/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7057 Release Google.Cloud.Domains.V1Beta1 version 1.0.0-beta03
  apis/Google.Cloud.Domains.V1Beta1/Google.Cloud.Domains.V1Beta1/Google.Cloud.Domains.V1Beta1.csproj
  apis/Google.Cloud.Domains.V1Beta1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7060 Release Google.Cloud.Eventarc.V1 version 1.1.0
  apis/Google.Cloud.Eventarc.V1/Google.Cloud.Eventarc.V1/Google.Cloud.Eventarc.V1.csproj
  apis/Google.Cloud.Eventarc.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7070 Release Google.Cloud.LifeSciences.V2Beta version 1.0.0-beta02
  apis/Google.Cloud.LifeSciences.V2Beta/Google.Cloud.LifeSciences.V2Beta/Google.Cloud.LifeSciences.V2Beta.csproj
  apis/Google.Cloud.LifeSciences.V2Beta/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7073 Release Google.Cloud.Memcache.V1 version 1.2.0
  apis/Google.Cloud.Memcache.V1/Google.Cloud.Memcache.V1/Google.Cloud.Memcache.V1.csproj
  apis/Google.Cloud.Memcache.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7061 Release Google.Cloud.Firestore.Admin.V1 version 2.3.0
  apis/Google.Cloud.Firestore.Admin.V1/Google.Cloud.Firestore.Admin.V1/Google.Cloud.Firestore.Admin.V1.csproj
  apis/Google.Cloud.Firestore.Admin.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7065 Release Google.Cloud.Iam.Admin.V1 version 1.1.0
  apis/Google.Cloud.Iam.Admin.V1/Google.Cloud.Iam.Admin.V1/Google.Cloud.Iam.Admin.V1.csproj
  apis/Google.Cloud.Iam.Admin.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7068 Release Google.Cloud.Iot.V1 version 1.2.0
  apis/Google.Cloud.Iot.V1/Google.Cloud.Iot.V1/Google.Cloud.Iot.V1.csproj
  apis/Google.Cloud.Iot.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7059 Release Google.Cloud.EssentialContacts.V1 version 1.1.0
  apis/Google.Cloud.EssentialContacts.V1/Google.Cloud.EssentialContacts.V1/Google.Cloud.EssentialContacts.V1.csproj
  apis/Google.Cloud.EssentialContacts.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7064 Release Google.Cloud.GkeHub.V1 version 1.1.0
  apis/Google.Cloud.GkeHub.V1/Google.Cloud.GkeHub.V1/Google.Cloud.GkeHub.V1.csproj
  apis/Google.Cloud.GkeHub.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7067 Release Google.Cloud.Iap.V1 version 1.1.0
  apis/Google.Cloud.Iap.V1/Google.Cloud.Iap.V1/Google.Cloud.Iap.V1.csproj
  apis/Google.Cloud.Iap.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7063 Release Google.Cloud.Gaming.V1Beta version 1.0.0-beta08
  apis/Google.Cloud.Gaming.V1Beta/Google.Cloud.Gaming.V1Beta/Google.Cloud.Gaming.V1Beta.csproj
  apis/Google.Cloud.Gaming.V1Beta/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7081 Release Google.Cloud.Translate.V3 version 2.3.0
  apis/Google.Cloud.Translate.V3/Google.Cloud.Translate.V3/Google.Cloud.Translate.V3.csproj
  apis/Google.Cloud.Translate.V3/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7083 Add a period
  tools/Google.Cloud.Tools.GenerateDocfxSources/Program.cs
Labels: cla: yes
