Repository googleapis/google-cloud-dotnet, pull requests merged in 2021-03, with the labels that each got.

#5989 Re-generated apis/ServiceDirectory with ApiGateway naming change and Document AI
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5988 chore: update Spanner v3.5.0 release notes
  apis/Google.Cloud.Spanner.Data/docs/history.md
Labels: api: spanner, cla: yes

#5992 Fix diff PR check
  tools/Google.Cloud.Tools.ReleaseManager/Google.Cloud.Tools.ReleaseManager.csproj
Labels: cla: yes

#5990 Release Google.Cloud.CloudBuild.V1 version 1.0.0
  README.md
  apis/Google.Cloud.CloudBuild.V1/.repo-metadata.json
  apis/Google.Cloud.CloudBuild.V1/Google.Cloud.CloudBuild.V1/Google.Cloud.CloudBuild.V1.csproj
  apis/Google.Cloud.CloudBuild.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5976 [apis/Google.Cloud.SecretManager.V1] feat: added topic field to Secret
  apis/Google.Cloud.SecretManager.V1/Google.Cloud.SecretManager.V1.Tests/SecretManagerServiceClientTest.g.cs
  apis/Google.Cloud.SecretManager.V1/Google.Cloud.SecretManager.V1/Resources.cs
  apis/Google.Cloud.SecretManager.V1/Google.Cloud.SecretManager.V1/ResourcesResourceNames.g.cs
  apis/Google.Cloud.SecretManager.V1/Google.Cloud.SecretManager.V1/ServiceGrpc.cs
  apis/Google.Cloud.SecretManager.V1/synth.metadata
Labels: cla: yes, context: full

#5994 Release Google.Cloud.Memcache.V1 version 1.0.0
  README.md
  apis/Google.Cloud.Memcache.V1/.repo-metadata.json
  apis/Google.Cloud.Memcache.V1/Google.Cloud.Memcache.V1/Google.Cloud.Memcache.V1.csproj
  apis/Google.Cloud.Memcache.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5995 Release Google.Cloud.Profiler.V2 version 1.0.0
  README.md
  apis/Google.Cloud.Profiler.V2/.repo-metadata.json
  apis/Google.Cloud.Profiler.V2/Google.Cloud.Profiler.V2/Google.Cloud.Profiler.V2.csproj
  apis/Google.Cloud.Profiler.V2/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5996 [apis/Google.Cloud.Dialogflow.Cx.V3] feat: allow to disable webhook invocation per request
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/ResponseMessage.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Session.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/synth.metadata
Labels: cla: yes, context: full

#5997 [apis/Google.Cloud.Functions.V1] fix: Fix service namespace in grpc_service_config.
  apis/Google.Cloud.Functions.V1/Google.Cloud.Functions.V1/CloudFunctionsServiceClient.g.cs
  apis/Google.Cloud.Functions.V1/synth.metadata
Labels: cla: yes, context: full

#5998 Release Google.Cloud.Channel.V1 version 1.0.0
  README.md
  apis/Google.Cloud.Channel.V1/.repo-metadata.json
  apis/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1.csproj
  apis/Google.Cloud.Channel.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6001 [apis/Google.Cloud.PubSub.V1] docs: Remove experimental note for schema APIs
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/Pubsub.cs
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/SchemaGrpc.cs
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/SchemaServiceClient.g.cs
  apis/Google.Cloud.PubSub.V1/synth.metadata
Labels: cla: yes, context: full

#6002 [apis/Google.Cloud.Spanner.V1] feat(spanner): add `optimizer_statistics_package` field in `QueryOptions`
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/Spanner.cs
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/SpannerGrpc.cs
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/Transaction.cs
  apis/Google.Cloud.Spanner.V1/synth.metadata
Labels: api: spanner, cla: yes, context: full

#5999 Include history-less dependencies within parent version history
  tools/Google.Cloud.Tools.Common/ApiCatalog.cs
  tools/Google.Cloud.Tools.Common/ApiMetadata.cs
  tools/Google.Cloud.Tools.ReleaseManager/GitHelpers.cs
  tools/Google.Cloud.Tools.ReleaseManager/ShowStaleCommand.cs
  tools/Google.Cloud.Tools.ReleaseManager/UpdateHistoryCommand.cs
Labels: cla: yes

#6003 Use the right xref URL for Google.Protobuf
  tools/Google.Cloud.Tools.PostProcessDevSite/Program.cs
Labels: cla: yes

#6007 [apis/Google.Cloud.Metastore.V1Alpha] feat: Publish Dataproc Metastore v1alpha API
  apis/Google.Cloud.Metastore.V1Alpha/Google.Cloud.Metastore.V1Alpha.Snippets/DataprocMetastoreClientSnippets.g.cs
  apis/Google.Cloud.Metastore.V1Alpha/Google.Cloud.Metastore.V1Alpha.Tests/DataprocMetastoreClientTest.g.cs
  apis/Google.Cloud.Metastore.V1Alpha/Google.Cloud.Metastore.V1Alpha/DataprocMetastoreClient.g.cs
  apis/Google.Cloud.Metastore.V1Alpha/Google.Cloud.Metastore.V1Alpha/Metastore.cs
  apis/Google.Cloud.Metastore.V1Alpha/Google.Cloud.Metastore.V1Alpha/MetastoreGrpc.cs
  apis/Google.Cloud.Metastore.V1Alpha/Google.Cloud.Metastore.V1Alpha/MetastoreResourceNames.g.cs
  apis/Google.Cloud.Metastore.V1Alpha/synth.metadata
Labels: cla: yes, context: full

#6008 [apis/ServiceDirectory] feat: Publish Dataproc Metastore v1alpha API
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#6009 [apis/Google.Analytics.Data.V1Beta] fix!: rename the 'page_size', 'page_token', 'total_size' fields to 'limit', 'offset' and 'row_count' respectively
  apis/Google.Analytics.Data.V1Beta/Google.Analytics.Data.V1Beta.Snippets/BetaAnalyticsDataClientSnippets.g.cs
  apis/Google.Analytics.Data.V1Beta/Google.Analytics.Data.V1Beta.Tests/BetaAnalyticsDataClientTest.g.cs
  apis/Google.Analytics.Data.V1Beta/Google.Analytics.Data.V1Beta/AnalyticsDataApi.cs
  apis/Google.Analytics.Data.V1Beta/Google.Analytics.Data.V1Beta/BetaAnalyticsDataClient.g.cs
  apis/Google.Analytics.Data.V1Beta/synth.metadata
Labels: cla: yes, context: full

#6010 [apis/ServiceDirectory] feat: Added client libraries for Drive Activity v2 API
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#6011 [apis/Google.Cloud.Bigtable.Admin.V2] fix(retry): restore grpc_service_config for CreateBackup and {Restore,Snapshot}Table
  apis/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2/BigtableTableAdminClient.g.cs
  apis/Google.Cloud.Bigtable.Admin.V2/synth.metadata
Labels: cla: yes, context: full

#6012 Fix "root" docs build
  docs/builddocs.sh
Labels: cla: yes

#6017 [apis/ServiceDirectory] feat: Publish Dataproc Metastore v1beta API
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#6016 [apis/Google.Cloud.Metastore.V1Alpha] feat: added support for release channels when creating service
  apis/Google.Cloud.Metastore.V1Alpha/Google.Cloud.Metastore.V1Alpha.Tests/DataprocMetastoreClientTest.g.cs
  apis/Google.Cloud.Metastore.V1Alpha/Google.Cloud.Metastore.V1Alpha/Metastore.cs
  apis/Google.Cloud.Metastore.V1Alpha/synth.metadata
Labels: cla: yes, context: full

#6015 fix: retry consecutive retryable errors in sql stream without timeout
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.Tests/V1/SqlResultStreamTests.cs
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/SqlResultStream.cs
Labels: cla: yes

#6020 Release Google.Cloud.Metastore.V1Alpha version 1.0.0-alpha02
  README.md
  apis/Google.Cloud.Metastore.V1Alpha/Google.Cloud.Metastore.V1Alpha/Google.Cloud.Metastore.V1Alpha.csproj
  apis/Google.Cloud.Metastore.V1Alpha/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6021 Release Google.Cloud.OrgPolicy.V2 version 1.0.0
  README.md
  apis/Google.Cloud.OrgPolicy.V2/.repo-metadata.json
  apis/Google.Cloud.OrgPolicy.V2/Google.Cloud.OrgPolicy.V2/Google.Cloud.OrgPolicy.V2.csproj
  apis/Google.Cloud.OrgPolicy.V2/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6022 [apis/Google.Cloud.Dialogflow.Cx.V3] feat: added fallback option when restoring an agent docs: clarified experiment length
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3.Snippets/AgentsClientSnippets.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Agent.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Environment.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Experiment.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/synth.metadata
Labels: cla: yes, context: full

#6023 [apis/Google.Cloud.Speech.V1P1Beta1] feat: Support output transcript to GCS for LongRunningRecognize.
  apis/Google.Cloud.Speech.V1P1Beta1/Google.Cloud.Speech.V1P1Beta1.Snippets/AdaptationClientSnippets.g.cs
  apis/Google.Cloud.Speech.V1P1Beta1/Google.Cloud.Speech.V1P1Beta1.Snippets/SpeechClientSnippets.g.cs
  apis/Google.Cloud.Speech.V1P1Beta1/Google.Cloud.Speech.V1P1Beta1.Tests/AdaptationClientTest.g.cs
  apis/Google.Cloud.Speech.V1P1Beta1/Google.Cloud.Speech.V1P1Beta1/AdaptationClient.g.cs
  apis/Google.Cloud.Speech.V1P1Beta1/Google.Cloud.Speech.V1P1Beta1/CloudSpeech.cs
  apis/Google.Cloud.Speech.V1P1Beta1/Google.Cloud.Speech.V1P1Beta1/CloudSpeechAdaptation.cs
  apis/Google.Cloud.Speech.V1P1Beta1/synth.metadata
Labels: cla: yes, context: full

#6025 test(Storage): Changes resources accessed by unauthenticated access tests.
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.IntegrationTests/UnauthenticatedAccessTest.cs
Labels: api: storage, cla: yes

#6027 [apis/Google.Cloud.AppEngine.V1] feat: added vm_liveness, search_api_available, network_settings, service_account, build_env_variables, kms_key_reference to v1 API
  apis/Google.Cloud.AppEngine.V1/Google.Cloud.AppEngine.V1.Tests/InstancesClientTest.g.cs
  apis/Google.Cloud.AppEngine.V1/Google.Cloud.AppEngine.V1.Tests/ServicesClientTest.g.cs
  apis/Google.Cloud.AppEngine.V1/Google.Cloud.AppEngine.V1.Tests/VersionsClientTest.g.cs
  apis/Google.Cloud.AppEngine.V1/Google.Cloud.AppEngine.V1/AppengineGrpc.cs
  apis/Google.Cloud.AppEngine.V1/Google.Cloud.AppEngine.V1/ApplicationsClient.g.cs
  apis/Google.Cloud.AppEngine.V1/Google.Cloud.AppEngine.V1/AuthorizedCertificatesClient.g.cs
  apis/Google.Cloud.AppEngine.V1/Google.Cloud.AppEngine.V1/AuthorizedDomainsClient.g.cs
  apis/Google.Cloud.AppEngine.V1/Google.Cloud.AppEngine.V1/DomainMappingsClient.g.cs
  apis/Google.Cloud.AppEngine.V1/Google.Cloud.AppEngine.V1/FirewallClient.g.cs
  apis/Google.Cloud.AppEngine.V1/Google.Cloud.AppEngine.V1/Instance.cs
  apis/Google.Cloud.AppEngine.V1/Google.Cloud.AppEngine.V1/InstanceResourceNames.g.cs
  apis/Google.Cloud.AppEngine.V1/Google.Cloud.AppEngine.V1/InstancesClient.g.cs
  apis/Google.Cloud.AppEngine.V1/Google.Cloud.AppEngine.V1/Location.cs
  apis/Google.Cloud.AppEngine.V1/Google.Cloud.AppEngine.V1/NetworkSettings.cs
  apis/Google.Cloud.AppEngine.V1/Google.Cloud.AppEngine.V1/Operation.cs
  apis/Google.Cloud.AppEngine.V1/Google.Cloud.AppEngine.V1/Service.cs
  apis/Google.Cloud.AppEngine.V1/Google.Cloud.AppEngine.V1/ServicesClient.g.cs
  apis/Google.Cloud.AppEngine.V1/Google.Cloud.AppEngine.V1/Version.cs
  apis/Google.Cloud.AppEngine.V1/Google.Cloud.AppEngine.V1/VersionsClient.g.cs
  apis/Google.Cloud.AppEngine.V1/synth.metadata
Labels: cla: yes, context: full

#6029 [apis/Google.Cloud.PubSub.V1] docs: Improve PubSub coding guidance
  apis/Google.Cloud.PubSub.V1/docs/index.md
Labels: cla: yes

#6032 [apis/Google.Cloud.Speech.V1P1Beta1] feat: Support output transcript to GCS for LongRunningRecognize.
  apis/Google.Cloud.Speech.V1P1Beta1/Google.Cloud.Speech.V1P1Beta1/CloudSpeech.cs
  apis/Google.Cloud.Speech.V1P1Beta1/synth.metadata
Labels: cla: yes, context: full

#6031 [apis/Google.Cloud.ManagedIdentities.V1] chore: Remove titles in docstring.
  apis/Google.Cloud.ManagedIdentities.V1/Google.Cloud.ManagedIdentities.V1/ManagedIdentitiesServiceClient.g.cs
  apis/Google.Cloud.ManagedIdentities.V1/Google.Cloud.ManagedIdentities.V1/ManagedIdentitiesServiceGrpc.cs
  apis/Google.Cloud.ManagedIdentities.V1/synth.metadata
Labels: cla: yes, context: full

#6030 [apis/Google.Cloud.Kms.V1] feat: Add maxAttempts to retry policy for KMS gRPC service config feat: Add Bazel exports_files entry for KMS gRPC service config
  apis/Google.Cloud.Kms.V1/Google.Cloud.Kms.V1/KeyManagementServiceClient.g.cs
  apis/Google.Cloud.Kms.V1/synth.metadata
Labels: cla: yes, context: full

#6033 [CHANGE ME] Re-generated apis/ServiceDirectory to pick up changes in the API or client library generator.
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#6024 GoogleStackdriverTarget - Added support for TraceId and SpanId for LogEntry
  apis/Google.Cloud.Logging.NLog/Google.Cloud.Logging.NLog.Tests/GoogleStackdriverTargetTest.cs
  apis/Google.Cloud.Logging.NLog/Google.Cloud.Logging.NLog/GoogleStackdriverTarget.cs
  apis/Google.Cloud.Logging.NLog/Google.Cloud.Logging.NLog/GoogleStackdriverTarget_Configuration.cs
Labels: cla: yes

#6013 fix: retry errors in stream until timeout
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.Tests/V1/SqlResultStream.RetryStateTests.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.Tests/V1/SqlResultStreamTests.cs
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/SqlResultStream.cs
Labels: cla: yes

#6144 [apis/Google.Cloud.CloudBuild.V1] fix: Specify `build` as the body of a `CreateBuild` call. The Cloud Build API has always assumed this, but now we are actually specifying it.
  apis/Google.Cloud.CloudBuild.V1/Google.Cloud.CloudBuild.V1.Snippets/CloudBuildClientSnippets.g.cs
  apis/Google.Cloud.CloudBuild.V1/Google.Cloud.CloudBuild.V1.Tests/CloudBuildClientTest.g.cs
  apis/Google.Cloud.CloudBuild.V1/Google.Cloud.CloudBuild.V1/CloudBuildClient.g.cs
  apis/Google.Cloud.CloudBuild.V1/Google.Cloud.CloudBuild.V1/Cloudbuild.cs
  apis/Google.Cloud.CloudBuild.V1/Google.Cloud.CloudBuild.V1/CloudbuildGrpc.cs
  apis/Google.Cloud.CloudBuild.V1/Google.Cloud.CloudBuild.V1/CloudbuildResourceNames.g.cs
  apis/Google.Cloud.CloudBuild.V1/synth.metadata
Labels: cla: yes, context: full

#6145 [apis/ServiceDirectory] feat: VPC Access GAPIC client library generation
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#6147 Release all Spanner packages as version 3.6.0
  README.md
  apis/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1.csproj
  apis/Google.Cloud.Spanner.Admin.Instance.V1/Google.Cloud.Spanner.Admin.Instance.V1/Google.Cloud.Spanner.Admin.Instance.V1.csproj
  apis/Google.Cloud.Spanner.Common.V1/Google.Cloud.Spanner.Common.V1/Google.Cloud.Spanner.Common.V1.csproj
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.csproj
  apis/Google.Cloud.Spanner.Data/docs/history.md
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1.csproj
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6148 [apis/ServiceDirectory] feat: published Database Migration Service v1 SDK
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#6149 Provide a cleaner method for configuring API-specific resources
  CommonResourcesConfig.json
  apis/Google.Cloud.Bigtable.Common.V2/CommonResourcesConfig.json
  apis/Google.Cloud.Spanner.Common.V1/CommonResourcesConfig.json
  apis/Google.Cloud.Workflows.Common.V1/CommonResourcesConfig.json
  apis/Google.Cloud.Workflows.Common.V1Beta/CommonResourcesConfig.json
  apis/Google.Cloud.Workflows.Executions.V1/CommonResourcesConfig.json
  apis/Google.Cloud.Workflows.Executions.V1Beta/CommonResourcesConfig.json
  apis/Google.Cloud.Workflows.V1/CommonResourcesConfig.json
  apis/Google.Cloud.Workflows.V1Beta/CommonResourcesConfig.json
  apis/README.md
  apis/apis.json
  generateapis.sh
  tools/Google.Cloud.Tools.Common/ApiMetadata.cs
Labels: cla: yes

#6153 fix: X-Cloud-Trace-Context trace mask values should be 0-1.
  apis/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common/Trace/TraceHeaderContext.cs
Labels: cla: yes

#6142 [apis/Google.Cloud.GkeHub.V1Beta1] chore: Use correct markdown for code block
  apis/Google.Cloud.GkeHub.V1Beta1/Google.Cloud.GkeHub.V1Beta1/Membership.cs
  apis/Google.Cloud.GkeHub.V1Beta1/synth.metadata
Labels: cla: yes, context: full

#6173 chore: Regenerate all APIs with latest generator
  apis/Google.Cloud.AutoML.V1/Google.Cloud.AutoML.V1.Snippets/AutoMlClientSnippets.g.cs
  apis/Google.Cloud.BigQuery.DataTransfer.V1/Google.Cloud.BigQuery.DataTransfer.V1.Snippets/DataTransferServiceClientSnippets.g.cs
  apis/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2.Snippets/BigtableTableAdminClientSnippets.g.cs
  apis/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1.Snippets/CloudChannelServiceClientSnippets.g.cs
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1.Snippets/DataCatalogClientSnippets.g.cs
  apis/Google.Cloud.DataLabeling.V1Beta1/Google.Cloud.DataLabeling.V1Beta1.Snippets/DataLabelingServiceClientSnippets.g.cs
  apis/Google.Cloud.Datastore.V1/Google.Cloud.Datastore.V1.Snippets/DatastoreClientSnippets.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3.Snippets/AgentsClientSnippets.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3.Snippets/TestCasesClientSnippets.g.cs
  apis/Google.Cloud.Dlp.V2/Google.Cloud.Dlp.V2.Snippets/DlpServiceClientSnippets.g.cs
  apis/Google.Cloud.DocumentAI.V1/Google.Cloud.DocumentAI.V1.Snippets/DocumentProcessorServiceClientSnippets.g.cs
  apis/Google.Cloud.Firestore.V1/Google.Cloud.Firestore.V1.Snippets/FirestoreClientSnippets.g.cs
  apis/Google.Cloud.MediaTranslation.V1Beta1/Google.Cloud.MediaTranslation.V1Beta1.Snippets/SpeechTranslationServiceClientSnippets.g.cs
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3.Snippets/GroupServiceClientSnippets.g.cs
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1.Snippets/SchemaServiceClientSnippets.g.cs
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1.Snippets/SubscriberServiceApiClientSnippets.g.cs
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1.Snippets/SpannerClientSnippets.g.cs
  apis/Google.Cloud.Speech.V1/Google.Cloud.Speech.V1.Snippets/SpeechClientSnippets.g.cs
  apis/Google.Cloud.Speech.V1P1Beta1/Google.Cloud.Speech.V1P1Beta1.Snippets/SpeechClientSnippets.g.cs
  apis/Google.Cloud.Vision.V1/Google.Cloud.Vision.V1.Snippets/ProductSearchClientSnippets.g.cs
Labels: cla: yes

#6259 feat: Add CCAI API
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2.Snippets/AgentsClientSnippets.g.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2.Snippets/AnswerRecordsClientSnippets.g.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2.Snippets/ConversationProfilesClientSnippets.g.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2.Snippets/ConversationsClientSnippets.g.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2.Snippets/DocumentsClientSnippets.g.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2.Snippets/EntityTypesClientSnippets.g.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2.Snippets/IntentsClientSnippets.g.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2.Snippets/KnowledgeBasesClientSnippets.g.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2.Snippets/ParticipantsClientSnippets.g.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2.Tests/AnswerRecordsClientTest.g.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2.Tests/ConversationProfilesClientTest.g.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2.Tests/ConversationsClientTest.g.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2.Tests/DocumentsClientTest.g.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2.Tests/IntentsClientTest.g.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2.Tests/KnowledgeBasesClientTest.g.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2.Tests/ParticipantsClientTest.g.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/AnswerRecord.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/AnswerRecordGrpc.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/AnswerRecordResourceNames.g.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/AnswerRecordsClient.g.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/AudioConfig.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/Conversation.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/ConversationEvent.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/ConversationGrpc.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/ConversationProfile.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/ConversationProfileGrpc.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/ConversationProfileResourceNames.g.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/ConversationProfilesClient.g.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/ConversationResourceNames.g.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/ConversationsClient.g.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/Document.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/DocumentGrpc.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/DocumentResourceNames.g.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/DocumentsClient.g.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/Gcs.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/HumanAgentAssistantEvent.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/Intent.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/KnowledgeBase.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/KnowledgeBaseGrpc.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/KnowledgeBaseResourceNames.g.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/KnowledgeBasesClient.g.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/Participant.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/ParticipantGrpc.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/ParticipantResourceNames.g.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/ParticipantsClient.g.cs
  apis/Google.Cloud.Dialogflow.V2/synth.metadata
Labels: cla: yes

#6260 [apis/ServiceDirectory] fix!: remove v1alpha1 client BREAKING CHANGE: Budget API alpha is no longer supported
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#6143 GoogleStackdriverTarget - Extracted RenderJsonPayload from BuildLogEntry
  apis/Google.Cloud.Logging.NLog/Google.Cloud.Logging.NLog/GoogleStackdriverTarget.cs
Labels: cla: yes

#6262 Release Google.Cloud.Logging.NLog version 3.3.0
  README.md
  apis/Google.Cloud.Logging.NLog/Google.Cloud.Logging.NLog/Google.Cloud.Logging.NLog.csproj
  apis/Google.Cloud.Logging.NLog/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6263 [apis/Google.Cloud.Dialogflow.V2] docs: fix link for version and environment in participant doc. fix: Add all missing regional HTTP bindings in DF API.
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/Agent.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/Context.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/Document.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/EntityType.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/Environment.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/Intent.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/KnowledgeBase.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/ParticipantGrpc.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/ParticipantsClient.g.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/Session.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/SessionEntityType.cs
  apis/Google.Cloud.Dialogflow.V2/synth.metadata
Labels: cla: yes, context: full

#6264 [apis/Google.Cloud.Monitoring.V3] feat: Added support for Monitoring Query Language: https://cloud.google.com/monitoring/mql feat: Added support for units in the MetricService feat: Added total_size to the response of ListAlertPolicies. fix: Un-depre
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3.Snippets/MetricServiceClientSnippets.g.cs
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3.Snippets/QueryServiceClientSnippets.g.cs
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3.Tests/NotificationChannelServiceClientTest.g.cs
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3.Tests/QueryServiceClientTest.g.cs
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3.Tests/ServiceMonitoringServiceClientTest.g.cs
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3/Alert.cs
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3/AlertPolicyServiceClient.g.cs
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3/AlertService.cs
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3/AlertServiceGrpc.cs
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3/Common.cs
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3/DroppedLabels.cs
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3/GroupServiceGrpc.cs
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3/Metric.cs
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3/MetricService.cs
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3/MetricServiceClient.g.cs
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3/MetricServiceGrpc.cs
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3/MetricServiceResourceNames.g.cs
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3/Notification.cs
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3/NotificationService.cs
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3/NotificationServiceGrpc.cs
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3/QueryService.cs
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3/QueryServiceClient.g.cs
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3/QueryServiceGrpc.cs
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3/Service.cs
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3/ServiceService.cs
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3/ServiceServiceGrpc.cs
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3/Uptime.cs
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3/UptimeServiceGrpc.cs
  apis/Google.Cloud.Monitoring.V3/synth.metadata
Labels: cla: yes, context: full

#6265 [apis/Google.Cloud.Spanner.V1] feat: add RPC Priority request options
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1.Snippets/SpannerClientSnippets.g.cs
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1.Tests/SpannerClientTest.g.cs
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/Spanner.cs
  apis/Google.Cloud.Spanner.V1/synth.metadata
Labels: cla: yes, context: full

#6266 [apis/ServiceDirectory] feat: Added support for Monitoring Query Language: https://cloud.google.com/monitoring/mql feat: Added support for units in the MetricService feat: Added total_size to the response of ListAlertPolicies. fix: Un-deprecated clus
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#6267 [apis/Google.Cloud.Dialogflow.V2] feat: expose MP3_64_KBPS and MULAW for output audio encodings.
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/AudioConfig.cs
  apis/Google.Cloud.Dialogflow.V2/synth.metadata
Labels: cla: yes, context: full

#6268 [apis/Google.Cloud.ServiceControl.V1] build: update package-name, update links to service control and service management
  apis/Google.Cloud.ServiceControl.V1/Google.Cloud.ServiceControl.V1/QuotaControllerClient.g.cs
  apis/Google.Cloud.ServiceControl.V1/Google.Cloud.ServiceControl.V1/QuotaControllerGrpc.cs
  apis/Google.Cloud.ServiceControl.V1/Google.Cloud.ServiceControl.V1/ServiceControllerClient.g.cs
  apis/Google.Cloud.ServiceControl.V1/Google.Cloud.ServiceControl.V1/ServiceControllerGrpc.cs
  apis/Google.Cloud.ServiceControl.V1/synth.metadata
Labels: cla: yes, context: full

#6270 [CHANGE ME] Re-generated apis/ServiceDirectory to pick up changes in the API or client library generator.
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#6269 [apis/Google.Cloud.ServiceManagement.V1] build: update package-name, update links to service control and service management
  apis/Google.Cloud.ServiceManagement.V1/Google.Cloud.ServiceManagement.V1/Resources.cs
  apis/Google.Cloud.ServiceManagement.V1/Google.Cloud.ServiceManagement.V1/ServiceManagerClient.g.cs
  apis/Google.Cloud.ServiceManagement.V1/Google.Cloud.ServiceManagement.V1/Servicemanager.cs
  apis/Google.Cloud.ServiceManagement.V1/synth.metadata
Labels: cla: yes, context: full

#6273 [apis/Google.Cloud.Dialogflow.Cx.V3] feat: include original user query in WebhookRequest; add GetTextCaseresult API. doc: clarify resource format for session response.
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3.Snippets/TestCasesClientSnippets.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3.Tests/SessionsClientTest.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3.Tests/TestCasesClientTest.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Session.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/SessionEntityTypeGrpc.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/SessionEntityTypesClient.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/SessionResourceNames.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/TestCase.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/TestCaseGrpc.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/TestCaseResourceNames.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/TestCasesClient.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Webhook.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/WebhookResourceNames.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/synth.metadata
Labels: cla: yes, context: full

#6274 [apis/ServiceDirectory] feat: Publish Dataproc Metastore v1 API
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#6279 [apis/Google.Cloud.Metastore.V1Beta] chore: migrate metastore to the PHP microgenerator
  apis/Google.Cloud.Metastore.V1Beta/Google.Cloud.Metastore.V1Beta/DataprocMetastoreClient.g.cs
  apis/Google.Cloud.Metastore.V1Beta/Google.Cloud.Metastore.V1Beta/Metastore.cs
  apis/Google.Cloud.Metastore.V1Beta/synth.metadata
Labels: cla: yes, context: full

#6282 [apis/Google.Cloud.Spanner.Admin.Instance.V1] feat: add tagging request options
  apis/Google.Cloud.Spanner.Admin.Instance.V1/Google.Cloud.Spanner.Admin.Instance.V1/SpannerInstanceAdmin.cs
  apis/Google.Cloud.Spanner.Admin.Instance.V1/Google.Cloud.Spanner.Admin.Instance.V1/SpannerInstanceAdminGrpc.cs
  apis/Google.Cloud.Spanner.Admin.Instance.V1/synth.metadata
Labels: cla: yes, context: full

#6280 [apis/Google.Cloud.Notebooks.V1Beta1] chore: migrate notebooks to the PHP microgenerator
  apis/Google.Cloud.Notebooks.V1Beta1/Google.Cloud.Notebooks.V1Beta1/Environment.cs
  apis/Google.Cloud.Notebooks.V1Beta1/Google.Cloud.Notebooks.V1Beta1/Instance.cs
  apis/Google.Cloud.Notebooks.V1Beta1/Google.Cloud.Notebooks.V1Beta1/Service.cs
  apis/Google.Cloud.Notebooks.V1Beta1/synth.metadata
Labels: cla: yes, context: full

#6284 [apis/Google.Cloud.Spanner.Admin.Database.V1] feat: add tagging request options
  apis/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1/SpannerDatabaseAdmin.cs
  apis/Google.Cloud.Spanner.Admin.Database.V1/synth.metadata
Labels: cla: yes, context: full

#6285 [apis/Google.Cloud.Spanner.V1] feat: add tagging request options
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/Spanner.cs
  apis/Google.Cloud.Spanner.V1/synth.metadata
Labels: cla: yes, context: full

#6287 [apis/Google.Cloud.SecretManager.V1] feat: Rotation for Secrets
  apis/Google.Cloud.SecretManager.V1/Google.Cloud.SecretManager.V1.Tests/SecretManagerServiceClientTest.g.cs
  apis/Google.Cloud.SecretManager.V1/Google.Cloud.SecretManager.V1/Resources.cs
  apis/Google.Cloud.SecretManager.V1/synth.metadata
Labels: cla: yes, context: full

#5657 feat(spanner): add support for RPC priority
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.Tests/SpannerBatchCommandTests.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.Tests/SpannerCommandTests.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.Tests/V1/SpannerClientHelpers.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/EphemeralTransaction.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/Priority.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/SpannerBatchCommand.ExecutableCommand.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/SpannerBatchCommand.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/SpannerCommand.ExecutableCommand.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/SpannerCommand.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/SpannerTransaction.cs
Labels: api: spanner, cla: yes

#6288 [apis/Google.Cloud.ApiGateway.V1] chore(apigateway): Update namespaces for Ruby clients
  apis/Google.Cloud.ApiGateway.V1/Google.Cloud.ApiGateway.V1/Apigateway.cs
  apis/Google.Cloud.ApiGateway.V1/Google.Cloud.ApiGateway.V1/ApigatewayService.cs
  apis/Google.Cloud.ApiGateway.V1/synth.metadata
Labels: api: apigateway, cla: yes, context: full

#6289 [apis/Google.Cloud.DataCatalog.V1] feat: Policy Tag Manager v1 API service feat: new RenameTagTemplateFieldEnumValue API feat: adding fully_qualified_name in lookup and search feat: added DATAPROC_METASTORE integrated system along with new entry type
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1.Snippets/DataCatalogClientSnippets.g.cs
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1.Snippets/PolicyTagManagerClientSnippets.g.cs
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1.Snippets/PolicyTagManagerSerializationClientSnippets.g.cs
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1.Tests/DataCatalogClientTest.g.cs
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1.Tests/PolicyTagManagerClientTest.g.cs
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1.Tests/PolicyTagManagerSerializationClientTest.g.cs
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/Common.cs
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/DataCatalogClient.g.cs
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/DataSource.cs
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/Datacatalog.cs
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/DatacatalogGrpc.cs
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/DatacatalogResourceNames.g.cs
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/PolicyTagManagerClient.g.cs
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/PolicyTagManagerSerializationClient.g.cs
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/Policytagmanager.cs
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/PolicytagmanagerGrpc.cs
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/PolicytagmanagerResourceNames.g.cs
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/Policytagmanagerserialization.cs
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/PolicytagmanagerserializationGrpc.cs
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/PolicytagmanagerserializationResourceNames.g.cs
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/Schema.cs
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/Search.cs
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/TableSpec.cs
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/Tags.cs
  apis/Google.Cloud.DataCatalog.V1/synth.metadata
Labels: cla: yes, context: full

#6286 Generate GAPIC metadata files
  generateapis.sh
Labels: cla: yes

#6301 [apis/Google.Cloud.BigQuery.Storage.V1] feat: add a Arrow compression options (Only LZ4 for now). feat: Return schema on first ReadRowsResponse. doc: clarify limit on filter string.
  apis/Google.Cloud.BigQuery.Storage.V1/Google.Cloud.BigQuery.Storage.V1/Arrow.cs
  apis/Google.Cloud.BigQuery.Storage.V1/Google.Cloud.BigQuery.Storage.V1/Storage.cs
  apis/Google.Cloud.BigQuery.Storage.V1/Google.Cloud.BigQuery.Storage.V1/StorageGrpc.cs
  apis/Google.Cloud.BigQuery.Storage.V1/Google.Cloud.BigQuery.Storage.V1/Stream.cs
  apis/Google.Cloud.BigQuery.Storage.V1/synth.metadata
Labels: cla: yes, context: full

#6303 [apis/Google.Analytics.Data.V1Beta] feat: add `kind` field which is used to distinguish between response types feat: add `potentially_thresholded_requests_per_hour` field to `PropertyQuota`
  apis/Google.Analytics.Data.V1Beta/Google.Analytics.Data.V1Beta.Tests/BetaAnalyticsDataClientTest.g.cs
  apis/Google.Analytics.Data.V1Beta/Google.Analytics.Data.V1Beta/AnalyticsDataApi.cs
  apis/Google.Analytics.Data.V1Beta/Google.Analytics.Data.V1Beta/Data.cs
  apis/Google.Analytics.Data.V1Beta/synth.metadata
Labels: cla: yes, context: full

#6304 [apis/Google.Cloud.RecommendationEngine.V1Beta1] docs: place paths in code spans chore: update python package name to `google-cloud-recomendations-ai`
  apis/Google.Cloud.RecommendationEngine.V1Beta1/Google.Cloud.RecommendationEngine.V1Beta1/CatalogService.cs
  apis/Google.Cloud.RecommendationEngine.V1Beta1/Google.Cloud.RecommendationEngine.V1Beta1/CatalogServiceClient.g.cs
  apis/Google.Cloud.RecommendationEngine.V1Beta1/Google.Cloud.RecommendationEngine.V1Beta1/Import.cs
  apis/Google.Cloud.RecommendationEngine.V1Beta1/Google.Cloud.RecommendationEngine.V1Beta1/PredictionApiKeyRegistryClient.g.cs
  apis/Google.Cloud.RecommendationEngine.V1Beta1/Google.Cloud.RecommendationEngine.V1Beta1/PredictionApikeyRegistryService.cs
  apis/Google.Cloud.RecommendationEngine.V1Beta1/Google.Cloud.RecommendationEngine.V1Beta1/PredictionService.cs
  apis/Google.Cloud.RecommendationEngine.V1Beta1/Google.Cloud.RecommendationEngine.V1Beta1/PredictionServiceClient.g.cs
  apis/Google.Cloud.RecommendationEngine.V1Beta1/Google.Cloud.RecommendationEngine.V1Beta1/UserEventService.cs
  apis/Google.Cloud.RecommendationEngine.V1Beta1/Google.Cloud.RecommendationEngine.V1Beta1/UserEventServiceClient.g.cs
  apis/Google.Cloud.RecommendationEngine.V1Beta1/synth.metadata
Labels: cla: yes, context: full

#6305 [CHANGE ME] Re-generated apis/ServiceDirectory to pick up changes in the API or client library generator.
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: partial

#5575 feat: add support for request and transaction tagging to Spanner
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.Tests/SpannerBatchCommandTests.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.Tests/SpannerCommandTests.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/SpannerBatchCommand.ExecutableCommand.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/SpannerBatchCommand.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/SpannerCommand.ExecutableCommand.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/SpannerCommand.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/SpannerTransaction.cs
Labels: api: spanner, cla: yes
