Repository googleapis/google-cloud-dotnet, pull requests merged in 2021-02, with the labels that each got.

#5892 [apis/Google.LongRunning] chore(longrunning): update proto license & README
  apis/Google.LongRunning/Google.LongRunning/OperationsGrpc.cs
  apis/Google.LongRunning/synth.metadata
Labels: cla: yes, context: full

#5894 Add script to generate utility package metadata
  .kokoro/updateutilitydocs.bat
  .kokoro/updateutilitydocs.sh
  docs/generate-devsite-utilities.sh
Labels: cla: yes

#5896 [apis/ServiceDirectory] feat:Publish Cloud OrgPolicy v2 API
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5898 [apis/Google.Cloud.Channel.V1] feat: Add Pub/Sub endpoints for Cloud Channel API.
  apis/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1.Snippets/CloudChannelServiceClientSnippets.g.cs
  apis/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1.Tests/CloudChannelServiceClientTest.g.cs
  apis/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1/CloudChannelServiceClient.g.cs
  apis/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1/Service.cs
  apis/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1/ServiceGrpc.cs
  apis/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1/SubscriberEvent.cs
  apis/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1/SubscriberEventResourceNames.g.cs
  apis/Google.Cloud.Channel.V1/synth.metadata
Labels: cla: yes, context: full

#5895 Add sync Create() method to PublisherClient and SubscriberClient
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/PublisherClient.cs
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/PublisherServiceApiClientBuilder.cs
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/SubscriberClient.cs
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/SubscriberServiceApiClientBuilder.cs
Labels: cla: yes

#5901 [apis/ServiceDirectory] chore(profiler): Set proto namespace to google.cloud
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: api: cloudprofiler, cla: yes, context: full

#5902 [apis/Google.Cloud.Iot.V1] docs: add fieldMask format clarification to avoid misunderstandings.
  apis/Google.Cloud.Iot.V1/Google.Cloud.Iot.V1/DeviceManager.cs
  apis/Google.Cloud.Iot.V1/Google.Cloud.Iot.V1/DeviceManagerGrpc.cs
  apis/Google.Cloud.Iot.V1/synth.metadata
Labels: cla: yes, context: full

#5903 Fix utility docs generation
  docs/generate-devsite-utilities.sh
Labels: cla: yes

#5506 feat: log CommitStats if requested by the client application
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.CommonTesting/SpannerFixtureBase.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.CommonTesting/SpannerTestDatabase.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.IntegrationTests/TransactionTests.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.Tests/SpannerConnectionStringBuilderTests.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/SpannerConnection.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/SpannerConnectionStringBuilder.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/SpannerTransaction.cs
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/Internal/Logging/Logger.cs
Labels: api: spanner, cla: yes

#5904 [Diagnostics]: Un-skips outgoing trace tests.
  apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore.Snippets/TraceSnippets.cs
Labels: cla: yes

#5906 Change doc uploading for DevSite to use the new tarball layout
  uploaddocs.sh
Labels: cla: yes

#5907 Release Google.Analytics.Admin.V1Alpha version 1.0.0-alpha04
  README.md
  apis/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha.csproj
  apis/Google.Analytics.Admin.V1Alpha/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5913 Release Google.Cloud.SecurityCenter.V1 version 2.2.0
  README.md
  apis/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1.csproj
  apis/Google.Cloud.SecurityCenter.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5915 Remove fixups for OrgPolicy.V2 generation
  apis/Google.Cloud.OrgPolicy.V2/postgeneration.sh
  apis/Google.Cloud.OrgPolicy.V2/pregeneration.sh
Labels: cla: yes

#5917 ci: Deletes generated standalone snippets.
  generateapis.sh
Labels: cla: yes

#5914 Release Spanner libraries version 3.5.0
  README.md
  apis/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1.csproj
  apis/Google.Cloud.Spanner.Admin.Instance.V1/Google.Cloud.Spanner.Admin.Instance.V1/Google.Cloud.Spanner.Admin.Instance.V1.csproj
  apis/Google.Cloud.Spanner.Common.V1/Google.Cloud.Spanner.Common.V1/Google.Cloud.Spanner.Common.V1.csproj
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.csproj
  apis/Google.Cloud.Spanner.Data/docs/history.md
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1.csproj
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5921 [apis/Google.Cloud.Memcache.V1Beta2] feat: added ApplySoftwareUpdate API docs: various clarifications, new documentation for ApplySoftwareUpdate chore: update proto annotations
  apis/Google.Cloud.Memcache.V1Beta2/Google.Cloud.Memcache.V1Beta2.Snippets/CloudMemcacheClientSnippets.g.cs
  apis/Google.Cloud.Memcache.V1Beta2/Google.Cloud.Memcache.V1Beta2.Tests/CloudMemcacheClientTest.g.cs
  apis/Google.Cloud.Memcache.V1Beta2/Google.Cloud.Memcache.V1Beta2/CloudMemcache.cs
  apis/Google.Cloud.Memcache.V1Beta2/Google.Cloud.Memcache.V1Beta2/CloudMemcacheClient.g.cs
  apis/Google.Cloud.Memcache.V1Beta2/Google.Cloud.Memcache.V1Beta2/CloudMemcacheGrpc.cs
  apis/Google.Cloud.Memcache.V1Beta2/Google.Cloud.Memcache.V1Beta2/CloudMemcacheResourceNames.g.cs
  apis/Google.Cloud.Memcache.V1Beta2/synth.metadata
Labels: cla: yes, context: full

#5923 [apis/ServiceDirectory] feat: Make resolution status field available for error groups. Now callers can set the status of an error group by passing this to UpdateGroup. When not specified, it's treated like OPEN. feat: Make source location available f
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5924 Improve clean-up of StandaloneSnippets
  generateapis.sh
Labels: cla: yes

#5926 build: Downgrades gRPC default version back to 2.31.0.
  apis/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha.csproj
  apis/Google.Analytics.Data.V1Alpha/Google.Analytics.Data.V1Alpha/Google.Analytics.Data.V1Alpha.csproj
  apis/Google.Area120.Tables.V1Alpha1/Google.Area120.Tables.V1Alpha1/Google.Area120.Tables.V1Alpha1.csproj
  apis/Google.Cloud.AppEngine.V1/Google.Cloud.AppEngine.V1/Google.Cloud.AppEngine.V1.csproj
  apis/Google.Cloud.ArtifactRegistry.V1Beta2/Google.Cloud.ArtifactRegistry.V1Beta2/Google.Cloud.ArtifactRegistry.V1Beta2.csproj
  apis/Google.Cloud.AssuredWorkloads.V1Beta1/Google.Cloud.AssuredWorkloads.V1Beta1/Google.Cloud.AssuredWorkloads.V1Beta1.csproj
  apis/Google.Cloud.Billing.Budgets.V1Beta1/Google.Cloud.Billing.Budgets.V1Beta1/Google.Cloud.Billing.Budgets.V1Beta1.csproj
  apis/Google.Cloud.BinaryAuthorization.V1Beta1/Google.Cloud.BinaryAuthorization.V1Beta1/Google.Cloud.BinaryAuthorization.V1Beta1.csproj
  apis/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1.csproj
  apis/Google.Cloud.CloudBuild.V1/Google.Cloud.CloudBuild.V1/Google.Cloud.CloudBuild.V1.csproj
  apis/Google.Cloud.DataLabeling.V1Beta1/Google.Cloud.DataLabeling.V1Beta1/Google.Cloud.DataLabeling.V1Beta1.csproj
  apis/Google.Cloud.DocumentAI.V1Beta2/Google.Cloud.DocumentAI.V1Beta2/Google.Cloud.DocumentAI.V1Beta2.csproj
  apis/Google.Cloud.Domains.V1Beta1/Google.Cloud.Domains.V1Beta1/Google.Cloud.Domains.V1Beta1.csproj
  apis/Google.Cloud.ErrorReporting.V1Beta1/Google.Cloud.ErrorReporting.V1Beta1/Google.Cloud.ErrorReporting.V1Beta1.csproj
  apis/Google.Cloud.Gaming.V1Beta/Google.Cloud.Gaming.V1Beta/Google.Cloud.Gaming.V1Beta.csproj
  apis/Google.Cloud.GkeHub.V1Beta1/Google.Cloud.GkeHub.V1Beta1/Google.Cloud.GkeHub.V1Beta1.csproj
  apis/Google.Cloud.MediaTranslation.V1Beta1/Google.Cloud.MediaTranslation.V1Beta1/Google.Cloud.MediaTranslation.V1Beta1.csproj
  apis/Google.Cloud.Memcache.V1/Google.Cloud.Memcache.V1/Google.Cloud.Memcache.V1.csproj
  apis/Google.Cloud.Notebooks.V1Beta1/Google.Cloud.Notebooks.V1Beta1/Google.Cloud.Notebooks.V1Beta1.csproj
  apis/Google.Cloud.OrgPolicy.V2/Google.Cloud.OrgPolicy.V2/Google.Cloud.OrgPolicy.V2.csproj
  apis/Google.Cloud.PhishingProtection.V1Beta1/Google.Cloud.PhishingProtection.V1Beta1/Google.Cloud.PhishingProtection.V1Beta1.csproj
  apis/Google.Cloud.Profiler.V2/Google.Cloud.Profiler.V2/Google.Cloud.Profiler.V2.csproj
  apis/Google.Cloud.RecaptchaEnterprise.V1Beta1/Google.Cloud.RecaptchaEnterprise.V1Beta1/Google.Cloud.RecaptchaEnterprise.V1Beta1.csproj
  apis/Google.Cloud.RecommendationEngine.V1Beta1/Google.Cloud.RecommendationEngine.V1Beta1/Google.Cloud.RecommendationEngine.V1Beta1.csproj
  apis/Google.Cloud.Redis.V1Beta1/Google.Cloud.Redis.V1Beta1/Google.Cloud.Redis.V1Beta1.csproj
  apis/Google.Cloud.SecretManager.V1Beta1/Google.Cloud.SecretManager.V1Beta1/Google.Cloud.SecretManager.V1Beta1.csproj
  apis/Google.Cloud.Security.PrivateCA.V1Beta1/Google.Cloud.Security.PrivateCA.V1Beta1/Google.Cloud.Security.PrivateCA.V1Beta1.csproj
  apis/Google.Cloud.ServiceDirectory.V1Beta1/Google.Cloud.ServiceDirectory.V1Beta1/Google.Cloud.ServiceDirectory.V1Beta1.csproj
  apis/Google.Cloud.Speech.V1P1Beta1/Google.Cloud.Speech.V1P1Beta1/Google.Cloud.Speech.V1P1Beta1.csproj
  apis/Google.Cloud.Talent.V4Beta1/Google.Cloud.Talent.V4Beta1/Google.Cloud.Talent.V4Beta1.csproj
  apis/Google.Cloud.Tasks.V2Beta3/Google.Cloud.Tasks.V2Beta3/Google.Cloud.Tasks.V2Beta3.csproj
  apis/Google.Cloud.Video.Transcoder.V1Beta1/Google.Cloud.Video.Transcoder.V1Beta1/Google.Cloud.Video.Transcoder.V1Beta1.csproj
  apis/Google.Cloud.WebRisk.V1Beta1/Google.Cloud.WebRisk.V1Beta1/Google.Cloud.WebRisk.V1Beta1.csproj
  apis/Google.Cloud.Workflows.Executions.V1/Google.Cloud.Workflows.Executions.V1/Google.Cloud.Workflows.Executions.V1.csproj
  apis/Google.Cloud.Workflows.Executions.V1Beta/Google.Cloud.Workflows.Executions.V1Beta/Google.Cloud.Workflows.Executions.V1Beta.csproj
  apis/Google.Cloud.Workflows.V1/Google.Cloud.Workflows.V1/Google.Cloud.Workflows.V1.csproj
  apis/Google.Cloud.Workflows.V1Beta/Google.Cloud.Workflows.V1Beta/Google.Cloud.Workflows.V1Beta.csproj
  tools/Google.Cloud.Tools.ReleaseManager/GenerateProjectsCommand.cs
Labels: cla: yes

#5927 Include a title even for non-products
  tools/Google.Cloud.Tools.GenerateDocfxSources/Program.cs
Labels: cla: yes

#5931 [apis/Google.Cloud.BinaryAuthorization.V1Beta1] docs: Replace "whitelist" with "allowlist" in generated documentation
  apis/Google.Cloud.BinaryAuthorization.V1Beta1/Google.Cloud.BinaryAuthorization.V1Beta1/Resources.cs
  apis/Google.Cloud.BinaryAuthorization.V1Beta1/synth.metadata
Labels: cla: yes, context: full

#5933 [apis/Google.Cloud.Vision.V1] fix: sync vision v1 protos to get extra FaceAnnotation Landmark Types
  apis/Google.Cloud.Vision.V1/Google.Cloud.Vision.V1/ImageAnnotator.cs
  apis/Google.Cloud.Vision.V1/Google.Cloud.Vision.V1/ImageAnnotatorClient.g.cs
  apis/Google.Cloud.Vision.V1/Google.Cloud.Vision.V1/ImageAnnotatorGrpc.cs
  apis/Google.Cloud.Vision.V1/Google.Cloud.Vision.V1/ProductSearch.cs
  apis/Google.Cloud.Vision.V1/Google.Cloud.Vision.V1/ProductSearchClient.g.cs
  apis/Google.Cloud.Vision.V1/Google.Cloud.Vision.V1/ProductSearchService.cs
  apis/Google.Cloud.Vision.V1/Google.Cloud.Vision.V1/ProductSearchServiceGrpc.cs
  apis/Google.Cloud.Vision.V1/synth.metadata
Labels: cla: yes, context: full

#5934 [apis/ServiceDirectory] fix: Remove dependency on AppEngine's proto definitions. This also removes the source_references field.
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5935 Improve ordering of guides in DevSite docs
  tools/Google.Cloud.Tools.PostProcessDevSite/Program.cs
Labels: cla: yes

#5936 [apis/Google.Cloud.Dialogflow.Cx.V3] feat: supports SentimentAnalysisResult in webhook request, add http rules for long running operations docs: minor updates in wording
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Page.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/ResponseMessage.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Webhook.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/synth.metadata
Labels: cla: yes, context: full

#5937 [apis/ServiceDirectory] feat: Added client libraries for Google Workspace Add-ons V1 API
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5938 [apis/Google.Cloud.Billing.Budgets.V1] docs: Update rules for currency_code in budget_amount.
  apis/Google.Cloud.Billing.Budgets.V1/Google.Cloud.Billing.Budgets.V1/BudgetModel.cs
  apis/Google.Cloud.Billing.Budgets.V1/Google.Cloud.Billing.Budgets.V1/BudgetServiceGrpc.cs
  apis/Google.Cloud.Billing.Budgets.V1/synth.metadata
Labels: cla: yes, context: full

#5939 [apis/Google.Cloud.Billing.Budgets.V1Beta1] docs: Update rules for currency_code in budget_amount.
  apis/Google.Cloud.Billing.Budgets.V1Beta1/Google.Cloud.Billing.Budgets.V1Beta1/BudgetModel.cs
  apis/Google.Cloud.Billing.Budgets.V1Beta1/Google.Cloud.Billing.Budgets.V1Beta1/BudgetServiceGrpc.cs
  apis/Google.Cloud.Billing.Budgets.V1Beta1/synth.metadata
Labels: cla: yes, context: full

#5940 [apis/Google.Cloud.Kms.V1] fix: do not retry on 13 INTERNAL
  apis/Google.Cloud.Kms.V1/Google.Cloud.Kms.V1/KeyManagementServiceClient.g.cs
  apis/Google.Cloud.Kms.V1/synth.metadata
Labels: cla: yes, context: full

#5941 [apis/Google.LongRunning] chore: Operations proto comment cleanup
  apis/Google.LongRunning/Google.LongRunning/OperationsClient.g.cs
  apis/Google.LongRunning/Google.LongRunning/OperationsGrpc.cs
  apis/Google.LongRunning/synth.metadata
Labels: cla: yes, context: full

#5943 [apis/Google.Cloud.GkeHub.V1Beta1] feat: Update Membership API v1beta1 proto
  apis/Google.Cloud.GkeHub.V1Beta1/Google.Cloud.GkeHub.V1Beta1/Membership.cs
  apis/Google.Cloud.GkeHub.V1Beta1/Google.Cloud.GkeHub.V1Beta1/MembershipGrpc.cs
  apis/Google.Cloud.GkeHub.V1Beta1/synth.metadata
Labels: cla: yes, context: full

#5946 [apis/Google.Cloud.Dialogflow.Cx.V3] fix: RunTestCase http template. PHP REST client lib can be generated. feat: Support transition route group coverage for Test Cases. feat: Support SentimentAnalysisResult input in the WebhookRequest.
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3.Tests/TestCasesClientTest.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/AgentGrpc.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/EntityTypeGrpc.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/EnvironmentGrpc.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/ExperimentGrpc.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/FlowGrpc.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/IntentGrpc.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/PageGrpc.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/SecuritySettingsGrpc.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/SessionEntityTypeGrpc.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/SessionGrpc.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/TestCase.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/TestCaseGrpc.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/TestCasesClient.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/TransitionRouteGroupGrpc.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/VersionGrpc.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/WebhookGrpc.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/synth.metadata
Labels: cla: yes, context: full

#5947 [apis/ServiceDirectory] chore: migrate StreetView to the {Java,Python} microgenerators
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5949 [apis/ServiceDirectory] feat: release the Google Analytics Data API V1 Beta
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5951 test: enable NUMERIC integration tests on emulator
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.IntegrationTests/BindingTests.cs
Labels: cla: yes

#5955 [apis/ServiceDirectory] chore: remove protos for Google Ads API v3, which has sunset and is no longer available
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5956 [apis/Google.Cloud.Dialogflow.V2] feat: add additional_bindings to Dialogflow v2 ListIntents API docs: update copyrights and session docs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/AgentGrpc.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/ContextGrpc.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/EntityTypeGrpc.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/EnvironmentGrpc.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/Intent.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/IntentGrpc.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/Session.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/SessionEntityTypeGrpc.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/SessionGrpc.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/SessionsClient.g.cs
  apis/Google.Cloud.Dialogflow.V2/synth.metadata
Labels: cla: yes, context: full

#5954 [apis/Google.Cloud.Speech.V1P1Beta1] feat: Support Model Adaptation.
  apis/Google.Cloud.Speech.V1P1Beta1/Google.Cloud.Speech.V1P1Beta1.Snippets/AdaptationClientSnippets.g.cs
  apis/Google.Cloud.Speech.V1P1Beta1/Google.Cloud.Speech.V1P1Beta1.Tests/AdaptationClientTest.g.cs
  apis/Google.Cloud.Speech.V1P1Beta1/Google.Cloud.Speech.V1P1Beta1/AdaptationClient.g.cs
  apis/Google.Cloud.Speech.V1P1Beta1/Google.Cloud.Speech.V1P1Beta1/CloudSpeech.cs
  apis/Google.Cloud.Speech.V1P1Beta1/Google.Cloud.Speech.V1P1Beta1/CloudSpeechAdaptation.cs
  apis/Google.Cloud.Speech.V1P1Beta1/Google.Cloud.Speech.V1P1Beta1/CloudSpeechAdaptationGrpc.cs
  apis/Google.Cloud.Speech.V1P1Beta1/Google.Cloud.Speech.V1P1Beta1/CloudSpeechAdaptationResourceNames.g.cs
  apis/Google.Cloud.Speech.V1P1Beta1/Google.Cloud.Speech.V1P1Beta1/CloudSpeechGrpc.cs
  apis/Google.Cloud.Speech.V1P1Beta1/Google.Cloud.Speech.V1P1Beta1/Resource.cs
  apis/Google.Cloud.Speech.V1P1Beta1/synth.metadata
Labels: cla: yes, context: full

#5952 ci: Runs Spanner tests in emulator on presubmits.
  .github/workflows/spanner-emulator-pr-push.yml
  apis/Google.Cloud.Spanner.Data/run-emulator-tests.sh
Labels: cla: yes

#5953 ci: Cleans up GitHub actions configs.
  .github/workflows/build-pr.yml
  .github/workflows/build-push.yml
  .github/workflows/diff-pr.yml
Labels: cla: yes

#5959 [apis/Google.Area120.Tables.V1Alpha1] feat: Added ListWorkspaces, GetWorkspace, BatchDeleteRows APIs.
  apis/Google.Area120.Tables.V1Alpha1/Google.Area120.Tables.V1Alpha1.Snippets/TablesServiceClientSnippets.g.cs
  apis/Google.Area120.Tables.V1Alpha1/Google.Area120.Tables.V1Alpha1.Tests/TablesServiceClientTest.g.cs
  apis/Google.Area120.Tables.V1Alpha1/Google.Area120.Tables.V1Alpha1/Tables.cs
  apis/Google.Area120.Tables.V1Alpha1/Google.Area120.Tables.V1Alpha1/TablesGrpc.cs
  apis/Google.Area120.Tables.V1Alpha1/Google.Area120.Tables.V1Alpha1/TablesResourceNames.g.cs
  apis/Google.Area120.Tables.V1Alpha1/Google.Area120.Tables.V1Alpha1/TablesServiceClient.g.cs
  apis/Google.Area120.Tables.V1Alpha1/synth.metadata
Labels: cla: yes, context: full

#5960 [apis/Google.Cloud.Spanner.Admin.Database.V1] feat(spanner): add CMEK fields to backup and database
  apis/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1.Snippets/DatabaseAdminClientSnippets.g.cs
  apis/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1.Tests/DatabaseAdminClientTest.g.cs
  apis/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1/Backup.cs
  apis/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1/BackupResourceNames.g.cs
  apis/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1/Common.cs
  apis/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1/CommonResourceNames.g.cs
  apis/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1/DatabaseAdminClient.g.cs
  apis/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1/SpannerDatabaseAdmin.cs
  apis/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1/SpannerDatabaseAdminGrpc.cs
  apis/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1/SpannerDatabaseAdminResourceNames.g.cs
  apis/Google.Cloud.Spanner.Admin.Database.V1/synth.metadata
Labels: api: spanner, cla: yes, context: full

#5961 [apis/ServiceDirectory] feat(spanner): add CMEK fields to backup and database
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: api: spanner, cla: yes, context: full

#5962 test(Storage): Loosens public access prevention tests.
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.IntegrationTests/PublicAccessPreventionTest.cs
Labels: api: storage, cla: yes

#5963 [apis/Google.Cloud.Channel.V1] docs: Documentation update BREAKING CHANGE: TransferableSkus field deprecation. Okay to make this change since no clients are using the libraries that were released just last week. The fields were supposed to be depreca
  apis/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1.Snippets/CloudChannelServiceClientSnippets.g.cs
  apis/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1.Tests/CloudChannelServiceClientTest.g.cs
  apis/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1/CloudChannelServiceClient.g.cs
  apis/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1/Entitlements.cs
  apis/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1/Service.cs
  apis/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1/ServiceGrpc.cs
  apis/Google.Cloud.Channel.V1/synth.metadata
Labels: cla: yes, context: full

#5965 Find protos recursively when generating
  generateapis.sh
Labels: cla: yes

#5967 [apis/Google.Cloud.Bigtable.Admin.V2] feat: Publish new fields to support Customer Managed Encryption Keys (CMEK) on the existing Cloud Bigtable service methods.
  apis/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2.Snippets/BigtableInstanceAdminClientSnippets.g.cs
  apis/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2.Tests/BigtableInstanceAdminClientTest.g.cs
  apis/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2.Tests/BigtableTableAdminClientTest.g.cs
  apis/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2/Instance.cs
  apis/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2/InstanceResourceNames.g.cs
  apis/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2/Table.cs
  apis/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2/TableResourceNames.g.cs
  apis/Google.Cloud.Bigtable.Admin.V2/synth.metadata
Labels: cla: yes, context: full

#5969 [apis/Google.Cloud.Dialogflow.Cx.V3] docs: update languages link
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Agent.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/EntityType.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Flow.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Intent.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Page.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Session.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/TransitionRouteGroup.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/synth.metadata
Labels: cla: yes, context: full

#5970 Multiple new services, and an extra Bigtable dependency
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5971 Improve TOC handling for DevSite
  Google.Cloud.Tools.DocfxMetadata/Google.Cloud.Tools.DocfxMetadata.csproj
  Google.Cloud.Tools.DocfxMetadata/ItemType.cs
  Google.Cloud.Tools.DocfxMetadata/MetadataFile.cs
  Google.Cloud.Tools.DocfxMetadata/MetadataItem.cs
  Google.Cloud.Tools.DocfxMetadata/TocEntry.cs
  Google.Cloud.Tools.DocfxMetadata/YamlHelpers.cs
  docs/Google.Cloud.DocTools.sln
  docs/generate-devsite-utilities.sh
  tools/Google.Cloud.Tools.PostProcessDevSite/Google.Cloud.Tools.PostProcessDevSite.csproj
  tools/Google.Cloud.Tools.PostProcessDevSite/Program.cs
  tools/Google.Cloud.Tools.RegenerateToc/Google.Cloud.Tools.RegenerateToc.csproj
  tools/Google.Cloud.Tools.RegenerateToc/Program.cs
Labels: cla: yes

#5975 Release Google.Cloud.AppEngine.V1 version 1.0.0
  README.md
  apis/Google.Cloud.AppEngine.V1/.repo-metadata.json
  apis/Google.Cloud.AppEngine.V1/Google.Cloud.AppEngine.V1/Google.Cloud.AppEngine.V1.csproj
  apis/Google.Cloud.AppEngine.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#5980 [apis/Google.Analytics.Admin.V1Alpha] fix: add `https://www.googleapis.com/auth/analytics.edit` OAuth2 scope to the list of acceptable scopes for all read only methods of the Admin API docs: update the documentation of the `update_mask` field used by
  apis/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha/AnalyticsAdmin.cs
  apis/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha/AnalyticsAdminGrpc.cs
  apis/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha/AnalyticsAdminServiceClient.g.cs
  apis/Google.Analytics.Admin.V1Alpha/synth.metadata
Labels: cla: yes, context: full

#5983 Re-generated apis/ServiceDirectory with Workspace Marketplace and Cloud Shell APIs
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#5985 Use https://cloud.google.com/docs/authentication for auth docs
  README.md
Labels: cla: yes

#5986 [apis/Google.Cloud.Channel.V1] feat: addition of billing_account field on Plan. docs: clarification that valid address lines are required for all customers.
  apis/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1/CloudChannelServiceClient.g.cs
  apis/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1/Customers.cs
  apis/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1/Offers.cs
  apis/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1/ServiceGrpc.cs
  apis/Google.Cloud.Channel.V1/synth.metadata
Labels: cla: yes, context: full
