Repository googleapis/google-cloud-dotnet, pull requests merged in 2021-12, with the labels that each got.

#7570 Release Spanner libraries version 3.13.0
  apis/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1.csproj
  apis/Google.Cloud.Spanner.Admin.Instance.V1/Google.Cloud.Spanner.Admin.Instance.V1/Google.Cloud.Spanner.Admin.Instance.V1.csproj
  apis/Google.Cloud.Spanner.Common.V1/Google.Cloud.Spanner.Common.V1/Google.Cloud.Spanner.Common.V1.csproj
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.csproj
  apis/Google.Cloud.Spanner.Data/docs/history.md
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1.csproj
  apis/apis.json
Labels: cla: yes, autorelease: pending, allow breaking changes

#7571 Release Google.Cloud.Compute.V1 version 1.0.0-beta05
  apis/Google.Cloud.Compute.V1/Google.Cloud.Compute.V1/Google.Cloud.Compute.V1.csproj
  apis/Google.Cloud.Compute.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7575 chore: Remove synthtool support
  ENVIRONMENT.md
  generateapis.sh
  owl-bot-post-processor/main.sh
  tools/Google.Cloud.Tools.Common/AutoGeneratorType.cs
  tools/Google.Cloud.Tools.ReleaseManager/GenerateProjectsCommand.cs
  tools/Google.Cloud.Tools.ReleaseManager/History/GitCommit.cs
  toolversions.sh
Labels: cla: yes

#7583 Release Google.Cloud.Compute.V1 version 1.0.0-beta06
  apis/Google.Cloud.Compute.V1/Google.Cloud.Compute.V1/Google.Cloud.Compute.V1.csproj
  apis/Google.Cloud.Compute.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7585 chore: auto-assign issues to new Spanner owner
  .github/blunderbuss.yml
Labels: api: spanner

#7520 tests: Added two additional integration tests for dml insert
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.IntegrationTests/AllTypesTableFixture.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.IntegrationTests/GetSchemaTableTests.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.IntegrationTests/WriteTests.cs
Labels: cla: yes

#7591 Release Google.Cloud.Dlp.V2 version 3.4.0
  apis/Google.Cloud.Dlp.V2/Google.Cloud.Dlp.V2/Google.Cloud.Dlp.V2.csproj
  apis/Google.Cloud.Dlp.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#7592 Release Google.Cloud.NetworkConnectivity.V1 version 1.1.0
  apis/Google.Cloud.NetworkConnectivity.V1/Google.Cloud.NetworkConnectivity.V1/Google.Cloud.NetworkConnectivity.V1.csproj
  apis/Google.Cloud.NetworkConnectivity.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#7589 Release Google.Cloud.ContactCenterInsights.V1 version 1.1.0
  apis/Google.Cloud.ContactCenterInsights.V1/Google.Cloud.ContactCenterInsights.V1/Google.Cloud.ContactCenterInsights.V1.csproj
  apis/Google.Cloud.ContactCenterInsights.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#7594 Release Google.Cloud.RecaptchaEnterprise.V1 version 1.6.0
  apis/Google.Cloud.RecaptchaEnterprise.V1/Google.Cloud.RecaptchaEnterprise.V1/Google.Cloud.RecaptchaEnterprise.V1.csproj
  apis/Google.Cloud.RecaptchaEnterprise.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#7588 Release Google.Cloud.Bigtable.Admin.V2 version 2.7.0
  apis/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2.csproj
  apis/Google.Cloud.Bigtable.Admin.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#7597 Release Google.Cloud.Retail.V2 version 1.5.0
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2.csproj
  apis/Google.Cloud.Retail.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#7601 Release Google.Cloud.ServiceControl.V1 version 1.4.0
  apis/Google.Cloud.ServiceControl.V1/Google.Cloud.ServiceControl.V1/Google.Cloud.ServiceControl.V1.csproj
  apis/Google.Cloud.ServiceControl.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#7590 Release Google.Cloud.Dialogflow.Cx.V3 version 1.8.0
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3.csproj
  apis/Google.Cloud.Dialogflow.Cx.V3/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#7598 Release Google.Cloud.Security.PrivateCA.V1Beta1 version 1.0.0-beta04
  apis/Google.Cloud.Security.PrivateCA.V1Beta1/Google.Cloud.Security.PrivateCA.V1Beta1/Google.Cloud.Security.PrivateCA.V1Beta1.csproj
  apis/Google.Cloud.Security.PrivateCA.V1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#7595 Release Google.Cloud.Recommender.V1 version 2.7.0
  apis/Google.Cloud.Recommender.V1/Google.Cloud.Recommender.V1/Google.Cloud.Recommender.V1.csproj
  apis/Google.Cloud.Recommender.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#7603 Release Google.Cloud.ServiceUsage.V1 version 1.2.0
  apis/Google.Cloud.ServiceUsage.V1/Google.Cloud.ServiceUsage.V1/Google.Cloud.ServiceUsage.V1.csproj
  apis/Google.Cloud.ServiceUsage.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#7593 Release Google.Cloud.Notebooks.V1 version 1.0.0-beta02
  apis/Google.Cloud.Notebooks.V1/Google.Cloud.Notebooks.V1/Google.Cloud.Notebooks.V1.csproj
  apis/Google.Cloud.Notebooks.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#7604 Release Google.Cloud.Speech.V1 version 2.7.0
  apis/Google.Cloud.Speech.V1/Google.Cloud.Speech.V1/Google.Cloud.Speech.V1.csproj
  apis/Google.Cloud.Speech.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#7596 Release Google.Cloud.ResourceManager.V3 version 1.2.0
  apis/Google.Cloud.ResourceManager.V3/Google.Cloud.ResourceManager.V3/Google.Cloud.ResourceManager.V3.csproj
  apis/Google.Cloud.ResourceManager.V3/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#7606 Release Google.Cloud.Talent.V4 version 1.3.0
  apis/Google.Cloud.Talent.V4/Google.Cloud.Talent.V4/Google.Cloud.Talent.V4.csproj
  apis/Google.Cloud.Talent.V4/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#7602 Release Google.Cloud.ServiceDirectory.V1 version 1.3.0
  apis/Google.Cloud.ServiceDirectory.V1/Google.Cloud.ServiceDirectory.V1/Google.Cloud.ServiceDirectory.V1.csproj
  apis/Google.Cloud.ServiceDirectory.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#7607 Release Google.Cloud.Talent.V4Beta1 version 2.0.0-beta07
  apis/Google.Cloud.Talent.V4Beta1/Google.Cloud.Talent.V4Beta1/Google.Cloud.Talent.V4Beta1.csproj
  apis/Google.Cloud.Talent.V4Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#7608 Release Google.Cloud.Tasks.V2 version 2.4.0
  apis/Google.Cloud.Tasks.V2/Google.Cloud.Tasks.V2/Google.Cloud.Tasks.V2.csproj
  apis/Google.Cloud.Tasks.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#7609 Release Google.Cloud.Tasks.V2Beta3 version 2.0.0-beta08
  apis/Google.Cloud.Tasks.V2Beta3/Google.Cloud.Tasks.V2Beta3/Google.Cloud.Tasks.V2Beta3.csproj
  apis/Google.Cloud.Tasks.V2Beta3/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#7599 Release Google.Cloud.SecurityCenter.V1 version 2.10.0
  apis/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1.csproj
  apis/Google.Cloud.SecurityCenter.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#7611 Release Google.Cloud.Channel.V1 version 1.6.0
  apis/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1.csproj
  apis/Google.Cloud.Channel.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#7612 Release Google.Cloud.Deploy.V1 version 1.0.0-beta02
  apis/Google.Cloud.Deploy.V1/Google.Cloud.Deploy.V1/Google.Cloud.Deploy.V1.csproj
  apis/Google.Cloud.Deploy.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#7613 Release Google.Cloud.Gaming.V1 version 1.3.0
  apis/Google.Cloud.Gaming.V1/Google.Cloud.Gaming.V1/Google.Cloud.Gaming.V1.csproj
  apis/Google.Cloud.Gaming.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#7614 Release Google.Cloud.Gaming.V1Beta version 1.0.0-beta09
  apis/Google.Cloud.Gaming.V1Beta/Google.Cloud.Gaming.V1Beta/Google.Cloud.Gaming.V1Beta.csproj
  apis/Google.Cloud.Gaming.V1Beta/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#7610 Release Google.Cloud.AutoML.V1 version 2.4.0
  apis/Google.Cloud.AutoML.V1/Google.Cloud.AutoML.V1/Google.Cloud.AutoML.V1.csproj
  apis/Google.Cloud.AutoML.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#7605 Release Google.Cloud.Speech.V1P1Beta1 version 2.0.0-beta07
  apis/Google.Cloud.Speech.V1P1Beta1/Google.Cloud.Speech.V1P1Beta1/Google.Cloud.Speech.V1P1Beta1.csproj
  apis/Google.Cloud.Speech.V1P1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#7600 Release Google.Cloud.SecurityCenter.V1P1Beta1 version 2.0.0-beta07
  apis/Google.Cloud.SecurityCenter.V1P1Beta1/Google.Cloud.SecurityCenter.V1P1Beta1/Google.Cloud.SecurityCenter.V1P1Beta1.csproj
  apis/Google.Cloud.SecurityCenter.V1P1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact
