Repository googleapis/google-cloud-dotnet, pull requests merged in 2021-11, with the labels that each got.

#7411 Release diagnostics libraries version 4.3.0
  apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore.csproj
  apis/Google.Cloud.Diagnostics.AspNetCore/docs/history.md
  apis/Google.Cloud.Diagnostics.AspNetCore3/Google.Cloud.Diagnostics.AspNetCore3/Google.Cloud.Diagnostics.AspNetCore3.csproj
  apis/Google.Cloud.Diagnostics.AspNetCore3/docs/history.md
  apis/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common.csproj
  apis/Google.Cloud.Diagnostics.Common/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7410 [apis/Google.Analytics.Data.V1Beta] feat: add the `schema_restriction_response` field to the `ResponseMetaData` type that contains the schema restrictions actively enforced in creating a report feat: add the `currency_code`, `time_zone` fields to the
  apis/Google.Analytics.Data.V1Beta/Google.Analytics.Data.V1Beta/Data.g.cs
  apis/Google.Analytics.Data.V1Beta/synth.metadata
Labels: cla: yes, context: full

#7414 [apis/Google.Cloud.Recommender.V1] docs: fix docstring formatting
  apis/Google.Cloud.Recommender.V1/Google.Cloud.Recommender.V1/Recommendation.g.cs
  apis/Google.Cloud.Recommender.V1/Google.Cloud.Recommender.V1/RecommenderClient.g.cs
  apis/Google.Cloud.Recommender.V1/Google.Cloud.Recommender.V1/RecommenderService.g.cs
  apis/Google.Cloud.Recommender.V1/synth.metadata
Labels: cla: yes, context: full

#7415 fix: Adjust the common Bigtable Table resource service
  apis/Google.Cloud.Bigtable.Common.V2/CommonResourcesConfig.json
Labels: cla: yes

#7416 [CHANGE ME] Re-generated apis/Google.Cloud.Bigtable.Admin.V2 to pick up changes in the API or client library generator.
  apis/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2/BigtableInstanceAdmin.g.cs
  apis/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2/BigtableTableAdmin.g.cs
  apis/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2/Instance.g.cs
  apis/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2/Table.g.cs
  apis/Google.Cloud.Bigtable.Admin.V2/synth.metadata
Labels: cla: yes, context: partial

#7417 [CHANGE ME] Re-generated apis/Google.Cloud.Bigtable.V2 to pick up changes in the API or client library generator.
  apis/Google.Cloud.Bigtable.V2/Google.Cloud.Bigtable.V2/Bigtable.g.cs
  apis/Google.Cloud.Bigtable.V2/synth.metadata
Labels: cla: yes, context: partial

#7418 [apis/Google.Cloud.RecaptchaEnterprise.V1] feat: add reCAPTCHA Enterprise account defender API methods
  apis/Google.Cloud.RecaptchaEnterprise.V1/Google.Cloud.RecaptchaEnterprise.V1.Snippets/RecaptchaEnterpriseServiceClientSnippets.g.cs
  apis/Google.Cloud.RecaptchaEnterprise.V1/Google.Cloud.RecaptchaEnterprise.V1.Tests/RecaptchaEnterpriseServiceClientTest.g.cs
  apis/Google.Cloud.RecaptchaEnterprise.V1/Google.Cloud.RecaptchaEnterprise.V1/RecaptchaEnterpriseServiceClient.g.cs
  apis/Google.Cloud.RecaptchaEnterprise.V1/Google.Cloud.RecaptchaEnterprise.V1/Recaptchaenterprise.g.cs
  apis/Google.Cloud.RecaptchaEnterprise.V1/Google.Cloud.RecaptchaEnterprise.V1/RecaptchaenterpriseGrpc.g.cs
  apis/Google.Cloud.RecaptchaEnterprise.V1/Google.Cloud.RecaptchaEnterprise.V1/RecaptchaenterpriseResourceNames.g.cs
  apis/Google.Cloud.RecaptchaEnterprise.V1/gapic_metadata.json
  apis/Google.Cloud.RecaptchaEnterprise.V1/synth.metadata
Labels: cla: yes, context: full

#7420 [apis/Google.Cloud.Channel.V1] docs: clarified usage of entitlement parameters
  apis/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1/Entitlements.g.cs
  apis/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1/Service.g.cs
  apis/Google.Cloud.Channel.V1/synth.metadata
Labels: cla: yes, context: full

#7423 Add Google.LongRunning dependency for OSConfig
  apis/Google.Cloud.OsConfig.V1/Google.Cloud.OsConfig.V1/Google.Cloud.OsConfig.V1.csproj
  apis/apis.json
Labels: cla: yes

#7424 [apis/Google.Cloud.OsConfig.V1] feat: OSConfig: add OS policy assignment rpcs
  apis/Google.Cloud.OsConfig.V1/Google.Cloud.OsConfig.V1.Snippets/OsConfigZonalServiceClientSnippets.g.cs
  apis/Google.Cloud.OsConfig.V1/Google.Cloud.OsConfig.V1.Tests/OsConfigZonalServiceClientTest.g.cs
  apis/Google.Cloud.OsConfig.V1/Google.Cloud.OsConfig.V1/OsConfigZonalServiceClient.g.cs
  apis/Google.Cloud.OsConfig.V1/Google.Cloud.OsConfig.V1/OsPolicy.g.cs
  apis/Google.Cloud.OsConfig.V1/Google.Cloud.OsConfig.V1/OsPolicyAssignmentReports.g.cs
  apis/Google.Cloud.OsConfig.V1/Google.Cloud.OsConfig.V1/OsPolicyAssignmentReportsResourceNames.g.cs
  apis/Google.Cloud.OsConfig.V1/Google.Cloud.OsConfig.V1/OsPolicyAssignments.g.cs
  apis/Google.Cloud.OsConfig.V1/Google.Cloud.OsConfig.V1/OsPolicyAssignmentsResourceNames.g.cs
  apis/Google.Cloud.OsConfig.V1/Google.Cloud.OsConfig.V1/OsconfigZonalService.g.cs
  apis/Google.Cloud.OsConfig.V1/Google.Cloud.OsConfig.V1/OsconfigZonalServiceGrpc.g.cs
  apis/Google.Cloud.OsConfig.V1/gapic_metadata.json
  apis/Google.Cloud.OsConfig.V1/synth.metadata
Labels: cla: yes, context: full

#7431 [apis/Google.Cloud.Functions.V1] feat: Secret Manager integration fields 'secret_environment_variables' and 'secret_volumes' added feat: CMEK integration fields 'kms_key_name' and 'docker_repository' added
  apis/Google.Cloud.Functions.V1/Google.Cloud.Functions.V1.Tests/CloudFunctionsServiceClientTest.g.cs
  apis/Google.Cloud.Functions.V1/Google.Cloud.Functions.V1/Functions.g.cs
  apis/Google.Cloud.Functions.V1/Google.Cloud.Functions.V1/FunctionsResourceNames.g.cs
  apis/Google.Cloud.Functions.V1/Google.Cloud.Functions.V1/Operations.g.cs
  apis/Google.Cloud.Functions.V1/synth.metadata
Labels: cla: yes, context: full

#7432 chore: Update GAPIC generator version
  generateapis.sh
  toolversions.sh
Labels: cla: yes

#7434 docs: Fix docs typo
  apis/Google.Cloud.PubSub.V1/docs/index.md
Labels: cla: yes

#7436 [apis/Google.Cloud.ResourceManager.V3] docs: fix docstring formatting
  apis/Google.Cloud.ResourceManager.V3/Google.Cloud.ResourceManager.V3/Folders.g.cs
  apis/Google.Cloud.ResourceManager.V3/Google.Cloud.ResourceManager.V3/FoldersClient.g.cs
  apis/Google.Cloud.ResourceManager.V3/Google.Cloud.ResourceManager.V3/Organizations.g.cs
  apis/Google.Cloud.ResourceManager.V3/Google.Cloud.ResourceManager.V3/OrganizationsClient.g.cs
  apis/Google.Cloud.ResourceManager.V3/Google.Cloud.ResourceManager.V3/Projects.g.cs
  apis/Google.Cloud.ResourceManager.V3/Google.Cloud.ResourceManager.V3/ProjectsClient.g.cs
  apis/Google.Cloud.ResourceManager.V3/synth.metadata
Labels: cla: yes, context: full

#7437 [apis/Google.Cloud.Workflows.Executions.V1] feat: add a stack_trace field to the Error messages specifying where the error occured feat: add call_log_level field to Execution messages doc: clarify requirement to escape strings within JSON arguments
  apis/Google.Cloud.Workflows.Executions.V1/Google.Cloud.Workflows.Executions.V1.Tests/ExecutionsClientTest.g.cs
  apis/Google.Cloud.Workflows.Executions.V1/Google.Cloud.Workflows.Executions.V1/Executions.g.cs
  apis/Google.Cloud.Workflows.Executions.V1/Google.Cloud.Workflows.Executions.V1/ExecutionsGrpc.g.cs
  apis/Google.Cloud.Workflows.Executions.V1/synth.metadata
Labels: cla: yes, context: full

#7439 chore: Update default branch to main
  .github/workflows/build-pr.yml
  .github/workflows/build-push.yml
  .github/workflows/diff-pr.yml
  .github/workflows/spanner-emulator-pr-push.yml
  build.sh
  buildrelease.sh
  checkpackages.sh
  detect-pr-changes.sh
  tools/Google.Cloud.Tools.ApiIndex.V1/IndexAugmentations.cs
  tools/Google.Cloud.Tools.ReleaseManager/CommandBase.cs
  tools/Google.Cloud.Tools.ReleaseManager/PushCommand.cs
Labels: cla: yes

#7443 [apis/Google.Cloud.DataCatalog.V1] feat: Added BigQueryDateShardedSpec.latest_shard_resource field feat: Added SearchCatalogResult.display_name field feat: Added SearchCatalogResult.description field
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/Common.g.cs
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/DataCatalogClient.g.cs
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/Datacatalog.g.cs
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/DatacatalogGrpc.g.cs
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/PolicyTagManagerClient.g.cs
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/Policytagmanager.g.cs
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/Search.g.cs
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/TableSpec.g.cs
  apis/Google.Cloud.DataCatalog.V1/synth.metadata
Labels: cla: yes, context: full

#7444 Release Google.Cloud.Iam.V1 version 2.3.0
  apis/Google.Cloud.Iam.V1/Google.Cloud.Iam.V1.Snippets/Google.Cloud.Iam.V1.Snippets.csproj
  apis/Google.Cloud.Iam.V1/Google.Cloud.Iam.V1.Snippets/IAMPolicyClientSnippets.g.cs
  apis/Google.Cloud.Iam.V1/Google.Cloud.Iam.V1.Snippets/coverage.xml
  apis/Google.Cloud.Iam.V1/Google.Cloud.Iam.V1.Tests/IAMPolicyClientTest.g.cs
  apis/Google.Cloud.Iam.V1/Google.Cloud.Iam.V1.sln
  apis/Google.Cloud.Iam.V1/Google.Cloud.Iam.V1/Google.Cloud.Iam.V1.csproj
  apis/Google.Cloud.Iam.V1/Google.Cloud.Iam.V1/IAMPolicyClient.g.cs
  apis/Google.Cloud.Iam.V1/Google.Cloud.Iam.V1/IamPolicyResourceNames.g.cs
  apis/Google.Cloud.Iam.V1/Google.Cloud.Iam.V1/Logging/AuditData.g.cs
  apis/Google.Cloud.Iam.V1/docs/history.md
  apis/Google.Cloud.Iam.V1/gapic_metadata.json
  apis/Google.Cloud.Iam.V1/synth.metadata
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7442 chore: Skip another commit
  tools/Google.Cloud.Tools.ReleaseManager/History/overrides.json
Labels: cla: yes

#7445 chore: remove facility to generate a "protogrpc" package
  generateapis.sh
  tools/Google.Cloud.Tools.Common/GeneratorType.cs
Labels: cla: yes

#7458 [apis/Google.Cloud.Gaming.V1] docs: fix docstring formatting
  apis/Google.Cloud.Gaming.V1/Google.Cloud.Gaming.V1/Common.g.cs
  apis/Google.Cloud.Gaming.V1/synth.metadata
Labels: cla: yes, context: full

#7459 [apis/Google.Cloud.Gaming.V1Beta] docs: fix docstring formatting
  apis/Google.Cloud.Gaming.V1Beta/Google.Cloud.Gaming.V1Beta/Common.g.cs
  apis/Google.Cloud.Gaming.V1Beta/synth.metadata
Labels: cla: yes, context: full

#7460 Regenerate Google.Cloud.Location
  apis/Google.Cloud.Location/synth.metadata
Labels: cla: yes

#7447 [apis/Google.Cloud.BinaryAuthorization.V1Beta1] feat: add new admission rule types to Policy feat: update SignatureAlgorithm enum to match algorithm names in KMS feat: add SystemPolicyV1Beta1 service
  apis/Google.Cloud.BinaryAuthorization.V1Beta1/Google.Cloud.BinaryAuthorization.V1Beta1.Snippets/SystemPolicyV1Beta1ClientSnippets.g.cs
  apis/Google.Cloud.BinaryAuthorization.V1Beta1/Google.Cloud.BinaryAuthorization.V1Beta1.Tests/BinauthzManagementServiceV1Beta1ClientTest.g.cs
  apis/Google.Cloud.BinaryAuthorization.V1Beta1/Google.Cloud.BinaryAuthorization.V1Beta1.Tests/SystemPolicyV1Beta1ClientTest.g.cs
  apis/Google.Cloud.BinaryAuthorization.V1Beta1/Google.Cloud.BinaryAuthorization.V1Beta1/BinauthzManagementServiceV1Beta1Client.g.cs
  apis/Google.Cloud.BinaryAuthorization.V1Beta1/Google.Cloud.BinaryAuthorization.V1Beta1/Resources.g.cs
  apis/Google.Cloud.BinaryAuthorization.V1Beta1/Google.Cloud.BinaryAuthorization.V1Beta1/ResourcesResourceNames.g.cs
  apis/Google.Cloud.BinaryAuthorization.V1Beta1/Google.Cloud.BinaryAuthorization.V1Beta1/Service.g.cs
  apis/Google.Cloud.BinaryAuthorization.V1Beta1/Google.Cloud.BinaryAuthorization.V1Beta1/ServiceGrpc.g.cs
  apis/Google.Cloud.BinaryAuthorization.V1Beta1/Google.Cloud.BinaryAuthorization.V1Beta1/ServiceResourceNames.g.cs
  apis/Google.Cloud.BinaryAuthorization.V1Beta1/Google.Cloud.BinaryAuthorization.V1Beta1/SystemPolicyV1Beta1Client.g.cs
  apis/Google.Cloud.BinaryAuthorization.V1Beta1/gapic_metadata.json
  apis/Google.Cloud.BinaryAuthorization.V1Beta1/synth.metadata
Labels: cla: yes, context: full

#7463 [apis/Google.Cloud.SecurityCenter.V1] feat: Added resource type and display_name field to the FindingResult, and supported them in the filter for ListFindings and GroupFindings. Also added display_name to the resource which is surfaced in Notificatio
  apis/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1/Resource.g.cs
  apis/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1/SecuritycenterService.g.cs
  apis/Google.Cloud.SecurityCenter.V1/synth.metadata
Labels: cla: yes, context: full

#7461 [apis/Google.Cloud.Redis.V1] feat: [Cloud Memorystore for Redis] Support Multiple Read Replicas when creating Instance
  apis/Google.Cloud.Redis.V1/Google.Cloud.Redis.V1.Tests/CloudRedisClientTest.g.cs
  apis/Google.Cloud.Redis.V1/Google.Cloud.Redis.V1/CloudRedis.g.cs
  apis/Google.Cloud.Redis.V1/Google.Cloud.Redis.V1/CloudRedisClient.g.cs
  apis/Google.Cloud.Redis.V1/Google.Cloud.Redis.V1/CloudRedisGrpc.g.cs
  apis/Google.Cloud.Redis.V1/synth.metadata
Labels: cla: yes, context: full

#7462 [apis/Google.Cloud.Redis.V1Beta1] feat: [Cloud Memorystore for Redis] Support Multiple Read Replicas when creating Instance
  apis/Google.Cloud.Redis.V1Beta1/Google.Cloud.Redis.V1Beta1.Tests/CloudRedisClientTest.g.cs
  apis/Google.Cloud.Redis.V1Beta1/Google.Cloud.Redis.V1Beta1/CloudRedis.g.cs
  apis/Google.Cloud.Redis.V1Beta1/Google.Cloud.Redis.V1Beta1/CloudRedisClient.g.cs
  apis/Google.Cloud.Redis.V1Beta1/Google.Cloud.Redis.V1Beta1/CloudRedisGrpc.g.cs
  apis/Google.Cloud.Redis.V1Beta1/synth.metadata
Labels: cla: yes, context: full

#7464 Release Google.Cloud.Ids.V1 version 1.0.0-beta01
  .github/renovate.json
  README.md
  apis/Google.Cloud.Ids.V1/.repo-metadata.json
  apis/Google.Cloud.Ids.V1/Google.Cloud.Ids.V1.Snippets/Google.Cloud.Ids.V1.Snippets.csproj
  apis/Google.Cloud.Ids.V1/Google.Cloud.Ids.V1.Snippets/IDSClientSnippets.g.cs
  apis/Google.Cloud.Ids.V1/Google.Cloud.Ids.V1.Snippets/coverage.xml
  apis/Google.Cloud.Ids.V1/Google.Cloud.Ids.V1.Tests/Google.Cloud.Ids.V1.Tests.csproj
  apis/Google.Cloud.Ids.V1/Google.Cloud.Ids.V1.Tests/IDSClientTest.g.cs
  apis/Google.Cloud.Ids.V1/Google.Cloud.Ids.V1.Tests/coverage.xml
  apis/Google.Cloud.Ids.V1/Google.Cloud.Ids.V1.sln
  apis/Google.Cloud.Ids.V1/Google.Cloud.Ids.V1/Google.Cloud.Ids.V1.csproj
  apis/Google.Cloud.Ids.V1/Google.Cloud.Ids.V1/IDSClient.g.cs
  apis/Google.Cloud.Ids.V1/Google.Cloud.Ids.V1/Ids.g.cs
  apis/Google.Cloud.Ids.V1/Google.Cloud.Ids.V1/IdsGrpc.g.cs
  apis/Google.Cloud.Ids.V1/Google.Cloud.Ids.V1/IdsResourceNames.g.cs
  apis/Google.Cloud.Ids.V1/docs/history.md
  apis/Google.Cloud.Ids.V1/docs/index.md
  apis/Google.Cloud.Ids.V1/gapic_metadata.json
  apis/Google.Cloud.Ids.V1/smoketests.json
  apis/Google.Cloud.Ids.V1/synth.metadata
  apis/Google.Cloud.Ids.V1/synth.py
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7465 fix: Respects the service client set through error reporting options.
  apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore.IntegrationTests/ErrorReporting/ErrorReportingTest.cs
  apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore.IntegrationTests/Logging/LoggingTest.cs
  apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore.IntegrationTests/Trace/TraceTest.cs
  apis/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common/ErrorReporting/ErrorReportingExtensions.cs
Labels: cla: yes

#7467 Release diagnostics libraries version 4.3.1
  apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore.csproj
  apis/Google.Cloud.Diagnostics.AspNetCore/docs/history.md
  apis/Google.Cloud.Diagnostics.AspNetCore3/Google.Cloud.Diagnostics.AspNetCore3/Google.Cloud.Diagnostics.AspNetCore3.csproj
  apis/Google.Cloud.Diagnostics.AspNetCore3/docs/history.md
  apis/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common.csproj
  apis/Google.Cloud.Diagnostics.Common/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7468 [apis/Google.Cloud.DataCatalog.V1] docs: Improved formatting
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/DataCatalogClient.g.cs
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/Datacatalog.g.cs
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/DatacatalogGrpc.g.cs
  apis/Google.Cloud.DataCatalog.V1/synth.metadata
Labels: cla: yes, context: full

#7469 [apis/Google.Cloud.SecurityCenter.V1P1Beta1] docs: fix docstring formatting
  apis/Google.Cloud.SecurityCenter.V1P1Beta1/Google.Cloud.SecurityCenter.V1P1Beta1/SecuritycenterService.g.cs
  apis/Google.Cloud.SecurityCenter.V1P1Beta1/synth.metadata
Labels: cla: yes, context: full

#7477 Release Google.Cloud.AIPlatform.V1 version 1.0.0
  apis/Google.Cloud.AIPlatform.V1/.repo-metadata.json
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1.csproj
  apis/Google.Cloud.AIPlatform.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7478 Release Google.Cloud.ArtifactRegistry.V1 version 1.0.0
  apis/Google.Cloud.ArtifactRegistry.V1/.repo-metadata.json
  apis/Google.Cloud.ArtifactRegistry.V1/Google.Cloud.ArtifactRegistry.V1/Google.Cloud.ArtifactRegistry.V1.csproj
  apis/Google.Cloud.ArtifactRegistry.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7480 Release Google.Cloud.Orchestration.Airflow.Service.V1 version 1.0.0
  apis/Google.Cloud.Orchestration.Airflow.Service.V1/.repo-metadata.json
  apis/Google.Cloud.Orchestration.Airflow.Service.V1/Google.Cloud.Orchestration.Airflow.Service.V1/Google.Cloud.Orchestration.Airflow.Service.V1.csproj
  apis/Google.Cloud.Orchestration.Airflow.Service.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7482 Release Google.Cloud.ContactCenterInsights.V1 version 1.0.0
  apis/Google.Cloud.ContactCenterInsights.V1/.repo-metadata.json
  apis/Google.Cloud.ContactCenterInsights.V1/Google.Cloud.ContactCenterInsights.V1/Google.Cloud.ContactCenterInsights.V1.csproj
  apis/Google.Cloud.ContactCenterInsights.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7483 Release Google.Cloud.DataFusion.V1 version 1.0.0
  apis/Google.Cloud.DataFusion.V1/.repo-metadata.json
  apis/Google.Cloud.DataFusion.V1/Google.Cloud.DataFusion.V1/Google.Cloud.DataFusion.V1.csproj
  apis/Google.Cloud.DataFusion.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7481 Release Google.Cloud.NetworkConnectivity.V1 version 1.0.0
  apis/Google.Cloud.NetworkConnectivity.V1/.repo-metadata.json
  apis/Google.Cloud.NetworkConnectivity.V1/Google.Cloud.NetworkConnectivity.V1/Google.Cloud.NetworkConnectivity.V1.csproj
  apis/Google.Cloud.NetworkConnectivity.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7479 fix: When generating history, get commits in the right version
  tools/Google.Cloud.Tools.ReleaseManager/History/Release.cs
Labels: cla: yes

#7485 Release Google.Cloud.BinaryAuthorization.V1 version 1.0.0
  apis/Google.Cloud.BinaryAuthorization.V1/.repo-metadata.json
  apis/Google.Cloud.BinaryAuthorization.V1/Google.Cloud.BinaryAuthorization.V1/Google.Cloud.BinaryAuthorization.V1.csproj
  apis/Google.Cloud.BinaryAuthorization.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7484 Release Google.Cloud.AssuredWorkloads.V1 version 1.0.0
  apis/Google.Cloud.AssuredWorkloads.V1/.repo-metadata.json
  apis/Google.Cloud.AssuredWorkloads.V1/Google.Cloud.AssuredWorkloads.V1/Google.Cloud.AssuredWorkloads.V1.csproj
  apis/Google.Cloud.AssuredWorkloads.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7490 Release Google.Cloud.Dialogflow.Cx.V3 version 1.6.0
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3.csproj
  apis/Google.Cloud.Dialogflow.Cx.V3/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7489 Release Google.Cloud.DataCatalog.V1 version 1.6.0
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1.csproj
  apis/Google.Cloud.DataCatalog.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7491 Release Google.Cloud.Dialogflow.V2 version 3.7.0
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2.csproj
  apis/Google.Cloud.Dialogflow.V2/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7488 Release Google.Cloud.Compute.V1 version 1.0.0-beta04
  apis/Google.Cloud.Compute.V1/Google.Cloud.Compute.V1/Google.Cloud.Compute.V1.csproj
  apis/Google.Cloud.Compute.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7494 Release Google.Cloud.OsConfig.V1 version 1.6.0
  apis/Google.Cloud.OsConfig.V1/Google.Cloud.OsConfig.V1/Google.Cloud.OsConfig.V1.csproj
  apis/Google.Cloud.OsConfig.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7492 Release Google.Cloud.Functions.V1 version 1.3.0
  apis/Google.Cloud.Functions.V1/Google.Cloud.Functions.V1/Google.Cloud.Functions.V1.csproj
  apis/Google.Cloud.Functions.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7498 Release Google.Cloud.SecurityCenter.V1 version 2.8.0
  apis/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1.csproj
  apis/Google.Cloud.SecurityCenter.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7499 Release Google.Cloud.Kms.V1 version 2.7.0
  apis/Google.Cloud.Kms.V1/Google.Cloud.Kms.V1/Google.Cloud.Kms.V1.csproj
  apis/Google.Cloud.Kms.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7486 Release Google.Cloud.BinaryAuthorization.V1Beta1 version 1.0.0-beta05
  apis/Google.Cloud.BinaryAuthorization.V1Beta1/Google.Cloud.BinaryAuthorization.V1Beta1/Google.Cloud.BinaryAuthorization.V1Beta1.csproj
  apis/Google.Cloud.BinaryAuthorization.V1Beta1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7496 Release Google.Cloud.Redis.V1 version 2.4.0
  apis/Google.Cloud.Redis.V1/Google.Cloud.Redis.V1/Google.Cloud.Redis.V1.csproj
  apis/Google.Cloud.Redis.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7497 Release Google.Cloud.Redis.V1Beta1 version 2.0.0-beta06
  apis/Google.Cloud.Redis.V1Beta1/Google.Cloud.Redis.V1Beta1/Google.Cloud.Redis.V1Beta1.csproj
  apis/Google.Cloud.Redis.V1Beta1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7495 Release Google.Cloud.RecaptchaEnterprise.V1 version 1.5.0
  apis/Google.Cloud.RecaptchaEnterprise.V1/Google.Cloud.RecaptchaEnterprise.V1/Google.Cloud.RecaptchaEnterprise.V1.csproj
  apis/Google.Cloud.RecaptchaEnterprise.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7487 Release Google.Cloud.Channel.V1 version 1.5.0
  apis/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1.csproj
  apis/Google.Cloud.Channel.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7503 chore: Move AIPlatform to OwlBot
  apis/Google.Cloud.AIPlatform.V1/.OwlBot.yaml
  apis/Google.Cloud.AIPlatform.V1/synth.metadata
  apis/Google.Cloud.AIPlatform.V1/synth.py
  apis/apis.json
Labels: cla: yes

#7505 chore: Migrate Google.Cloud.Compute.V1 to OwlBot
  apis/Google.Cloud.Compute.V1/.OwlBot.yaml
  apis/Google.Cloud.Compute.V1/synth.metadata
  apis/Google.Cloud.Compute.V1/synth.py
  apis/apis.json
Labels: cla: yes

#7514 docs: Fix emulator help page
  docs/devsite-help/emulators.md
  tools/Google.Cloud.Docs.Snippets/EmulatorSnippets.cs
Labels: cla: yes

#7521 chore: Remove now-unnecessary proto changes for Compute
  apis/Google.Cloud.Compute.V1/postgeneration.sh
  apis/Google.Cloud.Compute.V1/pregeneration.sh
Labels: cla: yes

#7542 Release Google.Cloud.AIPlatform.V1 version 1.1.0
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1.csproj
  apis/Google.Cloud.AIPlatform.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7545 Release Google.Cloud.Monitoring.V3 version 2.5.0
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3.csproj
  apis/Google.Cloud.Monitoring.V3/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7549 Release Google.Cloud.TextToSpeech.V1Beta1 version 1.0.0-beta03
  apis/Google.Cloud.TextToSpeech.V1Beta1/Google.Cloud.TextToSpeech.V1Beta1/Google.Cloud.TextToSpeech.V1Beta1.csproj
  apis/Google.Cloud.TextToSpeech.V1Beta1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7544 Release Google.Cloud.Dialogflow.V2 version 3.8.0
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2.csproj
  apis/Google.Cloud.Dialogflow.V2/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7548 Release Google.Cloud.TextToSpeech.V1 version 2.4.0
  apis/Google.Cloud.TextToSpeech.V1/Google.Cloud.TextToSpeech.V1/Google.Cloud.TextToSpeech.V1.csproj
  apis/Google.Cloud.TextToSpeech.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7550 Release Google.Cloud.Domains.V1 version 1.0.0
  apis/Google.Cloud.Domains.V1/.repo-metadata.json
  apis/Google.Cloud.Domains.V1/Google.Cloud.Domains.V1/Google.Cloud.Domains.V1.csproj
  apis/Google.Cloud.Domains.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7547 Release Google.Cloud.SecurityCenter.V1 version 2.9.0
  apis/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1.csproj
  apis/Google.Cloud.SecurityCenter.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7543 Release Google.Cloud.Dialogflow.Cx.V3 version 1.7.0
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3.csproj
  apis/Google.Cloud.Dialogflow.Cx.V3/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7561 feat: Add helper methods for converting Compute enum values
  apis/Google.Cloud.Compute.V1/Google.Cloud.Compute.V1.Tests/ComputeEnumHelpersTest.cs
  apis/Google.Cloud.Compute.V1/Google.Cloud.Compute.V1/ComputeEnumHelpers.cs
Labels: cla: yes

#7563 chore: Make the generation script more selective about gRPC service configs
  generateapis.sh
Labels: cla: yes

#7566 docs: Move manual emulator connection snippet
  docs/devsite-help/emulators.md
  tools/Google.Cloud.Docs.Snippets/EmulatorSnippets.cs
  tools/Google.Cloud.Docs.Snippets/FaqSnippets.cs
Labels: cla: yes

#7567 docs: Document the enum helpers for Compute
  apis/Google.Cloud.Compute.V1/Google.Cloud.Compute.V1.IntegrationTests/AcceptanceTest.cs
  apis/Google.Cloud.Compute.V1/Google.Cloud.Compute.V1.IntegrationTests/InstancesTest.cs
  apis/Google.Cloud.Compute.V1/Google.Cloud.Compute.V1.Snippets/EnumSnippets.cs
  apis/Google.Cloud.Compute.V1/docs/index.md
Labels: cla: yes

#7568 tests: Only return the first 10 elements in a list smoke test.
  tools/Google.Cloud.Tools.ReleaseManager/SmokeTest.cs
Labels: cla: yes
