Repository googleapis/google-cloud-dotnet, pull requests merged in 2021-10, with the labels that each got.

#7279 Fix Airflow smoke tests
  apis/Google.Cloud.Orchestration.Airflow.Service.V1/smoketests.json
Labels: cla: yes

#7283 tests(Storage): Remove the obsolete PAP "uspecified" value.
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.IntegrationTests/PublicAccessPreventionTest.cs
Labels: api: storage, cla: yes

#7284 chore: remove .cs -> .g.cs naming
  owl-bot-post-processor/main.sh
Labels: cla: yes

#7287 [apis/Google.Cloud.Video.Transcoder.V1] docs: clarify that project number is used as the canonical project identifier for job and job template names docs: fix broken link and code formatting feat: add support for allow_missing param on DELETE request
  apis/Google.Cloud.Video.Transcoder.V1/Google.Cloud.Video.Transcoder.V1.Snippets/TranscoderServiceClientSnippets.g.cs
  apis/Google.Cloud.Video.Transcoder.V1/Google.Cloud.Video.Transcoder.V1.Tests/TranscoderServiceClientTest.g.cs
  apis/Google.Cloud.Video.Transcoder.V1/Google.Cloud.Video.Transcoder.V1/Resources.g.cs
  apis/Google.Cloud.Video.Transcoder.V1/Google.Cloud.Video.Transcoder.V1/Services.g.cs
  apis/Google.Cloud.Video.Transcoder.V1/synth.metadata
Labels: cla: yes, context: full

#7288 chore: Add Google.LongRunning dependency to Google.Cloud.Compute.V1
  apis/Google.Cloud.Compute.V1/Google.Cloud.Compute.V1/Google.Cloud.Compute.V1.csproj
  apis/apis.json
Labels: cla: yes

#7409 [apis/Google.Cloud.Talent.V4Beta1] docs: fix docstring formatting
  apis/Google.Cloud.Talent.V4Beta1/Google.Cloud.Talent.V4Beta1/Job.g.cs
  apis/Google.Cloud.Talent.V4Beta1/Google.Cloud.Talent.V4Beta1/JobService.g.cs
  apis/Google.Cloud.Talent.V4Beta1/Google.Cloud.Talent.V4Beta1/ProfileService.g.cs
  apis/Google.Cloud.Talent.V4Beta1/synth.metadata
Labels: cla: yes, context: full

#7408 [apis/Google.Cloud.Talent.V4] docs: fix docstring formatting
  apis/Google.Cloud.Talent.V4/Google.Cloud.Talent.V4/Job.g.cs
  apis/Google.Cloud.Talent.V4/Google.Cloud.Talent.V4/JobService.g.cs
  apis/Google.Cloud.Talent.V4/synth.metadata
Labels: cla: yes, context: full

#7407 [apis/Google.Cloud.AIPlatform.V1] feat: Adds support for `google.protobuf.Value` pipeline parameters in the `parameter_values` field
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/PipelineJob.g.cs
  apis/Google.Cloud.AIPlatform.V1/synth.metadata
Labels: cla: yes, context: full
