Repository googleapis/google-cloud-dotnet, pull requests merged in 2021-05, with the labels that each got.

#6422 Fix ASP.NET template for Log4Net
  apis/Google.Cloud.Logging.Log4Net/Google.Cloud.Logging.Log4Net.Snippets/log4net-aspnet-template.xml
Labels: cla: yes

#6428 Release Google.Cloud.Bigtable.V2 version 2.2.0
  README.md
  apis/Google.Cloud.Bigtable.V2/Google.Cloud.Bigtable.V2.IntegrationTests/Google.Cloud.Bigtable.V2.IntegrationTests.csproj
  apis/Google.Cloud.Bigtable.V2/Google.Cloud.Bigtable.V2.Snippets/Google.Cloud.Bigtable.V2.Snippets.csproj
  apis/Google.Cloud.Bigtable.V2/Google.Cloud.Bigtable.V2.Tests/Google.Cloud.Bigtable.V2.Tests.csproj
  apis/Google.Cloud.Bigtable.V2/Google.Cloud.Bigtable.V2/Google.Cloud.Bigtable.V2.csproj
  apis/Google.Cloud.Bigtable.V2/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6429 Release Google.Cloud.DataCatalog.V1 version 1.2.0
  README.md
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1.csproj
  apis/Google.Cloud.DataCatalog.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6430 Release Firestore libraries
  README.md
  apis/Google.Cloud.Firestore.V1/Google.Cloud.Firestore.V1/Google.Cloud.Firestore.V1.csproj
  apis/Google.Cloud.Firestore.V1/docs/history.md
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore.IntegrationTests/Google.Cloud.Firestore.IntegrationTests.csproj
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore.Snippets/Google.Cloud.Firestore.Snippets.csproj
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore.Tests/Google.Cloud.Firestore.Tests.csproj
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore/Google.Cloud.Firestore.csproj
  apis/Google.Cloud.Firestore/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6431 Release Google.Cloud.Memcache.V1Beta2 version 1.0.0-beta04
  README.md
  apis/Google.Cloud.Memcache.V1Beta2/Google.Cloud.Memcache.V1Beta2/Google.Cloud.Memcache.V1Beta2.csproj
  apis/Google.Cloud.Memcache.V1Beta2/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6433 Release Google.Cloud.RecommendationEngine.V1Beta1 version 1.0.0-beta02
  README.md
  apis/Google.Cloud.RecommendationEngine.V1Beta1/Google.Cloud.RecommendationEngine.V1Beta1/Google.Cloud.RecommendationEngine.V1Beta1.csproj
  apis/Google.Cloud.RecommendationEngine.V1Beta1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6435 Release Google.Cloud.Functions.V1 version 1.1.0
  README.md
  apis/Google.Cloud.Functions.V1/Google.Cloud.Functions.V1/Google.Cloud.Functions.V1.csproj
  apis/Google.Cloud.Functions.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6434 Release Google.Cloud.Datastore.V1 version 3.2.0
  README.md
  V1
  apis/Google.Cloud.Datastore.V1/Google.Cloud.Datastore.V1/Google.Cloud.Datastore.V1.csproj
  apis/Google.Cloud.Datastore.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6436 Release Google.Cloud.Logging.V2 version 3.3.0
  README.md
  apis/Google.Cloud.Logging.V2/Google.Cloud.Logging.V2/Google.Cloud.Logging.V2.csproj
  apis/Google.Cloud.Logging.V2/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6438 Release Google.Cloud.BigQuery.V2 version 2.2.0
  README.md
  apis/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2.csproj
  apis/Google.Cloud.BigQuery.V2/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6440 [apis/Google.Cloud.Security.PrivateCA.V1] feat!: Make CertificateTemplate bools optional to indicate unset values.
  apis/Google.Cloud.Security.PrivateCA.V1/Google.Cloud.Security.PrivateCA.V1/Resources.g.cs
  apis/Google.Cloud.Security.PrivateCA.V1/synth.metadata
Labels: cla: yes, context: full

#6443 Remove codecov reporting
  .kokoro/runintegrationtests.sh
  README.md
  codecov.yml
  createcoveragereport.sh
Labels: cla: yes

#6446 [apis/Google.Cloud.SecurityCenter.V1] feat: add canonical_name and folder fields
  apis/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1.Snippets/SecurityCenterClientSnippets.g.cs
  apis/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1.Tests/SecurityCenterClientTest.g.cs
  apis/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1/Asset.g.cs
  apis/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1/AssetResourceNames.g.cs
  apis/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1/Finding.g.cs
  apis/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1/FindingResourceNames.g.cs
  apis/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1/Folder.g.cs
  apis/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1/NotificationConfig.g.cs
  apis/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1/NotificationMessage.g.cs
  apis/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1/OrganizationSettings.g.cs
  apis/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1/Resource.g.cs
  apis/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1/RunAssetDiscoveryResponse.g.cs
  apis/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1/SecurityCenterClient.g.cs
  apis/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1/SecurityMarks.g.cs
  apis/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1/SecurityMarksResourceNames.g.cs
  apis/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1/SecuritycenterService.g.cs
  apis/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1/SecuritycenterServiceGrpc.g.cs
  apis/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1/SecuritycenterServiceResourceNames.g.cs
  apis/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1/Source.g.cs
  apis/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1/SourceResourceNames.g.cs
  apis/Google.Cloud.SecurityCenter.V1/synth.metadata
Labels: cla: yes, context: full

#6447 [apis/Google.Cloud.SecurityCenter.V1P1Beta1] feat: add canonical_name and folder fields
  apis/Google.Cloud.SecurityCenter.V1P1Beta1/Google.Cloud.SecurityCenter.V1P1Beta1.Snippets/SecurityCenterClientSnippets.g.cs
  apis/Google.Cloud.SecurityCenter.V1P1Beta1/Google.Cloud.SecurityCenter.V1P1Beta1.Tests/SecurityCenterClientTest.g.cs
  apis/Google.Cloud.SecurityCenter.V1P1Beta1/Google.Cloud.SecurityCenter.V1P1Beta1/Asset.g.cs
  apis/Google.Cloud.SecurityCenter.V1P1Beta1/Google.Cloud.SecurityCenter.V1P1Beta1/AssetResourceNames.g.cs
  apis/Google.Cloud.SecurityCenter.V1P1Beta1/Google.Cloud.SecurityCenter.V1P1Beta1/Finding.g.cs
  apis/Google.Cloud.SecurityCenter.V1P1Beta1/Google.Cloud.SecurityCenter.V1P1Beta1/FindingResourceNames.g.cs
  apis/Google.Cloud.SecurityCenter.V1P1Beta1/Google.Cloud.SecurityCenter.V1P1Beta1/Folder.g.cs
  apis/Google.Cloud.SecurityCenter.V1P1Beta1/Google.Cloud.SecurityCenter.V1P1Beta1/NotificationConfig.g.cs
  apis/Google.Cloud.SecurityCenter.V1P1Beta1/Google.Cloud.SecurityCenter.V1P1Beta1/NotificationMessage.g.cs
  apis/Google.Cloud.SecurityCenter.V1P1Beta1/Google.Cloud.SecurityCenter.V1P1Beta1/OrganizationSettings.g.cs
  apis/Google.Cloud.SecurityCenter.V1P1Beta1/Google.Cloud.SecurityCenter.V1P1Beta1/Resource.g.cs
  apis/Google.Cloud.SecurityCenter.V1P1Beta1/Google.Cloud.SecurityCenter.V1P1Beta1/RunAssetDiscoveryResponse.g.cs
  apis/Google.Cloud.SecurityCenter.V1P1Beta1/Google.Cloud.SecurityCenter.V1P1Beta1/SecurityCenterClient.g.cs
  apis/Google.Cloud.SecurityCenter.V1P1Beta1/Google.Cloud.SecurityCenter.V1P1Beta1/SecurityMarks.g.cs
  apis/Google.Cloud.SecurityCenter.V1P1Beta1/Google.Cloud.SecurityCenter.V1P1Beta1/SecurityMarksResourceNames.g.cs
  apis/Google.Cloud.SecurityCenter.V1P1Beta1/Google.Cloud.SecurityCenter.V1P1Beta1/SecuritycenterService.g.cs
  apis/Google.Cloud.SecurityCenter.V1P1Beta1/Google.Cloud.SecurityCenter.V1P1Beta1/SecuritycenterServiceGrpc.g.cs
  apis/Google.Cloud.SecurityCenter.V1P1Beta1/Google.Cloud.SecurityCenter.V1P1Beta1/SecuritycenterServiceResourceNames.g.cs
  apis/Google.Cloud.SecurityCenter.V1P1Beta1/Google.Cloud.SecurityCenter.V1P1Beta1/Source.g.cs
  apis/Google.Cloud.SecurityCenter.V1P1Beta1/Google.Cloud.SecurityCenter.V1P1Beta1/SourceResourceNames.g.cs
  apis/Google.Cloud.SecurityCenter.V1P1Beta1/synth.metadata
Labels: cla: yes, context: full

#6448 Release Workflows libraries version 1.0.0
  README.md
  apis/Google.Cloud.Workflows.Common.V1/.repo-metadata.json
  apis/Google.Cloud.Workflows.Common.V1/Google.Cloud.Workflows.Common.V1/Google.Cloud.Workflows.Common.V1.csproj
  apis/Google.Cloud.Workflows.Executions.V1/.repo-metadata.json
  apis/Google.Cloud.Workflows.Executions.V1/Google.Cloud.Workflows.Executions.V1/Google.Cloud.Workflows.Executions.V1.csproj
  apis/Google.Cloud.Workflows.Executions.V1/docs/history.md
  apis/Google.Cloud.Workflows.V1/.repo-metadata.json
  apis/Google.Cloud.Workflows.V1/Google.Cloud.Workflows.V1/Google.Cloud.Workflows.V1.csproj
  apis/Google.Cloud.Workflows.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6451 [apis/ServiceDirectory] fix!: Fixing PHP, Ruby and C# package names for the CloudDMS API. This is a breaking change for the above languages.
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#6452 [apis/Google.Cloud.BinaryAuthorization.V1Beta1] feat: Publish Binary Authorization ContinuousValidationEvent proto.
  apis/Google.Cloud.BinaryAuthorization.V1Beta1/Google.Cloud.BinaryAuthorization.V1Beta1/ContinuousValidationLogging.g.cs
  apis/Google.Cloud.BinaryAuthorization.V1Beta1/synth.metadata
Labels: cla: yes, context: full

#6453 [CHANGE ME] Re-generated apis/ServiceDirectory to pick up changes in the API or client library generator.
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#6455 Remove AppVeyor build
  README.md
  appveyor.sh
  appveyor.yml
Labels: cla: yes

#6457 [apis/Google.Cloud.DocumentAI.V1] feat: Use non-regionalized default host name for documentai.googleapis.com
  apis/Google.Cloud.DocumentAI.V1/Google.Cloud.DocumentAI.V1/DocumentProcessorService.g.cs
  apis/Google.Cloud.DocumentAI.V1/Google.Cloud.DocumentAI.V1/DocumentProcessorServiceClient.g.cs
  apis/Google.Cloud.DocumentAI.V1/synth.metadata
Labels: cla: yes, context: full

#6456 test: remove specific tests for binding NUMERIC
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.IntegrationTests/BindingTests.cs
Labels: api: spanner, cla: yes

#6458 tests: add tests for instances
  apis/Google.Cloud.Compute.V1/Google.Cloud.Compute.V1.IntegrationTests/ComputeFixture.cs
  apis/Google.Cloud.Compute.V1/Google.Cloud.Compute.V1.IntegrationTests/InstancesTest.cs
Labels: cla: yes

#6460 First part of a link canonicalizer
  docs/Google.Cloud.DocTools.sln
  tools/.gcloudignore
  tools/Google.Cloud.Tools.CanonicalLinkFunction/Function.cs
  tools/Google.Cloud.Tools.CanonicalLinkFunction/Google.Cloud.Tools.CanonicalLinkFunction.csproj
  tools/Google.Cloud.Tools.GenerateCanonicalLinks/Canonicalizer.cs
  tools/Google.Cloud.Tools.GenerateCanonicalLinks/Google.Cloud.Tools.GenerateCanonicalLinks.csproj
  tools/Google.Cloud.Tools.GenerateCanonicalLinks/Program.cs
Labels: cla: yes

#6462 Improvements to Compute integration test polling
  apis/Google.Cloud.Compute.V1/Google.Cloud.Compute.V1.IntegrationTests/AcceptanceTest.cs
  apis/Google.Cloud.Compute.V1/Google.Cloud.Compute.V1.IntegrationTests/ComputeFixture.cs
  apis/Google.Cloud.Compute.V1/Google.Cloud.Compute.V1.IntegrationTests/InstancesTest.cs
Labels: cla: yes

#6463 Release Google.Cloud.Compute.V1 version 1.0.0-alpha01
  README.md
  apis/Google.Cloud.Compute.V1/.repo-metadata.json
  apis/Google.Cloud.Compute.V1/Google.Cloud.Compute.V1/Google.Cloud.Compute.V1.csproj
  apis/Google.Cloud.Compute.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6464 [apis/ServiceDirectory] feat: publish alertcenter/v1beta API and Bazel targets
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#6465 test(spanner): remove region tags from tests
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.IntegrationTests/BindingTests.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.IntegrationTests/ChunkingTests.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.IntegrationTests/DmlTests.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.IntegrationTests/QueryOptionsTests.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.IntegrationTests/ReadTests.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.IntegrationTests/StructParameterTests.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.IntegrationTests/TransactionTests.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.IntegrationTests/WriteTests.cs
Labels: api: spanner, cla: yes

#6467 [apis/Google.Cloud.Dialogflow.V2] feat: added location-aware HTTP path binding for ListIntents
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/Intent.g.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/IntentsClient.g.cs
  apis/Google.Cloud.Dialogflow.V2/synth.metadata
Labels: cla: yes, context: full

#6468 [apis/Google.Cloud.SecretManager.V1] feat: Etags in Secret Manager
  apis/Google.Cloud.SecretManager.V1/Google.Cloud.SecretManager.V1.Snippets/SecretManagerServiceClientSnippets.g.cs
  apis/Google.Cloud.SecretManager.V1/Google.Cloud.SecretManager.V1.Tests/SecretManagerServiceClientTest.g.cs
  apis/Google.Cloud.SecretManager.V1/Google.Cloud.SecretManager.V1/Resources.g.cs
  apis/Google.Cloud.SecretManager.V1/Google.Cloud.SecretManager.V1/SecretManagerServiceClient.g.cs
  apis/Google.Cloud.SecretManager.V1/Google.Cloud.SecretManager.V1/Service.g.cs
  apis/Google.Cloud.SecretManager.V1/Google.Cloud.SecretManager.V1/ServiceGrpc.g.cs
  apis/Google.Cloud.SecretManager.V1/synth.metadata
Labels: automerge, cla: yes, context: full

#6466 test: add tests for all data types in GetSchemaTableTests
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.IntegrationTests/GetSchemaTableTests.cs
Labels: cla: yes

#6471 [apis/Google.Cloud.BigQuery.Storage.V1] feat: Add ZSTD compression as an option for Arrow.
  apis/Google.Cloud.BigQuery.Storage.V1/Google.Cloud.BigQuery.Storage.V1/Arrow.g.cs
  apis/Google.Cloud.BigQuery.Storage.V1/Google.Cloud.BigQuery.Storage.V1/Stream.g.cs
  apis/Google.Cloud.BigQuery.Storage.V1/synth.metadata
Labels: cla: yes, context: full

#6358 feat(spanner): add option to return read timestamp
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.IntegrationTests/TransactionTests.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.Tests/TimestampBoundTests.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/SpannerCommand.ExecutableCommand.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/SpannerDataReader.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/SpannerTransaction.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/TimestampBound.cs
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/PooledSession.cs
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/SessionPool.DetachedSessionPool.cs
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/SessionPool.TargetedSessionPool.cs
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/SessionPool.cs
Labels: api: spanner, cla: yes

#6472 Release Spanner libraries version 3.8.0
  README.md
  apis/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1.csproj
  apis/Google.Cloud.Spanner.Admin.Instance.V1/Google.Cloud.Spanner.Admin.Instance.V1/Google.Cloud.Spanner.Admin.Instance.V1.csproj
  apis/Google.Cloud.Spanner.Common.V1/Google.Cloud.Spanner.Common.V1/Google.Cloud.Spanner.Common.V1.csproj
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.csproj
  apis/Google.Cloud.Spanner.Data/docs/history.md
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1.csproj
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6475 [apis/Google.Cloud.Dialogflow.Cx.V3] docs: clarified documentation for security settings docs: clarified documentation for session parameters
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/SecuritySettings.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Session.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/synth.metadata
Labels: cla: yes, context: full

#6478 Rename "User Guides" to "Overview" for DevSite
  tools/Google.Cloud.Tools.PostProcessDevSite/Program.cs
Labels: cla: yes

#6474 First proper pass at link canonicalization
  docs/Google.Cloud.DocTools.sln
  tools/Google.Cloud.Tools.GenerateCanonicalLinks.Tests/CanonicalizerTest.cs
  tools/Google.Cloud.Tools.GenerateCanonicalLinks.Tests/Google.Cloud.Tools.GenerateCanonicalLinks.Tests.csproj
  tools/Google.Cloud.Tools.GenerateCanonicalLinks/Canonicalizer.cs
Labels: cla: yes

#6479 Fix Storage integration test usage of deprecated API
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.IntegrationTests/NotificationsTest.cs
Labels: cla: yes

#6480 Release Google.LongRunning version 2.2.0
  README.md
  apis/Google.LongRunning/Google.LongRunning.Snippets/Google.LongRunning.Snippets.csproj
  apis/Google.LongRunning/Google.LongRunning.Tests/Google.LongRunning.Tests.csproj
  apis/Google.LongRunning/Google.LongRunning/Google.LongRunning.csproj
  apis/Google.LongRunning/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6483 Namespace options for PrivateCatalog and ServiceUsage
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#6485 Namespace and description changes to service index
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#6484 [apis/Google.Apps.Script.Type] fix: add outer classname for addon_widget_set proto for java
  apis/Google.Apps.Script.Type/Google.Apps.Script.Type/AddonWidgetSet.cs
  apis/Google.Apps.Script.Type/synth.metadata
Labels: cla: yes, context: full

#6487 [apis/ServiceDirectory] docs: changes product name to 'Vertex AI' docs: removes tinyurl links
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#6490 [apis/Google.Cloud.Dialogflow.V2] feat: added a field in the query result to indicate whether slot filling is cancelled.
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/Session.g.cs
  apis/Google.Cloud.Dialogflow.V2/synth.metadata
Labels: cla: yes, context: full

#6491 [apis/Google.Cloud.OsConfig.V1Alpha] feat: OSConfig: add ExecResourceOutput and per step error message.
  apis/Google.Cloud.OsConfig.V1Alpha/Google.Cloud.OsConfig.V1Alpha/ConfigCommon.g.cs
  apis/Google.Cloud.OsConfig.V1Alpha/Google.Cloud.OsConfig.V1Alpha/Inventory.g.cs
  apis/Google.Cloud.OsConfig.V1Alpha/Google.Cloud.OsConfig.V1Alpha/OsConfigZonalServiceClient.g.cs
  apis/Google.Cloud.OsConfig.V1Alpha/Google.Cloud.OsConfig.V1Alpha/OsPolicy.g.cs
  apis/Google.Cloud.OsConfig.V1Alpha/Google.Cloud.OsConfig.V1Alpha/OsPolicyAssignments.g.cs
  apis/Google.Cloud.OsConfig.V1Alpha/Google.Cloud.OsConfig.V1Alpha/Vulnerability.g.cs
  apis/Google.Cloud.OsConfig.V1Alpha/synth.metadata
Labels: cla: yes, context: full

#6493 Release Google.Analytics.Data.V1Alpha version 1.0.0-alpha05
  README.md
  apis/Google.Analytics.Data.V1Alpha/Google.Analytics.Data.V1Alpha/Google.Analytics.Data.V1Alpha.csproj
  apis/Google.Analytics.Data.V1Alpha/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6495 Release Google.Cloud.ArtifactRegistry.V1Beta2 version 1.0.0-beta02
  README.md
  apis/Google.Cloud.ArtifactRegistry.V1Beta2/Google.Cloud.ArtifactRegistry.V1Beta2/Google.Cloud.ArtifactRegistry.V1Beta2.csproj
  apis/Google.Cloud.ArtifactRegistry.V1Beta2/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6496 Release Google.Cloud.AutoML.V1 version 2.2.0
  README.md
  apis/Google.Cloud.AutoML.V1/Google.Cloud.AutoML.V1/Google.Cloud.AutoML.V1.csproj
  apis/Google.Cloud.AutoML.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6498 Release Google.Cloud.BigQuery.Connection.V1 version 1.2.0
  README.md
  apis/Google.Cloud.BigQuery.Connection.V1/Google.Cloud.BigQuery.Connection.V1/Google.Cloud.BigQuery.Connection.V1.csproj
  apis/Google.Cloud.BigQuery.Connection.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6497 [CHANGE ME] Re-generated apis/ServiceDirectory to pick up changes in the API or client library generator.
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#6499 Release Google.Cloud.BigQuery.DataTransfer.V1 version 3.1.0
  README.md
  apis/Google.Cloud.BigQuery.DataTransfer.V1/Google.Cloud.BigQuery.DataTransfer.V1/Google.Cloud.BigQuery.DataTransfer.V1.csproj
  apis/Google.Cloud.BigQuery.DataTransfer.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6500 Release Google.Cloud.BigQuery.Reservation.V1 version 1.2.0
  README.md
  apis/Google.Cloud.BigQuery.Reservation.V1/Google.Cloud.BigQuery.Reservation.V1/Google.Cloud.BigQuery.Reservation.V1.csproj
  apis/Google.Cloud.BigQuery.Reservation.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6501 Release Google.Cloud.Bigtable.Common.V2 version 2.1.0
  README.md
  apis/Google.Cloud.Bigtable.Common.V2/Google.Cloud.Bigtable.Common.V2/Google.Cloud.Bigtable.Common.V2.csproj
  apis/Google.Cloud.Bigtable.Common.V2/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6502 Release Google.Cloud.Billing.V1 version 2.2.0
  README.md
  apis/Google.Cloud.Billing.V1/Google.Cloud.Billing.V1/Google.Cloud.Billing.V1.csproj
  apis/Google.Cloud.Billing.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6503 Release Google.Cloud.Container.V1 version 2.3.0
  README.md
  apis/Google.Cloud.Container.V1/Google.Cloud.Container.V1/Google.Cloud.Container.V1.csproj
  apis/Google.Cloud.Container.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6504 Release Google.Cloud.DataLabeling.V1Beta1 version 1.0.0-beta02
  README.md
  apis/Google.Cloud.DataLabeling.V1Beta1/Google.Cloud.DataLabeling.V1Beta1/Google.Cloud.DataLabeling.V1Beta1.csproj
  apis/Google.Cloud.DataLabeling.V1Beta1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6505 Release Google.Cloud.DataQnA.V1Alpha version 1.0.0-alpha02
  README.md
  apis/Google.Cloud.DataQnA.V1Alpha/Google.Cloud.DataQnA.V1Alpha/Google.Cloud.DataQnA.V1Alpha.csproj
  apis/Google.Cloud.DataQnA.V1Alpha/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6506 Release Google.Cloud.Debugger.V2 version 2.2.0
  README.md
  apis/Google.Cloud.Debugger.V2/Google.Cloud.Debugger.V2/Google.Cloud.Debugger.V2.csproj
  apis/Google.Cloud.Debugger.V2/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6507 Release Google.Cloud.DevTools.Common version 2.1.0
  README.md
  apis/Google.Cloud.DevTools.Common/Google.Cloud.DevTools.Common/Google.Cloud.DevTools.Common.csproj
  apis/Google.Cloud.DevTools.Common/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6508 Release container analysis APIs version 2.2.0
  README.md
  apis/Google.Cloud.DevTools.ContainerAnalysis.V1/Google.Cloud.DevTools.ContainerAnalysis.V1/Google.Cloud.DevTools.ContainerAnalysis.V1.csproj
  apis/Google.Cloud.DevTools.ContainerAnalysis.V1/docs/history.md
  apis/Grafeas.V1/Grafeas.V1/Grafeas.V1.csproj
  apis/Grafeas.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6510 Release Google.Cloud.Dlp.V2 version 3.2.0
  README.md
  apis/Google.Cloud.Dlp.V2/Google.Cloud.Dlp.V2/Google.Cloud.Dlp.V2.csproj
  apis/Google.Cloud.Dlp.V2/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6512 [apis/Google.Analytics.Admin.V1Alpha] feat: add `GetMeasurementProtocolSecret`, `ListMeasurementProtocolSecrets`, `CreateMeasurementProtocolSecret`, `DeleteMeasurementProtocolSecret`, `UpdateMeasurementProtocolSecret` methods to the API feat: add `Ge
  apis/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha.Snippets/AnalyticsAdminServiceClientSnippets.g.cs
  apis/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha.Tests/AnalyticsAdminServiceClientTest.g.cs
  apis/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha/AnalyticsAdmin.g.cs
  apis/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha/AnalyticsAdminGrpc.g.cs
  apis/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha/AnalyticsAdminResourceNames.g.cs
  apis/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha/AnalyticsAdminServiceClient.g.cs
  apis/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha/Resources.g.cs
  apis/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha/ResourcesResourceNames.g.cs
  apis/Google.Analytics.Admin.V1Alpha/gapic_metadata.json
  apis/Google.Analytics.Admin.V1Alpha/synth.metadata
Labels: cla: yes, context: full

#6513 [apis/Google.Cloud.Asset.V1] feat: add Cloud Asset List API, add access time as condition context in request and evaluation value in response for Cloud Asset AnalyzeIamPolicy API, add more info (folders, organizations, kms_key, create_time, update_ti
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1.Snippets/AssetServiceClientSnippets.g.cs
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1/AssetService.g.cs
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1/AssetServiceClient.g.cs
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1/AssetServiceGrpc.g.cs
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1/AssetServiceResourceNames.g.cs
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1/Assets.g.cs
  apis/Google.Cloud.Asset.V1/gapic_metadata.json
  apis/Google.Cloud.Asset.V1/synth.metadata
Labels: cla: yes, context: full

#6514 [apis/Google.Cloud.Dialogflow.Cx.V3] feat: added API for running continuous test
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3.Snippets/EnvironmentsClientSnippets.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Environment.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/EnvironmentGrpc.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/EnvironmentResourceNames.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/EnvironmentsClient.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/gapic_metadata.json
  apis/Google.Cloud.Dialogflow.Cx.V3/synth.metadata
Labels: cla: yes, context: full

#6515 [CHANGE ME] Re-generated apis/ServiceDirectory to pick up changes in the API or client library generator.
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#6516 Release Google.Cloud.DocumentAI.V1Beta2 version 1.0.0-beta03
  README.md
  apis/Google.Cloud.DocumentAI.V1Beta2/Google.Cloud.DocumentAI.V1Beta2/Google.Cloud.DocumentAI.V1Beta2.csproj
  apis/Google.Cloud.DocumentAI.V1Beta2/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6517 Release Google.Cloud.Domains.V1Beta1 version 1.0.0-beta02
  README.md
  apis/Google.Cloud.Domains.V1Beta1/Google.Cloud.Domains.V1Beta1/Google.Cloud.Domains.V1Beta1.csproj
  apis/Google.Cloud.Domains.V1Beta1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6518 Release Google.Cloud.Firestore.Admin.V1 version 2.2.0
  README.md
  apis/Google.Cloud.Firestore.Admin.V1/Google.Cloud.Firestore.Admin.V1/Google.Cloud.Firestore.Admin.V1.csproj
  apis/Google.Cloud.Firestore.Admin.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6519 Release Google.Cloud.Gaming.V1 version 1.1.0
  README.md
  apis/Google.Cloud.Gaming.V1/Google.Cloud.Gaming.V1/Google.Cloud.Gaming.V1.csproj
  apis/Google.Cloud.Gaming.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6520 Release Google.Cloud.Gaming.V1Beta version 1.0.0-beta07
  README.md
  apis/Google.Cloud.Gaming.V1Beta/Google.Cloud.Gaming.V1Beta/Google.Cloud.Gaming.V1Beta.csproj
  apis/Google.Cloud.Gaming.V1Beta/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6521 Release Google.Cloud.Iam.Credentials.V1 version 1.1.0
  README.md
  apis/Google.Cloud.Iam.Credentials.V1/Google.Cloud.Iam.Credentials.V1/Google.Cloud.Iam.Credentials.V1.csproj
  apis/Google.Cloud.Iam.Credentials.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6523 Release Google.Cloud.Iam.V1 version 2.2.0
  README.md
  apis/Google.Cloud.Iam.V1/Google.Cloud.Iam.V1/Google.Cloud.Iam.V1.csproj
  apis/Google.Cloud.Iam.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6524 Release Google.Cloud.Language.V1 version 2.2.0
  README.md
  apis/Google.Cloud.Language.V1/Google.Cloud.Language.V1/Google.Cloud.Language.V1.csproj
  apis/Google.Cloud.Language.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6525 Release Google.Cloud.Memcache.V1 version 1.1.0
  README.md
  apis/Google.Cloud.Memcache.V1/Google.Cloud.Memcache.V1/Google.Cloud.Memcache.V1.csproj
  apis/Google.Cloud.Memcache.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6526 Stop publishing to GitHub pages on release
  .kokoro/release.sh
  buildrelease.sh
Labels: cla: yes

#6527 Release Google.Cloud.Logging.Log4Net version 3.3.0
  README.md
  apis/Google.Cloud.Logging.Log4Net/Google.Cloud.Logging.Log4Net.IntegrationTests/Google.Cloud.Logging.Log4Net.IntegrationTests.csproj
  apis/Google.Cloud.Logging.Log4Net/Google.Cloud.Logging.Log4Net.Snippets/Google.Cloud.Logging.Log4Net.Snippets.csproj
  apis/Google.Cloud.Logging.Log4Net/Google.Cloud.Logging.Log4Net.Tests/Google.Cloud.Logging.Log4Net.Tests.csproj
  apis/Google.Cloud.Logging.Log4Net/Google.Cloud.Logging.Log4Net/Google.Cloud.Logging.Log4Net.csproj
  apis/Google.Cloud.Logging.Log4Net/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6528 Release Google.Cloud.Logging.Type version 3.3.0
  README.md
  apis/Google.Cloud.Logging.Type/Google.Cloud.Logging.Type/Google.Cloud.Logging.Type.csproj
  apis/Google.Cloud.Logging.Type/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6529 Release Google.Cloud.NetworkConnectivity.V1Alpha1 version 1.0.0-alpha02
  README.md
  apis/Google.Cloud.NetworkConnectivity.V1Alpha1/Google.Cloud.NetworkConnectivity.V1Alpha1/Google.Cloud.NetworkConnectivity.V1Alpha1.csproj
  apis/Google.Cloud.NetworkConnectivity.V1Alpha1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6530 Release Google.Cloud.Notebooks.V1Beta1 version 1.0.0-beta03
  README.md
  apis/Google.Cloud.Notebooks.V1Beta1/Google.Cloud.Notebooks.V1Beta1/Google.Cloud.Notebooks.V1Beta1.csproj
  apis/Google.Cloud.Notebooks.V1Beta1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6531 Release Google.Cloud.OrgPolicy.V1 version 2.2.0
  README.md
  apis/Google.Cloud.OrgPolicy.V1/Google.Cloud.OrgPolicy.V1/Google.Cloud.OrgPolicy.V1.csproj
  apis/Google.Cloud.OrgPolicy.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6532 Release Google.Cloud.OsConfig.V1 version 1.3.0
  README.md
  apis/Google.Cloud.OsConfig.V1/Google.Cloud.OsConfig.V1/Google.Cloud.OsConfig.V1.csproj
  apis/Google.Cloud.OsConfig.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6533 Release dependency update for OsLogin libraries
  README.md
  apis/Google.Cloud.OsLogin.Common/Google.Cloud.OsLogin.Common/Google.Cloud.OsLogin.Common.csproj
  apis/Google.Cloud.OsLogin.V1/Google.Cloud.OsLogin.V1/Google.Cloud.OsLogin.V1.csproj
  apis/Google.Cloud.OsLogin.V1/docs/history.md
  apis/Google.Cloud.OsLogin.V1Beta/Google.Cloud.OsLogin.V1Beta/Google.Cloud.OsLogin.V1Beta.csproj
  apis/Google.Cloud.OsLogin.V1Beta/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6534 Release Google.Cloud.PhishingProtection.V1Beta1 version 1.0.0-beta04
  README.md
  apis/Google.Cloud.PhishingProtection.V1Beta1/Google.Cloud.PhishingProtection.V1Beta1/Google.Cloud.PhishingProtection.V1Beta1.csproj
  apis/Google.Cloud.PhishingProtection.V1Beta1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6535 Release Google.Cloud.PolicyTroubleshooter.V1 version 1.1.0
  README.md
  apis/Google.Cloud.PolicyTroubleshooter.V1/Google.Cloud.PolicyTroubleshooter.V1/Google.Cloud.PolicyTroubleshooter.V1.csproj
  apis/Google.Cloud.PolicyTroubleshooter.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6537 Release Google.Cloud.PubSub.V1 version 2.5.0
  README.md
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1.csproj
  apis/Google.Cloud.PubSub.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6538 Release Google.Cloud.RecaptchaEnterprise.V1 version 1.2.0
  README.md
  apis/Google.Cloud.RecaptchaEnterprise.V1/Google.Cloud.RecaptchaEnterprise.V1/Google.Cloud.RecaptchaEnterprise.V1.csproj
  apis/Google.Cloud.RecaptchaEnterprise.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6539 Release Google.Cloud.RecaptchaEnterprise.V1Beta1 version 1.0.0-beta04
  README.md
  apis/Google.Cloud.RecaptchaEnterprise.V1Beta1/Google.Cloud.RecaptchaEnterprise.V1Beta1/Google.Cloud.RecaptchaEnterprise.V1Beta1.csproj
  apis/Google.Cloud.RecaptchaEnterprise.V1Beta1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6540 Release Google.Cloud.Redis.V1 version 2.2.0
  README.md
  apis/Google.Cloud.Redis.V1/Google.Cloud.Redis.V1/Google.Cloud.Redis.V1.csproj
  apis/Google.Cloud.Redis.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6541 Release Google.Cloud.Redis.V1Beta1 version 2.0.0-beta04
  README.md
  apis/Google.Cloud.Redis.V1Beta1/Google.Cloud.Redis.V1Beta1/Google.Cloud.Redis.V1Beta1.csproj
  apis/Google.Cloud.Redis.V1Beta1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6542 Release Google.Cloud.Scheduler.V1 version 2.2.0
  README.md
  apis/Google.Cloud.Scheduler.V1/Google.Cloud.Scheduler.V1/Google.Cloud.Scheduler.V1.csproj
  apis/Google.Cloud.Scheduler.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6543 Release Google.Cloud.SecretManager.V1Beta1 version 2.0.0-beta04
  README.md
  apis/Google.Cloud.SecretManager.V1Beta1/Google.Cloud.SecretManager.V1Beta1/Google.Cloud.SecretManager.V1Beta1.csproj
  apis/Google.Cloud.SecretManager.V1Beta1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6544 Release Google.Cloud.Security.PrivateCA.V1Beta1 version 1.0.0-beta02
  README.md
  apis/Google.Cloud.Security.PrivateCA.V1Beta1/Google.Cloud.Security.PrivateCA.V1Beta1/Google.Cloud.Security.PrivateCA.V1Beta1.csproj
  apis/Google.Cloud.Security.PrivateCA.V1Beta1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6545 Release Google.Cloud.SecurityCenter.Settings.V1Beta1 version 1.0.0-beta03
  README.md
  apis/Google.Cloud.SecurityCenter.Settings.V1Beta1/Google.Cloud.SecurityCenter.Settings.V1Beta1/Google.Cloud.SecurityCenter.Settings.V1Beta1.csproj
  apis/Google.Cloud.SecurityCenter.Settings.V1Beta1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6546 Release Google.Cloud.SecurityCenter.V1 version 2.3.0
  README.md
  apis/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1.csproj
  apis/Google.Cloud.SecurityCenter.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6547 Release Google.Cloud.SecurityCenter.V1P1Beta1 version 2.0.0-beta05
  README.md
  apis/Google.Cloud.SecurityCenter.V1P1Beta1/Google.Cloud.SecurityCenter.V1P1Beta1/Google.Cloud.SecurityCenter.V1P1Beta1.csproj
  apis/Google.Cloud.SecurityCenter.V1P1Beta1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6548 Release Google.Cloud.ServiceDirectory.V1 version 1.1.0
  README.md
  apis/Google.Cloud.ServiceDirectory.V1/Google.Cloud.ServiceDirectory.V1/Google.Cloud.ServiceDirectory.V1.csproj
  apis/Google.Cloud.ServiceDirectory.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6549 Release Google.Cloud.ServiceDirectory.V1Beta1 version 1.0.0-beta04
  README.md
  apis/Google.Cloud.ServiceDirectory.V1Beta1/Google.Cloud.ServiceDirectory.V1Beta1/Google.Cloud.ServiceDirectory.V1Beta1.csproj
  apis/Google.Cloud.ServiceDirectory.V1Beta1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6550 Release Google.Cloud.Speech.V1 version 2.2.0
  README.md
  apis/Google.Cloud.Speech.V1/Google.Cloud.Speech.V1/Google.Cloud.Speech.V1.csproj
  apis/Google.Cloud.Speech.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6551 Release Google.Cloud.Talent.V4 version 1.1.0
  README.md
  apis/Google.Cloud.Talent.V4/Google.Cloud.Talent.V4/Google.Cloud.Talent.V4.csproj
  apis/Google.Cloud.Talent.V4/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6552 Release Google.Cloud.Storage.V1 version 3.5.0
  README.md
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.IntegrationTests/Google.Cloud.Storage.V1.IntegrationTests.csproj
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.Snippets/Google.Cloud.Storage.V1.Snippets.csproj
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.Tests/Google.Cloud.Storage.V1.Tests.csproj
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.csproj
  apis/Google.Cloud.Storage.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6554 Release Google.Cloud.Tasks.V2 version 2.2.0
  README.md
  apis/Google.Cloud.Tasks.V2/Google.Cloud.Tasks.V2/Google.Cloud.Tasks.V2.csproj
  apis/Google.Cloud.Tasks.V2/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6555 Release Google.Cloud.Tasks.V2Beta3 version 2.0.0-beta05
  README.md
  apis/Google.Cloud.Tasks.V2Beta3/Google.Cloud.Tasks.V2Beta3/Google.Cloud.Tasks.V2Beta3.csproj
  apis/Google.Cloud.Tasks.V2Beta3/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6556 Release Google.Cloud.TextToSpeech.V1 version 2.2.0
  README.md
  apis/Google.Cloud.TextToSpeech.V1/Google.Cloud.TextToSpeech.V1/Google.Cloud.TextToSpeech.V1.csproj
  apis/Google.Cloud.TextToSpeech.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6557 Release Google.Cloud.Trace.V1 version 2.2.0
  README.md
  apis/Google.Cloud.Trace.V1/Google.Cloud.Trace.V1/Google.Cloud.Trace.V1.csproj
  apis/Google.Cloud.Trace.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6558 Release Google.Cloud.Trace.V2 version 2.2.0
  README.md
  apis/Google.Cloud.Trace.V2/Google.Cloud.Trace.V2/Google.Cloud.Trace.V2.csproj
  apis/Google.Cloud.Trace.V2/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6559 Release Google.Cloud.Translate.V3 version 2.2.0
  README.md
  apis/Google.Cloud.Translate.V3/Google.Cloud.Translate.V3/Google.Cloud.Translate.V3.csproj
  apis/Google.Cloud.Translate.V3/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6560 Release Google.Cloud.Translation.V2 version 2.1.0
  README.md
  apis/Google.Cloud.Translation.V2/Google.Cloud.Translation.V2/Google.Cloud.Translation.V2.csproj
  apis/Google.Cloud.Translation.V2/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6561 Release Google.Cloud.Video.Transcoder.V1Beta1 version 1.0.0-beta02
  README.md
  apis/Google.Cloud.Video.Transcoder.V1Beta1/Google.Cloud.Video.Transcoder.V1Beta1/Google.Cloud.Video.Transcoder.V1Beta1.csproj
  apis/Google.Cloud.Video.Transcoder.V1Beta1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6562 Release Google.Cloud.WebRisk.V1 version 1.2.0
  README.md
  apis/Google.Cloud.WebRisk.V1/Google.Cloud.WebRisk.V1/Google.Cloud.WebRisk.V1.csproj
  apis/Google.Cloud.WebRisk.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6563 Release Google.Cloud.WebRisk.V1Beta1 version 2.0.0-beta04
  README.md
  apis/Google.Cloud.WebRisk.V1Beta1/Google.Cloud.WebRisk.V1Beta1/Google.Cloud.WebRisk.V1Beta1.csproj
  apis/Google.Cloud.WebRisk.V1Beta1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6564 Release Google.Cloud.WebSecurityScanner.V1 version 1.1.0
  README.md
  apis/Google.Cloud.WebSecurityScanner.V1/Google.Cloud.WebSecurityScanner.V1/Google.Cloud.WebSecurityScanner.V1.csproj
  apis/Google.Cloud.WebSecurityScanner.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6565 Release Workflows V1Beta libraries version 1.0.0-beta02
  README.md
  apis/Google.Cloud.Workflows.Common.V1Beta/Google.Cloud.Workflows.Common.V1Beta/Google.Cloud.Workflows.Common.V1Beta.csproj
  apis/Google.Cloud.Workflows.Executions.V1Beta/Google.Cloud.Workflows.Executions.V1Beta/Google.Cloud.Workflows.Executions.V1Beta.csproj
  apis/Google.Cloud.Workflows.Executions.V1Beta/docs/history.md
  apis/Google.Cloud.Workflows.V1Beta/Google.Cloud.Workflows.V1Beta/Google.Cloud.Workflows.V1Beta.csproj
  apis/Google.Cloud.Workflows.V1Beta/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6566 Release Google.Identity.AccessContextManager.Type version 1.1.0
  README.md
  apis/Google.Identity.AccessContextManager.Type/Google.Identity.AccessContextManager.Type/Google.Identity.AccessContextManager.Type.csproj
  apis/Google.Identity.AccessContextManager.Type/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6567 Release Google.Identity.AccessContextManager.V1 version 1.2.0
  README.md
  apis/Google.Identity.AccessContextManager.V1/Google.Identity.AccessContextManager.V1/Google.Identity.AccessContextManager.V1.csproj
  apis/Google.Identity.AccessContextManager.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6571 Release Google.Cloud.Debugger.V2 version 2.3.0
  README.md
  apis/Google.Cloud.Debugger.V2/Google.Cloud.Debugger.V2/Google.Cloud.Debugger.V2.csproj
  apis/Google.Cloud.Debugger.V2/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6572 [apis/ServiceDirectory] feat: add C#/php namespaces and ruby package.
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#6573 Release Google.Cloud.Asset.V1 version 2.8.0
  README.md
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1.csproj
  apis/Google.Cloud.Asset.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6577 [apis/Google.Cloud.Tasks.V2Beta3] docs: fix grammar in documentation.
  apis/Google.Cloud.Tasks.V2Beta3/Google.Cloud.Tasks.V2Beta3/Queue.g.cs
  apis/Google.Cloud.Tasks.V2Beta3/synth.metadata
Labels: cla: yes, context: full
