Repository googleapis/google-cloud-dotnet, pull requests merged in 2021-09, with the labels that each got.

#7084 [apis/Google.Cloud.AIPlatform.V1] feat: add Vizier service to aiplatform v1
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1.Snippets/VizierServiceClientSnippets.g.cs
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1.Tests/VizierServiceClientTest.g.cs
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/JobService.g.cs
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/JobServiceClient.g.cs
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/VizierService.g.cs
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/VizierServiceClient.g.cs
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/VizierServiceGrpc.g.cs
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/VizierServiceResourceNames.g.cs
  apis/Google.Cloud.AIPlatform.V1/gapic_metadata.json
  apis/Google.Cloud.AIPlatform.V1/synth.metadata
Labels: cla: yes, context: full

#7085 [apis/Google.Cloud.BigQuery.Reservation.V1] feat: Deprecated SearchAssignments in favor of SearchAllAssignments feat: Reservation objects now contain a creation time and an update time feat: Added commitment_start_time to capacity commitments feat: F
  apis/Google.Cloud.BigQuery.Reservation.V1/Google.Cloud.BigQuery.Reservation.V1.Snippets/ReservationServiceClientSnippets.g.cs
  apis/Google.Cloud.BigQuery.Reservation.V1/Google.Cloud.BigQuery.Reservation.V1.Tests/ReservationServiceClientTest.g.cs
  apis/Google.Cloud.BigQuery.Reservation.V1/Google.Cloud.BigQuery.Reservation.V1/Reservation.g.cs
  apis/Google.Cloud.BigQuery.Reservation.V1/Google.Cloud.BigQuery.Reservation.V1/ReservationGrpc.g.cs
  apis/Google.Cloud.BigQuery.Reservation.V1/Google.Cloud.BigQuery.Reservation.V1/ReservationResourceNames.g.cs
  apis/Google.Cloud.BigQuery.Reservation.V1/Google.Cloud.BigQuery.Reservation.V1/ReservationServiceClient.g.cs
  apis/Google.Cloud.BigQuery.Reservation.V1/gapic_metadata.json
  apis/Google.Cloud.BigQuery.Reservation.V1/synth.metadata
Labels: cla: yes, context: full

#7088 Release Google.Cloud.PrivateCatalog.V1Beta1 version 1.0.0-beta02
  apis/Google.Cloud.PrivateCatalog.V1Beta1/Google.Cloud.PrivateCatalog.V1Beta1/Google.Cloud.PrivateCatalog.V1Beta1.csproj
  apis/Google.Cloud.PrivateCatalog.V1Beta1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7091 Release Google.Cloud.RecaptchaEnterprise.V1Beta1 version 1.0.0-beta05
  apis/Google.Cloud.RecaptchaEnterprise.V1Beta1/Google.Cloud.RecaptchaEnterprise.V1Beta1/Google.Cloud.RecaptchaEnterprise.V1Beta1.csproj
  apis/Google.Cloud.RecaptchaEnterprise.V1Beta1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7093 Release Google.Cloud.Recommender.V1 version 2.6.0
  apis/Google.Cloud.Recommender.V1/Google.Cloud.Recommender.V1/Google.Cloud.Recommender.V1.csproj
  apis/Google.Cloud.Recommender.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7087 Release Google.Cloud.PolicyTroubleshooter.V1 version 1.2.0
  apis/Google.Cloud.PolicyTroubleshooter.V1/Google.Cloud.PolicyTroubleshooter.V1/Google.Cloud.PolicyTroubleshooter.V1.csproj
  apis/Google.Cloud.PolicyTroubleshooter.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7094 Release Google.Cloud.Redis.V1 version 2.3.0
  apis/Google.Cloud.Redis.V1/Google.Cloud.Redis.V1/Google.Cloud.Redis.V1.csproj
  apis/Google.Cloud.Redis.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7096 Release Google.Cloud.ResourceManager.V3 version 1.1.0
  apis/Google.Cloud.ResourceManager.V3/Google.Cloud.ResourceManager.V3/Google.Cloud.ResourceManager.V3.csproj
  apis/Google.Cloud.ResourceManager.V3/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7100 Release Google.Cloud.SecretManager.V1Beta1 version 2.0.0-beta05
  apis/Google.Cloud.SecretManager.V1Beta1/Google.Cloud.SecretManager.V1Beta1/Google.Cloud.SecretManager.V1Beta1.csproj
  apis/Google.Cloud.SecretManager.V1Beta1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7090 Release Google.Cloud.RecaptchaEnterprise.V1 version 1.3.0
  apis/Google.Cloud.RecaptchaEnterprise.V1/Google.Cloud.RecaptchaEnterprise.V1/Google.Cloud.RecaptchaEnterprise.V1.csproj
  apis/Google.Cloud.RecaptchaEnterprise.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7098 Release Google.Cloud.Scheduler.V1 version 2.3.0
  apis/Google.Cloud.Scheduler.V1/Google.Cloud.Scheduler.V1/Google.Cloud.Scheduler.V1.csproj
  apis/Google.Cloud.Scheduler.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7101 Release Google.Cloud.Security.PrivateCA.V1 version 2.1.0
  apis/Google.Cloud.Security.PrivateCA.V1/Google.Cloud.Security.PrivateCA.V1/Google.Cloud.Security.PrivateCA.V1.csproj
  apis/Google.Cloud.Security.PrivateCA.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7106 Release Google.Cloud.ServiceControl.V1 version 1.3.0
  apis/Google.Cloud.ServiceControl.V1/Google.Cloud.ServiceControl.V1/Google.Cloud.ServiceControl.V1.csproj
  apis/Google.Cloud.ServiceControl.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7092 Release Google.Cloud.RecommendationEngine.V1Beta1 version 1.0.0-beta03
  apis/Google.Cloud.RecommendationEngine.V1Beta1/Google.Cloud.RecommendationEngine.V1Beta1/Google.Cloud.RecommendationEngine.V1Beta1.csproj
  apis/Google.Cloud.RecommendationEngine.V1Beta1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7095 Release Google.Cloud.Redis.V1Beta1 version 2.0.0-beta05
  apis/Google.Cloud.Redis.V1Beta1/Google.Cloud.Redis.V1Beta1/Google.Cloud.Redis.V1Beta1.csproj
  apis/Google.Cloud.Redis.V1Beta1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7107 Release Google.Cloud.ServiceDirectory.V1 version 1.2.0
  apis/Google.Cloud.ServiceDirectory.V1/Google.Cloud.ServiceDirectory.V1/Google.Cloud.ServiceDirectory.V1.csproj
  apis/Google.Cloud.ServiceDirectory.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7108 Release Google.Cloud.ServiceDirectory.V1Beta1 version 1.0.0-beta06
  apis/Google.Cloud.ServiceDirectory.V1Beta1/Google.Cloud.ServiceDirectory.V1Beta1/Google.Cloud.ServiceDirectory.V1Beta1.csproj
  apis/Google.Cloud.ServiceDirectory.V1Beta1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7097 Release Google.Cloud.ResourceSettings.V1 version 1.2.0
  apis/Google.Cloud.ResourceSettings.V1/Google.Cloud.ResourceSettings.V1/Google.Cloud.ResourceSettings.V1.csproj
  apis/Google.Cloud.ResourceSettings.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7103 Release Google.Cloud.SecurityCenter.Settings.V1Beta1 version 1.0.0-beta04
  apis/Google.Cloud.SecurityCenter.Settings.V1Beta1/Google.Cloud.SecurityCenter.Settings.V1Beta1/Google.Cloud.SecurityCenter.Settings.V1Beta1.csproj
  apis/Google.Cloud.SecurityCenter.Settings.V1Beta1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7105 Release Google.Cloud.SecurityCenter.V1P1Beta1 version 2.0.0-beta06
  apis/Google.Cloud.SecurityCenter.V1P1Beta1/Google.Cloud.SecurityCenter.V1P1Beta1/Google.Cloud.SecurityCenter.V1P1Beta1.csproj
  apis/Google.Cloud.SecurityCenter.V1P1Beta1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7089 Release Google.Cloud.Profiler.V2 version 1.2.0
  apis/Google.Cloud.Profiler.V2/Google.Cloud.Profiler.V2/Google.Cloud.Profiler.V2.csproj
  apis/Google.Cloud.Profiler.V2/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7102 Release Google.Cloud.Security.PrivateCA.V1Beta1 version 1.0.0-beta03
  apis/Google.Cloud.Security.PrivateCA.V1Beta1/Google.Cloud.Security.PrivateCA.V1Beta1/Google.Cloud.Security.PrivateCA.V1Beta1.csproj
  apis/Google.Cloud.Security.PrivateCA.V1Beta1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7086 Release Google.Cloud.NetworkConnectivity.V1Alpha1 version 1.0.0-alpha03
  apis/Google.Cloud.NetworkConnectivity.V1Alpha1/Google.Cloud.NetworkConnectivity.V1Alpha1/Google.Cloud.NetworkConnectivity.V1Alpha1.csproj
  apis/Google.Cloud.NetworkConnectivity.V1Alpha1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7104 Release Google.Cloud.SecurityCenter.V1 version 2.6.0
  apis/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1.csproj
  apis/Google.Cloud.SecurityCenter.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7099 Release Google.Cloud.SecretManager.V1 version 1.7.0
  apis/Google.Cloud.SecretManager.V1/Google.Cloud.SecretManager.V1/Google.Cloud.SecretManager.V1.csproj
  apis/Google.Cloud.SecretManager.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7043 tests(Diagnostics): Improvements on entry polling
  apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore.IntegrationTests/DiagnosticsWebHostTests.cs
  apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore.IntegrationTests/ErrorReporting/ErrorReportingTest.cs
  apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore.IntegrationTests/LogValidatingFixture.cs
  apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore.IntegrationTests/Logging/LoggingTest.cs
  apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore.IntegrationTests/Trace/TraceTest.cs
  apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore.Snippets/DiagnosticsSnippets.cs
  apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore.Snippets/ErrorReportingSnippets.cs
  apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore.Snippets/LoggingSnippets.cs
  apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore.Snippets/StandaloneTraceSnippets.cs
  apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore.Snippets/TraceSnippets.cs
  apis/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common.IntegrationTests/BaseEntryPolling.cs
  apis/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common.IntegrationTests/ErrorReporting/ErrorEventEntryPolling.cs
  apis/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common.IntegrationTests/Logging/LogEntryPolling.cs
  apis/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common.IntegrationTests/Trace/SimpleManagedTracerTest.cs
  apis/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common.IntegrationTests/Trace/TraceEntryPolling.cs
  apis/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common.IntegrationTests/Trace/TraceHeaderPropagatingHandlerTest.cs
Labels: cla: yes

#7109 [apis/Google.Analytics.Data.V1Beta] feat: add `CheckCompatibility` method to the API
  apis/Google.Analytics.Data.V1Beta/Google.Analytics.Data.V1Beta.Snippets/BetaAnalyticsDataClientSnippets.g.cs
  apis/Google.Analytics.Data.V1Beta/Google.Analytics.Data.V1Beta.Tests/BetaAnalyticsDataClientTest.g.cs
  apis/Google.Analytics.Data.V1Beta/Google.Analytics.Data.V1Beta/AnalyticsDataApi.g.cs
  apis/Google.Analytics.Data.V1Beta/Google.Analytics.Data.V1Beta/AnalyticsDataApiGrpc.g.cs
  apis/Google.Analytics.Data.V1Beta/Google.Analytics.Data.V1Beta/BetaAnalyticsDataClient.g.cs
  apis/Google.Analytics.Data.V1Beta/Google.Analytics.Data.V1Beta/Data.g.cs
  apis/Google.Analytics.Data.V1Beta/gapic_metadata.json
  apis/Google.Analytics.Data.V1Beta/synth.metadata
Labels: cla: yes, context: full

#7110 [apis/Google.Cloud.Dialogflow.V2] docs: clarified some LRO types
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/AgentGrpc.g.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/AgentsClient.g.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/AudioConfig.g.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/DocumentGrpc.g.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/DocumentsClient.g.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/EntityTypeGrpc.g.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/EntityTypesClient.g.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/IntentGrpc.g.cs
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/IntentsClient.g.cs
  apis/Google.Cloud.Dialogflow.V2/synth.metadata
Labels: cla: yes, context: full

#7112 [apis/Google.Cloud.Asset.V1] feat: Release of relationships in v1, Add content type Relationship to support relationship search Committer: yuwangyw@
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1/Assets.g.cs
  apis/Google.Cloud.Asset.V1/synth.metadata
Labels: cla: yes, context: full

#7114 [apis/Google.Cloud.Channel.V1] feat: add API ImportCustomer for Cloud Channel API docs: update comments for a few fields
  apis/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1.Snippets/CloudChannelServiceClientSnippets.g.cs
  apis/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1.Tests/CloudChannelServiceClientTest.g.cs
  apis/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1/CloudChannelServiceClient.g.cs
  apis/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1/Customers.g.cs
  apis/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1/Service.g.cs
  apis/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1/ServiceGrpc.g.cs
  apis/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1/ServiceResourceNames.g.cs
  apis/Google.Cloud.Channel.V1/gapic_metadata.json
  apis/Google.Cloud.Channel.V1/synth.metadata
Labels: cla: yes, context: full

#7115 [apis/Google.Cloud.OsConfig.V1] feat: add OSConfigZonalService API Committer: @jaiminsh
  apis/Google.Cloud.OsConfig.V1/Google.Cloud.OsConfig.V1.Snippets/OsConfigZonalServiceClientSnippets.g.cs
  apis/Google.Cloud.OsConfig.V1/Google.Cloud.OsConfig.V1.Tests/OsConfigZonalServiceClientTest.g.cs
  apis/Google.Cloud.OsConfig.V1/Google.Cloud.OsConfig.V1/Inventory.g.cs
  apis/Google.Cloud.OsConfig.V1/Google.Cloud.OsConfig.V1/InventoryResourceNames.g.cs
  apis/Google.Cloud.OsConfig.V1/Google.Cloud.OsConfig.V1/OsConfigZonalServiceClient.g.cs
  apis/Google.Cloud.OsConfig.V1/Google.Cloud.OsConfig.V1/OsconfigService.g.cs
  apis/Google.Cloud.OsConfig.V1/Google.Cloud.OsConfig.V1/OsconfigServiceResourceNames.g.cs
  apis/Google.Cloud.OsConfig.V1/Google.Cloud.OsConfig.V1/OsconfigZonalService.g.cs
  apis/Google.Cloud.OsConfig.V1/Google.Cloud.OsConfig.V1/OsconfigZonalServiceGrpc.g.cs
  apis/Google.Cloud.OsConfig.V1/Google.Cloud.OsConfig.V1/Vulnerability.g.cs
  apis/Google.Cloud.OsConfig.V1/Google.Cloud.OsConfig.V1/VulnerabilityResourceNames.g.cs
  apis/Google.Cloud.OsConfig.V1/gapic_metadata.json
  apis/Google.Cloud.OsConfig.V1/synth.metadata
Labels: cla: yes, context: full

#7116 Add google/cloud/extended_operations.proto to Google.LongRunning
  apis/Google.LongRunning/postgeneration.sh
  apis/Google.LongRunning/synth.metadata
  generateapis.sh
Labels: cla: yes

#7117 Re-generated apis/Google.LongRunning with extended_operations.proto
  apis/Google.LongRunning/Google.LongRunning/ExtendedOperations.g.cs
Labels: cla: yes, context: none

#7118 Release Google.LongRunning version 2.3.0
  apis/Google.LongRunning/Google.LongRunning/Google.LongRunning.csproj
  apis/Google.LongRunning/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7119 Release Google.LongRunning version 2.3.0
  tools/Google.Cloud.Tools.GenerateCanonicalLinks.Tests/CanonicalizerTest.cs
  tools/Google.Cloud.Tools.GenerateCanonicalLinks/Canonicalizer.cs
Labels: cla: yes, autorelease: pending, automerge: exact

#7120 fix: Add workaround to fix Google.Cloud.Asset.V1 build
  apis/Google.Cloud.Asset.V1/postgeneration.sh
  apis/Google.Cloud.Asset.V1/pregeneration.sh
Labels: cla: yes

#7121 Re-generated apis/Google.Cloud.Asset.V1 to pick up changes in OS Config
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1/Assets.g.cs
Labels: cla: yes, context: none

#7141 Release Google.Cloud.WebRisk.V1Beta1 version 2.0.0-beta05
  apis/Google.Cloud.WebRisk.V1Beta1/Google.Cloud.WebRisk.V1Beta1/Google.Cloud.WebRisk.V1Beta1.csproj
  apis/Google.Cloud.WebRisk.V1Beta1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7140 Release Google.Cloud.WebRisk.V1 version 1.3.0
  apis/Google.Cloud.WebRisk.V1/Google.Cloud.WebRisk.V1/Google.Cloud.WebRisk.V1.csproj
  apis/Google.Cloud.WebRisk.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7142 Release Google.Cloud.WebSecurityScanner.V1 version 1.2.0
  apis/Google.Cloud.WebSecurityScanner.V1/Google.Cloud.WebSecurityScanner.V1/Google.Cloud.WebSecurityScanner.V1.csproj
  apis/Google.Cloud.WebSecurityScanner.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7135 Release Google.Cloud.Trace.V2 version 2.3.0
  apis/Google.Cloud.Trace.V2/Google.Cloud.Trace.V2/Google.Cloud.Trace.V2.csproj
  apis/Google.Cloud.Trace.V2/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7138 Release Google.Cloud.Vision.V1 version 2.4.0
  apis/Google.Cloud.Vision.V1/Google.Cloud.Vision.V1/Google.Cloud.Vision.V1.csproj
  apis/Google.Cloud.Vision.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7131 Release Google.Cloud.TextToSpeech.V1 version 2.3.0
  apis/Google.Cloud.TextToSpeech.V1/Google.Cloud.TextToSpeech.V1/Google.Cloud.TextToSpeech.V1.csproj
  apis/Google.Cloud.TextToSpeech.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7134 Release Google.Cloud.Trace.V1 version 2.3.0
  apis/Google.Cloud.Trace.V1/Google.Cloud.Trace.V1/Google.Cloud.Trace.V1.csproj
  apis/Google.Cloud.Trace.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7122 Release Google.Cloud.Logging.V2 version 3.4.0
  apis/Google.Cloud.Logging.V2/Google.Cloud.Logging.V2/Google.Cloud.Logging.V2.csproj
  apis/Google.Cloud.Logging.V2/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7126 Release Google.Cloud.Speech.V1 version 2.4.0
  apis/Google.Cloud.Speech.V1/Google.Cloud.Speech.V1/Google.Cloud.Speech.V1.csproj
  apis/Google.Cloud.Speech.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7127 Release Google.Cloud.StorageTransfer.V1 version 1.1.0
  apis/Google.Cloud.StorageTransfer.V1/Google.Cloud.StorageTransfer.V1/Google.Cloud.StorageTransfer.V1.csproj
  apis/Google.Cloud.StorageTransfer.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7136 Release Google.Cloud.Video.Transcoder.V1Beta1 version 1.0.0-beta04
  apis/Google.Cloud.Video.Transcoder.V1Beta1/Google.Cloud.Video.Transcoder.V1Beta1/Google.Cloud.Video.Transcoder.V1Beta1.csproj
  apis/Google.Cloud.Video.Transcoder.V1Beta1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7139 Release Google.Cloud.VpcAccess.V1 version 1.1.0
  apis/Google.Cloud.VpcAccess.V1/Google.Cloud.VpcAccess.V1/Google.Cloud.VpcAccess.V1.csproj
  apis/Google.Cloud.VpcAccess.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7137 Release Google.Cloud.VideoIntelligence.V1 version 2.3.0
  apis/Google.Cloud.VideoIntelligence.V1/Google.Cloud.VideoIntelligence.V1/Google.Cloud.VideoIntelligence.V1.csproj
  apis/Google.Cloud.VideoIntelligence.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7128 Release Google.Cloud.Talent.V4Beta1 version 2.0.0-beta06
  apis/Google.Cloud.Talent.V4Beta1/Google.Cloud.Talent.V4Beta1/Google.Cloud.Talent.V4Beta1.csproj
  apis/Google.Cloud.Talent.V4Beta1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7132 Release Google.Cloud.TextToSpeech.V1Beta1 version 1.0.0-beta02
  apis/Google.Cloud.TextToSpeech.V1Beta1/Google.Cloud.TextToSpeech.V1Beta1/Google.Cloud.TextToSpeech.V1Beta1.csproj
  apis/Google.Cloud.TextToSpeech.V1Beta1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7123 Release Google.Cloud.ServiceManagement.V1 version 1.3.0
  apis/Google.Cloud.ServiceManagement.V1/Google.Cloud.ServiceManagement.V1/Google.Cloud.ServiceManagement.V1.csproj
  apis/Google.Cloud.ServiceManagement.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7130 Release Google.Cloud.Tasks.V2Beta3 version 2.0.0-beta07
  apis/Google.Cloud.Tasks.V2Beta3/Google.Cloud.Tasks.V2Beta3/Google.Cloud.Tasks.V2Beta3.csproj
  apis/Google.Cloud.Tasks.V2Beta3/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7124 Release Google.Cloud.ServiceUsage.V1 version 1.1.0
  apis/Google.Cloud.ServiceUsage.V1/Google.Cloud.ServiceUsage.V1/Google.Cloud.ServiceUsage.V1.csproj
  apis/Google.Cloud.ServiceUsage.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7133 Release Google.Cloud.Tpu.V1 version 1.1.0
  apis/Google.Cloud.Tpu.V1/Google.Cloud.Tpu.V1/Google.Cloud.Tpu.V1.csproj
  apis/Google.Cloud.Tpu.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7125 Release Google.Cloud.Shell.V1 version 1.1.0
  apis/Google.Cloud.Shell.V1/Google.Cloud.Shell.V1/Google.Cloud.Shell.V1.csproj
  apis/Google.Cloud.Shell.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7129 Release Google.Cloud.Tasks.V2 version 2.3.0
  apis/Google.Cloud.Tasks.V2/Google.Cloud.Tasks.V2/Google.Cloud.Tasks.V2.csproj
  apis/Google.Cloud.Tasks.V2/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7146 chore: Remove hack now all releases have been successful
  buildrelease.sh
Labels: cla: yes

#7149 ci: Renovate ignores Grpc.Core
  .github/renovate.json
Labels: cla: yes

#7150 chore: Update CODEOWNERS for @googleapis/cloud-storage-dpe
  .github/CODEOWNERS
Labels: cla: yes

#7152 test(Vision): Adjust assert on detect images.
  apis/Google.Cloud.Vision.V1/Google.Cloud.Vision.V1.Snippets/ImageAnnotatorClientSnippets.cs
Labels: api: vision, cla: yes

#7155 chore: Move #7154 to the backlog
  BACKLOG.md
Labels: cla: yes

#7156 tests(Vision): Loosen landmark tests some more.
  apis/Google.Cloud.Vision.V1/Google.Cloud.Vision.V1.Snippets/ImageAnnotatorClientSnippets.cs
Labels: api: vision, cla: yes

#7160 Fix OSConfig v1alpha smoke test
  apis/Google.Cloud.OsConfig.V1Alpha/smoketests.json
Labels: cla: yes

#7164 [apis/Google.Cloud.Talent.V4] feat: Added a new `KeywordMatchMode` field to support more keyword matching options feat: Added more `DiversificationLevel` configuration options
  apis/Google.Cloud.Talent.V4/Google.Cloud.Talent.V4.Snippets/JobServiceClientSnippets.g.cs
  apis/Google.Cloud.Talent.V4/Google.Cloud.Talent.V4.Tests/JobServiceClientTest.g.cs
  apis/Google.Cloud.Talent.V4/Google.Cloud.Talent.V4/CompanyServiceGrpc.g.cs
  apis/Google.Cloud.Talent.V4/Google.Cloud.Talent.V4/CompletionServiceGrpc.g.cs
  apis/Google.Cloud.Talent.V4/Google.Cloud.Talent.V4/EventServiceGrpc.g.cs
  apis/Google.Cloud.Talent.V4/Google.Cloud.Talent.V4/JobService.g.cs
  apis/Google.Cloud.Talent.V4/Google.Cloud.Talent.V4/JobServiceGrpc.g.cs
  apis/Google.Cloud.Talent.V4/Google.Cloud.Talent.V4/TenantServiceGrpc.g.cs
  apis/Google.Cloud.Talent.V4/synth.metadata
Labels: cla: yes, context: full

#7166 chore: Remove additional Asset import
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1/Assets.g.cs
  apis/Google.Cloud.Asset.V1/postgeneration.sh
  apis/Google.Cloud.Asset.V1/pregeneration.sh
  apis/Google.Cloud.Asset.V1/synth.metadata
Labels: cla: yes

#7167 chore: Remove obsolete compatibility check in generateapis.sh
  generateapis.sh
Labels: cla: yes

#7055 [apis/Google.Cloud.Monitoring.V3] feat: Added support for logs-based alerts: https://cloud.google.com/logging/docs/alerting/log-based-alerts feat: Added support for user-defined labels on cloud monitoring's Service and ServiceLevelObjective objects f
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3.Tests/AlertPolicyServiceClientTest.g.cs
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3.Tests/NotificationChannelServiceClientTest.g.cs
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3.Tests/ServiceMonitoringServiceClientTest.g.cs
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3/Alert.g.cs
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3/AlertPolicyServiceClient.g.cs
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3/AlertService.g.cs
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3/Common.g.cs
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3/GroupService.g.cs
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3/GroupServiceClient.g.cs
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3/Metric.g.cs
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3/MetricService.g.cs
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3/MetricServiceClient.g.cs
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3/Notification.g.cs
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3/NotificationChannelServiceClient.g.cs
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3/NotificationService.g.cs
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3/Service.g.cs
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3/ServiceMonitoringServiceClient.g.cs
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3/ServiceService.g.cs
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3/SpanContext.g.cs
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3/Uptime.g.cs
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3/UptimeCheckServiceClient.g.cs
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3/UptimeService.g.cs
  apis/Google.Cloud.Monitoring.V3/synth.metadata
Labels: cla: yes, context: full, allow breaking changes

#7169 chore: Regenerate apis/Google.Cloud.Monitoring.V3 to pick up newer gRPC generator version
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3/AlertServiceGrpc.g.cs
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3/GroupServiceGrpc.g.cs
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3/MetricServiceGrpc.g.cs
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3/NotificationServiceGrpc.g.cs
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3/QueryServiceGrpc.g.cs
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3/ServiceServiceGrpc.g.cs
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3/UptimeServiceGrpc.g.cs
Labels: cla: yes, context: none, allow breaking changes

#7171 [apis/Google.Cloud.BigQuery.Storage.V1] docs: Align session length with public documentation feat: Expose estimated bytes that a session will scan.
  apis/Google.Cloud.BigQuery.Storage.V1/Google.Cloud.BigQuery.Storage.V1.Tests/BigQueryReadClientTest.g.cs
  apis/Google.Cloud.BigQuery.Storage.V1/Google.Cloud.BigQuery.Storage.V1/BigQueryReadClient.g.cs
  apis/Google.Cloud.BigQuery.Storage.V1/Google.Cloud.BigQuery.Storage.V1/StorageGrpc.g.cs
  apis/Google.Cloud.BigQuery.Storage.V1/Google.Cloud.BigQuery.Storage.V1/Stream.g.cs
  apis/Google.Cloud.BigQuery.Storage.V1/synth.metadata
Labels: cla: yes, context: full

#7172 [apis/Google.Cloud.Functions.V1] feat: add SecurityLevel option on HttpsTrigger
  apis/Google.Cloud.Functions.V1/Google.Cloud.Functions.V1/Functions.g.cs
  apis/Google.Cloud.Functions.V1/synth.metadata
Labels: cla: yes, context: full

#7173 [apis/Google.Cloud.RecaptchaEnterprise.V1] feat: add GetMetrics and MigrateKey methods to reCAPTCHA enterprise API
  apis/Google.Cloud.RecaptchaEnterprise.V1/Google.Cloud.RecaptchaEnterprise.V1.Snippets/RecaptchaEnterpriseServiceClientSnippets.g.cs
  apis/Google.Cloud.RecaptchaEnterprise.V1/Google.Cloud.RecaptchaEnterprise.V1.Tests/RecaptchaEnterpriseServiceClientTest.g.cs
  apis/Google.Cloud.RecaptchaEnterprise.V1/Google.Cloud.RecaptchaEnterprise.V1/RecaptchaEnterpriseServiceClient.g.cs
  apis/Google.Cloud.RecaptchaEnterprise.V1/Google.Cloud.RecaptchaEnterprise.V1/Recaptchaenterprise.g.cs
  apis/Google.Cloud.RecaptchaEnterprise.V1/Google.Cloud.RecaptchaEnterprise.V1/RecaptchaenterpriseGrpc.g.cs
  apis/Google.Cloud.RecaptchaEnterprise.V1/Google.Cloud.RecaptchaEnterprise.V1/RecaptchaenterpriseResourceNames.g.cs
  apis/Google.Cloud.RecaptchaEnterprise.V1/gapic_metadata.json
  apis/Google.Cloud.RecaptchaEnterprise.V1/synth.metadata
Labels: cla: yes, context: full

#7175 docs: Fix the documentation for BigtableServiceApiSettings
  apis/Google.Cloud.Bigtable.V2/Google.Cloud.Bigtable.V2/BigtableServiceApiClientPartial.cs
Labels: cla: yes

#7176 [apis/Google.Cloud.ContactCenterInsights.V1] feat: filter is used to filter conversations used for issue model training feat: update_time is used to indicate when the phrase matcher was updated
  apis/Google.Cloud.ContactCenterInsights.V1/Google.Cloud.ContactCenterInsights.V1.Tests/ContactCenterInsightsClientTest.g.cs
  apis/Google.Cloud.ContactCenterInsights.V1/Google.Cloud.ContactCenterInsights.V1/Resources.g.cs
  apis/Google.Cloud.ContactCenterInsights.V1/synth.metadata
Labels: cla: yes, context: full

#7178 [apis/Google.Cloud.BigQuery.Storage.V1] feat: add BigQuery Storage Write API v1
  apis/Google.Cloud.BigQuery.Storage.V1/Google.Cloud.BigQuery.Storage.V1.Snippets/BigQueryWriteClientSnippets.g.cs
  apis/Google.Cloud.BigQuery.Storage.V1/Google.Cloud.BigQuery.Storage.V1.Tests/BigQueryWriteClientTest.g.cs
  apis/Google.Cloud.BigQuery.Storage.V1/Google.Cloud.BigQuery.Storage.V1/BigQueryReadClient.g.cs
  apis/Google.Cloud.BigQuery.Storage.V1/Google.Cloud.BigQuery.Storage.V1/BigQueryWriteClient.g.cs
  apis/Google.Cloud.BigQuery.Storage.V1/Google.Cloud.BigQuery.Storage.V1/Protobuf.g.cs
  apis/Google.Cloud.BigQuery.Storage.V1/Google.Cloud.BigQuery.Storage.V1/Storage.g.cs
  apis/Google.Cloud.BigQuery.Storage.V1/Google.Cloud.BigQuery.Storage.V1/StorageGrpc.g.cs
  apis/Google.Cloud.BigQuery.Storage.V1/Google.Cloud.BigQuery.Storage.V1/StorageResourceNames.g.cs
  apis/Google.Cloud.BigQuery.Storage.V1/Google.Cloud.BigQuery.Storage.V1/Stream.g.cs
  apis/Google.Cloud.BigQuery.Storage.V1/Google.Cloud.BigQuery.Storage.V1/StreamResourceNames.g.cs
  apis/Google.Cloud.BigQuery.Storage.V1/Google.Cloud.BigQuery.Storage.V1/Table.g.cs
  apis/Google.Cloud.BigQuery.Storage.V1/gapic_metadata.json
  apis/Google.Cloud.BigQuery.Storage.V1/synth.metadata
Labels: cla: yes, context: full

#7180 [apis/Google.Cloud.Speech.V1] feat: add output_config request field
  apis/Google.Cloud.Speech.V1/Google.Cloud.Speech.V1.Snippets/SpeechClientSnippets.g.cs
  apis/Google.Cloud.Speech.V1/Google.Cloud.Speech.V1/CloudSpeech.g.cs
  apis/Google.Cloud.Speech.V1/synth.metadata
Labels: cla: yes, context: full

#7181 First step towards package groups
  apis/apis.json
  tools/Google.Cloud.Tools.Common/ApiCatalog.cs
  tools/Google.Cloud.Tools.Common/ApiMetadata.cs
  tools/Google.Cloud.Tools.Common/PackageGroup.cs
  tools/Google.Cloud.Tools.ReleaseManager/GenerateProjectsCommand.cs
Labels: cla: yes

#7183 Release Cloud Workflows V1 libraries version 1.1.0
  apis/Google.Cloud.Workflows.Common.V1/Google.Cloud.Workflows.Common.V1/Google.Cloud.Workflows.Common.V1.csproj
  apis/Google.Cloud.Workflows.Executions.V1/Google.Cloud.Workflows.Executions.V1/Google.Cloud.Workflows.Executions.V1.csproj
  apis/Google.Cloud.Workflows.Executions.V1/docs/history.md
  apis/Google.Cloud.Workflows.V1/Google.Cloud.Workflows.V1/Google.Cloud.Workflows.V1.csproj
  apis/Google.Cloud.Workflows.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7186 Release GSuite Add-Ons libraries version 1.1.0
  apis/Google.Apps.Script.Type/Google.Apps.Script.Type/Google.Apps.Script.Type.csproj
  apis/Google.Apps.Script.Type/docs/history.md
  apis/Google.Cloud.GSuiteAddOns.V1/Google.Cloud.GSuiteAddOns.V1/Google.Cloud.GSuiteAddOns.V1.csproj
  apis/Google.Cloud.GSuiteAddOns.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7187 Release OS Login libraries
  apis/Google.Cloud.OsLogin.Common/Google.Cloud.OsLogin.Common/Google.Cloud.OsLogin.Common.csproj
  apis/Google.Cloud.OsLogin.V1/Google.Cloud.OsLogin.V1/Google.Cloud.OsLogin.V1.csproj
  apis/Google.Cloud.OsLogin.V1/docs/history.md
  apis/Google.Cloud.OsLogin.V1Beta/Google.Cloud.OsLogin.V1Beta/Google.Cloud.OsLogin.V1Beta.csproj
  apis/Google.Cloud.OsLogin.V1Beta/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7190 chore: Add support for OwlBot
  generateapis.sh
  tools/Google.Cloud.Tools.Common/ApiMetadata.cs
  tools/Google.Cloud.Tools.Common/AutoGeneratorType.cs
  tools/Google.Cloud.Tools.ReleaseManager/GenerateProjectsCommand.cs
Labels: cla: yes

#7193 chore: Make it simpler to run a local generator
  toolversions.sh
Labels: cla: yes

#7199 fix: Fix typo in generation script
  generateapis.sh
Labels: cla: yes

#7200 [apis/Google.Cloud.BigQuery.Storage.V1] fix: add missing read api retry setting on SplitReadStream
  apis/Google.Cloud.BigQuery.Storage.V1/Google.Cloud.BigQuery.Storage.V1/BigQueryReadClient.g.cs
  apis/Google.Cloud.BigQuery.Storage.V1/synth.metadata
Labels: cla: yes, context: full

#7201 Regenerate Google.Cloud.Deploy.V1
  apis/Google.Cloud.Deploy.V1/synth.metadata
Labels: cla: yes

#7202 fix: Update the OwlBot Docker image hash to use
  .github/.OwlBot.lock.yaml
Labels: cla: yes

#7203 fix: Make the OwlBot post-processing script executable
  owl-bot-post-processor/main.sh
Labels: cla: yes

#7205 [apis/Google.Cloud.Audit] feat: Add BigQueryAuditMetadata proto. The BigQueryAuditMetadata proto is used by BigQuery Cloud Audit Logging. It is encoded as a google.protobuf.Struct message inside the metadata field of the AuditLog proto
  apis/Google.Cloud.Audit/Google.Cloud.Audit/BigqueryAuditMetadata.cs
  apis/Google.Cloud.Audit/synth.metadata
Labels: cla: yes, context: full

#7207 Release Google.Cloud.Deploy.V1 version 1.0.0-beta01
  README.md
  apis/Google.Cloud.Deploy.V1/.repo-metadata.json
  apis/Google.Cloud.Deploy.V1/Google.Cloud.Deploy.V1/Google.Cloud.Deploy.V1.csproj
  apis/Google.Cloud.Deploy.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7208 Release Google.Cloud.NetworkSecurity.V1Beta1 version 1.0.0-beta01
  .github/renovate.json
  README.md
  apis/Google.Cloud.NetworkSecurity.V1Beta1/.repo-metadata.json
  apis/Google.Cloud.NetworkSecurity.V1Beta1/Google.Cloud.NetworkSecurity.V1Beta1.Snippets/Google.Cloud.NetworkSecurity.V1Beta1.Snippets.csproj
  apis/Google.Cloud.NetworkSecurity.V1Beta1/Google.Cloud.NetworkSecurity.V1Beta1.Snippets/NetworkSecurityClientSnippets.g.cs
  apis/Google.Cloud.NetworkSecurity.V1Beta1/Google.Cloud.NetworkSecurity.V1Beta1.Snippets/coverage.xml
  apis/Google.Cloud.NetworkSecurity.V1Beta1/Google.Cloud.NetworkSecurity.V1Beta1.Tests/Google.Cloud.NetworkSecurity.V1Beta1.Tests.csproj
  apis/Google.Cloud.NetworkSecurity.V1Beta1/Google.Cloud.NetworkSecurity.V1Beta1.Tests/NetworkSecurityClientTest.g.cs
  apis/Google.Cloud.NetworkSecurity.V1Beta1/Google.Cloud.NetworkSecurity.V1Beta1.Tests/coverage.xml
  apis/Google.Cloud.NetworkSecurity.V1Beta1/Google.Cloud.NetworkSecurity.V1Beta1.sln
  apis/Google.Cloud.NetworkSecurity.V1Beta1/Google.Cloud.NetworkSecurity.V1Beta1/AuthorizationPolicy.g.cs
  apis/Google.Cloud.NetworkSecurity.V1Beta1/Google.Cloud.NetworkSecurity.V1Beta1/AuthorizationPolicyResourceNames.g.cs
  apis/Google.Cloud.NetworkSecurity.V1Beta1/Google.Cloud.NetworkSecurity.V1Beta1/ClientTlsPolicy.g.cs
  apis/Google.Cloud.NetworkSecurity.V1Beta1/Google.Cloud.NetworkSecurity.V1Beta1/ClientTlsPolicyResourceNames.g.cs
  apis/Google.Cloud.NetworkSecurity.V1Beta1/Google.Cloud.NetworkSecurity.V1Beta1/Common.g.cs
  apis/Google.Cloud.NetworkSecurity.V1Beta1/Google.Cloud.NetworkSecurity.V1Beta1/Google.Cloud.NetworkSecurity.V1Beta1.csproj
  apis/Google.Cloud.NetworkSecurity.V1Beta1/Google.Cloud.NetworkSecurity.V1Beta1/NetworkSecurity.g.cs
  apis/Google.Cloud.NetworkSecurity.V1Beta1/Google.Cloud.NetworkSecurity.V1Beta1/NetworkSecurityClient.g.cs
  apis/Google.Cloud.NetworkSecurity.V1Beta1/Google.Cloud.NetworkSecurity.V1Beta1/NetworkSecurityGrpc.g.cs
  apis/Google.Cloud.NetworkSecurity.V1Beta1/Google.Cloud.NetworkSecurity.V1Beta1/ServerTlsPolicy.g.cs
  apis/Google.Cloud.NetworkSecurity.V1Beta1/Google.Cloud.NetworkSecurity.V1Beta1/ServerTlsPolicyResourceNames.g.cs
  apis/Google.Cloud.NetworkSecurity.V1Beta1/Google.Cloud.NetworkSecurity.V1Beta1/Tls.g.cs
  apis/Google.Cloud.NetworkSecurity.V1Beta1/docs/history.md
  apis/Google.Cloud.NetworkSecurity.V1Beta1/docs/index.md
  apis/Google.Cloud.NetworkSecurity.V1Beta1/gapic_metadata.json
  apis/Google.Cloud.NetworkSecurity.V1Beta1/postgeneration.sh
  apis/Google.Cloud.NetworkSecurity.V1Beta1/pregeneration.sh
  apis/Google.Cloud.NetworkSecurity.V1Beta1/smoketests.json
  apis/Google.Cloud.NetworkSecurity.V1Beta1/synth.metadata
  apis/Google.Cloud.NetworkSecurity.V1Beta1/synth.py
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7206 Release Google.Cloud.Gaming.V1 version 1.2.0
  apis/Google.Cloud.Gaming.V1/Google.Cloud.Gaming.V1/Google.Cloud.Gaming.V1.csproj
  apis/Google.Cloud.Gaming.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7209 chore: Update google-cloud-dotnet based on gax-dotnet's branch change
  apis/Google.Cloud.Logging.Log4Net/docs/configuration.md
  docs/fetchdependencies.sh
Labels: cla: yes

#7226 Release Google.Cloud.Metastore.V1 version 1.1.0
  apis/Google.Cloud.Metastore.V1/Google.Cloud.Metastore.V1/Google.Cloud.Metastore.V1.csproj
  apis/Google.Cloud.Metastore.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7231 Release Google.Cloud.Talent.V4 version 1.2.0
  apis/Google.Cloud.Talent.V4/Google.Cloud.Talent.V4/Google.Cloud.Talent.V4.csproj
  apis/Google.Cloud.Talent.V4/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7229 Release Google.Cloud.Retail.V2 version 1.3.0
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2.csproj
  apis/Google.Cloud.Retail.V2/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7225 Release Google.Cloud.Kms.V1 version 2.5.0
  apis/Google.Cloud.Kms.V1/Google.Cloud.Kms.V1/Google.Cloud.Kms.V1.csproj
  apis/Google.Cloud.Kms.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7228 Release Google.Cloud.PubSub.V1 version 2.7.0
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1.csproj
  apis/Google.Cloud.PubSub.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7222 Release Google.Cloud.Filestore.V1 version 1.1.0
  apis/Google.Cloud.Filestore.V1/Google.Cloud.Filestore.V1/Google.Cloud.Filestore.V1.csproj
  apis/Google.Cloud.Filestore.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7223 Release Google.Cloud.Functions.V1 version 1.2.0
  apis/Google.Cloud.Functions.V1/Google.Cloud.Functions.V1/Google.Cloud.Functions.V1.csproj
  apis/Google.Cloud.Functions.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7216 Release Google.Cloud.BinaryAuthorization.V1Beta1 version 1.0.0-beta04
  apis/Google.Cloud.BinaryAuthorization.V1Beta1/Google.Cloud.BinaryAuthorization.V1Beta1/Google.Cloud.BinaryAuthorization.V1Beta1.csproj
  apis/Google.Cloud.BinaryAuthorization.V1Beta1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7219 Release Google.Cloud.Datastream.V1Alpha1 version 1.0.0-beta02
  apis/Google.Cloud.Datastream.V1Alpha1/Google.Cloud.Datastream.V1Alpha1/Google.Cloud.Datastream.V1Alpha1.csproj
  apis/Google.Cloud.Datastream.V1Alpha1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7211 Release Google.Cloud.Asset.V1 version 2.10.0
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1.csproj
  apis/Google.Cloud.Asset.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7220 Release Google.Cloud.Dialogflow.Cx.V3 version 1.4.0
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3.csproj
  apis/Google.Cloud.Dialogflow.Cx.V3/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7221 Release Google.Cloud.Dialogflow.V2 version 3.5.0
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2.csproj
  apis/Google.Cloud.Dialogflow.V2/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7214 Release Google.Cloud.Bigtable.Admin.V2 version 2.5.0
  apis/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2.csproj
  apis/Google.Cloud.Bigtable.Admin.V2/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7217 Release Google.Cloud.CloudBuild.V1 version 1.4.0
  apis/Google.Cloud.CloudBuild.V1/Google.Cloud.CloudBuild.V1/Google.Cloud.CloudBuild.V1.csproj
  apis/Google.Cloud.CloudBuild.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7213 Release Google.Cloud.BigQuery.DataTransfer.V1 version 3.2.0
  apis/Google.Cloud.BigQuery.DataTransfer.V1/Google.Cloud.BigQuery.DataTransfer.V1/Google.Cloud.BigQuery.DataTransfer.V1.csproj
  apis/Google.Cloud.BigQuery.DataTransfer.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7215 Release Google.Cloud.Bigtable.V2 version 2.4.0
  apis/Google.Cloud.Bigtable.V2/Google.Cloud.Bigtable.V2/Google.Cloud.Bigtable.V2.csproj
  apis/Google.Cloud.Bigtable.V2/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7212 Release Google.Cloud.Audit version 1.1.0
  apis/Google.Cloud.Audit/Google.Cloud.Audit/Google.Cloud.Audit.csproj
  apis/Google.Cloud.Audit/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7232 Release Google.Cloud.Video.Transcoder.V1 version 1.0.0-beta02
  apis/Google.Cloud.Video.Transcoder.V1/Google.Cloud.Video.Transcoder.V1/Google.Cloud.Video.Transcoder.V1.csproj
  apis/Google.Cloud.Video.Transcoder.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, allow breaking changes

#7230 Release Google.Cloud.Speech.V1P1Beta1 version 2.0.0-beta06
  apis/Google.Cloud.Speech.V1P1Beta1/Google.Cloud.Speech.V1P1Beta1/Google.Cloud.Speech.V1P1Beta1.csproj
  apis/Google.Cloud.Speech.V1P1Beta1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, allow breaking changes

#7224 Release Google.Cloud.GkeHub.V1Beta1 version 1.0.0-beta03
  apis/Google.Cloud.GkeHub.V1Beta1/Google.Cloud.GkeHub.V1Beta1/Google.Cloud.GkeHub.V1Beta1.csproj
  apis/Google.Cloud.GkeHub.V1Beta1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, allow breaking changes

#7218 Release Google.Cloud.ContactCenterInsights.V1 version 1.0.0-beta02
  apis/Google.Cloud.ContactCenterInsights.V1/Google.Cloud.ContactCenterInsights.V1/Google.Cloud.ContactCenterInsights.V1.csproj
  apis/Google.Cloud.ContactCenterInsights.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, allow breaking changes

#7227 Release Google.Cloud.NetworkConnectivity.V1 version 1.0.0-beta02
  apis/Google.Cloud.NetworkConnectivity.V1/Google.Cloud.NetworkConnectivity.V1/Google.Cloud.NetworkConnectivity.V1.csproj
  apis/Google.Cloud.NetworkConnectivity.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, allow breaking changes

#7210 Release Google.Analytics.Admin.V1Alpha version 1.0.0-alpha09
  apis/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha.csproj
  apis/Google.Analytics.Admin.V1Alpha/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, allow breaking changes

#7235 fix: Fix the link canonicalizer to handle pages in Google.Apis pages better
  tools/Google.Cloud.Tools.GenerateCanonicalLinks.Tests/CanonicalizerTest.cs
  tools/Google.Cloud.Tools.GenerateCanonicalLinks/Canonicalizer.cs
Labels: cla: yes

#7234 Add a "release all" criterion to batch release all changed packages.
  tools/Google.Cloud.Tools.ReleaseManager/BatchRelease/BatchReleaseConfig.cs
  tools/Google.Cloud.Tools.ReleaseManager/BatchRelease/KnownCommitsCriterion.cs
  tools/Google.Cloud.Tools.ReleaseManager/BatchRelease/ReleaseAllCriterion.cs
Labels: cla: yes

#7236 chore: improving the compatibility checker
  tools/Google.Cloud.Tools.Common/StructuredVersion.cs
  tools/Google.Cloud.Tools.ReleaseManager.Tests/CheckVersionCompatibilityCommandTest.cs
  tools/Google.Cloud.Tools.ReleaseManager.Tests/Google.Cloud.Tools.ReleaseManager.Tests.csproj
  tools/Google.Cloud.Tools.ReleaseManager/AssemblyInfo.cs
  tools/Google.Cloud.Tools.ReleaseManager/CheckVersionCompatibilityCommand.cs
  tools/Google.Cloud.Tools.sln
Labels: cla: yes

#7243 Release Google.Cloud.DataCatalog.V1 version 1.5.0
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1.csproj
  apis/Google.Cloud.DataCatalog.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7245 Release Google.Cloud.OsConfig.V1Alpha version 1.0.0-alpha03
  apis/Google.Cloud.OsConfig.V1Alpha/Google.Cloud.OsConfig.V1Alpha/Google.Cloud.OsConfig.V1Alpha.csproj
  apis/Google.Cloud.OsConfig.V1Alpha/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7238 Release Google.Cloud.AIPlatform.V1 version 1.0.0-beta04
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1.csproj
  apis/Google.Cloud.AIPlatform.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7240 Release Google.Cloud.BigQuery.Reservation.V1 version 1.4.0
  apis/Google.Cloud.BigQuery.Reservation.V1/Google.Cloud.BigQuery.Reservation.V1/Google.Cloud.BigQuery.Reservation.V1.csproj
  apis/Google.Cloud.BigQuery.Reservation.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7246 Release Google.Cloud.RecaptchaEnterprise.V1 version 1.4.0
  apis/Google.Cloud.RecaptchaEnterprise.V1/Google.Cloud.RecaptchaEnterprise.V1/Google.Cloud.RecaptchaEnterprise.V1.csproj
  apis/Google.Cloud.RecaptchaEnterprise.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7237 Release Google.Analytics.Data.V1Beta version 1.0.0-beta06
  apis/Google.Analytics.Data.V1Beta/Google.Analytics.Data.V1Beta/Google.Analytics.Data.V1Beta.csproj
  apis/Google.Analytics.Data.V1Beta/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7242 Release Google.Cloud.Channel.V1 version 1.4.0
  apis/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1.csproj
  apis/Google.Cloud.Channel.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7244 Release Google.Cloud.OsConfig.V1 version 1.4.0
  apis/Google.Cloud.OsConfig.V1/Google.Cloud.OsConfig.V1/Google.Cloud.OsConfig.V1.csproj
  apis/Google.Cloud.OsConfig.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7247 Release Google.Cloud.Speech.V1 version 2.5.0
  apis/Google.Cloud.Speech.V1/Google.Cloud.Speech.V1/Google.Cloud.Speech.V1.csproj
  apis/Google.Cloud.Speech.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7241 Release Google.Cloud.BigQuery.Storage.V1 version 2.5.0
  apis/Google.Cloud.BigQuery.Storage.V1/Google.Cloud.BigQuery.Storage.V1/Google.Cloud.BigQuery.Storage.V1.csproj
  apis/Google.Cloud.BigQuery.Storage.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7239 Release Google.Cloud.AssuredWorkloads.V1Beta1 version 1.0.0-beta07
  apis/Google.Cloud.AssuredWorkloads.V1Beta1/Google.Cloud.AssuredWorkloads.V1Beta1/Google.Cloud.AssuredWorkloads.V1Beta1.csproj
  apis/Google.Cloud.AssuredWorkloads.V1Beta1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7248 fix: More link canonicalization issues found (in older packages)
  tools/Google.Cloud.Tools.GenerateCanonicalLinks.Tests/CanonicalizerTest.cs
  tools/Google.Cloud.Tools.GenerateCanonicalLinks/Canonicalizer.cs
Labels: cla: yes

#7250 chore: Add GAPIC generator version selection to generator scripts
  toolversions.sh
Labels: cla: yes

#7251 tests(Storage): PAP unspecified -> inherited.
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.IntegrationTests/PublicAccessPreventionTest.cs
Labels: api: storage, cla: yes

#7255 chore: Delete Google.Analytics.Data.V1Alpha from the repo
  .github/renovate.json
  README.md
  apis/Google.Analytics.Data.V1Alpha/.repo-metadata.json
  apis/Google.Analytics.Data.V1Alpha/Google.Analytics.Data.V1Alpha.Snippets/AlphaAnalyticsDataClientSnippets.g.cs
  apis/Google.Analytics.Data.V1Alpha/Google.Analytics.Data.V1Alpha.Snippets/Google.Analytics.Data.V1Alpha.Snippets.csproj
  apis/Google.Analytics.Data.V1Alpha/Google.Analytics.Data.V1Alpha.Snippets/coverage.xml
  apis/Google.Analytics.Data.V1Alpha/Google.Analytics.Data.V1Alpha.Tests/AlphaAnalyticsDataClientTest.g.cs
  apis/Google.Analytics.Data.V1Alpha/Google.Analytics.Data.V1Alpha.Tests/Google.Analytics.Data.V1Alpha.Tests.csproj
  apis/Google.Analytics.Data.V1Alpha/Google.Analytics.Data.V1Alpha.Tests/coverage.xml
  apis/Google.Analytics.Data.V1Alpha/Google.Analytics.Data.V1Alpha.sln
  apis/Google.Analytics.Data.V1Alpha/Google.Analytics.Data.V1Alpha/AlphaAnalyticsDataClient.g.cs
  apis/Google.Analytics.Data.V1Alpha/Google.Analytics.Data.V1Alpha/AnalyticsDataApi.g.cs
  apis/Google.Analytics.Data.V1Alpha/Google.Analytics.Data.V1Alpha/AnalyticsDataApiGrpc.g.cs
  apis/Google.Analytics.Data.V1Alpha/Google.Analytics.Data.V1Alpha/AnalyticsDataApiResourceNames.g.cs
  apis/Google.Analytics.Data.V1Alpha/Google.Analytics.Data.V1Alpha/Data.g.cs
  apis/Google.Analytics.Data.V1Alpha/Google.Analytics.Data.V1Alpha/Google.Analytics.Data.V1Alpha.csproj
  apis/Google.Analytics.Data.V1Alpha/docs/history.md
  apis/Google.Analytics.Data.V1Alpha/docs/index.md
  apis/Google.Analytics.Data.V1Alpha/gapic_metadata.json
  apis/Google.Analytics.Data.V1Alpha/synth.metadata
  apis/Google.Analytics.Data.V1Alpha/synth.py
  apis/apis.json
Labels: cla: yes, allow breaking changes

#7256 chore: Generate OwlBot config files
  apis/Google.Cloud.ContactCenterInsights.V1/.OwlBot.yaml
  apis/Google.Cloud.Dialogflow.Cx.V3/.OwlBot.yaml
  apis/Google.Cloud.Firestore.V1/.OwlBot.yaml
Labels: cla: yes

#7261 Release Google.Cloud.ContactCenterInsights.V1 version 1.0.0-beta03
  apis/Google.Cloud.ContactCenterInsights.V1/Google.Cloud.ContactCenterInsights.V1/Google.Cloud.ContactCenterInsights.V1.csproj
  apis/Google.Cloud.ContactCenterInsights.V1/docs/history.md
  apis/apis.json
  tools/Google.Cloud.Tools.ReleaseManager/History/GitCommit.cs
Labels: cla: yes, autorelease: pending, automerge: exact

#7259 fix: Fix diff checker when we're building on a stable release
  tools/Google.Cloud.Tools.ReleaseManager.Tests/CheckVersionCompatibilityCommandTest.cs
  tools/Google.Cloud.Tools.ReleaseManager/CheckVersionCompatibilityCommand.cs
Labels: cla: yes

#7260 chore: Update GAPIC generator to 1.3.11
  toolversions.sh
Labels: cla: yes

#7265 chore: Add regeneration to skippable commit list
  tools/Google.Cloud.Tools.ReleaseManager/History/overrides.json
Labels: cla: yes

#7264 Release Google.Cloud.Storage.V1 version 3.6.0
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.IntegrationTests/Google.Cloud.Storage.V1.IntegrationTests.csproj
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.Snippets/Google.Cloud.Storage.V1.Snippets.csproj
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.Tests/Google.Cloud.Storage.V1.Tests.csproj
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.csproj
  apis/Google.Cloud.Storage.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7272 [apis/Google.Cloud.Filestore.V1] fix(filestore): add missing operation_metadata.proto import
  apis/Google.Cloud.Filestore.V1/Google.Cloud.Filestore.V1/CloudFilestoreManagerClient.g.cs
  apis/Google.Cloud.Filestore.V1/Google.Cloud.Filestore.V1/CloudFilestoreService.g.cs
  apis/Google.Cloud.Filestore.V1/synth.metadata
Labels: cla: yes, context: full

#7273 [apis/Google.Cloud.Kms.V1] feat: add OAEP+SHA1 to the list of supported algorithms
  apis/Google.Cloud.Kms.V1/Google.Cloud.Kms.V1.Tests/KeyManagementServiceClientTest.g.cs
  apis/Google.Cloud.Kms.V1/Google.Cloud.Kms.V1/Resources.g.cs
  apis/Google.Cloud.Kms.V1/synth.metadata
Labels: cla: yes, context: full

#7274 Smoke tests for Google.Cloud.Orchestration.Airflow.Service.V1
  apis/Google.Cloud.Orchestration.Airflow.Service.V1/smoketests.json
Labels: cla: yes

#7275 Release Google.Cloud.Orchestration.Airflow.Service.V1 version 1.0.0-beta01
  README.md
  apis/Google.Cloud.Orchestration.Airflow.Service.V1/.repo-metadata.json
  apis/Google.Cloud.Orchestration.Airflow.Service.V1/Google.Cloud.Orchestration.Airflow.Service.V1/Google.Cloud.Orchestration.Airflow.Service.V1.csproj
  apis/Google.Cloud.Orchestration.Airflow.Service.V1/docs/history.md
  apis/apis.json
Labels: cla: yes, autorelease: pending, automerge: exact

#7276 [apis/Google.Cloud.Kms.V1] feat: add RPC retry information for MacSign, MacVerify, and GenerateRandomBytes Committer: @bdhess
  apis/Google.Cloud.Kms.V1/Google.Cloud.Kms.V1/KeyManagementServiceClient.g.cs
  apis/Google.Cloud.Kms.V1/synth.metadata
Labels: cla: yes, context: full
