Repository googleapis/google-cloud-dotnet, pull requests merged in 2021-07, with the labels that each got.

#6701 [apis/Google.Cloud.Spanner.Admin.Database.V1] feat(spanner): add leader_options to InstanceConfig and default_leader to Database
  apis/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1.Tests/DatabaseAdminClientTest.g.cs
  apis/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1/SpannerDatabaseAdmin.g.cs
  apis/Google.Cloud.Spanner.Admin.Database.V1/synth.metadata
Labels: api: spanner, cla: yes, context: full

#6702 [apis/Google.Cloud.Spanner.Admin.Instance.V1] feat(spanner): add leader_options to InstanceConfig and default_leader to Database
  apis/Google.Cloud.Spanner.Admin.Instance.V1/Google.Cloud.Spanner.Admin.Instance.V1.Tests/InstanceAdminClientTest.g.cs
  apis/Google.Cloud.Spanner.Admin.Instance.V1/Google.Cloud.Spanner.Admin.Instance.V1/SpannerInstanceAdmin.g.cs
  apis/Google.Cloud.Spanner.Admin.Instance.V1/synth.metadata
Labels: api: spanner, cla: yes, context: full

#6703 Make common proto use conditional on the protos being present
  generateapis.sh
Labels: cla: yes

#6707 [apis/Google.Cloud.PubSub.V1] feat: Adding subscription properties to streaming pull response in third party pubsub.proto.
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/Pubsub.g.cs
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/PubsubGrpc.g.cs
  apis/Google.Cloud.PubSub.V1/synth.metadata
Labels: cla: yes, context: full

#6708 [apis/Google.Cloud.Datastream.V1Alpha1] chore: Add package/namespace options for C#, Ruby and PHP. This is a breaking change *only* for those languages, and packages for those languages have not been published yet.
  apis/Google.Cloud.Datastream.V1Alpha1/Google.Cloud.Datastream.V1Alpha1/DatastreamResources.g.cs
  apis/Google.Cloud.Datastream.V1Alpha1/synth.metadata
Labels: cla: yes, context: full

#6709 Release Google.Cloud.Eventarc.V1 version 1.0.0
  README.md
  apis/Google.Cloud.Eventarc.V1/.repo-metadata.json
  apis/Google.Cloud.Eventarc.V1/Google.Cloud.Eventarc.V1/Google.Cloud.Eventarc.V1.csproj
  apis/Google.Cloud.Eventarc.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6711 fix: Fully qualifies all alternative types/members for obsolete ones.
  apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore.IntegrationTests/Logging/LoggingTest.cs
  apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore/Logging/GoogleLoggerProvider.cs
  apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore/Logging/GoogleTraceProvider.cs
  apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore/Logging/IExternalTraceProvider.cs
  apis/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common/Trace/ManagedTracer.cs
Labels: cla: yes

#6712 Another attempt at using autosynth for Compute
  apis/Google.Cloud.Compute.V1/synth.metadata
  apis/Google.Cloud.Compute.V1/synth.py
  generateapis.sh
  tools/Google.Cloud.Tools.ReleaseManager/GenerateProjectsCommand.cs
Labels: cla: yes

#6714 Negate condition for cloning
  generateapis.sh
Labels: cla: yes

#6715 Log everything as we go for autosynth
  generateapis.sh
Labels: cla: yes

#6716 Fix autosynth: Return from the function, don't exit the process...
  generateapis.sh
Labels: cla: yes

#6718 Include googleapis for REGAPIC
  apis/Google.Cloud.Compute.V1/synth.metadata
  generateapis.sh
Labels: cla: yes

#6721 [apis/ServiceDirectory] chore: Remove protos for googleads v4 and v5, which have sunset
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#6722 Remove stray V1 file
  V1
Labels: cla: yes

#6723 [apis/Google.Cloud.PubSub.V1] feat: Add method signature for Subscriber.Pull without the deprecated return_immediately field.
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1.Snippets/SubscriberServiceApiClientSnippets.g.cs
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1.Tests/SubscriberServiceApiClientTest.g.cs
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/Pubsub.g.cs
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/SubscriberServiceApiClient.g.cs
  apis/Google.Cloud.PubSub.V1/synth.metadata
Labels: cla: yes, context: full

#6724 Remove use of obsolete methods in manually-written snippets
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1.Snippets/SubscriberServiceApiClientSnippets.cs
Labels: cla: yes

#6726 [apis/ServiceDirectory] feat: Initial commit for the Transcoder V1 client libraries.
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#6728 Release Spanner libraries version 3.11.0
  README.md
  apis/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1.csproj
  apis/Google.Cloud.Spanner.Admin.Instance.V1/Google.Cloud.Spanner.Admin.Instance.V1/Google.Cloud.Spanner.Admin.Instance.V1.csproj
  apis/Google.Cloud.Spanner.Common.V1/Google.Cloud.Spanner.Common.V1/Google.Cloud.Spanner.Common.V1.csproj
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.csproj
  apis/Google.Cloud.Spanner.Data/docs/history.md
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1.csproj
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6729 [apis/Google.Analytics.Data.V1Beta] feat: add `minute_ranges` field to `RunRealtimeReportRequest` object which can be used to specify the time range (in minutes) for realtime report queries docs: document the increase from 8 to 9 of the number of all
  apis/Google.Analytics.Data.V1Beta/Google.Analytics.Data.V1Beta.Snippets/BetaAnalyticsDataClientSnippets.g.cs
  apis/Google.Analytics.Data.V1Beta/Google.Analytics.Data.V1Beta.Tests/BetaAnalyticsDataClientTest.g.cs
  apis/Google.Analytics.Data.V1Beta/Google.Analytics.Data.V1Beta/AnalyticsDataApi.g.cs
  apis/Google.Analytics.Data.V1Beta/Google.Analytics.Data.V1Beta/Data.g.cs
  apis/Google.Analytics.Data.V1Beta/synth.metadata
Labels: cla: yes, context: full

#6730 [apis/Google.Cloud.Container.V1] feat: allow updating security group on existing clusters
  apis/Google.Cloud.Container.V1/Google.Cloud.Container.V1/ClusterService.g.cs
  apis/Google.Cloud.Container.V1/synth.metadata
Labels: cla: yes, context: full

#6731 [apis/Google.Cloud.Datastore.Admin.V1] feat: Publish message definitions for new Cloud Datastore migration logging steps.
  apis/Google.Cloud.Datastore.Admin.V1/Google.Cloud.Datastore.Admin.V1/Migration.g.cs
  apis/Google.Cloud.Datastore.Admin.V1/synth.metadata
Labels: cla: yes, context: full

#6732 [apis/Google.Cloud.SecretManager.V1] feat: Tune Secret Manager auto retry parameters
  apis/Google.Cloud.SecretManager.V1/Google.Cloud.SecretManager.V1/SecretManagerServiceClient.g.cs
  apis/Google.Cloud.SecretManager.V1/synth.metadata
Labels: cla: yes, context: full

#6733 [apis/Google.Cloud.Video.Transcoder.V1] feat: Enables generation of client libraries for C#, php and ruby.
  apis/Google.Cloud.Video.Transcoder.V1/Google.Cloud.Video.Transcoder.V1/Services.g.cs
  apis/Google.Cloud.Video.Transcoder.V1/synth.metadata
Labels: cla: yes, context: full

#6735 [apis/Google.Cloud.BigQuery.Connection.V1] feat: add cloud spanner connection support
  apis/Google.Cloud.BigQuery.Connection.V1/Google.Cloud.BigQuery.Connection.V1.Tests/ConnectionServiceClientTest.g.cs
  apis/Google.Cloud.BigQuery.Connection.V1/Google.Cloud.BigQuery.Connection.V1/Connection.g.cs
  apis/Google.Cloud.BigQuery.Connection.V1/Google.Cloud.BigQuery.Connection.V1/ConnectionGrpc.g.cs
  apis/Google.Cloud.BigQuery.Connection.V1/synth.metadata
Labels: cla: yes, context: full

#6736 [apis/ServiceDirectory] chore: publish Storage v2 API artifacts
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#6737 chore(docs): update client library help title case
  docs/devsite-help/toc.yml
Labels: cla: yes

#6738 [apis/Google.Cloud.AIPlatform.V1] feat: Adds additional_experiments field to AutoMlTablesInputs feat: Adds two new ModelType constants for Video Action Recognition training jobs
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/Schema/Predict/Instance/ImageClassification.g.cs
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/Schema/Predict/Instance/ImageObjectDetection.g.cs
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/Schema/Predict/Instance/TextExtraction.g.cs
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/Schema/Predict/Params/VideoClassification.g.cs
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/Schema/Predict/Prediction/Classification.g.cs
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/Schema/TrainingJob/Definition/AutomlTables.g.cs
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/Schema/TrainingJob/Definition/AutomlVideoActionRecognition.g.cs
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/Schema/TrainingJob/Definition/ExportEvaluatedDataItemsConfig.g.cs
  apis/Google.Cloud.AIPlatform.V1/synth.metadata
Labels: cla: yes, context: full

#6739 Start generating canonical links
  docs/builddocs.sh
Labels: cla: yes

#6744 [apis/ServiceDirectory] docs: fixed broken links
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#6745 Explicitly use Google.Protobuf.WellKnownTypes.Value in ValueConverter
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/ValueConverter.cs
Labels: cla: yes

#6746 Fix links between APIs
  apis/Google.Cloud.ErrorReporting.V1Beta1/docs/index.md
  apis/Google.Cloud.Language.V1/docs/index.md
  apis/Google.Cloud.Logging.V2/docs/index.md
  apis/Google.Cloud.Spanner.Admin.Database.V1/docs/index.md
  apis/Google.Cloud.Spanner.Admin.Instance.V1/docs/index.md
  apis/Google.Cloud.Spanner.Data/docs/index.md
  apis/Google.Cloud.Spanner.V1/docs/index.md
  uploaddocs.sh
Labels: cla: yes

#6747 [apis/Google.Cloud.AIPlatform.V1] feat!: Removes AcceleratorType.TPU_V2 and TPU_V3 constants feat: Adds AcceleratorType.NVIDIA_TESLA_A100 constant feat: Adds BigQuery output table field to batch prediction job output config feat: Adds JobState.JOB_ST
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1.Snippets/PipelineServiceClientSnippets.g.cs
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1.Snippets/PredictionServiceClientSnippets.g.cs
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1.Tests/JobServiceClientTest.g.cs
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1.Tests/PipelineServiceClientTest.g.cs
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1.Tests/PredictionServiceClientTest.g.cs
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/AcceleratorType.g.cs
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/Artifact.g.cs
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/ArtifactResourceNames.g.cs
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/BatchPredictionJob.g.cs
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/Context.g.cs
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/ContextResourceNames.g.cs
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/CustomJob.g.cs
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/CustomJobResourceNames.g.cs
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/Execution.g.cs
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/ExecutionResourceNames.g.cs
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/Io.g.cs
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/JobState.g.cs
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/MachineResources.g.cs
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/PipelineJob.g.cs
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/PipelineJobResourceNames.g.cs
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/PipelineService.g.cs
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/PipelineServiceClient.g.cs
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/PipelineServiceGrpc.g.cs
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/PipelineServiceResourceNames.g.cs
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/PredictionService.g.cs
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/PredictionServiceClient.g.cs
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/Study.g.cs
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/StudyResourceNames.g.cs
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/Value.g.cs
  apis/Google.Cloud.AIPlatform.V1/gapic_metadata.json
  apis/Google.Cloud.AIPlatform.V1/synth.metadata
Labels: cla: yes, context: full

#6749 Remove GitHub pages rewriting tool
  docs/Google.Cloud.DocTools.sln
  tools/Google.Cloud.Tools.RewriteGitHubPages/Google.Cloud.Tools.RewriteGitHubPages.csproj
  tools/Google.Cloud.Tools.RewriteGitHubPages/Program.cs
Labels: cla: yes

#6750 Fix link canonicalizer for Google.Cloud.Common package
  tools/Google.Cloud.Tools.GenerateCanonicalLinks.Tests/CanonicalizerTest.cs
  tools/Google.Cloud.Tools.GenerateCanonicalLinks/Canonicalizer.cs
Labels: cla: yes

#6752 [apis/Google.Cloud.ResourceSettings.V1] feat:Publish Cloud ResourceSettings v1 API
  apis/Google.Cloud.ResourceSettings.V1/Google.Cloud.ResourceSettings.V1/ResourceSettingsServiceClient.g.cs
  apis/Google.Cloud.ResourceSettings.V1/synth.metadata
Labels: cla: yes, context: full

#6753 [apis/Google.Cloud.Security.PrivateCA.V1] fix!: mark some bools as optional, correct response type of DeleteCaPool
  apis/Google.Cloud.Security.PrivateCA.V1/Google.Cloud.Security.PrivateCA.V1.Snippets/CertificateAuthorityServiceClientSnippets.g.cs
  apis/Google.Cloud.Security.PrivateCA.V1/Google.Cloud.Security.PrivateCA.V1/CertificateAuthorityServiceClient.g.cs
  apis/Google.Cloud.Security.PrivateCA.V1/Google.Cloud.Security.PrivateCA.V1/Resources.g.cs
  apis/Google.Cloud.Security.PrivateCA.V1/Google.Cloud.Security.PrivateCA.V1/Service.g.cs
  apis/Google.Cloud.Security.PrivateCA.V1/synth.metadata
Labels: cla: yes, context: full

#6754 Release Google.Cloud.Security.PrivateCA.V1 version 2.0.0
  README.md
  apis/Google.Cloud.Security.PrivateCA.V1/Google.Cloud.Security.PrivateCA.V1/Google.Cloud.Security.PrivateCA.V1.csproj
  apis/Google.Cloud.Security.PrivateCA.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6755 Update docfx YAML docs to include isExternal references
  tools/Google.Cloud.Tools.Common/Google.Cloud.Tools.Common.csproj
  tools/Google.Cloud.Tools.PostProcessDevSite/Program.cs
Labels: cla: yes

#6756 Release Google.Cloud.Common version 1.0.0
  README.md
  apis/Google.Cloud.Common/.repo-metadata.json
  apis/Google.Cloud.Common/Google.Cloud.Common/Google.Cloud.Common.csproj
  apis/Google.Cloud.Common/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6757 Release Google.Cloud.Iap.V1 version 1.0.0
  README.md
  apis/Google.Cloud.Iap.V1/.repo-metadata.json
  apis/Google.Cloud.Iap.V1/Google.Cloud.Iap.V1/Google.Cloud.Iap.V1.csproj
  apis/Google.Cloud.Iap.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6760 Release Google.Cloud.Filestore.V1 version 1.0.0
  README.md
  apis/Google.Cloud.Filestore.V1/.repo-metadata.json
  apis/Google.Cloud.Filestore.V1/Google.Cloud.Filestore.V1/Google.Cloud.Filestore.V1.csproj
  apis/Google.Cloud.Filestore.V1/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6761 Release Google.Cloud.ResourceManager.V3 version 1.0.0
  README.md
  apis/Google.Cloud.ResourceManager.V3/.repo-metadata.json
  apis/Google.Cloud.ResourceManager.V3/Google.Cloud.ResourceManager.V3/Google.Cloud.ResourceManager.V3.csproj
  apis/Google.Cloud.ResourceManager.V3/docs/history.md
  apis/apis.json
  docs/root/index.md
Labels: autorelease: pending, cla: yes

#6763 [apis/ServiceDirectory] feat: OSConfig AgentEndpoint: add basic os info to RegisterAgentRequest, add WindowsApplication type to Inventory
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#6762 [apis/Google.Cloud.CloudBuild.V1] feat: add a WorkerPools API
  apis/Google.Cloud.CloudBuild.V1/Google.Cloud.CloudBuild.V1.Snippets/CloudBuildClientSnippets.g.cs
  apis/Google.Cloud.CloudBuild.V1/Google.Cloud.CloudBuild.V1.Tests/CloudBuildClientTest.g.cs
  apis/Google.Cloud.CloudBuild.V1/Google.Cloud.CloudBuild.V1/CloudBuildClient.g.cs
  apis/Google.Cloud.CloudBuild.V1/Google.Cloud.CloudBuild.V1/Cloudbuild.g.cs
  apis/Google.Cloud.CloudBuild.V1/Google.Cloud.CloudBuild.V1/CloudbuildGrpc.g.cs
  apis/Google.Cloud.CloudBuild.V1/Google.Cloud.CloudBuild.V1/CloudbuildResourceNames.g.cs
  apis/Google.Cloud.CloudBuild.V1/synth.metadata
Labels: cla: yes, context: full

#6765 [apis/Google.Cloud.AIPlatform.V1] feat!: Removes breaking change from v1 version of AI Platform protos
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1.Snippets/PredictionServiceClientSnippets.g.cs
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1.Tests/PredictionServiceClientTest.g.cs
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/PredictionService.g.cs
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/PredictionServiceClient.g.cs
  apis/Google.Cloud.AIPlatform.V1/synth.metadata
Labels: cla: yes, context: full

#6766 [apis/Google.Cloud.CloudBuild.V1] feat: Implementation of Build Failure Info: - Added message FailureInfo field
  apis/Google.Cloud.CloudBuild.V1/Google.Cloud.CloudBuild.V1.Tests/CloudBuildClientTest.g.cs
  apis/Google.Cloud.CloudBuild.V1/Google.Cloud.CloudBuild.V1/Cloudbuild.g.cs
  apis/Google.Cloud.CloudBuild.V1/synth.metadata
Labels: cla: yes, context: full

#6767 [apis/ServiceDirectory] feat: Adds BigQuery output table field to batch prediction job output config feat: Adds Feature Store features feat: Adds CustomJob.web_access_uris, CustomJob.enable_web_access fields feat: Adds Endpoint.network, Endpoint.priv
  apis/ServiceDirectory/directory.json
  apis/ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#6764 tests(spanner): fix optimizer stats package IT
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.IntegrationTests/QueryOptionsTests.cs
Labels: api: spanner, cla: yes

#6616 fix: synchronize access to the underlying transaction for ambient transactions
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.IntegrationTests/TransactionScopeTests.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.Tests/Google.Cloud.Spanner.Data.Tests.csproj
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.Tests/SpannerCommandTests.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/VolatileResourceManager.cs
Labels: cla: yes

#6771 Add an "allow breaking changes" label to avoid failing the GitHub check
  .github/workflows/diff-pr.yml
  detect-pr-changes.sh
Labels: cla: yes

#6770 feat: Adds context trace information to error log entries if there's any.
  apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore.IntegrationTests/ErrorReporting/ErrorReportingTest.cs
  apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore/GoogleDiagnosticsStartupFilter.cs
  apis/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common.Tests/ErrorReporting/ErrorReportingContextExceptionLoggerTest.cs
  apis/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common/ErrorReporting/ContextExceptionLogger.cs
  apis/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common/ErrorReporting/ErrorReportingContextExceptionLogger.cs
  apis/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common/Logging/GoogleLogger.cs
  apis/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common/Logging/LogEntryExtensions.cs
Labels: allow breaking changes, cla: yes

#6773 Rerun diff action when labels change
  .github/workflows/diff-pr.yml
Labels: cla: yes

#6772 Release Diagnostics libraries version 4.3.0-beta02
  README.md
  apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore.csproj
  apis/Google.Cloud.Diagnostics.AspNetCore/docs/history.md
  apis/Google.Cloud.Diagnostics.AspNetCore3/Google.Cloud.Diagnostics.AspNetCore3/Google.Cloud.Diagnostics.AspNetCore3.csproj
  apis/Google.Cloud.Diagnostics.AspNetCore3/docs/history.md
  apis/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common.csproj
  apis/apis.json
  docs/root/index.md
Labels: allow breaking changes, autorelease: pending, cla: yes

#6774 Release Diagnostics libraries version 4.3.0-beta03
  README.md
  apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore.csproj
  apis/Google.Cloud.Diagnostics.AspNetCore/docs/history.md
  apis/Google.Cloud.Diagnostics.AspNetCore3/Google.Cloud.Diagnostics.AspNetCore3/Google.Cloud.Diagnostics.AspNetCore3.csproj
  apis/Google.Cloud.Diagnostics.AspNetCore3/docs/history.md
  apis/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common.csproj
  apis/apis.json
  docs/root/index.md
Labels: allow breaking changes, autorelease: pending, cla: yes

#6778 Don't run the diff action if the PR has been merged
  .github/workflows/diff-pr.yml
Labels: cla: yes

#6781 [apis/Google.Cloud.Asset.V1] feat!: *Change metadata field for the AnalyzeIamPolicyLongrunning. feat: Add AnalyzeMove API. feat: Add read_mask field for SearchAllResourcesRequest feat：Add VersionedResource/AttachedResource fields for ResourceSearchRe
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1.Snippets/AssetServiceClientSnippets.g.cs
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1.Tests/AssetServiceClientTest.g.cs
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1/AssetService.g.cs
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1/AssetServiceClient.g.cs
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1/AssetServiceGrpc.g.cs
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1/Assets.g.cs
  apis/Google.Cloud.Asset.V1/gapic_metadata.json
  apis/Google.Cloud.Asset.V1/synth.metadata
Labels: allow breaking changes, cla: yes, context: full

#6784 Release Google.Analytics.Data.V1Beta version 1.0.0-beta04
  README.md
  apis/Google.Analytics.Data.V1Beta/Google.Analytics.Data.V1Beta/Google.Analytics.Data.V1Beta.csproj
  apis/Google.Analytics.Data.V1Beta/docs/history.md
  apis/apis.json
Labels: autorelease: pending, cla: yes

#6785 [apis/Google.Cloud.SecurityCenter.V1] feat: add finding_class and indicator fields in Finding
  apis/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1.Tests/SecurityCenterClientTest.g.cs
  apis/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1/Finding.g.cs
  apis/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1/Indicator.g.cs
  apis/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1/SecurityCenterClient.g.cs
  apis/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1/SecuritycenterService.g.cs
  apis/Google.Cloud.SecurityCenter.V1/synth.metadata
Labels: cla: yes, context: full

#6786 Release Google.Cloud.ServiceDirectory.V1Beta1 version 1.0.0-beta05
  README.md
  apis/Google.Cloud.ServiceDirectory.V1Beta1/Google.Cloud.ServiceDirectory.V1Beta1/Google.Cloud.ServiceDirectory.V1Beta1.csproj
  apis/Google.Cloud.ServiceDirectory.V1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, cla: yes

#6788 [apis/Google.Cloud.SecretManager.V1] feat: In Secret Manager, users can now use filter to customize the output of ListSecrets/ListSecretVersions calls
  apis/Google.Cloud.SecretManager.V1/Google.Cloud.SecretManager.V1.Snippets/SecretManagerServiceClientSnippets.g.cs
  apis/Google.Cloud.SecretManager.V1/Google.Cloud.SecretManager.V1/Service.g.cs
  apis/Google.Cloud.SecretManager.V1/synth.metadata
Labels: cla: yes, context: full

#6789 [apis/Google.Cloud.Speech.V1P1Beta1] feat: add total_billed_time response field. fix!: phrase_set_id is required field in CreatePhraseSetRequest. fix!: custom_class_id is required field in CreateCustomClassRequest.
  apis/Google.Cloud.Speech.V1P1Beta1/Google.Cloud.Speech.V1P1Beta1.Tests/SpeechClientTest.g.cs
  apis/Google.Cloud.Speech.V1P1Beta1/Google.Cloud.Speech.V1P1Beta1/AdaptationClient.g.cs
  apis/Google.Cloud.Speech.V1P1Beta1/Google.Cloud.Speech.V1P1Beta1/CloudSpeech.g.cs
  apis/Google.Cloud.Speech.V1P1Beta1/Google.Cloud.Speech.V1P1Beta1/CloudSpeechAdaptation.g.cs
  apis/Google.Cloud.Speech.V1P1Beta1/Google.Cloud.Speech.V1P1Beta1/Resource.g.cs
  apis/Google.Cloud.Speech.V1P1Beta1/Google.Cloud.Speech.V1P1Beta1/ResourceResourceNames.g.cs
  apis/Google.Cloud.Speech.V1P1Beta1/synth.metadata
Labels: cla: yes, context: full

#6791 Add Google.LongRunning dependency to Google.Identity.AccessContextManager.V1
  README.md
  apis/Google.Identity.AccessContextManager.V1/Google.Identity.AccessContextManager.V1/Google.Identity.AccessContextManager.V1.csproj
  apis/apis.json
Labels: cla: yes

#6793 [apis/Google.Identity.AccessContextManager.V1] chore: publish Access Context Manager API v1
  apis/Google.Identity.AccessContextManager.V1/Google.Identity.AccessContextManager.V1/AccessContextManager.cs
  apis/Google.Identity.AccessContextManager.V1/Google.Identity.AccessContextManager.V1/AccessLevel.cs
  apis/Google.Identity.AccessContextManager.V1/Google.Identity.AccessContextManager.V1/AccessPolicy.cs
  apis/Google.Identity.AccessContextManager.V1/Google.Identity.AccessContextManager.V1/GcpUserAccessBinding.cs
  apis/Google.Identity.AccessContextManager.V1/Google.Identity.AccessContextManager.V1/ServicePerimeter.cs
  apis/Google.Identity.AccessContextManager.V1/synth.metadata
Labels: cla: yes, context: full

#6792 Fix docs build for cloud.google.com
  docs/builddocs.sh
Labels: cla: yes

#6794 Release Google.Cloud.Speech.V1P1Beta1 version 2.0.0-beta05
  README.md
  apis/Google.Cloud.Speech.V1P1Beta1/Google.Cloud.Speech.V1P1Beta1/Google.Cloud.Speech.V1P1Beta1.csproj
  apis/Google.Cloud.Speech.V1P1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, cla: yes

#6799 [apis/Google.Cloud.DataCatalog.V1] feat: Added support for BigQuery connections entries feat: Added support for BigQuery routines entries feat: Added usage_signal field feat: Added labels field feat: Added ReplaceTaxonomy in Policy Tag Manager Serial
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1.Snippets/PolicyTagManagerSerializationClientSnippets.g.cs
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1.Tests/DataCatalogClientTest.g.cs
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1.Tests/PolicyTagManagerSerializationClientTest.g.cs
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/Bigquery.g.cs
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/Common.g.cs
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/DataCatalogClient.g.cs
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/DataSource.g.cs
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/Datacatalog.g.cs
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/DatacatalogGrpc.g.cs
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/GcsFilesetSpec.g.cs
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/PolicyTagManagerClient.g.cs
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/PolicyTagManagerSerializationClient.g.cs
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/Policytagmanager.g.cs
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/PolicytagmanagerGrpc.g.cs
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/Policytagmanagerserialization.g.cs
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/PolicytagmanagerserializationGrpc.g.cs
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/PolicytagmanagerserializationResourceNames.g.cs
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/Schema.g.cs
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/Search.g.cs
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/TableSpec.g.cs
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/Tags.g.cs
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/Timestamps.g.cs
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/Usage.g.cs
  apis/Google.Cloud.DataCatalog.V1/gapic_metadata.json
  apis/Google.Cloud.DataCatalog.V1/synth.metadata
Labels: cla: yes, context: full

#6814 [apis/Google.Cloud.Filestore.V1] docs(filestore): Fix various formatting issues and broken links
  apis/Google.Cloud.Filestore.V1/Google.Cloud.Filestore.V1/CloudFilestoreManagerClient.g.cs
  apis/Google.Cloud.Filestore.V1/Google.Cloud.Filestore.V1/CloudFilestoreService.g.cs
  apis/Google.Cloud.Filestore.V1/synth.metadata
Labels: cla: yes, context: full

#6812 [apis/Google.Cloud.AssuredWorkloads.V1Beta1] feat: Add EU Regions And Support compliance regime
  apis/Google.Cloud.AssuredWorkloads.V1Beta1/Google.Cloud.AssuredWorkloads.V1Beta1.Tests/AssuredWorkloadsServiceClientTest.g.cs
  apis/Google.Cloud.AssuredWorkloads.V1Beta1/Google.Cloud.AssuredWorkloads.V1Beta1/AssuredworkloadsV1Beta1.g.cs
  apis/Google.Cloud.AssuredWorkloads.V1Beta1/synth.metadata
Labels: cla: yes, context: full

#6816 Remove tools we never use any more
  adhoc/Google.Cloud.MetadataTesting/Google.Cloud.MetadataTesting.csproj
  adhoc/Google.Cloud.MetadataTesting/Program.cs
  adhoc/Google.Cloud.ScopeTesting/Api.cs
  adhoc/Google.Cloud.ScopeTesting/Google.Cloud.ScopeTesting.csproj
  adhoc/Google.Cloud.ScopeTesting/Program.cs
  adhoc/MetadataTesting.sln
  adhoc/README.md
  adhoc/ScopeTesting.sln
Labels: cla: yes

#6818 Remove the old release note generator
  tools/Google.Cloud.Tools.GenerateReleaseNotes/Google.Cloud.Tools.GenerateReleaseNotes.csproj
  tools/Google.Cloud.Tools.GenerateReleaseNotes/Program.cs
Labels: cla: yes

#6813 [apis/Google.Cloud.CloudBuild.V1] docs: Add a new build phase `SETUPBUILD` for timing information
  apis/Google.Cloud.CloudBuild.V1/Google.Cloud.CloudBuild.V1/Cloudbuild.g.cs
  apis/Google.Cloud.CloudBuild.V1/synth.metadata
Labels: allow breaking changes, cla: yes, context: full

#6815 [apis/Google.Cloud.Retail.V2] feat: Add restricted Retail Search features for Retail API v2.
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2.Snippets/CatalogServiceClientSnippets.g.cs
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2.Snippets/CompletionServiceClientSnippets.g.cs
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2.Snippets/ProductServiceClientSnippets.g.cs
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2.Snippets/SearchServiceClientSnippets.g.cs
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2.Snippets/UserEventServiceClientSnippets.g.cs
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2.Tests/CatalogServiceClientTest.g.cs
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2.Tests/CompletionServiceClientTest.g.cs
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2.Tests/ProductServiceClientTest.g.cs
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2.Tests/SearchServiceClientTest.g.cs
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2.Tests/UserEventServiceClientTest.g.cs
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/Catalog.g.cs
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/CatalogService.g.cs
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/CatalogServiceClient.g.cs
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/CatalogServiceGrpc.g.cs
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/CatalogServiceResourceNames.g.cs
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/Common.g.cs
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/CompletionService.g.cs
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/CompletionServiceClient.g.cs
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/CompletionServiceGrpc.g.cs
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/CompletionServiceResourceNames.g.cs
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/ImportConfig.g.cs
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/ImportConfigResourceNames.g.cs
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/PredictionService.g.cs
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/Product.g.cs
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/ProductService.g.cs
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/ProductServiceClient.g.cs
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/ProductServiceGrpc.g.cs
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/ProductServiceResourceNames.g.cs
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/PurgeConfig.g.cs
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/SearchService.g.cs
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/SearchServiceClient.g.cs
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/SearchServiceGrpc.g.cs
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/SearchServiceResourceNames.g.cs
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/UserEvent.g.cs
  apis/Google.Cloud.Retail.V2/gapic_metadata.json
  apis/Google.Cloud.Retail.V2/synth.metadata
Labels: cla: yes, context: full

#6819 Release Google.Cloud.CloudBuild.V1 version 1.3.0
  README.md
  apis/Google.Cloud.CloudBuild.V1/Google.Cloud.CloudBuild.V1/Google.Cloud.CloudBuild.V1.csproj
  apis/Google.Cloud.CloudBuild.V1/docs/history.md
  apis/apis.json
Labels: allow breaking changes, autorelease: pending, cla: yes

#6846 [CHANGE ME] Re-generated apis/Google.Cloud.Retail.V2 to pick up changes in the API or client library generator.
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/SearchService.g.cs
  apis/Google.Cloud.Retail.V2/synth.metadata
Labels: cla: yes, context: full

#6844 [apis/Google.Cloud.BinaryAuthorization.V1Beta1] docs: Replace "global policy" with "system policy" in Binary Authorization documentation
  apis/Google.Cloud.BinaryAuthorization.V1Beta1/Google.Cloud.BinaryAuthorization.V1Beta1/Resources.g.cs
  apis/Google.Cloud.BinaryAuthorization.V1Beta1/synth.metadata
Labels: cla: yes, context: full

#6845 [apis/Google.Cloud.Dialogflow.Cx.V3] feat: add advanced settings for agent level feat: add rollout config, state and failure reason for experiment feat: add insights export settings for security setting feat: add language code for streaming recogniti
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3.Tests/AgentsClientTest.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3.Tests/ExperimentsClientTest.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3.Tests/SecuritySettingsServiceClientTest.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/AdvancedSettings.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Agent.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Experiment.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Flow.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Fulfillment.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Intent.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Page.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/SecuritySettings.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Session.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/SessionResourceNames.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Version.g.cs
  apis/Google.Cloud.Dialogflow.Cx.V3/synth.metadata
Labels: cla: yes, context: full
