Repository googleapis/google-cloud-dotnet, pull requests merged in 2022-06, with the labels that each got.

#8573 Release Google.LongRunning version 3.0.0
  apis/Google.LongRunning/Google.LongRunning/Google.LongRunning.csproj
  apis/Google.LongRunning/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8575 Release Google.Cloud.Location version 2.0.0
  apis/Google.Cloud.Location/Google.Cloud.Location/Google.Cloud.Location.csproj
  apis/Google.Cloud.Location/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8581 Release Google.Cloud.AccessApproval.V1 version 2.0.0
  apis/Google.Cloud.AccessApproval.V1/Google.Cloud.AccessApproval.V1/Google.Cloud.AccessApproval.V1.csproj
  apis/Google.Cloud.AccessApproval.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8580 Release Google.Area120.Tables.V1Alpha1 version 2.0.0-alpha01
  apis/Google.Area120.Tables.V1Alpha1/Google.Area120.Tables.V1Alpha1/Google.Area120.Tables.V1Alpha1.csproj
  apis/Google.Area120.Tables.V1Alpha1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8579 Release Google.Analytics.Data.V1Beta version 2.0.0-beta01
  apis/Google.Analytics.Data.V1Beta/Google.Analytics.Data.V1Beta/Google.Analytics.Data.V1Beta.csproj
  apis/Google.Analytics.Data.V1Beta/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8583 Release Google.Cloud.BigQuery.DataTransfer.V1 version 4.0.0
  apis/Google.Cloud.BigQuery.DataTransfer.V1/Google.Cloud.BigQuery.DataTransfer.V1/Google.Cloud.BigQuery.DataTransfer.V1.csproj
  apis/Google.Cloud.BigQuery.DataTransfer.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8584 Release Google.Cloud.BigQuery.Reservation.V1 version 2.0.0
  apis/Google.Cloud.BigQuery.Reservation.V1/Google.Cloud.BigQuery.Reservation.V1/Google.Cloud.BigQuery.Reservation.V1.csproj
  apis/Google.Cloud.BigQuery.Reservation.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8587 Release Google.Cloud.Bigtable.Common.V2 version 3.0.0
  apis/Google.Cloud.Bigtable.Common.V2/Google.Cloud.Bigtable.Common.V2/Google.Cloud.Bigtable.Common.V2.csproj
  apis/Google.Cloud.Bigtable.Common.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending

#8588 Release Google.Cloud.Billing.Budgets.V1 version 2.0.0
  apis/Google.Cloud.Billing.Budgets.V1/Google.Cloud.Billing.Budgets.V1/Google.Cloud.Billing.Budgets.V1.csproj
  apis/Google.Cloud.Billing.Budgets.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8589 Release Google.Cloud.Billing.Budgets.V1Beta1 version 2.0.0-beta01
  apis/Google.Cloud.Billing.Budgets.V1Beta1/Google.Cloud.Billing.Budgets.V1Beta1/Google.Cloud.Billing.Budgets.V1Beta1.csproj
  apis/Google.Cloud.Billing.Budgets.V1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8586 Release Google.Cloud.BigQuery.Storage.V1 version 3.0.0
  apis/Google.Cloud.BigQuery.Storage.V1/Google.Cloud.BigQuery.Storage.V1/Google.Cloud.BigQuery.Storage.V1.csproj
  apis/Google.Cloud.BigQuery.Storage.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8591 Release Google.Cloud.BinaryAuthorization.V1Beta1 version 2.0.0-beta01
  apis/Google.Cloud.BinaryAuthorization.V1Beta1/Google.Cloud.BinaryAuthorization.V1Beta1/Google.Cloud.BinaryAuthorization.V1Beta1.csproj
  apis/Google.Cloud.BinaryAuthorization.V1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8585 Release Google.Cloud.BigQuery.V2 version 3.0.0
  apis/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2.csproj
  apis/Google.Cloud.BigQuery.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8582 Release Google.Cloud.ApigeeConnect.V1 version 2.0.0
  apis/Google.Cloud.ApigeeConnect.V1/Google.Cloud.ApigeeConnect.V1/Google.Cloud.ApigeeConnect.V1.csproj
  apis/Google.Cloud.ApigeeConnect.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8592 Release Google.Cloud.Common version 2.0.0
  apis/Google.Cloud.Common/Google.Cloud.Common/Google.Cloud.Common.csproj
  apis/Google.Cloud.Common/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8593 Release Google.Cloud.Container.V1 version 3.0.0
  apis/Google.Cloud.Container.V1/Google.Cloud.Container.V1/Google.Cloud.Container.V1.csproj
  apis/Google.Cloud.Container.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8594 Release Google.Cloud.DataQnA.V1Alpha version 2.0.0-alpha01
  apis/Google.Cloud.DataQnA.V1Alpha/Google.Cloud.DataQnA.V1Alpha/Google.Cloud.DataQnA.V1Alpha.csproj
  apis/Google.Cloud.DataQnA.V1Alpha/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8596 Release Google.Cloud.Datastore.V1 version 4.0.0
  apis/Google.Cloud.Datastore.V1/Google.Cloud.Datastore.V1/Google.Cloud.Datastore.V1.csproj
  apis/Google.Cloud.Datastore.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8598 Release Google.Cloud.Dlp.V2 version 4.0.0
  apis/Google.Cloud.Dlp.V2/Google.Cloud.Dlp.V2/Google.Cloud.Dlp.V2.csproj
  apis/Google.Cloud.Dlp.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8600 Release Google.Cloud.EssentialContacts.V1 version 2.0.0
  apis/Google.Cloud.EssentialContacts.V1/Google.Cloud.EssentialContacts.V1/Google.Cloud.EssentialContacts.V1.csproj
  apis/Google.Cloud.EssentialContacts.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8601 Release Google.Cloud.GkeConnect.Gateway.V1Beta1 version 2.0.0-beta01
  apis/Google.Cloud.GkeConnect.Gateway.V1Beta1/Google.Cloud.GkeConnect.Gateway.V1Beta1/Google.Cloud.GkeConnect.Gateway.V1Beta1.csproj
  apis/Google.Cloud.GkeConnect.Gateway.V1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8595 Release Google.Cloud.Dataflow.V1Beta3 version 2.0.0-beta01
  apis/Google.Cloud.Dataflow.V1Beta3/Google.Cloud.Dataflow.V1Beta3/Google.Cloud.Dataflow.V1Beta3.csproj
  apis/Google.Cloud.Dataflow.V1Beta3/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8604 Release Google.Cloud.Logging.Type version 4.0.0
  apis/Google.Cloud.Logging.Type/Google.Cloud.Logging.Type/Google.Cloud.Logging.Type.csproj
  apis/Google.Cloud.Logging.Type/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8603 Release Google.Cloud.Language.V1 version 3.0.0
  apis/Google.Cloud.Language.V1/Google.Cloud.Language.V1/Google.Cloud.Language.V1.csproj
  apis/Google.Cloud.Language.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8599 Release Google.Cloud.ErrorReporting.V1Beta1 version 3.0.0-beta01
  apis/Google.Cloud.ErrorReporting.V1Beta1/Google.Cloud.ErrorReporting.V1Beta1/Google.Cloud.ErrorReporting.V1Beta1.csproj
  apis/Google.Cloud.ErrorReporting.V1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8606 Release Google.Cloud.OrgPolicy.V1 version 3.0.0
  apis/Google.Cloud.OrgPolicy.V1/Google.Cloud.OrgPolicy.V1/Google.Cloud.OrgPolicy.V1.csproj
  apis/Google.Cloud.OrgPolicy.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8608 Release Google.Cloud.PhishingProtection.V1Beta1 version 2.0.0-beta01
  apis/Google.Cloud.PhishingProtection.V1Beta1/Google.Cloud.PhishingProtection.V1Beta1/Google.Cloud.PhishingProtection.V1Beta1.csproj
  apis/Google.Cloud.PhishingProtection.V1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8613 Release Google.Cloud.ResourceSettings.V1 version 2.0.0
  apis/Google.Cloud.ResourceSettings.V1/Google.Cloud.ResourceSettings.V1/Google.Cloud.ResourceSettings.V1.csproj
  apis/Google.Cloud.ResourceSettings.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8610 Release Google.Cloud.RecaptchaEnterprise.V1 version 2.0.0
  apis/Google.Cloud.RecaptchaEnterprise.V1/Google.Cloud.RecaptchaEnterprise.V1/Google.Cloud.RecaptchaEnterprise.V1.csproj
  apis/Google.Cloud.RecaptchaEnterprise.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8614 Release Google.Cloud.Scheduler.V1 version 3.0.0
  apis/Google.Cloud.Scheduler.V1/Google.Cloud.Scheduler.V1/Google.Cloud.Scheduler.V1.csproj
  apis/Google.Cloud.Scheduler.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8620 Release Google.Cloud.Video.Transcoder.V1 version 2.0.0
  apis/Google.Cloud.Video.Transcoder.V1/Google.Cloud.Video.Transcoder.V1/Google.Cloud.Video.Transcoder.V1.csproj
  apis/Google.Cloud.Video.Transcoder.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8609 Release Google.Cloud.Profiler.V2 version 2.0.0
  apis/Google.Cloud.Profiler.V2/Google.Cloud.Profiler.V2/Google.Cloud.Profiler.V2.csproj
  apis/Google.Cloud.Profiler.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8618 Release Google.Cloud.Trace.V2 version 3.0.0
  apis/Google.Cloud.Trace.V2/Google.Cloud.Trace.V2/Google.Cloud.Trace.V2.csproj
  apis/Google.Cloud.Trace.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8623 Release Google.Cloud.WebSecurityScanner.V1 version 2.0.0
  apis/Google.Cloud.WebSecurityScanner.V1/Google.Cloud.WebSecurityScanner.V1/Google.Cloud.WebSecurityScanner.V1.csproj
  apis/Google.Cloud.WebSecurityScanner.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8624 Release Google.Identity.AccessContextManager.Type version 2.0.0
  apis/Google.Identity.AccessContextManager.Type/Google.Identity.AccessContextManager.Type/Google.Identity.AccessContextManager.Type.csproj
  apis/Google.Identity.AccessContextManager.Type/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8605 Release Google.Cloud.MediaTranslation.V1Beta1 version 2.0.0-beta01
  apis/Google.Cloud.MediaTranslation.V1Beta1/Google.Cloud.MediaTranslation.V1Beta1/Google.Cloud.MediaTranslation.V1Beta1.csproj
  apis/Google.Cloud.MediaTranslation.V1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8621 Release Google.Cloud.WebRisk.V1 version 2.0.0
  apis/Google.Cloud.WebRisk.V1/Google.Cloud.WebRisk.V1/Google.Cloud.WebRisk.V1.csproj
  apis/Google.Cloud.WebRisk.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8622 Release Google.Cloud.WebRisk.V1Beta1 version 3.0.0-beta01
  apis/Google.Cloud.WebRisk.V1Beta1/Google.Cloud.WebRisk.V1Beta1/Google.Cloud.WebRisk.V1Beta1.csproj
  apis/Google.Cloud.WebRisk.V1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8607 Release Google.Cloud.OrgPolicy.V2 version 2.0.0
  apis/Google.Cloud.OrgPolicy.V2/Google.Cloud.OrgPolicy.V2/Google.Cloud.OrgPolicy.V2.csproj
  apis/Google.Cloud.OrgPolicy.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8611 Release Google.Cloud.RecaptchaEnterprise.V1Beta1 version 2.0.0-beta01
  apis/Google.Cloud.RecaptchaEnterprise.V1Beta1/Google.Cloud.RecaptchaEnterprise.V1Beta1/Google.Cloud.RecaptchaEnterprise.V1Beta1.csproj
  apis/Google.Cloud.RecaptchaEnterprise.V1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8615 Release Google.Cloud.TextToSpeech.V1 version 3.0.0
  apis/Google.Cloud.TextToSpeech.V1/Google.Cloud.TextToSpeech.V1/Google.Cloud.TextToSpeech.V1.csproj
  apis/Google.Cloud.TextToSpeech.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8627 Release Google.Cloud.AIPlatform.V1 version 2.0.0
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1.csproj
  apis/Google.Cloud.AIPlatform.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8628 Release Google.Cloud.AppEngine.V1 version 2.0.0
  apis/Google.Cloud.AppEngine.V1/Google.Cloud.AppEngine.V1/Google.Cloud.AppEngine.V1.csproj
  apis/Google.Cloud.AppEngine.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8626 Release Google.Cloud.ApiGateway.V1 version 2.0.0
  apis/Google.Cloud.ApiGateway.V1/Google.Cloud.ApiGateway.V1/Google.Cloud.ApiGateway.V1.csproj
  apis/Google.Cloud.ApiGateway.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8631 Release Google.Cloud.AssuredWorkloads.V1 version 2.0.0
  apis/Google.Cloud.AssuredWorkloads.V1/Google.Cloud.AssuredWorkloads.V1/Google.Cloud.AssuredWorkloads.V1.csproj
  apis/Google.Cloud.AssuredWorkloads.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8633 Release Google.Cloud.Audit version 2.0.0
  apis/Google.Cloud.Audit/Google.Cloud.Audit/Google.Cloud.Audit.csproj
  apis/Google.Cloud.Audit/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8629 Release Google.Cloud.ArtifactRegistry.V1 version 2.0.0
  apis/Google.Cloud.ArtifactRegistry.V1/Google.Cloud.ArtifactRegistry.V1/Google.Cloud.ArtifactRegistry.V1.csproj
  apis/Google.Cloud.ArtifactRegistry.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8637 Release Google.Cloud.Bigtable.V2 version 3.0.0
  apis/Google.Cloud.Bigtable.V2/Google.Cloud.Bigtable.V2/Google.Cloud.Bigtable.V2.csproj
  apis/Google.Cloud.Bigtable.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8642 Release Google.Cloud.Compute.V1 version 2.0.0
  apis/Google.Cloud.Compute.V1/Google.Cloud.Compute.V1/Google.Cloud.Compute.V1.csproj
  apis/Google.Cloud.Compute.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8640 Release Google.Cloud.CloudBuild.V1 version 2.0.0
  apis/Google.Cloud.CloudBuild.V1/Google.Cloud.CloudBuild.V1/Google.Cloud.CloudBuild.V1.csproj
  apis/Google.Cloud.CloudBuild.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8645 Release Google.Cloud.DataFusion.V1 version 2.0.0
  apis/Google.Cloud.DataFusion.V1/Google.Cloud.DataFusion.V1/Google.Cloud.DataFusion.V1.csproj
  apis/Google.Cloud.DataFusion.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8647 Release Google.Cloud.Dataplex.V1 version 2.0.0
  apis/Google.Cloud.Dataplex.V1/Google.Cloud.Dataplex.V1/Google.Cloud.Dataplex.V1.csproj
  apis/Google.Cloud.Dataplex.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8643 Release Google.Cloud.ContactCenterInsights.V1 version 2.0.0
  apis/Google.Cloud.ContactCenterInsights.V1/Google.Cloud.ContactCenterInsights.V1/Google.Cloud.ContactCenterInsights.V1.csproj
  apis/Google.Cloud.ContactCenterInsights.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8649 Release Google.Cloud.Datastore.Admin.V1 version 2.0.0
  apis/Google.Cloud.Datastore.Admin.V1/Google.Cloud.Datastore.Admin.V1/Google.Cloud.Datastore.Admin.V1.csproj
  apis/Google.Cloud.Datastore.Admin.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8651 Release Google.Cloud.Datastream.V1Alpha1 version 2.0.0-alpha01
  apis/Google.Cloud.Datastream.V1Alpha1/Google.Cloud.Datastream.V1Alpha1/Google.Cloud.Datastream.V1Alpha1.csproj
  apis/Google.Cloud.Datastream.V1Alpha1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8653 Release Google.Cloud.Deploy.V1 version 2.0.0
  apis/Google.Cloud.Deploy.V1/Google.Cloud.Deploy.V1/Google.Cloud.Deploy.V1.csproj
  apis/Google.Cloud.Deploy.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8632 Release Google.Cloud.AssuredWorkloads.V1Beta1 version 2.0.0-beta01
  apis/Google.Cloud.AssuredWorkloads.V1Beta1/Google.Cloud.AssuredWorkloads.V1Beta1/Google.Cloud.AssuredWorkloads.V1Beta1.csproj
  apis/Google.Cloud.AssuredWorkloads.V1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8652 Release Google.Cloud.Debugger.V2 version 3.0.0
  apis/Google.Cloud.Debugger.V2/Google.Cloud.Debugger.V2/Google.Cloud.Debugger.V2.csproj
  apis/Google.Cloud.Debugger.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8655 Release Google.Cloud.Dialogflow.V2 version 4.0.0
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2.csproj
  apis/Google.Cloud.Dialogflow.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8636 Release Google.Cloud.Bigtable.Admin.V2 version 3.0.0
  apis/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2.csproj
  apis/Google.Cloud.Bigtable.Admin.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8646 Release Google.Cloud.DataLabeling.V1Beta1 version 2.0.0-beta01
  apis/Google.Cloud.DataLabeling.V1Beta1/Google.Cloud.DataLabeling.V1Beta1/Google.Cloud.DataLabeling.V1Beta1.csproj
  apis/Google.Cloud.DataLabeling.V1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8650 Release Google.Cloud.Datastream.V1 version 2.0.0
  apis/Google.Cloud.Datastream.V1/Google.Cloud.Datastream.V1/Google.Cloud.Datastream.V1.csproj
  apis/Google.Cloud.Datastream.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8656 docs(Spanner): Updated Connection String documentation.
  apis/Google.Cloud.Spanner.Data/docs/connection_string.md
Labels: api: spanner

#8657 Release Google.Cloud.DocumentAI.V1 version 2.0.0
  apis/Google.Cloud.DocumentAI.V1/Google.Cloud.DocumentAI.V1/Google.Cloud.DocumentAI.V1.csproj
  apis/Google.Cloud.DocumentAI.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8664 Release Google.Cloud.Functions.V1 version 2.0.0
  apis/Google.Cloud.Functions.V1/Google.Cloud.Functions.V1/Google.Cloud.Functions.V1.csproj
  apis/Google.Cloud.Functions.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8668 Release Google.Cloud.GkeHub.V1 version 2.0.0
  apis/Google.Cloud.GkeHub.V1/Google.Cloud.GkeHub.V1/Google.Cloud.GkeHub.V1.csproj
  apis/Google.Cloud.GkeHub.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8674 Release Google.Cloud.LifeSciences.V2Beta version 2.0.0-beta01
  apis/Google.Cloud.LifeSciences.V2Beta/Google.Cloud.LifeSciences.V2Beta/Google.Cloud.LifeSciences.V2Beta.csproj
  apis/Google.Cloud.LifeSciences.V2Beta/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8672 Release Google.Cloud.Iot.V1 version 2.0.0
  apis/Google.Cloud.Iot.V1/Google.Cloud.Iot.V1/Google.Cloud.Iot.V1.csproj
  apis/Google.Cloud.Iot.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8675 Release Google.Cloud.Logging.V2 version 4.0.0
  apis/Google.Cloud.Logging.V2/Google.Cloud.Logging.V2/Google.Cloud.Logging.V2.csproj
  apis/Google.Cloud.Logging.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8665 Release Google.Cloud.Gaming.V1 version 2.0.0
  apis/Google.Cloud.Gaming.V1/Google.Cloud.Gaming.V1/Google.Cloud.Gaming.V1.csproj
  apis/Google.Cloud.Gaming.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8676 Release Google.Cloud.ManagedIdentities.V1 version 3.0.0
  apis/Google.Cloud.ManagedIdentities.V1/Google.Cloud.ManagedIdentities.V1/Google.Cloud.ManagedIdentities.V1.csproj
  apis/Google.Cloud.ManagedIdentities.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8671 Release Google.Cloud.Ids.V1 version 2.0.0
  apis/Google.Cloud.Ids.V1/Google.Cloud.Ids.V1/Google.Cloud.Ids.V1.csproj
  apis/Google.Cloud.Ids.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8673 Release Google.Cloud.Kms.V1 version 3.0.0
  apis/Google.Cloud.Kms.V1/Google.Cloud.Kms.V1/Google.Cloud.Kms.V1.csproj
  apis/Google.Cloud.Kms.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8663 Release Google.Cloud.Firestore.Admin.V1 version 3.0.0
  apis/Google.Cloud.Firestore.Admin.V1/Google.Cloud.Firestore.Admin.V1/Google.Cloud.Firestore.Admin.V1.csproj
  apis/Google.Cloud.Firestore.Admin.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8669 Release Google.Cloud.Iam.Admin.V1 version 2.0.0
  apis/Google.Cloud.Iam.Admin.V1/Google.Cloud.Iam.Admin.V1/Google.Cloud.Iam.Admin.V1.csproj
  apis/Google.Cloud.Iam.Admin.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8659 Release Google.Cloud.Domains.V1 version 2.0.0
  apis/Google.Cloud.Domains.V1/Google.Cloud.Domains.V1/Google.Cloud.Domains.V1.csproj
  apis/Google.Cloud.Domains.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8667 Release Google.Cloud.GkeHub.V1Beta1 version 2.0.0-beta01
  apis/Google.Cloud.GkeHub.V1Beta1/Google.Cloud.GkeHub.V1Beta1/Google.Cloud.GkeHub.V1Beta1.csproj
  apis/Google.Cloud.GkeHub.V1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8679 Release Google.Cloud.Metastore.V1 version 2.0.0
  apis/Google.Cloud.Metastore.V1/Google.Cloud.Metastore.V1/Google.Cloud.Metastore.V1.csproj
  apis/Google.Cloud.Metastore.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8680 Release Google.Cloud.Metastore.V1Alpha version 2.0.0-alpha01
  apis/Google.Cloud.Metastore.V1Alpha/Google.Cloud.Metastore.V1Alpha/Google.Cloud.Metastore.V1Alpha.csproj
  apis/Google.Cloud.Metastore.V1Alpha/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8670 Release Google.Cloud.Iap.V1 version 2.0.0
  apis/Google.Cloud.Iap.V1/Google.Cloud.Iap.V1/Google.Cloud.Iap.V1.csproj
  apis/Google.Cloud.Iap.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8722 Release Google.Cloud.VideoIntelligence.V1 version 3.0.0
  apis/Google.Cloud.VideoIntelligence.V1/Google.Cloud.VideoIntelligence.V1/Google.Cloud.VideoIntelligence.V1.csproj
  apis/Google.Cloud.VideoIntelligence.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8721 Release Google.Cloud.VMMigration.V1 version 2.0.0
  apis/Google.Cloud.VMMigration.V1/Google.Cloud.VMMigration.V1/Google.Cloud.VMMigration.V1.csproj
  apis/Google.Cloud.VMMigration.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8720 Release Google.Cloud.Translate.V3 version 3.0.0
  apis/Google.Cloud.Translate.V3/Google.Cloud.Translate.V3/Google.Cloud.Translate.V3.csproj
  apis/Google.Cloud.Translate.V3/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8718 Release Google.Cloud.Tasks.V2Beta3 version 3.0.0-beta01
  apis/Google.Cloud.Tasks.V2Beta3/Google.Cloud.Tasks.V2Beta3/Google.Cloud.Tasks.V2Beta3.csproj
  apis/Google.Cloud.Tasks.V2Beta3/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8724 Release Google.Cloud.VpcAccess.V1 version 2.0.0
  apis/Google.Cloud.VpcAccess.V1/Google.Cloud.VpcAccess.V1/Google.Cloud.VpcAccess.V1.csproj
  apis/Google.Cloud.VpcAccess.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8716 Release Google.Cloud.Talent.V4Beta1 version 3.0.0-beta01
  apis/Google.Cloud.Talent.V4Beta1/Google.Cloud.Talent.V4Beta1/Google.Cloud.Talent.V4Beta1.csproj
  apis/Google.Cloud.Talent.V4Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8715 Release Google.Cloud.Talent.V4 version 2.0.0
  apis/Google.Cloud.Talent.V4/Google.Cloud.Talent.V4/Google.Cloud.Talent.V4.csproj
  apis/Google.Cloud.Talent.V4/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8713 Release Google.Cloud.Storage.V1 version 4.0.0
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.csproj
  apis/Google.Cloud.Storage.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8714 Release Google.Cloud.StorageTransfer.V1 version 2.0.0
  apis/Google.Cloud.StorageTransfer.V1/Google.Cloud.StorageTransfer.V1/Google.Cloud.StorageTransfer.V1.csproj
  apis/Google.Cloud.StorageTransfer.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8719 Release Google.Cloud.Tpu.V1 version 2.0.0
  apis/Google.Cloud.Tpu.V1/Google.Cloud.Tpu.V1/Google.Cloud.Tpu.V1.csproj
  apis/Google.Cloud.Tpu.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8717 Release Google.Cloud.Tasks.V2 version 3.0.0
  apis/Google.Cloud.Tasks.V2/Google.Cloud.Tasks.V2/Google.Cloud.Tasks.V2.csproj
  apis/Google.Cloud.Tasks.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8712 Release Google.Cloud.Speech.V1P1Beta1 version 3.0.0-beta01
  apis/Google.Cloud.Speech.V1P1Beta1/Google.Cloud.Speech.V1P1Beta1/Google.Cloud.Speech.V1P1Beta1.csproj
  apis/Google.Cloud.Speech.V1P1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8711 Release Google.Cloud.Speech.V1 version 3.0.0
  apis/Google.Cloud.Speech.V1/Google.Cloud.Speech.V1/Google.Cloud.Speech.V1.csproj
  apis/Google.Cloud.Speech.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8709 Release Google.Cloud.ServiceUsage.V1 version 2.0.0
  apis/Google.Cloud.ServiceUsage.V1/Google.Cloud.ServiceUsage.V1/Google.Cloud.ServiceUsage.V1.csproj
  apis/Google.Cloud.ServiceUsage.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8710 Release Google.Cloud.Shell.V1 version 2.0.0
  apis/Google.Cloud.Shell.V1/Google.Cloud.Shell.V1/Google.Cloud.Shell.V1.csproj
  apis/Google.Cloud.Shell.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8708 Release Google.Cloud.ServiceManagement.V1 version 2.0.0
  apis/Google.Cloud.ServiceManagement.V1/Google.Cloud.ServiceManagement.V1/Google.Cloud.ServiceManagement.V1.csproj
  apis/Google.Cloud.ServiceManagement.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8706 Release Google.Cloud.ServiceDirectory.V1 version 2.0.0
  apis/Google.Cloud.ServiceDirectory.V1/Google.Cloud.ServiceDirectory.V1/Google.Cloud.ServiceDirectory.V1.csproj
  apis/Google.Cloud.ServiceDirectory.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8703 Release Google.Cloud.SecurityCenter.V1 version 3.0.0
  apis/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1.csproj
  apis/Google.Cloud.SecurityCenter.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8704 Release Google.Cloud.SecurityCenter.V1P1Beta1 version 3.0.0-beta01
  apis/Google.Cloud.SecurityCenter.V1P1Beta1/Google.Cloud.SecurityCenter.V1P1Beta1/Google.Cloud.SecurityCenter.V1P1Beta1.csproj
  apis/Google.Cloud.SecurityCenter.V1P1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8698 Release Google.Cloud.SecretManager.V1 version 2.0.0
  apis/Google.Cloud.SecretManager.V1/Google.Cloud.SecretManager.V1/Google.Cloud.SecretManager.V1.csproj
  apis/Google.Cloud.SecretManager.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8699 Release Google.Cloud.SecretManager.V1Beta1 version 3.0.0-beta01
  apis/Google.Cloud.SecretManager.V1Beta1/Google.Cloud.SecretManager.V1Beta1/Google.Cloud.SecretManager.V1Beta1.csproj
  apis/Google.Cloud.SecretManager.V1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8701 Release Google.Cloud.Security.PrivateCA.V1Beta1 version 2.0.0-beta01
  apis/Google.Cloud.Security.PrivateCA.V1Beta1/Google.Cloud.Security.PrivateCA.V1Beta1/Google.Cloud.Security.PrivateCA.V1Beta1.csproj
  apis/Google.Cloud.Security.PrivateCA.V1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8702 Release Google.Cloud.SecurityCenter.Settings.V1Beta1 version 2.0.0-beta01
  apis/Google.Cloud.SecurityCenter.Settings.V1Beta1/Google.Cloud.SecurityCenter.Settings.V1Beta1/Google.Cloud.SecurityCenter.Settings.V1Beta1.csproj
  apis/Google.Cloud.SecurityCenter.Settings.V1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8697 Release Google.Cloud.Retail.V2 version 2.0.0
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2.csproj
  apis/Google.Cloud.Retail.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8693 Release Google.Cloud.RecommendationEngine.V1Beta1 version 2.0.0-beta01
  apis/Google.Cloud.RecommendationEngine.V1Beta1/Google.Cloud.RecommendationEngine.V1Beta1/Google.Cloud.RecommendationEngine.V1Beta1.csproj
  apis/Google.Cloud.RecommendationEngine.V1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8694 Release Google.Cloud.Redis.V1 version 3.0.0
  apis/Google.Cloud.Redis.V1/Google.Cloud.Redis.V1/Google.Cloud.Redis.V1.csproj
  apis/Google.Cloud.Redis.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8696 Release Google.Cloud.ResourceManager.V3 version 2.0.0
  apis/Google.Cloud.ResourceManager.V3/Google.Cloud.ResourceManager.V3/Google.Cloud.ResourceManager.V3.csproj
  apis/Google.Cloud.ResourceManager.V3/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8695 Release Google.Cloud.Redis.V1Beta1 version 3.0.0-beta01
  apis/Google.Cloud.Redis.V1Beta1/Google.Cloud.Redis.V1Beta1/Google.Cloud.Redis.V1Beta1.csproj
  apis/Google.Cloud.Redis.V1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8690 Release Google.Cloud.OsConfig.V1Alpha version 2.0.0-alpha01
  apis/Google.Cloud.OsConfig.V1Alpha/Google.Cloud.OsConfig.V1Alpha/Google.Cloud.OsConfig.V1Alpha.csproj
  apis/Google.Cloud.OsConfig.V1Alpha/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8688 Release Google.Cloud.Orchestration.Airflow.Service.V1 version 2.0.0
  apis/Google.Cloud.Orchestration.Airflow.Service.V1/Google.Cloud.Orchestration.Airflow.Service.V1/Google.Cloud.Orchestration.Airflow.Service.V1.csproj
  apis/Google.Cloud.Orchestration.Airflow.Service.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8689 Release Google.Cloud.OsConfig.V1 version 2.0.0
  apis/Google.Cloud.OsConfig.V1/Google.Cloud.OsConfig.V1/Google.Cloud.OsConfig.V1.csproj
  apis/Google.Cloud.OsConfig.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8691 Release Google.Cloud.PolicyTroubleshooter.V1 version 2.0.0
  apis/Google.Cloud.PolicyTroubleshooter.V1/Google.Cloud.PolicyTroubleshooter.V1/Google.Cloud.PolicyTroubleshooter.V1.csproj
  apis/Google.Cloud.PolicyTroubleshooter.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8692 Release Google.Cloud.PrivateCatalog.V1Beta1 version 2.0.0-beta01
  apis/Google.Cloud.PrivateCatalog.V1Beta1/Google.Cloud.PrivateCatalog.V1Beta1/Google.Cloud.PrivateCatalog.V1Beta1.csproj
  apis/Google.Cloud.PrivateCatalog.V1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8686 Release Google.Cloud.NetworkSecurity.V1Beta1 version 2.0.0-beta01
  apis/Google.Cloud.NetworkSecurity.V1Beta1/Google.Cloud.NetworkSecurity.V1Beta1/Google.Cloud.NetworkSecurity.V1Beta1.csproj
  apis/Google.Cloud.NetworkSecurity.V1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8687 Release Google.Cloud.Notebooks.V1Beta1 version 2.0.0-beta01
  apis/Google.Cloud.Notebooks.V1Beta1/Google.Cloud.Notebooks.V1Beta1/Google.Cloud.Notebooks.V1Beta1.csproj
  apis/Google.Cloud.Notebooks.V1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8683 Release Google.Cloud.NetworkConnectivity.V1 version 2.0.0
  apis/Google.Cloud.NetworkConnectivity.V1/Google.Cloud.NetworkConnectivity.V1/Google.Cloud.NetworkConnectivity.V1.csproj
  apis/Google.Cloud.NetworkConnectivity.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8682 Release Google.Cloud.Monitoring.V3 version 3.0.0
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3.csproj
  apis/Google.Cloud.Monitoring.V3/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8684 Release Google.Cloud.NetworkConnectivity.V1Alpha1 version 2.0.0-alpha01
  apis/Google.Cloud.NetworkConnectivity.V1Alpha1/Google.Cloud.NetworkConnectivity.V1Alpha1/Google.Cloud.NetworkConnectivity.V1Alpha1.csproj
  apis/Google.Cloud.NetworkConnectivity.V1Alpha1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8685 Release Google.Cloud.NetworkManagement.V1 version 2.0.0
  apis/Google.Cloud.NetworkManagement.V1/Google.Cloud.NetworkManagement.V1/Google.Cloud.NetworkManagement.V1.csproj
  apis/Google.Cloud.NetworkManagement.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8681 Release Google.Cloud.Metastore.V1Beta version 2.0.0-beta01
  apis/Google.Cloud.Metastore.V1Beta/Google.Cloud.Metastore.V1Beta/Google.Cloud.Metastore.V1Beta.csproj
  apis/Google.Cloud.Metastore.V1Beta/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8730 Release Google.Cloud.Bigtable.V2 version 3.0.0
  apis/Google.Cloud.Bigtable.V2/docs/history.md
Labels: autorelease: pending, automerge: exact

#8736 Release Google.Cloud.Eventarc.Publishing.V1 version 2.0.0-beta01
  apis/Google.Cloud.Eventarc.Publishing.V1/Google.Cloud.Eventarc.Publishing.V1/Google.Cloud.Eventarc.Publishing.V1.csproj
  apis/Google.Cloud.Eventarc.Publishing.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8738 Release Google.Cloud.GkeMultiCloud.V1 version 2.0.0-beta01
  apis/Google.Cloud.GkeMultiCloud.V1/.repo-metadata.json
  apis/Google.Cloud.GkeMultiCloud.V1/Google.Cloud.GkeMultiCloud.V1/Google.Cloud.GkeMultiCloud.V1.csproj
  apis/Google.Cloud.GkeMultiCloud.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8734 Release Google.Cloud.Logging.Console version 1.0.0-beta01
  apis/Google.Cloud.Logging.Console/Google.Cloud.Logging.Console/Google.Cloud.Logging.Console.csproj
  apis/Google.Cloud.Logging.Console/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8737 Release Google.Cloud.GkeBackup.V1 version 2.0.0-beta01
  apis/Google.Cloud.GkeBackup.V1/.repo-metadata.json
  apis/Google.Cloud.GkeBackup.V1/Google.Cloud.GkeBackup.V1/Google.Cloud.GkeBackup.V1.csproj
  apis/Google.Cloud.GkeBackup.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8741 Release Google.Cloud.Run.V2 version 2.0.0-beta01
  apis/Google.Cloud.Run.V2/Google.Cloud.Run.V2/Google.Cloud.Run.V2.csproj
  apis/Google.Cloud.Run.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8743 Release Google.Cloud.Logging.Log4Net version 4.0.0
  apis/Google.Cloud.Logging.Log4Net/Google.Cloud.Logging.Log4Net/Google.Cloud.Logging.Log4Net.csproj
  apis/Google.Cloud.Logging.Log4Net/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8744 Release Google.Cloud.Logging.NLog version 4.0.0
  apis/Google.Cloud.Logging.NLog/Google.Cloud.Logging.NLog/Google.Cloud.Logging.NLog.csproj
  apis/Google.Cloud.Logging.NLog/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8739 Release Google.Cloud.Notebooks.V1 version 2.0.0-beta01
  apis/Google.Cloud.Notebooks.V1/Google.Cloud.Notebooks.V1/Google.Cloud.Notebooks.V1.csproj
  apis/Google.Cloud.Notebooks.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8747 Release diagnostics libraries version 5.0.0
  apis/Google.Cloud.Diagnostics.AspNetCore3/Google.Cloud.Diagnostics.AspNetCore3/Google.Cloud.Diagnostics.AspNetCore3.csproj
  apis/Google.Cloud.Diagnostics.AspNetCore3/docs/history.md
  apis/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common.csproj
  apis/Google.Cloud.Diagnostics.Common/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8740 Release Google.Cloud.Optimization.V1 version 2.0.0-beta01
  apis/Google.Cloud.Optimization.V1/Google.Cloud.Optimization.V1/Google.Cloud.Optimization.V1.csproj
  apis/Google.Cloud.Optimization.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8745 Release BigQuery DataExchange libraries version 2.0.0-beta01
  apis/Google.Cloud.BigQuery.DataExchange.Common/Google.Cloud.BigQuery.DataExchange.Common/Google.Cloud.BigQuery.DataExchange.Common.csproj
  apis/Google.Cloud.BigQuery.DataExchange.V1Beta1/Google.Cloud.BigQuery.DataExchange.V1Beta1/Google.Cloud.BigQuery.DataExchange.V1Beta1.csproj
  apis/Google.Cloud.BigQuery.DataExchange.V1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8746 Release Spanner libraries version 4.0.0-beta01
  apis/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1.csproj
  apis/Google.Cloud.Spanner.Admin.Instance.V1/Google.Cloud.Spanner.Admin.Instance.V1/Google.Cloud.Spanner.Admin.Instance.V1.csproj
  apis/Google.Cloud.Spanner.Common.V1/Google.Cloud.Spanner.Common.V1/Google.Cloud.Spanner.Common.V1.csproj
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.csproj
  apis/Google.Cloud.Spanner.Data/docs/history.md
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1.csproj
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8755 Release Google.Cloud.PubSub.V1 version 3.0.0-beta01
  apis/Google.Cloud.DevTools.ContainerAnalysis.V1/Google.Cloud.DevTools.ContainerAnalysis.V1/Google.Cloud.DevTools.ContainerAnalysis.V1.csproj
  apis/Google.Cloud.DevTools.ContainerAnalysis.V1/docs/history.md
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1.csproj
  apis/Google.Cloud.PubSub.V1/docs/history.md
  apis/Grafeas.V1/Grafeas.V1/Grafeas.V1.csproj
  apis/Grafeas.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8749 Release Container Analysis libraries version 3.0.0
  apis/Google.Cloud.Firestore.V1/Google.Cloud.Firestore.V1/Google.Cloud.Firestore.V1.csproj
  apis/Google.Cloud.Firestore.V1/docs/history.md
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore/Google.Cloud.Firestore.csproj
  apis/Google.Cloud.Firestore/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8758 Release Google.Cloud.BinaryAuthorization.V1 version 2.0.0
  apis/Google.Cloud.BinaryAuthorization.V1/docs/history.md
Labels: autorelease: pending, automerge: exact

#8771 Release Google.Cloud.ApigeeRegistry.V1 version 1.0.0-beta01
  README.md
  apis/Google.Cloud.ApigeeRegistry.V1/.repo-metadata.json
  apis/Google.Cloud.ApigeeRegistry.V1/Google.Cloud.ApigeeRegistry.V1/Google.Cloud.ApigeeRegistry.V1.csproj
  apis/Google.Cloud.ApigeeRegistry.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8772 Release Spanner libraries version 4.0.0-beta02
  apis/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1.csproj
  apis/Google.Cloud.Spanner.Admin.Instance.V1/Google.Cloud.Spanner.Admin.Instance.V1/Google.Cloud.Spanner.Admin.Instance.V1.csproj
  apis/Google.Cloud.Spanner.Common.V1/Google.Cloud.Spanner.Common.V1/Google.Cloud.Spanner.Common.V1.csproj
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.csproj
  apis/Google.Cloud.Spanner.Data/docs/history.md
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1.csproj
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8801 Release Spanner libraries version 4.0.0
  apis/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1.csproj
  apis/Google.Cloud.Spanner.Admin.Instance.V1/Google.Cloud.Spanner.Admin.Instance.V1/Google.Cloud.Spanner.Admin.Instance.V1.csproj
  apis/Google.Cloud.Spanner.Common.V1/Google.Cloud.Spanner.Common.V1/Google.Cloud.Spanner.Common.V1.csproj
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.csproj
  apis/Google.Cloud.Spanner.Data/docs/history.md
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1.csproj
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8802 Release Google.Cloud.Datastore.V1 version 4.1.0
  apis/Google.Cloud.Datastore.V1/Google.Cloud.Datastore.V1/Google.Cloud.Datastore.V1.csproj
  apis/Google.Cloud.Datastore.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8826 Release Google.Cloud.PubSub.V1 version 3.0.0
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1.csproj
  apis/Google.Cloud.PubSub.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact
