Repository googleapis/google-cloud-dotnet, pull requests merged in 2022-07, with the labels that each got.

#8851 Release Google.Cloud.AssuredWorkloads.V1 version 2.1.0
  apis/Google.Cloud.AssuredWorkloads.V1/Google.Cloud.AssuredWorkloads.V1/Google.Cloud.AssuredWorkloads.V1.csproj
  apis/Google.Cloud.AssuredWorkloads.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8852 Release Google.Cloud.AssuredWorkloads.V1Beta1 version 2.0.0-beta02
  apis/Google.Cloud.AssuredWorkloads.V1Beta1/Google.Cloud.AssuredWorkloads.V1Beta1/Google.Cloud.AssuredWorkloads.V1Beta1.csproj
  apis/Google.Cloud.AssuredWorkloads.V1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8860 Release Google.Cloud.Dialogflow.Cx.V3 version 2.1.0
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3.csproj
  apis/Google.Cloud.Dialogflow.Cx.V3/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8850 Release Google.Cloud.AIPlatform.V1 version 2.1.0
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1.csproj
  apis/Google.Cloud.AIPlatform.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8857 Release Google.Cloud.CertificateManager.V1 version 2.0.0-beta02
  apis/Google.Cloud.CertificateManager.V1/Google.Cloud.CertificateManager.V1/Google.Cloud.CertificateManager.V1.csproj
  apis/Google.Cloud.CertificateManager.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8866 Release Google.Cloud.SecurityCenter.V1 version 3.1.0
  apis/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1.csproj
  apis/Google.Cloud.SecurityCenter.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8867 Release Google.Cloud.Video.Transcoder.V1 version 2.1.0
  apis/Google.Cloud.Video.Transcoder.V1/Google.Cloud.Video.Transcoder.V1/Google.Cloud.Video.Transcoder.V1.csproj
  apis/Google.Cloud.Video.Transcoder.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8856 Release Google.Cloud.BinaryAuthorization.V1Beta1 version 2.0.0-beta02
  apis/Google.Cloud.BinaryAuthorization.V1Beta1/Google.Cloud.BinaryAuthorization.V1Beta1/Google.Cloud.BinaryAuthorization.V1Beta1.csproj
  apis/Google.Cloud.BinaryAuthorization.V1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8865 Release Google.Cloud.Recommender.V1 version 3.1.0
  apis/Google.Cloud.Recommender.V1/Google.Cloud.Recommender.V1/Google.Cloud.Recommender.V1.csproj
  apis/Google.Cloud.Recommender.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8861 Release Google.Cloud.Dialogflow.V2 version 4.1.0
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2.csproj
  apis/Google.Cloud.Dialogflow.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8864 Release Google.Cloud.RecaptchaEnterprise.V1 version 2.1.0
  apis/Google.Cloud.RecaptchaEnterprise.V1/Google.Cloud.RecaptchaEnterprise.V1/Google.Cloud.RecaptchaEnterprise.V1.csproj
  apis/Google.Cloud.RecaptchaEnterprise.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8853 Release Google.Cloud.BigQuery.Storage.V1 version 3.1.0
  apis/Google.Cloud.BigQuery.Storage.V1/Google.Cloud.BigQuery.Storage.V1/Google.Cloud.BigQuery.Storage.V1.csproj
  apis/Google.Cloud.BigQuery.Storage.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8863 Release Google.Cloud.NetworkManagement.V1 version 2.1.0
  apis/Google.Cloud.NetworkManagement.V1/Google.Cloud.NetworkManagement.V1/Google.Cloud.NetworkManagement.V1.csproj
  apis/Google.Cloud.NetworkManagement.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8858 Release Google.Cloud.Container.V1 version 3.1.0
  apis/Google.Cloud.Container.V1/Google.Cloud.Container.V1/Google.Cloud.Container.V1.csproj
  apis/Google.Cloud.Container.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8854 Release Google.Cloud.Bigtable.Admin.V2 version 3.1.0
  apis/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2.csproj
  apis/Google.Cloud.Bigtable.Admin.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8885 Release Google.Cloud.Batch.V1Alpha version 1.0.0-alpha01
  README.md
  apis/Google.Cloud.Batch.V1Alpha/.repo-metadata.json
  apis/Google.Cloud.Batch.V1Alpha/Google.Cloud.Batch.V1Alpha/Google.Cloud.Batch.V1Alpha.csproj
  apis/Google.Cloud.Batch.V1Alpha/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8887 Release Google.Cloud.Batch.V1 version 1.0.0-beta01
  README.md
  apis/Google.Cloud.Batch.V1/.repo-metadata.json
  apis/Google.Cloud.Batch.V1/Google.Cloud.Batch.V1/Google.Cloud.Batch.V1.csproj
  apis/Google.Cloud.Batch.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8897 Release Google.Cloud.Logging.Console version 1.0.0
  apis/Google.Cloud.Logging.Console/.repo-metadata.json
  apis/Google.Cloud.Logging.Console/Google.Cloud.Logging.Console/Google.Cloud.Logging.Console.csproj
  apis/Google.Cloud.Logging.Console/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8896 Release Google.Cloud.BeyondCorp.AppConnections.V1 version 1.0.0-beta01
  .github/renovate.json
  README.md
  apis/Google.Cloud.BeyondCorp.AppConnections.V1/.OwlBot.yaml
  apis/Google.Cloud.BeyondCorp.AppConnections.V1/.repo-metadata.json
  apis/Google.Cloud.BeyondCorp.AppConnections.V1/Google.Cloud.BeyondCorp.AppConnections.V1.GeneratedSnippets/AppConnectionsServiceClient.CreateAppConnectionAsyncSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.AppConnections.V1/Google.Cloud.BeyondCorp.AppConnections.V1.GeneratedSnippets/AppConnectionsServiceClient.CreateAppConnectionRequestObjectAsyncSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.AppConnections.V1/Google.Cloud.BeyondCorp.AppConnections.V1.GeneratedSnippets/AppConnectionsServiceClient.CreateAppConnectionRequestObjectSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.AppConnections.V1/Google.Cloud.BeyondCorp.AppConnections.V1.GeneratedSnippets/AppConnectionsServiceClient.CreateAppConnectionResourceNamesAsyncSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.AppConnections.V1/Google.Cloud.BeyondCorp.AppConnections.V1.GeneratedSnippets/AppConnectionsServiceClient.CreateAppConnectionResourceNamesSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.AppConnections.V1/Google.Cloud.BeyondCorp.AppConnections.V1.GeneratedSnippets/AppConnectionsServiceClient.CreateAppConnectionSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.AppConnections.V1/Google.Cloud.BeyondCorp.AppConnections.V1.GeneratedSnippets/AppConnectionsServiceClient.DeleteAppConnectionAsyncSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.AppConnections.V1/Google.Cloud.BeyondCorp.AppConnections.V1.GeneratedSnippets/AppConnectionsServiceClient.DeleteAppConnectionRequestObjectAsyncSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.AppConnections.V1/Google.Cloud.BeyondCorp.AppConnections.V1.GeneratedSnippets/AppConnectionsServiceClient.DeleteAppConnectionRequestObjectSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.AppConnections.V1/Google.Cloud.BeyondCorp.AppConnections.V1.GeneratedSnippets/AppConnectionsServiceClient.DeleteAppConnectionResourceNamesAsyncSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.AppConnections.V1/Google.Cloud.BeyondCorp.AppConnections.V1.GeneratedSnippets/AppConnectionsServiceClient.DeleteAppConnectionResourceNamesSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.AppConnections.V1/Google.Cloud.BeyondCorp.AppConnections.V1.GeneratedSnippets/AppConnectionsServiceClient.DeleteAppConnectionSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.AppConnections.V1/Google.Cloud.BeyondCorp.AppConnections.V1.GeneratedSnippets/AppConnectionsServiceClient.GetAppConnectionAsyncSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.AppConnections.V1/Google.Cloud.BeyondCorp.AppConnections.V1.GeneratedSnippets/AppConnectionsServiceClient.GetAppConnectionRequestObjectAsyncSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.AppConnections.V1/Google.Cloud.BeyondCorp.AppConnections.V1.GeneratedSnippets/AppConnectionsServiceClient.GetAppConnectionRequestObjectSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.AppConnections.V1/Google.Cloud.BeyondCorp.AppConnections.V1.GeneratedSnippets/AppConnectionsServiceClient.GetAppConnectionResourceNamesAsyncSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.AppConnections.V1/Google.Cloud.BeyondCorp.AppConnections.V1.GeneratedSnippets/AppConnectionsServiceClient.GetAppConnectionResourceNamesSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.AppConnections.V1/Google.Cloud.BeyondCorp.AppConnections.V1.GeneratedSnippets/AppConnectionsServiceClient.GetAppConnectionSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.AppConnections.V1/Google.Cloud.BeyondCorp.AppConnections.V1.GeneratedSnippets/AppConnectionsServiceClient.ListAppConnectionsAsyncSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.AppConnections.V1/Google.Cloud.BeyondCorp.AppConnections.V1.GeneratedSnippets/AppConnectionsServiceClient.ListAppConnectionsRequestObjectAsyncSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.AppConnections.V1/Google.Cloud.BeyondCorp.AppConnections.V1.GeneratedSnippets/AppConnectionsServiceClient.ListAppConnectionsRequestObjectSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.AppConnections.V1/Google.Cloud.BeyondCorp.AppConnections.V1.GeneratedSnippets/AppConnectionsServiceClient.ListAppConnectionsResourceNamesAsyncSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.AppConnections.V1/Google.Cloud.BeyondCorp.AppConnections.V1.GeneratedSnippets/AppConnectionsServiceClient.ListAppConnectionsResourceNamesSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.AppConnections.V1/Google.Cloud.BeyondCorp.AppConnections.V1.GeneratedSnippets/AppConnectionsServiceClient.ListAppConnectionsSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.AppConnections.V1/Google.Cloud.BeyondCorp.AppConnections.V1.GeneratedSnippets/AppConnectionsServiceClient.ResolveAppConnectionsAsyncSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.AppConnections.V1/Google.Cloud.BeyondCorp.AppConnections.V1.GeneratedSnippets/AppConnectionsServiceClient.ResolveAppConnectionsRequestObjectAsyncSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.AppConnections.V1/Google.Cloud.BeyondCorp.AppConnections.V1.GeneratedSnippets/AppConnectionsServiceClient.ResolveAppConnectionsRequestObjectSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.AppConnections.V1/Google.Cloud.BeyondCorp.AppConnections.V1.GeneratedSnippets/AppConnectionsServiceClient.ResolveAppConnectionsResourceNamesAsyncSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.AppConnections.V1/Google.Cloud.BeyondCorp.AppConnections.V1.GeneratedSnippets/AppConnectionsServiceClient.ResolveAppConnectionsResourceNamesSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.AppConnections.V1/Google.Cloud.BeyondCorp.AppConnections.V1.GeneratedSnippets/AppConnectionsServiceClient.ResolveAppConnectionsSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.AppConnections.V1/Google.Cloud.BeyondCorp.AppConnections.V1.GeneratedSnippets/AppConnectionsServiceClient.UpdateAppConnectionAsyncSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.AppConnections.V1/Google.Cloud.BeyondCorp.AppConnections.V1.GeneratedSnippets/AppConnectionsServiceClient.UpdateAppConnectionRequestObjectAsyncSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.AppConnections.V1/Google.Cloud.BeyondCorp.AppConnections.V1.GeneratedSnippets/AppConnectionsServiceClient.UpdateAppConnectionRequestObjectSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.AppConnections.V1/Google.Cloud.BeyondCorp.AppConnections.V1.GeneratedSnippets/AppConnectionsServiceClient.UpdateAppConnectionSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.AppConnections.V1/Google.Cloud.BeyondCorp.AppConnections.V1.GeneratedSnippets/Google.Cloud.BeyondCorp.AppConnections.V1.GeneratedSnippets.csproj
  apis/Google.Cloud.BeyondCorp.AppConnections.V1/Google.Cloud.BeyondCorp.AppConnections.V1.GeneratedSnippets/snippet_metadata_google.cloud.beyondcorp.appconnections.v1.json
  apis/Google.Cloud.BeyondCorp.AppConnections.V1/Google.Cloud.BeyondCorp.AppConnections.V1.Snippets/AppConnectionsServiceClientSnippets.g.cs
  apis/Google.Cloud.BeyondCorp.AppConnections.V1/Google.Cloud.BeyondCorp.AppConnections.V1.Snippets/Google.Cloud.BeyondCorp.AppConnections.V1.Snippets.csproj
  apis/Google.Cloud.BeyondCorp.AppConnections.V1/Google.Cloud.BeyondCorp.AppConnections.V1.Snippets/coverage.xml
  apis/Google.Cloud.BeyondCorp.AppConnections.V1/Google.Cloud.BeyondCorp.AppConnections.V1.Tests/AppConnectionsServiceClientTest.g.cs
  apis/Google.Cloud.BeyondCorp.AppConnections.V1/Google.Cloud.BeyondCorp.AppConnections.V1.Tests/Google.Cloud.BeyondCorp.AppConnections.V1.Tests.csproj
  apis/Google.Cloud.BeyondCorp.AppConnections.V1/Google.Cloud.BeyondCorp.AppConnections.V1.Tests/coverage.xml
  apis/Google.Cloud.BeyondCorp.AppConnections.V1/Google.Cloud.BeyondCorp.AppConnections.V1.sln
  apis/Google.Cloud.BeyondCorp.AppConnections.V1/Google.Cloud.BeyondCorp.AppConnections.V1/AppConnectionsService.g.cs
  apis/Google.Cloud.BeyondCorp.AppConnections.V1/Google.Cloud.BeyondCorp.AppConnections.V1/AppConnectionsServiceClient.g.cs
  apis/Google.Cloud.BeyondCorp.AppConnections.V1/Google.Cloud.BeyondCorp.AppConnections.V1/AppConnectionsServiceGrpc.g.cs
  apis/Google.Cloud.BeyondCorp.AppConnections.V1/Google.Cloud.BeyondCorp.AppConnections.V1/AppConnectionsServiceResourceNames.g.cs
  apis/Google.Cloud.BeyondCorp.AppConnections.V1/Google.Cloud.BeyondCorp.AppConnections.V1/Google.Cloud.BeyondCorp.AppConnections.V1.csproj
  apis/Google.Cloud.BeyondCorp.AppConnections.V1/Google.Cloud.BeyondCorp.AppConnections.V1/PackageApiMetadata.g.cs
  apis/Google.Cloud.BeyondCorp.AppConnections.V1/Google.Cloud.BeyondCorp.AppConnections.V1/ServiceCollectionExtensions.g.cs
  apis/Google.Cloud.BeyondCorp.AppConnections.V1/docs/history.md
  apis/Google.Cloud.BeyondCorp.AppConnections.V1/docs/index.md
  apis/Google.Cloud.BeyondCorp.AppConnections.V1/gapic_metadata.json
  apis/Google.Cloud.BeyondCorp.AppConnections.V1/smoketests.json
  apis/apis.json
Labels: autorelease: pending, snippet-bot:no-prefix-req, automerge: exact

#8899 Release Google.Cloud.BeyondCorp.AppGateways.V1 version 1.0.0-beta01
  .github/renovate.json
  README.md
  apis/Google.Cloud.BeyondCorp.AppGateways.V1/.OwlBot.yaml
  apis/Google.Cloud.BeyondCorp.AppGateways.V1/.repo-metadata.json
  apis/Google.Cloud.BeyondCorp.AppGateways.V1/Google.Cloud.BeyondCorp.AppGateways.V1.GeneratedSnippets/AppGatewaysServiceClient.CreateAppGatewayAsyncSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.AppGateways.V1/Google.Cloud.BeyondCorp.AppGateways.V1.GeneratedSnippets/AppGatewaysServiceClient.CreateAppGatewayRequestObjectAsyncSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.AppGateways.V1/Google.Cloud.BeyondCorp.AppGateways.V1.GeneratedSnippets/AppGatewaysServiceClient.CreateAppGatewayRequestObjectSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.AppGateways.V1/Google.Cloud.BeyondCorp.AppGateways.V1.GeneratedSnippets/AppGatewaysServiceClient.CreateAppGatewayResourceNamesAsyncSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.AppGateways.V1/Google.Cloud.BeyondCorp.AppGateways.V1.GeneratedSnippets/AppGatewaysServiceClient.CreateAppGatewayResourceNamesSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.AppGateways.V1/Google.Cloud.BeyondCorp.AppGateways.V1.GeneratedSnippets/AppGatewaysServiceClient.CreateAppGatewaySnippet.g.cs
  apis/Google.Cloud.BeyondCorp.AppGateways.V1/Google.Cloud.BeyondCorp.AppGateways.V1.GeneratedSnippets/AppGatewaysServiceClient.DeleteAppGatewayAsyncSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.AppGateways.V1/Google.Cloud.BeyondCorp.AppGateways.V1.GeneratedSnippets/AppGatewaysServiceClient.DeleteAppGatewayRequestObjectAsyncSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.AppGateways.V1/Google.Cloud.BeyondCorp.AppGateways.V1.GeneratedSnippets/AppGatewaysServiceClient.DeleteAppGatewayRequestObjectSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.AppGateways.V1/Google.Cloud.BeyondCorp.AppGateways.V1.GeneratedSnippets/AppGatewaysServiceClient.DeleteAppGatewayResourceNamesAsyncSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.AppGateways.V1/Google.Cloud.BeyondCorp.AppGateways.V1.GeneratedSnippets/AppGatewaysServiceClient.DeleteAppGatewayResourceNamesSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.AppGateways.V1/Google.Cloud.BeyondCorp.AppGateways.V1.GeneratedSnippets/AppGatewaysServiceClient.DeleteAppGatewaySnippet.g.cs
  apis/Google.Cloud.BeyondCorp.AppGateways.V1/Google.Cloud.BeyondCorp.AppGateways.V1.GeneratedSnippets/AppGatewaysServiceClient.GetAppGatewayAsyncSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.AppGateways.V1/Google.Cloud.BeyondCorp.AppGateways.V1.GeneratedSnippets/AppGatewaysServiceClient.GetAppGatewayRequestObjectAsyncSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.AppGateways.V1/Google.Cloud.BeyondCorp.AppGateways.V1.GeneratedSnippets/AppGatewaysServiceClient.GetAppGatewayRequestObjectSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.AppGateways.V1/Google.Cloud.BeyondCorp.AppGateways.V1.GeneratedSnippets/AppGatewaysServiceClient.GetAppGatewayResourceNamesAsyncSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.AppGateways.V1/Google.Cloud.BeyondCorp.AppGateways.V1.GeneratedSnippets/AppGatewaysServiceClient.GetAppGatewayResourceNamesSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.AppGateways.V1/Google.Cloud.BeyondCorp.AppGateways.V1.GeneratedSnippets/AppGatewaysServiceClient.GetAppGatewaySnippet.g.cs
  apis/Google.Cloud.BeyondCorp.AppGateways.V1/Google.Cloud.BeyondCorp.AppGateways.V1.GeneratedSnippets/AppGatewaysServiceClient.ListAppGatewaysAsyncSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.AppGateways.V1/Google.Cloud.BeyondCorp.AppGateways.V1.GeneratedSnippets/AppGatewaysServiceClient.ListAppGatewaysRequestObjectAsyncSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.AppGateways.V1/Google.Cloud.BeyondCorp.AppGateways.V1.GeneratedSnippets/AppGatewaysServiceClient.ListAppGatewaysRequestObjectSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.AppGateways.V1/Google.Cloud.BeyondCorp.AppGateways.V1.GeneratedSnippets/AppGatewaysServiceClient.ListAppGatewaysResourceNamesAsyncSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.AppGateways.V1/Google.Cloud.BeyondCorp.AppGateways.V1.GeneratedSnippets/AppGatewaysServiceClient.ListAppGatewaysResourceNamesSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.AppGateways.V1/Google.Cloud.BeyondCorp.AppGateways.V1.GeneratedSnippets/AppGatewaysServiceClient.ListAppGatewaysSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.AppGateways.V1/Google.Cloud.BeyondCorp.AppGateways.V1.GeneratedSnippets/Google.Cloud.BeyondCorp.AppGateways.V1.GeneratedSnippets.csproj
  apis/Google.Cloud.BeyondCorp.AppGateways.V1/Google.Cloud.BeyondCorp.AppGateways.V1.GeneratedSnippets/snippet_metadata_google.cloud.beyondcorp.appgateways.v1.json
  apis/Google.Cloud.BeyondCorp.AppGateways.V1/Google.Cloud.BeyondCorp.AppGateways.V1.Snippets/AppGatewaysServiceClientSnippets.g.cs
  apis/Google.Cloud.BeyondCorp.AppGateways.V1/Google.Cloud.BeyondCorp.AppGateways.V1.Snippets/Google.Cloud.BeyondCorp.AppGateways.V1.Snippets.csproj
  apis/Google.Cloud.BeyondCorp.AppGateways.V1/Google.Cloud.BeyondCorp.AppGateways.V1.Snippets/coverage.xml
  apis/Google.Cloud.BeyondCorp.AppGateways.V1/Google.Cloud.BeyondCorp.AppGateways.V1.Tests/AppGatewaysServiceClientTest.g.cs
  apis/Google.Cloud.BeyondCorp.AppGateways.V1/Google.Cloud.BeyondCorp.AppGateways.V1.Tests/Google.Cloud.BeyondCorp.AppGateways.V1.Tests.csproj
  apis/Google.Cloud.BeyondCorp.AppGateways.V1/Google.Cloud.BeyondCorp.AppGateways.V1.Tests/coverage.xml
  apis/Google.Cloud.BeyondCorp.AppGateways.V1/Google.Cloud.BeyondCorp.AppGateways.V1.sln
  apis/Google.Cloud.BeyondCorp.AppGateways.V1/Google.Cloud.BeyondCorp.AppGateways.V1/AppGatewaysService.g.cs
  apis/Google.Cloud.BeyondCorp.AppGateways.V1/Google.Cloud.BeyondCorp.AppGateways.V1/AppGatewaysServiceClient.g.cs
  apis/Google.Cloud.BeyondCorp.AppGateways.V1/Google.Cloud.BeyondCorp.AppGateways.V1/AppGatewaysServiceGrpc.g.cs
  apis/Google.Cloud.BeyondCorp.AppGateways.V1/Google.Cloud.BeyondCorp.AppGateways.V1/AppGatewaysServiceResourceNames.g.cs
  apis/Google.Cloud.BeyondCorp.AppGateways.V1/Google.Cloud.BeyondCorp.AppGateways.V1/Google.Cloud.BeyondCorp.AppGateways.V1.csproj
  apis/Google.Cloud.BeyondCorp.AppGateways.V1/Google.Cloud.BeyondCorp.AppGateways.V1/PackageApiMetadata.g.cs
  apis/Google.Cloud.BeyondCorp.AppGateways.V1/Google.Cloud.BeyondCorp.AppGateways.V1/ServiceCollectionExtensions.g.cs
  apis/Google.Cloud.BeyondCorp.AppGateways.V1/docs/history.md
  apis/Google.Cloud.BeyondCorp.AppGateways.V1/docs/index.md
  apis/Google.Cloud.BeyondCorp.AppGateways.V1/gapic_metadata.json
  apis/Google.Cloud.BeyondCorp.AppGateways.V1/smoketests.json
  apis/apis.json
Labels: autorelease: pending, snippet-bot:no-prefix-req, automerge: exact

#8901 Release Google.Cloud.BeyondCorp.ClientGateways.V1 version 1.0.0-beta01
  .github/renovate.json
  README.md
  apis/Google.Cloud.BeyondCorp.ClientGateways.V1/.OwlBot.yaml
  apis/Google.Cloud.BeyondCorp.ClientGateways.V1/.repo-metadata.json
  apis/Google.Cloud.BeyondCorp.ClientGateways.V1/Google.Cloud.BeyondCorp.ClientGateways.V1.GeneratedSnippets/ClientGatewaysServiceClient.CreateClientGatewayAsyncSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.ClientGateways.V1/Google.Cloud.BeyondCorp.ClientGateways.V1.GeneratedSnippets/ClientGatewaysServiceClient.CreateClientGatewayRequestObjectAsyncSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.ClientGateways.V1/Google.Cloud.BeyondCorp.ClientGateways.V1.GeneratedSnippets/ClientGatewaysServiceClient.CreateClientGatewayRequestObjectSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.ClientGateways.V1/Google.Cloud.BeyondCorp.ClientGateways.V1.GeneratedSnippets/ClientGatewaysServiceClient.CreateClientGatewayResourceNamesAsyncSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.ClientGateways.V1/Google.Cloud.BeyondCorp.ClientGateways.V1.GeneratedSnippets/ClientGatewaysServiceClient.CreateClientGatewayResourceNamesSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.ClientGateways.V1/Google.Cloud.BeyondCorp.ClientGateways.V1.GeneratedSnippets/ClientGatewaysServiceClient.CreateClientGatewaySnippet.g.cs
  apis/Google.Cloud.BeyondCorp.ClientGateways.V1/Google.Cloud.BeyondCorp.ClientGateways.V1.GeneratedSnippets/ClientGatewaysServiceClient.DeleteClientGatewayAsyncSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.ClientGateways.V1/Google.Cloud.BeyondCorp.ClientGateways.V1.GeneratedSnippets/ClientGatewaysServiceClient.DeleteClientGatewayRequestObjectAsyncSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.ClientGateways.V1/Google.Cloud.BeyondCorp.ClientGateways.V1.GeneratedSnippets/ClientGatewaysServiceClient.DeleteClientGatewayRequestObjectSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.ClientGateways.V1/Google.Cloud.BeyondCorp.ClientGateways.V1.GeneratedSnippets/ClientGatewaysServiceClient.DeleteClientGatewayResourceNamesAsyncSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.ClientGateways.V1/Google.Cloud.BeyondCorp.ClientGateways.V1.GeneratedSnippets/ClientGatewaysServiceClient.DeleteClientGatewayResourceNamesSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.ClientGateways.V1/Google.Cloud.BeyondCorp.ClientGateways.V1.GeneratedSnippets/ClientGatewaysServiceClient.DeleteClientGatewaySnippet.g.cs
  apis/Google.Cloud.BeyondCorp.ClientGateways.V1/Google.Cloud.BeyondCorp.ClientGateways.V1.GeneratedSnippets/ClientGatewaysServiceClient.GetClientGatewayAsyncSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.ClientGateways.V1/Google.Cloud.BeyondCorp.ClientGateways.V1.GeneratedSnippets/ClientGatewaysServiceClient.GetClientGatewayRequestObjectAsyncSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.ClientGateways.V1/Google.Cloud.BeyondCorp.ClientGateways.V1.GeneratedSnippets/ClientGatewaysServiceClient.GetClientGatewayRequestObjectSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.ClientGateways.V1/Google.Cloud.BeyondCorp.ClientGateways.V1.GeneratedSnippets/ClientGatewaysServiceClient.GetClientGatewayResourceNamesAsyncSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.ClientGateways.V1/Google.Cloud.BeyondCorp.ClientGateways.V1.GeneratedSnippets/ClientGatewaysServiceClient.GetClientGatewayResourceNamesSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.ClientGateways.V1/Google.Cloud.BeyondCorp.ClientGateways.V1.GeneratedSnippets/ClientGatewaysServiceClient.GetClientGatewaySnippet.g.cs
  apis/Google.Cloud.BeyondCorp.ClientGateways.V1/Google.Cloud.BeyondCorp.ClientGateways.V1.GeneratedSnippets/ClientGatewaysServiceClient.ListClientGatewaysAsyncSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.ClientGateways.V1/Google.Cloud.BeyondCorp.ClientGateways.V1.GeneratedSnippets/ClientGatewaysServiceClient.ListClientGatewaysRequestObjectAsyncSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.ClientGateways.V1/Google.Cloud.BeyondCorp.ClientGateways.V1.GeneratedSnippets/ClientGatewaysServiceClient.ListClientGatewaysRequestObjectSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.ClientGateways.V1/Google.Cloud.BeyondCorp.ClientGateways.V1.GeneratedSnippets/ClientGatewaysServiceClient.ListClientGatewaysResourceNamesAsyncSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.ClientGateways.V1/Google.Cloud.BeyondCorp.ClientGateways.V1.GeneratedSnippets/ClientGatewaysServiceClient.ListClientGatewaysResourceNamesSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.ClientGateways.V1/Google.Cloud.BeyondCorp.ClientGateways.V1.GeneratedSnippets/ClientGatewaysServiceClient.ListClientGatewaysSnippet.g.cs
  apis/Google.Cloud.BeyondCorp.ClientGateways.V1/Google.Cloud.BeyondCorp.ClientGateways.V1.GeneratedSnippets/Google.Cloud.BeyondCorp.ClientGateways.V1.GeneratedSnippets.csproj
  apis/Google.Cloud.BeyondCorp.ClientGateways.V1/Google.Cloud.BeyondCorp.ClientGateways.V1.GeneratedSnippets/snippet_metadata_google.cloud.beyondcorp.clientgateways.v1.json
  apis/Google.Cloud.BeyondCorp.ClientGateways.V1/Google.Cloud.BeyondCorp.ClientGateways.V1.Snippets/ClientGatewaysServiceClientSnippets.g.cs
  apis/Google.Cloud.BeyondCorp.ClientGateways.V1/Google.Cloud.BeyondCorp.ClientGateways.V1.Snippets/Google.Cloud.BeyondCorp.ClientGateways.V1.Snippets.csproj
  apis/Google.Cloud.BeyondCorp.ClientGateways.V1/Google.Cloud.BeyondCorp.ClientGateways.V1.Snippets/coverage.xml
  apis/Google.Cloud.BeyondCorp.ClientGateways.V1/Google.Cloud.BeyondCorp.ClientGateways.V1.Tests/ClientGatewaysServiceClientTest.g.cs
  apis/Google.Cloud.BeyondCorp.ClientGateways.V1/Google.Cloud.BeyondCorp.ClientGateways.V1.Tests/Google.Cloud.BeyondCorp.ClientGateways.V1.Tests.csproj
  apis/Google.Cloud.BeyondCorp.ClientGateways.V1/Google.Cloud.BeyondCorp.ClientGateways.V1.Tests/coverage.xml
  apis/Google.Cloud.BeyondCorp.ClientGateways.V1/Google.Cloud.BeyondCorp.ClientGateways.V1.sln
  apis/Google.Cloud.BeyondCorp.ClientGateways.V1/Google.Cloud.BeyondCorp.ClientGateways.V1/ClientGatewaysService.g.cs
  apis/Google.Cloud.BeyondCorp.ClientGateways.V1/Google.Cloud.BeyondCorp.ClientGateways.V1/ClientGatewaysServiceClient.g.cs
  apis/Google.Cloud.BeyondCorp.ClientGateways.V1/Google.Cloud.BeyondCorp.ClientGateways.V1/ClientGatewaysServiceGrpc.g.cs
  apis/Google.Cloud.BeyondCorp.ClientGateways.V1/Google.Cloud.BeyondCorp.ClientGateways.V1/ClientGatewaysServiceResourceNames.g.cs
  apis/Google.Cloud.BeyondCorp.ClientGateways.V1/Google.Cloud.BeyondCorp.ClientGateways.V1/Google.Cloud.BeyondCorp.ClientGateways.V1.csproj
  apis/Google.Cloud.BeyondCorp.ClientGateways.V1/Google.Cloud.BeyondCorp.ClientGateways.V1/PackageApiMetadata.g.cs
  apis/Google.Cloud.BeyondCorp.ClientGateways.V1/Google.Cloud.BeyondCorp.ClientGateways.V1/ServiceCollectionExtensions.g.cs
  apis/Google.Cloud.BeyondCorp.ClientGateways.V1/docs/history.md
  apis/Google.Cloud.BeyondCorp.ClientGateways.V1/docs/index.md
  apis/Google.Cloud.BeyondCorp.ClientGateways.V1/gapic_metadata.json
  apis/Google.Cloud.BeyondCorp.ClientGateways.V1/smoketests.json
  apis/apis.json
Labels: autorelease: pending, snippet-bot:no-prefix-req, automerge: exact

#8906 fix(spanner/admin/database): switch service config
  apis/apis.json
Labels: api: spanner

#8913 Release Google.Cloud.Storage.V1 version 4.1.0
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.csproj
  apis/Google.Cloud.Storage.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8914 Release Google.Cloud.Video.Stitcher.V1 version 1.0.0-beta01
  README.md
  apis/Google.Cloud.Video.Stitcher.V1/.repo-metadata.json
  apis/Google.Cloud.Video.Stitcher.V1/Google.Cloud.Video.Stitcher.V1/Google.Cloud.Video.Stitcher.V1.csproj
  apis/Google.Cloud.Video.Stitcher.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8917 Release Google.Cloud.AssuredWorkloads.V1Beta1 version 2.0.0-beta03
  apis/Google.Cloud.AssuredWorkloads.V1Beta1/Google.Cloud.AssuredWorkloads.V1Beta1/Google.Cloud.AssuredWorkloads.V1Beta1.csproj
  apis/Google.Cloud.AssuredWorkloads.V1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8920 Release Google.Cloud.Dataplex.V1 version 2.1.0
  apis/Google.Cloud.Dataplex.V1/Google.Cloud.Dataplex.V1/Google.Cloud.Dataplex.V1.csproj
  apis/Google.Cloud.Dataplex.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8921 Release Google.Cloud.Dlp.V2 version 4.1.0
  apis/Google.Cloud.Dlp.V2/Google.Cloud.Dlp.V2/Google.Cloud.Dlp.V2.csproj
  apis/Google.Cloud.Dlp.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8922 Release Google.Cloud.NetworkManagement.V1 version 2.2.0
  apis/Google.Cloud.NetworkManagement.V1/Google.Cloud.NetworkManagement.V1/Google.Cloud.NetworkManagement.V1.csproj
  apis/Google.Cloud.NetworkManagement.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8923 Release Google.Cloud.NetworkSecurity.V1Beta1 version 2.0.0-beta02
  apis/Google.Cloud.NetworkSecurity.V1Beta1/Google.Cloud.NetworkSecurity.V1Beta1/Google.Cloud.NetworkSecurity.V1Beta1.csproj
  apis/Google.Cloud.NetworkSecurity.V1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8924 Release Google.Cloud.SecurityCenter.V1 version 3.2.0
  apis/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1.csproj
  apis/Google.Cloud.SecurityCenter.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8925 Release Google.Cloud.Translation.V2 version 3.1.0
  apis/Google.Cloud.Translation.V2/Google.Cloud.Translation.V2/Google.Cloud.Translation.V2.csproj
  apis/Google.Cloud.Translation.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8926 Release Google.Cloud.VMMigration.V1 version 2.1.0
  apis/Google.Cloud.VMMigration.V1/Google.Cloud.VMMigration.V1/Google.Cloud.VMMigration.V1.csproj
  apis/Google.Cloud.VMMigration.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8919 Release Google.Cloud.BigQuery.V2 version 3.1.0
  apis/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2.csproj
  apis/Google.Cloud.BigQuery.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8918 Release Google.Cloud.BigQuery.Migration.V2 version 1.0.0-beta02
  apis/Google.Cloud.BigQuery.Migration.V2/Google.Cloud.BigQuery.Migration.V2/Google.Cloud.BigQuery.Migration.V2.csproj
  apis/Google.Cloud.BigQuery.Migration.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8936 Release Google.Cloud.Functions.V2 version 1.0.0-beta01
  README.md
  apis/Google.Cloud.Functions.V2/.repo-metadata.json
  apis/Google.Cloud.Functions.V2/Google.Cloud.Functions.V2/Google.Cloud.Functions.V2.csproj
  apis/Google.Cloud.Functions.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8939 Release Google.Cloud.BigQuery.Connection.V1 version 2.1.0
  apis/Google.Cloud.BigQuery.Connection.V1/Google.Cloud.BigQuery.Connection.V1/Google.Cloud.BigQuery.Connection.V1.csproj
  apis/Google.Cloud.BigQuery.Connection.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8942 Release Google.Cloud.PubSub.V1 version 3.1.0
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1.csproj
  apis/Google.Cloud.PubSub.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8940 Release Google.Cloud.Bigtable.Admin.V2 version 3.2.0
  apis/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2.csproj
  apis/Google.Cloud.Bigtable.Admin.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8941 Release Google.Cloud.Datastore.V1 version 4.2.0
  apis/Google.Cloud.Datastore.V1/Google.Cloud.Datastore.V1/Google.Cloud.Datastore.V1.csproj
  apis/Google.Cloud.Datastore.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact
