Repository googleapis/google-cloud-dotnet, pull requests merged in 2022-04, with the labels that each got.

#8287 fix(PubSub): Invalid Arguments error should not be thrown to the client
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1.Tests/SubscriberClientTest.cs
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/SubscriberClient.cs
Labels: api: pubsub

#8298 Release Google.Cloud.PubSub.V1 version 2.9.0
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1.csproj
  apis/Google.Cloud.PubSub.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8304 Release Google.Cloud.Datastore.V1 version 3.4.0
  apis/Google.Cloud.Datastore.V1/Google.Cloud.Datastore.V1/Google.Cloud.Datastore.V1.csproj
  apis/Google.Cloud.Datastore.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8306 Release Google.Cloud.Dlp.V2 version 3.5.0
  apis/Google.Cloud.Dlp.V2/Google.Cloud.Dlp.V2/Google.Cloud.Dlp.V2.csproj
  apis/Google.Cloud.Dlp.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8309 Release Google.Cloud.Retail.V2 version 1.6.0
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2.csproj
  apis/Google.Cloud.Retail.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8299 Release Google.Cloud.AIPlatform.V1 version 1.6.0
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1.csproj
  apis/Google.Cloud.AIPlatform.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8308 Release Google.Cloud.Redis.V1 version 2.5.0
  apis/Google.Cloud.Redis.V1/Google.Cloud.Redis.V1/Google.Cloud.Redis.V1.csproj
  apis/Google.Cloud.Redis.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8302 Release Google.Cloud.Bigtable.Admin.V2 version 2.8.0
  apis/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2.csproj
  apis/Google.Cloud.Bigtable.Admin.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8305 Release Google.Cloud.Dialogflow.Cx.V3 version 1.11.0
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3.csproj
  apis/Google.Cloud.Dialogflow.Cx.V3/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8301 Release Google.Cloud.BigQuery.Storage.V1 version 2.9.0
  apis/Google.Cloud.BigQuery.Storage.V1/Google.Cloud.BigQuery.Storage.V1/Google.Cloud.BigQuery.Storage.V1.csproj
  apis/Google.Cloud.BigQuery.Storage.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8307 Release Google.Cloud.Metastore.V1Alpha version 1.0.0-alpha04
  apis/Google.Cloud.Metastore.V1Alpha/Google.Cloud.Metastore.V1Alpha/Google.Cloud.Metastore.V1Alpha.csproj
  apis/Google.Cloud.Metastore.V1Alpha/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8313 Release Google.Cloud.Iam.V1 version 2.4.0
  apis/Google.Cloud.Iam.V1/Google.Cloud.Iam.V1.GeneratedSnippets/IAMPolicyClient.SetIamPolicyRequestObjectAsyncSnippet.g.cs
  apis/Google.Cloud.Iam.V1/Google.Cloud.Iam.V1.GeneratedSnippets/IAMPolicyClient.SetIamPolicyRequestObjectSnippet.g.cs
  apis/Google.Cloud.Iam.V1/Google.Cloud.Iam.V1.Snippets/IAMPolicyClientSnippets.g.cs
  apis/Google.Cloud.Iam.V1/Google.Cloud.Iam.V1.Tests/IAMPolicyClientTest.g.cs
  apis/Google.Cloud.Iam.V1/Google.Cloud.Iam.V1/Google.Cloud.Iam.V1.csproj
  apis/Google.Cloud.Iam.V1/Google.Cloud.Iam.V1/IAMPolicyClient.g.cs
  apis/Google.Cloud.Iam.V1/Google.Cloud.Iam.V1/IamPolicy.g.cs
  apis/Google.Cloud.Iam.V1/Google.Cloud.Iam.V1/IamPolicyGrpc.g.cs
  apis/Google.Cloud.Iam.V1/Google.Cloud.Iam.V1/Options.g.cs
  apis/Google.Cloud.Iam.V1/Google.Cloud.Iam.V1/Policy.g.cs
  apis/Google.Cloud.Iam.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8333 Release Google.Cloud.Compute.V1 version 1.2.0
  apis/Google.Cloud.Compute.V1/Google.Cloud.Compute.V1/Google.Cloud.Compute.V1.csproj
  apis/Google.Cloud.Compute.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8344 Release Google.Cloud.Compute.V1 version 1.3.0
  apis/Google.Cloud.Compute.V1/Google.Cloud.Compute.V1/Google.Cloud.Compute.V1.csproj
  apis/Google.Cloud.Compute.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, allow breaking changes

#8362 Release Google.Cloud.Eventarc.Publishing.V1 version 1.0.0-beta02
  apis/Google.Cloud.Eventarc.Publishing.V1/Google.Cloud.Eventarc.Publishing.V1/Google.Cloud.Eventarc.Publishing.V1.csproj
  apis/Google.Cloud.Eventarc.Publishing.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8367 feat(Spanner): SpannerDate and its unit tests
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.IntegrationTests/DateTimestampReadTests.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.Tests/V1/SpannerDateTests.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/SpannerDataReader.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/SpannerDbType.ValueConversion.cs
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/SpannerDate.cs
Labels: api: spanner

#8378 Release Google.Cloud.BigQuery.DataTransfer.V1 version 3.4.0
  apis/Google.Cloud.BigQuery.DataTransfer.V1/Google.Cloud.BigQuery.DataTransfer.V1/Google.Cloud.BigQuery.DataTransfer.V1.csproj
  apis/Google.Cloud.BigQuery.DataTransfer.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8403 Release Google.Identity.AccessContextManager.V1 version 1.5.0
  apis/Google.Identity.AccessContextManager.V1/Google.Identity.AccessContextManager.V1/Google.Identity.AccessContextManager.V1.csproj
  apis/Google.Identity.AccessContextManager.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8402 Release Google.Cloud.Vision.V1 version 2.5.0
  apis/Google.Cloud.Vision.V1/Google.Cloud.Vision.V1/Google.Cloud.Vision.V1.csproj
  apis/Google.Cloud.Vision.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8399 Release Google.Cloud.StorageTransfer.V1 version 1.2.0
  apis/Google.Cloud.StorageTransfer.V1/Google.Cloud.StorageTransfer.V1/Google.Cloud.StorageTransfer.V1.csproj
  apis/Google.Cloud.StorageTransfer.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8400 Release Google.Cloud.Talent.V4 version 1.4.0
  apis/Google.Cloud.Talent.V4/Google.Cloud.Talent.V4/Google.Cloud.Talent.V4.csproj
  apis/Google.Cloud.Talent.V4/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8394 Release Google.Cloud.SecurityCenter.V1 version 2.13.0
  apis/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1.csproj
  apis/Google.Cloud.SecurityCenter.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8395 Release Google.Cloud.ServiceDirectory.V1 version 1.4.0
  apis/Google.Cloud.ServiceDirectory.V1/Google.Cloud.ServiceDirectory.V1/Google.Cloud.ServiceDirectory.V1.csproj
  apis/Google.Cloud.ServiceDirectory.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8386 Release Google.Cloud.Deploy.V1 version 1.1.0
  apis/Google.Cloud.Deploy.V1/Google.Cloud.Deploy.V1/Google.Cloud.Deploy.V1.csproj
  apis/Google.Cloud.Deploy.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8388 Release Google.Cloud.DocumentAI.V1 version 1.5.0
  apis/Google.Cloud.DocumentAI.V1/Google.Cloud.DocumentAI.V1/Google.Cloud.DocumentAI.V1.csproj
  apis/Google.Cloud.DocumentAI.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8393 Release Google.Cloud.SecretManager.V1 version 1.9.0
  apis/Google.Cloud.SecretManager.V1/Google.Cloud.SecretManager.V1/Google.Cloud.SecretManager.V1.csproj
  apis/Google.Cloud.SecretManager.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8398 Release Google.Cloud.Speech.V1P1Beta1 version 2.0.0-beta08
  apis/Google.Cloud.Speech.V1P1Beta1/Google.Cloud.Speech.V1P1Beta1/Google.Cloud.Speech.V1P1Beta1.csproj
  apis/Google.Cloud.Speech.V1P1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8381 Release Google.Cloud.CertificateManager.V1 version 1.0.0-beta02
  apis/Google.Cloud.CertificateManager.V1/Google.Cloud.CertificateManager.V1/Google.Cloud.CertificateManager.V1.csproj
  apis/Google.Cloud.CertificateManager.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8387 Release Google.Cloud.Dialogflow.Cx.V3 version 1.12.0
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3.csproj
  apis/Google.Cloud.Dialogflow.Cx.V3/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8392 Release Google.Cloud.Notebooks.V1 version 1.0.0-beta03
  apis/Google.Cloud.Notebooks.V1/Google.Cloud.Notebooks.V1/Google.Cloud.Notebooks.V1.csproj
  apis/Google.Cloud.Notebooks.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8396 Release Google.Cloud.ServiceManagement.V1 version 1.5.0
  apis/Google.Cloud.ServiceManagement.V1/Google.Cloud.ServiceManagement.V1/Google.Cloud.ServiceManagement.V1.csproj
  apis/Google.Cloud.ServiceManagement.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8374 Release Google.Cloud.AppEngine.V1 version 1.3.0
  apis/Google.Cloud.AppEngine.V1/Google.Cloud.AppEngine.V1/Google.Cloud.AppEngine.V1.csproj
  apis/Google.Cloud.AppEngine.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8382 Release Google.Cloud.Channel.V1 version 1.7.0
  apis/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1.csproj
  apis/Google.Cloud.Channel.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8390 Release Google.Cloud.Iam.Admin.V1 version 1.2.0
  apis/Google.Cloud.Iam.Admin.V1/Google.Cloud.Iam.Admin.V1/Google.Cloud.Iam.Admin.V1.csproj
  apis/Google.Cloud.Iam.Admin.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8397 Release Google.Cloud.Speech.V1 version 2.8.0
  apis/Google.Cloud.Speech.V1/Google.Cloud.Speech.V1/Google.Cloud.Speech.V1.csproj
  apis/Google.Cloud.Speech.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8375 Release Google.Cloud.ArtifactRegistry.V1Beta2 version 1.0.0-beta06
  apis/Google.Cloud.ArtifactRegistry.V1Beta2/Google.Cloud.ArtifactRegistry.V1Beta2/Google.Cloud.ArtifactRegistry.V1Beta2.csproj
  apis/Google.Cloud.ArtifactRegistry.V1Beta2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8380 Release Google.Cloud.BigQuery.V2 version 2.4.0-beta02
  apis/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2.csproj
  apis/Google.Cloud.BigQuery.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8391 Release Google.Cloud.Monitoring.V3 version 2.6.0
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3.csproj
  apis/Google.Cloud.Monitoring.V3/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8377 Release Google.Cloud.BigQuery.Connection.V1 version 1.6.0
  apis/Google.Cloud.BigQuery.Connection.V1/Google.Cloud.BigQuery.Connection.V1/Google.Cloud.BigQuery.Connection.V1.csproj
  apis/Google.Cloud.BigQuery.Connection.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8384 Release Google.Cloud.DataCatalog.V1 version 1.8.0
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1.csproj
  apis/Google.Cloud.DataCatalog.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8376 Release Google.Cloud.AutoML.V1 version 2.6.0
  apis/Google.Cloud.AutoML.V1/Google.Cloud.AutoML.V1/Google.Cloud.AutoML.V1.csproj
  apis/Google.Cloud.AutoML.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8389 Release Google.Cloud.Gaming.V1 version 1.4.0
  apis/Google.Cloud.Gaming.V1/Google.Cloud.Gaming.V1/Google.Cloud.Gaming.V1.csproj
  apis/Google.Cloud.Gaming.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8383 Release Google.Cloud.ContactCenterInsights.V1 version 1.3.0
  apis/Google.Cloud.ContactCenterInsights.V1/Google.Cloud.ContactCenterInsights.V1/Google.Cloud.ContactCenterInsights.V1.csproj
  apis/Google.Cloud.ContactCenterInsights.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8385 Release Google.Cloud.Datastore.V1 version 3.5.0
  apis/Google.Cloud.Datastore.V1/Google.Cloud.Datastore.V1/Google.Cloud.Datastore.V1.csproj
  apis/Google.Cloud.Datastore.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#8373 Release Google.Cloud.AIPlatform.V1 version 1.7.0
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1.csproj
  apis/Google.Cloud.AIPlatform.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact
