Repository googleapis/google-cloud-dotnet, pull requests merged in 2022-09, with the labels that each got.

#9072 Release Google.Cloud.BigQuery.DataExchange.V1Beta1 version 2.0.0-beta02
  apis/Google.Cloud.BigQuery.DataExchange.V1Beta1/Google.Cloud.BigQuery.DataExchange.V1Beta1/Google.Cloud.BigQuery.DataExchange.V1Beta1.csproj
  apis/Google.Cloud.BigQuery.DataExchange.V1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9080 Release Google.Cloud.Batch.V1Alpha version 1.0.0-alpha03
  apis/Google.Cloud.Batch.V1Alpha/Google.Cloud.Batch.V1Alpha/Google.Cloud.Batch.V1Alpha.csproj
  apis/Google.Cloud.Batch.V1Alpha/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9082 Release Google.Cloud.Dlp.V2 version 4.2.0
  apis/Google.Cloud.Dlp.V2/Google.Cloud.Dlp.V2/Google.Cloud.Dlp.V2.csproj
  apis/Google.Cloud.Dlp.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9083 Release Google.Maps.Routing.V2 version 1.0.0-beta04
  apis/Google.Maps.Routing.V2/Google.Maps.Routing.V2/Google.Maps.Routing.V2.csproj
  apis/Google.Maps.Routing.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9079 Release Google.Cloud.AssuredWorkloads.V1Beta1 version 2.0.0-beta04
  apis/Google.Cloud.AssuredWorkloads.V1Beta1/Google.Cloud.AssuredWorkloads.V1Beta1/Google.Cloud.AssuredWorkloads.V1Beta1.csproj
  apis/Google.Cloud.AssuredWorkloads.V1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9081 Release Google.Cloud.Container.V1 version 3.2.0
  apis/Google.Cloud.Container.V1/Google.Cloud.Container.V1/Google.Cloud.Container.V1.csproj
  apis/Google.Cloud.Container.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9078 Release Google.Cloud.ApigeeRegistry.V1 version 1.0.0-beta03
  apis/Google.Cloud.ApigeeRegistry.V1/Google.Cloud.ApigeeRegistry.V1/Google.Cloud.ApigeeRegistry.V1.csproj
  apis/Google.Cloud.ApigeeRegistry.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9102 Release Google.Cloud.BigQuery.Logging.V1 version 1.0.0
  README.md
  apis/Google.Cloud.BigQuery.Logging.V1/.repo-metadata.json
  apis/Google.Cloud.BigQuery.Logging.V1/Google.Cloud.BigQuery.Logging.V1/Google.Cloud.BigQuery.Logging.V1.csproj
  apis/Google.Cloud.BigQuery.Logging.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9103 Release Google.Cloud.AppEngine.Logging.V1 version 1.0.0
  README.md
  apis/Google.Cloud.AppEngine.Logging.V1/.repo-metadata.json
  apis/Google.Cloud.AppEngine.Logging.V1/Google.Cloud.AppEngine.Logging.V1/Google.Cloud.AppEngine.Logging.V1.csproj
  apis/Google.Cloud.AppEngine.Logging.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9113 Release Google.Cloud.BareMetalSolution.V2 version 1.0.0
  apis/Google.Cloud.BareMetalSolution.V2/.repo-metadata.json
  apis/Google.Cloud.BareMetalSolution.V2/Google.Cloud.BareMetalSolution.V2/Google.Cloud.BareMetalSolution.V2.csproj
  apis/Google.Cloud.BareMetalSolution.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9112 Release Google.Cloud.ApiKeys.V2 version 1.0.0
  apis/Google.Cloud.ApiKeys.V2/.repo-metadata.json
  apis/Google.Cloud.ApiKeys.V2/Google.Cloud.ApiKeys.V2/Google.Cloud.ApiKeys.V2.csproj
  apis/Google.Cloud.ApiKeys.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9117 Release Google.Cloud.Functions.V2 version 1.0.0
  apis/Google.Cloud.Functions.V2/.repo-metadata.json
  apis/Google.Cloud.Functions.V2/Google.Cloud.Functions.V2/Google.Cloud.Functions.V2.csproj
  apis/Google.Cloud.Functions.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9116 Release Google.Cloud.CertificateManager.V1 version 2.0.0
  apis/Google.Cloud.CertificateManager.V1/Google.Cloud.CertificateManager.V1/Google.Cloud.CertificateManager.V1.csproj
  apis/Google.Cloud.CertificateManager.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9120 Release Google.Cloud.Optimization.V1 version 2.0.0
  apis/Google.Cloud.Optimization.V1/Google.Cloud.Optimization.V1/Google.Cloud.Optimization.V1.csproj
  apis/Google.Cloud.Optimization.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9114 Release BeyondCorp libraries version 1.0.0
  apis/Google.Cloud.BeyondCorp.AppConnections.V1/.repo-metadata.json
  apis/Google.Cloud.BeyondCorp.AppConnections.V1/Google.Cloud.BeyondCorp.AppConnections.V1/Google.Cloud.BeyondCorp.AppConnections.V1.csproj
  apis/Google.Cloud.BeyondCorp.AppConnections.V1/docs/history.md
  apis/Google.Cloud.BeyondCorp.AppConnectors.V1/.repo-metadata.json
  apis/Google.Cloud.BeyondCorp.AppConnectors.V1/Google.Cloud.BeyondCorp.AppConnectors.V1/Google.Cloud.BeyondCorp.AppConnectors.V1.csproj
  apis/Google.Cloud.BeyondCorp.AppConnectors.V1/docs/history.md
  apis/Google.Cloud.BeyondCorp.AppGateways.V1/.repo-metadata.json
  apis/Google.Cloud.BeyondCorp.AppGateways.V1/Google.Cloud.BeyondCorp.AppGateways.V1/Google.Cloud.BeyondCorp.AppGateways.V1.csproj
  apis/Google.Cloud.BeyondCorp.AppGateways.V1/docs/history.md
  apis/Google.Cloud.BeyondCorp.ClientConnectorServices.V1/.repo-metadata.json
  apis/Google.Cloud.BeyondCorp.ClientConnectorServices.V1/Google.Cloud.BeyondCorp.ClientConnectorServices.V1/Google.Cloud.BeyondCorp.ClientConnectorServices.V1.csproj
  apis/Google.Cloud.BeyondCorp.ClientConnectorServices.V1/docs/history.md
  apis/Google.Cloud.BeyondCorp.ClientGateways.V1/.repo-metadata.json
  apis/Google.Cloud.BeyondCorp.ClientGateways.V1/Google.Cloud.BeyondCorp.ClientGateways.V1/Google.Cloud.BeyondCorp.ClientGateways.V1.csproj
  apis/Google.Cloud.BeyondCorp.ClientGateways.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9118 Release Google.Cloud.GkeMultiCloud.V1 version 2.0.0
  apis/Google.Cloud.GkeMultiCloud.V1/Google.Cloud.GkeMultiCloud.V1/Google.Cloud.GkeMultiCloud.V1.csproj
  apis/Google.Cloud.GkeMultiCloud.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9119 Release Google.Cloud.Notebooks.V1 version 2.0.0
  apis/Google.Cloud.Notebooks.V1/Google.Cloud.Notebooks.V1/Google.Cloud.Notebooks.V1.csproj
  apis/Google.Cloud.Notebooks.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9115 Release Google.Cloud.BigQuery.Migration.V2 version 1.0.0
  apis/Google.Cloud.BigQuery.Migration.V2/.repo-metadata.json
  apis/Google.Cloud.BigQuery.Migration.V2/Google.Cloud.BigQuery.Migration.V2/Google.Cloud.BigQuery.Migration.V2.csproj
  apis/Google.Cloud.BigQuery.Migration.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9133 Release Google.Cloud.Vision.V1 version 3.2.0
  apis/Google.Cloud.Vision.V1/Google.Cloud.Vision.V1/Google.Cloud.Vision.V1.csproj
  apis/Google.Cloud.Vision.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9128 Release Google.Cloud.RecommendationEngine.V1Beta1 version 2.0.0-beta02
  apis/Google.Cloud.RecommendationEngine.V1Beta1/Google.Cloud.RecommendationEngine.V1Beta1/Google.Cloud.RecommendationEngine.V1Beta1.csproj
  apis/Google.Cloud.RecommendationEngine.V1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9129 Release Google.Cloud.SecurityCenter.V1 version 3.4.0
  apis/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1.csproj
  apis/Google.Cloud.SecurityCenter.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9134 Release Google.Cloud.WebSecurityScanner.V1 version 2.1.0
  apis/Google.Cloud.WebSecurityScanner.V1/Google.Cloud.WebSecurityScanner.V1/Google.Cloud.WebSecurityScanner.V1.csproj
  apis/Google.Cloud.WebSecurityScanner.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9123 Release Google.Cloud.BigQuery.Storage.V1 version 3.3.0
  apis/Google.Cloud.BigQuery.Storage.V1/Google.Cloud.BigQuery.Storage.V1/Google.Cloud.BigQuery.Storage.V1.csproj
  apis/Google.Cloud.BigQuery.Storage.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9132 Release Google.Cloud.Trace.V2 version 3.1.0
  apis/Google.Cloud.Trace.V2/Google.Cloud.Trace.V2/Google.Cloud.Trace.V2.csproj
  apis/Google.Cloud.Trace.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9125 Release Google.Cloud.Compute.V1 version 2.2.0
  apis/Google.Cloud.Compute.V1/Google.Cloud.Compute.V1/Google.Cloud.Compute.V1.csproj
  apis/Google.Cloud.Compute.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9131 Release Google.Cloud.Talent.V4 version 2.1.0
  apis/Google.Cloud.Talent.V4/Google.Cloud.Talent.V4/Google.Cloud.Talent.V4.csproj
  apis/Google.Cloud.Talent.V4/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9124 Release Google.Cloud.Bigtable.Admin.V2 version 3.3.0
  apis/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2.GeneratedSnippets/Google.Cloud.Bigtable.Admin.V2.GeneratedSnippets.csproj
  apis/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2.Snippets/Google.Cloud.Bigtable.Admin.V2.Snippets.csproj
  apis/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2.Tests/Google.Cloud.Bigtable.Admin.V2.Tests.csproj
  apis/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2.csproj
  apis/Google.Cloud.Bigtable.Admin.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9130 Release Google.Cloud.StorageTransfer.V1 version 2.1.0
  apis/Google.Cloud.StorageTransfer.V1/Google.Cloud.StorageTransfer.V1/Google.Cloud.StorageTransfer.V1.csproj
  apis/Google.Cloud.StorageTransfer.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9126 Release Google.Cloud.ContactCenterInsights.V1 version 2.1.0
  apis/Google.Cloud.ContactCenterInsights.V1/Google.Cloud.ContactCenterInsights.V1/Google.Cloud.ContactCenterInsights.V1.csproj
  apis/Google.Cloud.ContactCenterInsights.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9142 Release Spanner libraries version 4.1.0
  apis/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1.csproj
  apis/Google.Cloud.Spanner.Admin.Instance.V1/Google.Cloud.Spanner.Admin.Instance.V1/Google.Cloud.Spanner.Admin.Instance.V1.csproj
  apis/Google.Cloud.Spanner.Common.V1/Google.Cloud.Spanner.Common.V1/Google.Cloud.Spanner.Common.V1.csproj
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.IntegrationTests/Google.Cloud.Spanner.Data.IntegrationTests.csproj
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.Snippets/Google.Cloud.Spanner.Data.Snippets.csproj
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.Tests/Google.Cloud.Spanner.Data.Tests.csproj
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.csproj
  apis/Google.Cloud.Spanner.Data/docs/history.md
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1.csproj
  apis/apis.json
Labels: autorelease: pending

#9167 feat: Support dependency injection of SpannerConnection
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.IntegrationTests/Google.Cloud.Spanner.Data.IntegrationTests.csproj
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.Snippets/Google.Cloud.Spanner.Data.Snippets.csproj
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.Snippets/SpannerConnectionSnippets.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.Tests/Google.Cloud.Spanner.Data.Tests.csproj
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.Tests/ServiceCollectionExtensionsTests.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.csproj
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/ServiceCollectionExtensions.cs
  apis/Google.Cloud.Spanner.Data/docs/index.md
  apis/apis.json
Labels: automerge: exact

#9171 Release Google.Cloud.Speech.V2 version 1.0.0-beta01
  README.md
  apis/Google.Cloud.Speech.V2/.repo-metadata.json
  apis/Google.Cloud.Speech.V2/Google.Cloud.Speech.V2.Snippets/SpeechClientSnippets.cs
  apis/Google.Cloud.Speech.V2/Google.Cloud.Speech.V2/Google.Cloud.Speech.V2.csproj
  apis/Google.Cloud.Speech.V2/docs/history.md
  apis/Google.Cloud.Speech.V2/docs/index.md
  apis/Google.Cloud.Speech.V2/smoketests.json
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9172 Release Google.Cloud.BigQuery.AnalyticsHub.V1 version 1.0.0-beta01
  README.md
  apis/Google.Cloud.BigQuery.AnalyticsHub.V1/.repo-metadata.json
  apis/Google.Cloud.BigQuery.AnalyticsHub.V1/Google.Cloud.BigQuery.AnalyticsHub.V1/Google.Cloud.BigQuery.AnalyticsHub.V1.csproj
  apis/Google.Cloud.BigQuery.AnalyticsHub.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact
