Repository googleapis/google-cloud-dotnet, pull requests merged in 2023-10, with the labels that each got.

#11121 Release Google.Cloud.AlloyDb.V1 version 1.3.0
  apis/Google.Cloud.AlloyDb.V1/Google.Cloud.AlloyDb.V1/Google.Cloud.AlloyDb.V1.csproj
  apis/Google.Cloud.AlloyDb.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11124 Release Google.Cloud.Dialogflow.V2 version 4.14.0
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2.csproj
  apis/Google.Cloud.Dialogflow.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11123 Release Google.Cloud.Dialogflow.Cx.V3 version 2.13.0
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3.csproj
  apis/Google.Cloud.Dialogflow.Cx.V3/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11125 Release Google.Cloud.Dialogflow.V2Beta1 version 1.0.0-beta11
  apis/Google.Cloud.Dialogflow.V2Beta1/Google.Cloud.Dialogflow.V2Beta1/Google.Cloud.Dialogflow.V2Beta1.csproj
  apis/Google.Cloud.Dialogflow.V2Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11129 Release Google.Cloud.NetworkConnectivity.V1 version 2.5.0
  apis/Google.Cloud.NetworkConnectivity.V1/Google.Cloud.NetworkConnectivity.V1/Google.Cloud.NetworkConnectivity.V1.csproj
  apis/Google.Cloud.NetworkConnectivity.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11130 Release Google.Cloud.OsLogin.V1Beta version 3.0.0-beta04
  apis/Google.Cloud.OsLogin.V1Beta/Google.Cloud.OsLogin.V1Beta/Google.Cloud.OsLogin.V1Beta.csproj
  apis/Google.Cloud.OsLogin.V1Beta/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11127 Release Google.Cloud.Metastore.V1Alpha version 2.0.0-alpha07
  apis/Google.Cloud.Metastore.V1Alpha/Google.Cloud.Metastore.V1Alpha/Google.Cloud.Metastore.V1Alpha.csproj
  apis/Google.Cloud.Metastore.V1Alpha/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11137 Release Firestore libraries version 3.4.0
  apis/Google.Cloud.Firestore.V1/Google.Cloud.Firestore.V1/Google.Cloud.Firestore.V1.csproj
  apis/Google.Cloud.Firestore.V1/docs/history.md
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore/Google.Cloud.Firestore.csproj
  apis/Google.Cloud.Firestore/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11155 Release Google.Shopping.Type version 1.0.0-beta01
  README.md
  apis/Google.Shopping.Type/.repo-metadata.json
  apis/Google.Shopping.Type/Google.Shopping.Type/Google.Shopping.Type.csproj
  apis/Google.Shopping.Type/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11174 Release Google.Shopping.Type version 1.0.0-beta02
  apis/Google.Shopping.Type/Google.Shopping.Type/Google.Shopping.Type.csproj
  apis/Google.Shopping.Type/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11177 Release Google.Cloud.BigQuery.V2 version 3.5.0
  apis/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2.csproj
  apis/Google.Cloud.BigQuery.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11179 Release Google.Shopping.Merchant.Inventories.V1Beta version 1.0.0-beta01
  README.md
  apis/Google.Shopping.Merchant.Inventories.V1Beta/.repo-metadata.json
  apis/Google.Shopping.Merchant.Inventories.V1Beta/Google.Shopping.Merchant.Inventories.V1Beta/Google.Shopping.Merchant.Inventories.V1Beta.csproj
  apis/Google.Shopping.Merchant.Inventories.V1Beta/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11200 chore: Remove Google.Cloud.Redis.Cluster.V1Beta1
  .github/renovate.json
  apis/Google.Cloud.Redis.Cluster.V1Beta1/.OwlBot.yaml
  apis/Google.Cloud.Redis.Cluster.V1Beta1/.repo-metadata.json
  apis/Google.Cloud.Redis.Cluster.V1Beta1/Google.Cloud.Redis.Cluster.V1Beta1.GeneratedSnippets/CloudRedisClusterClient.CreateClusterAsyncSnippet.g.cs
  apis/Google.Cloud.Redis.Cluster.V1Beta1/Google.Cloud.Redis.Cluster.V1Beta1.GeneratedSnippets/CloudRedisClusterClient.CreateClusterRequestObjectAsyncSnippet.g.cs
  apis/Google.Cloud.Redis.Cluster.V1Beta1/Google.Cloud.Redis.Cluster.V1Beta1.GeneratedSnippets/CloudRedisClusterClient.CreateClusterRequestObjectSnippet.g.cs
  apis/Google.Cloud.Redis.Cluster.V1Beta1/Google.Cloud.Redis.Cluster.V1Beta1.GeneratedSnippets/CloudRedisClusterClient.CreateClusterResourceNamesAsyncSnippet.g.cs
  apis/Google.Cloud.Redis.Cluster.V1Beta1/Google.Cloud.Redis.Cluster.V1Beta1.GeneratedSnippets/CloudRedisClusterClient.CreateClusterResourceNamesSnippet.g.cs
  apis/Google.Cloud.Redis.Cluster.V1Beta1/Google.Cloud.Redis.Cluster.V1Beta1.GeneratedSnippets/CloudRedisClusterClient.CreateClusterSnippet.g.cs
  apis/Google.Cloud.Redis.Cluster.V1Beta1/Google.Cloud.Redis.Cluster.V1Beta1.GeneratedSnippets/CloudRedisClusterClient.DeleteClusterAsyncSnippet.g.cs
  apis/Google.Cloud.Redis.Cluster.V1Beta1/Google.Cloud.Redis.Cluster.V1Beta1.GeneratedSnippets/CloudRedisClusterClient.DeleteClusterRequestObjectAsyncSnippet.g.cs
  apis/Google.Cloud.Redis.Cluster.V1Beta1/Google.Cloud.Redis.Cluster.V1Beta1.GeneratedSnippets/CloudRedisClusterClient.DeleteClusterRequestObjectSnippet.g.cs
  apis/Google.Cloud.Redis.Cluster.V1Beta1/Google.Cloud.Redis.Cluster.V1Beta1.GeneratedSnippets/CloudRedisClusterClient.DeleteClusterResourceNamesAsyncSnippet.g.cs
  apis/Google.Cloud.Redis.Cluster.V1Beta1/Google.Cloud.Redis.Cluster.V1Beta1.GeneratedSnippets/CloudRedisClusterClient.DeleteClusterResourceNamesSnippet.g.cs
  apis/Google.Cloud.Redis.Cluster.V1Beta1/Google.Cloud.Redis.Cluster.V1Beta1.GeneratedSnippets/CloudRedisClusterClient.DeleteClusterSnippet.g.cs
  apis/Google.Cloud.Redis.Cluster.V1Beta1/Google.Cloud.Redis.Cluster.V1Beta1.GeneratedSnippets/CloudRedisClusterClient.GetClusterAsyncSnippet.g.cs
  apis/Google.Cloud.Redis.Cluster.V1Beta1/Google.Cloud.Redis.Cluster.V1Beta1.GeneratedSnippets/CloudRedisClusterClient.GetClusterRequestObjectAsyncSnippet.g.cs
  apis/Google.Cloud.Redis.Cluster.V1Beta1/Google.Cloud.Redis.Cluster.V1Beta1.GeneratedSnippets/CloudRedisClusterClient.GetClusterRequestObjectSnippet.g.cs
  apis/Google.Cloud.Redis.Cluster.V1Beta1/Google.Cloud.Redis.Cluster.V1Beta1.GeneratedSnippets/CloudRedisClusterClient.GetClusterResourceNamesAsyncSnippet.g.cs
  apis/Google.Cloud.Redis.Cluster.V1Beta1/Google.Cloud.Redis.Cluster.V1Beta1.GeneratedSnippets/CloudRedisClusterClient.GetClusterResourceNamesSnippet.g.cs
  apis/Google.Cloud.Redis.Cluster.V1Beta1/Google.Cloud.Redis.Cluster.V1Beta1.GeneratedSnippets/CloudRedisClusterClient.GetClusterSnippet.g.cs
  apis/Google.Cloud.Redis.Cluster.V1Beta1/Google.Cloud.Redis.Cluster.V1Beta1.GeneratedSnippets/CloudRedisClusterClient.ListClustersAsyncSnippet.g.cs
  apis/Google.Cloud.Redis.Cluster.V1Beta1/Google.Cloud.Redis.Cluster.V1Beta1.GeneratedSnippets/CloudRedisClusterClient.ListClustersRequestObjectAsyncSnippet.g.cs
  apis/Google.Cloud.Redis.Cluster.V1Beta1/Google.Cloud.Redis.Cluster.V1Beta1.GeneratedSnippets/CloudRedisClusterClient.ListClustersRequestObjectSnippet.g.cs
  apis/Google.Cloud.Redis.Cluster.V1Beta1/Google.Cloud.Redis.Cluster.V1Beta1.GeneratedSnippets/CloudRedisClusterClient.ListClustersResourceNamesAsyncSnippet.g.cs
  apis/Google.Cloud.Redis.Cluster.V1Beta1/Google.Cloud.Redis.Cluster.V1Beta1.GeneratedSnippets/CloudRedisClusterClient.ListClustersResourceNamesSnippet.g.cs
  apis/Google.Cloud.Redis.Cluster.V1Beta1/Google.Cloud.Redis.Cluster.V1Beta1.GeneratedSnippets/CloudRedisClusterClient.ListClustersSnippet.g.cs
  apis/Google.Cloud.Redis.Cluster.V1Beta1/Google.Cloud.Redis.Cluster.V1Beta1.GeneratedSnippets/CloudRedisClusterClient.UpdateClusterAsyncSnippet.g.cs
  apis/Google.Cloud.Redis.Cluster.V1Beta1/Google.Cloud.Redis.Cluster.V1Beta1.GeneratedSnippets/CloudRedisClusterClient.UpdateClusterRequestObjectAsyncSnippet.g.cs
  apis/Google.Cloud.Redis.Cluster.V1Beta1/Google.Cloud.Redis.Cluster.V1Beta1.GeneratedSnippets/CloudRedisClusterClient.UpdateClusterRequestObjectSnippet.g.cs
  apis/Google.Cloud.Redis.Cluster.V1Beta1/Google.Cloud.Redis.Cluster.V1Beta1.GeneratedSnippets/CloudRedisClusterClient.UpdateClusterSnippet.g.cs
  apis/Google.Cloud.Redis.Cluster.V1Beta1/Google.Cloud.Redis.Cluster.V1Beta1.GeneratedSnippets/Google.Cloud.Redis.Cluster.V1Beta1.GeneratedSnippets.csproj
  apis/Google.Cloud.Redis.Cluster.V1Beta1/Google.Cloud.Redis.Cluster.V1Beta1.GeneratedSnippets/snippet_metadata_google.cloud.redis.cluster.v1beta1.json
  apis/Google.Cloud.Redis.Cluster.V1Beta1/Google.Cloud.Redis.Cluster.V1Beta1.Snippets/CloudRedisClusterClientSnippets.g.cs
  apis/Google.Cloud.Redis.Cluster.V1Beta1/Google.Cloud.Redis.Cluster.V1Beta1.Snippets/Google.Cloud.Redis.Cluster.V1Beta1.Snippets.csproj
  apis/Google.Cloud.Redis.Cluster.V1Beta1/Google.Cloud.Redis.Cluster.V1Beta1.Snippets/coverage.xml
  apis/Google.Cloud.Redis.Cluster.V1Beta1/Google.Cloud.Redis.Cluster.V1Beta1.sln
  apis/Google.Cloud.Redis.Cluster.V1Beta1/Google.Cloud.Redis.Cluster.V1Beta1/CloudRedisCluster.g.cs
  apis/Google.Cloud.Redis.Cluster.V1Beta1/Google.Cloud.Redis.Cluster.V1Beta1/CloudRedisClusterClient.g.cs
  apis/Google.Cloud.Redis.Cluster.V1Beta1/Google.Cloud.Redis.Cluster.V1Beta1/CloudRedisClusterGrpc.g.cs
  apis/Google.Cloud.Redis.Cluster.V1Beta1/Google.Cloud.Redis.Cluster.V1Beta1/CloudRedisClusterResourceNames.g.cs
  apis/Google.Cloud.Redis.Cluster.V1Beta1/Google.Cloud.Redis.Cluster.V1Beta1/Google.Cloud.Redis.Cluster.V1Beta1.csproj
  apis/Google.Cloud.Redis.Cluster.V1Beta1/Google.Cloud.Redis.Cluster.V1Beta1/PackageApiMetadata.g.cs
  apis/Google.Cloud.Redis.Cluster.V1Beta1/Google.Cloud.Redis.Cluster.V1Beta1/ServiceCollectionExtensions.g.cs
  apis/Google.Cloud.Redis.Cluster.V1Beta1/docs/index.md
  apis/Google.Cloud.Redis.Cluster.V1Beta1/gapic_metadata.json
  apis/Google.Cloud.Redis.Cluster.V1Beta1/smoketests.json
  apis/apis.json
Labels: allow breaking changes

#11213 Release Google.Cloud.Tools.SbomGenerator version 0.2.0
  tools/Google.Cloud.Tools.SbomGenerator/Google.Cloud.Tools.SbomGenerator.csproj
Labels: autorelease: pending

#11215 Release Google.Analytics.Admin.V1Alpha version 2.0.0-alpha14
  apis/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha.csproj
  apis/Google.Analytics.Admin.V1Alpha/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11221 Release Google.Cloud.AIPlatform.V1 version 2.20.0
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1.csproj
  apis/Google.Cloud.AIPlatform.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11232 Release Google.Cloud.Batch.V1Alpha version 1.0.0-alpha18
  apis/Google.Cloud.Batch.V1Alpha/Google.Cloud.Batch.V1Alpha/Google.Cloud.Batch.V1Alpha.csproj
  apis/Google.Cloud.Batch.V1Alpha/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11233 Release Google.Cloud.Bigtable.Admin.V2 version 3.7.0
  apis/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2.csproj
  apis/Google.Cloud.Bigtable.Admin.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11231 Release Google.Cloud.Batch.V1 version 2.5.0
  apis/Google.Cloud.Batch.V1/Google.Cloud.Batch.V1/Google.Cloud.Batch.V1.csproj
  apis/Google.Cloud.Batch.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11235 Release Google.Cloud.Dataplex.V1 version 2.8.0
  apis/Google.Cloud.Dataplex.V1/Google.Cloud.Dataplex.V1/Google.Cloud.Dataplex.V1.csproj
  apis/Google.Cloud.Dataplex.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11240 Release Google.Cloud.RecaptchaEnterprise.V1 version 2.5.0
  apis/Google.Cloud.RecaptchaEnterprise.V1/Google.Cloud.RecaptchaEnterprise.V1/Google.Cloud.RecaptchaEnterprise.V1.csproj
  apis/Google.Cloud.RecaptchaEnterprise.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11236 Release Google.Cloud.Deploy.V1 version 2.9.0
  apis/Google.Cloud.Deploy.V1/Google.Cloud.Deploy.V1/Google.Cloud.Deploy.V1.csproj
  apis/Google.Cloud.Deploy.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11238 Release Google.Cloud.Optimization.V1 version 2.3.0
  apis/Google.Cloud.Optimization.V1/Google.Cloud.Optimization.V1/Google.Cloud.Optimization.V1.csproj
  apis/Google.Cloud.Optimization.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11242 Release Google.Cloud.SecurityCenter.V1 version 3.13.0
  apis/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1.csproj
  apis/Google.Cloud.SecurityCenter.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11234 Release Google.Cloud.Dataform.V1Beta1 version 1.0.0-beta03
  apis/Google.Cloud.Dataform.V1Beta1/Google.Cloud.Dataform.V1Beta1/Google.Cloud.Dataform.V1Beta1.csproj
  apis/Google.Cloud.Dataform.V1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11230 Release Google.Cloud.ArtifactRegistry.V1 version 2.4.0
  apis/Google.Cloud.ArtifactRegistry.V1/Google.Cloud.ArtifactRegistry.V1/Google.Cloud.ArtifactRegistry.V1.csproj
  apis/Google.Cloud.ArtifactRegistry.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11241 Release Google.Cloud.RecaptchaEnterprise.V1Beta1 version 2.0.0-beta04
  apis/Google.Cloud.RecaptchaEnterprise.V1Beta1/Google.Cloud.RecaptchaEnterprise.V1Beta1/Google.Cloud.RecaptchaEnterprise.V1Beta1.csproj
  apis/Google.Cloud.RecaptchaEnterprise.V1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11239 Release Google.Cloud.OsLogin.V1Beta version 3.0.0-beta05
  apis/Google.Cloud.OsLogin.V1Beta/Google.Cloud.OsLogin.V1Beta/Google.Cloud.OsLogin.V1Beta.csproj
  apis/Google.Cloud.OsLogin.V1Beta/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11254 Release Google.Cloud.Redis.Cluster.V1 version 1.0.0-beta01
  README.md
  apis/Google.Cloud.Redis.Cluster.V1/.repo-metadata.json
  apis/Google.Cloud.Redis.Cluster.V1/Google.Cloud.Redis.Cluster.V1/Google.Cloud.Redis.Cluster.V1.csproj
  apis/Google.Cloud.Redis.Cluster.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11255 Release Google.Maps.Places.V1 version 1.0.0-beta01
  README.md
  apis/Google.Maps.Places.V1/.repo-metadata.json
  apis/Google.Maps.Places.V1/Google.Maps.Places.V1/Google.Maps.Places.V1.csproj
  apis/Google.Maps.Places.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11256 Release Google.Cloud.Storage.V1 version 4.7.0
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.IntegrationTests/DeleteObjectTest.cs
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.IntegrationTests/Google.Cloud.Storage.V1.IntegrationTests.csproj
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.IntegrationTests/RetentionPolicyTest.cs
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.IntegrationTests/UniformBucketLevelAccessTest.cs
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.Snippets/Google.Cloud.Storage.V1.Snippets.csproj
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.Snippets/StorageClientSnippets.cs
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.Tests/Google.Cloud.Storage.V1.Tests.csproj
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.csproj
  apis/Google.Cloud.Storage.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact
