Repository googleapis/google-cloud-dotnet, pull requests merged in 2023-06, with the labels that each got.

#10477 Release Google.Cloud.Firestore.Admin.V1 version 3.3.0
  apis/Google.Cloud.Firestore.Admin.V1/Google.Cloud.Firestore.Admin.V1/Google.Cloud.Firestore.Admin.V1.csproj
  apis/Google.Cloud.Firestore.Admin.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10476 Release Google.Cloud.DataCatalog.V1 version 2.4.0
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1.csproj
  apis/Google.Cloud.DataCatalog.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10475 Release Google.Cloud.Container.V1 version 3.13.0
  apis/Google.Cloud.Container.V1/Google.Cloud.Container.V1/Google.Cloud.Container.V1.csproj
  apis/Google.Cloud.Container.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10474 Release Google.Cloud.ContactCenterInsights.V1 version 2.8.0
  apis/Google.Cloud.ContactCenterInsights.V1/Google.Cloud.ContactCenterInsights.V1/Google.Cloud.ContactCenterInsights.V1.csproj
  apis/Google.Cloud.ContactCenterInsights.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10482 chore: Clean stale comments from Update SubscriberClientImpl
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/SubscriberClientImpl.cs
Labels: automerge: exact

#10498 Release Google.Cloud.Kms.Inventory.V1 version 1.0.0
  apis/Google.Cloud.Kms.Inventory.V1/.repo-metadata.json
  apis/Google.Cloud.Kms.Inventory.V1/Google.Cloud.Kms.Inventory.V1/Google.Cloud.Kms.Inventory.V1.csproj
  apis/Google.Cloud.Kms.Inventory.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10507 Release Google.Cloud.MigrationCenter.V1 version 1.0.0-beta01
  README.md
  apis/Google.Cloud.MigrationCenter.V1/.repo-metadata.json
  apis/Google.Cloud.MigrationCenter.V1/Google.Cloud.MigrationCenter.V1/Google.Cloud.MigrationCenter.V1.csproj
  apis/Google.Cloud.MigrationCenter.V1/docs/history.md
  apis/Google.Cloud.MigrationCenter.V1/smoketests.json
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10512 Release Google.Cloud.PubSub.V1 version 3.6.0
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1.csproj
  apis/Google.Cloud.PubSub.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10515 Release Google.Geo.Type version 1.0.0
  apis/Google.Geo.Type/.repo-metadata.json
  apis/Google.Geo.Type/Google.Geo.Type/Google.Geo.Type.csproj
  apis/Google.Geo.Type/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10509 Release Google.Cloud.AdvisoryNotifications.V1 version 1.0.0
  apis/Google.Cloud.AdvisoryNotifications.V1/.repo-metadata.json
  apis/Google.Cloud.AdvisoryNotifications.V1/Google.Cloud.AdvisoryNotifications.V1/Google.Cloud.AdvisoryNotifications.V1.csproj
  apis/Google.Cloud.AdvisoryNotifications.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10514 Release Google.Cloud.StorageInsights.V1 version 1.0.0
  apis/Google.Cloud.StorageInsights.V1/.repo-metadata.json
  apis/Google.Cloud.StorageInsights.V1/Google.Cloud.StorageInsights.V1/Google.Cloud.StorageInsights.V1.csproj
  apis/Google.Cloud.StorageInsights.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10511 Release Google.Cloud.Iam.V2 version 1.0.0
  apis/Google.Cloud.Iam.V2/.repo-metadata.json
  apis/Google.Cloud.Iam.V2/Google.Cloud.Iam.V2/Google.Cloud.Iam.V2.csproj
  apis/Google.Cloud.Iam.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10510 Release Google.Cloud.AlloyDb.V1 version 1.0.0
  apis/Google.Cloud.AlloyDb.V1/.repo-metadata.json
  apis/Google.Cloud.AlloyDb.V1/Google.Cloud.AlloyDb.V1/Google.Cloud.AlloyDb.V1.csproj
  apis/Google.Cloud.AlloyDb.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10533 Release Google.Cloud.Iot.V1 version 2.2.0
  apis/Google.Cloud.Iot.V1/Google.Cloud.Iot.V1/Google.Cloud.Iot.V1.csproj
  apis/Google.Cloud.Iot.V1/docs/history.md
  apis/Google.Cloud.Iot.V1/docs/index.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10549 Release Google.Cloud.AlloyDb.V1Alpha version 1.0.0-alpha02
  apis/Google.Cloud.AlloyDb.V1Alpha/Google.Cloud.AlloyDb.V1Alpha/Google.Cloud.AlloyDb.V1Alpha.csproj
  apis/Google.Cloud.AlloyDb.V1Alpha/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10553 Release Google.Cloud.Batch.V1Alpha version 1.0.0-alpha12
  apis/Google.Cloud.Batch.V1Alpha/Google.Cloud.Batch.V1Alpha/Google.Cloud.Batch.V1Alpha.csproj
  apis/Google.Cloud.Batch.V1Alpha/docs/history.md
  apis/apis.json
Labels: autorelease: pending

#10551 Release Google.Cloud.AIPlatform.V1 version 2.16.0
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1.csproj
  apis/Google.Cloud.AIPlatform.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10554 Release Google.Cloud.Billing.Budgets.V1 version 2.2.0
  apis/Google.Cloud.Billing.Budgets.V1/Google.Cloud.Billing.Budgets.V1/Google.Cloud.Billing.Budgets.V1.csproj
  apis/Google.Cloud.Billing.Budgets.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10556 Release Google.Cloud.Billing.V1 version 3.3.0
  apis/Google.Cloud.Billing.V1/Google.Cloud.Billing.V1/Google.Cloud.Billing.V1.csproj
  apis/Google.Cloud.Billing.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending

#10552 Release Google.Cloud.Batch.V1 version 2.2.0
  apis/Google.Cloud.Batch.V1/Google.Cloud.Batch.V1/Google.Cloud.Batch.V1.csproj
  apis/Google.Cloud.Batch.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10555 Release Google.Cloud.Billing.Budgets.V1Beta1 version 2.0.0-beta02
  apis/Google.Cloud.Billing.Budgets.V1Beta1/Google.Cloud.Billing.Budgets.V1Beta1/Google.Cloud.Billing.Budgets.V1Beta1.csproj
  apis/Google.Cloud.Billing.Budgets.V1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10548 Release Google.Cloud.AlloyDb.V1 version 1.1.0
  apis/Google.Cloud.AlloyDb.V1/Google.Cloud.AlloyDb.V1/Google.Cloud.AlloyDb.V1.csproj
  apis/Google.Cloud.AlloyDb.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10557 Release Google.Cloud.Channel.V1 version 2.8.0
  apis/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1.csproj
  apis/Google.Cloud.Channel.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10550 Release Google.Cloud.AlloyDb.V1Beta version 1.0.0-beta02
  apis/Google.Cloud.AlloyDb.V1Beta/Google.Cloud.AlloyDb.V1Beta/Google.Cloud.AlloyDb.V1Beta.csproj
  apis/Google.Cloud.AlloyDb.V1Beta/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10560 Release Google.Cloud.Dialogflow.Cx.V3 version 2.8.0
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3.csproj
  apis/Google.Cloud.Dialogflow.Cx.V3/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10564 Release Google.Cloud.Logging.V2 version 4.1.0
  apis/Google.Cloud.Logging.V2/Google.Cloud.Logging.V2/Google.Cloud.Logging.V2.csproj
  apis/Google.Cloud.Logging.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10561 Release Google.Cloud.DiscoveryEngine.V1Beta version 1.0.0-beta06
  apis/Google.Cloud.DiscoveryEngine.V1Beta/Google.Cloud.DiscoveryEngine.V1Beta/Google.Cloud.DiscoveryEngine.V1Beta.csproj
  apis/Google.Cloud.DiscoveryEngine.V1Beta/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10567 Release Google.Cloud.VmwareEngine.V1 version 1.0.0-beta03
  apis/Google.Cloud.VmwareEngine.V1/Google.Cloud.VmwareEngine.V1/Google.Cloud.VmwareEngine.V1.csproj
  apis/Google.Cloud.VmwareEngine.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10563 Release Google.Cloud.DocumentAI.V1Beta3 version 2.0.0-beta11
  apis/Google.Cloud.DocumentAI.V1Beta3/Google.Cloud.DocumentAI.V1Beta3/Google.Cloud.DocumentAI.V1Beta3.csproj
  apis/Google.Cloud.DocumentAI.V1Beta3/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10566 Release Google.Cloud.SecurityCenter.V1 version 3.11.0
  apis/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1.csproj
  apis/Google.Cloud.SecurityCenter.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10565 Release Google.Cloud.Orchestration.Airflow.Service.V1 version 2.4.0
  apis/Google.Cloud.Orchestration.Airflow.Service.V1/Google.Cloud.Orchestration.Airflow.Service.V1/Google.Cloud.Orchestration.Airflow.Service.V1.csproj
  apis/Google.Cloud.Orchestration.Airflow.Service.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10562 Release Google.Cloud.DocumentAI.V1 version 3.7.0
  apis/Google.Cloud.DocumentAI.V1/Google.Cloud.DocumentAI.V1/Google.Cloud.DocumentAI.V1.csproj
  apis/Google.Cloud.DocumentAI.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10559 Release Google.Cloud.Deploy.V1 version 2.5.0
  apis/Google.Cloud.Deploy.V1/Google.Cloud.Deploy.V1/Google.Cloud.Deploy.V1.csproj
  apis/Google.Cloud.Deploy.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10579 Release Spanner libraries version 4.6.0
  apis/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1.csproj
  apis/Google.Cloud.Spanner.Admin.Instance.V1/Google.Cloud.Spanner.Admin.Instance.V1/Google.Cloud.Spanner.Admin.Instance.V1.csproj
  apis/Google.Cloud.Spanner.Common.V1/Google.Cloud.Spanner.Common.V1/Google.Cloud.Spanner.Common.V1.csproj
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.csproj
  apis/Google.Cloud.Spanner.Data/docs/history.md
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1.csproj
  apis/apis.json
Labels: autorelease: pending

#10589 Release Google.Cloud.BigQuery.Storage.V1 version 3.8.0
  apis/Google.Cloud.BigQuery.Storage.V1/Google.Cloud.BigQuery.Storage.V1/Google.Cloud.BigQuery.Storage.V1.csproj
  apis/Google.Cloud.BigQuery.Storage.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10591 Release Google.Cloud.Dialogflow.V2 version 4.11.0
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2.csproj
  apis/Google.Cloud.Dialogflow.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10593 Release Google.Cloud.EssentialContacts.V1 version 2.2.0
  apis/Google.Cloud.EssentialContacts.V1/Google.Cloud.EssentialContacts.V1/Google.Cloud.EssentialContacts.V1.csproj
  apis/Google.Cloud.EssentialContacts.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending

#10596 Release Google.Cloud.SecurityCenter.V1 version 3.12.0
  apis/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1.csproj
  apis/Google.Cloud.SecurityCenter.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10594 Release Google.Cloud.GkeBackup.V1 version 2.2.0
  apis/Google.Cloud.GkeBackup.V1/Google.Cloud.GkeBackup.V1/Google.Cloud.GkeBackup.V1.csproj
  apis/Google.Cloud.GkeBackup.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10597 Release Google.Cloud.StorageTransfer.V1 version 2.3.0
  apis/Google.Cloud.StorageTransfer.V1/Google.Cloud.StorageTransfer.V1/Google.Cloud.StorageTransfer.V1.csproj
  apis/Google.Cloud.StorageTransfer.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10595 Release Google.Cloud.NetworkManagement.V1 version 2.4.0
  apis/Google.Cloud.NetworkManagement.V1/Google.Cloud.NetworkManagement.V1/Google.Cloud.NetworkManagement.V1.csproj
  apis/Google.Cloud.NetworkManagement.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10592 Release Google.Cloud.Dialogflow.V2Beta1 version 1.0.0-beta08
  apis/Google.Cloud.Dialogflow.V2Beta1/Google.Cloud.Dialogflow.V2Beta1/Google.Cloud.Dialogflow.V2Beta1.csproj
  apis/Google.Cloud.Dialogflow.V2Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10590 Release Google.Cloud.Deploy.V1 version 2.6.0
  apis/Google.Cloud.Deploy.V1/Google.Cloud.Deploy.V1/Google.Cloud.Deploy.V1.csproj
  apis/Google.Cloud.Deploy.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10600 Release Google.Cloud.Support.V2 version 1.0.0-beta01
  README.md
  apis/Google.Cloud.Support.V2/.repo-metadata.json
  apis/Google.Cloud.Support.V2/Google.Cloud.Support.V2/Google.Cloud.Support.V2.csproj
  apis/Google.Cloud.Support.V2/docs/history.md
  apis/Google.Cloud.Support.V2/smoketests.json
  apis/apis.json
Labels: autorelease: pending, automerge: exact
