Repository googleapis/google-cloud-dotnet, pull requests merged in 2023-02, with the labels that each got.

#9852 Release Google.Cloud.Storage.V1 version 4.3.0
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.IntegrationTests/Google.Cloud.Storage.V1.IntegrationTests.csproj
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.Snippets/Google.Cloud.Storage.V1.Snippets.csproj
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.Tests/Google.Cloud.Storage.V1.Tests.csproj
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.csproj
  apis/Google.Cloud.Storage.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9851 Release Google.Cloud.NetworkConnectivity.V1 version 2.3.0
  apis/Google.Cloud.NetworkConnectivity.V1/Google.Cloud.NetworkConnectivity.V1/Google.Cloud.NetworkConnectivity.V1.csproj
  apis/Google.Cloud.NetworkConnectivity.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9850 Release Google.Cloud.GkeMultiCloud.V1 version 2.2.0
  apis/Google.Cloud.GkeMultiCloud.V1/Google.Cloud.GkeMultiCloud.V1/Google.Cloud.GkeMultiCloud.V1.csproj
  apis/Google.Cloud.GkeMultiCloud.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9848 Release Google.Cloud.Dataplex.V1 version 2.3.0
  apis/Google.Cloud.Dataplex.V1/Google.Cloud.Dataplex.V1/Google.Cloud.Dataplex.V1.csproj
  apis/Google.Cloud.Dataplex.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9849 Release Google.Cloud.DocumentAI.V1Beta3 version 2.0.0-beta08
  apis/Google.Cloud.DocumentAI.V1Beta3/Google.Cloud.DocumentAI.V1Beta3/Google.Cloud.DocumentAI.V1Beta3.csproj
  apis/Google.Cloud.DocumentAI.V1Beta3/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9844 Release Google.Cloud.Batch.V1 version 1.3.0
  apis/Google.Cloud.Batch.V1/Google.Cloud.Batch.V1/Google.Cloud.Batch.V1.csproj
  apis/Google.Cloud.Batch.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9845 Release Google.Cloud.Batch.V1Alpha version 1.0.0-alpha08
  apis/Google.Cloud.Batch.V1Alpha/Google.Cloud.Batch.V1Alpha/Google.Cloud.Batch.V1Alpha.csproj
  apis/Google.Cloud.Batch.V1Alpha/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9846 Release Google.Cloud.Compute.V1 version 2.7.0
  apis/Google.Cloud.Compute.V1/Google.Cloud.Compute.V1/Google.Cloud.Compute.V1.csproj
  apis/Google.Cloud.Compute.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9847 Release Google.Cloud.ContactCenterInsights.V1 version 2.4.0
  apis/Google.Cloud.ContactCenterInsights.V1/Google.Cloud.ContactCenterInsights.V1/Google.Cloud.ContactCenterInsights.V1.csproj
  apis/Google.Cloud.ContactCenterInsights.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9843 Release Google.Cloud.ArtifactRegistry.V1 version 2.2.0
  apis/Google.Cloud.ArtifactRegistry.V1/Google.Cloud.ArtifactRegistry.V1/Google.Cloud.ArtifactRegistry.V1.csproj
  apis/Google.Cloud.ArtifactRegistry.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9841 Release Google.Analytics.Admin.V1Alpha version 2.0.0-alpha05
  apis/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha.csproj
  apis/Google.Analytics.Admin.V1Alpha/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9842 Release Google.Cloud.AIPlatform.V1 version 2.10.0
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1.csproj
  apis/Google.Cloud.AIPlatform.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9853 Release diagnostics libraries version 5.1.0
  apis/Google.Cloud.Diagnostics.AspNetCore3/Google.Cloud.Diagnostics.AspNetCore3/Google.Cloud.Diagnostics.AspNetCore3.csproj
  apis/Google.Cloud.Diagnostics.AspNetCore3/docs/history.md
  apis/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common.IntegrationTests/Google.Cloud.Diagnostics.Common.IntegrationTests.csproj
  apis/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common.Snippets/Google.Cloud.Diagnostics.Common.Snippets.csproj
  apis/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common.Tests/Google.Cloud.Diagnostics.Common.Tests.csproj
  apis/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common.csproj
  apis/Google.Cloud.Diagnostics.Common/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9854 Release Spanner libraries version 4.3.0
  apis/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1.csproj
  apis/Google.Cloud.Spanner.Admin.Instance.V1/Google.Cloud.Spanner.Admin.Instance.V1/Google.Cloud.Spanner.Admin.Instance.V1.csproj
  apis/Google.Cloud.Spanner.Common.V1/Google.Cloud.Spanner.Common.V1/Google.Cloud.Spanner.Common.V1.csproj
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.IntegrationTests/Google.Cloud.Spanner.Data.IntegrationTests.csproj
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.Snippets/Google.Cloud.Spanner.Data.Snippets.csproj
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.Tests/Google.Cloud.Spanner.Data.Tests.csproj
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.csproj
  apis/Google.Cloud.Spanner.Data/docs/history.md
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1.csproj
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9858 Release OS Login libraries
  apis/Google.Cloud.OsLogin.Common/Google.Cloud.OsLogin.Common/Google.Cloud.OsLogin.Common.csproj
  apis/Google.Cloud.OsLogin.V1/Google.Cloud.OsLogin.V1/Google.Cloud.OsLogin.V1.csproj
  apis/Google.Cloud.OsLogin.V1/docs/history.md
  apis/Google.Cloud.OsLogin.V1Beta/Google.Cloud.OsLogin.V1Beta/Google.Cloud.OsLogin.V1Beta.csproj
  apis/Google.Cloud.OsLogin.V1Beta/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9859 Release Cloud Workflows V1 libraries version 2.1.0
  apis/Google.Cloud.Workflows.Common.V1/Google.Cloud.Workflows.Common.V1/Google.Cloud.Workflows.Common.V1.csproj
  apis/Google.Cloud.Workflows.Executions.V1/Google.Cloud.Workflows.Executions.V1/Google.Cloud.Workflows.Executions.V1.csproj
  apis/Google.Cloud.Workflows.Executions.V1/docs/history.md
  apis/Google.Cloud.Workflows.V1/Google.Cloud.Workflows.V1/Google.Cloud.Workflows.V1.csproj
  apis/Google.Cloud.Workflows.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9860 Release Cloud Workflows V1Beta libraries version 2.0.0-beta02
  apis/Google.Cloud.Workflows.Common.V1Beta/Google.Cloud.Workflows.Common.V1Beta/Google.Cloud.Workflows.Common.V1Beta.csproj
  apis/Google.Cloud.Workflows.Executions.V1Beta/Google.Cloud.Workflows.Executions.V1Beta/Google.Cloud.Workflows.Executions.V1Beta.csproj
  apis/Google.Cloud.Workflows.Executions.V1Beta/docs/history.md
  apis/Google.Cloud.Workflows.V1Beta/Google.Cloud.Workflows.V1Beta/Google.Cloud.Workflows.V1Beta.csproj
  apis/Google.Cloud.Workflows.V1Beta/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9857 Release Firestore libraries version 3.1.0
  apis/Google.Cloud.Firestore.V1/Google.Cloud.Firestore.V1/Google.Cloud.Firestore.V1.csproj
  apis/Google.Cloud.Firestore.V1/docs/history.md
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore.IntegrationTests/Google.Cloud.Firestore.IntegrationTests.csproj
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore.Snippets/Google.Cloud.Firestore.Snippets.csproj
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore.Tests/Google.Cloud.Firestore.Tests.csproj
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore/Google.Cloud.Firestore.csproj
  apis/Google.Cloud.Firestore/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9855 Release Container Analysis libraries version 3.1.0
  apis/Google.Cloud.DevTools.ContainerAnalysis.V1/Google.Cloud.DevTools.ContainerAnalysis.V1/Google.Cloud.DevTools.ContainerAnalysis.V1.csproj
  apis/Google.Cloud.DevTools.ContainerAnalysis.V1/docs/history.md
  apis/Grafeas.V1/Grafeas.V1/Grafeas.V1.csproj
  apis/Grafeas.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9881 fix(PubSub): Ack/ModAck failures in non-exactly once delivery flow should not be retried.
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1.Tests/SubscriberClientTest.cs
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/SubscriberClient.cs
Labels: api: pubsub

#9918 Release Google.Cloud.Storage.V1 version 4.4.0
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.csproj
  apis/Google.Cloud.Storage.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9920 Release Google.Analytics.Admin.V1Alpha version 2.0.0-alpha06
  apis/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha.csproj
  apis/Google.Analytics.Admin.V1Alpha/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9933 Release Google.Cloud.Dialogflow.Cx.V3 version 2.5.0
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3.csproj
  apis/Google.Cloud.Dialogflow.Cx.V3/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9938 Release Google.Cloud.Translate.V3 version 3.2.0
  apis/Google.Cloud.Translate.V3/Google.Cloud.Translate.V3/Google.Cloud.Translate.V3.csproj
  apis/Google.Cloud.Translate.V3/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9935 Release Google.Cloud.Dialogflow.V2Beta1 version 1.0.0-beta05
  apis/Google.Cloud.Dialogflow.V2Beta1/Google.Cloud.Dialogflow.V2Beta1/Google.Cloud.Dialogflow.V2Beta1.csproj
  apis/Google.Cloud.Dialogflow.V2Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9937 Release Google.Cloud.Security.PrivateCA.V1 version 3.2.0
  apis/Google.Cloud.Security.PrivateCA.V1/Google.Cloud.Security.PrivateCA.V1/Google.Cloud.Security.PrivateCA.V1.csproj
  apis/Google.Cloud.Security.PrivateCA.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9932 Release Google.Cloud.BigQuery.Storage.V1 version 3.6.0
  apis/Google.Cloud.BigQuery.Storage.V1/Google.Cloud.BigQuery.Storage.V1/Google.Cloud.BigQuery.Storage.V1.csproj
  apis/Google.Cloud.BigQuery.Storage.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9936 Release Google.Cloud.DocumentAI.V1 version 3.6.0
  apis/Google.Cloud.DocumentAI.V1/Google.Cloud.DocumentAI.V1/Google.Cloud.DocumentAI.V1.csproj
  apis/Google.Cloud.DocumentAI.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9934 Release Google.Cloud.Dialogflow.V2 version 4.8.0
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2.csproj
  apis/Google.Cloud.Dialogflow.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9955 Release Google.Cloud.Kms.Inventory.V1 version 1.0.0-beta01
  .github/renovate.json
  README.md
  apis/Google.Cloud.Kms.Inventory.V1/.OwlBot.yaml
  apis/Google.Cloud.Kms.Inventory.V1/.repo-metadata.json
  apis/Google.Cloud.Kms.Inventory.V1/Google.Cloud.Kms.Inventory.V1.GeneratedSnippets/Google.Cloud.Kms.Inventory.V1.GeneratedSnippets.csproj
  apis/Google.Cloud.Kms.Inventory.V1/Google.Cloud.Kms.Inventory.V1.GeneratedSnippets/KeyDashboardServiceClient.ListCryptoKeysAsyncSnippet.g.cs
  apis/Google.Cloud.Kms.Inventory.V1/Google.Cloud.Kms.Inventory.V1.GeneratedSnippets/KeyDashboardServiceClient.ListCryptoKeysRequestObjectAsyncSnippet.g.cs
  apis/Google.Cloud.Kms.Inventory.V1/Google.Cloud.Kms.Inventory.V1.GeneratedSnippets/KeyDashboardServiceClient.ListCryptoKeysRequestObjectSnippet.g.cs
  apis/Google.Cloud.Kms.Inventory.V1/Google.Cloud.Kms.Inventory.V1.GeneratedSnippets/KeyDashboardServiceClient.ListCryptoKeysResourceNamesAsyncSnippet.g.cs
  apis/Google.Cloud.Kms.Inventory.V1/Google.Cloud.Kms.Inventory.V1.GeneratedSnippets/KeyDashboardServiceClient.ListCryptoKeysResourceNamesSnippet.g.cs
  apis/Google.Cloud.Kms.Inventory.V1/Google.Cloud.Kms.Inventory.V1.GeneratedSnippets/KeyDashboardServiceClient.ListCryptoKeysSnippet.g.cs
  apis/Google.Cloud.Kms.Inventory.V1/Google.Cloud.Kms.Inventory.V1.GeneratedSnippets/KeyTrackingServiceClient.GetProtectedResourcesSummaryAsyncSnippet.g.cs
  apis/Google.Cloud.Kms.Inventory.V1/Google.Cloud.Kms.Inventory.V1.GeneratedSnippets/KeyTrackingServiceClient.GetProtectedResourcesSummaryRequestObjectAsyncSnippet.g.cs
  apis/Google.Cloud.Kms.Inventory.V1/Google.Cloud.Kms.Inventory.V1.GeneratedSnippets/KeyTrackingServiceClient.GetProtectedResourcesSummaryRequestObjectSnippet.g.cs
  apis/Google.Cloud.Kms.Inventory.V1/Google.Cloud.Kms.Inventory.V1.GeneratedSnippets/KeyTrackingServiceClient.GetProtectedResourcesSummaryResourceNamesAsyncSnippet.g.cs
  apis/Google.Cloud.Kms.Inventory.V1/Google.Cloud.Kms.Inventory.V1.GeneratedSnippets/KeyTrackingServiceClient.GetProtectedResourcesSummaryResourceNamesSnippet.g.cs
  apis/Google.Cloud.Kms.Inventory.V1/Google.Cloud.Kms.Inventory.V1.GeneratedSnippets/KeyTrackingServiceClient.GetProtectedResourcesSummarySnippet.g.cs
  apis/Google.Cloud.Kms.Inventory.V1/Google.Cloud.Kms.Inventory.V1.GeneratedSnippets/KeyTrackingServiceClient.SearchProtectedResourcesAsyncSnippet.g.cs
  apis/Google.Cloud.Kms.Inventory.V1/Google.Cloud.Kms.Inventory.V1.GeneratedSnippets/KeyTrackingServiceClient.SearchProtectedResourcesRequestObjectAsyncSnippet.g.cs
  apis/Google.Cloud.Kms.Inventory.V1/Google.Cloud.Kms.Inventory.V1.GeneratedSnippets/KeyTrackingServiceClient.SearchProtectedResourcesRequestObjectSnippet.g.cs
  apis/Google.Cloud.Kms.Inventory.V1/Google.Cloud.Kms.Inventory.V1.GeneratedSnippets/KeyTrackingServiceClient.SearchProtectedResourcesResourceNamesAsyncSnippet.g.cs
  apis/Google.Cloud.Kms.Inventory.V1/Google.Cloud.Kms.Inventory.V1.GeneratedSnippets/KeyTrackingServiceClient.SearchProtectedResourcesResourceNamesSnippet.g.cs
  apis/Google.Cloud.Kms.Inventory.V1/Google.Cloud.Kms.Inventory.V1.GeneratedSnippets/KeyTrackingServiceClient.SearchProtectedResourcesSnippet.g.cs
  apis/Google.Cloud.Kms.Inventory.V1/Google.Cloud.Kms.Inventory.V1.GeneratedSnippets/snippet_metadata_google.cloud.kms.inventory.v1.json
  apis/Google.Cloud.Kms.Inventory.V1/Google.Cloud.Kms.Inventory.V1.Snippets/Google.Cloud.Kms.Inventory.V1.Snippets.csproj
  apis/Google.Cloud.Kms.Inventory.V1/Google.Cloud.Kms.Inventory.V1.Snippets/KeyDashboardServiceClientSnippets.g.cs
  apis/Google.Cloud.Kms.Inventory.V1/Google.Cloud.Kms.Inventory.V1.Snippets/KeyTrackingServiceClientSnippets.g.cs
  apis/Google.Cloud.Kms.Inventory.V1/Google.Cloud.Kms.Inventory.V1.Snippets/coverage.xml
  apis/Google.Cloud.Kms.Inventory.V1/Google.Cloud.Kms.Inventory.V1.sln
  apis/Google.Cloud.Kms.Inventory.V1/Google.Cloud.Kms.Inventory.V1/Google.Cloud.Kms.Inventory.V1.csproj
  apis/Google.Cloud.Kms.Inventory.V1/Google.Cloud.Kms.Inventory.V1/KeyDashboardService.g.cs
  apis/Google.Cloud.Kms.Inventory.V1/Google.Cloud.Kms.Inventory.V1/KeyDashboardServiceClient.g.cs
  apis/Google.Cloud.Kms.Inventory.V1/Google.Cloud.Kms.Inventory.V1/KeyDashboardServiceGrpc.g.cs
  apis/Google.Cloud.Kms.Inventory.V1/Google.Cloud.Kms.Inventory.V1/KeyDashboardServiceResourceNames.g.cs
  apis/Google.Cloud.Kms.Inventory.V1/Google.Cloud.Kms.Inventory.V1/KeyTrackingService.g.cs
  apis/Google.Cloud.Kms.Inventory.V1/Google.Cloud.Kms.Inventory.V1/KeyTrackingServiceClient.g.cs
  apis/Google.Cloud.Kms.Inventory.V1/Google.Cloud.Kms.Inventory.V1/KeyTrackingServiceGrpc.g.cs
  apis/Google.Cloud.Kms.Inventory.V1/Google.Cloud.Kms.Inventory.V1/KeyTrackingServiceResourceNames.g.cs
  apis/Google.Cloud.Kms.Inventory.V1/Google.Cloud.Kms.Inventory.V1/PackageApiMetadata.g.cs
  apis/Google.Cloud.Kms.Inventory.V1/Google.Cloud.Kms.Inventory.V1/ServiceCollectionExtensions.g.cs
  apis/Google.Cloud.Kms.Inventory.V1/docs/history.md
  apis/Google.Cloud.Kms.Inventory.V1/docs/index.md
  apis/Google.Cloud.Kms.Inventory.V1/gapic_metadata.json
  apis/Google.Cloud.Kms.Inventory.V1/smoketests.json
  apis/apis.json
Labels: autorelease: pending, snippet-bot:no-prefix-req, automerge: exact
