Repository googleapis/google-cloud-dotnet, pull requests merged in 2023-08, with the labels that each got.

#10770 Release Google.Cloud.AdvisoryNotifications.V1 version 1.1.0
  apis/Google.Cloud.AdvisoryNotifications.V1/Google.Cloud.AdvisoryNotifications.V1/Google.Cloud.AdvisoryNotifications.V1.csproj
  apis/Google.Cloud.AdvisoryNotifications.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10773 Release Google.Cloud.Batch.V1Alpha version 1.0.0-alpha14
  apis/Google.Cloud.Batch.V1Alpha/Google.Cloud.Batch.V1Alpha/Google.Cloud.Batch.V1Alpha.csproj
  apis/Google.Cloud.Batch.V1Alpha/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10769 Release Google.Analytics.Admin.V1Alpha version 2.0.0-alpha11
  apis/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha.csproj
  apis/Google.Analytics.Admin.V1Alpha/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10774 Release Google.Cloud.BigQuery.DataTransfer.V1 version 4.4.0
  apis/Google.Cloud.BigQuery.DataTransfer.V1/Google.Cloud.BigQuery.DataTransfer.V1/Google.Cloud.BigQuery.DataTransfer.V1.csproj
  apis/Google.Cloud.BigQuery.DataTransfer.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10778 Release Google.Cloud.Compute.V1 version 2.11.0
  apis/Google.Cloud.Compute.V1/Google.Cloud.Compute.V1/Google.Cloud.Compute.V1.csproj
  apis/Google.Cloud.Compute.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10777 Release Google.Cloud.Commerce.Consumer.Procurement.V1 version 1.0.0-beta02
  apis/Google.Cloud.Commerce.Consumer.Procurement.V1/Google.Cloud.Commerce.Consumer.Procurement.V1/Google.Cloud.Commerce.Consumer.Procurement.V1.csproj
  apis/Google.Cloud.Commerce.Consumer.Procurement.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10776 Release Google.Cloud.CloudBuild.V1 version 2.6.0
  apis/Google.Cloud.CloudBuild.V1/Google.Cloud.CloudBuild.V1/Google.Cloud.CloudBuild.V1.csproj
  apis/Google.Cloud.CloudBuild.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10775 Release Google.Cloud.Bigtable.V2 version 3.7.0
  apis/Google.Cloud.Bigtable.V2/Google.Cloud.Bigtable.V2/Google.Cloud.Bigtable.V2.csproj
  apis/Google.Cloud.Bigtable.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10779 Release Google.Cloud.ConfidentialComputing.V1 version 1.0.0-beta02
  apis/Google.Cloud.ConfidentialComputing.V1/Google.Cloud.ConfidentialComputing.V1/Google.Cloud.ConfidentialComputing.V1.csproj
  apis/Google.Cloud.ConfidentialComputing.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10783 Release Google.Cloud.Datastream.V1 version 2.4.0
  apis/Google.Cloud.Datastream.V1/Google.Cloud.Datastream.V1/Google.Cloud.Datastream.V1.csproj
  apis/Google.Cloud.Datastream.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10786 Release Google.Cloud.DocumentAI.V1 version 3.8.0
  apis/Google.Cloud.DocumentAI.V1/Google.Cloud.DocumentAI.V1/Google.Cloud.DocumentAI.V1.csproj
  apis/Google.Cloud.DocumentAI.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10781 Release Google.Cloud.DataCatalog.V1 version 2.6.0
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1.csproj
  apis/Google.Cloud.DataCatalog.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10787 Release Google.Cloud.DocumentAI.V1Beta3 version 2.0.0-beta12
  apis/Google.Cloud.DocumentAI.V1Beta3/Google.Cloud.DocumentAI.V1Beta3/Google.Cloud.DocumentAI.V1Beta3.csproj
  apis/Google.Cloud.DocumentAI.V1Beta3/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10785 Release Google.Cloud.DiscoveryEngine.V1Beta version 1.0.0-beta07
  apis/Google.Cloud.DiscoveryEngine.V1Beta/Google.Cloud.DiscoveryEngine.V1Beta/Google.Cloud.DiscoveryEngine.V1Beta.csproj
  apis/Google.Cloud.DiscoveryEngine.V1Beta/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10784 Release Google.Cloud.Deploy.V1 version 2.8.0
  apis/Google.Cloud.Deploy.V1/Google.Cloud.Deploy.V1/Google.Cloud.Deploy.V1.csproj
  apis/Google.Cloud.Deploy.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10791 Release Google.Cloud.ServiceDirectory.V1 version 2.2.0
  apis/Google.Cloud.ServiceDirectory.V1/Google.Cloud.ServiceDirectory.V1/Google.Cloud.ServiceDirectory.V1.csproj
  apis/Google.Cloud.ServiceDirectory.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10794 Release Google.Cloud.Tasks.V2Beta3 version 3.0.0-beta03
  apis/Google.Cloud.Tasks.V2Beta3/Google.Cloud.Tasks.V2Beta3/Google.Cloud.Tasks.V2Beta3.csproj
  apis/Google.Cloud.Tasks.V2Beta3/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10780 Release Google.Cloud.Container.V1 version 3.16.0
  apis/Google.Cloud.Container.V1/Google.Cloud.Container.V1/Google.Cloud.Container.V1.csproj
  apis/Google.Cloud.Container.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10789 Release Google.Cloud.Kms.V1 version 3.7.0
  apis/Google.Cloud.Kms.V1/Google.Cloud.Kms.V1/Google.Cloud.Kms.V1.csproj
  apis/Google.Cloud.Kms.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10796 Release Google.Cloud.Tasks.V2 version 3.2.0
  apis/Google.Cloud.Tasks.V2/Google.Cloud.Tasks.V2/Google.Cloud.Tasks.V2.csproj
  apis/Google.Cloud.Tasks.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10795 Release Google.Cloud.Video.LiveStream.V1 version 1.3.0
  apis/Google.Cloud.Video.LiveStream.V1/Google.Cloud.Video.LiveStream.V1/Google.Cloud.Video.LiveStream.V1.csproj
  apis/Google.Cloud.Video.LiveStream.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10790 Release Google.Cloud.PolicyTroubleshooter.V1 version 2.2.0
  apis/Google.Cloud.PolicyTroubleshooter.V1/Google.Cloud.PolicyTroubleshooter.V1/Google.Cloud.PolicyTroubleshooter.V1.csproj
  apis/Google.Cloud.PolicyTroubleshooter.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10788 Release Google.Cloud.Kms.Inventory.V1 version 1.1.0
  apis/Google.Cloud.Kms.Inventory.V1/Google.Cloud.Kms.Inventory.V1/Google.Cloud.Kms.Inventory.V1.csproj
  apis/Google.Cloud.Kms.Inventory.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10792 Release Google.Cloud.ServiceDirectory.V1Beta1 version 2.0.0-beta03
  apis/Google.Cloud.ServiceDirectory.V1Beta1/Google.Cloud.ServiceDirectory.V1Beta1/Google.Cloud.ServiceDirectory.V1Beta1.csproj
  apis/Google.Cloud.ServiceDirectory.V1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10807 Release Google.Cloud.ConfidentialComputing.V1 version 1.0.0-beta03
  apis/Google.Cloud.ConfidentialComputing.V1/Google.Cloud.ConfidentialComputing.V1/Google.Cloud.ConfidentialComputing.V1.csproj
  apis/Google.Cloud.ConfidentialComputing.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10818 Release Google.Cloud.Gaming.V1Beta version 2.0.0-beta03
  apis/Google.Cloud.Gaming.V1Beta/Google.Cloud.Gaming.V1Beta/Google.Cloud.Gaming.V1Beta.csproj
  apis/Google.Cloud.Gaming.V1Beta/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10817 Release Google.Cloud.Gaming.V1 version 2.2.0
  apis/Google.Cloud.Gaming.V1/Google.Cloud.Gaming.V1/Google.Cloud.Gaming.V1.csproj
  apis/Google.Cloud.Gaming.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10836 [DO NOT MERGE] chore: test release
  .kokoro/autorelease.sh
Labels: autorelease: tagged

#10837 chore: test release 2
  .kokoro/autorelease.sh
Labels: autorelease: tagged

#10838 chore : release 3
  .kokoro/autorelease.sh
Labels: autorelease: tagged

#10843 chore : release 3
  .kokoro/autorelease.sh
Labels: autorelease: tagged

#10883 Release Cloud Workflows V1 libraries version 2.2.0
  apis/Google.Cloud.Workflows.Common.V1/Google.Cloud.Workflows.Common.V1/Google.Cloud.Workflows.Common.V1.csproj
  apis/Google.Cloud.Workflows.Executions.V1/Google.Cloud.Workflows.Executions.V1/Google.Cloud.Workflows.Executions.V1.csproj
  apis/Google.Cloud.Workflows.Executions.V1/docs/history.md
  apis/Google.Cloud.Workflows.V1/Google.Cloud.Workflows.V1/Google.Cloud.Workflows.V1.csproj
  apis/Google.Cloud.Workflows.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10879 Release Google.Cloud.Dialogflow.V2Beta1 version 1.0.0-beta09
  apis/Google.Cloud.Dialogflow.V2Beta1/Google.Cloud.Dialogflow.V2Beta1/Google.Cloud.Dialogflow.V2Beta1.csproj
  apis/Google.Cloud.Dialogflow.V2Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10881 Release Google.Cloud.Translate.V3 version 3.3.0
  apis/Google.Cloud.Translate.V3/Google.Cloud.Translate.V3/Google.Cloud.Translate.V3.csproj
  apis/Google.Cloud.Translate.V3/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10880 Release Google.Cloud.NetworkManagement.V1 version 2.5.0
  apis/Google.Cloud.NetworkManagement.V1/Google.Cloud.NetworkManagement.V1/Google.Cloud.NetworkManagement.V1.csproj
  apis/Google.Cloud.NetworkManagement.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10878 Release Google.Cloud.Dialogflow.V2 version 4.12.0
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2.csproj
  apis/Google.Cloud.Dialogflow.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10875 Release Google.Cloud.ConfidentialComputing.V1 version 1.0.0-beta04
  apis/Google.Cloud.ConfidentialComputing.V1/Google.Cloud.ConfidentialComputing.V1/Google.Cloud.ConfidentialComputing.V1.csproj
  apis/Google.Cloud.ConfidentialComputing.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10877 Release Google.Cloud.Dialogflow.Cx.V3 version 2.10.0
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3.csproj
  apis/Google.Cloud.Dialogflow.Cx.V3/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10876 Release Google.Cloud.Container.V1 version 3.17.0
  apis/Google.Cloud.Container.V1/Google.Cloud.Container.V1/Google.Cloud.Container.V1.csproj
  apis/Google.Cloud.Container.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10871 Release Google.Cloud.BigQuery.DataPolicies.V1 version 1.1.0
  apis/Google.Cloud.BigQuery.DataPolicies.V1/Google.Cloud.BigQuery.DataPolicies.V1/Google.Cloud.BigQuery.DataPolicies.V1.csproj
  apis/Google.Cloud.BigQuery.DataPolicies.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10874 Release Google.Cloud.BinaryAuthorization.V1Beta1 version 2.0.0-beta04
  apis/Google.Cloud.BinaryAuthorization.V1Beta1/Google.Cloud.BinaryAuthorization.V1Beta1/Google.Cloud.BinaryAuthorization.V1Beta1.csproj
  apis/Google.Cloud.BinaryAuthorization.V1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10873 Release Google.Cloud.Bigtable.Admin.V2 version 3.6.0
  apis/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2.csproj
  apis/Google.Cloud.Bigtable.Admin.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10872 Release Google.Cloud.BigQuery.Storage.V1 version 3.10.0
  apis/Google.Cloud.BigQuery.Storage.V1/Google.Cloud.BigQuery.Storage.V1/Google.Cloud.BigQuery.Storage.V1.csproj
  apis/Google.Cloud.BigQuery.Storage.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10868 Release Google.Cloud.BareMetalSolution.V2 version 1.2.0
  apis/Google.Cloud.BareMetalSolution.V2/Google.Cloud.BareMetalSolution.V2/Google.Cloud.BareMetalSolution.V2.csproj
  apis/Google.Cloud.BareMetalSolution.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10870 Release Google.Cloud.Batch.V1Alpha version 1.0.0-alpha15
  apis/Google.Cloud.Batch.V1Alpha/Google.Cloud.Batch.V1Alpha/Google.Cloud.Batch.V1Alpha.csproj
  apis/Google.Cloud.Batch.V1Alpha/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10869 Release Google.Cloud.Batch.V1 version 2.4.0
  apis/Google.Cloud.Batch.V1/Google.Cloud.Batch.V1/Google.Cloud.Batch.V1.csproj
  apis/Google.Cloud.Batch.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10866 Release Google.Analytics.Admin.V1Alpha version 2.0.0-alpha12
  apis/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha.csproj
  apis/Google.Analytics.Admin.V1Alpha/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10864 Release Google.Cloud.PolicyTroubleshooter.Iam.V3 version 1.0.0-beta01
  .github/renovate.json
  README.md
  apis/Google.Cloud.PolicyTroubleshooter.Iam.V3/.OwlBot.yaml
  apis/Google.Cloud.PolicyTroubleshooter.Iam.V3/.repo-metadata.json
  apis/Google.Cloud.PolicyTroubleshooter.Iam.V3/Google.Cloud.PolicyTroubleshooter.Iam.V3.GeneratedSnippets/Google.Cloud.PolicyTroubleshooter.Iam.V3.GeneratedSnippets.csproj
  apis/Google.Cloud.PolicyTroubleshooter.Iam.V3/Google.Cloud.PolicyTroubleshooter.Iam.V3.GeneratedSnippets/PolicyTroubleshooterClient.TroubleshootIamPolicyRequestObjectAsyncSnippet.g.cs
  apis/Google.Cloud.PolicyTroubleshooter.Iam.V3/Google.Cloud.PolicyTroubleshooter.Iam.V3.GeneratedSnippets/PolicyTroubleshooterClient.TroubleshootIamPolicyRequestObjectSnippet.g.cs
  apis/Google.Cloud.PolicyTroubleshooter.Iam.V3/Google.Cloud.PolicyTroubleshooter.Iam.V3.GeneratedSnippets/snippet_metadata_google.cloud.policytroubleshooter.iam.v3.json
  apis/Google.Cloud.PolicyTroubleshooter.Iam.V3/Google.Cloud.PolicyTroubleshooter.Iam.V3.Snippets/Google.Cloud.PolicyTroubleshooter.Iam.V3.Snippets.csproj
  apis/Google.Cloud.PolicyTroubleshooter.Iam.V3/Google.Cloud.PolicyTroubleshooter.Iam.V3.Snippets/PolicyTroubleshooterClientSnippets.g.cs
  apis/Google.Cloud.PolicyTroubleshooter.Iam.V3/Google.Cloud.PolicyTroubleshooter.Iam.V3.Snippets/coverage.xml
  apis/Google.Cloud.PolicyTroubleshooter.Iam.V3/Google.Cloud.PolicyTroubleshooter.Iam.V3.sln
  apis/Google.Cloud.PolicyTroubleshooter.Iam.V3/Google.Cloud.PolicyTroubleshooter.Iam.V3/Google.Cloud.PolicyTroubleshooter.Iam.V3.csproj
  apis/Google.Cloud.PolicyTroubleshooter.Iam.V3/Google.Cloud.PolicyTroubleshooter.Iam.V3/PackageApiMetadata.g.cs
  apis/Google.Cloud.PolicyTroubleshooter.Iam.V3/Google.Cloud.PolicyTroubleshooter.Iam.V3/PolicyTroubleshooterClient.g.cs
  apis/Google.Cloud.PolicyTroubleshooter.Iam.V3/Google.Cloud.PolicyTroubleshooter.Iam.V3/ServiceCollectionExtensions.g.cs
  apis/Google.Cloud.PolicyTroubleshooter.Iam.V3/Google.Cloud.PolicyTroubleshooter.Iam.V3/Troubleshooter.g.cs
  apis/Google.Cloud.PolicyTroubleshooter.Iam.V3/Google.Cloud.PolicyTroubleshooter.Iam.V3/TroubleshooterGrpc.g.cs
  apis/Google.Cloud.PolicyTroubleshooter.Iam.V3/docs/history.md
  apis/Google.Cloud.PolicyTroubleshooter.Iam.V3/docs/index.md
  apis/Google.Cloud.PolicyTroubleshooter.Iam.V3/gapic_metadata.json
  apis/Google.Cloud.PolicyTroubleshooter.Iam.V3/smoketests.json
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10908 chore: Update Bigtable generator diffs
  apis/Google.Cloud.Bigtable.V2/Google.Cloud.Bigtable.V2.GenerateClient/Google.Cloud.Bigtable.V2.GenerateClient.csproj
Labels: automerge: exact

#10913 Release Google.Cloud.Video.Stitcher.V1 version 3.0.0-beta02
  apis/Google.Cloud.Video.Stitcher.V1/Google.Cloud.Video.Stitcher.V1/Google.Cloud.Video.Stitcher.V1.csproj
  apis/Google.Cloud.Video.Stitcher.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10914 Release Google.Cloud.Datastore.V1 version 4.6.0
  apis/Google.Cloud.Datastore.V1/Google.Cloud.Datastore.V1/Google.Cloud.Datastore.V1.csproj
  apis/Google.Cloud.Datastore.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10916 Release Google.Cloud.Batch.V1Alpha version 1.0.0-alpha16
  apis/Google.Cloud.Batch.V1Alpha/Google.Cloud.Batch.V1Alpha/Google.Cloud.Batch.V1Alpha.csproj
  apis/Google.Cloud.Batch.V1Alpha/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10928 Release Google.Cloud.Billing.Budgets.V1 version 2.3.0
  apis/Google.Cloud.Billing.Budgets.V1/Google.Cloud.Billing.Budgets.V1/Google.Cloud.Billing.Budgets.V1.csproj
  apis/Google.Cloud.Billing.Budgets.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10929 Release Google.Cloud.Billing.Budgets.V1Beta1 version 2.0.0-beta03
  apis/Google.Cloud.Billing.Budgets.V1Beta1/Google.Cloud.Billing.Budgets.V1Beta1/Google.Cloud.Billing.Budgets.V1Beta1.csproj
  apis/Google.Cloud.Billing.Budgets.V1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact
