Repository googleapis/google-cloud-dotnet, pull requests merged in 2023-03, with the labels that each got.

#9921 fix(BigTable): Fixes the issue with same qualifier across families.
  apis/Google.Cloud.Bigtable.V2/Google.Cloud.Bigtable.V2/RowAsyncEnumerator.cs
Labels: api: bigtable

#9968 Release Google.Cloud.Bigtable.V2 version 3.4.0
  apis/Google.Cloud.Bigtable.V2/Google.Cloud.Bigtable.V2.GeneratedSnippets/Google.Cloud.Bigtable.V2.GeneratedSnippets.csproj
  apis/Google.Cloud.Bigtable.V2/Google.Cloud.Bigtable.V2.IntegrationTests/Google.Cloud.Bigtable.V2.IntegrationTests.csproj
  apis/Google.Cloud.Bigtable.V2/Google.Cloud.Bigtable.V2.Snippets/Google.Cloud.Bigtable.V2.Snippets.csproj
  apis/Google.Cloud.Bigtable.V2/Google.Cloud.Bigtable.V2.Tests/Google.Cloud.Bigtable.V2.Tests.csproj
  apis/Google.Cloud.Bigtable.V2/Google.Cloud.Bigtable.V2/Google.Cloud.Bigtable.V2.csproj
  apis/Google.Cloud.Bigtable.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9970 Release Google.Cloud.AlloyDb.V1Alpha version 1.0.0-alpha01
  README.md
  apis/Google.Cloud.AlloyDb.V1Alpha/.repo-metadata.json
  apis/Google.Cloud.AlloyDb.V1Alpha/Google.Cloud.AlloyDb.V1Alpha/Google.Cloud.AlloyDb.V1Alpha.csproj
  apis/Google.Cloud.AlloyDb.V1Alpha/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9976 Release Google.Cloud.AlloyDb.V1Beta version 1.0.0-beta01
  README.md
  apis/Google.Cloud.AlloyDb.V1Beta/.repo-metadata.json
  apis/Google.Cloud.AlloyDb.V1Beta/Google.Cloud.AlloyDb.V1Beta/Google.Cloud.AlloyDb.V1Beta.csproj
  apis/Google.Cloud.AlloyDb.V1Beta/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9977 Release Google.Cloud.AlloyDb.V1 version 1.0.0-beta01
  README.md
  apis/Google.Cloud.AlloyDb.V1/.repo-metadata.json
  apis/Google.Cloud.AlloyDb.V1/Google.Cloud.AlloyDb.V1/Google.Cloud.AlloyDb.V1.csproj
  apis/Google.Cloud.AlloyDb.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9998 Release Google.Cloud.Speech.V1P1Beta1 version 3.0.0-beta05
  apis/Google.Cloud.Speech.V1P1Beta1/Google.Cloud.Speech.V1P1Beta1/Google.Cloud.Speech.V1P1Beta1.csproj
  apis/Google.Cloud.Speech.V1P1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10001 Release GSuite Add-Ons libraries version 2.1.0
  apis/Google.Apps.Script.Type/Google.Apps.Script.Type/Google.Apps.Script.Type.csproj
  apis/Google.Apps.Script.Type/docs/history.md
  apis/Google.Cloud.GSuiteAddOns.V1/Google.Cloud.GSuiteAddOns.V1/Google.Cloud.GSuiteAddOns.V1.csproj
  apis/Google.Cloud.GSuiteAddOns.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9995 Release Google.Cloud.Dialogflow.V2Beta1 version 1.0.0-beta06
  apis/Google.Cloud.Dialogflow.V2Beta1/Google.Cloud.Dialogflow.V2Beta1/Google.Cloud.Dialogflow.V2Beta1.csproj
  apis/Google.Cloud.Dialogflow.V2Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9992 Release Google.Cloud.ContactCenterInsights.V1 version 2.5.0
  apis/Google.Cloud.ContactCenterInsights.V1/Google.Cloud.ContactCenterInsights.V1/Google.Cloud.ContactCenterInsights.V1.csproj
  apis/Google.Cloud.ContactCenterInsights.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9994 Release Google.Cloud.Dialogflow.V2 version 4.9.0
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2.csproj
  apis/Google.Cloud.Dialogflow.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9999 Release Google.Cloud.Video.Transcoder.V1 version 2.4.0
  apis/Google.Cloud.Video.Transcoder.V1/Google.Cloud.Video.Transcoder.V1/Google.Cloud.Video.Transcoder.V1.csproj
  apis/Google.Cloud.Video.Transcoder.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9989 Release Google.Cloud.AIPlatform.V1 version 2.11.0
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1.csproj
  apis/Google.Cloud.AIPlatform.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9993 Release Google.Cloud.Dialogflow.Cx.V3 version 2.6.0
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3.csproj
  apis/Google.Cloud.Dialogflow.Cx.V3/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9990 Release Google.Cloud.BigQuery.Connection.V1 version 2.4.0
  apis/Google.Cloud.BigQuery.Connection.V1/Google.Cloud.BigQuery.Connection.V1/Google.Cloud.BigQuery.Connection.V1.csproj
  apis/Google.Cloud.BigQuery.Connection.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9996 Release Google.Cloud.Scheduler.V1 version 3.2.0
  apis/Google.Cloud.Scheduler.V1/Google.Cloud.Scheduler.V1/Google.Cloud.Scheduler.V1.csproj
  apis/Google.Cloud.Scheduler.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10008 Release Google.Cloud.PubSub.V1 version 3.4.0
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1.GeneratedSnippets/Google.Cloud.PubSub.V1.GeneratedSnippets.csproj
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1.IntegrationTests/Google.Cloud.PubSub.V1.IntegrationTests.csproj
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1.Snippets/Google.Cloud.PubSub.V1.Snippets.csproj
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1.Tests/Google.Cloud.PubSub.V1.Tests.csproj
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1.csproj
  apis/Google.Cloud.PubSub.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10009 chore: Removed the [Fact] attribute from the sample.
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1.Snippets/SubscriberClientSnippets.cs
Labels: samples

#10010 Release Google.Cloud.PubSub.V1 version 3.4.0
  apis/Google.Cloud.PubSub.V1/docs/history.md
Labels: autorelease: pending, automerge: exact

#10014 Release Google.Cloud.Batch.V1Alpha version 1.0.0-alpha09
  apis/Google.Cloud.Batch.V1Alpha/Google.Cloud.Batch.V1Alpha/Google.Cloud.Batch.V1Alpha.csproj
  apis/Google.Cloud.Batch.V1Alpha/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10015 Release Google.Cloud.Batch.V1 version 2.0.0
  apis/Google.Cloud.Batch.V1/Google.Cloud.Batch.V1/Google.Cloud.Batch.V1.csproj
  apis/Google.Cloud.Batch.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10016 Release Spanner libraries version 4.4.0
  apis/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1.csproj
  apis/Google.Cloud.Spanner.Admin.Instance.V1/Google.Cloud.Spanner.Admin.Instance.V1/Google.Cloud.Spanner.Admin.Instance.V1.csproj
  apis/Google.Cloud.Spanner.Common.V1/Google.Cloud.Spanner.Common.V1/Google.Cloud.Spanner.Common.V1.csproj
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.csproj
  apis/Google.Cloud.Spanner.Data/docs/history.md
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1.csproj
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10022 Release Google.Cloud.Datastore.V1 version 4.5.0
  apis/Google.Cloud.Datastore.V1/Google.Cloud.Datastore.V1.GeneratedSnippets/Google.Cloud.Datastore.V1.GeneratedSnippets.csproj
  apis/Google.Cloud.Datastore.V1/Google.Cloud.Datastore.V1.IntegrationTests/Google.Cloud.Datastore.V1.IntegrationTests.csproj
  apis/Google.Cloud.Datastore.V1/Google.Cloud.Datastore.V1.Snippets/Google.Cloud.Datastore.V1.Snippets.csproj
  apis/Google.Cloud.Datastore.V1/Google.Cloud.Datastore.V1.Tests/Google.Cloud.Datastore.V1.Tests.csproj
  apis/Google.Cloud.Datastore.V1/Google.Cloud.Datastore.V1/Google.Cloud.Datastore.V1.csproj
  apis/Google.Cloud.Datastore.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending

#10027 chore: CI changes
  .github/workflows/retryConformTests.yml
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.RetryConformanceTests/RetryConformanceTestFixture.cs
Labels: lex-review

#10068 Release Google.Maps.Routing.V2 version 1.0.0-beta08
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore/Google.Cloud.Firestore.csproj
  apis/Google.Maps.Routing.V2/Google.Maps.Routing.V2/Google.Maps.Routing.V2.csproj
  apis/Google.Maps.Routing.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10085 Release Firestore libraries version 3.2.0
  apis/Google.Cloud.Firestore.V1/Google.Cloud.Firestore.V1/Google.Cloud.Firestore.V1.csproj
  apis/Google.Cloud.Firestore.V1/docs/history.md
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore/Google.Cloud.Firestore.csproj
  apis/Google.Cloud.Firestore/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10098 Release Google.Cloud.BigQuery.DataPolicies.V1 version 1.0.0
  apis/Google.Cloud.BigQuery.DataPolicies.V1/.repo-metadata.json
  apis/Google.Cloud.BigQuery.DataPolicies.V1/Google.Cloud.BigQuery.DataPolicies.V1/Google.Cloud.BigQuery.DataPolicies.V1.csproj
  apis/Google.Cloud.BigQuery.DataPolicies.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10099 Release Google.Cloud.DataCatalog.Lineage.V1 version 1.0.0
  apis/Google.Cloud.DataCatalog.Lineage.V1/.repo-metadata.json
  apis/Google.Cloud.DataCatalog.Lineage.V1/Google.Cloud.DataCatalog.Lineage.V1/Google.Cloud.DataCatalog.Lineage.V1.csproj
  apis/Google.Cloud.DataCatalog.Lineage.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10101 Release Google.Cloud.Translation.V2 version 3.2.0
  apis/Google.Cloud.Translation.V2/Google.Cloud.Translation.V2/Google.Cloud.Translation.V2.csproj
  apis/Google.Cloud.Translation.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10106 Release Google.Cloud.BigQuery.Migration.V2 version 1.1.0
  apis/Google.Cloud.BigQuery.Migration.V2/Google.Cloud.BigQuery.Migration.V2/Google.Cloud.BigQuery.Migration.V2.csproj
  apis/Google.Cloud.BigQuery.Migration.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10110 Release Google.Cloud.Deploy.V1 version 2.3.0
  apis/Google.Cloud.Deploy.V1/Google.Cloud.Deploy.V1/Google.Cloud.Deploy.V1.csproj
  apis/Google.Cloud.Deploy.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10108 Release Google.Cloud.CloudBuild.V2 version 1.0.0-beta02
  apis/Google.Cloud.CloudBuild.V2/Google.Cloud.CloudBuild.V2/Google.Cloud.CloudBuild.V2.csproj
  apis/Google.Cloud.CloudBuild.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10112 Release Google.Cloud.DocumentAI.V1Beta3 version 2.0.0-beta10
  apis/Google.Cloud.DocumentAI.V1Beta3/Google.Cloud.DocumentAI.V1Beta3/Google.Cloud.DocumentAI.V1Beta3.csproj
  apis/Google.Cloud.DocumentAI.V1Beta3/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10100 Release Google.Cloud.Run.V2 version 2.0.0
  apis/Google.Cloud.Run.V2/Google.Cloud.Run.V2/Google.Cloud.Run.V2.csproj
  apis/Google.Cloud.Run.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10113 Release Google.Cloud.Speech.V2 version 1.0.0-beta04
  apis/Google.Cloud.Speech.V2/Google.Cloud.Speech.V2/Google.Cloud.Speech.V2.csproj
  apis/Google.Cloud.Speech.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10111 Release Google.Cloud.DiscoveryEngine.V1Beta version 1.0.0-beta03
  apis/Google.Cloud.DiscoveryEngine.V1Beta/Google.Cloud.DiscoveryEngine.V1Beta/Google.Cloud.DiscoveryEngine.V1Beta.csproj
  apis/Google.Cloud.DiscoveryEngine.V1Beta/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10115 Release Google.Maps.Routing.V2 version 1.0.0-beta09
  apis/Google.Maps.Routing.V2/Google.Maps.Routing.V2/Google.Maps.Routing.V2.csproj
  apis/Google.Maps.Routing.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10114 Release Google.Cloud.Video.LiveStream.V1 version 1.2.0
  apis/Google.Cloud.Video.LiveStream.V1/Google.Cloud.Video.LiveStream.V1/Google.Cloud.Video.LiveStream.V1.csproj
  apis/Google.Cloud.Video.LiveStream.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact
