Repository googleapis/google-cloud-dotnet, pull requests merged in 2023-01, with the labels that each got.

#9510 chore: Fix GitHub Actions status badge
  README.md
Labels: automerge: exact

#9527 feat: Exposed RpcException property to SpannerException
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.Tests/SpannerExceptionTests.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/SpannerException.cs
Labels: lex-review

#9532 Release Google.Cloud.Notebooks.V1 version 2.2.0
  apis/Google.Cloud.Notebooks.V1/Google.Cloud.Notebooks.V1/Google.Cloud.Notebooks.V1.csproj
  apis/Google.Cloud.Notebooks.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9534 Release Google.Cloud.Batch.V1 version 1.2.0
  apis/Google.Cloud.Batch.V1/Google.Cloud.Batch.V1/Google.Cloud.Batch.V1.csproj
  apis/Google.Cloud.Batch.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9536 Release Google.Cloud.Gaming.V1 version 2.1.0
  apis/Google.Cloud.Gaming.V1/Google.Cloud.Gaming.V1/Google.Cloud.Gaming.V1.csproj
  apis/Google.Cloud.Gaming.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9535 Release Google.Cloud.Domains.V1 version 2.1.0
  apis/Google.Cloud.Domains.V1/Google.Cloud.Domains.V1/Google.Cloud.Domains.V1.csproj
  apis/Google.Cloud.Domains.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9533 Release Google.Cloud.AccessApproval.V1 version 2.2.0
  apis/Google.Cloud.AccessApproval.V1/Google.Cloud.AccessApproval.V1/Google.Cloud.AccessApproval.V1.csproj
  apis/Google.Cloud.AccessApproval.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9539 Release Google.Cloud.Tasks.V2 version 3.1.0
  apis/Google.Cloud.Tasks.V2/Google.Cloud.Tasks.V2/Google.Cloud.Tasks.V2.csproj
  apis/Google.Cloud.Tasks.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9538 Release Google.Cloud.SecretManager.V1 version 2.1.0
  apis/Google.Cloud.SecretManager.V1/Google.Cloud.SecretManager.V1/Google.Cloud.SecretManager.V1.csproj
  apis/Google.Cloud.SecretManager.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9540 Release Google.Cloud.TextToSpeech.V1 version 3.2.0
  apis/Google.Cloud.TextToSpeech.V1/Google.Cloud.TextToSpeech.V1/Google.Cloud.TextToSpeech.V1.csproj
  apis/Google.Cloud.TextToSpeech.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9541 Release Google.Cloud.Vision.V1 version 3.3.0
  apis/Google.Cloud.Vision.V1/Google.Cloud.Vision.V1/Google.Cloud.Vision.V1.csproj
  apis/Google.Cloud.Vision.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9543 chore(deps): update dependency dotnet-sdk to v6.0.405
  global.json
Labels: automerge: exact

#9598 Release Google.Cloud.VMMigration.V1 version 2.2.0
  apis/Google.Cloud.VMMigration.V1/Google.Cloud.VMMigration.V1/Google.Cloud.VMMigration.V1.csproj
  apis/Google.Cloud.VMMigration.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending

#9599 Release Google.Maps.AddressValidation.V1 version 1.0.0-beta03
  apis/Google.Maps.AddressValidation.V1/Google.Maps.AddressValidation.V1/Google.Maps.AddressValidation.V1.csproj
  apis/Google.Maps.AddressValidation.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending

#9597 Release Google.Cloud.Translation.V2 version 3.2.0-beta01
  apis/Google.Cloud.Translation.V2/Google.Cloud.Translation.V2/Google.Cloud.Translation.V2.csproj
  apis/Google.Cloud.Translation.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending

#9596 Release Google.Cloud.TextToSpeech.V1Beta1 version 2.0.0-beta03
  apis/Google.Cloud.TextToSpeech.V1Beta1/Google.Cloud.TextToSpeech.V1Beta1/Google.Cloud.TextToSpeech.V1Beta1.csproj
  apis/Google.Cloud.TextToSpeech.V1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9595 Release Google.Cloud.StorageTransfer.V1 version 2.2.0
  apis/Google.Cloud.StorageTransfer.V1/Google.Cloud.StorageTransfer.V1/Google.Cloud.StorageTransfer.V1.csproj
  apis/Google.Cloud.StorageTransfer.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9594 Release Google.Cloud.Speech.V1P1Beta1 version 3.0.0-beta03
  apis/Google.Cloud.Speech.V1P1Beta1/Google.Cloud.Speech.V1P1Beta1/Google.Cloud.Speech.V1P1Beta1.csproj
  apis/Google.Cloud.Speech.V1P1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending

#9593 Release Google.Cloud.Speech.V1 version 3.2.0
  apis/Google.Cloud.Speech.V1/Google.Cloud.Speech.V1/Google.Cloud.Speech.V1.csproj
  apis/Google.Cloud.Speech.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9592 Release Google.Cloud.Retail.V2 version 2.3.0
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2.csproj
  apis/Google.Cloud.Retail.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9590 Release Google.Cloud.Metastore.V1Beta version 2.0.0-beta03
  apis/Google.Cloud.Metastore.V1Beta/Google.Cloud.Metastore.V1Beta/Google.Cloud.Metastore.V1Beta.csproj
  apis/Google.Cloud.Metastore.V1Beta/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9589 Release Google.Cloud.Metastore.V1Alpha version 2.0.0-alpha03
  apis/Google.Cloud.Metastore.V1Alpha/Google.Cloud.Metastore.V1Alpha/Google.Cloud.Metastore.V1Alpha.csproj
  apis/Google.Cloud.Metastore.V1Alpha/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9587 Release Google.Cloud.Language.V1 version 3.2.0
  apis/Google.Cloud.Language.V1/Google.Cloud.Language.V1/Google.Cloud.Language.V1.csproj
  apis/Google.Cloud.Language.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9586 Release Google.Cloud.Iap.V1 version 2.1.0
  apis/Google.Cloud.Iap.V1/Google.Cloud.Iap.V1/Google.Cloud.Iap.V1.csproj
  apis/Google.Cloud.Iap.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending

#9585 Release Google.Cloud.Iam.V2 version 1.0.0-beta02
  apis/Google.Cloud.Iam.V2/Google.Cloud.Iam.V2/Google.Cloud.Iam.V2.csproj
  apis/Google.Cloud.Iam.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending

#9584 Release Google.Cloud.GkeMultiCloud.V1 version 2.1.0
  apis/Google.Cloud.GkeMultiCloud.V1/Google.Cloud.GkeMultiCloud.V1/Google.Cloud.GkeMultiCloud.V1.csproj
  apis/Google.Cloud.GkeMultiCloud.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending

#9583 Release Google.Cloud.Firestore.Admin.V1 version 3.1.0
  apis/Google.Cloud.Firestore.Admin.V1/Google.Cloud.Firestore.Admin.V1/Google.Cloud.Firestore.Admin.V1.csproj
  apis/Google.Cloud.Firestore.Admin.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9582 Release Google.Cloud.DocumentAI.V1Beta3 version 2.0.0-beta05
  apis/Google.Cloud.DocumentAI.V1Beta3/Google.Cloud.DocumentAI.V1Beta3/Google.Cloud.DocumentAI.V1Beta3.csproj
  apis/Google.Cloud.DocumentAI.V1Beta3/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9580 Release Google.Cloud.Dialogflow.V2 version 4.6.0
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2.csproj
  apis/Google.Cloud.Dialogflow.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9578 Release Google.Cloud.Datastore.V1 version 4.4.0
  apis/Google.Cloud.Datastore.V1/Google.Cloud.Datastore.V1.GeneratedSnippets/Google.Cloud.Datastore.V1.GeneratedSnippets.csproj
  apis/Google.Cloud.Datastore.V1/Google.Cloud.Datastore.V1.IntegrationTests/Google.Cloud.Datastore.V1.IntegrationTests.csproj
  apis/Google.Cloud.Datastore.V1/Google.Cloud.Datastore.V1.Snippets/Google.Cloud.Datastore.V1.Snippets.csproj
  apis/Google.Cloud.Datastore.V1/Google.Cloud.Datastore.V1.Tests/Google.Cloud.Datastore.V1.Tests.csproj
  apis/Google.Cloud.Datastore.V1/Google.Cloud.Datastore.V1/Google.Cloud.Datastore.V1.csproj
  apis/Google.Cloud.Datastore.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9579 Release Google.Cloud.Dialogflow.Cx.V3 version 2.3.0
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3.csproj
  apis/Google.Cloud.Dialogflow.Cx.V3/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9574 Release Google.Cloud.Container.V1 version 3.7.0
  apis/Google.Cloud.Container.V1/Google.Cloud.Container.V1/Google.Cloud.Container.V1.csproj
  apis/Google.Cloud.Container.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9575 Release Google.Cloud.DataCatalog.V1 version 2.2.0
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1.csproj
  apis/Google.Cloud.DataCatalog.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9568 Release Google.Cloud.ApiKeys.V2 version 1.1.0
  apis/Google.Cloud.ApiKeys.V2/Google.Cloud.ApiKeys.V2/Google.Cloud.ApiKeys.V2.csproj
  apis/Google.Cloud.ApiKeys.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9571 Release Google.Cloud.Asset.V1 version 3.4.0
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1.csproj
  apis/Google.Cloud.Asset.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9577 Release Google.Cloud.Datastore.Admin.V1 version 2.1.0
  apis/Google.Cloud.Datastore.Admin.V1/Google.Cloud.Datastore.Admin.V1/Google.Cloud.Datastore.Admin.V1.csproj
  apis/Google.Cloud.Datastore.Admin.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9570 Release Google.Cloud.ArtifactRegistry.V1Beta2 version 2.0.0-beta02
  apis/Google.Cloud.ArtifactRegistry.V1Beta2/Google.Cloud.ArtifactRegistry.V1Beta2/Google.Cloud.ArtifactRegistry.V1Beta2.csproj
  apis/Google.Cloud.ArtifactRegistry.V1Beta2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9573 Release Google.Cloud.BigQuery.DataTransfer.V1 version 4.2.0
  apis/Google.Cloud.BigQuery.DataTransfer.V1/Google.Cloud.BigQuery.DataTransfer.V1/Google.Cloud.BigQuery.DataTransfer.V1.csproj
  apis/Google.Cloud.BigQuery.DataTransfer.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9576 Release Google.Cloud.Dataproc.V1 version 5.3.0
  apis/Google.Cloud.Dataproc.V1/Google.Cloud.Dataproc.V1/Google.Cloud.Dataproc.V1.csproj
  apis/Google.Cloud.Dataproc.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9572 Release Google.Cloud.Batch.V1Alpha version 1.0.0-alpha06
  apis/Google.Cloud.Batch.V1Alpha/Google.Cloud.Batch.V1Alpha/Google.Cloud.Batch.V1Alpha.csproj
  apis/Google.Cloud.Batch.V1Alpha/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9567 Release Google.Cloud.AIPlatform.V1 version 2.8.0
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1.csproj
  apis/Google.Cloud.AIPlatform.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9569 Release Google.Cloud.ArtifactRegistry.V1 version 2.1.0
  apis/Google.Cloud.ArtifactRegistry.V1/Google.Cloud.ArtifactRegistry.V1/Google.Cloud.ArtifactRegistry.V1.csproj
  apis/Google.Cloud.ArtifactRegistry.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9619 Release Google.Cloud.WebRisk.V1Beta1 version 3.0.0-beta02
  apis/Google.Cloud.WebRisk.V1Beta1/Google.Cloud.WebRisk.V1Beta1/Google.Cloud.WebRisk.V1Beta1.csproj
  apis/Google.Cloud.WebRisk.V1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9616 Release Google.Cloud.SecretManager.V1Beta1 version 3.0.0-beta02
  apis/Google.Cloud.SecretManager.V1Beta1/Google.Cloud.SecretManager.V1Beta1/Google.Cloud.SecretManager.V1Beta1.csproj
  apis/Google.Cloud.SecretManager.V1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9614 Release Google.Cloud.LifeSciences.V2Beta version 2.0.0-beta03
  apis/Google.Cloud.LifeSciences.V2Beta/Google.Cloud.LifeSciences.V2Beta/Google.Cloud.LifeSciences.V2Beta.csproj
  apis/Google.Cloud.LifeSciences.V2Beta/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9613 Release Google.Cloud.Gaming.V1Beta version 2.0.0-beta02
  apis/Google.Cloud.Gaming.V1Beta/Google.Cloud.Gaming.V1Beta/Google.Cloud.Gaming.V1Beta.csproj
  apis/Google.Cloud.Gaming.V1Beta/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9617 Release Google.Cloud.Translate.V3 version 3.1.0
  apis/Google.Cloud.Translate.V3/Google.Cloud.Translate.V3/Google.Cloud.Translate.V3.csproj
  apis/Google.Cloud.Translate.V3/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9612 Release Google.Cloud.Filestore.V1 version 2.1.0
  apis/Google.Cloud.Filestore.V1/Google.Cloud.Filestore.V1/Google.Cloud.Filestore.V1.csproj
  apis/Google.Cloud.Filestore.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9615 Release Google.Cloud.NetworkSecurity.V1Beta1 version 2.0.0-beta03
  apis/Google.Cloud.NetworkSecurity.V1Beta1/Google.Cloud.NetworkSecurity.V1Beta1/Google.Cloud.NetworkSecurity.V1Beta1.csproj
  apis/Google.Cloud.NetworkSecurity.V1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9608 Release Google.Cloud.ApigeeRegistry.V1 version 1.0.0-beta04
  apis/Google.Cloud.ApigeeRegistry.V1/Google.Cloud.ApigeeRegistry.V1/Google.Cloud.ApigeeRegistry.V1.csproj
  apis/Google.Cloud.ApigeeRegistry.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9611 Release Google.Cloud.Dlp.V2 version 4.5.0
  apis/Google.Cloud.Dlp.V2/Google.Cloud.Dlp.V2/Google.Cloud.Dlp.V2.csproj
  apis/Google.Cloud.Dlp.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9610 Release Google.Cloud.Dataflow.V1Beta3 version 2.0.0-beta03
  apis/Google.Cloud.Dataflow.V1Beta3/Google.Cloud.Dataflow.V1Beta3/Google.Cloud.Dataflow.V1Beta3.csproj
  apis/Google.Cloud.Dataflow.V1Beta3/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9618 Release Google.Cloud.WebRisk.V1 version 2.2.0
  apis/Google.Cloud.WebRisk.V1/Google.Cloud.WebRisk.V1/Google.Cloud.WebRisk.V1.csproj
  apis/Google.Cloud.WebRisk.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9609 Release Google.Cloud.AppEngine.V1 version 2.1.0
  apis/Google.Cloud.AppEngine.V1/Google.Cloud.AppEngine.V1/Google.Cloud.AppEngine.V1.csproj
  apis/Google.Cloud.AppEngine.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9629 Release Google.Cloud.Batch.V1Alpha version 1.0.0-alpha07
  apis/Google.Cloud.Batch.V1Alpha/Google.Cloud.Batch.V1Alpha/Google.Cloud.Batch.V1Alpha.csproj
  apis/Google.Cloud.Batch.V1Alpha/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9630 Release Google.Cloud.Billing.V1 version 3.2.0
  apis/Google.Cloud.Billing.V1/Google.Cloud.Billing.V1/Google.Cloud.Billing.V1.csproj
  apis/Google.Cloud.Billing.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9631 Release Google.Cloud.CertificateManager.V1 version 2.2.0
  apis/Google.Cloud.CertificateManager.V1/Google.Cloud.CertificateManager.V1/Google.Cloud.CertificateManager.V1.csproj
  apis/Google.Cloud.CertificateManager.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9628 Release Google.Cloud.AIPlatform.V1 version 2.9.0
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1.csproj
  apis/Google.Cloud.AIPlatform.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9633 Release Google.Cloud.Container.V1 version 3.8.0
  apis/Google.Cloud.Container.V1/Google.Cloud.Container.V1/Google.Cloud.Container.V1.csproj
  apis/Google.Cloud.Container.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9634 Release Google.Cloud.DataFusion.V1 version 2.1.0
  apis/Google.Cloud.DataFusion.V1/Google.Cloud.DataFusion.V1/Google.Cloud.DataFusion.V1.csproj
  apis/Google.Cloud.DataFusion.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9638 Release Google.Cloud.DocumentAI.V1 version 3.4.0
  apis/Google.Cloud.DocumentAI.V1/Google.Cloud.DocumentAI.V1/Google.Cloud.DocumentAI.V1.csproj
  apis/Google.Cloud.DocumentAI.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9632 Release Google.Cloud.ContactCenterInsights.V1 version 2.3.0
  apis/Google.Cloud.ContactCenterInsights.V1/Google.Cloud.ContactCenterInsights.V1/Google.Cloud.ContactCenterInsights.V1.csproj
  apis/Google.Cloud.ContactCenterInsights.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9640 Release Google.Cloud.EssentialContacts.V1 version 2.1.0
  apis/Google.Cloud.EssentialContacts.V1/Google.Cloud.EssentialContacts.V1/Google.Cloud.EssentialContacts.V1.csproj
  apis/Google.Cloud.EssentialContacts.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9645 Release Google.Cloud.PhishingProtection.V1Beta1 version 2.0.0-beta02
  apis/Google.Cloud.PhishingProtection.V1Beta1/Google.Cloud.PhishingProtection.V1Beta1/Google.Cloud.PhishingProtection.V1Beta1.csproj
  apis/Google.Cloud.PhishingProtection.V1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9648 Release Google.Cloud.Recommender.V1 version 3.2.0
  apis/Google.Cloud.Recommender.V1/Google.Cloud.Recommender.V1/Google.Cloud.Recommender.V1.csproj
  apis/Google.Cloud.Recommender.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9647 Release Google.Cloud.RecaptchaEnterprise.V1Beta1 version 2.0.0-beta02
  apis/Google.Cloud.RecaptchaEnterprise.V1Beta1/Google.Cloud.RecaptchaEnterprise.V1Beta1/Google.Cloud.RecaptchaEnterprise.V1Beta1.csproj
  apis/Google.Cloud.RecaptchaEnterprise.V1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9649 Release Google.Cloud.ResourceManager.V3 version 2.1.0
  apis/Google.Cloud.ResourceManager.V3/Google.Cloud.ResourceManager.V3/Google.Cloud.ResourceManager.V3.csproj
  apis/Google.Cloud.ResourceManager.V3/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9644 Release Google.Cloud.OrgPolicy.V2 version 2.1.0
  apis/Google.Cloud.OrgPolicy.V2/Google.Cloud.OrgPolicy.V2/Google.Cloud.OrgPolicy.V2.csproj
  apis/Google.Cloud.OrgPolicy.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9652 Release Google.Cloud.VpcAccess.V1 version 2.2.0
  apis/Google.Cloud.VpcAccess.V1/Google.Cloud.VpcAccess.V1/Google.Cloud.VpcAccess.V1.csproj
  apis/Google.Cloud.VpcAccess.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9653 Release Google.Identity.AccessContextManager.V1 version 2.2.0
  apis/Google.Identity.AccessContextManager.V1/Google.Identity.AccessContextManager.V1/Google.Identity.AccessContextManager.V1.csproj
  apis/Google.Identity.AccessContextManager.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9636 Release Google.Cloud.Datastream.V1Alpha1 version 2.0.0-alpha02
  apis/Google.Cloud.Datastream.V1Alpha1/Google.Cloud.Datastream.V1Alpha1/Google.Cloud.Datastream.V1Alpha1.csproj
  apis/Google.Cloud.Datastream.V1Alpha1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9650 Release Google.Cloud.ResourceSettings.V1 version 2.1.0
  apis/Google.Cloud.ResourceSettings.V1/Google.Cloud.ResourceSettings.V1/Google.Cloud.ResourceSettings.V1.csproj
  apis/Google.Cloud.ResourceSettings.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9646 Release Google.Cloud.PolicyTroubleshooter.V1 version 2.1.0
  apis/Google.Cloud.PolicyTroubleshooter.V1/Google.Cloud.PolicyTroubleshooter.V1/Google.Cloud.PolicyTroubleshooter.V1.csproj
  apis/Google.Cloud.PolicyTroubleshooter.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9642 Release Google.Cloud.Ids.V1 version 2.1.0
  apis/Google.Cloud.Ids.V1/Google.Cloud.Ids.V1/Google.Cloud.Ids.V1.csproj
  apis/Google.Cloud.Ids.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9651 Release Google.Cloud.Run.V2 version 2.0.0-beta04
  apis/Google.Cloud.Run.V2/Google.Cloud.Run.V2/Google.Cloud.Run.V2.csproj
  apis/Google.Cloud.Run.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9639 Release Google.Cloud.DocumentAI.V1Beta3 version 2.0.0-beta06
  apis/Google.Cloud.DocumentAI.V1Beta3/Google.Cloud.DocumentAI.V1Beta3/Google.Cloud.DocumentAI.V1Beta3.csproj
  apis/Google.Cloud.DocumentAI.V1Beta3/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9715 Release Google.Maps.Routing.V2 version 1.0.0-beta07
  apis/Google.Maps.Routing.V2/Google.Maps.Routing.V2/Google.Maps.Routing.V2.csproj
  apis/Google.Maps.Routing.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9713 Release Google.Cloud.VmwareEngine.V1 version 1.0.0-beta02
  apis/Google.Cloud.VmwareEngine.V1/Google.Cloud.VmwareEngine.V1/Google.Cloud.VmwareEngine.V1.csproj
  apis/Google.Cloud.VmwareEngine.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9711 Release Google.Cloud.VMMigration.V1 version 2.3.0
  apis/Google.Cloud.VMMigration.V1/Google.Cloud.VMMigration.V1/Google.Cloud.VMMigration.V1.csproj
  apis/Google.Cloud.VMMigration.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9712 Release Google.Cloud.VideoIntelligence.V1 version 3.1.0
  apis/Google.Cloud.VideoIntelligence.V1/Google.Cloud.VideoIntelligence.V1/Google.Cloud.VideoIntelligence.V1.csproj
  apis/Google.Cloud.VideoIntelligence.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9710 Release Google.Cloud.Tasks.V2Beta3 version 3.0.0-beta02
  apis/Google.Cloud.Tasks.V2Beta3/Google.Cloud.Tasks.V2Beta3/Google.Cloud.Tasks.V2Beta3.csproj
  apis/Google.Cloud.Tasks.V2Beta3/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9706 Release Google.Cloud.Speech.V1 version 3.3.0
  apis/Google.Cloud.Speech.V1/Google.Cloud.Speech.V1/Google.Cloud.Speech.V1.csproj
  apis/Google.Cloud.Speech.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9707 Release Google.Cloud.Speech.V1P1Beta1 version 3.0.0-beta04
  apis/Google.Cloud.Speech.V1P1Beta1/Google.Cloud.Speech.V1P1Beta1/Google.Cloud.Speech.V1P1Beta1.csproj
  apis/Google.Cloud.Speech.V1P1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9709 Release Google.Cloud.Talent.V4Beta1 version 3.0.0-beta02
  apis/Google.Cloud.Talent.V4Beta1/Google.Cloud.Talent.V4Beta1/Google.Cloud.Talent.V4Beta1.csproj
  apis/Google.Cloud.Talent.V4Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9702 Release Google.Cloud.Redis.V1Beta1 version 3.0.0-beta02
  apis/Google.Cloud.Redis.V1Beta1/Google.Cloud.Redis.V1Beta1/Google.Cloud.Redis.V1Beta1.csproj
  apis/Google.Cloud.Redis.V1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9705 Release Google.Cloud.Shell.V1 version 2.2.0
  apis/Google.Cloud.Shell.V1/Google.Cloud.Shell.V1/Google.Cloud.Shell.V1.csproj
  apis/Google.Cloud.Shell.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9703 Release Google.Cloud.ServiceDirectory.V1 version 2.1.0
  apis/Google.Cloud.ServiceDirectory.V1/Google.Cloud.ServiceDirectory.V1/Google.Cloud.ServiceDirectory.V1.csproj
  apis/Google.Cloud.ServiceDirectory.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9697 Release Google.Cloud.OrgPolicy.V2 version 2.2.0
  apis/Google.Cloud.OrgPolicy.V2/Google.Cloud.OrgPolicy.V2/Google.Cloud.OrgPolicy.V2.csproj
  apis/Google.Cloud.OrgPolicy.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9700 Release Google.Cloud.PubSub.V1 version 3.3.0
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1.GeneratedSnippets/Google.Cloud.PubSub.V1.GeneratedSnippets.csproj
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1.IntegrationTests/Google.Cloud.PubSub.V1.IntegrationTests.csproj
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1.Snippets/Google.Cloud.PubSub.V1.Snippets.csproj
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1.Tests/Google.Cloud.PubSub.V1.Tests.csproj
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1.csproj
  apis/Google.Cloud.PubSub.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9704 Release Google.Cloud.ServiceDirectory.V1Beta1 version 2.0.0-beta02
  apis/Google.Cloud.ServiceDirectory.V1Beta1/Google.Cloud.ServiceDirectory.V1Beta1/Google.Cloud.ServiceDirectory.V1Beta1.csproj
  apis/Google.Cloud.ServiceDirectory.V1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9714 Release Google.Cloud.WebSecurityScanner.V1 version 2.2.0
  apis/Google.Cloud.WebSecurityScanner.V1/Google.Cloud.WebSecurityScanner.V1/Google.Cloud.WebSecurityScanner.V1.csproj
  apis/Google.Cloud.WebSecurityScanner.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9701 Release Google.Cloud.Redis.V1 version 3.1.0
  apis/Google.Cloud.Redis.V1/Google.Cloud.Redis.V1/Google.Cloud.Redis.V1.csproj
  apis/Google.Cloud.Redis.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9708 Release Google.Cloud.Speech.V2 version 1.0.0-beta03
  apis/Google.Cloud.Speech.V2/Google.Cloud.Speech.V2/Google.Cloud.Speech.V2.csproj
  apis/Google.Cloud.Speech.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9696 Release Google.Cloud.Optimization.V1 version 2.1.0
  apis/Google.Cloud.Optimization.V1/Google.Cloud.Optimization.V1/Google.Cloud.Optimization.V1.csproj
  apis/Google.Cloud.Optimization.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9693 Release Google.Cloud.Memcache.V1Beta2 version 2.0.0-beta03
  apis/Google.Cloud.Memcache.V1Beta2/Google.Cloud.Memcache.V1Beta2/Google.Cloud.Memcache.V1Beta2.csproj
  apis/Google.Cloud.Memcache.V1Beta2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9691 Release Google.Cloud.Kms.V1 version 3.3.0
  apis/Google.Cloud.Kms.V1/Google.Cloud.Kms.V1/Google.Cloud.Kms.V1.csproj
  apis/Google.Cloud.Kms.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9689 Release Google.Cloud.GkeHub.V1Beta1 version 2.0.0-beta03
  apis/Google.Cloud.GkeHub.V1Beta1/Google.Cloud.GkeHub.V1Beta1/Google.Cloud.GkeHub.V1Beta1.csproj
  apis/Google.Cloud.GkeHub.V1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9698 Release Google.Cloud.OsConfig.V1 version 2.1.0
  apis/Google.Cloud.OsConfig.V1/Google.Cloud.OsConfig.V1/Google.Cloud.OsConfig.V1.csproj
  apis/Google.Cloud.OsConfig.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9690 Release Google.Cloud.Iot.V1 version 2.1.0
  apis/Google.Cloud.Iot.V1/Google.Cloud.Iot.V1/Google.Cloud.Iot.V1.csproj
  apis/Google.Cloud.Iot.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9682 Release Google.Cloud.Dialogflow.V2 version 4.7.0
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2.csproj
  apis/Google.Cloud.Dialogflow.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9685 Release Google.Cloud.Functions.V1 version 2.1.0
  apis/Google.Cloud.Functions.V1/Google.Cloud.Functions.V1/Google.Cloud.Functions.V1.csproj
  apis/Google.Cloud.Functions.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9694 Release Google.Cloud.Metastore.V1Alpha version 2.0.0-alpha04
  apis/Google.Cloud.Metastore.V1Alpha/Google.Cloud.Metastore.V1Alpha/Google.Cloud.Metastore.V1Alpha.csproj
  apis/Google.Cloud.Metastore.V1Alpha/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9684 Release Google.Cloud.Eventarc.V1 version 2.2.0
  apis/Google.Cloud.Eventarc.V1/Google.Cloud.Eventarc.V1/Google.Cloud.Eventarc.V1.csproj
  apis/Google.Cloud.Eventarc.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9695 Release Google.Cloud.Metastore.V1Beta version 2.0.0-beta04
  apis/Google.Cloud.Metastore.V1Beta/Google.Cloud.Metastore.V1Beta/Google.Cloud.Metastore.V1Beta.csproj
  apis/Google.Cloud.Metastore.V1Beta/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9675 Release Google.Cloud.AutoML.V1 version 3.1.0
  apis/Google.Cloud.AutoML.V1/Google.Cloud.AutoML.V1/Google.Cloud.AutoML.V1.csproj
  apis/Google.Cloud.AutoML.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9680 Release Google.Cloud.Dataproc.V1 version 5.4.0
  apis/Google.Cloud.Dataproc.V1/Google.Cloud.Dataproc.V1/Google.Cloud.Dataproc.V1.csproj
  apis/Google.Cloud.Dataproc.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9681 Release Google.Cloud.Deploy.V1 version 2.2.0
  apis/Google.Cloud.Deploy.V1/Google.Cloud.Deploy.V1/Google.Cloud.Deploy.V1.csproj
  apis/Google.Cloud.Deploy.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9688 Release Google.Cloud.GkeBackup.V1 version 2.1.0
  apis/Google.Cloud.GkeBackup.V1/Google.Cloud.GkeBackup.V1/Google.Cloud.GkeBackup.V1.csproj
  apis/Google.Cloud.GkeBackup.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9672 Release Google.Cloud.ApigeeConnect.V1 version 2.1.0
  apis/Google.Cloud.ApigeeConnect.V1/Google.Cloud.ApigeeConnect.V1/Google.Cloud.ApigeeConnect.V1.csproj
  apis/Google.Cloud.ApigeeConnect.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9674 Release Google.Cloud.AssuredWorkloads.V1Beta1 version 2.0.0-beta05
  apis/Google.Cloud.AssuredWorkloads.V1Beta1/Google.Cloud.AssuredWorkloads.V1Beta1/Google.Cloud.AssuredWorkloads.V1Beta1.csproj
  apis/Google.Cloud.AssuredWorkloads.V1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9686 Release Google.Cloud.Functions.V2 version 1.1.0
  apis/Google.Cloud.Functions.V2/Google.Cloud.Functions.V2/Google.Cloud.Functions.V2.csproj
  apis/Google.Cloud.Functions.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9687 Release Google.Cloud.Functions.V2Beta version 1.0.0-beta02
  apis/Google.Cloud.Functions.V2Beta/Google.Cloud.Functions.V2Beta/Google.Cloud.Functions.V2Beta.csproj
  apis/Google.Cloud.Functions.V2Beta/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9673 Release Google.Cloud.AssuredWorkloads.V1 version 2.3.0
  apis/Google.Cloud.AssuredWorkloads.V1/Google.Cloud.AssuredWorkloads.V1/Google.Cloud.AssuredWorkloads.V1.csproj
  apis/Google.Cloud.AssuredWorkloads.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9678 Release Google.Cloud.BinaryAuthorization.V1Beta1 version 2.0.0-beta03
  apis/Google.Cloud.BinaryAuthorization.V1Beta1/Google.Cloud.BinaryAuthorization.V1Beta1/Google.Cloud.BinaryAuthorization.V1Beta1.csproj
  apis/Google.Cloud.BinaryAuthorization.V1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9683 Release Google.Cloud.Domains.V1Beta1 version 2.0.0-beta02
  apis/Google.Cloud.Domains.V1Beta1/Google.Cloud.Domains.V1Beta1/Google.Cloud.Domains.V1Beta1.csproj
  apis/Google.Cloud.Domains.V1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9676 Release Google.Cloud.BareMetalSolution.V2 version 1.1.0
  apis/Google.Cloud.BareMetalSolution.V2/Google.Cloud.BareMetalSolution.V2/Google.Cloud.BareMetalSolution.V2.csproj
  apis/Google.Cloud.BareMetalSolution.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9677 Release Google.Cloud.BinaryAuthorization.V1 version 2.1.0
  apis/Google.Cloud.BinaryAuthorization.V1/Google.Cloud.BinaryAuthorization.V1/Google.Cloud.BinaryAuthorization.V1.csproj
  apis/Google.Cloud.BinaryAuthorization.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9679 Release Google.Cloud.Channel.V1 version 2.4.0
  apis/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1.csproj
  apis/Google.Cloud.Channel.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9669 Release Google.Analytics.Admin.V1Beta version 1.0.0-beta02
  apis/Google.Analytics.Admin.V1Beta/Google.Analytics.Admin.V1Beta/Google.Analytics.Admin.V1Beta.csproj
  apis/Google.Analytics.Admin.V1Beta/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9671 Release Google.Cloud.ApiGateway.V1 version 2.1.0
  apis/Google.Cloud.ApiGateway.V1/Google.Cloud.ApiGateway.V1/Google.Cloud.ApiGateway.V1.csproj
  apis/Google.Cloud.ApiGateway.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9670 Release Google.Analytics.Data.V1Beta version 2.0.0-beta03
  apis/Google.Analytics.Data.V1Beta/Google.Analytics.Data.V1Beta/Google.Analytics.Data.V1Beta.csproj
  apis/Google.Analytics.Data.V1Beta/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9749 Release Google.Cloud.Video.Transcoder.V1 version 2.3.0
  apis/Google.Cloud.Video.Transcoder.V1/Google.Cloud.Video.Transcoder.V1/Google.Cloud.Video.Transcoder.V1.csproj
  apis/Google.Cloud.Video.Transcoder.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9746 Release Google.Cloud.Trace.V1 version 3.1.0
  apis/Google.Cloud.Trace.V1/Google.Cloud.Trace.V1/Google.Cloud.Trace.V1.csproj
  apis/Google.Cloud.Trace.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9748 Release Google.Cloud.Video.LiveStream.V1 version 1.1.0
  apis/Google.Cloud.Video.LiveStream.V1/Google.Cloud.Video.LiveStream.V1/Google.Cloud.Video.LiveStream.V1.csproj
  apis/Google.Cloud.Video.LiveStream.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9742 Release Google.Cloud.SecurityCenter.V1P1Beta1 version 3.0.0-beta02
  apis/Google.Cloud.SecurityCenter.V1P1Beta1/Google.Cloud.SecurityCenter.V1P1Beta1/Google.Cloud.SecurityCenter.V1P1Beta1.csproj
  apis/Google.Cloud.SecurityCenter.V1P1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9747 Release Google.Cloud.Trace.V2 version 3.2.0
  apis/Google.Cloud.Trace.V2/Google.Cloud.Trace.V2/Google.Cloud.Trace.V2.csproj
  apis/Google.Cloud.Trace.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9736 Release Google.Cloud.RecommendationEngine.V1Beta1 version 2.0.0-beta03
  apis/Google.Cloud.RecommendationEngine.V1Beta1/Google.Cloud.RecommendationEngine.V1Beta1/Google.Cloud.RecommendationEngine.V1Beta1.csproj
  apis/Google.Cloud.RecommendationEngine.V1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9740 Release Google.Cloud.Security.PublicCA.V1Beta1 version 1.0.0-beta02
  apis/Google.Cloud.Security.PublicCA.V1Beta1/Google.Cloud.Security.PublicCA.V1Beta1/Google.Cloud.Security.PublicCA.V1Beta1.csproj
  apis/Google.Cloud.Security.PublicCA.V1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9735 Release Google.Cloud.Profiler.V2 version 2.1.0
  apis/Google.Cloud.Profiler.V2/Google.Cloud.Profiler.V2/Google.Cloud.Profiler.V2.csproj
  apis/Google.Cloud.Profiler.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9745 Release Google.Cloud.ServiceUsage.V1 version 2.1.0
  apis/Google.Cloud.ServiceUsage.V1/Google.Cloud.ServiceUsage.V1/Google.Cloud.ServiceUsage.V1.csproj
  apis/Google.Cloud.ServiceUsage.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9733 Release Google.Cloud.Orchestration.Airflow.Service.V1 version 2.2.0
  apis/Google.Cloud.Orchestration.Airflow.Service.V1/Google.Cloud.Orchestration.Airflow.Service.V1/Google.Cloud.Orchestration.Airflow.Service.V1.csproj
  apis/Google.Cloud.Orchestration.Airflow.Service.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9738 Release Google.Cloud.Security.PrivateCA.V1 version 3.1.0
  apis/Google.Cloud.Security.PrivateCA.V1/Google.Cloud.Security.PrivateCA.V1/Google.Cloud.Security.PrivateCA.V1.csproj
  apis/Google.Cloud.Security.PrivateCA.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9743 Release Google.Cloud.ServiceControl.V1 version 2.1.0
  apis/Google.Cloud.ServiceControl.V1/Google.Cloud.ServiceControl.V1/Google.Cloud.ServiceControl.V1.csproj
  apis/Google.Cloud.ServiceControl.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9734 Release Google.Cloud.PrivateCatalog.V1Beta1 version 2.0.0-beta02
  apis/Google.Cloud.PrivateCatalog.V1Beta1/Google.Cloud.PrivateCatalog.V1Beta1/Google.Cloud.PrivateCatalog.V1Beta1.csproj
  apis/Google.Cloud.PrivateCatalog.V1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9739 Release Google.Cloud.Security.PrivateCA.V1Beta1 version 2.0.0-beta02
  apis/Google.Cloud.Security.PrivateCA.V1Beta1/Google.Cloud.Security.PrivateCA.V1Beta1/Google.Cloud.Security.PrivateCA.V1Beta1.csproj
  apis/Google.Cloud.Security.PrivateCA.V1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9726 Release Google.Cloud.DataCatalog.Lineage.V1 version 1.0.0-beta02
  apis/Google.Cloud.DataCatalog.Lineage.V1/Google.Cloud.DataCatalog.Lineage.V1/Google.Cloud.DataCatalog.Lineage.V1.csproj
  apis/Google.Cloud.DataCatalog.Lineage.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9729 Release Google.Cloud.ErrorReporting.V1Beta1 version 3.0.0-beta02
  apis/Google.Cloud.ErrorReporting.V1Beta1/Google.Cloud.ErrorReporting.V1Beta1/Google.Cloud.ErrorReporting.V1Beta1.csproj
  apis/Google.Cloud.ErrorReporting.V1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9731 Release Google.Cloud.Iap.V1 version 2.2.0
  apis/Google.Cloud.Iap.V1/Google.Cloud.Iap.V1/Google.Cloud.Iap.V1.csproj
  apis/Google.Cloud.Iap.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9720 Release Google.Cloud.BigQuery.Connection.V1 version 2.3.0
  apis/Google.Cloud.BigQuery.Connection.V1/Google.Cloud.BigQuery.Connection.V1/Google.Cloud.BigQuery.Connection.V1.csproj
  apis/Google.Cloud.BigQuery.Connection.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9725 Release Google.Cloud.CloudBuild.V1 version 2.2.0
  apis/Google.Cloud.CloudBuild.V1/Google.Cloud.CloudBuild.V1/Google.Cloud.CloudBuild.V1.csproj
  apis/Google.Cloud.CloudBuild.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9730 Release Google.Cloud.Eventarc.Publishing.V1 version 2.0.0-beta03
  apis/Google.Cloud.Eventarc.Publishing.V1/Google.Cloud.Eventarc.Publishing.V1/Google.Cloud.Eventarc.Publishing.V1.csproj
  apis/Google.Cloud.Eventarc.Publishing.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9732 Release Google.Cloud.MediaTranslation.V1Beta1 version 2.0.0-beta02
  apis/Google.Cloud.MediaTranslation.V1Beta1/Google.Cloud.MediaTranslation.V1Beta1/Google.Cloud.MediaTranslation.V1Beta1.csproj
  apis/Google.Cloud.MediaTranslation.V1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9741 Release Google.Cloud.SecurityCenter.V1 version 3.8.0
  apis/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1.csproj
  apis/Google.Cloud.SecurityCenter.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9722 Release Google.Cloud.BigQuery.DataTransfer.V1 version 4.3.0
  apis/Google.Cloud.BigQuery.DataTransfer.V1/Google.Cloud.BigQuery.DataTransfer.V1/Google.Cloud.BigQuery.DataTransfer.V1.csproj
  apis/Google.Cloud.BigQuery.DataTransfer.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9728 Release Google.Cloud.Debugger.V2 version 3.1.0
  apis/Google.Cloud.Debugger.V2/Google.Cloud.Debugger.V2/Google.Cloud.Debugger.V2.csproj
  apis/Google.Cloud.Debugger.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9737 Release Google.Cloud.Retail.V2 version 2.4.0
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2.csproj
  apis/Google.Cloud.Retail.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9723 Release Google.Cloud.BigQuery.Reservation.V1 version 2.1.0
  apis/Google.Cloud.BigQuery.Reservation.V1/Google.Cloud.BigQuery.Reservation.V1/Google.Cloud.BigQuery.Reservation.V1.csproj
  apis/Google.Cloud.BigQuery.Reservation.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9721 Release Google.Cloud.BigQuery.DataPolicies.V1 version 1.0.0-beta02
  apis/Google.Cloud.BigQuery.DataPolicies.V1/Google.Cloud.BigQuery.DataPolicies.V1/Google.Cloud.BigQuery.DataPolicies.V1.csproj
  apis/Google.Cloud.BigQuery.DataPolicies.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9724 Release Google.Cloud.Billing.Budgets.V1 version 2.1.0
  apis/Google.Cloud.Billing.Budgets.V1/Google.Cloud.Billing.Budgets.V1/Google.Cloud.Billing.Budgets.V1.csproj
  apis/Google.Cloud.Billing.Budgets.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#9754 Release Google.Cloud.Compute.V1 version 2.6.0
  apis/Google.Cloud.Compute.V1/Google.Cloud.Compute.V1/Google.Cloud.Compute.V1.csproj
  apis/Google.Cloud.Compute.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact
