Repository googleapis/google-cloud-dotnet, pull requests merged in 2023-05, with the labels that each got.

#10289 Release Google.Cloud.Run.V2 version 2.1.0
  apis/Google.Cloud.Run.V2/Google.Cloud.Run.V2/Google.Cloud.Run.V2.csproj
  apis/Google.Cloud.Run.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10291 Release Google.Cloud.Talent.V4 version 2.3.0
  apis/Google.Cloud.Talent.V4/Google.Cloud.Talent.V4/Google.Cloud.Talent.V4.csproj
  apis/Google.Cloud.Talent.V4/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10290 Release Google.Cloud.SecurityCenter.V1 version 3.10.0
  apis/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1.csproj
  apis/Google.Cloud.SecurityCenter.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10283 Release Google.Cloud.Container.V1 version 3.11.0
  apis/Google.Cloud.Container.V1/Google.Cloud.Container.V1/Google.Cloud.Container.V1.csproj
  apis/Google.Cloud.Container.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10287 Release Google.Cloud.GkeHub.V1 version 2.2.0
  apis/Google.Cloud.GkeHub.V1/Google.Cloud.GkeHub.V1/Google.Cloud.GkeHub.V1.csproj
  apis/Google.Cloud.GkeHub.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10281 Release Google.Cloud.Bigtable.V2 version 3.5.0
  apis/Google.Cloud.Bigtable.V2/Google.Cloud.Bigtable.V2/Google.Cloud.Bigtable.V2.csproj
  apis/Google.Cloud.Bigtable.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10286 Release Google.Cloud.GkeHub.V1Beta1 version 2.0.0-beta04
  apis/Google.Cloud.GkeHub.V1Beta1/Google.Cloud.GkeHub.V1Beta1/Google.Cloud.GkeHub.V1Beta1.csproj
  apis/Google.Cloud.GkeHub.V1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10279 Release Google.Analytics.Admin.V1Alpha version 2.0.0-alpha08
  apis/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha.csproj
  apis/Google.Analytics.Admin.V1Alpha/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10284 Release Google.Cloud.Deploy.V1 version 2.4.0
  apis/Google.Cloud.Deploy.V1/Google.Cloud.Deploy.V1/Google.Cloud.Deploy.V1.csproj
  apis/Google.Cloud.Deploy.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10285 Release Google.Cloud.DiscoveryEngine.V1Beta version 1.0.0-beta04
  apis/Google.Cloud.DiscoveryEngine.V1Beta/Google.Cloud.DiscoveryEngine.V1Beta/Google.Cloud.DiscoveryEngine.V1Beta.csproj
  apis/Google.Cloud.DiscoveryEngine.V1Beta/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10280 Release Google.Cloud.AIPlatform.V1 version 2.14.0
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1.csproj
  apis/Google.Cloud.AIPlatform.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10288 Release Google.Cloud.Orchestration.Airflow.Service.V1 version 2.3.0
  apis/Google.Cloud.Orchestration.Airflow.Service.V1/Google.Cloud.Orchestration.Airflow.Service.V1/Google.Cloud.Orchestration.Airflow.Service.V1.csproj
  apis/Google.Cloud.Orchestration.Airflow.Service.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10282 Release Google.Cloud.ContactCenterInsights.V1 version 2.7.0
  apis/Google.Cloud.ContactCenterInsights.V1/Google.Cloud.ContactCenterInsights.V1/Google.Cloud.ContactCenterInsights.V1.csproj
  apis/Google.Cloud.ContactCenterInsights.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10295 Release Firestore libraries version 3.3.0
  apis/Google.Cloud.Firestore.V1/Google.Cloud.Firestore.V1/Google.Cloud.Firestore.V1.csproj
  apis/Google.Cloud.Firestore.V1/docs/history.md
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore/Google.Cloud.Firestore.csproj
  apis/Google.Cloud.Firestore/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10293 Release Google.Cloud.Dataplex.V1 version 2.4.0
  apis/Google.Cloud.Dataplex.V1/Google.Cloud.Dataplex.V1/Google.Cloud.Dataplex.V1.csproj
  apis/Google.Cloud.Dataplex.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10300 Release Google.Cloud.Logging.Console version 1.1.0
  apis/Google.Cloud.Logging.Console/Google.Cloud.Logging.Console/Google.Cloud.Logging.Console.csproj
  apis/Google.Cloud.Logging.Console/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10302 Release Spanner libraries version 4.5.0
  apis/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1.csproj
  apis/Google.Cloud.Spanner.Admin.Instance.V1/Google.Cloud.Spanner.Admin.Instance.V1/Google.Cloud.Spanner.Admin.Instance.V1.csproj
  apis/Google.Cloud.Spanner.Common.V1/Google.Cloud.Spanner.Common.V1/Google.Cloud.Spanner.Common.V1.csproj
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.csproj
  apis/Google.Cloud.Spanner.Data/docs/history.md
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1.csproj
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10309 Release Google.Cloud.PubSub.V1 version 3.5.1
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1.csproj
  apis/Google.Cloud.PubSub.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10341 Release Google.Cloud.Speech.V2 version 1.0.0-beta05
  apis/Google.Cloud.Speech.V2/Google.Cloud.Speech.V2/Google.Cloud.Speech.V2.csproj
  apis/Google.Cloud.Speech.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10338 Release Google.Cloud.Functions.V1 version 2.2.0
  apis/Google.Cloud.Functions.V1/Google.Cloud.Functions.V1/Google.Cloud.Functions.V1.csproj
  apis/Google.Cloud.Functions.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10339 Release Google.Cloud.Monitoring.V3 version 3.3.0
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3.csproj
  apis/Google.Cloud.Monitoring.V3/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10334 Release Google.Cloud.Datastream.V1 version 2.3.0
  apis/Google.Cloud.Datastream.V1/Google.Cloud.Datastream.V1/Google.Cloud.Datastream.V1.csproj
  apis/Google.Cloud.Datastream.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10336 Release Google.Cloud.Dialogflow.V2 version 4.10.0
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2.csproj
  apis/Google.Cloud.Dialogflow.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10332 Release Google.Cloud.Channel.V1 version 2.6.0
  apis/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1.csproj
  apis/Google.Cloud.Channel.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10337 Release Google.Cloud.Dialogflow.V2Beta1 version 1.0.0-beta07
  apis/Google.Cloud.Dialogflow.V2Beta1/Google.Cloud.Dialogflow.V2Beta1/Google.Cloud.Dialogflow.V2Beta1.csproj
  apis/Google.Cloud.Dialogflow.V2Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10333 Release Google.Cloud.Container.V1 version 3.12.0
  apis/Google.Cloud.Container.V1/Google.Cloud.Container.V1/Google.Cloud.Container.V1.csproj
  apis/Google.Cloud.Container.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10331 Release Google.Cloud.Batch.V1 version 2.1.0
  apis/Google.Cloud.Batch.V1/Google.Cloud.Batch.V1/Google.Cloud.Batch.V1.csproj
  apis/Google.Cloud.Batch.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10335 Release Google.Cloud.Dialogflow.Cx.V3 version 2.7.0
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3.csproj
  apis/Google.Cloud.Dialogflow.Cx.V3/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10363 Release Google.Analytics.Admin.V1Alpha version 2.0.0-alpha09
  apis/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha.csproj
  apis/Google.Analytics.Admin.V1Alpha/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10365 Release Google.Cloud.PubSub.V1 version 3.6.0-beta01
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1.csproj
  apis/Google.Cloud.PubSub.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10393 chore: Remove deprecated package Google.Cloud.Debugger.V2
  apis/Google.Cloud.Debugger.V2/.OwlBot.yaml
  apis/Google.Cloud.Debugger.V2/.repo-metadata.json
  apis/Google.Cloud.Debugger.V2/Google.Cloud.Debugger.V2.GeneratedSnippets/Controller2Client.ListActiveBreakpointsAsyncSnippet.g.cs
  apis/Google.Cloud.Debugger.V2/Google.Cloud.Debugger.V2.GeneratedSnippets/Controller2Client.ListActiveBreakpointsRequestObjectAsyncSnippet.g.cs
  apis/Google.Cloud.Debugger.V2/Google.Cloud.Debugger.V2.GeneratedSnippets/Controller2Client.ListActiveBreakpointsRequestObjectSnippet.g.cs
  apis/Google.Cloud.Debugger.V2/Google.Cloud.Debugger.V2.GeneratedSnippets/Controller2Client.ListActiveBreakpointsSnippet.g.cs
  apis/Google.Cloud.Debugger.V2/Google.Cloud.Debugger.V2.GeneratedSnippets/Controller2Client.RegisterDebuggeeAsyncSnippet.g.cs
  apis/Google.Cloud.Debugger.V2/Google.Cloud.Debugger.V2.GeneratedSnippets/Controller2Client.RegisterDebuggeeRequestObjectAsyncSnippet.g.cs
  apis/Google.Cloud.Debugger.V2/Google.Cloud.Debugger.V2.GeneratedSnippets/Controller2Client.RegisterDebuggeeRequestObjectSnippet.g.cs
  apis/Google.Cloud.Debugger.V2/Google.Cloud.Debugger.V2.GeneratedSnippets/Controller2Client.RegisterDebuggeeSnippet.g.cs
  apis/Google.Cloud.Debugger.V2/Google.Cloud.Debugger.V2.GeneratedSnippets/Controller2Client.UpdateActiveBreakpointAsyncSnippet.g.cs
  apis/Google.Cloud.Debugger.V2/Google.Cloud.Debugger.V2.GeneratedSnippets/Controller2Client.UpdateActiveBreakpointRequestObjectAsyncSnippet.g.cs
  apis/Google.Cloud.Debugger.V2/Google.Cloud.Debugger.V2.GeneratedSnippets/Controller2Client.UpdateActiveBreakpointRequestObjectSnippet.g.cs
  apis/Google.Cloud.Debugger.V2/Google.Cloud.Debugger.V2.GeneratedSnippets/Controller2Client.UpdateActiveBreakpointSnippet.g.cs
  apis/Google.Cloud.Debugger.V2/Google.Cloud.Debugger.V2.GeneratedSnippets/Debugger2Client.DeleteBreakpointAsyncSnippet.g.cs
  apis/Google.Cloud.Debugger.V2/Google.Cloud.Debugger.V2.GeneratedSnippets/Debugger2Client.DeleteBreakpointRequestObjectAsyncSnippet.g.cs
  apis/Google.Cloud.Debugger.V2/Google.Cloud.Debugger.V2.GeneratedSnippets/Debugger2Client.DeleteBreakpointRequestObjectSnippet.g.cs
  apis/Google.Cloud.Debugger.V2/Google.Cloud.Debugger.V2.GeneratedSnippets/Debugger2Client.DeleteBreakpointSnippet.g.cs
  apis/Google.Cloud.Debugger.V2/Google.Cloud.Debugger.V2.GeneratedSnippets/Debugger2Client.GetBreakpointAsyncSnippet.g.cs
  apis/Google.Cloud.Debugger.V2/Google.Cloud.Debugger.V2.GeneratedSnippets/Debugger2Client.GetBreakpointRequestObjectAsyncSnippet.g.cs
  apis/Google.Cloud.Debugger.V2/Google.Cloud.Debugger.V2.GeneratedSnippets/Debugger2Client.GetBreakpointRequestObjectSnippet.g.cs
  apis/Google.Cloud.Debugger.V2/Google.Cloud.Debugger.V2.GeneratedSnippets/Debugger2Client.GetBreakpointSnippet.g.cs
  apis/Google.Cloud.Debugger.V2/Google.Cloud.Debugger.V2.GeneratedSnippets/Debugger2Client.ListBreakpointsAsyncSnippet.g.cs
  apis/Google.Cloud.Debugger.V2/Google.Cloud.Debugger.V2.GeneratedSnippets/Debugger2Client.ListBreakpointsRequestObjectAsyncSnippet.g.cs
  apis/Google.Cloud.Debugger.V2/Google.Cloud.Debugger.V2.GeneratedSnippets/Debugger2Client.ListBreakpointsRequestObjectSnippet.g.cs
  apis/Google.Cloud.Debugger.V2/Google.Cloud.Debugger.V2.GeneratedSnippets/Debugger2Client.ListBreakpointsSnippet.g.cs
  apis/Google.Cloud.Debugger.V2/Google.Cloud.Debugger.V2.GeneratedSnippets/Debugger2Client.ListDebuggeesAsyncSnippet.g.cs
  apis/Google.Cloud.Debugger.V2/Google.Cloud.Debugger.V2.GeneratedSnippets/Debugger2Client.ListDebuggeesRequestObjectAsyncSnippet.g.cs
  apis/Google.Cloud.Debugger.V2/Google.Cloud.Debugger.V2.GeneratedSnippets/Debugger2Client.ListDebuggeesRequestObjectSnippet.g.cs
  apis/Google.Cloud.Debugger.V2/Google.Cloud.Debugger.V2.GeneratedSnippets/Debugger2Client.ListDebuggeesSnippet.g.cs
  apis/Google.Cloud.Debugger.V2/Google.Cloud.Debugger.V2.GeneratedSnippets/Debugger2Client.SetBreakpointAsyncSnippet.g.cs
  apis/Google.Cloud.Debugger.V2/Google.Cloud.Debugger.V2.GeneratedSnippets/Debugger2Client.SetBreakpointRequestObjectAsyncSnippet.g.cs
  apis/Google.Cloud.Debugger.V2/Google.Cloud.Debugger.V2.GeneratedSnippets/Debugger2Client.SetBreakpointRequestObjectSnippet.g.cs
  apis/Google.Cloud.Debugger.V2/Google.Cloud.Debugger.V2.GeneratedSnippets/Debugger2Client.SetBreakpointSnippet.g.cs
  apis/Google.Cloud.Debugger.V2/Google.Cloud.Debugger.V2.GeneratedSnippets/Google.Cloud.Debugger.V2.GeneratedSnippets.csproj
  apis/Google.Cloud.Debugger.V2/Google.Cloud.Debugger.V2.GeneratedSnippets/snippet_metadata_google.devtools.clouddebugger.v2.json
  apis/Google.Cloud.Debugger.V2/Google.Cloud.Debugger.V2.Snippets/Controller2ClientSnippets.cs
  apis/Google.Cloud.Debugger.V2/Google.Cloud.Debugger.V2.Snippets/Controller2ClientSnippets.g.cs
  apis/Google.Cloud.Debugger.V2/Google.Cloud.Debugger.V2.Snippets/Debugger2ClientSnippets.g.cs
  apis/Google.Cloud.Debugger.V2/Google.Cloud.Debugger.V2.Snippets/DebuggerServiceFixture.cs
  apis/Google.Cloud.Debugger.V2/Google.Cloud.Debugger.V2.Snippets/Google.Cloud.Debugger.V2.Snippets.csproj
  apis/Google.Cloud.Debugger.V2/Google.Cloud.Debugger.V2.Snippets/coverage.xml
  apis/Google.Cloud.Debugger.V2/Google.Cloud.Debugger.V2.sln
  apis/Google.Cloud.Debugger.V2/Google.Cloud.Debugger.V2/Controller.g.cs
  apis/Google.Cloud.Debugger.V2/Google.Cloud.Debugger.V2/Controller2Client.g.cs
  apis/Google.Cloud.Debugger.V2/Google.Cloud.Debugger.V2/ControllerGrpc.g.cs
  apis/Google.Cloud.Debugger.V2/Google.Cloud.Debugger.V2/Data.g.cs
  apis/Google.Cloud.Debugger.V2/Google.Cloud.Debugger.V2/Debugger.g.cs
  apis/Google.Cloud.Debugger.V2/Google.Cloud.Debugger.V2/Debugger2Client.g.cs
  apis/Google.Cloud.Debugger.V2/Google.Cloud.Debugger.V2/DebuggerGrpc.g.cs
  apis/Google.Cloud.Debugger.V2/Google.Cloud.Debugger.V2/Google.Cloud.Debugger.V2.csproj
  apis/Google.Cloud.Debugger.V2/Google.Cloud.Debugger.V2/PackageApiMetadata.g.cs
  apis/Google.Cloud.Debugger.V2/Google.Cloud.Debugger.V2/ServiceCollectionExtensions.g.cs
  apis/Google.Cloud.Debugger.V2/docs/history.md
  apis/Google.Cloud.Debugger.V2/docs/index.md
  apis/Google.Cloud.Debugger.V2/gapic_metadata.json
  apis/apis.json
Labels: allow breaking changes

#10397 Release Google.Cloud.AIPlatform.V1 version 2.15.0
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1.csproj
  apis/Google.Cloud.AIPlatform.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10441 Release Google.Cloud.Batch.V1 version 2.1.0
  apis/Google.Cloud.Batch.V1/Google.Cloud.Batch.V1/Google.Cloud.Batch.V1.csproj
  apis/Google.Cloud.Batch.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10445 Release Google.Cloud.Bigtable.V2 version 3.6.0
  apis/Google.Cloud.Bigtable.V2/Google.Cloud.Bigtable.V2/Google.Cloud.Bigtable.V2.csproj
  apis/Google.Cloud.Bigtable.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10447 Release Google.Cloud.CloudDms.V1 version 2.1.0
  apis/Google.Cloud.CloudDms.V1/Google.Cloud.CloudDms.V1/Google.Cloud.CloudDms.V1.csproj
  apis/Google.Cloud.CloudDms.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10446 Release Google.Cloud.Channel.V1 version 2.7.0
  apis/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1.csproj
  apis/Google.Cloud.Channel.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10448 Release Google.Cloud.DiscoveryEngine.V1Beta version 1.0.0-beta05
  apis/Google.Cloud.DiscoveryEngine.V1Beta/Google.Cloud.DiscoveryEngine.V1Beta/Google.Cloud.DiscoveryEngine.V1Beta.csproj
  apis/Google.Cloud.DiscoveryEngine.V1Beta/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10453 Release Google.Cloud.Language.V1 version 3.3.0
  apis/Google.Cloud.Language.V1/Google.Cloud.Language.V1/Google.Cloud.Language.V1.csproj
  apis/Google.Cloud.Language.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10444 Release Google.Cloud.Bigtable.Admin.V2 version 3.4.0
  apis/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2.csproj
  apis/Google.Cloud.Bigtable.Admin.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10452 Release Google.Cloud.Kms.V1 version 3.5.0
  apis/Google.Cloud.Kms.V1/Google.Cloud.Kms.V1/Google.Cloud.Kms.V1.csproj
  apis/Google.Cloud.Kms.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10449 Release Google.Cloud.Firestore.Admin.V1 version 3.2.0
  apis/Google.Cloud.Firestore.Admin.V1/Google.Cloud.Firestore.Admin.V1/Google.Cloud.Firestore.Admin.V1.csproj
  apis/Google.Cloud.Firestore.Admin.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10454 Release Google.Cloud.WebRisk.V1 version 2.3.0
  apis/Google.Cloud.WebRisk.V1/Google.Cloud.WebRisk.V1/Google.Cloud.WebRisk.V1.csproj
  apis/Google.Cloud.WebRisk.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10450 Release Google.Cloud.Functions.V2 version 1.3.0
  apis/Google.Cloud.Functions.V2/Google.Cloud.Functions.V2/Google.Cloud.Functions.V2.csproj
  apis/Google.Cloud.Functions.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10443 Release Google.Cloud.BigQuery.Storage.V1 version 3.7.0
  apis/Google.Cloud.BigQuery.Storage.V1/Google.Cloud.BigQuery.Storage.V1/Google.Cloud.BigQuery.Storage.V1.csproj
  apis/Google.Cloud.BigQuery.Storage.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10451 Release Google.Cloud.Functions.V2Beta version 1.0.0-beta03
  apis/Google.Cloud.Functions.V2Beta/Google.Cloud.Functions.V2Beta/Google.Cloud.Functions.V2Beta.csproj
  apis/Google.Cloud.Functions.V2Beta/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#10383 feat: Support `dataBoostEnabled` field in partitioned Read/ExecuteSql
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.IntegrationTests/PartitionedReadTests.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.Tests/PartitionOptionsTests.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.Tests/SpannerCommandTests.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/DisposeBehavior.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/PartitionOptions.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/SpannerCommand.ExecutableCommand.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/SpannerCommand.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/SpannerTransaction.cs
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/ReadOrQueryRequest.cs
Labels: lex-review
