Repository googleapis/google-cloud-dotnet, pull requests merged in 2024-02, with the labels that each got.

#11656 Release Google.Cloud.SecurityCenterManagement.V1 version 1.0.0-beta01
  README.md
  apis/Google.Cloud.SecurityCenterManagement.V1/.repo-metadata.json
  apis/Google.Cloud.SecurityCenterManagement.V1/Google.Cloud.SecurityCenterManagement.V1/Google.Cloud.SecurityCenterManagement.V1.csproj
  apis/Google.Cloud.SecurityCenterManagement.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11680 Release Google.Cloud.VmwareEngine.V1 version 1.1.0
  apis/Google.Cloud.VmwareEngine.V1/Google.Cloud.VmwareEngine.V1/Google.Cloud.VmwareEngine.V1.csproj
  apis/Google.Cloud.VmwareEngine.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11684 Release Google.Cloud.Batch.V1 version 2.7.0
  apis/Google.Cloud.Batch.V1/Google.Cloud.Batch.V1/Google.Cloud.Batch.V1.csproj
  apis/Google.Cloud.Batch.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending

#11688 Release Google.Cloud.ContactCenterInsights.V1 version 2.12.0
  apis/Google.Cloud.ContactCenterInsights.V1/Google.Cloud.ContactCenterInsights.V1/Google.Cloud.ContactCenterInsights.V1.csproj
  apis/Google.Cloud.ContactCenterInsights.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11689 Release Google.Cloud.Container.V1 version 3.21.0
  apis/Google.Cloud.Container.V1/Google.Cloud.Container.V1/Google.Cloud.Container.V1.csproj
  apis/Google.Cloud.Container.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11685 Release Google.Cloud.Batch.V1Alpha version 1.0.0-alpha21
  apis/Google.Cloud.Batch.V1Alpha/Google.Cloud.Batch.V1Alpha/Google.Cloud.Batch.V1Alpha.csproj
  apis/Google.Cloud.Batch.V1Alpha/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11687 Release Google.Cloud.Compute.V1 version 2.13.0
  apis/Google.Cloud.Compute.V1/Google.Cloud.Compute.V1/Google.Cloud.Compute.V1.csproj
  apis/Google.Cloud.Compute.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11683 Release Google.Cloud.AIPlatform.V1 version 2.22.0
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1.csproj
  apis/Google.Cloud.AIPlatform.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11682 Release Google.Analytics.Admin.V1Alpha version 2.0.0-alpha16
  apis/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha.csproj
  apis/Google.Analytics.Admin.V1Alpha/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11686 Release Google.Cloud.Bigtable.V2 version 3.10.0-beta01
  apis/Google.Cloud.Bigtable.V2/Google.Cloud.Bigtable.V2/Google.Cloud.Bigtable.V2.csproj
  apis/Google.Cloud.Bigtable.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending

#11717 Release Spanner libraries version 5.0.0-beta01
  apis/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1.csproj
  apis/Google.Cloud.Spanner.Admin.Instance.V1/Google.Cloud.Spanner.Admin.Instance.V1/Google.Cloud.Spanner.Admin.Instance.V1.csproj
  apis/Google.Cloud.Spanner.Common.V1/Google.Cloud.Spanner.Common.V1/Google.Cloud.Spanner.Common.V1.csproj
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.csproj
  apis/Google.Cloud.Spanner.Data/docs/history.md
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1.csproj
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11711 Release Google.Cloud.Retail.V2 version 2.6.0
  apis/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2/Google.Cloud.Retail.V2.csproj
  apis/Google.Cloud.Retail.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11713 Release Google.Cloud.Tasks.V2Beta3 version 3.0.0-beta04
  apis/Google.Cloud.Tasks.V2Beta3/Google.Cloud.Tasks.V2Beta3/Google.Cloud.Tasks.V2Beta3.csproj
  apis/Google.Cloud.Tasks.V2Beta3/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11714 Release Google.Cloud.TelcoAutomation.V1 version 1.0.0-beta02
  apis/Google.Cloud.TelcoAutomation.V1/Google.Cloud.TelcoAutomation.V1/Google.Cloud.TelcoAutomation.V1.csproj
  apis/Google.Cloud.TelcoAutomation.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11715 Release Google.Cloud.Vision.V1 version 3.4.0
  apis/Google.Cloud.Vision.V1/Google.Cloud.Vision.V1/Google.Cloud.Vision.V1.csproj
  apis/Google.Cloud.Vision.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11704 Release Google.Cloud.DiscoveryEngine.V1Beta version 1.0.0-beta09
  apis/Google.Cloud.DiscoveryEngine.V1Beta/Google.Cloud.DiscoveryEngine.V1Beta/Google.Cloud.DiscoveryEngine.V1Beta.csproj
  apis/Google.Cloud.DiscoveryEngine.V1Beta/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11707 Release Google.Cloud.EdgeNetwork.V1 version 1.0.0-beta03
  apis/Google.Cloud.EdgeNetwork.V1/Google.Cloud.EdgeNetwork.V1/Google.Cloud.EdgeNetwork.V1.csproj
  apis/Google.Cloud.EdgeNetwork.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11709 Release Google.Cloud.Kms.V1 version 3.8.0
  apis/Google.Cloud.Kms.V1/Google.Cloud.Kms.V1/Google.Cloud.Kms.V1.csproj
  apis/Google.Cloud.Kms.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11700 Release Google.Cloud.Bigtable.Admin.V2 version 3.9.0
  apis/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2.csproj
  apis/Google.Cloud.Bigtable.Admin.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11701 Release Google.Cloud.Dataplex.V1 version 2.12.0
  apis/Google.Cloud.Dataplex.V1/Google.Cloud.Dataplex.V1/Google.Cloud.Dataplex.V1.csproj
  apis/Google.Cloud.Dataplex.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11703 Release Google.Cloud.DiscoveryEngine.V1 version 1.0.0-beta02
  apis/Google.Cloud.DiscoveryEngine.V1/Google.Cloud.DiscoveryEngine.V1/Google.Cloud.DiscoveryEngine.V1.csproj
  apis/Google.Cloud.DiscoveryEngine.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11706 Release Google.Cloud.DocumentAI.V1Beta3 version 2.0.0-beta14
  apis/Google.Cloud.DocumentAI.V1Beta3/Google.Cloud.DocumentAI.V1Beta3/Google.Cloud.DocumentAI.V1Beta3.csproj
  apis/Google.Cloud.DocumentAI.V1Beta3/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11712 Release Google.Cloud.Storage.V1 version 4.8.0
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.csproj
  apis/Google.Cloud.Storage.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11716 Release Google.Shopping.Merchant.Inventories.V1Beta version 1.0.0-beta02
  apis/Google.Shopping.Merchant.Inventories.V1Beta/Google.Shopping.Merchant.Inventories.V1Beta/Google.Shopping.Merchant.Inventories.V1Beta.csproj
  apis/Google.Shopping.Merchant.Inventories.V1Beta/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11702 Release Google.Cloud.Dialogflow.Cx.V3 version 2.15.0
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3.csproj
  apis/Google.Cloud.Dialogflow.Cx.V3/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11708 Release Google.Cloud.Functions.V1 version 2.3.0
  apis/Google.Cloud.Functions.V1/Google.Cloud.Functions.V1/Google.Cloud.Functions.V1.csproj
  apis/Google.Cloud.Functions.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11705 Release Google.Cloud.DocumentAI.V1 version 3.11.0
  apis/Google.Cloud.DocumentAI.V1/Google.Cloud.DocumentAI.V1/Google.Cloud.DocumentAI.V1.csproj
  apis/Google.Cloud.DocumentAI.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11710 Release Google.Cloud.PubSub.V1 version 3.10.0-beta01
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1.csproj
  apis/Google.Cloud.PubSub.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11723 Release Google.Cloud.AIPlatform.V1 version 2.23.0
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1.csproj
  apis/Google.Cloud.AIPlatform.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact, allow breaking changes

#11732 Release Firestore libraries version 3.5.1
  apis/Google.Cloud.Firestore.V1/Google.Cloud.Firestore.V1/Google.Cloud.Firestore.V1.csproj
  apis/Google.Cloud.Firestore.V1/docs/history.md
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore/Google.Cloud.Firestore.csproj
  apis/Google.Cloud.Firestore/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11765 Release Google.Apps.Meet.V2 version 1.0.0-beta01
  README.md
  apis/Google.Apps.Meet.V2/.repo-metadata.json
  apis/Google.Apps.Meet.V2/Google.Apps.Meet.V2/Google.Apps.Meet.V2.csproj
  apis/Google.Apps.Meet.V2/docs/history.md
  apis/Google.Apps.Meet.V2/smoketests.json
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11766 Release Google.Cloud.BigQuery.DataTransfer.V1 version 4.5.0
  apis/Google.Cloud.BigQuery.DataTransfer.V1/Google.Cloud.BigQuery.DataTransfer.V1/Google.Cloud.BigQuery.DataTransfer.V1.csproj
  apis/Google.Cloud.BigQuery.DataTransfer.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11768 Release Google.Cloud.BigQuery.Storage.V1 version 3.12.0
  apis/Google.Cloud.BigQuery.Storage.V1/Google.Cloud.BigQuery.Storage.V1/Google.Cloud.BigQuery.Storage.V1.csproj
  apis/Google.Cloud.BigQuery.Storage.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11767 Release Google.Cloud.BigQuery.V2 version 3.6.0
  apis/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2.csproj
  apis/Google.Cloud.BigQuery.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11770 Release Google.Cloud.DocumentAI.V1Beta3 version 2.0.0-beta15
  apis/Google.Cloud.DocumentAI.V1Beta3/Google.Cloud.DocumentAI.V1Beta3/Google.Cloud.DocumentAI.V1Beta3.csproj
  apis/Google.Cloud.DocumentAI.V1Beta3/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11774 Release Google.Maps.AddressValidation.V1 version 1.1.0
  apis/Google.Maps.AddressValidation.V1/Google.Maps.AddressValidation.V1/Google.Maps.AddressValidation.V1.csproj
  apis/Google.Maps.AddressValidation.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11773 Release Google.Cloud.SecurityCenter.V1 version 3.14.0
  apis/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1.csproj
  apis/Google.Cloud.SecurityCenter.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11772 Release Google.Cloud.RecaptchaEnterprise.V1 version 2.9.0
  apis/Google.Cloud.RecaptchaEnterprise.V1/Google.Cloud.RecaptchaEnterprise.V1/Google.Cloud.RecaptchaEnterprise.V1.csproj
  apis/Google.Cloud.RecaptchaEnterprise.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11775 Release Google.Maps.Places.V1 version 1.0.0-beta03
  apis/Google.Maps.Places.V1/Google.Maps.Places.V1/Google.Maps.Places.V1.csproj
  apis/Google.Maps.Places.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11771 Release Google.Cloud.Orchestration.Airflow.Service.V1 version 2.5.0
  apis/Google.Cloud.Orchestration.Airflow.Service.V1/Google.Cloud.Orchestration.Airflow.Service.V1/Google.Cloud.Orchestration.Airflow.Service.V1.csproj
  apis/Google.Cloud.Orchestration.Airflow.Service.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11807 Release Google.Cloud.Speech.V2 version 1.0.0-beta08
  apis/Google.Cloud.Speech.V2/Google.Cloud.Speech.V2/Google.Cloud.Speech.V2.csproj
  apis/Google.Cloud.Speech.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11803 Release Google.Cloud.Container.V1 version 3.22.0
  apis/Google.Cloud.Container.V1/Google.Cloud.Container.V1/Google.Cloud.Container.V1.csproj
  apis/Google.Cloud.Container.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11805 Release Google.Cloud.SecurityCenter.V1 version 3.15.0
  apis/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1.csproj
  apis/Google.Cloud.SecurityCenter.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11800 Release Google.Cloud.AlloyDb.V1Alpha version 1.0.0-alpha06
  apis/Google.Cloud.AlloyDb.V1Alpha/Google.Cloud.AlloyDb.V1Alpha/Google.Cloud.AlloyDb.V1Alpha.csproj
  apis/Google.Cloud.AlloyDb.V1Alpha/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11806 Release Google.Cloud.ServiceControl.V1 version 2.2.0
  apis/Google.Cloud.ServiceControl.V1/Google.Cloud.ServiceControl.V1/Google.Cloud.ServiceControl.V1.csproj
  apis/Google.Cloud.ServiceControl.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11801 Release Google.Cloud.AlloyDb.V1Beta version 1.0.0-beta04
  apis/Google.Cloud.AlloyDb.V1Beta/Google.Cloud.AlloyDb.V1Beta/Google.Cloud.AlloyDb.V1Beta.csproj
  apis/Google.Cloud.AlloyDb.V1Beta/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11804 Release Google.Cloud.Profiler.V2 version 2.4.0
  apis/Google.Cloud.Profiler.V2/Google.Cloud.Profiler.V2/Google.Cloud.Profiler.V2.csproj
  apis/Google.Cloud.Profiler.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11823 Release Google.Cloud.ApigeeRegistry.V1 version 1.0.0-beta05
  apis/Google.Cloud.ApigeeRegistry.V1/Google.Cloud.ApigeeRegistry.V1/Google.Cloud.ApigeeRegistry.V1.csproj
  apis/Google.Cloud.ApigeeRegistry.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11821 Release Google.Cloud.ApiKeys.V2 version 1.2.0
  apis/Google.Cloud.ApiKeys.V2/Google.Cloud.ApiKeys.V2/Google.Cloud.ApiKeys.V2.csproj
  apis/Google.Cloud.ApiKeys.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11825 Release Google.Cloud.AppEngine.V1 version 2.2.0
  apis/Google.Cloud.AppEngine.V1/Google.Cloud.AppEngine.V1/Google.Cloud.AppEngine.V1.csproj
  apis/Google.Cloud.AppEngine.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11813 Release Google.Analytics.Data.V1Beta version 2.0.0-beta05
  apis/Google.Analytics.Data.V1Beta/Google.Analytics.Data.V1Beta/Google.Analytics.Data.V1Beta.csproj
  apis/Google.Analytics.Data.V1Beta/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11820 Release Google.Cloud.ApiGateway.V1 version 2.2.0
  apis/Google.Cloud.ApiGateway.V1/Google.Cloud.ApiGateway.V1/Google.Cloud.ApiGateway.V1.csproj
  apis/Google.Cloud.ApiGateway.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11826 Release Google.Cloud.ArtifactRegistry.V1 version 2.5.0
  apis/Google.Cloud.ArtifactRegistry.V1/Google.Cloud.ArtifactRegistry.V1/Google.Cloud.ArtifactRegistry.V1.csproj
  apis/Google.Cloud.ArtifactRegistry.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11814 Release Google.Apps.Meet.V2Beta version 1.0.0-beta03
  apis/Google.Apps.Meet.V2Beta/Google.Apps.Meet.V2Beta/Google.Apps.Meet.V2Beta.csproj
  apis/Google.Apps.Meet.V2Beta/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11822 Release Google.Cloud.ApigeeConnect.V1 version 2.2.0
  apis/Google.Cloud.ApigeeConnect.V1/Google.Cloud.ApigeeConnect.V1/Google.Cloud.ApigeeConnect.V1.csproj
  apis/Google.Cloud.ApigeeConnect.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11824 Release Google.Cloud.AppEngine.Logging.V1 version 1.1.0
  apis/Google.Cloud.AppEngine.Logging.V1/Google.Cloud.AppEngine.Logging.V1/Google.Cloud.AppEngine.Logging.V1.csproj
  apis/Google.Cloud.AppEngine.Logging.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11817 Release Google.Cloud.AccessApproval.V1 version 2.3.0
  apis/Google.Cloud.AccessApproval.V1/Google.Cloud.AccessApproval.V1/Google.Cloud.AccessApproval.V1.csproj
  apis/Google.Cloud.AccessApproval.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11818 Release Google.Cloud.AdvisoryNotifications.V1 version 1.4.0
  apis/Google.Cloud.AdvisoryNotifications.V1/Google.Cloud.AdvisoryNotifications.V1/Google.Cloud.AdvisoryNotifications.V1.csproj
  apis/Google.Cloud.AdvisoryNotifications.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11812 Release Google.Analytics.Admin.V1Beta version 1.0.0-beta05
  apis/Google.Analytics.Admin.V1Beta/Google.Analytics.Admin.V1Beta/Google.Analytics.Admin.V1Beta.csproj
  apis/Google.Analytics.Admin.V1Beta/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11819 Release Google.Cloud.AlloyDb.V1 version 1.5.0
  apis/Google.Cloud.AlloyDb.V1/Google.Cloud.AlloyDb.V1/Google.Cloud.AlloyDb.V1.csproj
  apis/Google.Cloud.AlloyDb.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11816 Release Google.Area120.Tables.V1Alpha1 version 2.0.0-alpha03
  apis/Google.Area120.Tables.V1Alpha1/Google.Area120.Tables.V1Alpha1/Google.Area120.Tables.V1Alpha1.csproj
  apis/Google.Area120.Tables.V1Alpha1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11869 Release Google.Cloud.DataLabeling.V1Beta1 version 2.0.0-beta02
  apis/Google.Cloud.DataLabeling.V1Beta1/Google.Cloud.DataLabeling.V1Beta1/Google.Cloud.DataLabeling.V1Beta1.csproj
  apis/Google.Cloud.DataLabeling.V1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11860 Release Google.Cloud.Commerce.Consumer.Procurement.V1 version 1.1.0
  apis/Google.Cloud.Commerce.Consumer.Procurement.V1/Google.Cloud.Commerce.Consumer.Procurement.V1/Google.Cloud.Commerce.Consumer.Procurement.V1.csproj
  apis/Google.Cloud.Commerce.Consumer.Procurement.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11863 Release Google.Cloud.ConfidentialComputing.V1Alpha1 version 1.0.0-alpha02
  apis/Google.Cloud.ConfidentialComputing.V1Alpha1/Google.Cloud.ConfidentialComputing.V1Alpha1/Google.Cloud.ConfidentialComputing.V1Alpha1.csproj
  apis/Google.Cloud.ConfidentialComputing.V1Alpha1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11861 Release Google.Cloud.Common version 2.1.0
  apis/Google.Cloud.Common/Google.Cloud.Common/Google.Cloud.Common.csproj
  apis/Google.Cloud.Common/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11862 Release Google.Cloud.ConfidentialComputing.V1 version 1.2.0
  apis/Google.Cloud.ConfidentialComputing.V1/Google.Cloud.ConfidentialComputing.V1/Google.Cloud.ConfidentialComputing.V1.csproj
  apis/Google.Cloud.ConfidentialComputing.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11867 Release Google.Cloud.DataCatalog.V1 version 2.9.0
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1.csproj
  apis/Google.Cloud.DataCatalog.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11865 Release Google.Cloud.Connectors.V1 version 1.1.0
  apis/Google.Cloud.Connectors.V1/Google.Cloud.Connectors.V1/Google.Cloud.Connectors.V1.csproj
  apis/Google.Cloud.Connectors.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11864 Release Google.Cloud.Config.V1 version 1.2.0
  apis/Google.Cloud.Config.V1/Google.Cloud.Config.V1/Google.Cloud.Config.V1.csproj
  apis/Google.Cloud.Config.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11866 Release Google.Cloud.DataCatalog.Lineage.V1 version 1.2.0
  apis/Google.Cloud.DataCatalog.Lineage.V1/Google.Cloud.DataCatalog.Lineage.V1/Google.Cloud.DataCatalog.Lineage.V1.csproj
  apis/Google.Cloud.DataCatalog.Lineage.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11868 Release Google.Cloud.DataFusion.V1 version 2.2.0
  apis/Google.Cloud.DataFusion.V1/Google.Cloud.DataFusion.V1/Google.Cloud.DataFusion.V1.csproj
  apis/Google.Cloud.DataFusion.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11918 Release Google.Cloud.Logging.V2 version 4.2.0
  apis/Google.Cloud.Logging.V2/Google.Cloud.Logging.V2/Google.Cloud.Logging.V2.csproj
  apis/Google.Cloud.Logging.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11916 Release Google.Cloud.Logging.Type version 4.1.0
  apis/Google.Cloud.Logging.Type/Google.Cloud.Logging.Type/Google.Cloud.Logging.Type.csproj
  apis/Google.Cloud.Logging.Type/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11913 Release Google.Cloud.Logging.Console version 1.2.0
  apis/Google.Cloud.Logging.Console/Google.Cloud.Logging.Console/Google.Cloud.Logging.Console.csproj
  apis/Google.Cloud.Logging.Console/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11905 Release Google.Cloud.Ids.V1 version 2.2.0
  apis/Google.Cloud.Ids.V1/Google.Cloud.Ids.V1/Google.Cloud.Ids.V1.csproj
  apis/Google.Cloud.Ids.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11910 Release Google.Cloud.LifeSciences.V2Beta version 2.0.0-beta04
  apis/Google.Cloud.LifeSciences.V2Beta/Google.Cloud.LifeSciences.V2Beta/Google.Cloud.LifeSciences.V2Beta.csproj
  apis/Google.Cloud.LifeSciences.V2Beta/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11903 Release Google.Cloud.Iam.V2 version 1.1.0
  apis/Google.Cloud.Iam.V2/Google.Cloud.Iam.V2/Google.Cloud.Iam.V2.csproj
  apis/Google.Cloud.Iam.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11909 Release Google.Cloud.Language.V2 version 1.0.0-beta02
  apis/Google.Cloud.Language.V2/Google.Cloud.Language.V2/Google.Cloud.Language.V2.csproj
  apis/Google.Cloud.Language.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11902 Release Google.Cloud.Iam.V1 version 3.1.0
  apis/Google.Cloud.Iam.V1/Google.Cloud.Iam.V1/Google.Cloud.Iam.V1.csproj
  apis/Google.Cloud.Iam.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11921 Release Google.Cloud.ManagedIdentities.V1 version 3.1.0
  apis/Google.Cloud.ManagedIdentities.V1/Google.Cloud.ManagedIdentities.V1/Google.Cloud.ManagedIdentities.V1.csproj
  apis/Google.Cloud.ManagedIdentities.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11911 Release Google.Cloud.Location version 2.1.0
  apis/Google.Cloud.Location/Google.Cloud.Location/Google.Cloud.Location.csproj
  apis/Google.Cloud.Location/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11906 Release Google.Cloud.Kms.Inventory.V1 version 1.2.0
  apis/Google.Cloud.Kms.Inventory.V1/Google.Cloud.Kms.Inventory.V1/Google.Cloud.Kms.Inventory.V1.csproj
  apis/Google.Cloud.Kms.Inventory.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11901 Release Google.Cloud.Iam.Credentials.V1 version 2.2.0
  apis/Google.Cloud.Iam.Credentials.V1/Google.Cloud.Iam.Credentials.V1/Google.Cloud.Iam.Credentials.V1.csproj
  apis/Google.Cloud.Iam.Credentials.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11904 Release Google.Cloud.Iap.V1 version 2.5.0
  apis/Google.Cloud.Iap.V1/Google.Cloud.Iap.V1/Google.Cloud.Iap.V1.csproj
  apis/Google.Cloud.Iap.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11907 Release Google.Cloud.Language.V1 version 3.5.0
  apis/Google.Cloud.Language.V1/Google.Cloud.Language.V1/Google.Cloud.Language.V1.csproj
  apis/Google.Cloud.Language.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11948 Release Google.Cloud.OsConfig.V1Alpha version 2.0.0-alpha03
  apis/Google.Cloud.OsConfig.V1Alpha/Google.Cloud.OsConfig.V1Alpha/Google.Cloud.OsConfig.V1Alpha.csproj
  apis/Google.Cloud.OsConfig.V1Alpha/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11947 Release Google.Cloud.OsConfig.V1 version 2.2.0
  apis/Google.Cloud.OsConfig.V1/Google.Cloud.OsConfig.V1/Google.Cloud.OsConfig.V1.csproj
  apis/Google.Cloud.OsConfig.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11946 Release Google.Cloud.OrgPolicy.V2 version 2.4.0
  apis/Google.Cloud.OrgPolicy.V2/Google.Cloud.OrgPolicy.V2/Google.Cloud.OrgPolicy.V2.csproj
  apis/Google.Cloud.OrgPolicy.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11945 Release Google.Cloud.OrgPolicy.V1 version 3.1.0
  apis/Google.Cloud.OrgPolicy.V1/Google.Cloud.OrgPolicy.V1/Google.Cloud.OrgPolicy.V1.csproj
  apis/Google.Cloud.OrgPolicy.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11942 Release Google.Cloud.Notebooks.V1Beta1 version 2.0.0-beta03
  apis/Google.Cloud.Notebooks.V1Beta1/Google.Cloud.Notebooks.V1Beta1/Google.Cloud.Notebooks.V1Beta1.csproj
  apis/Google.Cloud.Notebooks.V1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11938 Release Google.Cloud.NetworkConnectivity.V1Alpha1 version 2.0.0-alpha02
  apis/Google.Cloud.NetworkConnectivity.V1Alpha1/Google.Cloud.NetworkConnectivity.V1Alpha1/Google.Cloud.NetworkConnectivity.V1Alpha1.csproj
  apis/Google.Cloud.NetworkConnectivity.V1Alpha1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11935 Release Google.Cloud.Monitoring.V3 version 3.6.0
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3.csproj
  apis/Google.Cloud.Monitoring.V3/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11939 Release Google.Cloud.NetworkManagement.V1 version 2.6.0
  apis/Google.Cloud.NetworkManagement.V1/Google.Cloud.NetworkManagement.V1/Google.Cloud.NetworkManagement.V1.csproj
  apis/Google.Cloud.NetworkManagement.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11937 Release Google.Cloud.NetworkConnectivity.V1 version 2.6.0
  apis/Google.Cloud.NetworkConnectivity.V1/Google.Cloud.NetworkConnectivity.V1/Google.Cloud.NetworkConnectivity.V1.csproj
  apis/Google.Cloud.NetworkConnectivity.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11940 Release Google.Cloud.NetworkSecurity.V1Beta1 version 2.0.0-beta04
  apis/Google.Cloud.NetworkSecurity.V1Beta1/Google.Cloud.NetworkSecurity.V1Beta1/Google.Cloud.NetworkSecurity.V1Beta1.csproj
  apis/Google.Cloud.NetworkSecurity.V1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11934 Release Google.Cloud.MigrationCenter.V1 version 1.1.0
  apis/Google.Cloud.MigrationCenter.V1/Google.Cloud.MigrationCenter.V1/Google.Cloud.MigrationCenter.V1.csproj
  apis/Google.Cloud.MigrationCenter.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11944 Release Google.Cloud.Optimization.V1 version 2.4.0
  apis/Google.Cloud.Optimization.V1/Google.Cloud.Optimization.V1/Google.Cloud.Optimization.V1.csproj
  apis/Google.Cloud.Optimization.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11941 Release Google.Cloud.Notebooks.V1 version 2.3.0
  apis/Google.Cloud.Notebooks.V1/Google.Cloud.Notebooks.V1/Google.Cloud.Notebooks.V1.csproj
  apis/Google.Cloud.Notebooks.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11936 Release Google.Cloud.NetApp.V1 version 1.0.0-beta03
  apis/Google.Cloud.NetApp.V1/Google.Cloud.NetApp.V1/Google.Cloud.NetApp.V1.csproj
  apis/Google.Cloud.NetApp.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11933 Release Google.Cloud.Metastore.V1Beta version 2.0.0-beta08
  apis/Google.Cloud.Metastore.V1Beta/Google.Cloud.Metastore.V1Beta/Google.Cloud.Metastore.V1Beta.csproj
  apis/Google.Cloud.Metastore.V1Beta/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11899 Release Google.Cloud.GkeMultiCloud.V1 version 2.4.0
  apis/Google.Cloud.GkeMultiCloud.V1/Google.Cloud.GkeMultiCloud.V1/Google.Cloud.GkeMultiCloud.V1.csproj
  apis/Google.Cloud.GkeMultiCloud.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11928 Release Google.Cloud.MediaTranslation.V1Beta1 version 2.0.0-beta03
  apis/Google.Cloud.MediaTranslation.V1Beta1/Google.Cloud.MediaTranslation.V1Beta1/Google.Cloud.MediaTranslation.V1Beta1.csproj
  apis/Google.Cloud.MediaTranslation.V1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11931 Release Google.Cloud.Metastore.V1 version 2.6.0
  apis/Google.Cloud.Metastore.V1/Google.Cloud.Metastore.V1/Google.Cloud.Metastore.V1.csproj
  apis/Google.Cloud.Metastore.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11897 Release Google.Cloud.GkeHub.V1Beta1 version 2.0.0-beta05
  apis/Google.Cloud.GkeHub.V1Beta1/Google.Cloud.GkeHub.V1Beta1/Google.Cloud.GkeHub.V1Beta1.csproj
  apis/Google.Cloud.GkeHub.V1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11932 Release Google.Cloud.Metastore.V1Alpha version 2.0.0-alpha08
  apis/Google.Cloud.Metastore.V1Alpha/Google.Cloud.Metastore.V1Alpha/Google.Cloud.Metastore.V1Alpha.csproj
  apis/Google.Cloud.Metastore.V1Alpha/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11898 Release Google.Cloud.GkeHub.V1 version 2.3.0
  apis/Google.Cloud.GkeHub.V1/Google.Cloud.GkeHub.V1/Google.Cloud.GkeHub.V1.csproj
  apis/Google.Cloud.GkeHub.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11896 Release Google.Cloud.GkeConnect.Gateway.V1Beta1 version 2.0.0-beta02
  apis/Google.Cloud.GkeConnect.Gateway.V1Beta1/Google.Cloud.GkeConnect.Gateway.V1Beta1/Google.Cloud.GkeConnect.Gateway.V1Beta1.csproj
  apis/Google.Cloud.GkeConnect.Gateway.V1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11929 Release Google.Cloud.Memcache.V1 version 2.3.0
  apis/Google.Cloud.Memcache.V1/Google.Cloud.Memcache.V1/Google.Cloud.Memcache.V1.csproj
  apis/Google.Cloud.Memcache.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11930 Release Google.Cloud.Memcache.V1Beta2 version 2.0.0-beta04
  apis/Google.Cloud.Memcache.V1Beta2/Google.Cloud.Memcache.V1Beta2/Google.Cloud.Memcache.V1Beta2.csproj
  apis/Google.Cloud.Memcache.V1Beta2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11894 Release Google.Cloud.GSuiteAddOns.V1 version 2.2.0
  apis/Google.Cloud.GSuiteAddOns.V1/Google.Cloud.GSuiteAddOns.V1/Google.Cloud.GSuiteAddOns.V1.csproj
  apis/Google.Cloud.GSuiteAddOns.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11893 Release Google.Cloud.Functions.V2Beta version 1.0.0-beta04
  apis/Google.Cloud.Functions.V2Beta/Google.Cloud.Functions.V2Beta/Google.Cloud.Functions.V2Beta.csproj
  apis/Google.Cloud.Functions.V2Beta/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11888 Release Google.Cloud.Eventarc.Publishing.V1 version 2.0.0-beta04
  apis/Google.Cloud.Eventarc.Publishing.V1/Google.Cloud.Eventarc.Publishing.V1/Google.Cloud.Eventarc.Publishing.V1.csproj
  apis/Google.Cloud.Eventarc.Publishing.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11895 Release Google.Cloud.GkeBackup.V1 version 2.3.0
  apis/Google.Cloud.GkeBackup.V1/Google.Cloud.GkeBackup.V1/Google.Cloud.GkeBackup.V1.csproj
  apis/Google.Cloud.GkeBackup.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11892 Release Google.Cloud.Functions.V2 version 1.4.0
  apis/Google.Cloud.Functions.V2/Google.Cloud.Functions.V2/Google.Cloud.Functions.V2.csproj
  apis/Google.Cloud.Functions.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11889 Release Google.Cloud.Eventarc.V1 version 2.3.0
  apis/Google.Cloud.Eventarc.V1/Google.Cloud.Eventarc.V1/Google.Cloud.Eventarc.V1.csproj
  apis/Google.Cloud.Eventarc.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11886 Release Google.Cloud.ErrorReporting.V1Beta1 version 3.0.0-beta03
  apis/Google.Cloud.ErrorReporting.V1Beta1/Google.Cloud.ErrorReporting.V1Beta1/Google.Cloud.ErrorReporting.V1Beta1.csproj
  apis/Google.Cloud.ErrorReporting.V1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11890 Release Google.Cloud.Filestore.V1 version 2.4.0
  apis/Google.Cloud.Filestore.V1/Google.Cloud.Filestore.V1/Google.Cloud.Filestore.V1.csproj
  apis/Google.Cloud.Filestore.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11891 Release Google.Cloud.Firestore.Admin.V1 version 3.6.0
  apis/Google.Cloud.Firestore.Admin.V1/Google.Cloud.Firestore.Admin.V1/Google.Cloud.Firestore.Admin.V1.csproj
  apis/Google.Cloud.Firestore.Admin.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11887 Release Google.Cloud.EssentialContacts.V1 version 2.3.0
  apis/Google.Cloud.EssentialContacts.V1/Google.Cloud.EssentialContacts.V1/Google.Cloud.EssentialContacts.V1.csproj
  apis/Google.Cloud.EssentialContacts.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11885 Release Google.Cloud.EnterpriseKnowledgeGraph.V1 version 1.0.0-beta02
  apis/Google.Cloud.EnterpriseKnowledgeGraph.V1/Google.Cloud.EnterpriseKnowledgeGraph.V1/Google.Cloud.EnterpriseKnowledgeGraph.V1.csproj
  apis/Google.Cloud.EnterpriseKnowledgeGraph.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11883 Release Google.Cloud.Domains.V1 version 2.2.0
  apis/Google.Cloud.Domains.V1/Google.Cloud.Domains.V1/Google.Cloud.Domains.V1.csproj
  apis/Google.Cloud.Domains.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11884 Release Google.Cloud.Domains.V1Beta1 version 2.0.0-beta03
  apis/Google.Cloud.Domains.V1Beta1/Google.Cloud.Domains.V1Beta1/Google.Cloud.Domains.V1Beta1.csproj
  apis/Google.Cloud.Domains.V1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11881 Release Google.Cloud.Dialogflow.V2Beta1 version 1.0.0-beta13
  apis/Google.Cloud.Dialogflow.V2Beta1/Google.Cloud.Dialogflow.V2Beta1/Google.Cloud.Dialogflow.V2Beta1.csproj
  apis/Google.Cloud.Dialogflow.V2Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11878 Release Google.Cloud.Deploy.V1 version 2.13.0
  apis/Google.Cloud.Deploy.V1/Google.Cloud.Deploy.V1/Google.Cloud.Deploy.V1.csproj
  apis/Google.Cloud.Deploy.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11882 Release Google.Cloud.Dlp.V2 version 4.7.0
  apis/Google.Cloud.Dlp.V2/Google.Cloud.Dlp.V2/Google.Cloud.Dlp.V2.csproj
  apis/Google.Cloud.Dlp.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11875 Release Google.Cloud.Datastore.V1 version 4.8.0
  apis/Google.Cloud.Datastore.V1/Google.Cloud.Datastore.V1/Google.Cloud.Datastore.V1.csproj
  apis/Google.Cloud.Datastore.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11880 Release Google.Cloud.Dialogflow.V2 version 4.16.0
  apis/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2/Google.Cloud.Dialogflow.V2.csproj
  apis/Google.Cloud.Dialogflow.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11876 Release Google.Cloud.Datastream.V1 version 2.5.0
  apis/Google.Cloud.Datastream.V1/Google.Cloud.Datastream.V1/Google.Cloud.Datastream.V1.csproj
  apis/Google.Cloud.Datastream.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11871 Release Google.Cloud.Dataflow.V1Beta3 version 2.0.0-beta05
  apis/Google.Cloud.Dataflow.V1Beta3/Google.Cloud.Dataflow.V1Beta3/Google.Cloud.Dataflow.V1Beta3.csproj
  apis/Google.Cloud.Dataflow.V1Beta3/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11872 Release Google.Cloud.Dataform.V1Beta1 version 1.0.0-beta04
  apis/Google.Cloud.Dataform.V1Beta1/Google.Cloud.Dataform.V1Beta1/Google.Cloud.Dataform.V1Beta1.csproj
  apis/Google.Cloud.Dataform.V1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11857 Release Google.Cloud.CloudBuild.V2 version 1.1.0
  apis/Google.Cloud.CloudBuild.V2/Google.Cloud.CloudBuild.V2/Google.Cloud.CloudBuild.V2.csproj
  apis/Google.Cloud.CloudBuild.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11874 Release Google.Cloud.Datastore.Admin.V1 version 2.2.0
  apis/Google.Cloud.Datastore.Admin.V1/Google.Cloud.Datastore.Admin.V1/Google.Cloud.Datastore.Admin.V1.csproj
  apis/Google.Cloud.Datastore.Admin.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11856 Release Google.Cloud.CloudBuild.V1 version 2.8.0
  apis/Google.Cloud.CloudBuild.V1/Google.Cloud.CloudBuild.V1/Google.Cloud.CloudBuild.V1.csproj
  apis/Google.Cloud.CloudBuild.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11858 Release Google.Cloud.CloudDms.V1 version 2.3.0
  apis/Google.Cloud.CloudDms.V1/Google.Cloud.CloudDms.V1/Google.Cloud.CloudDms.V1.csproj
  apis/Google.Cloud.CloudDms.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11873 Release Google.Cloud.Dataproc.V1 version 5.9.0
  apis/Google.Cloud.Dataproc.V1/Google.Cloud.Dataproc.V1/Google.Cloud.Dataproc.V1.csproj
  apis/Google.Cloud.Dataproc.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11859 Release Google.Cloud.CloudQuotas.V1 version 1.0.0-beta02
  apis/Google.Cloud.CloudQuotas.V1/Google.Cloud.CloudQuotas.V1/Google.Cloud.CloudQuotas.V1.csproj
  apis/Google.Cloud.CloudQuotas.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11855 Release Google.Cloud.Channel.V1 version 2.10.0
  apis/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1/Google.Cloud.Channel.V1.csproj
  apis/Google.Cloud.Channel.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11849 Release Google.Cloud.Billing.Budgets.V1 version 2.4.0
  apis/Google.Cloud.Billing.Budgets.V1/Google.Cloud.Billing.Budgets.V1/Google.Cloud.Billing.Budgets.V1.csproj
  apis/Google.Cloud.Billing.Budgets.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11852 Release Google.Cloud.BinaryAuthorization.V1 version 2.2.0
  apis/Google.Cloud.BinaryAuthorization.V1/Google.Cloud.BinaryAuthorization.V1/Google.Cloud.BinaryAuthorization.V1.csproj
  apis/Google.Cloud.BinaryAuthorization.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11851 Release Google.Cloud.Billing.V1 version 3.6.0
  apis/Google.Cloud.Billing.V1/Google.Cloud.Billing.V1/Google.Cloud.Billing.V1.csproj
  apis/Google.Cloud.Billing.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11850 Release Google.Cloud.Billing.Budgets.V1Beta1 version 2.0.0-beta04
  apis/Google.Cloud.Billing.Budgets.V1Beta1/Google.Cloud.Billing.Budgets.V1Beta1/Google.Cloud.Billing.Budgets.V1Beta1.csproj
  apis/Google.Cloud.Billing.Budgets.V1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11848 Release Google.Cloud.BigQuery.Reservation.V1 version 2.3.0
  apis/Google.Cloud.BigQuery.Reservation.V1/Google.Cloud.BigQuery.Reservation.V1/Google.Cloud.BigQuery.Reservation.V1.csproj
  apis/Google.Cloud.BigQuery.Reservation.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11854 Release Google.Cloud.CertificateManager.V1 version 2.4.0
  apis/Google.Cloud.CertificateManager.V1/Google.Cloud.CertificateManager.V1/Google.Cloud.CertificateManager.V1.csproj
  apis/Google.Cloud.CertificateManager.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11853 Release Google.Cloud.BinaryAuthorization.V1Beta1 version 2.0.0-beta06
  apis/Google.Cloud.BinaryAuthorization.V1Beta1/Google.Cloud.BinaryAuthorization.V1Beta1/Google.Cloud.BinaryAuthorization.V1Beta1.csproj
  apis/Google.Cloud.BinaryAuthorization.V1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11847 Release Google.Cloud.BigQuery.Migration.V2 version 1.2.0
  apis/Google.Cloud.BigQuery.Migration.V2/Google.Cloud.BigQuery.Migration.V2/Google.Cloud.BigQuery.Migration.V2.csproj
  apis/Google.Cloud.BigQuery.Migration.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11846 Release Google.Cloud.BigQuery.Logging.V1 version 1.2.0
  apis/Google.Cloud.BigQuery.Logging.V1/Google.Cloud.BigQuery.Logging.V1/Google.Cloud.BigQuery.Logging.V1.csproj
  apis/Google.Cloud.BigQuery.Logging.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11842 Release Google.Cloud.BigQuery.DataExchange.V1Beta1 version 2.0.0-beta03
  apis/Google.Cloud.BigQuery.DataExchange.V1Beta1/Google.Cloud.BigQuery.DataExchange.V1Beta1/Google.Cloud.BigQuery.DataExchange.V1Beta1.csproj
  apis/Google.Cloud.BigQuery.DataExchange.V1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11843 Release Google.Cloud.BigQuery.DataPolicies.V1 version 1.3.0
  apis/Google.Cloud.BigQuery.DataPolicies.V1/Google.Cloud.BigQuery.DataPolicies.V1/Google.Cloud.BigQuery.DataPolicies.V1.csproj
  apis/Google.Cloud.BigQuery.DataPolicies.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11839 Release Google.Cloud.BeyondCorp.ClientGateways.V1 version 1.1.0
  apis/Google.Cloud.BeyondCorp.ClientGateways.V1/Google.Cloud.BeyondCorp.ClientGateways.V1/Google.Cloud.BeyondCorp.ClientGateways.V1.csproj
  apis/Google.Cloud.BeyondCorp.ClientGateways.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#11841 Release Google.Cloud.BigQuery.Connection.V1 version 2.7.0
  apis/Google.Cloud.BigQuery.Connection.V1/Google.Cloud.BigQuery.Connection.V1/Google.Cloud.BigQuery.Connection.V1.csproj
  apis/Google.Cloud.BigQuery.Connection.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact
