Repository googleapis/google-cloud-dotnet, pull requests merged in 2024-04, with the labels that each got.

#12538 Release Spanner libraries version 5.0.0-beta02
  apis/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1.csproj
  apis/Google.Cloud.Spanner.Admin.Instance.V1/Google.Cloud.Spanner.Admin.Instance.V1/Google.Cloud.Spanner.Admin.Instance.V1.csproj
  apis/Google.Cloud.Spanner.Common.V1/Google.Cloud.Spanner.Common.V1/Google.Cloud.Spanner.Common.V1.csproj
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.csproj
  apis/Google.Cloud.Spanner.Data/docs/history.md
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1.csproj
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#12541 Release Google.Cloud.Speech.V2 version 1.0.0
  apis/Google.Cloud.Speech.V2/.repo-metadata.json
  apis/Google.Cloud.Speech.V2/Google.Cloud.Speech.V2/Google.Cloud.Speech.V2.csproj
  apis/Google.Cloud.Speech.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#12542 feat: Generate (but don't release) Google.Cloud.BackupDR.V1
  .github/renovate.json
  apis/Google.Cloud.BackupDR.V1/.OwlBot.yaml
  apis/Google.Cloud.BackupDR.V1/.repo-metadata.json
  apis/Google.Cloud.BackupDR.V1/Google.Cloud.BackupDR.V1.GeneratedSnippets/BackupDRClient.CreateManagementServerAsyncSnippet.g.cs
  apis/Google.Cloud.BackupDR.V1/Google.Cloud.BackupDR.V1.GeneratedSnippets/BackupDRClient.CreateManagementServerRequestObjectAsyncSnippet.g.cs
  apis/Google.Cloud.BackupDR.V1/Google.Cloud.BackupDR.V1.GeneratedSnippets/BackupDRClient.CreateManagementServerRequestObjectSnippet.g.cs
  apis/Google.Cloud.BackupDR.V1/Google.Cloud.BackupDR.V1.GeneratedSnippets/BackupDRClient.CreateManagementServerResourceNamesAsyncSnippet.g.cs
  apis/Google.Cloud.BackupDR.V1/Google.Cloud.BackupDR.V1.GeneratedSnippets/BackupDRClient.CreateManagementServerResourceNamesSnippet.g.cs
  apis/Google.Cloud.BackupDR.V1/Google.Cloud.BackupDR.V1.GeneratedSnippets/BackupDRClient.CreateManagementServerSnippet.g.cs
  apis/Google.Cloud.BackupDR.V1/Google.Cloud.BackupDR.V1.GeneratedSnippets/BackupDRClient.DeleteManagementServerAsyncSnippet.g.cs
  apis/Google.Cloud.BackupDR.V1/Google.Cloud.BackupDR.V1.GeneratedSnippets/BackupDRClient.DeleteManagementServerRequestObjectAsyncSnippet.g.cs
  apis/Google.Cloud.BackupDR.V1/Google.Cloud.BackupDR.V1.GeneratedSnippets/BackupDRClient.DeleteManagementServerRequestObjectSnippet.g.cs
  apis/Google.Cloud.BackupDR.V1/Google.Cloud.BackupDR.V1.GeneratedSnippets/BackupDRClient.DeleteManagementServerResourceNamesAsyncSnippet.g.cs
  apis/Google.Cloud.BackupDR.V1/Google.Cloud.BackupDR.V1.GeneratedSnippets/BackupDRClient.DeleteManagementServerResourceNamesSnippet.g.cs
  apis/Google.Cloud.BackupDR.V1/Google.Cloud.BackupDR.V1.GeneratedSnippets/BackupDRClient.DeleteManagementServerSnippet.g.cs
  apis/Google.Cloud.BackupDR.V1/Google.Cloud.BackupDR.V1.GeneratedSnippets/BackupDRClient.GetManagementServerAsyncSnippet.g.cs
  apis/Google.Cloud.BackupDR.V1/Google.Cloud.BackupDR.V1.GeneratedSnippets/BackupDRClient.GetManagementServerRequestObjectAsyncSnippet.g.cs
  apis/Google.Cloud.BackupDR.V1/Google.Cloud.BackupDR.V1.GeneratedSnippets/BackupDRClient.GetManagementServerRequestObjectSnippet.g.cs
  apis/Google.Cloud.BackupDR.V1/Google.Cloud.BackupDR.V1.GeneratedSnippets/BackupDRClient.GetManagementServerResourceNamesAsyncSnippet.g.cs
  apis/Google.Cloud.BackupDR.V1/Google.Cloud.BackupDR.V1.GeneratedSnippets/BackupDRClient.GetManagementServerResourceNamesSnippet.g.cs
  apis/Google.Cloud.BackupDR.V1/Google.Cloud.BackupDR.V1.GeneratedSnippets/BackupDRClient.GetManagementServerSnippet.g.cs
  apis/Google.Cloud.BackupDR.V1/Google.Cloud.BackupDR.V1.GeneratedSnippets/BackupDRClient.ListManagementServersAsyncSnippet.g.cs
  apis/Google.Cloud.BackupDR.V1/Google.Cloud.BackupDR.V1.GeneratedSnippets/BackupDRClient.ListManagementServersRequestObjectAsyncSnippet.g.cs
  apis/Google.Cloud.BackupDR.V1/Google.Cloud.BackupDR.V1.GeneratedSnippets/BackupDRClient.ListManagementServersRequestObjectSnippet.g.cs
  apis/Google.Cloud.BackupDR.V1/Google.Cloud.BackupDR.V1.GeneratedSnippets/BackupDRClient.ListManagementServersResourceNamesAsyncSnippet.g.cs
  apis/Google.Cloud.BackupDR.V1/Google.Cloud.BackupDR.V1.GeneratedSnippets/BackupDRClient.ListManagementServersResourceNamesSnippet.g.cs
  apis/Google.Cloud.BackupDR.V1/Google.Cloud.BackupDR.V1.GeneratedSnippets/BackupDRClient.ListManagementServersSnippet.g.cs
  apis/Google.Cloud.BackupDR.V1/Google.Cloud.BackupDR.V1.GeneratedSnippets/Google.Cloud.BackupDR.V1.GeneratedSnippets.csproj
  apis/Google.Cloud.BackupDR.V1/Google.Cloud.BackupDR.V1.GeneratedSnippets/snippet_metadata_google.cloud.backupdr.v1.json
  apis/Google.Cloud.BackupDR.V1/Google.Cloud.BackupDR.V1.Snippets/BackupDRClientSnippets.g.cs
  apis/Google.Cloud.BackupDR.V1/Google.Cloud.BackupDR.V1.Snippets/Google.Cloud.BackupDR.V1.Snippets.csproj
  apis/Google.Cloud.BackupDR.V1/Google.Cloud.BackupDR.V1.Snippets/coverage.xml
  apis/Google.Cloud.BackupDR.V1/Google.Cloud.BackupDR.V1.sln
  apis/Google.Cloud.BackupDR.V1/Google.Cloud.BackupDR.V1/BackupDRClient.g.cs
  apis/Google.Cloud.BackupDR.V1/Google.Cloud.BackupDR.V1/Backupdr.g.cs
  apis/Google.Cloud.BackupDR.V1/Google.Cloud.BackupDR.V1/BackupdrGrpc.g.cs
  apis/Google.Cloud.BackupDR.V1/Google.Cloud.BackupDR.V1/BackupdrResourceNames.g.cs
  apis/Google.Cloud.BackupDR.V1/Google.Cloud.BackupDR.V1/Google.Cloud.BackupDR.V1.csproj
  apis/Google.Cloud.BackupDR.V1/Google.Cloud.BackupDR.V1/PackageApiMetadata.g.cs
  apis/Google.Cloud.BackupDR.V1/Google.Cloud.BackupDR.V1/ServiceCollectionExtensions.g.cs
  apis/Google.Cloud.BackupDR.V1/docs/index.md
  apis/Google.Cloud.BackupDR.V1/gapic_metadata.json
  apis/Google.Cloud.BackupDR.V1/smoketests.json
  apis/apis.json
Labels: automerge: exact

#12584 Release Google.Apps.Card.V1 version 1.0.0-beta01
  README.md
  apis/Google.Apps.Card.V1/.repo-metadata.json
  apis/Google.Apps.Card.V1/Google.Apps.Card.V1/Google.Apps.Card.V1.csproj
  apis/Google.Apps.Card.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#12588 Release Google.Cloud.Language.V1 version 3.6.0
  apis/Google.Cloud.Language.V1/Google.Cloud.Language.V1/Google.Cloud.Language.V1.csproj
  apis/Google.Cloud.Language.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#12589 Release Google.Shopping.Merchant.Lfp.V1Beta version 1.0.0-beta01
  README.md
  apis/Google.Shopping.Merchant.Lfp.V1Beta/.repo-metadata.json
  apis/Google.Shopping.Merchant.Lfp.V1Beta/Google.Shopping.Merchant.Lfp.V1Beta/Google.Shopping.Merchant.Lfp.V1Beta.csproj
  apis/Google.Shopping.Merchant.Lfp.V1Beta/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#12591 Release Google.Shopping.Merchant.Notifications.V1Beta version 1.0.0-beta01
  README.md
  apis/Google.Shopping.Merchant.Notifications.V1Beta/.repo-metadata.json
  apis/Google.Shopping.Merchant.Notifications.V1Beta/Google.Shopping.Merchant.Notifications.V1Beta/Google.Shopping.Merchant.Notifications.V1Beta.csproj
  apis/Google.Shopping.Merchant.Notifications.V1Beta/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#12592 Release Google.Cloud.BackupDR.V1 version 1.0.0-beta01
  README.md
  apis/Google.Cloud.BackupDR.V1/.repo-metadata.json
  apis/Google.Cloud.BackupDR.V1/Google.Cloud.BackupDR.V1/Google.Cloud.BackupDR.V1.csproj
  apis/Google.Cloud.BackupDR.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#12594 Release Google.Cloud.Parallelstore.V1Beta version 1.0.0-beta01
  README.md
  apis/Google.Cloud.Parallelstore.V1Beta/.repo-metadata.json
  apis/Google.Cloud.Parallelstore.V1Beta/Google.Cloud.Parallelstore.V1Beta/Google.Cloud.Parallelstore.V1Beta.csproj
  apis/Google.Cloud.Parallelstore.V1Beta/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#12593 Release Google.Cloud.CloudControlsPartner.V1Beta version 1.0.0-beta01
  README.md
  apis/Google.Cloud.CloudControlsPartner.V1Beta/.repo-metadata.json
  apis/Google.Cloud.CloudControlsPartner.V1Beta/Google.Cloud.CloudControlsPartner.V1Beta/Google.Cloud.CloudControlsPartner.V1Beta.csproj
  apis/Google.Cloud.CloudControlsPartner.V1Beta/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#12595 Release Google.Shopping.Merchant.Reports.V1Beta version 1.0.0-beta01
  README.md
  apis/Google.Shopping.Merchant.Reports.V1Beta/.repo-metadata.json
  apis/Google.Shopping.Merchant.Reports.V1Beta/Google.Shopping.Merchant.Reports.V1Beta/Google.Shopping.Merchant.Reports.V1Beta.csproj
  apis/Google.Shopping.Merchant.Reports.V1Beta/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#12557 feat!: Add support for FLOAT32
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.IntegrationTests/AllTypesTableFixture.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.IntegrationTests/BindingTests.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.IntegrationTests/GetSchemaTableTests.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.IntegrationTests/WriteTests.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.Tests/KeysTests.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.Tests/SpannerCommandTests.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.Tests/SpannerConversionOptionsTests.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.Tests/SpannerDbTypeTests.ValueConversions.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.Tests/SpannerDbTypeTests.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.Tests/SpannerParameterTests.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/SpannerConversionOptions.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/SpannerDbType.StringParsing.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/SpannerDbType.ValueConversion.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/SpannerDbType.cs
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/SpannerParameter.cs
Labels: allow breaking changes

#12596 Release Google.Cloud.CloudControlsPartner.V1 version 1.0.0-beta01
  README.md
  apis/Google.Cloud.CloudControlsPartner.V1/.repo-metadata.json
  apis/Google.Cloud.CloudControlsPartner.V1/Google.Cloud.CloudControlsPartner.V1/Google.Cloud.CloudControlsPartner.V1.csproj
  apis/Google.Cloud.CloudControlsPartner.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#12598 Release Spanner libraries version 5.0.0-beta03
  apis/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1.csproj
  apis/Google.Cloud.Spanner.Admin.Instance.V1/Google.Cloud.Spanner.Admin.Instance.V1/Google.Cloud.Spanner.Admin.Instance.V1.csproj
  apis/Google.Cloud.Spanner.Common.V1/Google.Cloud.Spanner.Common.V1/Google.Cloud.Spanner.Common.V1.csproj
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.csproj
  apis/Google.Cloud.Spanner.Data/docs/history.md
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1.csproj
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#12601 Release Google.Cloud.Asset.V1 version 3.11.0
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1.csproj
  apis/Google.Cloud.Asset.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#12602 Release Google.Cloud.Batch.V1Alpha version 1.0.0-alpha26
  apis/Google.Cloud.Batch.V1Alpha/Google.Cloud.Batch.V1Alpha/Google.Cloud.Batch.V1Alpha.csproj
  apis/Google.Cloud.Batch.V1Alpha/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#12599 Release Google.Cloud.AdvisoryNotifications.V1 version 1.6.0
  apis/Google.Cloud.AdvisoryNotifications.V1/Google.Cloud.AdvisoryNotifications.V1/Google.Cloud.AdvisoryNotifications.V1.csproj
  apis/Google.Cloud.AdvisoryNotifications.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#12603 Release Google.Cloud.BigQuery.DataTransfer.V1 version 4.8.0
  apis/Google.Cloud.BigQuery.DataTransfer.V1/Google.Cloud.BigQuery.DataTransfer.V1/Google.Cloud.BigQuery.DataTransfer.V1.csproj
  apis/Google.Cloud.BigQuery.DataTransfer.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#12616 Release Google.Shopping.Merchant.Inventories.V1Beta version 1.0.0-beta05
  apis/Google.Shopping.Merchant.Inventories.V1Beta/Google.Shopping.Merchant.Inventories.V1Beta/Google.Shopping.Merchant.Inventories.V1Beta.csproj
  apis/Google.Shopping.Merchant.Inventories.V1Beta/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#12600 Release Google.Cloud.AIPlatform.V1 version 2.27.0
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1.csproj
  apis/Google.Cloud.AIPlatform.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#12609 Release Google.Cloud.DocumentAI.V1 version 3.15.0
  apis/Google.Cloud.DocumentAI.V1/Google.Cloud.DocumentAI.V1/Google.Cloud.DocumentAI.V1.csproj
  apis/Google.Cloud.DocumentAI.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#12612 Release Google.Cloud.Security.PrivateCA.V1 version 3.7.0
  apis/Google.Cloud.Security.PrivateCA.V1/Google.Cloud.Security.PrivateCA.V1/Google.Cloud.Security.PrivateCA.V1.csproj
  apis/Google.Cloud.Security.PrivateCA.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#12617 Release Google.Apps.Chat.V1 version 1.0.0-beta01
  README.md
  apis/Google.Apps.Chat.V1/.repo-metadata.json
  apis/Google.Apps.Chat.V1/Google.Apps.Chat.V1/Google.Apps.Chat.V1.csproj
  apis/Google.Apps.Chat.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#12608 Release Google.Cloud.DiscoveryEngine.V1Beta version 1.0.0-beta12
  apis/Google.Cloud.DiscoveryEngine.V1Beta/Google.Cloud.DiscoveryEngine.V1Beta/Google.Cloud.DiscoveryEngine.V1Beta.csproj
  apis/Google.Cloud.DiscoveryEngine.V1Beta/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#12610 Release Google.Cloud.DocumentAI.V1Beta3 version 2.0.0-beta18
  apis/Google.Cloud.DocumentAI.V1Beta3/Google.Cloud.DocumentAI.V1Beta3/Google.Cloud.DocumentAI.V1Beta3.csproj
  apis/Google.Cloud.DocumentAI.V1Beta3/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#12615 Release Google.Maps.Routing.V2 version 1.0.0-beta13
  apis/Google.Maps.Routing.V2/Google.Maps.Routing.V2/Google.Maps.Routing.V2.csproj
  apis/Google.Maps.Routing.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#12607 Release Google.Cloud.DiscoveryEngine.V1 version 1.0.0-beta05
  apis/Google.Cloud.DiscoveryEngine.V1/Google.Cloud.DiscoveryEngine.V1/Google.Cloud.DiscoveryEngine.V1.csproj
  apis/Google.Cloud.DiscoveryEngine.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#12613 Release Google.Cloud.SecurityCenter.V1 version 3.20.0
  apis/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1/Google.Cloud.SecurityCenter.V1.csproj
  apis/Google.Cloud.SecurityCenter.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#12611 Release Google.Cloud.Monitoring.V3 version 3.8.0
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3.csproj
  apis/Google.Cloud.Monitoring.V3/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#12614 Release Google.Cloud.Storage.Control.V2 version 1.0.0-beta03
  apis/Google.Cloud.Storage.Control.V2/Google.Cloud.Storage.Control.V2/Google.Cloud.Storage.Control.V2.csproj
  apis/Google.Cloud.Storage.Control.V2/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#12618 Release Google.Shopping.Merchant.Conversions.V1Beta version 1.0.0-beta01
  .github/renovate.json
  README.md
  apis/Google.Shopping.Merchant.Conversions.V1Beta/.OwlBot.yaml
  apis/Google.Shopping.Merchant.Conversions.V1Beta/.repo-metadata.json
  apis/Google.Shopping.Merchant.Conversions.V1Beta/Google.Shopping.Merchant.Conversions.V1Beta.GeneratedSnippets/ConversionSourcesServiceClient.CreateConversionSourceAsyncSnippet.g.cs
  apis/Google.Shopping.Merchant.Conversions.V1Beta/Google.Shopping.Merchant.Conversions.V1Beta.GeneratedSnippets/ConversionSourcesServiceClient.CreateConversionSourceRequestObjectAsyncSnippet.g.cs
  apis/Google.Shopping.Merchant.Conversions.V1Beta/Google.Shopping.Merchant.Conversions.V1Beta.GeneratedSnippets/ConversionSourcesServiceClient.CreateConversionSourceRequestObjectSnippet.g.cs
  apis/Google.Shopping.Merchant.Conversions.V1Beta/Google.Shopping.Merchant.Conversions.V1Beta.GeneratedSnippets/ConversionSourcesServiceClient.CreateConversionSourceResourceNamesAsyncSnippet.g.cs
  apis/Google.Shopping.Merchant.Conversions.V1Beta/Google.Shopping.Merchant.Conversions.V1Beta.GeneratedSnippets/ConversionSourcesServiceClient.CreateConversionSourceResourceNamesSnippet.g.cs
  apis/Google.Shopping.Merchant.Conversions.V1Beta/Google.Shopping.Merchant.Conversions.V1Beta.GeneratedSnippets/ConversionSourcesServiceClient.CreateConversionSourceSnippet.g.cs
  apis/Google.Shopping.Merchant.Conversions.V1Beta/Google.Shopping.Merchant.Conversions.V1Beta.GeneratedSnippets/ConversionSourcesServiceClient.DeleteConversionSourceAsyncSnippet.g.cs
  apis/Google.Shopping.Merchant.Conversions.V1Beta/Google.Shopping.Merchant.Conversions.V1Beta.GeneratedSnippets/ConversionSourcesServiceClient.DeleteConversionSourceRequestObjectAsyncSnippet.g.cs
  apis/Google.Shopping.Merchant.Conversions.V1Beta/Google.Shopping.Merchant.Conversions.V1Beta.GeneratedSnippets/ConversionSourcesServiceClient.DeleteConversionSourceRequestObjectSnippet.g.cs
  apis/Google.Shopping.Merchant.Conversions.V1Beta/Google.Shopping.Merchant.Conversions.V1Beta.GeneratedSnippets/ConversionSourcesServiceClient.DeleteConversionSourceResourceNamesAsyncSnippet.g.cs
  apis/Google.Shopping.Merchant.Conversions.V1Beta/Google.Shopping.Merchant.Conversions.V1Beta.GeneratedSnippets/ConversionSourcesServiceClient.DeleteConversionSourceResourceNamesSnippet.g.cs
  apis/Google.Shopping.Merchant.Conversions.V1Beta/Google.Shopping.Merchant.Conversions.V1Beta.GeneratedSnippets/ConversionSourcesServiceClient.DeleteConversionSourceSnippet.g.cs
  apis/Google.Shopping.Merchant.Conversions.V1Beta/Google.Shopping.Merchant.Conversions.V1Beta.GeneratedSnippets/ConversionSourcesServiceClient.GetConversionSourceAsyncSnippet.g.cs
  apis/Google.Shopping.Merchant.Conversions.V1Beta/Google.Shopping.Merchant.Conversions.V1Beta.GeneratedSnippets/ConversionSourcesServiceClient.GetConversionSourceRequestObjectAsyncSnippet.g.cs
  apis/Google.Shopping.Merchant.Conversions.V1Beta/Google.Shopping.Merchant.Conversions.V1Beta.GeneratedSnippets/ConversionSourcesServiceClient.GetConversionSourceRequestObjectSnippet.g.cs
  apis/Google.Shopping.Merchant.Conversions.V1Beta/Google.Shopping.Merchant.Conversions.V1Beta.GeneratedSnippets/ConversionSourcesServiceClient.GetConversionSourceResourceNamesAsyncSnippet.g.cs
  apis/Google.Shopping.Merchant.Conversions.V1Beta/Google.Shopping.Merchant.Conversions.V1Beta.GeneratedSnippets/ConversionSourcesServiceClient.GetConversionSourceResourceNamesSnippet.g.cs
  apis/Google.Shopping.Merchant.Conversions.V1Beta/Google.Shopping.Merchant.Conversions.V1Beta.GeneratedSnippets/ConversionSourcesServiceClient.GetConversionSourceSnippet.g.cs
  apis/Google.Shopping.Merchant.Conversions.V1Beta/Google.Shopping.Merchant.Conversions.V1Beta.GeneratedSnippets/ConversionSourcesServiceClient.ListConversionSourcesAsyncSnippet.g.cs
  apis/Google.Shopping.Merchant.Conversions.V1Beta/Google.Shopping.Merchant.Conversions.V1Beta.GeneratedSnippets/ConversionSourcesServiceClient.ListConversionSourcesRequestObjectAsyncSnippet.g.cs
  apis/Google.Shopping.Merchant.Conversions.V1Beta/Google.Shopping.Merchant.Conversions.V1Beta.GeneratedSnippets/ConversionSourcesServiceClient.ListConversionSourcesRequestObjectSnippet.g.cs
  apis/Google.Shopping.Merchant.Conversions.V1Beta/Google.Shopping.Merchant.Conversions.V1Beta.GeneratedSnippets/ConversionSourcesServiceClient.ListConversionSourcesResourceNamesAsyncSnippet.g.cs
  apis/Google.Shopping.Merchant.Conversions.V1Beta/Google.Shopping.Merchant.Conversions.V1Beta.GeneratedSnippets/ConversionSourcesServiceClient.ListConversionSourcesResourceNamesSnippet.g.cs
  apis/Google.Shopping.Merchant.Conversions.V1Beta/Google.Shopping.Merchant.Conversions.V1Beta.GeneratedSnippets/ConversionSourcesServiceClient.ListConversionSourcesSnippet.g.cs
  apis/Google.Shopping.Merchant.Conversions.V1Beta/Google.Shopping.Merchant.Conversions.V1Beta.GeneratedSnippets/ConversionSourcesServiceClient.UndeleteConversionSourceRequestObjectAsyncSnippet.g.cs
  apis/Google.Shopping.Merchant.Conversions.V1Beta/Google.Shopping.Merchant.Conversions.V1Beta.GeneratedSnippets/ConversionSourcesServiceClient.UndeleteConversionSourceRequestObjectSnippet.g.cs
  apis/Google.Shopping.Merchant.Conversions.V1Beta/Google.Shopping.Merchant.Conversions.V1Beta.GeneratedSnippets/ConversionSourcesServiceClient.UpdateConversionSourceAsyncSnippet.g.cs
  apis/Google.Shopping.Merchant.Conversions.V1Beta/Google.Shopping.Merchant.Conversions.V1Beta.GeneratedSnippets/ConversionSourcesServiceClient.UpdateConversionSourceRequestObjectAsyncSnippet.g.cs
  apis/Google.Shopping.Merchant.Conversions.V1Beta/Google.Shopping.Merchant.Conversions.V1Beta.GeneratedSnippets/ConversionSourcesServiceClient.UpdateConversionSourceRequestObjectSnippet.g.cs
  apis/Google.Shopping.Merchant.Conversions.V1Beta/Google.Shopping.Merchant.Conversions.V1Beta.GeneratedSnippets/ConversionSourcesServiceClient.UpdateConversionSourceSnippet.g.cs
  apis/Google.Shopping.Merchant.Conversions.V1Beta/Google.Shopping.Merchant.Conversions.V1Beta.GeneratedSnippets/Google.Shopping.Merchant.Conversions.V1Beta.GeneratedSnippets.csproj
  apis/Google.Shopping.Merchant.Conversions.V1Beta/Google.Shopping.Merchant.Conversions.V1Beta.GeneratedSnippets/snippet_metadata_google.shopping.merchant.conversions.v1beta.json
  apis/Google.Shopping.Merchant.Conversions.V1Beta/Google.Shopping.Merchant.Conversions.V1Beta.Snippets/ConversionSourcesServiceClientSnippets.g.cs
  apis/Google.Shopping.Merchant.Conversions.V1Beta/Google.Shopping.Merchant.Conversions.V1Beta.Snippets/Google.Shopping.Merchant.Conversions.V1Beta.Snippets.csproj
  apis/Google.Shopping.Merchant.Conversions.V1Beta/Google.Shopping.Merchant.Conversions.V1Beta.Snippets/coverage.xml
  apis/Google.Shopping.Merchant.Conversions.V1Beta/Google.Shopping.Merchant.Conversions.V1Beta.sln
  apis/Google.Shopping.Merchant.Conversions.V1Beta/Google.Shopping.Merchant.Conversions.V1Beta/ConversionSourcesServiceClient.g.cs
  apis/Google.Shopping.Merchant.Conversions.V1Beta/Google.Shopping.Merchant.Conversions.V1Beta/Conversionsources.g.cs
  apis/Google.Shopping.Merchant.Conversions.V1Beta/Google.Shopping.Merchant.Conversions.V1Beta/ConversionsourcesGrpc.g.cs
  apis/Google.Shopping.Merchant.Conversions.V1Beta/Google.Shopping.Merchant.Conversions.V1Beta/ConversionsourcesResourceNames.g.cs
  apis/Google.Shopping.Merchant.Conversions.V1Beta/Google.Shopping.Merchant.Conversions.V1Beta/Google.Shopping.Merchant.Conversions.V1Beta.csproj
  apis/Google.Shopping.Merchant.Conversions.V1Beta/Google.Shopping.Merchant.Conversions.V1Beta/PackageApiMetadata.g.cs
  apis/Google.Shopping.Merchant.Conversions.V1Beta/Google.Shopping.Merchant.Conversions.V1Beta/ServiceCollectionExtensions.g.cs
  apis/Google.Shopping.Merchant.Conversions.V1Beta/docs/history.md
  apis/Google.Shopping.Merchant.Conversions.V1Beta/docs/index.md
  apis/Google.Shopping.Merchant.Conversions.V1Beta/gapic_metadata.json
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#12625 Release Google.Cloud.Deploy.V1 version 2.15.0
  apis/Google.Cloud.Deploy.V1/Google.Cloud.Deploy.V1/Google.Cloud.Deploy.V1.csproj
  apis/Google.Cloud.Deploy.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#12624 Release Google.Apps.Chat.V1 version 1.0.0-beta02
  apis/Google.Apps.Chat.V1/Google.Apps.Chat.V1/Google.Apps.Chat.V1.csproj
  apis/Google.Apps.Chat.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#12626 Release Google.Cloud.SecretManager.V1 version 2.4.0
  apis/Google.Cloud.SecretManager.V1/Google.Cloud.SecretManager.V1/Google.Cloud.SecretManager.V1.csproj
  apis/Google.Cloud.SecretManager.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#12654 Release Google.Cloud.Config.V1 version 1.5.0
  apis/Google.Cloud.Config.V1/Google.Cloud.Config.V1/Google.Cloud.Config.V1.csproj
  apis/Google.Cloud.Config.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#12656 Release Google.Cloud.Monitoring.V3 version 3.9.0
  apis/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3/Google.Cloud.Monitoring.V3.csproj
  apis/Google.Cloud.Monitoring.V3/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#12658 Release Google.Cloud.RecaptchaEnterprise.V1Beta1 version 2.0.0-beta07
  apis/Google.Cloud.RecaptchaEnterprise.V1Beta1/Google.Cloud.RecaptchaEnterprise.V1Beta1/Google.Cloud.RecaptchaEnterprise.V1Beta1.csproj
  apis/Google.Cloud.RecaptchaEnterprise.V1Beta1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact

#12657 Release Google.Cloud.RecaptchaEnterprise.V1 version 2.13.0
  apis/Google.Cloud.RecaptchaEnterprise.V1/Google.Cloud.RecaptchaEnterprise.V1/Google.Cloud.RecaptchaEnterprise.V1.csproj
  apis/Google.Cloud.RecaptchaEnterprise.V1/docs/history.md
  apis/apis.json
Labels: autorelease: pending, automerge: exact
