Repository googleapis/google-cloud-dotnet, pull requests merged in 2025-03, with the labels that each got.

#14380 Release Google.Maps.Places.V1 version 1.0.0-beta13
  apis/Google.Maps.Places.V1/Google.Maps.Places.V1/Google.Maps.Places.V1.csproj
  apis/Google.Maps.Places.V1/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14373 Release Google.Cloud.BigQuery.Reservation.V1 version 2.7.0
  apis/Google.Cloud.BigQuery.Reservation.V1/Google.Cloud.BigQuery.Reservation.V1/Google.Cloud.BigQuery.Reservation.V1.csproj
  apis/Google.Cloud.BigQuery.Reservation.V1/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14376 Release Google.Cloud.Dialogflow.Cx.V3 version 2.22.0
  apis/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3/Google.Cloud.Dialogflow.Cx.V3.csproj
  apis/Google.Cloud.Dialogflow.Cx.V3/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14378 Release Google.Maps.FleetEngine.Delivery.V1 version 2.2.0
  apis/Google.Maps.FleetEngine.Delivery.V1/Google.Maps.FleetEngine.Delivery.V1/Google.Maps.FleetEngine.Delivery.V1.csproj
  apis/Google.Maps.FleetEngine.Delivery.V1/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14370 Release Google.Apps.Meet.V2Beta version 1.0.0-beta07
  apis/Google.Apps.Meet.V2Beta/Google.Apps.Meet.V2Beta/Google.Apps.Meet.V2Beta.csproj
  apis/Google.Apps.Meet.V2Beta/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14374 Release Google.Cloud.Bigtable.Admin.V2 version 3.23.0
  apis/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2.csproj
  apis/Google.Cloud.Bigtable.Admin.V2/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14371 Release Google.Cloud.AIPlatform.V1 version 3.20.0
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1.csproj
  apis/Google.Cloud.AIPlatform.V1/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14375 Release Google.Cloud.Dataform.V1Beta1 version 1.0.0-beta08
  apis/Google.Cloud.Dataform.V1Beta1/Google.Cloud.Dataform.V1Beta1/Google.Cloud.Dataform.V1Beta1.csproj
  apis/Google.Cloud.Dataform.V1Beta1/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14388 Release Google.Cloud.AIPlatform.V1Beta1 version 1.0.0-beta20
  apis/Google.Cloud.AIPlatform.V1Beta1/Google.Cloud.AIPlatform.V1Beta1/Google.Cloud.AIPlatform.V1Beta1.csproj
  apis/Google.Cloud.AIPlatform.V1Beta1/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14387 Release Google.Cloud.AIPlatform.V1 version 3.21.0
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1.csproj
  apis/Google.Cloud.AIPlatform.V1/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, allow breaking changes

#13894 feat(storage): support bucket restore in soft delete phase 2
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.IntegrationTests/GetBucketTest.cs
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.IntegrationTests/ListBucketsTest.cs
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.IntegrationTests/RestoreBucketTest.cs
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.Tests/GetBucketOptionsTest.cs
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.Tests/ListBucketsOptionsTest.cs
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.Tests/RestoreBucketOptionsTest.cs
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1/GetBucketOptions.cs
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.csproj
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1/ListBucketsOptions.cs
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1/RestoreBucketOptions.cs
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1/StorageClient.RestoreBucket.cs
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1/StorageClientImpl.RestoreBucket.cs
  generator-input/apis.json
Labels: api: storage

#14421 Release Google.Cloud.Storage.V1 version 4.11.0
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.csproj
  apis/Google.Cloud.Storage.V1/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14415 Release Google.Cloud.Bigtable.V2 version 3.16.0
  apis/Google.Cloud.Bigtable.V2/Google.Cloud.Bigtable.V2/Google.Cloud.Bigtable.V2.csproj
  apis/Google.Cloud.Bigtable.V2/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14419 Release Google.Cloud.Filestore.V1 version 2.7.0
  apis/Google.Cloud.Filestore.V1/Google.Cloud.Filestore.V1/Google.Cloud.Filestore.V1.csproj
  apis/Google.Cloud.Filestore.V1/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14414 Release Google.Cloud.Bigtable.Admin.V2 version 3.24.0
  apis/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2.csproj
  apis/Google.Cloud.Bigtable.Admin.V2/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14420 Release Google.Cloud.PubSub.V1 version 3.22.0
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1.csproj
  apis/Google.Cloud.PubSub.V1/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14411 Release Google.Cloud.AIPlatform.V1 version 3.22.0
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1.csproj
  apis/Google.Cloud.AIPlatform.V1/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14412 Release Google.Cloud.AIPlatform.V1Beta1 version 1.0.0-beta21
  apis/Google.Cloud.AIPlatform.V1Beta1/Google.Cloud.AIPlatform.V1Beta1/Google.Cloud.AIPlatform.V1Beta1.csproj
  apis/Google.Cloud.AIPlatform.V1Beta1/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14409 Release Google.Analytics.Admin.V1Alpha version 2.0.0-alpha22
  apis/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha.csproj
  apis/Google.Analytics.Admin.V1Alpha/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14418 Release Google.Cloud.Dialogflow.V2Beta1 version 1.0.0-beta23
  apis/Google.Cloud.Dialogflow.V2Beta1/Google.Cloud.Dialogflow.V2Beta1/Google.Cloud.Dialogflow.V2Beta1.csproj
  apis/Google.Cloud.Dialogflow.V2Beta1/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14430 Release Google.Cloud.Audit version 2.5.0
  apis/Google.Cloud.Audit/Google.Cloud.Audit/Google.Cloud.Audit.csproj
  apis/Google.Cloud.Audit/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14440 Release Firestore libraries version 3.10.0
  apis/Google.Cloud.Firestore.V1/Google.Cloud.Firestore.V1/Google.Cloud.Firestore.V1.csproj
  apis/Google.Cloud.Firestore.V1/docs/history.md
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore.IntegrationTests/Google.Cloud.Firestore.IntegrationTests.csproj
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore.Snippets/Google.Cloud.Firestore.Snippets.csproj
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore.Tests/Google.Cloud.Firestore.Tests.csproj
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore.sln
  apis/Google.Cloud.Firestore/Google.Cloud.Firestore/Google.Cloud.Firestore.csproj
  apis/Google.Cloud.Firestore/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14450 Release Google.Cloud.PubSub.V1 version 3.23.0
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1.csproj
  apis/Google.Cloud.PubSub.V1/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14473 Release Google.Shopping.Merchant.Products.V1Beta version 1.0.0-beta03
  apis/Google.Shopping.Merchant.Products.V1Beta/Google.Shopping.Merchant.Products.V1Beta/Google.Shopping.Merchant.Products.V1Beta.csproj
  apis/Google.Shopping.Merchant.Products.V1Beta/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14471 Release Google.Shopping.Merchant.Accounts.V1Beta version 1.0.0-beta05
  apis/Google.Shopping.Merchant.Accounts.V1Beta/Google.Shopping.Merchant.Accounts.V1Beta/Google.Shopping.Merchant.Accounts.V1Beta.csproj
  apis/Google.Shopping.Merchant.Accounts.V1Beta/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14467 Release Google.Cloud.OracleDatabase.V1 version 1.2.0
  apis/Google.Cloud.OracleDatabase.V1/Google.Cloud.OracleDatabase.V1/Google.Cloud.OracleDatabase.V1.csproj
  apis/Google.Cloud.OracleDatabase.V1/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14468 Release Google.Cloud.RecaptchaEnterprise.V1 version 2.18.0
  apis/Google.Cloud.RecaptchaEnterprise.V1/Google.Cloud.RecaptchaEnterprise.V1/Google.Cloud.RecaptchaEnterprise.V1.csproj
  apis/Google.Cloud.RecaptchaEnterprise.V1/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending

#14463 Release Google.Cloud.Compute.V1 version 3.6.0
  apis/Google.Cloud.Compute.V1/Google.Cloud.Compute.V1/Google.Cloud.Compute.V1.csproj
  apis/Google.Cloud.Compute.V1/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending

#14464 Release Google.Cloud.DataCatalog.V1 version 2.15.0
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1.csproj
  apis/Google.Cloud.DataCatalog.V1/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14459 Release Google.Cloud.AIPlatform.V1 version 3.23.0
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1.csproj
  apis/Google.Cloud.AIPlatform.V1/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14460 Release Google.Cloud.AIPlatform.V1Beta1 version 1.0.0-beta22
  apis/Google.Cloud.AIPlatform.V1Beta1/Google.Cloud.AIPlatform.V1Beta1/Google.Cloud.AIPlatform.V1Beta1.csproj
  apis/Google.Cloud.AIPlatform.V1Beta1/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14470 Release Google.Maps.Places.V1 version 1.0.0-beta14
  apis/Google.Maps.Places.V1/Google.Maps.Places.V1/Google.Maps.Places.V1.csproj
  apis/Google.Maps.Places.V1/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14466 Release Google.Cloud.ManagedKafka.V1 version 1.0.0-beta04
  apis/Google.Cloud.ManagedKafka.V1/Google.Cloud.ManagedKafka.V1/Google.Cloud.ManagedKafka.V1.csproj
  apis/Google.Cloud.ManagedKafka.V1/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14462 Release Google.Cloud.Bigtable.V2 version 3.17.0
  apis/Google.Cloud.Bigtable.V2/Google.Cloud.Bigtable.V2/Google.Cloud.Bigtable.V2.csproj
  apis/Google.Cloud.Bigtable.V2/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14511 Release Google.Cloud.DocumentAI.V1Beta3 version 2.0.0-beta24
  apis/Google.Cloud.DocumentAI.V1Beta3/Google.Cloud.DocumentAI.V1Beta3/Google.Cloud.DocumentAI.V1Beta3.csproj
  apis/Google.Cloud.DocumentAI.V1Beta3/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14510 Release Google.Cloud.Dlp.V2 version 4.17.0
  apis/Google.Cloud.Dlp.V2/Google.Cloud.Dlp.V2/Google.Cloud.Dlp.V2.csproj
  apis/Google.Cloud.Dlp.V2/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14513 Release Google.Cloud.NetworkConnectivity.V1 version 2.10.0
  apis/Google.Cloud.NetworkConnectivity.V1/Google.Cloud.NetworkConnectivity.V1/Google.Cloud.NetworkConnectivity.V1.csproj
  apis/Google.Cloud.NetworkConnectivity.V1/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14506 Release Google.Cloud.AIPlatform.V1 version 3.24.0
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1.csproj
  apis/Google.Cloud.AIPlatform.V1/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14512 Release Google.Cloud.ManagedKafka.V1 version 1.0.0-beta05
  apis/Google.Cloud.ManagedKafka.V1/Google.Cloud.ManagedKafka.V1/Google.Cloud.ManagedKafka.V1.csproj
  apis/Google.Cloud.ManagedKafka.V1/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14508 Release Google.Cloud.AlloyDb.V1Beta version 1.0.0-beta10
  apis/Google.Cloud.AlloyDb.V1Beta/Google.Cloud.AlloyDb.V1Beta/Google.Cloud.AlloyDb.V1Beta.csproj
  apis/Google.Cloud.AlloyDb.V1Beta/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14507 Release Google.Cloud.AIPlatform.V1Beta1 version 1.0.0-beta23
  apis/Google.Cloud.AIPlatform.V1Beta1/Google.Cloud.AIPlatform.V1Beta1/Google.Cloud.AIPlatform.V1Beta1.csproj
  apis/Google.Cloud.AIPlatform.V1Beta1/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14509 Release Google.Cloud.Compute.V1 version 3.7.0
  apis/Google.Cloud.Compute.V1/Google.Cloud.Compute.V1/Google.Cloud.Compute.V1.csproj
  apis/Google.Cloud.Compute.V1/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact, allow breaking changes

#14542 Release Google.Cloud.AIPlatform.V1 version 3.25.0
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1.csproj
  apis/Google.Cloud.AIPlatform.V1/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14546 Release Google.Cloud.Compute.V1 version 3.8.0
  apis/Google.Cloud.Compute.V1/Google.Cloud.Compute.V1/Google.Cloud.Compute.V1.csproj
  apis/Google.Cloud.Compute.V1/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14547 Release Google.Cloud.Datastream.V1 version 2.10.0
  apis/Google.Cloud.Datastream.V1/Google.Cloud.Datastream.V1/Google.Cloud.Datastream.V1.csproj
  apis/Google.Cloud.Datastream.V1/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14549 Release Google.Cloud.PubSub.V1 version 3.24.0
  apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1.csproj
  apis/Google.Cloud.PubSub.V1/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending

#14544 Release Google.Cloud.AppHub.V1 version 1.1.0
  apis/Google.Cloud.AppHub.V1/Google.Cloud.AppHub.V1/Google.Cloud.AppHub.V1.csproj
  apis/Google.Cloud.AppHub.V1/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14545 Release Google.Cloud.BigQuery.AnalyticsHub.V1 version 1.8.0
  apis/Google.Cloud.BigQuery.AnalyticsHub.V1/Google.Cloud.BigQuery.AnalyticsHub.V1/Google.Cloud.BigQuery.AnalyticsHub.V1.csproj
  apis/Google.Cloud.BigQuery.AnalyticsHub.V1/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact
