Repository googleapis/google-cloud-dotnet, pull requests merged in 2025-05, with the labels that each got.

#14694 Release Google.Cloud.Lustre.V1 version 1.0.0-beta01
  README.md
  apis/Google.Cloud.Lustre.V1/.repo-metadata.json
  apis/Google.Cloud.Lustre.V1/Google.Cloud.Lustre.V1/Google.Cloud.Lustre.V1.csproj
  apis/Google.Cloud.Lustre.V1/docs/history.md
  generator-input/apis.json
  generator-input/pipeline-state.json
Labels: autorelease: pending, automerge: exact

#14744 tests: Improve some storage tests and samples
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.Snippets/StorageClientSnippets.cs
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.Snippets/UrlSignerSnippets.cs
Labels: samples

#14794 fix(BigTable): ReadRow/s respects rowsLimit and retries on Aborted exception
  apis/Google.Cloud.Bigtable.V2/Google.Cloud.Bigtable.V2.ConformanceTests/bigtable-conformance.sh
  apis/Google.Cloud.Bigtable.V2/Google.Cloud.Bigtable.V2/BigtableClientPartial.cs
  apis/Google.Cloud.Bigtable.V2/Google.Cloud.Bigtable.V2/BigtableReadRowsRequestManager.cs
  apis/Google.Cloud.Bigtable.V2/Google.Cloud.Bigtable.V2/BigtableServiceApiClientPartial.cs
  apis/Google.Cloud.Bigtable.V2/Google.Cloud.Bigtable.V2/RowAsyncEnumerator.cs
Labels: api: bigtable
