Repository googleapis/google-cloud-dotnet, pull requests merged in 2025-04, with the labels that each got.

#14571 Release Container Analysis libraries version 3.8.0
  .github/renovate.json
  README.md
  apis/Google.Cloud.DevTools.ContainerAnalysis.V1/Google.Cloud.DevTools.ContainerAnalysis.V1/Google.Cloud.DevTools.ContainerAnalysis.V1.csproj
  apis/Google.Cloud.DevTools.ContainerAnalysis.V1/docs/history.md
  apis/Grafeas.V1/Grafeas.V1/Grafeas.V1.csproj
  apis/Grafeas.V1/docs/history.md
  generator-input/apis.json
  generator-input/pipeline-state.json
Labels: autorelease: pending, allow breaking changes

#14627 Release diagnostics libraries version 5.3.0
  apis/Google.Cloud.Diagnostics.AspNetCore3/Google.Cloud.Diagnostics.AspNetCore3/Google.Cloud.Diagnostics.AspNetCore3.csproj
  apis/Google.Cloud.Diagnostics.AspNetCore3/docs/history.md
  apis/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common.csproj
  apis/Google.Cloud.Diagnostics.Common/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14623 Release Google.Cloud.WebRisk.V1 version 2.7.0
  apis/Google.Cloud.WebRisk.V1/Google.Cloud.WebRisk.V1/Google.Cloud.WebRisk.V1.csproj
  apis/Google.Cloud.WebRisk.V1/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14626 Release Spanner libraries version 5.0.0-beta06
  apis/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1.csproj
  apis/Google.Cloud.Spanner.Admin.Instance.V1/Google.Cloud.Spanner.Admin.Instance.V1/Google.Cloud.Spanner.Admin.Instance.V1.csproj
  apis/Google.Cloud.Spanner.Common.V1/Google.Cloud.Spanner.Common.V1/Google.Cloud.Spanner.Common.V1.csproj
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.csproj
  apis/Google.Cloud.Spanner.Data/docs/history.md
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1.csproj
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14617 Release Google.Cloud.Iap.V1 version 2.8.0
  apis/Google.Cloud.Iap.V1/Google.Cloud.Iap.V1/Google.Cloud.Iap.V1.csproj
  apis/Google.Cloud.Iap.V1/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14620 Release Google.Cloud.Parallelstore.V1Beta version 1.0.0-beta08
  apis/Google.Cloud.Parallelstore.V1Beta/Google.Cloud.Parallelstore.V1Beta/Google.Cloud.Parallelstore.V1Beta.csproj
  apis/Google.Cloud.Parallelstore.V1Beta/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14622 Release Google.Cloud.TextToSpeech.V1 version 3.11.0
  apis/Google.Cloud.TextToSpeech.V1/Google.Cloud.TextToSpeech.V1/Google.Cloud.TextToSpeech.V1.csproj
  apis/Google.Cloud.TextToSpeech.V1/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14612 Release Google.Cloud.AIPlatform.V1Beta1 version 1.0.0-beta25
  apis/Google.Cloud.AIPlatform.V1Beta1/Google.Cloud.AIPlatform.V1Beta1/Google.Cloud.AIPlatform.V1Beta1.csproj
  apis/Google.Cloud.AIPlatform.V1Beta1/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14616 Release Google.Cloud.Firestore.Admin.V1 version 3.13.0
  apis/Google.Cloud.Firestore.Admin.V1/Google.Cloud.Firestore.Admin.V1/Google.Cloud.Firestore.Admin.V1.csproj
  apis/Google.Cloud.Firestore.Admin.V1/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14621 Release Google.Cloud.Speech.V1P1Beta1 version 3.0.0-beta09
  apis/Google.Cloud.Speech.V1P1Beta1/Google.Cloud.Speech.V1P1Beta1/Google.Cloud.Speech.V1P1Beta1.csproj
  apis/Google.Cloud.Speech.V1P1Beta1/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14619 Release Google.Cloud.OracleDatabase.V1 version 1.3.0
  apis/Google.Cloud.OracleDatabase.V1/Google.Cloud.OracleDatabase.V1/Google.Cloud.OracleDatabase.V1.csproj
  apis/Google.Cloud.OracleDatabase.V1/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14625 Release Google.Shopping.Merchant.Products.V1Beta version 1.0.0-beta04
  apis/Google.Shopping.Merchant.Products.V1Beta/Google.Shopping.Merchant.Products.V1Beta/Google.Shopping.Merchant.Products.V1Beta.csproj
  apis/Google.Shopping.Merchant.Products.V1Beta/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14613 Release Google.Cloud.ArtifactRegistry.V1 version 2.10.0
  apis/Google.Cloud.ArtifactRegistry.V1/Google.Cloud.ArtifactRegistry.V1/Google.Cloud.ArtifactRegistry.V1.csproj
  apis/Google.Cloud.ArtifactRegistry.V1/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14615 Release Google.Cloud.Deploy.V1 version 3.5.0
  apis/Google.Cloud.Deploy.V1/Google.Cloud.Deploy.V1/Google.Cloud.Deploy.V1.csproj
  apis/Google.Cloud.Deploy.V1/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14624 Release Google.Shopping.Css.V1 version 1.0.0-beta07
  apis/Google.Shopping.Css.V1/Google.Shopping.Css.V1/Google.Shopping.Css.V1.csproj
  apis/Google.Shopping.Css.V1/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14631 Release Spanner libraries version 5.0.0
  apis/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1/Google.Cloud.Spanner.Admin.Database.V1.csproj
  apis/Google.Cloud.Spanner.Admin.Instance.V1/Google.Cloud.Spanner.Admin.Instance.V1/Google.Cloud.Spanner.Admin.Instance.V1.csproj
  apis/Google.Cloud.Spanner.Common.V1/Google.Cloud.Spanner.Common.V1/Google.Cloud.Spanner.Common.V1.csproj
  apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data.csproj
  apis/Google.Cloud.Spanner.Data/docs/history.md
  apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1.csproj
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact, allow breaking changes

#14640 Release Google.Shopping.Merchant.Lfp.V1Beta version 1.0.0-beta03
  apis/Google.Shopping.Merchant.Lfp.V1Beta/Google.Shopping.Merchant.Lfp.V1Beta/Google.Shopping.Merchant.Lfp.V1Beta.csproj
  apis/Google.Shopping.Merchant.Lfp.V1Beta/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14648 Release Google.Cloud.GkeBackup.V1 version 2.7.0
  apis/Google.Cloud.GkeBackup.V1/Google.Cloud.GkeBackup.V1/Google.Cloud.GkeBackup.V1.csproj
  apis/Google.Cloud.GkeBackup.V1/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14647 Release Google.Cloud.GdcHardwareManagement.V1Alpha version 1.0.0-alpha05
  apis/Google.Cloud.GdcHardwareManagement.V1Alpha/Google.Cloud.GdcHardwareManagement.V1Alpha/Google.Cloud.GdcHardwareManagement.V1Alpha.csproj
  apis/Google.Cloud.GdcHardwareManagement.V1Alpha/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14645 Release Google.Cloud.DataCatalog.V1 version 2.16.0
  apis/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1/Google.Cloud.DataCatalog.V1.csproj
  apis/Google.Cloud.DataCatalog.V1/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14644 Release Google.Cloud.Compute.V1 version 3.9.0
  apis/Google.Cloud.Compute.V1/Google.Cloud.Compute.V1/Google.Cloud.Compute.V1.csproj
  apis/Google.Cloud.Compute.V1/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14643 Release Google.Analytics.Admin.V1Alpha version 2.0.0-alpha23
  apis/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha/Google.Analytics.Admin.V1Alpha.csproj
  apis/Google.Analytics.Admin.V1Alpha/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14646 Release Google.Cloud.DocumentAI.V1 version 3.20.0
  apis/Google.Cloud.DocumentAI.V1/Google.Cloud.DocumentAI.V1/Google.Cloud.DocumentAI.V1.csproj
  apis/Google.Cloud.DocumentAI.V1/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14654 Release Google.Cloud.FinancialServices.V1 version 1.0.0-beta01
  README.md
  apis/Google.Cloud.FinancialServices.V1/.repo-metadata.json
  apis/Google.Cloud.FinancialServices.V1/Google.Cloud.FinancialServices.V1/Google.Cloud.FinancialServices.V1.csproj
  apis/Google.Cloud.FinancialServices.V1/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14653 Release Google.Cloud.DeviceStreaming.V1 version 1.0.0-beta01
  README.md
  apis/Google.Cloud.DeviceStreaming.V1/.repo-metadata.json
  apis/Google.Cloud.DeviceStreaming.V1/Google.Cloud.DeviceStreaming.V1/Google.Cloud.DeviceStreaming.V1.csproj
  apis/Google.Cloud.DeviceStreaming.V1/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14656 Release Google.Maps.AerialView.V1 version 1.0.0-beta01
  README.md
  apis/Google.Maps.AerialView.V1/.repo-metadata.json
  apis/Google.Maps.AerialView.V1/Google.Maps.AerialView.V1/Google.Maps.AerialView.V1.csproj
  apis/Google.Maps.AerialView.V1/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14652 Release Google.Cloud.Chronicle.V1 version 1.0.0-beta01
  README.md
  apis/Google.Cloud.Chronicle.V1/.repo-metadata.json
  apis/Google.Cloud.Chronicle.V1/Google.Cloud.Chronicle.V1/Google.Cloud.Chronicle.V1.csproj
  apis/Google.Cloud.Chronicle.V1/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14657 Release Google.Cloud.Storage.V1 version 4.12.0
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.csproj
  apis/Google.Cloud.Storage.V1/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14655 Release Google.Cloud.StorageBatchOperations.V1 version 1.0.0-beta01
  README.md
  apis/Google.Cloud.StorageBatchOperations.V1/.repo-metadata.json
  apis/Google.Cloud.StorageBatchOperations.V1/Google.Cloud.StorageBatchOperations.V1/Google.Cloud.StorageBatchOperations.V1.csproj
  apis/Google.Cloud.StorageBatchOperations.V1/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14662 Release Google.Cloud.DeveloperConnect.V1 version 1.0.0-beta01
  README.md
  apis/Google.Cloud.DeveloperConnect.V1/.repo-metadata.json
  apis/Google.Cloud.DeveloperConnect.V1/Google.Cloud.DeveloperConnect.V1/Google.Cloud.DeveloperConnect.V1.csproj
  apis/Google.Cloud.DeveloperConnect.V1/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14670 Release Google.Cloud.Storage.V1 version 4.13.0
  apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.csproj
  apis/Google.Cloud.Storage.V1/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14676 Release Google.Cloud.Asset.V1 version 3.13.0
  apis/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1/Google.Cloud.Asset.V1.csproj
  apis/Google.Cloud.Asset.V1/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14677 Release Google.Cloud.Bigtable.Admin.V2 version 3.26.0
  apis/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2/Google.Cloud.Bigtable.Admin.V2.csproj
  apis/Google.Cloud.Bigtable.Admin.V2/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14678 Release Google.Cloud.DocumentAI.V1Beta3 version 2.0.0-beta25
  apis/Google.Cloud.DocumentAI.V1Beta3/Google.Cloud.DocumentAI.V1Beta3/Google.Cloud.DocumentAI.V1Beta3.csproj
  apis/Google.Cloud.DocumentAI.V1Beta3/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14683 Release Google.Cloud.Tools.DocUploader version 0.2.3
  tools/Google.Cloud.Tools.DocUploader/Google.Cloud.Tools.DocUploader.csproj
Labels: autorelease: pending

#14685 Release Google.Cloud.AIPlatform.V1 version 3.26.0
  apis/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1/Google.Cloud.AIPlatform.V1.csproj
  apis/Google.Cloud.AIPlatform.V1/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending, automerge: exact

#14688 Release Google.Cloud.DocumentAI.V1Beta3 version 2.0.0-beta26
  apis/Google.Cloud.DocumentAI.V1Beta3/Google.Cloud.DocumentAI.V1Beta3/Google.Cloud.DocumentAI.V1Beta3.csproj
  apis/Google.Cloud.DocumentAI.V1Beta3/docs/history.md
  generator-input/apis.json
Labels: autorelease: pending
